### ISSUE TITLE
Negative zeros are not handled correctly when linking from JS

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#1011]
See tests excluded with the "no-neg-zero" tag (when running through `toolsJS`).

**Comment by timotheecour** [comment]
@gzm0
Object.is seems better, refs https://github.com/nim-lang/Nim/pull/16505/files#r549826330

**Comment by gzm0** [comment]
Thank you for the suggestion. But the IR project compiles both to JS and the JVM, so `Object.is` isn't available.
