### ISSUE TITLE
String.split(x: Array[Char]) produces bad regexes

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#105]
Just like `split(x: Char)` (see #65), `StringLike` relies on the `\Q`, `\E` escapes for Regex creation. We now have to deal with the following pattern:

```
[\Q<char>\E\Q<char>\E<etc>]
```

This produces regexes such as:

```
[\Q-\E]
```

Which then cause an exception in the JavaScript regex matcher.

@sjrd Should we handle this as a hack just like #65, knowing that this is substantially more complex?

**Comment by sjrd** [comment]
This would be fixed by #4455 as well.

(This means the Semantics page on the website should be updated.)
