### ISSUE TITLE
Turn all warnings in PrepJSInterop into errors

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#1111]
See #130

**Comment by gzm0** [comment]
I want to do this, once it is time :)

**Comment by sjrd** [comment]
OK ^^

**Comment by sjrd** [comment]
Generalizing this to include all warnings generated by `PrepJSInterop` into errors.

**Comment by sjrd** [comment]
@gzm0 

> I want to do this, once it is time :)

It is time :)
