### ISSUE TITLE
Obfuscation of class names

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#1113]
The output of `fullOptJS` is well minimised and obfuscated with the exception of all the class names.  The plain readability (and thus easier backward-engineerability) is a significant concern. Addressing this would bring the size down too, looking at a bit of code I'm working on, 40k of my 557k file (7.3%) appears to be just class names.

Are there any plans or ideas in the pipeline around this?

**Comment by japgolly** [comment]
AWesome! Thanks again! This will provide an important, extra little piece of mind when closed-source projects go to prod.

**Comment by strelec** [comment]
It appears that case classes and case objects still keep their name in the final JS file.

**Comment by sjrd** [comment]
Case classes and case objects have a specified `.toString()` which includes their unqualified name, yes. That's part of Scala's specified semantics and enforced by the scalac compiler. There is nothing Scala.js can do about those (nor do I think we *should* do anything).
