### ISSUE TITLE
Contributor License Agreement (CLA)

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#1139]
Dear Scala.js contributors,

I should have taken care of this a long time ago: a contributor license agreement (CLA) for Scala.js.
So far, I have been accepting contributions to the Scala.js repository without care for legal issues. I'd like to fix this, which means using a CLA.
As many other open source software, from now on, I will only accept pull requests from contributors who have signed the CLA.

But what CLA? It turns out that the [Scala CLA](http://typesafe.com/contribute/cla/scala/current) applies to "any of the products owned or managed by EPFL" (in 1. Definitions). Well, Scala.js is part of the products owned and managed by EPFL. Therefore, we'll simply use the Scala CLA as the Scala.js CLA.

**Comment by gzm0** [comment]
Assigning to v0.6.0-M1 since it was around that time. Notably:

```shell
$ git tag --contains $(git rev-list --after="2014-10-19" master | tail -n 1)
v0.6.0
v0.6.0-M1
v0.6.0-M2
v0.6.0-M3
v0.6.0-RC1
v0.6.0-RC2
v0.6.1
v0.6.10
v0.6.11
v0.6.12
v0.6.2
v0.6.3
v0.6.4
v0.6.5
v0.6.5-scala-2.12.0-M3
v0.6.6
v0.6.7
v0.6.8
v0.6.9
```
