### ISSUE TITLE
java.nio

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#1256]
Scala.js is missing an implementation for `java.nio`.

I have a draft PR for everything in the public API for `java.nio` except `MappedByteBuffer` and `java.nio.channels`. Not realising how big it was, I ended up spending hours and hours on this tiring thing. It's a direct port from Harmony (minus the stuff in the package object).

https://github.com/japgolly/scala-js/commit/bf5e60097bfb2d739d5b4bf76016c0348cd18477

Some notes and questions:
* Typed arrays are needed. According to http://caniuse.com/#feat=typedarrays everything except IE8 and IE9 support typed arrays. Problem?
* I added `doubleToRawLongBits` and similar, but in the `java.nio` package object for now. Should I move to `Double` and `Float`?
* What do you think? Suggestions? What else (if anything) would be needed to get this over the line?

**Comment by japgolly** [comment]
If someone in the community could carry this on over the line that'd be great.

**Comment by sjrd** [comment]
So, for the record, I've been working on this. WiP is in #1495. One of the students at EPFL will need this for his project this semester, so I'm pushing it over. Note that it's a reimplementation from scratch, using the capabilities of the Scala.js optimizer to keep it DRY. So it doesn't look at all like Harmony's source code.
