### ISSUE TITLE
Take advantage of all the new methods in Math in ES6

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#1275]
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math
There are actual native methods for most of the methods in `java.lang.Math`, now :-p

There is also `Math.clz32` which can be used for `java.lang.Integer.numberOfLeadingZeros`. In turn, `numberOfTrailingZeros` can be implemented efficiently in terms of the former.

The mappings should be done with intrinsics, with snapshots of all these methods || polyfills taken at the start of scalajsenv.js.

**Comment by sjrd** [comment]
Once we have this, we can reimplement more efficiently `Random.nextInt(n)` in the power-of-2 case. Currently it is:
```scala
((n * next(31).toLong) >> 31).toInt
```
which is meant to return the `x = log2(n)` *higher* order bits out of the 31 bits asked to `next()`. But this uses Longs.

For a power of 2, `x` is also equal to `ctz(n)` the number of trailing zeros. For a power of two, `ctz(n) == 32 - 1 - clz(n) == 31 - x`. And to return `x` higher order bits out of `r = next(31)`, we can return `r >> (31 - x)`. So we can return `r >> clz(n)`. :-)

Note that `clz` has a quite inefficient polyfill. (See current implementation of [numberOfLeadingZeros](https://github.com/scala-js/scala-js/blob/v0.6.1/javalanglib/src/main/scala/java/lang/Integer.scala#L123-L132). I think it would still be faster than using the Long operations, though. But we can also have a faster implementation even in that case.

We need to compute `r >> (31 - x)`, which is:
`r >> (31 - x) == r / 2^(31 - x)`
because `x` is an integer `0 <= x <= 31`, this is also equal to:
`r / (2^31 / 2^x)`
But `2^x == n`, so:
`r / (2^31 / n)`
Since `2^31` is a constant, this is effectively two integer divisions, which is much slower than a shift and a native `clz`, but much faster than the polyfill of `clz`.

So ideally `Random` should detect whether `clz` is native, and do:
```scala
if (clzIsNative) r >> clz(n)
else r / ((1 << 31) / n)
```
^^

**Comment by mkotsbak** [comment]
https://github.com/scala-js/scala-js/pull/1946 has implemented clz32, but there are more functions missing, e.g. cbrt().

**Comment by mkotsbak** [comment]
This issue should be closed now after merge of PR https://github.com/scala-js/scala-js/pull/2919.

If there are other methods that needs to be optimized or there are more added in future versions of JS I suggest opening new issues.

**Comment by sjrd** [comment]
Indeed. It's annoying that GitHub does not auto-closes issues for PRs merged in non-master branches ...
