### ISSUE TITLE
Date.parse should return a Double, not an Int

### ISSUE THREAD

**Issue by michelschinz** [scala-js/scala-js#1324]
Hi,
In `library/src/main/scala/scala/scalajs/js/Date.scala`, the `parse` method of the `Date` object is declared as returning an `Int`. This should be changed to `Double`.

**Comment by matthughes** [comment]
@michelschinz  Out of curiosity, why Double and not Long?

**Comment by sjrd** [comment]
Because `Long` is an [opaque type](http://stackoverflow.com/questions/27821841/working-with-opaque-types-char-and-long): it doesn't map to any JavaScript type.

**Comment by michelschinz** [comment]
...and because `parse` returns `NaN` in case of error.

**Comment by sjrd** [comment]
Oh, I didn't even know that ^^
