### ISSUE TITLE
Add a way to export a top-level method/value

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#1381]
Some APIs (at least the Google maps API) need the name of a callback function as a get parameter. They apparently do not allow calling a method to get the callback (see [SO Post](http://stackoverflow.com/questions/27440235/using-scala-js-method-as-callback)).

This is a problem for Scala.js interop, since it basically requires adding a tiny bit of JS wrapper code or abusing a module initializer.

**Comment by nafg** [comment]
What happens if you JSExport a package object and a method in it?
