### ISSUE TITLE
js.Dynamic <: scala.Dynamic causes unsoundness in the IR

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#1385]
Since `js.Dynamic <: scala.Dynamic`, it is possible to put any value in a `scala.Dynamic` by casting it to a `js.Dynamic`, and then upcasting it `scala.Dynamic`. Therefore, `scala.Dynamic` should be typed as `AnyType` in the IR, and be handled accordingly (desugar to helpers, prevent `isInstanceOf[scala.Dynamic]`).

**Comment by gzm0** [comment]
Cross-refing the instance where somebody actually hit this: https://stackoverflow.com/questions/66163125/scalajs-fulllinkjs-errors
