### ISSUE TITLE
SimpleDateFormat

### ISSUE THREAD

**Issue by antonkulaga** [scala-js/scala-js#1429]
It would be nice to have working SimpleDateFormat

**Comment by khronnuz** [comment]
To implement `SimpleDateFormat` according to docs it will also require implementing other classes from `java.text` such as `Format`, `DateFormat` and helper classes such as `FieldPosition`, `ParserPosition`, `AttributedCharacterIterator`, etc.

I am working on this and will update here as I have a working version.

**Comment by sjrd** [comment]
There seems to be some support for this in [scala-java-locales](https://github.com/cquiroz/scala-java-locales).

**Comment by andreaTP** [comment]
Just for future reference that is only a partial implementation and not a full one.
