### ISSUE TITLE
Improve stack traces

### ISSUE THREAD

**Issue by tindzk** [scala-js/scala-js#1448]
In the stack trace there is a spare ``ScalaJS.c.sjsr_AnonFunction1.apply__O__O`` entry for each anonymous function call. I find that it considerably reduces the readability as seen here:

![stacktrace](https://cloud.githubusercontent.com/assets/196819/5702567/f8c75734-9a5b-11e4-9916-4090e8781b27.png)

I had a look at the source which explicitly states that the class should get inlined anyway. If these entries appear in the stack trace, does this mean that there is a run-time overhead?

The stack traces make use of serialised identifiers. Is there a way to format these in development releases?

**Comment by sjrd** [comment]
We can't format the identifiers in dev releases. It should be the job of the debugger to find the original names in the source maps (which we emit), but currently no debugger reads the original names data.

The `AnonFunctionN`s are indeed an overhead if they appear in the stack trace. Maybe someday we'll manage to get rid of them with a (much) smarter optimizer (I have ideas, but it'll be a considerable effort to implement those ideas).

We can't really omit them from the stack trace, except by deliberately amending the stack trace we reverse engineer in [`StackTrace.scala`](https://github.com/scala-js/scala-js/blob/master/library/src/main/scala/scala/scalajs/runtime/StackTrace.scala). But I'm not sure that's a good idea.
