### ISSUE TITLE
PhantomJS doesn't shut down properly on Linux

### ISSUE THREAD

**Issue by l15k4** [scala-js/scala-js#1452]
Hi, [details are here](https://groups.google.com/forum/#!topic/scala-js/Y6k10K5YyKI), basically what happens is that utest suite fails and PhantomJS OS process still exists which results in unpredictable errors when you run test suite again. This is the first run that ends with error : 
```
[info] Compiling 1 Scala source to /.../js/target/scala-2.11/test-classes...
[info] Fast optimizing /.../js/target/scala-2.11/app-test-fastopt.js
Uncaught failure in async execution: utest.AssertionError: assert(p == expectedPosition)

  /tmp/phantomjs-launcher4242163106310882054.js:9 in onError


  /tmp/phantomjs-launcher4242163106310882054.js:11 in onError
  file:///.../js/target/scala-2.11/app-test-fastopt.js:94303 (in function "doWriteLine__p4__T__V")

  /tmp/phantomjs-launcher4242163106310882054.js:13
[trace] Stack trace suppressed: run last js/test:test for the full output.
[error] Could not run test ....EditorSuite: org.scalajs.jsenv.ComJSEnv$ComClosedException: JSCom has been closed
[trace] Stack trace suppressed: run last js/test:executeTests for the full output.
[error] (js/test:executeTests) org.scalajs.jsenv.ComJSEnv$ComClosedException: Phantom.js isn't connected
```
Then you have to go and kill the process for the next run to work correctly : 
```
ps aux | grep phantom
user     7310  0.2  0.7 1739472 61520 pts/1   Sl+  12:50   0:00 phantomjs /tmp/phantomjs-launcher7268336573458704946.js
kill -9 7310
```

Otherwise your suite probably fails on some IndexedDB issues or something that doesn't allow for running multiple PhantomJS instances...

When I'm chasing test issues I'm constantly running suite and killing PhantomJS afterwards. 

The solution would be checking whether PhantomJS process isn't already running before starting tests. It seems to be much easier that checking whether the process shut down properly.

NOTE: It might be specific to my test suite, but I didn't figure out the reason, I'm closing all resources I'm using when error occurs, like IndexedDb. Dunno why the process hangs out.

**Comment by sjrd** [comment]
Is this an 0.5.x or 0.6.x issue, or both?

It seems PhantomJS is never going to stop failing us in some cases :-(

**Comment by l15k4** [comment]
It is scala-js M3 and last release version of PhantomJS + a few more further commits

**Comment by sjrd** [comment]
@gzm0 It seems to me we should forcibly kill (with `.stop()`) the slaves and the master if they fail to close properly within a short window (`VMTermTimeout`) in `ScalaJSRunner.done()` and `stopSlaves()` in the test-adapter:
https://github.com/scala-js/scala-js/blob/v0.6.0-RC1/test-adapter/src/main/scala/org/scalajs/sbttestadapter/ScalaJSRunner.scala#L64
Or is that a bad idea?

**Comment by sjrd** [comment]
@l15k4 Could you provide a reproducible test case in a git branch somewhere, please?

**Comment by l15k4** [comment]
It currently happens in a project I haven't open sourced yet, but I will in ~ 5-6 days. I couldn't reproduce it in the OSS. 

I'll try to figure out what is the reason of it first, If I don't it'll have to wait those 5~6 days.

Btw before the master/slave architecture it usually remained in zombie mode `[phantomjs] <defunct>` which was OK, but now the process literally runs and if you don't kill it you may end up with as many processes as many times you run tests.

**Comment by gzm0** [comment]
@sjrd Yes, we can do that. Await should fail anyway, if the timeout expires, so this can be in a finally block I guess...

**Comment by japgolly** [comment]
I'm using PhantomJS on Arch Linux with RC1 (haven't tried M3) and I'm not seeing this issue. If there's any info I can provide for comparison let me know.

```
> uname -a
Linux golly-desktop 3.17.6-1-ARCH #1 SMP PREEMPT Sun Dec 7 23:43:32 UTC 2014 x86_64 GNU/Linux

> java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

> phantomjs -v
1.9.8
```

**Comment by l15k4** [comment]
I feel like I'm chasing a ghost, I can only reproduce this issue with uTest like this : 
```scala
import utest._
import monifu.reactive.Ack.Continue
import monifu.reactive.{Ack, Observer, Observable}
"test"-{
      Observable.fromIterable(List(1,2,3)).unsafeSubscribe(
        new Observer[Int] {
          override def onError(ex: Throwable): Unit = throw new IllegalStateException("wtf")
          override def onComplete(): Unit = throw new IllegalStateException("wtf")
          override def onNext(elem: Int): Future[Ack] = Continue
        }
      )
    }
```

unsafeSubscribe returns `Unit`, you cannot catch any `Throwable` if you `try catch` it although the execution doesn't continue after the `try catch` statement around this statemnt, still it somehow kills the test run as you can see in the first comment. An exception is thrown within a Runnable#run in a recursive function. But I can't reproduce it by anything similar, like :  
```scala
"test" - {
    throw new IllegalStateException("wtf") 
}
```
There must be some sort of internal screw up I don't follow, something inside that statement kills it without letting me  `try catch` throwable that should come from it.

**Comment by l15k4** [comment]
Basically : 
```scala
    "test"-{
      try {
        Observable.fromIterable(List(1,2,3)).unsafeSubscribe(
          new Observer[Int] {
            override def onError(ex: Throwable): Unit = throw new IllegalStateException("wtf")
            override def onComplete(): Unit = throw new IllegalStateException("wtf")
            override def onNext(elem: Int): Future[Ack] = Continue
          }
        )
      } catch {
        case e : Throwable => println("NEVER PRINTS")
      }
      println("NEVER PRINTS")
    }
```

results in this ouput, which leaves PhantomJS process running : 
```
[info] Compiling 1 Scala source to /.../js/target/scala-2.11/test-classes...
[info] Fast optimizing /.../js/target/scala-2.11/app-test-fastopt.js
Uncaught failure in async execution: utest.AssertionError: assert(p == expectedPosition)

  /tmp/phantomjs-launcher4242163106310882054.js:9 in onError


  /tmp/phantomjs-launcher4242163106310882054.js:11 in onError
  file:///.../js/target/scala-2.11/app-test-fastopt.js:94303 (in function "doWriteLine__p4__T__V")

  /tmp/phantomjs-launcher4242163106310882054.js:13
[trace] Stack trace suppressed: run last js/test:test for the full output.
[error] Could not run test ....EditorSuite: org.scalajs.jsenv.ComJSEnv$ComClosedException: JSCom has been closed
[trace] Stack trace suppressed: run last js/test:executeTests for the full output.
[error] (js/test:executeTests) org.scalajs.jsenv.ComJSEnv$ComClosedException: Phantom.js isn't connected
```

**Comment by l15k4** [comment]
**This is it**, see, [execute](https://github.com/alexandru/monifu/blob/master/monifu-core/js/src/main/scala/monifu/concurrent/schedulers/TrampolinedScheduler.scala#L40) is not asynchronous, yet it does what I explained above, dunno why : 
```scala
    "test" - {
      Scheduler.trampoline().execute(new Runnable {
        override def run(): Unit = throw new IllegalStateException("wtf")
      })
    }
```

**Comment by sjrd** [comment]
I think I have a local reproduction of this with the following code:
```scala
    val id = scala.util.Random.nextInt(1000)
    println("ONE " + id)
    js.timers.setTimeout(2000) {
      println("TWO " + id)
      throw new IllegalStateException("BOOM " + id)
    }
```
If I throw the exception in the normal flow, all goes well. But if I throw it in a `setTimeout`, I indeed have a `ComClosedException` + one instance of `phantomjs` keeps running.

**Comment by l15k4** [comment]
But why does it happen in that synchronous Scheduler.trampoline().[execute](https://github.com/alexandru/monifu/blob/master/monifu-core/js/src/main/scala/monifu/concurrent/schedulers/TrampolinedScheduler.scala#L40)? From what I see, there is no `setTimeout` in there involved. `TrampolineScheduler` uses `setTimeout` only for `scheduleOnce` method, not for `execute`. Weird

**Comment by sjrd** [comment]
It can also happen in a synchronous context if the surrounding executer is asynchronous in some way. And for a testing framework using the asynchronous nature of the testing interface, that basically mean all the time.

**Comment by SemanticBeeng** [comment]
Seems something similar happens with this code
https://github.com/SemanticBeeng/play-scalajs-showcase/commit/4faf378bd34a761bc098b5898563319c86fe209d
and with RC2 on Ubuntu and PhantomJS 1.9.0

Hope it helps

[info] Set current project to jvm (in build file:/home/nickdsc/projects/playframework-learn/play-scalajs-showcase/)
[trace] Stack trace suppressed: run last js/test:loadedTestFrameworks for the full output.
[trace] Stack trace suppressed: run last js/test:test for the full output.
[error] Could not run test domain.SharedTest: org.scalajs.jsenv.ComJSEnv$ComClosedException: JSCom has been closed
[trace] Stack trace suppressed: run last js/test:executeTests for the full output.
[error] (js/test:executeTests) org.scalajs.jsenv.ComJSEnv$ComClosedException: JSCom has been closed
[error] Total time: 3 s, completed Jan 30, 2015 5:36:52 PM
[jvm] $ last js/test:loadedTestFrameworks
org.mozilla.javascript.JavaScriptException: scala.scalajs.runtime.UndefinedBehaviorError: An undefined behavior was detected: true is not an instance of scala.util.Try (Lorg_scalajs_testinterface_internal_BridgeBase.sjsir#46)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1018)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
	at org.scalajs.jsenv.rhino.RhinoJSEnv$$anonfun$org$scalajs$jsenv$rhino$RhinoJSEnv$$setupCom$2$$anonfun$4.apply(RhinoJSEnv.scala:285)
	at org.scalajs.jsenv.rhino.RhinoJSEnv$$anonfun$org$scalajs$jsenv$rhino$RhinoJSEnv$$setupCom$2$$anonfun$4.apply(RhinoJSEnv.scala:285)


[jvm] $ last js/test:test
[debug] Running TaskDef(domain.SharedTest, org.scalajs.testadapter.FingerprintSerializers$DeserializedSubclassFingerprint@274bc6c3, false, [SuiteSelector])
org.scalajs.jsenv.ComJSEnv$ComClosedException: JSCom has been closed
	at org.scalajs.jsenv.rhino.RhinoJSEnv$ComRunner.receive(RhinoJSEnv.scala:117)
	at org.scalajs.testadapter.ComUtils$.receiveResponse(ComUtils.scala:42)
	at org.scalajs.testadapter.ComUtils$.receiveLoop(ComUtils.scala:21)
	at org.scalajs.testadapter.ComUtils$.receiveLoop(ComUtils.scala:16)
	at org.scalajs.testadapter.ScalaJSTask.execute(ScalaJSTask.scala:62)
	at sbt.TestRunner.runTest$1(TestFramework.scala:84)
	at sbt.TestRunner.run(TestFramework.scala:94)


[jvm] $ last js/test:executeTests
org.scalajs.jsenv.ComJSEnv$ComClosedException: JSCom has been closed
	at org.scalajs.jsenv.rhino.RhinoJSEnv$ComRunner.receive(RhinoJSEnv.scala:117)
	at org.scalajs.testadapter.ComUtils$.receiveResponse(ComUtils.scala:42)
	at org.scalajs.testadapter.ComUtils$.receiveLoop(ComUtils.scala:30)
	at org.scalajs.testadapter.ScalaJSRunner$$anonfun$8$$anonfun$apply$3.apply$mcV$sp(ScalaJSRunner.scala:165)
	at org.scalajs.testadapter.ScalaJSRunner$$anonfun$8$$anonfun$apply$3.apply(ScalaJSRunner.scala:164)
	at org.scalajs.testadapter.ScalaJSRunner$$anonfun$8$$anonfun$apply$3.apply(ScalaJSRunner.scala:164)
	at scala.util.Try$.apply(Try.scala:161)
	at org.scalajs.testadapter.ScalaJSRunner$$anonfun$8.apply(ScalaJSRunner.scala:164)

**Comment by SemanticBeeng** [comment]
Or is it because the code uses futures?
https://github.com/lihaoyi/utest/issues/33
