### ISSUE TITLE
cookie still not settable in 0.6.0-RC1

### ISSUE THREAD

**Issue by fommil** [scala-js/scala-js#1462]
```scala
    println("raw cookies = " + dom.document.cookie)
    println(cookies)
    dom.document.cookie = "a=12; b=13"
    println(dom.document.cookie)
    println(cookies)
```

gives

```
raw cookies = 
Map( -> )

Map( -> )
```

instead of the expected

```
raw cookies = 
Map( -> )
a=12; b=13
Map( -> )
```

**Comment by sjrd** [comment]
Please verify that this is actually different than the behavior in JS.
I.e., in your .html page where you observe this behavior, open a console, and write:
```javascript
document.cookie = "a=12; b=13";
document.cookie
```

**Comment by lihaoyi** [comment]
Try it in the chrome console in javascript, it does the same thing

**Comment by fommil** [comment]
http://www.w3schools.com/js/js_cookies.asp

**Comment by sjrd** [comment]
As @lihaoyi said, it behaves exactly like that on Chrome (with a local .html file, at least)

**Comment by fommil** [comment]
chrome console

```
document.cookie="a=12; b=13"
"a=12; b=13"
document.cookie
"a=12; __gads=ID=aff68ed886cf6b03:T=1415655109:S=ALNI_MZMPhbttBTKQyov7g0PiYGQ6SqisQ; ASPSESSIONIDSAAQBQAB=CPCLEKHCLNJGGNOPCCDKGIID; ASPSESSIONIDCCCRCTDD=BFJGDJBABOGDHMHBFKCIAMJE; _ga=GA1.2.410821601.1415655109; _gat=1"
```

**Comment by sjrd** [comment]
In a page for *a local .html file*? really? I get `""` doing the same thing.

**Comment by fommil** [comment]
hmm, with a standalone HTML it doesn't print anything.

I'll investigate further. Do you think this'll work if i serve it from a webhost? How are we supposed to test that sort of thing?

**Comment by sjrd** [comment]
Yes, it will work if served from an HTTP server.
To test this, well, you need an HTTP server, even a local one.

**Comment by fommil** [comment]
god damn you, chrome http://stackoverflow.com/questions/12992494

**Comment by lihaoyi** [comment]
^_^ workbench provides a HTTP server. IntelliJ does too

**Comment by fommil** [comment]
pppppfff, workbench? IntelliJ?

I Jedi need not these things.

https://github.com/nicferrier/elnode#how-does-it-work
