### ISSUE TITLE
Get single js file after aggressive closure compilation?

### ISSUE THREAD

**Issue by SRGOM** [scala-js/scala-js#1474]
First off, big thanks. 
Is it possible to get just a single final js file with all the unused functions of the dependencies removed by google closure compiler? 
What I mean is including  a library with 10K functions, using only 5 of them and hence including only 5? I know this is not directly Scala.js so a single word yes/planning/no answer would be great.

**Comment by sjrd** [comment]
Duplicate of #761?

**Comment by SRGOM** [comment]
Yes. The general question is a duplicate of #761 and what I had in mind was jquery which is not closure advanced ready. http://bugs.jquery.com/ticket/7318
