### ISSUE TITLE
fullOptJS: chunked output possible?

### ISSUE THREAD

**Issue by siriux** [scala-js/scala-js#1475]
Hi,

I open a new issue, even if https://github.com/scala-js/scala-js/issues/947 is closely related because I'm interested in fullOptJS.

Given that the Closure Compiler already supports compiling multiple modules together, but generating the output in multiple files, I think this should be fairly easy. 

Also, seeing the code from optimizeIR here: https://github.com/scala-js/scala-js/blob/f4ba58cc2c89ca8e6a147d45d4793ddfac23f5cb/tools/jvm/src/main/scala/org/scalajs/core/tools/optimizer/ScalaJSClosureOptimizer.scala

Looking at the code, it should be really easy to add independent modules, as long as we know how to separate the files. A really simple option (that can cover most use cases) would be to just allow to compile some libraries as independent files, because we already know the files in a library.

This can be really useful for large applications, allowing to show something really fast (even on mobile), while lazy loading the fat libraries only when needed. Also, once we have the split output, it's really easy from the code to load the file when needed, but a standard way of doing this this would be even better.

**Comment by sjrd** [comment]
I wonder where you saw that Closure supports generating the output in multiple files. Care to provide a link to some reference?

Anyway, I do *not* believe this is easy. Even if it is technically easy to separate modules along some arbitrary borders, it will be very difficult to find appropriate borders, i.e., partition your application into parts that can be meaningfully loaded lazily.

If you have a better idea than me, and you feel this is easy, feel free to go ahead and implement it!

**Comment by siriux** [comment]
Hi,

I've found two examples on stackoverflow: http://stackoverflow.com/a/7827251 and http://stackoverflow.com/a/10401030

Also some info here: https://groups.google.com/forum/#!topic/closure-compiler-discuss/7H9oCbGbAZ4

So, I guess, (not actually tested) that this is possible and easy with the closure compiler. Also, I imagine that is as simple as creating multiple modules and providing them in the list of line 79 from : https://github.com/scala-js/scala-js/blob/f4ba58cc2c89ca8e6a147d45d4793ddfac23f5cb/tools/jvm/src/main/scala/org/scalajs/core/tools/optimizer/ScalaJSClosureOptimizer.scala

About separating modules along arbitrary borders, I agree that it can be difficult, but it's the responsibility of the programmer to do it, and it will depend a lot on the app. 

Also, there are many examples where it's useful and "easy", and they could benefit from it. I'm thinking about an app that can perform multiple heavyweight tasks, but not all of them are performed every time. Another example could be an app that requires filling in some kind of info before the real heavy task. In both cases, it would be extremely simple to factor out this functionality in a separate library/dependency, and would improve load times a lot, specially in mobile.

I'm trying to re-evaluate ScalaJS for a project now that 0.6 is out, and this is one feature I miss from Dart (currently used in my prototype).

Thanks

**Comment by siriux** [comment]
Another option would be to be able to compile (without optimizing with closure) a main file and it's dependencies in different files. (related to https://github.com/scala-js/scala-js/issues/947) From there, it would be very easy to run the closure compiler by hand (or build script) with the right options to generate the files for production.

**Comment by ochrons** [comment]
I believe the intial download time is not very significant these days. More important is to make the production files "immutable" (through unique naming like in GWT) so that they can be cached on the device forever.

**Comment by sjrd** [comment]
OK so it seems possible, indeed. The surface of the codebase that this feature would touch also seems quite small, so I'll mark this as community.

**Comment by siriux** [comment]
That depends a lot on the use case, the web is used for many different things today. Also, it's not only download time, it's also parsing and executing a really big blob of JS on mobile (even if it's not used right there).

**Comment by siriux** [comment]
Thanks Sébastien, I just wanted to be sure this it's not something is going to block me in the future if I choose to go along with ScalaJS.

Just one last small question, because I don't have the big picture on the code, in case I need to implement it. To separate the files in libraries, I would do it in a custom builder, isn't it? But is there information to known from which library a Tree comes from.

Thanks

**Comment by sjrd** [comment]
You can't know from what library a `Tree` comes from. A `Tree` has no information that can tell you that (well, sort of, it has a `pos` with a `file`, but that's a Source file, and it can be an arbitrary URI).

So a custom builder will probably not be enough. You will likely have to adapt the API of `ScalaJSOptimizer.optimizeIR` to accept not a builder, but a function of `LinkedClass => Builder`, or something like that.

**Comment by siriux** [comment]
Perfect, thanks!

**Comment by gzm0** [comment]
@siriux is this still an issue, or can we close it?

**Comment by siriux** [comment]
Hi,

I think you can close it. I just wanted to know that was not a possible
future block if I choose to use scala-js.

If I find problems implementing it in the future, I'll reopen it.

Thanks
