### ISSUE TITLE
does @JSExportAll require @JSExport?

### ISSUE THREAD

**Issue by gcanti** [scala-js/scala-js#1476]
Hello, maybe I misinterpreted how to use @JSExportAll in:

http://www.scala-js.org/doc/export-to-javascript.html

but this doesn't work for me:

```scala
package issue

import scala.scalajs.js.annotation.JSExportAll

@JSExportAll
object Issue {
  val name = "Giulio"
  val surname = "Canti"
}
```

```js
// compiled JavaScript
console.log(window.issue); // => undefined
```

This works instead:

```scala
package issue

import scala.scalajs.js.annotation.JSExport
import scala.scalajs.js.annotation.JSExportAll

@JSExport // <- adding also @JSExport
@JSExportAll
object Issue {
  val name = "Giulio"
  val surname = "Canti"
}
```

```js
// ok!
console.log(window.issue); // => Object {Issue: function}
```

Is it correct to add both annotations? Or there is a way to add just @JSExportAll and I'm missing something?

Thanks, Giulio

**Comment by sjrd** [comment]
This is the intended behavior.

* `@JSExport` exports the object itself (or the class' constructor, if it is a class)
* `@JSExportAll` exports all its *members*, but not the object/constructor itself.

So, yes, you need both, and it is OK to use both.

**Comment by gcanti** [comment]
Ok, thanks!

**Comment by matanster** [comment]
Maybe the specific section dedicated to `@JSExportAll` in [Export Scala.js APIs to JavaScript](http://www.scala-js.org/doc/interoperability/export-to-javascript.html) would somehow make this fact more obvious? 

I had spent my first 20 minutes of hands-on scala.js (dedicated to wiring an existing internal library project with scala.js) ― around troubleshooting this point :) When I only used `@JSExportAll`, not even members got exported to the `.js` artifact, at least in the fast optimization (`sbt fastOptJS`), which led to some 20 minutes of various troubleshoot techniques.

**Comment by gzm0** [comment]
@matanster feel free to open an issue against [scala-js/scala-js-website][1] or even a PR.

[1]: https://github.com/scala-js/scala-js-website
