### ISSUE TITLE
Packaging as node library

### ISSUE THREAD

**Issue by mizchi** [scala-js/scala-js#1477]
Perhaps there are people who want use scala.js casually in node.js even if it was a bit big size(including me). And it will pay in pure and big code like a complex algorithm or language parser.

I tried v0.6 and thought today's scala.js is enough small to run in node(io).(`Hello World` is 19k)

I tried these codes.

```scala
package main
import scala.scalajs.js
import js.annotation.JSExport

@JSExport("Main")
object Main extends js.JSApp {
  @JSExport
  def square(n: Int) = n * n
}
```

To use naturary in node, I need facad.

index.js

```javascript
var vm = require('vm');
var fs = require('fs');
var code = fs.readFileSync(__dirname + 'target/scala-2.11/scala-js-tutorial-opt.js').toString();
var sandbox = {};

vm.runInNewContext(code, sandbox, 'scalajs-tutorial');
module.exports = sandbox.Main().square;
```

It works but It's too simple and I have no confidence it is right in any case. If scala.js can do it with right way, I hope it so. (Of cource I know scala.js will perform better in scala ecosystem)

**Comment by sjrd** [comment]
Does [this SO question](http://stackoverflow.com/questions/26637600/how-to-convert-scala-js-application-to-commonjs-module) help?

**Comment by mizchi** [comment]
@sjrd I know it works but that injects many properties to global namespace. I used vm module to avoid it and filter exposed API. (http://nodejs.org/api/vm.html)
But I fear that filtering scope by running `vm` context break scala.js.

**Comment by sjrd** [comment]
Huh? What does that inject into the global namespace? It shouldn't, at all. Scala.js only exports things in its `exportsNamespace` (+, in FastOpt, it exports the `ScalaJS` variable in the "this" scope, but that will change at some point).

**Comment by sjrd** [comment]
I don't think `vm` would break anything in Scala.js.
