### ISSUE TITLE
Wrong optimization of Float/Double * -1

### ISSUE THREAD

**Issue by smeagol74** [scala-js/scala-js#1478]
Good day, I'm using Scala JS version 0.6.0

Simple function in scala compiles to very wrong JavaScript.
```scala
def testCompiler(a: Float) = a * -1
```
is compiled to following JavaScript with fastOptJS directive
```javascript
ScalaJS.c.Ltutorial_webapp_TutorialApp$.prototype.testCompiler__F__F = (function(a) {
  return 1.0
});
```
As you can see function compiles to return constant value. This do not looks like proper behaviour.

Such negation works fine for Int, but not for Float or Double

**Comment by sjrd** [comment]
Oh god. This is the same issue as #1453 but [for Float](https://github.com/scala-js/scala-js/blob/v0.6.0/tools/shared/src/main/scala/org/scalajs/core/tools/optimizer/OptimizerCore.scala#L2318) and [for Double](https://github.com/scala-js/scala-js/blob/v0.6.0/tools/shared/src/main/scala/org/scalajs/core/tools/optimizer/OptimizerCore.scala#L2373). How did I not verify these cases when I fixed it for Int? Stupid me.

Thanks for the report.

You can work around the issue by disabling the optimizer with:
```scala
scalaJSOptimizerOptions ~= { _.withDisableOptimizer(true) }
```
or, if your code is literally like this, you can also rewrite it as:
```scala
def testCompiler(a: Float) = -a
```
instead.
