### ISSUE TITLE
Question: How to export properties of shared case classes

### ISSUE THREAD

**Issue by rparree** [scala-js/scala-js#1481]
I am trying to share a case class between server and client. I am using upickle on both ends. The objects and their data are nicely available on both ends.

shared class

```scala
case class Foo(var id : Long,var title: Description)
```

However i need to export the fields of the case class on the client side. I could add the `@ExportAll` annotation, but that means pulling in the scalajs libraries on the server project. 

Is there perhaps a better way of exposing the members `id` and `title` to the javascript.

tx.,

**Comment by sjrd** [comment]
First: questions are best asked [on StackOverflow](http://stackoverflow.com/questions/tagged/scala.js). GitHub Issues are for, well, issues. It would be great if you could re-ask your question on SO. But anyhow, let me answer already.

The right way to export things to JavaScript is to use the `@JSExportAll` annotation. You cannot, and should not, pull the Scala.js libraries on the server project, though. For this use case, we have a dedicated JVM artifact, `scalajs-stubs`, which you can add to your JVM project like this:
```scala
libraryDependencies += "org.scala-js" %% "scalajs-stubs" % scalaJSVersion % "provided"
```
As a "provided" dependency, it will not be present at runtime. But it will allow you to compile the JVM project even though it references `JSExportAll`.

See also [the ScalaDoc of scalajs-stubs](http://www.scala-js.org/api/scalajs-stubs/0.6.0/#package).

**Comment by rparree** [comment]
Sorry and thanks :)

Posted the Q and A on SO as a reference for other developers
 http://stackoverflow.com/questions/28413266/how-to-export-properties-of-shared-case-classes/28413267#28413267

**Comment by georgeorfanidi** [comment]
in case I have a case class of the form
case class Foo(var id : Long,var title: Seq[String])
i.e. it contains a sequence of data, is there any setting to be exported as js.Array ?

**Comment by sjrd** [comment]
@georgeorfanidi 

> Questions are best asked [on StackOverflow](http://stackoverflow.com/questions/tagged/scala.js). GitHub Issues are for, well, issues.

Please post your question on SO.

**Comment by evbo** [comment]
> in case I have a case class of the form case class Foo(var id : Long,var title: Seq[String]) i.e. it contains a sequence of data, is there any setting to be exported as js.Array ?

I'm sure you found a solution by now ;) but for anyone else reading this for the first time here is an excellent blog that discusses how to work around Scala types _not_ exported, like `Seq` or `Option`:
https://pavkin.ru/how-to-make-an-idiomatic-javascript-library-with-scala-js/
