### ISSUE TITLE
java.util.concurrent.ConcurrentHashMap impl missing

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#1487]
JS is single-threaded so this can be very-simply backed by a plain HashMap.

Good for any new, eager contributors out there to pick up.  :)

**Comment by japgolly** [comment]
Actually, I'll do this myself. I didn't want to commit (again) to something I don't have time for but I should be able to smash this in an hour or two.

...with a little guidance. Could you please give me a few beginning bits of info:
* where (which dir) should I put this?
* which Java version interface should I adhere to?
* how much is expected in terms of unit test? (keeping in mind I'll just write a facade over a Scala mutable `Map`.

**Comment by gzm0** [comment]
> where (which dir) should I put this?

Code: `javalib/src/main/scala/java/util/concurrent/ConcurrentHashMap.scala`
Tests: `test-suite/src/test/scala/org/scalajs/testsuite/javalib/ConcurrentHashMapTest.scala`

> which Java version interface should I adhere to?

JDK7, such that it is backwards compat with JDK6. If this is not possible, we need to discuss

> how much is expected in terms of unit test? (keeping in mind I'll just write a facade over a Scala mutable Map.

I think the expectation is to have a test per method. I'd be mostly concerned about different null handling and different behavior with primitive types. @sjrd?

**Comment by sjrd** [comment]
Agreed.

**Comment by andreaTP** [comment]
Going to implement this here: 
https://github.com/andreaTP/scala-js

but couldn't run tests and looks that the mocked implementation of ConcurrentHashMap is hidden by something else.
I added in my class a TEST method that is not in the standard library and tests couldn't compile if I call it.

Any suggestion?

**Comment by sjrd** [comment]
This is normal. For classes of the JDK, you have to implement the public API of the JDK. Even if you add other public methods, you cannot access them from users of these classes, including tests. Your unit tests should live in `test-suite/.../javalib/`, and they can only call methods that are public in the JDK API.

**Comment by andreaTP** [comment]
Thanks, 
I try to do this because an inner val of the class (the mutable.HashMap) is null if not declared lazy, is it intended?
Anyhow now it works...
I'm writing some tests and that ask the pull.

**Comment by sjrd** [comment]
> I try to do this because an inner val of the class (the mutable.HashMap) is null if not declared lazy, is it intended?

You may have an issue with initialization order of fields, which is a recurrent problem in Scala (not just Scala.js).

**Comment by gzm0** [comment]
Fixed in 07dd4fa6bed9ec718012686aa079497460f0d11d
