### ISSUE TITLE
JSExport of abstract class should fail more elegantly

### ISSUE THREAD

**Issue by bshlgrs** [scala-js/scala-js#1497]
When I tried to export a Scala abstract class, the `fastOptJS` command fails with this error:

	[error] Referring to non-existent method Last_Statement.toIntermediate__sci_List
	[error]   called from Last_StatementHelper$.statementsToIntermediate__sci_List__sci_List
	[error]   called from Last_IfElse.toIntermediate__sci_List
	[error]   called from Last_Expr.toIntermediate__T2
	[error]   called from Last_Return.toIntermediate__sci_List
	[error]   called from Last_StatementHelper$.statementsToIntermediate__sci_List__sci_List
	[error]     (already seen, not repeating call stack)
	[error] involving instantiated classes:
	[error]   Last_StatementHelper$
	[error]   Last_IfElse
	[error]   Last_Var
	[error]   Last_FunctionCall
	[error]   Last_IfExpression
	[error]   Last_Lit
	[error]   Last_Load
	[error]   Last_PointerToName
	[error]   Last_BinOp
	[error]   Last_StringLiteral
	[error]   Last_Expr
	[error]   Last_Return

When I google that, I end up [here](https://github.com/scala-js/scala-js/issues/1394), from which I managed to guess that the problem was that abstract classes require `ClassManifest`s, which breaks the linker.

It would be great if this error message were more obvious: when you try to run the JSExport macro on a abstract class, it should fail immediately.

**Comment by gzm0** [comment]
Indeed. Exporting an abstract class or a trait does not make sense.

**Comment by gzm0** [comment]
@sjrd I would like to forbid `@JSExport` of abstract classes (exporting traits is already forbidden). However, this will break source compatibility. The following actually "works" (i.e. print "Hello World: 1"):

```scala
package helloworld

import scala.scalajs.js
import js.annotation._

@JSExport
abstract class A {
  @JSExport
  def foo: Int = 1
  def bar: Int
}

object HelloWorld extends js.JSApp {
  def main() {
    import js.Dynamic.{global => g}
    val obj = js.Dynamic.newInstance(g.helloworld.A)()
    println(s"Hello World: ${obj.foo}")
  }
}
```

Note that it is (potentially) non-trivial to turn this abstract class into a normal class.

Should we just emit a non-suppressible warning instead? (or do we need suppression?)

**Comment by gzm0** [comment]
Note that DCE warnings are emitted properly (e.g. if we re-implement `foo` as `def foo = bar`).

**Comment by sjrd** [comment]
Ergh. No here I think we should still "break" it. Because this is still a bug, and code "working" like that is wrong anyway. And the impact will be a compilation error with a newer compiler, not a silent change in behavior.
