### ISSUE TITLE
Memory leak when using anonymous inner classes

### ISSUE THREAD

**Issue by wwagner4** [scala-js/scala-js#1504]
Massive creation of inner classes creates a memoryleak.

The error can be reproduced in the following branche [scalajs_memoryleak](https://github.com/wwagner4/doctus/tree/scalajs_memoryleak) of my project. The JS-Profiler
shows the memoryleak.

Open scalajs-showcase/dummy02.html in your browser.

I found a workaround by replacing the anonymous inner classes by toplevel case classes. [Workaround](https://github.com/wwagner4/doctus/commit/6846c4a5f2bf83c8663dcfdbe807b2d0f9439abc)

Try it out using the following branch. [scalajs_memoryleak_workarount](https://github.com/wwagner4/doctus/tree/scalajs_memoryleak_workarount).

**Comment by sjrd** [comment]
Thanks for the report. Does it not leak on the JVM as well?

**Comment by sjrd** [comment]
On closer inspection of your code, I think it's quite normal that you get a memory leak. The way your code is written, there's nothing a compiler can do. You should observe the same leak on the JVM.

For example, [here](https://github.com/wwagner4/doctus/blob/scalajs_memoryleak/core/src/main/scala/doctus/core/util/DoctusVector.scala#L62-L67):
```scala
def add(v1: DoctusVector, v2: DoctusVector): DoctusVector = {
  new AbstractDoctusVector {
    def x = v1.x + v2.x
    def y = v1.y + v2.y
  }
}
```
By writing this, you cause `v1` and `v2` to be captured as fields of the anonymous class. If you translate this with top-level classes the way the compiler (scalac) does, you get:
```scala
class add_AbstractDoctusVector_anon(
    private[this] val v1: DoctusVector,
    private[this] val v2: DoctusVector) extends AbstractDoctusVector {
  def x = v1.x + v2.x
  def y = v1.y + v2.y
}
```
This class is forced to retain links to `v1` and `v2`, which must therefore leak. It has nothing to do with being an anonymous class.

You can instead write a non-leaking anonymous class like this:
```scala
def add(v1: DoctusVector, v2: DoctusVector): DoctusVector = {
  val newX = v1.x + v2.x
  val newY = v1.y + v2.y
  new AbstractDoctusVector {
    def x = newX
    def y = newY
  }
}
```

**Comment by wwagner4** [comment]
Did not seem to leak on the JVM. Will have a look at the Profiler

**Comment by wwagner4** [comment]
Same issue on the JVM.
Thanks for the advise.
