### ISSUE TITLE
fastopt.js file timestamp changes even when there is no source changes

### ISSUE THREAD

**Issue by ramnivas** [scala-js/scala-js#1513]
How to reproduce:
1. Clone a simple scala.js project (e.g. https://github.com/sjrd/scala-js-example-app)
2. Launch `sbt`
3. fastOptJS
5. Note the timestamp for the *-fastopt.js file
6. Wait a minute
7. Again fastOptJS
8. Again check the timestamp for the *-fastopt.js file. It will have changed to the current time.

If you were to check the *.class files' timestamps, they will not have changed.

Background: I am experiencing slow fastOpt compilation in a multi-project setup (15 seconds for a trivial string change in a project that no other subproject depends on). So I am trying to understand enough to report a helpful issue and encountered this during that attempt. I am not sure if the fastopt timestamp is a part of the issue (could be if the fastopt in dependee depends on fastopt output in a dependent project), but in any case seems not right. I expected fastopt files to behave like .class files in this case.

**Comment by sjrd** [comment]
Already fixed: #1505.
