### ISSUE TITLE
Multi-project setup with scala.js performs unnecessary work

### ISSUE THREAD

**Issue by ramnivas** [scala-js/scala-js#1514]
In a multi-project setting, even when there is no change to a subproject (or its dependent projects), `fastOptJS` performs some work for any change in other parts of the project. Here is a repo that can be used to reproduce the issue: https://github.com/ramnivas/scalajs-multi-project-issue. The essential part is that `subproject1` depends on `subproject2` and `root` aggregate them all.

```
$ sbt
...
> ~fastOptJS
...
[success] Total time: 4 s, completed Feb 28, 2015 4:55:55 PM
1. Waiting for source changes... (press enter to interrupt)

=== Now make some trivial change to ScalaJSExample in subproject1 ===

[info] Compiling 1 Scala source to /Users/ramnivas/template-dev/scalajs-multi-project-issue/subproject1/target/scala-2.11/classes...
[info] Fast optimizing /Users/ramnivas/template-dev/scalajs-multi-project-issue/target/scala-2.11/root-fastopt.js
[info] Fast optimizing /Users/ramnivas/template-dev/scalajs-multi-project-issue/subproject2/target/scala-2.11/subproject2-fastopt.js
[info] Fast optimizing /Users/ramnivas/template-dev/scalajs-multi-project-issue/subproject1/target/scala-2.11/subproject1-fastopt.js
[success] Total time: 3 s, completed Feb 28, 2015 4:56:23 PM
```

While I expected `subproject1` and `root` to perform some work, the `[info] Fast optimizing /Users/ramnivas/template-dev/scalajs-multi-project-issue/subproject2/target/scala-2.11/subproject2-fastopt.js` part seems unnecessary.

p.s. This is the continuation of exploration mentioned in #1513

**Comment by sjrd** [comment]
Also fixed by #1505 and #1507.

**Comment by ddispaltro** [comment]
I am guessing this doesn't need a recompile for it to be used in dependent projects, correct?

e.g. if uTest depends on 0.6.0 and your project depends on 0.6.1 and uTest, this fix is "included" right?

**Comment by ramnivas** [comment]
My understanding is that my project needs to not only use scalajs 0.6.1, but also a uTest version that is compiled with 0.6.1.

**Comment by sjrd** [comment]
@ramnivas is right. Just depending on Scala.js 0.6.1 will remove a lot of the unnecessary work (because the standard library upgrades) but some parts of uTest will be reoptimized every time *something* changes in the project or is dependencies. 

Independently, with 0.6.1, if *nothing* changed in a project and any of its dependencies, then `fastOpt` will avoid doing *any* work whatsoever. But this is another issue #1491, which doesn't need recompilation to be applied.
