### ISSUE TITLE
source code is compiled even before you type "compile" or "package"

### ISSUE THREAD

**Issue by zfy0701** [scala-js/scala-js#1517]
Hi,

I was trying to compile scala-js using a local version of scala by setting
```
scalaVersion := "2.10.0-local"

scalaHome := Some(file("/path/to/scala/home/"))
```

but this doesn't work, after some investigation, I found that the code has all be compiled before I even set those parameters, actually, if I just type sbt without any parameters, the code will all be compiled to `project/target`, while in normal cases, the code should be compile to `target` after you type `compile` or `package`.

Is this the intended behavior?

**Comment by gzm0** [comment]
Are you talking about the Scala.js project itself?

Since some of the projects in the Scala.js build depend on the sbt plugin, we include the sbt-plugin sources (and its dependencies) in the build itself.

However, if you compile things once sbt is up and running, it should use the scala version you specify (i.e. all artifacts of the build will be compiled with your local version).

On the other hand, if you use Scala.js specific tasks in the Scala.js project itself, it will use the binaries compiled with the default Scala version of the build (2.10.4 IIRC).

If you want everything compiled with your local scala version, you'll need to change the scala version of the build itself in `project/build.sbt` (this is the build of the build).

Hope that makes it a bit clearer what happens here.

**Comment by zfy0701** [comment]
Hi
Thanks for the quick reply, yes, I'm talking about the project itself because I'm trying to play around with it but found things doesn't go exactly the same as what described in dev doc.

let's put aside the the problem of using local scala version.

I tried to simply do things like following:
```
git pull
git clean -xfd
sbt
```
```
[info] Loading project definition from /Users/fuyaoz/src/scala-js/project/project
[info] Updating {file:/Users/fuyaoz/src/scala-js/project/project/}scala-js-build-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 1 Scala source to /Users/fuyaoz/src/scala-js/project/project/target/scala-2.10/sbt-0.13/classes...
[info] Loading project definition from /Users/fuyaoz/src/scala-js/project
[info] Updating {file:/Users/fuyaoz/src/scala-js/project/}scala-js-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 144 Scala sources to /Users/fuyaoz/src/scala-js/project/target/scala-2.10/sbt-0.13/classes...
[warn] there were 1 deprecation warning(s); re-run with -deprecation for details
[warn] there were 3 unchecked warning(s); re-run with -unchecked for details
[warn] two warnings found
```

it seems all sources will be compiled at this moment

```
tree scala-js/project/target/scala-2.10/sbt-0.13/classes

...
│       │       │   └── ScalaJSEnvHolder.class
│       │       ├── io
│       │       │   ├── CacheUtils$$anonfun$1.class
│       │       │   ├── CacheUtils$$anonfun$2$$anonfun$apply$1.class
│       │       │   ├── CacheUtils$$anonfun$2$$anonfun$apply$2.class
│       │       │   ├── CacheUtils$$anonfun$2.class
│       │       │   ├── CacheUtils$$anonfun$cached$1$$anonfun$apply$3.class
│       │       │   ├── CacheUtils$$anonfun$cached$1.class
│       │       │   ├── CacheUtils$$anonfun$joinVersions$1.class
│       │       │   ├── CacheUtils$.class
│       │       │   ├── CacheUtils.class
│       │       │   ├── FileVirtualBinaryFile$.class
│       │       │   ├── FileVirtualBinaryFile.class
│       │       │   ├── FileVirtualFile$$anonfun$withExtension$1.class
│       │       │   ├── FileVirtualFile$.class
│       │       │   ├── FileVirtualFile.class
│       │       │   ├── FileVirtualJSFile$.class
│       │       │   ├── FileVirtualJSFile.class
│       │       │   ├── FileVirtualScalaJSIRFile$.class
│       │       │   ├── FileVirtualScalaJSIRFile.class
│       │       │   ├── FileVirtualTextFile$.class
...

```
those classes must belong to the main source

then

```
> compile
[info] Updating {file:/Users/fuyaoz/src/scala-js/}scalajs...
[info] Resolving jline#jline;2.12 ...
[info] Done updating.
[success] Total time: 0 s, completed Mar 4, 2015 6:04:56 PM
> package
[info] Packaging /Users/fuyaoz/src/scala-js/target/scala-2.11/scalajs_2.11-0.6.2-SNAPSHOT.jar ...
[info] Done packaging.
[success] Total time: 0 s, completed Mar 4, 2015 6:05:11 PM
```

if I modify the files, I don't know what I need to do because from following console logs, clean/compile/package basically does nothing.

```
> clean
[success] Total time: 0 s, completed Mar 4, 2015 6:05:55 PM
>
> compile
[info] Updating {file:/Users/fuyaoz/src/scala-js/}scalajs...
[info] Resolving jline#jline;2.12 ...
[info] Done updating.
[success] Total time: 0 s, completed Mar 4, 2015 6:05:58 PM
>
> package
[info] Packaging /Users/fuyaoz/src/scala-js/target/scala-2.11/scalajs_2.11-0.6.2-SNAPSHOT.jar ...
[info] Done packaging.
[success] Total time: 0 s, completed Mar 4, 2015 6:06:00 PM
```

so when if I want to make any change to the project, it seems I need to clean the project by git clean and run sbt again, that seems really annoy.

**Comment by gzm0** [comment]
Indeed... The developer documentation is outdated: The root project [does not aggregate any projects anymore][1].

Therefore, `compile` indeed does nothing. However, the instructions on [publishing locally][2] are correct and will recompile everything (even the things compiled for the build itself).

[1]: https://github.com/scala-js/scala-js/commit/99c92547de78a648ded3d53d3994f34d1621b652
[2]: https://github.com/scala-js/scala-js/blob/c900b3b933a9c71468cdcfd8c22a99e6cac553a6/DEVELOPING.md#publish-locally

**Comment by gzm0** [comment]
Filed as #1518

**Comment by gzm0** [comment]
PR #1523 should update the documentation. @zfy0701 is this resolved for you, or does this need further investigation?
