### ISSUE TITLE
TypedArrayByteBuffer.asDoubleBuffer results in a "RangeError: Invalid typed array length"

### ISSUE THREAD

**Issue by joelross** [scala-js/scala-js#1532]
I suspect a minor typo on [this line](https://github.com/scala-js/scala-js/blob/184217741a2291c72833dcf7299a5daad6fadb94/javalib/src/main/scala/java/nio/TypedArrayDoubleBuffer.scala#L99): ```def bytesPerElem = 2```

**Comment by sjrd** [comment]
Indeed.
Can you give a test case that fails, please? My oh-so-extensive test suite failed to catch this typo, apparently.

**Comment by joelross** [comment]
Yes, I can cause it with the following line:
```scala
ByteBuffer.allocateDirect(16).order(ByteOrder.nativeOrder()).asDoubleBuffer()
```
