### ISSUE TITLE
Hijack scala.Symbol as ES6 Symbols

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#1541]
The more I think about it, the more I am convinced that we should hijack `scala.Symbol` to represent them as the new primitive type `Symbol` of ES6.
Doc: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol

Unlike `scala.Symbol`, there are 2 variants of ES6 symbols: named and opaque (or shared and non-shared, to take MDN's terminology). Named symbols are created with `Symbol.for("foo")`, and correspond to `scala.Symbol`:

* Two shared symbols created for the same string have the same identity: `Symbol.for("foo") === Symbol.for("foo")`
* You can get the string that was used to created a shared symbol: `Symbol.keyFor(Symbol.for("foo")) === "foo")`

Unique symbols are created with `Symbol()` or `Symbol(desc)`. The description is only relevant for debugging purposes, and cannot be retrieved. Each symbol created this way is unique, even if the same description is given twice.

I believe all of these can fit in a `scala.Symbol`. `Symbol.apply` would use `Symbol.for` to create a shared symbol, so only shared symbols can be created with the Scala API. But unique symbols created with the JS API would be valid "instances" of `scala.Symbol`. The semantics of `name()` would be modified to throw for unique symbols.

One gotcha: `scala.Symbol` allows `Symbol.apply(null)`, and gives a perfectly working `Symbol` whose name is `null` (not `"null"` the string). In JS, `Symbol.for(null) === Symbol.for("null")`, so we would create a dedicated unique symbol for `Symbol.apply(null)`.

The semantics of `.toString()` would change. In JS, `Symbol.for("foo").toString() === "Symbol(foo)"`, but in Scala it should be `'foo`.

JS' `Symbol`s are the only hope to ever get memory-leak-free `scala.Symbol`s. Note that `WeakMap`s do not help, because their *keys* are weak, not their values, and they are not iterable.

**Alternative**

Only consider shared Symbols (+ the unique `null` Symbol) to be instances of `scala.Symbol`. This keeps the semantics of `scala.Symbol` more compatible with Scala (only the `toString()` method changes). But then we need a *second* type to represent unique symbols, and we can't have a common super-type of both. This would also complicate type tests: `x.isInstanceOf[Symbol]` would be `typeof x === "symbol" && (Symbol.keyFor(x) !== (void 0) || x === NullSymbol)`, instead of just `typeof x === "symbol"`.

**Polyfill**

If `Symbol` is not present in JS, we can polyfill its shared variant using a leaky map for the purposes of implementing `scala.Symbol`, just like we do currently. We wouldn't expose the polyfill outside of the implementation of `scala.Symbol`, which means that we wouldn't introduce unique symbols.

**Binary compatibility**

At this point, I have not yet evaluated whether this can be implemented in a binary-compatible way. But I believe it can (at least backward).

**Comment by sjrd** [comment]
@gzm0 and others, opinions?

**Comment by jducoeur** [comment]
Makes sense to me.  The toString difference isn't trivial, but you *should* generally be using name, so I suspect it wouldn't break most sensible code; in particular, I'm not coming up with an obvious reason why you would care about toString compatibility between the two sides.  The variant for unique Symbols seems like a reasonably strict superset of the JVM functionality -- so long as it's clearly marked JS-only, it doesn't seem likely to cause problems.  (And IMO the fact that the JVM version allows null is a bit bizarre to begin with, so the difference there doesn't worry me much.)

Overall, seems like a win...

**Comment by gzm0** [comment]
I think this is a good proposal. Including the unique symbol for `null`, even if this will make the implementation of `name` have a special case. Further, it is probably a better idea to fully hijack the symbol, rather than half way and have a **very** strange runtime-type semantic (so I would tend towards the initial proposal, not the alternative).

**Comment by sjrd** [comment]
OK, thanks for the comments. I'll work on it.

**Comment by japgolly** [comment]
> The semantics of name() would be modified to throw for unique symbols.

This point seems bad. If there's no way of discriminating against the two types of ES6 symbols in Scala types, then there's no way of knowing whether it's safe to call `.name`. If I ever called `.name` I'd want to know for sure that it would succeed without throwing an error once it's the end-user's problem. (If nothing else, having it return `<unique symbol>` or something would be better.)

Not knowing much about the application or point of these symbols hinders my ability to reason about this, but generally speaking, merging two types into one without discrimination seems sure to hinder in future. Put cheekily, why would we want less type-safety than Javascript?

**Comment by sjrd** [comment]
This is a good point. I need to think more about this.

**Comment by sjrd** [comment]
Let's not do this, after all.
