### ISSUE TITLE
ES6 ...rest parameters

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#1542]
ECMAScript 6 introduces [rest parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters), a wonderful replacement for the quirky `arguments` special variable. Example:
```js
function foo(a, b, ...rest) {
  console.log(a);
  console.log(b);
  console.log(rest); // rest is a proper Array
  console.log(rest.length);
  console.log(rest.splice(1)); // methods of Array can be called
}

foo(1, 2, 3, 4, 5);
// 1
// 2
// [3, 4, 5] <-- note that 1 and 2 are not there
// 3
// [4, 5]
```
These rest parameters are supposedly going to be more efficient than `arguments`.

In an ECMAScript 6 output mode, we would like to use rest parameters instead of `arguments`. (And in [strong mode](https://github.com/scala-js/scala-js/issues/1527) we *need* to.) There is only one single place where we even use `arguments`: in exports of methods with varargs.

The question is at which point should we tackle this thing:

**Reverse-engineer rest params in ES 6 output mode**

This is the most conservative solution wrt to the IR. Binary compat is guaranteed simply because we don't change a thing. It also has absolutely no impact on the ES 5 mode, which could be considered less risky.

However, we'll need to perpetuate a reverse-engineering in the ES 6 mode for, well, ever.

**Add rest parameters in the IR**

This is probably the nicest alternative in the long run, but it has a bigger potential for breakage. Also, it breaks forward binary compatibility.

They must be last and must be of type `any`.
In that case, `JSDesugar` should desugar rest parameters into an initialization based on `arguments` when targeting ECMAScript 5.1.
A deserialization hack can be used in 0.6.x to recover rest parameters from usages of `arguments`.

Pros:
* We push to desugar a transformation that is currently done in GenJSExport for no good reason.
* The IR does not [need to know](https://github.com/scala-js/scala-js/blob/v0.6.1/tools/shared/src/main/scala/org/scalajs/core/tools/optimizer/IRChecker.scala#L232-L233) about the magical `arguments` variable, which is a fragile thing from an optimizations point of view (but the optimizer currently does not run on exports).
* The ECMAScript 6 output mode does not need to reverse-engineer rest parameters.

Cons:
* The IR will need to know what rest parameters are.
* Rest parameters should be disallowed in non-exports, just like `arguments` is only introduced for exports. So we still have a special-case for exports.

Subsidiary question: should we allow rest parameters in `Closure` nodes? Probably not: our *language* does not have any construct that would let us create such a closure anyway.

**Comment by gzm0** [comment]
I think we should add them in the IR **and** we should add support in the language for them (`js.FunctionRest1`, etc... ?). The current way to create an anonymous JS function with varargs (via JSExport) is just bad....

**Comment by sjrd** [comment]
Hum, I did not consider that. That would two more sets of `js.XFunctionN` types (we also need the `This` variant).

I'll investigate the implications. It seems like at the IR level, we just need to support `Closure` with rest parameters.

**Comment by gzm0** [comment]
Yeah, I know. It's a bit ugly, but it will be a blocker to the interop eventually I believe... (and it is relatively easy to support).

**Comment by gzm0** [comment]
By the way, I think we should explicitly forbid the `arguments` variable in the IR, once we have made this change.

**Comment by sjrd** [comment]
Yes, obviously.
