### ISSUE TITLE
Node.js isn't connected (on Travis)

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#1546]
See this build, for example:
https://travis-ci.org/japgolly/scalacss/builds/54414973
Reported on the chat by @japgolly

**Comment by sjrd** [comment]
I suspect we're simply too strict on the connection time. It is currently set to 1 s. By comparison, the same timeout for PhantomJS is 10 s. I'll increase it to 5 s, and hopefully that will solve the issue.

**Comment by japgolly** [comment]
It might be nice to have this configurable somehow - even via a quick & dirty hack if need be. All my SJS stuff fails on Travis and it's hard to debug.

FYI I even have problems with Phantom JS (on scalajs-react). Those builds are worse: it runs a few tests, threads (presumably) crash and burn and then it happily reports that all 8 of your tests passed (despite there being 100+ tests).
https://travis-ci.org/japgolly/scalajs-react/builds/45252395

**Comment by sjrd** [comment]
PhantomJS is a weird beast. We still have long-standing issues with it, e.g., #1457.

> It might be nice to have this configurable somehow - even via a quick & dirty hack if need be. All my SJS stuff fails on Travis and it's hard to debug.

I guess I could make [the val](https://github.com/scala-js/scala-js/pull/1547/files) `protected`, then you would be able to hack around it by subclassing `NodeJSEnv`?

**Comment by tindzk** [comment]
I encountered the same problem. As per https://github.com/scala-js/scala-js/issues/2642#issuecomment-276802048, adding the following lines to `.travis.yml` [fixed the tests](https://travis-ci.org/sparsetech/pine/builds/240419469):

```
script:
  sbt ++$TRAVIS_SCALA_VERSION 'set parallelExecution in ThisBuild := false' test
```
