### ISSUE TITLE
Integrate with JSPM

### ISSUE THREAD

**Issue by atrauzzi** [scala-js/scala-js#1552]
Check out JSPM here: http://jspm.io/

This tool seems to be getting a lot of attention for simplifying workflows that target the browser.  It would be cool if there was some way you could get in as a plugin for the ecosystem.

**Comment by sjrd** [comment]
Hi,

Thanks for the pointer, but this outside the responsibilities of Scala.js. It's completely orthogonal. The closest thing would be [sbt-web](https://github.com/sbt/sbt-web) and all their assets management. I guess you could write a plugin for jspm based on sbt-web, or simply sbt. But in any case, it's completely orthogonal to Scala.js, so it should not be part of the Scala.js project.

**Comment by atrauzzi** [comment]
Supporting tooling with official plugins makes your offering more appealing.  I suppose you can hope for a smattering of inferior options to emerge over time.  But if you're interested in adoption, sometimes it helps to build roads to making this project easier to use.

**Comment by sjrd** [comment]
I disagree. It only leads to more coupling between projects. It's best to just write an additional, independent project, that links both things, if that even makes sense. Here I think it doesn't even make sense to Scala.js itself. As I said, this is the kind of responsibility that sbt-web takes and is made for.

Contrary to other systems like GWT, Scala.js is *not* an all-powerful platform that tries to solves all problems. Scala.js solves *one* problem: compiling Scala to JavaScript. The rest is up to other tools, that can be composed modularly.

**Comment by atrauzzi** [comment]
Obviously it wouldn't be in this repository.

**Comment by sjrd** [comment]
Then this is not the right place to discuss it ;-) I suggest you send a mail on the mailing list. Thanks.
