### ISSUE TITLE
Missing impl's in Integer, Char, Long and String

### ISSUE THREAD

**Issue by InTheNow** [scala-js/scala-js#1553]
As mentioned in #1549, the following are missing from javalib:

- ```Integer toString(i: scala.Int, radix: scala.Int): String, Integer highestOneBit(i: Int): Int```
- ```Char forDigit(digit: Int): Char , def forDigit(digit: Int, radix: Int): Char```
- ```Long toString(value: Long, intRadix: Int): String```
- ```String  regionMatches(s: String, ignoreCase: Boolean, toffset: Int, other: String, ooffset: Int, len: Int): Boolean ``` 
- ``` def regionMatches(s: String, toffset: Int, other: String, ooffset: Int, en: Int): Boolean``` 

This are/were implemented as part of  #1549, I can lift them as a new PR

**Comment by sjrd** [comment]
If not a new PR, they should at least be in separate commits. Each in a separate commit, actually, except related ones. So `{Integer,Long}.toString` would go together, and for `regionMatches` together.

**Comment by InTheNow** [comment]
I'm happy to do separate PR's as you suggest, as it's easier to squash changes later on. I'll proceed like this, if that's OK

**Comment by InTheNow** [comment]
Ok - will add as separate commits in #1549
