### ISSUE TITLE
Allow overriding path prefixes

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#1564]
If a library (as in Scala.js library) I use depends on, say, jQuery.js, and I need a webjar (or library) that bundles jQuery.js as well, there is no way I can resolve this conflict (before that, you could use filter for everything. But now it comes after the first resolution step).

**Comment by sjrd** [comment]
Ah, good point.

**Comment by gzm0** [comment]
I will introduce a `ManifestFilter`, that operates on `JSDependencyManifests`, rather than `FlatJSDependencies`. Further, I will add a factory for a filter, that lets you re-interpret a dependency from given origins.
