### ISSUE TITLE
numerous Boxed and memory errors

### ISSUE THREAD

**Issue by antonkulaga** [scala-js/scala-js#1565]
After switching to 0.6.x (in all 0.6.0 -0.6.2) I started to get numerous memory related errors in different project although I already increased sbt xmx to 3G 
Depending on the project I get either Boxed Error or Not enough space or GC error.
A good example of such erorr is https://github.com/w3c/banana-rdf/issues/250

**Comment by sjrd** [comment]
Duplicate of #1525?

**Comment by antonkulaga** [comment]
This errors occured even though I had dependencyOverrides += "org.scala-js" %% "scalajs-sbt-test-adapter" % "0.6.0"

**Comment by gzm0** [comment]
@antonkulaga can we close this? Do you still see these issues?

**Comment by antonkulaga** [comment]
I do have those issues but I would prefer to wait for 0.6.3 to see if they will dissapear
