### ISSUE TITLE
Tutorial: can not find main

### ISSUE THREAD

**Issue by donnut** [scala-js/scala-js#1573]
When setting up the Hello World tutorial, in step 1 sbt complains:
```
> run
[warn] No main class detected
[info] Fast optimizing /Users/donnut/dev/scala/scalajs/target/scala-2.11/scala-js-tutorial-fastopt.js
[trace] Stack trace suppressed: run last compile:scalaJSLauncher for the full output.
[error] (compile:scalaJSLauncher) No main class detected.
[error] Total time: 2 s, completed Mar 28, 2015 2:15:03 PM
```
I'm using scala 2.11.6, sbt 0.13.7.
Any thought on what can go wrong here?

Thanks

**Comment by gzm0** [comment]
Welcome to Scala.js. This is not the right place to ask questions like this. Please use SO or the mailing list.

Have you defined the main class `TutorialApp`? sbt cannot find it.

**Comment by gzm0** [comment]
If you need further assistance on this, please create an SO post or ask on the mailing list or gitter and cross reference here.
