### ISSUE TITLE
better async error reporting

### ISSUE THREAD

**Issue by antonkulaga** [scala-js/scala-js#1578]
I have a lot async things in my app and it is a huge pain to debug them, cause I get errors like:
```
Failure in async execution: TypeError: Cannot read property 'name__T' of nullSystem.scala:264 $c_jl_JSConsoleBasedPrintStream.doWriteLine__p4__T__VSystem.scala:237 $c_jl_JSConsoleBasedPrintStream.printString__p4__T__VSystem.scala:226 $c_Ljava_io_PrintStream.println__T__VQueueExecutionContext.scala:16 $c_sjs_concurrent_QueueExecutionContext$.reportFailure__jl_Throwable__VPromise.scala:32 $c_s_concurrent_impl_CallbackRunnable.run__VQueueExecutionContext.scala:11 (anonymous function)
```
It is possible (at least at fast.opt mode) to report async function that crashed?

**Comment by lihaoyi** [comment]
FWIW this was also a huge pain point for me working on www.scala-js-fiddle.com. I never found a good solution for it

**Comment by ngbinh** [comment]
same here! I am interested in the solution

**Comment by sjrd** [comment]
Can someone write a short reproduction, please?

**Comment by sjrd** [comment]
I guess [this](https://github.com/scala-js/scala-js/blob/master/library/src/main/scala/scala/scalajs/concurrent/RunNowExcecutionContext.scala#L13) and [that](https://github.com/scala-js/scala-js/blob/master/library/src/main/scala/scala/scalajs/concurrent/QueueExecutionContext.scala) are to blame. They should just `t.printStackTrace(System.err)`. I wonder why they didn't do that in the first place ... Maybe `printStackTrace` was not implemented at the time these were written.
