### ISSUE TITLE
Excessive LoadModule usage

### ISSUE THREAD

**Issue by colinrgodsey** [scala-js/scala-js#1588]
Assumptions
----------------
* Static object initialization is ~~*murky and largely undefined behavior* already~~ class-loader driven with initialization happening in the static space *-verified-*. (§5.4)
* Scala ~~may~~ will optimize static *final val* fields ~~methods~~ into pure static access (constant expressions) *-verified-* (§4.1 via §6.24)
* Static object initialization is potentially side-effecting, with initialization order being provided ~~naturally by the 'first reference' of such objects~~ by the class-loader (first class dereference in the VM) *-verified-*. (§5.4)
* Can deterministically deduce whether an object init causes side-effects. *Sort of?? We can determine if the constructor contains only pure expressions right? If a module has just methods, it should really have 0 constructor expressions, and we can measure that.*
* Scala will set the singleton reference to a static object before its init code is run (potentially leaking the 'this' reference during construction, causing null vals and all that fun) *-verified-*. 
* To fully mimic the 'static space' initialization, we need to imitate class-loading by executing the static space on first class reference/load. *-verified- this is already happening. Idempotent class-load checks already exist, everywhere, but are not necessarily the best option for JS*
* ~~Getters on the JVM are basically free. They are more costly in JavaScript.~~ Class-loader static-space singleton initialization of scala objects is basically free on the JVM and is an implicit mechanic of the JVM at every initial class dereference (the 'class load'). Dereference occurs with no explicit method calls. The current scalajs lazy checks are a manual construct in JS per every dereference, which has different performance characteristics. *-verified?-*

Suggestions
----------------
* Remove side-effect-only [  a = (BlahModule(), 0)  ] LoadModule calls if we can guarantee it's already been loaded *-verified-*.
* ~~Remove side-effect-only LoadModule calls all together (does scala do this?)~~.  *see prior*
* Reference the static object itself instead of LoadModule if we can guarantee it's been loaded *-verified-*.
* ~~LoadTime~~ Link-time generation of 'pure' static objects that require no init (nothing side-effects in the static init space, especially useful with objects that contain just methods) *see comments about method-only modules above*

Questions
-------------
* ~~If values or defs are inlined, do we really need to load the module? Does scala do this? It would seem to me that the normal class-loader dynamic would avoid referencing static-space on an object if you've already inlined its content.~~ *Apparently scala will not inline method calls for you that are not private to your scope. I've found no way to make it do anything like that on its own. I have seen scala-js do this tho, but I really do not understand the context or what the rules are about inlining methods/defs. Black magic?*

Examples
-------------
(look for ```$m_Lorg_HdrHistogram_Histogram$();``` or ```H();``` in the full opt)
* fastOpt 1.6.3  - https://gist.github.com/colinrgodsey/dbc39d6c7a382e6a62bd
* fullOpt 1.6.3 - https://gist.github.com/colinrgodsey/b3e02602c5f113244cb3
* fastOpt 1.6.3 with changes - https://gist.github.com/colinrgodsey/5d1d988afa907d2f8221

Proposed Changes
-------------------------
* js.Env with tracking of initialized modules https://github.com/scala-js/scala-js/compare/master...colinrgodsey:wip-loadmodule

User group discussion: https://groups.google.com/forum/#!topic/scala-js/Vj-jRKe7vEA

**Comment by colinrgodsey** [comment]
My proposed changes so far are here: https://github.com/scala-js/scala-js/compare/master...colinrgodsey:wip-loadmodule?expand=1

Definitely still a WIP, but it greatly helps my use case so far.

**Comment by sjrd** [comment]
There are certainly improvements that can be brought to module initialization, but it is not simple. Here are a couple comments on your items.

> Static object initialization is murky and largely undefined behavior already

Hum, no, it's pretty well defined, actually: first access to an object causes it to initialize, just like `lazy val`s.

> Scala may optimize object methods/fields into pure static access

*If* it can prove that initializing this object is either 1) already done or 2) pure. Note that currently, scalac/JVM never does this, even under `-optimize`

> Can deterministically deduce whether an object causes side-effects

Cannot. This is an undecidable problem. However, we can approach the issue with a safe approximation: in some cases we can prove that initializing an object is a pure op (but we will also miss some pure object inits and "think" they are not).

> Scala will set the singleton reference to a static object before its init code is run (potentially leaking the 'this' reference during construction, causing null vals and all that fun)

It is initialized right after calling the super constructor in the constructor of the object. Between the beginning of the constructor, and until the end of the super constructor, accessing the reference to the object is undefined behavior [but can be required to give `null`](https://github.com/scala-js/scala-js/pull/1558) like it does on the JVM. After the call to super constructor, the `StoreModule` instruction initializes the reference, and therefore accesses to the object are legal and specified (there still could be parts of the object that are not initialized, until the constructor terminates).

> Getters on the JVM are basically free. They are more costly in JavaScript.

What kind of getters? You mean methods that read a field? They're systematically inlined in Scala.js and so they are free.
If you mean ES5 getters, then, indeed, they are costly.

> Remove side-effect-only LoadModule calls if we can guarantee it's already been loaded.

OK

> Remove side-effect-only LoadModule calls all together (does scala do this?).

Scala doesn't, and we cannot. That would break code.

> Reference the static object itself instead of LoadModule if we can guarantee it's been loaded.

OK

> LoadTime generation of 'pure' static objects that require no init (nothing side-effects in the static init space, especially useful with objects that contain just methods)

LoadTime -> link-time. Yes, I've been willing to do this, but it is not a trivial change, although it can definitely be done.

> If values or defs are inlined, do we really need to load the module? Does scala do this?

Yes, we really need to. Scala/JVM does it. Not doing so would break code.

**Comment by colinrgodsey** [comment]
*Static object initialization is murky and largely undefined behavior already*
I guess it is pretty well defined in the fact that its executed in a static block of the class, but it is specifically 'class-loader' driven. Other underlying VMs are free to violate this ordering AFAIK. 

Scala via JVM normally does not have to worry about this at all, as its assumed to just be init'd when the class loads (and it really only guarantees that the classloader is called for any computed static values).

If you look at the way scala emits ByteCode for inlines values, it does/can completely drop the class reference to the other class (this is the murkiness im talking about. depending on inlining, module initialization can change in unexpected ways).

```scala
object A {
        @inline final val a = 1
        final val b = math.sqrt(7)
}

object B {
        final val a = A.a
}
```

```java
public final class B$
{
  public static final  MODULE$;
  private final int a;

  static
  {
    new ();
  }

  public final int a()
  {
    return 1;
  }
  private B$() { MODULE$ = this; }

}
```

**Comment by colinrgodsey** [comment]
I'm assuming this behavior has also changed between scala versions. I take that as a cue that this is undefined behavior, or at least behavior that is not to be relied upon. Given that they're relying on VM mechanics to lazy-load the static space, I think that gives us some freedom to implement VM specific mechanics that play well with JS. 

One of the things I like most about scala-js is that it gives up some of the JVM specific mechanics to gain more 'mechanical sympathy' for the JS world. I like to think of Scala as something that could/should emit to several other languages, and I feel like that's why they don't post defined behavior for some of these JVM specific mechanics. 

Lots of what goes on 'under the hood' definitely effects how you use scala, but you're often discouraged from relying on it, and you're given tons of tools/paths to free yourself from needing to think about it (auto-boxing, lazy vals, objects, package objects, etc.). I feel like any problems that might be caused by changing the LoadModule mechanics will be based in code that is already brittle and subject to similar initialization issues that may occur in different version of scala for the JVM.

With that said, I understand we can't exactly abolish it, but there are definitely some 'solvable' cases where we can guarantee when a module is loaded, and given the above 2.11.6 behavior, some cases where we can totally drop it.

**Comment by lihaoyi** [comment]
I wonder how many module initializers are trivially pure, or can be
constant-folded to be trivially pure? I suspect that it'll be quite a large
portion.

**Comment by colinrgodsey** [comment]
I know for the code I'm trying to write (conversion of HdrHistogram), inlines are almost useless to me because of the LoadModule use. Im writing the scala specifically to take advantage of js.Dynamic types, and that involves some extra sugar that is not compiling down in an favorable way. 

I'm trying to write some of the more performance-intensive portions in a way where I can write 'javascript in scala' basically- catering to a specific desired JS output. Using objects, inlining, and AnyVals allows me to create a handy DSL for healing with native JS the way I want to, but its producing rather non-optimal JS when dealing with modules.

I really do not want to write this in pure JS. Scalajs does really amazing things like inlining iterators and crazy stuff like that, which I really want to take advantage of and not copy-pasta my own JS everywhere (or produce slow overly-abstract-but-readable manual JS). I want to really own think of JS as some kind of low-level bytecode. You should be concerned with its existence and how it works, but you dont want to write things in it.

**Comment by sjrd** [comment]
Dropping load modules for `final val`s in top-level objects is actually specified in the Scala spec. (See constant expressions) In all other cases, they are retained.

**Comment by sjrd** [comment]
Btw, be wary of trying to outsmart Scala.js for performance by using `js.Dynamic`. You might think you write better code where in fact you're not. For example, `(a+b)|0` produced by Scala.js is faster than `a+b` on modern VMs.

You should measure the difference in performance before assuming that hand-written code is faster. There is a reason Scala.js outperforms hand-written js in some of our benchmarks.

**Comment by colinrgodsey** [comment]
So the patch I have should remove any leftover LoadModules from constant expression inlining, which sounds like its ok as far as the spec. 

I'm actually trying to side-step long emulation, in a way which is rather specific to this use case. I'm aware of some of the int optimizations (a la asm.js) and  similar detection for 'true integer' blocks, and am still using them in the 'native-ish' code. I'm still casting to regular scala ints and scala types whenever possible, I just have this specific type at a few points. 

Whether or not any of the above will be entirely beneficial to me.... we'll see. But for now I'm kind of caught up on this LoadModule stuff.

**Comment by colinrgodsey** [comment]
@sjrd I cleaned up the above description, I think we're all lined up? I got extra caught up trying to figure out how method inlining works, but im just claiming unknown magic for now.

**Comment by sjrd** [comment]
The thing about `final val`s is not only allowed but mandatory. It is handled by scalac way before Scala.js even kicks in. It's simply constant folding. This is spec'ed. So your second bullet is completely irrelevant in this discussion, since when Scala.js kicks in, the would-be involved LoadModules are already not there at all. As far as this discussion is concerned, all LoadModules must stay or keep their semantics.

Regarding method inlining, well, that's because the Scala.js optimizer is kick ass. It can do much more than Scala/JVM because it can assume closed world. It all happens in [OptimizerCore.scala](https://github.com/scala-js/scala-js/blob/master/tools/shared/src/main/scala/org/scalajs/core/tools/optimizer/OptimizerCore.scala), along with all other optimizations.

**Comment by colinrgodsey** [comment]
I'm thinking that in my examples, the inlining im seeing must be caused by the scalajs optimizer and not just the constant folding done in the scala compiler, because im seeing LoadModules in a side-effect only  position in the output (BlahModule$(), 0). So these can still be optimized out, at least in the desugaring phase. 

I think we agreed there are some situations where the LoadModule 'desugaring' behavior can be changed. I'm not proposing changing any of the actual LoadModule tree creation, just how its emitted to JS.

`Remove side-effect-only LoadModule calls if we can guarantee it's already been loaded.`
`Reference the static object itself instead of LoadModule if we can guarantee it's been loaded.`

Correct me if I'm wrong, but this should still be possible. This is what I have currently in my patch, and it seems to work perfectly for my project (and obviously the test suite tests).

I've also been reading through the spec and §5.4 seems to be pretty explicit that top-level objects are just initialized via static space (and is really the only code run in static space). To me, this seems like a cue that is still all VM specific. Looking into the Java spec on these things, they seem to list reasonable rules about optimizing class-loading: https://docs.oracle.com/javase/specs/jls/se7/html/jls-12.html#jls-12.4.2

```
Code generators need to preserve the points of possible initialization of a class or interface, inserting an invocation of the initialization procedure just described. If this initialization procedure completes normally and the Class object is fully initialized and ready for use, then the invocation of the initialization procedure is no longer necessary and it may be eliminated from the code - for example, by patching it out or otherwise regenerating the code.

Compile-time analysis may, in some cases, be able to eliminate many of the checks that a type has been initialized from the generated code, if an initialization order for a group of related types can be determined. Such analysis must, however, fully account for concurrency and for the fact that initialization code is unrestricted.
```

**Comment by sjrd** [comment]
> I'm thinking that in my examples, [...]

Yes, you're right.

> I think we agreed [...]

Yes.

> It also seems to me that 0-side effect objects [...]

Absolutely.

> To me, this seems like a cue that this is still VM specific behavior.

Yes, and no. Lots of stuff in the Scala spec differ to "the VM" for lots of behaviors. But we have to keep in mind that this spec was written thinking that "the VM" was always a JVM. So every time we choose *not* to behave like the JVM, we're breaking the Scala spec. We must not do so lightly. Sometimes it's ok to do it, but we should weigh the benefits vs the potential amount of code that people actually write and would break.

I'm happy to welcome any improvements that result in less load-modules as long as this doesn't change the behavior. If we're going to change the behavior, this is a different category of change, that we need to consider separately.

**Comment by colinrgodsey** [comment]
Awesome! I'll work with those few points above as action items and try to produce a clean PR. 

I'll move the bigger picture convo to a new issue after that.

**Comment by colinrgodsey** [comment]
I'll make a new issue for the action items here too

**Comment by colinrgodsey** [comment]
defering to #1593 for now
