### ISSUE TITLE
Feature request: add JSDependency.minified()

### ISSUE THREAD

**Issue by jducoeur** [scala-js/scala-js#1592]
One of the most common problems with SJS at the moment is its handling of minified JavaScript dependencies.  When you want to use an existing JavaScript library, you generally want to use the "raw" form during development, so you can trace into it during debugging (in, eg, the Chrome debugger), but the "minified" form during production, for efficiency.  Most JS libraries ship both forms, and it is assumed in the JS world that you use them this way.

But we have no elegant way of representing that in build.sbt, so folks often wind up writing duplicate jsDependencies trees for development and production.  Worse, there is no good way for a facade library such as scalajs-jquery to declare both forms such that the consuming application can use them, requiring considerable hackery to work around.  This is inconvenient for anyone who really delves into the JS during debugging, and I expect it to be an adoption hurdle for folks coming from the JS side of things -- they generally care about this a lot.

So I propose that we should add a new clause to JSDependency, named `minified()`. This would be parallel to `dependsOn()` and `commonJSName()`, and look something like this in practice:
```
jsDependencies += "org.webjars" % "jquery" % "2.1.3" / "jquery.js" minified "jquery.min.js"
```
This "minified" name would get carried through the jsDependencies pipeline, including from library to application, but would be largely invisible to most of the code; in particular, the "raw" name would always be used for dependency calculation.

Along with this, we would add a Setting named something like `useMinifiedJS`. The only place where minified would matter is in packageJsDependencies -- if `useMinifiedJS` is set to true, it would use the minified path instead of the "raw" one.

I'm sure that there are some subtleties I'm missing, but in principle this seems right: it ties the minified version closely to the "raw" one, in such a way that the dependency code can completely ignore it, removing the need for the sort of completely alternate jsDependencies trees that we see in, eg, @ochrons' tutorial. This should make things easier to reason about, and reduce bugs. It would allow libraries to declare both forms easily. And it should be straightforward enough to add `useMinifiedJS` to folks' Dev vs. Prod pathways in their build.sbt files, the same way they choose fastJSOpt vs. fullJSOpt.

**Comment by gzm0** [comment]
I think that makes sense. It is also plausible to implement this in a backwards compatible manner, as the fallback if no minified exists, should be the normal version anyway.

The dependency tree and linearization would in any case be calculated based on the non-minified versions. I hope this is acceptable.

@sjrd opinions?

**Comment by sjrd** [comment]
Sounds good and well thought-of. :-)

**Comment by jducoeur** [comment]
> The dependency tree and linearization would in any case be calculated based on the non-minified versions. I hope this is acceptable.

I can't think of any cases where that isn't correct.  (Indeed, I would worry about any library where it wasn't...)

**Comment by gzm0** [comment]
Actually there is one minor point I'm not so sure of: Should we have two different `packageJSDependencies` tasks (just like we have `fastOptJS` and `fullOptJS`), or should we make it depend on another setting?

The thing which is ugly with the setting, is that the file contents of `<name>-jsdeps.js` depend on a setting (which is IIUC not optimal).

Another option would be to change the artifact path to `<name>-jsdeps.min.js` if we are in `useMinifiedJS` mode...

WDYT?

**Comment by sjrd** [comment]
Or simply have `packageJSDependencies` systematically produce *both* `<name>-jsdeps.js` and `<name>-jsdeps.min.js`.

**Comment by sjrd** [comment]
But I think having two tasks is better.

**Comment by jducoeur** [comment]
Hmm.  I don't think I have a passionate opinion here.  Having a second task adds slightly to the boilerplate, but only to a constant degree, and having a separate -jsdeps.min.js means that, eg, my .html file goes from saying:
```
    <script src="@routes.Assets.at("querkiclient-jsdeps.js")"></script>
    
    @if(isProd) {
      <script src="@routes.Assets.at("querkiclient-opt.js")" type="text/javascript"></script>
    } else {
      <script src="@routes.Assets.at("querkiclient-fastopt.js")" type="text/javascript"></script>
    }
```
to
```
    @if(isProd) {
      <script src="@routes.Assets.at("querkiclient-jsdeps.min.js")"></script>
      <script src="@routes.Assets.at("querkiclient-opt.js")" type="text/javascript"></script>
    } else {
      <script src="@routes.Assets.at("querkiclient-jsdeps.js")"></script>
      <script src="@routes.Assets.at("querkiclient-fastopt.js")" type="text/javascript"></script>
    }
```
So long as the generated launcher does the right thing (for those who are using it), it seems likely to be fine...

**Comment by abrighton** [comment]
Did you decide not to add the "useMinifiedJS" option?

**Comment by jducoeur** [comment]
@gzmo did the work, but yeah - the general sense was that using the minified version in fullOpt is essentially always correct, so it's automatic, IIRC...

**Comment by sjrd** [comment]
There are two files generated: `xyz-jsdeps.js` and `xyz-jsdeps.min.js`. The latter may be generated only by fullOptJS by default, IIRC. Just include the one you want in your HTML.
