### ISSUE TITLE
Double-definition in a JS literal generates invalid ES5 JavaScript

### ISSUE THREAD

**Issue by jducoeur** [scala-js/scala-js#1595]
The example code that caused this was essentially:
```
js.Dynamic.literal(
  url = "http://something.com/",
  // ... other stuff
  url = "http://somethingelse.com/"
)
```
The actual error from test was swallowed, but @gzm0 says that PhantomJS reports a "parse error" on this situation -- the output JS is considered invalid.

Conversation on Gitter suggests that the compiler should catch this double-definition before we get to runtime.

**Comment by sjrd** [comment]
So, actually, this is not an error in ECMAScript 6 anymore. It is an (early) error in ES5 strict mode, but in ES6 (even strict mode) they have reverted to the ES5 sloppy mode behavior of last-definition wins. Given this, I believe we should keep the compiler and the IR as they are now, and fix `JSDesugaring` to desugar an object literal with a double definition as a series of successive assignments to an initially empty object. In ES6 output mode we wouldn't do this desugaring. (Potentially, the compiler could emit a warning.)

Actually, we could even allow non-constant keys in `JSObjectConstr` in the IR. Non-constant keys (aka computed properties) are now possible in ES6 as well (and is the reason the early errors have been canceled). Desugar could similarly transform that to gradually constructing the object when emitting to ES5.

**Comment by jducoeur** [comment]
Fine by me -- my only real concern is that the above code not cause hard-to-figure-out parse errors.  (Even those wouldn't be critical if #1594 gets fixed: it was really the combination of the two that is really bad, since the JS parser crashed and there was difficult to figure out why.)
