### ISSUE TITLE
Macro to safely cast from Scala class to JS trait

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#1596]
Write a macro to do the following with static checking:

```scala
trait Foo extends js.Object {
  def foo(x: Int): Int = js.Native
}

class Bar {
  @JSExport
  def foo(x: Int): Int = x * 2
}

val x: Bar = ???

// Macro should check this:
val y: Foo = x.asInstanceOf[Foo]
```

**Comment by gzm0** [comment]
@sjrd should we have a member `asJS` that we pimp on everything? Or rather a function in the `js` namespace?

**Comment by lihaoyi** [comment]
that's not really a cast is it? That's more a conversion since the data structure will need to be re-created for anything with attributes, which are methods in Scala but raw-attributes in JS?

**Comment by gzm0** [comment]
It is a cast, since `Bar` has `@JSExport` on `foo`. If you have `@JSExport` on an attribute in Scala, it will be implemented as a property in JS:

```scala
class Bar {
  @JSExport
  def a = 1
}

val x = (new Bar).asInstanceOf[js.Dynamic]
x.a // -> 1
```

**Comment by lihaoyi** [comment]
What about `asInstanceOf`s? Those check the prototype chain, and we allow `asInstanceOf` for Javascript classes

**Comment by gzm0** [comment]
You mean `isInstanceOf`s. Indeed, they are an issue. But I guess we will only allow the conversion for traits extending `js.Any`. These do not allow `isInstanceOf`.

**Comment by sjrd** [comment]
Don't pimp something on everything, ever. This should be a separate function.

**Comment by gzm0** [comment]
Ok. But then we have the issue that we need two type parameters but only one that you specify in general...

We could do:

```scala
js.convert(x).to[Foo]
js.asJS(x)[Foo]
js.asJS[Bar, Foo](x)
```

I don't like any of them... We could protect the pimp with an implicit at the cost of having a sensible error message... :(

**Comment by gzm0** [comment]
Things I have come up with during my first explorations and developments:

## Syntax

I propose:
```scala
js.use(x).as[Foo]
```
This allows us to not write the source type if we don't want to. `js.use` returns a value class, so there is zero overhead to this.

## Limitations

I plan to not handle the following things in the first version:

### Refinement Types
Given
```scala
trait Foo extends js.Object {
  type T
  def get: T = js.native
}

class Bar {
  @JSExport
  def get: Int = 1
}
```

This will fail:
```scala
js.use(new Bar).as[Foo { type T = Int }]
```

Note that generics (`Foo[T]`) will be supported.

### Multiple Parameter Lists

Given:
```scala
trait Foo extends js.Object {
  def do(x: Int, y: Int): Unit = js.native
}

class Bar {
  @JSExport
  def do(x: Int)(y: Int): Unit = js.native
}
```

This will fail:
```scala
js.use(new Bar).as[Foo]
```

WDYT?

**Comment by sjrd** [comment]
That seems reasonable.
