### ISSUE TITLE
Link even when running with Rhino

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#1600]
There isn't any good reason anymore that running with Rhino doesn't link. This would eliminate the discrepancy between Rhino and Node.js/PhantomJS runners that Rhino only reports linking errors at runtime, rather than at link time. This sometimes confuse people, who think their code works as long as they use Rhino to test, and are surprised to see linking errors once they go to fastOptJS or running with Node.js/PhantomJS.

We could even fastOpt (but not fullOpt) if we add an interface that returns a `LinkedUnit` from fastOpt rather than always emitting JS code.

**Comment by gzm0** [comment]
IIRC there are a couple of code paths which are only tested if we run with Rhino. (Intrinsics?) Or are these tested as well if we disable the optimzer?

**Comment by sjrd** [comment]
These are tested when we disable the optimizer.

There are also code paths that are indeed only tested on Rhino, such as polyfills when TypedArrays are not available. But this is not impacted by whether we optimize or not.

**Comment by gzm0** [comment]
Ok. Sounds good to me.
