### ISSUE TITLE
Option to @JSExportDescendent{Classes,Objects} to ignore invalid descendants

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#1604]
For a class/object to be exported, it must be
* Public
* Top-level
* (and therefore non-anonymous)

When using `@JSExportDescendentClasses` and `@JSExportDescendentObjects`, this causes compilation errors for subclasses/objects that do not satisfy these requirements.

Usually, this is what we want, but sometimes -- and this is true for ScalaTest -- we would prefer these to be simply silently ignored (hence not exported).

I suggest we add an option to these two annotations that would make the compiler silently ignore non-public and nested descendants. Possible name for the option: `ignoreInvalidDescendants`. It would of course default to false.

**Comment by sjrd** [comment]
@gzm0 WDYT?
/cc @cheeseng

**Comment by gzm0** [comment]
The request of having this functionality seems very reasonable. I am wondering whether an option is the right thing as opposed to another annotation... I'd also consider to simply call the parameter `force`.

**Comment by bvenners** [comment]
Hi Scala.js-ians,

FYI, ScalaTest's Scala.js support is essentially blocked waiting on an enhancement like this. Upshot is we have so many places where we have anonymous subclasses of Suites in our own tests that it isn't practical for us to port ScalaTest's tests of itself to run on Scala.js without this feature. And our philosophy, not surprisingly, is if we can't test ScalaTest on Scala.js, we don't consider it "working" on Scala.js if if ScalaTest itself is compiling on Scala.js. (Scalactic is fully tested under Scala.js, so that one is done.)

Do you have any idea when this might get added? What would help us more forward is even a snapshot with this in place, though a milestone would be better than a snapshot. I'd like to get an idea of timing so we can plan when to do what for our upcoming releases.

Thanks.

Bill

**Comment by gzm0** [comment]
@bvenners I can hack this over the weekend which will make it into 0.6.3. Hopefully released in a couple of weeks. Is that enough of a timeline?

**Comment by gzm0** [comment]
@sjrd after more thinking, we shouldn't make separate annotations, simply to avoid explosion. I still prefer the name force over `ignoreInvalidDescendants` mainly due to brevity. WDYT?

**Comment by sjrd** [comment]
I'm afraid `force` implies "force exporting this class, even if it's private/anonymous/nested", which doesn't make any sense. It should ignore instead.

**Comment by bvenners** [comment]
Weekend hack would be awesome. Please post here when you have something for us to try. Thanks!

**Comment by gzm0** [comment]
> I'm afraid force implies "force exporting this class, even if it's private/anonymous/nested"

That is true. Let's use `ignoreInvalidDescendants` then.

Another thing: I am a bit concerned that for ScalaTest's specific case, this is actually not the right tool. For everything else but their own tests, `ignoreInvalidDescendants` should be false (which is of course not possible).

It seems that selective disabling might be more reasonable... (but how to annotate anonymous classes?).

**Comment by sjrd** [comment]
Here are parts of a private discussion that are relevant to this issue.

@cheeseng:
> JSExportDescendentClasses seems to prevent private/nested/anomynous subclass, and actually we have quite many tests written like this: 
>
>     val suite = new FunSuite { ...}
>     suite.run()
>
> and since we annotate JSExportDescendentClasses at FunSuiteLike level (which FunSuite extends), scala.js raise numerous compilation errors.  Is there anyway we can go around this rule?  If not may be we can no longer annotate our style traits with @JSExportDescendentClasses and need to do it for all the test classes instead, that's not very cool for our users indeed.

@sjrd:
> The case of private/nested/anonymous subclasses is tricky. I'm not sure what's the best course of action, here. One question first: for such classes, do they have to be instantiable via their classOf? I guess not for anonymous subclasses (it'd be tricky to get the classOf in the first place), but maybe for private/nested subclasses? If not, we can probably come up with a relatively easy solution (an option or an alternative JSExportDescendentClasses that silently ignores anything but public top-level subclasses). If they do have to be instantiable, then it's going to be even trickier.

@cheeseng:
> We do not need them to be instantiaable via their classOf, indeed if they do then the current behavior of JSExportDescendentClasses is correct, I think the relatively easy solution you proposed will be more than enough (e.g. JSExportPublicDescendentClasses that will only export public descendent class and just ignore the private/nested/anomynous subclasses).

From this, it seems to me that the proposal perfectly fits the needs.

**Comment by gzm0** [comment]
Indeed. I'll proceed with implementing this, then.

**Comment by gzm0** [comment]
Question: Should this trigger an error or not:

```scala
@JSExportDescendantClasses(ignoreInvalidDescendants = true)
trait Foo
class Bar__ extends Foo // <- having __ in exported name is not allowed
```

While this should technically be ignored, it could be **very** unintuitive and hard to debug.

Another option would be to add a compiler flag to warn in these cases (but that's kind of unnice as well).

**Comment by sjrd** [comment]
Hum ... Good question. I believe the only reasonable thing to do is to ignore it as well, for regularity. A Scala class with `__` is unlikely anyway. It's already unlikely to have a single `_` ^^

**Comment by gzm0** [comment]
Ok.

**Comment by gzm0** [comment]
What happens in this case?

```scala
@JSExportDescendantClasses
trait Foo

@JSExportDescendantClasses(ignoreInvalidDescendants = true)
trait Bar extends Foo

val x = new Bar { }
```

IMO we should fail at `trait Bar`. Otherwise we violate a sort of meta Liskov Substitution Principle. The other way around could be allowed though:

```scala
@JSExportDescendantClasses(ignoreInvalidDescendants = true)
trait Foo

@JSExportDescendantClasses
trait Bar extends Foo

val x = new Bar { } // Compiler error
val y = new Foo { } // OK
```

**Comment by sjrd** [comment]
It should fail at `new Bar { }`. The rationale is that exports are all *cumulative*, not *overriding*. So `new Bar { }` inherits both the `@JSExportDescendantClasses` and should comply with all of them. The one without `ignoreInvalidDescendants` causes an error.

But if you declare `class Baz extends Bar` at the top-level, it's fine: it complies with all its inherited export annotations.

**Comment by gzm0** [comment]
Ok. That also makes it easier to implement :P

**Comment by sjrd** [comment]
@bvenners The fix has landed in master. Use this annotation:
```scala
@JSExportDescendentClasses(ignoreInvalidDescendants = true)
```
If you could try at least locally that it indeed fixes your issue, that would be great. 

I'll try to schedule a release end of next week or so.

**Comment by cheeseng** [comment]
@sjrd @gzm0 @bvenners @JSExportDescendentClasses(ignoreInvalidDescendants = true) works perfectly and fixed the blocking issue, we're now progressing in our tests in the following branch: 

https://github.com/cheeseng/scalatest/tree/scala-js-0.6.3-SNAPSHOT

We shall merge the branch into scalatest/scalatest's 2.3.x branch once scala-js 0.6.3.

Thank you very much for your help!

**Comment by sjrd** [comment]
Excellent. Thanks for your tests!
