### ISSUE TITLE
Char#isUpper behavior diverges between Scala.js/Scala-JVM

### ISSUE THREAD

**Issue by lihaoyi** [scala-js/scala-js#1646]
```scala
scala> ')'.isUpper
false

scala-js> ')'.isUpper
true
```

`Char#isLower` also shares this behavior, discovered porting https://github.com/lihaoyi/fastparse to Scala.js

**Comment by InTheNow** [comment]
it is possible that this is associated with an old issue - https://github.com/scala-js/scala-js/issues/964#issuecomment-62422223 - specifically the lack of `c.isLetter` as some implementations add a call to this as part of the `isUpper` and `isLower` checks.

**Comment by lihaoyi** [comment]
I've taken to just [pre-computing](https://github.com/lihaoyi/fastparse/blob/low-level-intrinsics/utils/shared/src/main/scala/fastparse/Utils.scala#L10-L20) and storing the bitmaps of the various [predicates I need](https://github.com/lihaoyi/fastparse/blob/low-level-intrinsics/fastparse/js/src/main/scala/fastparse/preds/CharPredicates.scala). 

Naturally this wont work for 32-bit versions of these functions, but for 16 bit the 8kb of cost seems to be ok. Probably could make that number go down even more with clever run-length-encoding

**Comment by InTheNow** [comment]
This _works_ .... (diff in Character.scala)
```
-  def isLowerCase(c: scala.Char): scala.Boolean = toLowerCase(c) == c
-  def isUpperCase(c: scala.Char): scala.Boolean = toUpperCase(c) == c
+  def isLetter(c: scala.Char): scala.Boolean =
+    !(toLowerCase(c) == c && toUpperCase(c) == c)
+
+  def isLowerCase(c: scala.Char): scala.Boolean = toLowerCase(c) == c && isLetter(c)
+  def isUpperCase(c: scala.Char): scala.Boolean = toUpperCase(c) == c  && isLetter(c)

```
