### ISSUE TITLE
@JSExport on an `apply` method is confusing

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#1647]
Exporting a method named `apply`, like this:
```scala
@JSExport
def apply(...) = ...
```
is confusing. It exports a method named `apply` to JS, but the expected behavior would be to make the enclosing object callable (with the `()` syntax). The latter is not possible to implement, given the current state of JS. But we should emit a deprecation warning in this case. If exporting an `apply` method is really what's wanted, the following syntax should be used instead:
```scala
@JSExport("apply")
def apply(...) = ...
```
which would reconcile how `@JSName` and `@JSExport` view `apply` methods.

**Comment by gzm0** [comment]
What about this?

```scala
@JSExportAll
class A {
  def apply(...) = ...
}
```

**Comment by sjrd** [comment]
Oh! That's a nasty one. What about this: we emit a warning if there is an `@JSExportAll`, and an `apply` method without any `@JSExport` annotation. The proper way to avoid all warnings would therefore be:
```scala
@JSExportAll
class A {
  @JSExport("apply")
  def apply(...) = ...
}
```

**Comment by gzm0** [comment]
Yeah, I was thinking of that as well. It sounds reasonable.
