### ISSUE TITLE
Allow export of classes inside object

### ISSUE THREAD

**Issue by yawnt** [scala-js/scala-js#1655]
In Akka classes are, most of the time, encapsulated in an outer object when they aren't exposed to the user:

``` scala
object Outer {
  class Inner {}
}
```

It's a fairly standard pattern, but unfortunately the current implementation of `@JSExport` prevents from exporting nested classes.
If we could improve the annotation system to allow for such a behaviour, it would help tremendously!
Thanks :)

**Comment by andreaTP** [comment]
:+1:

**Comment by gzm0** [comment]
This is IMO a very valid use case to have a separate way to make things reachable without exporting them to JS. The main issue with nested classes (not your example, truly nested classes, see #354) is that making them available from JavaScript is hard. Not eliminating them is trivial.

**Comment by yawnt** [comment]
my use case is a bit more complex.. take [this for instance](https://github.com/unicredit/akka.js/blob/master/akka-js-actor/shared/src/main/scala/akka/event/Logging.scala#L848)
I need to `@JSExport` it exclusively so I can dinamically instantiate it using `js.Dynamic`

**Comment by sjrd** [comment]
That use case is actually much more related to #1744 than to the ability to export a nested class. In fact, solving the "export a nested class" feature would not help your use case, as you could probably not derive the right way to instantiate the class just from its full class name, as it appears in is `classOf`.

**Comment by andreaTP** [comment]
Thanks guys, probably this allow us to remove a couple of workarounds in Akka.Js :-)
