### ISSUE TITLE
applyDynamic does not support passing a vararg parameter

### ISSUE THREAD

**Issue by yoeluk** [scala-js/scala-js#1656]
it will be nice if it did so that one can do this

```scala
js.Dynamic.literal(map.toSeq: _*)
```

**Comment by sjrd** [comment]
Yea, that's a scalac bug, actually. You don't need `js.Dynamic.literal` per se. Any `applyDynamic` causes scalac to bug out. Please report this to the scalac JIRA tracker: https://issues.scala-lang.org/

**Comment by yoeluk** [comment]
Ok thanks. I reported here https://issues.scala-lang.org/browse/SI-9308
