### ISSUE TITLE
@JSName(variable) annotation does not fail on objects and classes

### ISSUE THREAD

**Issue by helllamer** [scala-js/scala-js#1664]
```
object Constants {
  def CONST_1 = "bar"
}


import Constants._

@JSName(CONST_1)
object foo extends js.Object {
 ...
}
```
When i'm calling `fastOptJS` and `fullOptJS`, no error occurs, but it should.
When i'm running this code in browser, `foo is undefined` runtime exception occurs.
scala.js 0.6.3.

Normally, some like this must be thrown during compile:
```
[error] TestCase.scala:8: The argument to JSName must be a literal string
[error]   @JSName(CONST_1)
[error]    ^
[error] one error found
```

**Comment by sjrd** [comment]
Thanks for the report.
