### ISSUE TITLE
Adding members to JS constructor functions?

### ISSUE THREAD

**Issue by jokade** [scala-js/scala-js#1666]
Is there any way to piggyback a member onto the constructor function for an exported class (other than using `js.Dynamic.global`)? For example, when I have this class:
```scala
@JSExport
class Foo
```
I would need to define a property directly on the constructor function generated by Scala.js, i.e.:
```javascript
$e["Foo"] = function() { /* ... */ };

// any way to achieve this from within class Foo or its companion object?
$["Foo"]["bar"] = [ /* ... */ ];
```

My use case is a Scala.js binding for Angular 2, which uses properties defined on constructor functions to define "annotations" in ES5. For example:
```javascript
function AppComponent() { /* ... */ }

// add annotations to AppComponent
AppComponent.annotations = [
  new angular.ComponentAnnotation({selector: "my-app"})
];
```
It would be great if I could create the annotations array using Scala macro annotations. Thus the user wouldn't need to do anything more than adding a Scala `@Component` annotation to the `AppComponent` class :)

**Comment by sjrd** [comment]
No, there isn't any way to do that. And there won't be, I'm afraid, because that would mean executing user code at definition time of Scala.js classes, which causes endless issues with the ordering of said user code.

`js.Dynamic` is the way to go.

**Comment by jokade** [comment]
Thanks for the quick reply!
