### ISSUE TITLE
Add {Integer, Long}.lowestOneBit and Long.highestOneBit

### ISSUE THREAD

**Issue by InTheNow** [scala-js/scala-js#1675]
The methods `Integer.lowestOneBit, Long.lowestOneBit, Long.highestOneBit` are missing.

I will do a PR for this myself, as I need these for spire port.

**Comment by sjrd** [comment]
For `lowestOneBit`, IIRC there's a super-optimized bit trick. Something like `n & ~n`. (To be checked somewhere.)

**Comment by InTheNow** [comment]
yes, and I hadn't forgotten - https://github.com/scala-js/scala-js/pull/1559#discussion_r26932467
