### ISSUE TITLE
"hi".charAt(-1) throwing UndefinedBehaviorError

### ISSUE THREAD

**Issue by cheeseng** [scala-js/scala-js#1678]
In version 0.6.3, "hi".charAt(-1) is throwing UndefinedBehaviorError, not the expected StringIndexOutOfBoundException.

**Comment by sjrd** [comment]
This is expected. Index out of bounds exceptions are undefined behavior, as documented [here](http://www.scala-js.org/doc/semantics.html). So this is a won't fix.

**Comment by sjrd** [comment]
I would suggest replacing `"hi".charAt(-1)` in ScalaTest's tests by something else that reliably throws a known exception. For example `"hi".toInt`.

**Comment by cheeseng** [comment]
@sjrd Thanks for the explanation, sorry that we didn't notice that documentation, we have rewritten the tests in the way you suggested.
