### ISSUE TITLE
Wrong type of options val in org.scalajs.dom.raw.HTMLSelectElement

### ISSUE THREAD

**Issue by jn73** [scala-js/scala-js#1682]
In org.scalajs.dom.raw.HTMLSelectElement the declaration of:

```
val options: js.Array[HTMLSelectElement] = js.native
```

Should be:

```
val options: js.Array[HTMLOptionElement] = js.native
```

**Comment by sjrd** [comment]
Since this is an issue about the DOM typings, it should be reported on the repo about DOM typings: https://github.com/scala-js/scala-js-dom

**Comment by jn73** [comment]
Ok, I'll go file it there instead. Sorry for any inconvenience!
