### ISSUE TITLE
TypeError is thrown When an anonymous function passes the ScalaJS converted function in NodeJS

### ISSUE THREAD

**Issue by k-kinzal** [scala-js/scala-js#1684]
https://github.com/k-kinzal/scala-js-example-app/blob/master/src/main/scala/MyList.scala#L17-L21
https://github.com/k-kinzal/scala-js-example-app/blob/master/test/MyList.spec.js#L18-L20

I want to call a function that was converted in ScalaJS in NodeJS. But, `TypeError` is thrown.

```
{ 's$1': 'An undefined behavior was detected: function (a, b) {\n                    return a + b;\n                } is not an instance of scala.Function2',
  'e$1': 
   { 's$1': 'function (a, b) {\n                    return a + b;\n                } is not an instance of scala.Function2',
     'e$1': null,
     'stackTrace$1': null,
     stackdata: [TypeError: undefined is not a function] },
  'stackTrace$1': null,
  stackdata: [TypeError: undefined is not a function] }
```

Do not be able to pass an anonymous function from NodeJS?

**Comment by sjrd** [comment]
This is a usage question. Please post it [on StackOverflow](http://stackoverflow.com/questions/tagged/scala.js).

**Comment by sjrd** [comment]
As the short version of the answer: use `js.Function2[B, A, B]` instead of `(B, A) => B`. A Scala `FunctionN` is not a JS function, but a `js.FunctionN` is.

**Comment by k-kinzal** [comment]
Thank you for answer. I give up, or extract the `js.FunctionN` from converted code.

**Comment by sjrd** [comment]
I don't understand. Could you elaborate, please?
