### ISSUE TITLE
Publish CLI JAR

### ISSUE THREAD

**Issue by cretz** [scala-js/scala-js#1685]
Publish the JAR for the "cli" project to Maven for use by other tooling. Ref: https://groups.google.com/forum/?fromgroups&pli=1#!topic/scala-js/tcWk7IEosGk

**Comment by sjrd** [comment]
Maybe a saner solution to this problem would be to provide a "Java API" to the tools, at least the essential entry points?

**Comment by cretz** [comment]
Many tools use things like scalac/javac as separate processes though. ANT scripts, Bash scripts, etc. While a Java API might be nice and helpful for IDE's and other tooling, I think the CLI is still essential.

Granted my want for the CLI main classes in Maven is selfish. I didn't really want to require users to download the zip and update a configuration path manually. Maybe for long-term, OS installers (or even bundled with regular Scala) could help too.
