### ISSUE TITLE
Port JUnit

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#1690]
I figured we didn't have an issue tracking this. So just creating it, so that people know we're on it.

**Comment by nicolasstucki** [comment]
Good. As a start for tracking of progress on this issue. I've already ported a large amount of classes from JUnit to Scala.js but got stuck due to missing implementation for Java collections in Scala.js. I'm currently working on porting them.

**Comment by andreaTP** [comment]
Please, if you can provide a list of the missing java.util classes you are
going to work on we can synchronize better the effort.

**Comment by nicolasstucki** [comment]
The first set of javalib classes that I need are #1692, #1693, #1694 and #1695. @andreaTP, are you by any chance working on `concurrent.CopyOnWriteArrayList` (#1693) ?

**Comment by andreaTP** [comment]
@nicolasstucki I will first work on these:
https://github.com/unicredit/akka.js/issues/8
and looks that there are no clash.

If you need any help on #1693 , please start an implementation with ```concurrent.ConcurrentSkipListSet``` as reference and I will help you! ;-)

**Comment by andreaTP** [comment]
Anyhow, thanks for opening Issues on the topics!

**Comment by nicolasstucki** [comment]
There is currently an alpha version of Scala.js JUnit on https://github.com/nicolasstucki/scala-js-junit.
And example of a project that uses it can be found in https://github.com/nicolasstucki/scala-js-junit-examples.

**Comment by sjrd** [comment]
Awesome. You should advertise this on the mailing list and on Gitter.
