### ISSUE TITLE
Implement java.util.Arrays

### ISSUE THREAD

**Issue by nicolasstucki** [scala-js/scala-js#1694]
Implementation for `java.util.Arrays` object.

**Comment by nicolasstucki** [comment]
`java.util.Arrays` is partially implemented. This issue is to complete it.

**Comment by adriaanm** [comment]
FYI, since https://github.com/scala/scala/pull/4534 we now defer to java.util.Arrays.sort, but we do have a quickSort implementation you could reroute calls to that method to.
