### ISSUE TITLE
Fix java.util.Map.putAll type parameters definition.

### ISSUE THREAD

**Issue by nicolasstucki** [scala-js/scala-js#1700]
The current version defines it as ` def putAll[K2 <: K, V2 <: V](m: Map[K2, V2]): Unit` but is should be ` def putAll(m: Map[_ <: K, _ <: V]): Unit`.
Also need to change classes that overload it like `AbstractMap` and `ConcurrentHashMap`.

**Comment by andreaTP** [comment]
right, if you prefer I can do it...

**Comment by nicolasstucki** [comment]
I've done it as part of #1692. It was a simple fix, I opened this issue to make it evident. The fix will be applied when this I finish the implementation of #1692.

**Comment by nicolasstucki** [comment]
@andreaTP if you do a PR for some `Map` before I finish the #1692, you should include that fix directly.

**Comment by andreaTP** [comment]
at this point I think the best will be to fix this issue itself.
at least for clarity.
PR #1708

**Comment by nicolasstucki** [comment]
Good
