### ISSUE TITLE
Add nice title and logo to doc

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#1701]
The Scala.js doc currently displays the name of the open package as title and has no special logo. This is confusing when it is opened in the browser. Adding a logo and a title prefix saying "Scala.js" will help developers recognize the correct tab faster.

**Comment by antonsarov** [comment]
@gzm0 There is a favicon for API docs pages. Or do you have some other pages in mind? Of course the title prefix is still missing...

![scalajs](https://cloud.githubusercontent.com/assets/5653996/8290109/228f4ab0-1921-11e5-819f-31441376ae2b.png)

**Comment by vendethiel** [comment]
A title prefix has the downside of looking a bit worse than a postfix on google, though. "Scala.js" is small enough that it shouldn't matter, though

**Comment by gzm0** [comment]
@antonsarov Hmmm... doesn't show on Chrome Version 41.0.2272.89 (64-bit) on Ubuntu... I assume your screenshot is from firefox...

**Comment by antonsarov** [comment]
@gzm0 Correct, Firefox on Windows
