### ISSUE TITLE
Explicit setter @JSName strips `_=` suffix

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#1705]
The following:

```scala
object JS extends js.Object {
  @JSName("a_=")
  def a_=(x: Int): Unit = js.native
}

JS.a = 1
```

translates to:

```javascript
JS["a"] = 1;
```

but should translate to

```javascript
JS["a_="] = 1;
```

Note: this ticket was heavily updated. The conversation is out of date.

**Comment by gzm0** [comment]
@sjrd opinion?

**Comment by sjrd** [comment]
It's unlikely to be useful, but I don't see why it should be disallowed. If we disallow it, there's no way to access a property named `a_=` in a statically typed way at all.

**Comment by gzm0** [comment]
Hmmm... there is currently no way to set a property named like that :S

**Comment by sjrd** [comment]
Isn't there? What about this:
```scala
@JSExport("a_=")
def foo_=(v: Int): Unit = js.native
```

**Comment by gzm0** [comment]
This will strip the "_=" prefix form the name.

**Comment by gzm0** [comment]
Actually, not the export, but the corresponding `@JSName` annotation will. Grep the codebase for `stripSuffix("_=")`.

**Comment by sjrd** [comment]
No it doesn't: http://www.scala-js-fiddle.com/gist/e13eec8ab881a351e337

**Comment by sjrd** [comment]
> Actually, not the export, but the corresponding @JSName annotation will.

Ah yes. That is a problem. http://www.scala-js-fiddle.com/gist/e13eec8ab881a351e337
It shouldn't, that is a bug. We're not supposed to transform an explicit string in `@JSName` or `@JSExport`.

**Comment by gzm0** [comment]
Do you think we can just change it? Or do we need a migration path?

**Comment by gzm0** [comment]
So basically, the following applies in interop:

1. If a Scala name ends with `_=`, it is a setter and must have corresponding form
2. The default names of setters have the `_=` suffix stripped off
3. No explicitly specified name is ever transformed

**Comment by sjrd** [comment]
> So basically, the following applies in interop:

Yes.

> Do you think we can just change it? Or do we need a migration path?

I don't think there *is* a migration path. So I'd say we just change it now, and mention it clearly in the release notes.

**Comment by gzm0** [comment]
> I don't think there is a migration path.

Neither do I... Except for defining a new annotation of course and deprecating the old one. But that seems very extreme for something that probably no one will hit anyways...

We could emit a warning every time we see a `@JSName` on a setter ending in `_=` on an opt-in basis...

**Comment by sjrd** [comment]
> on an opt-in basis...

If they opt-in, they probably get faster results just by grepping `_="` in their codebase ;-)

**Comment by gzm0** [comment]
... indeed... but we can't make it opt-out, otherwise we have the suppress warning issue again.

So the official migration help is:

```
git grep '_='
```

**Comment by sjrd** [comment]
Nope:

    git grep '_="'

(note the `"` ^^)
