### ISSUE TITLE
Provide an HTML runner for tests

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#1709]
This will allow to:

- Run tests in the browser
- Debug tests in the browser (since they run in the browser)
- Have a nice HTML report

This can be completely agnostic of the underlying test framework and hopefully even implemented outside of scala-js core.

The only issue being test detection which is currently done by sbt and hard to port to JavaScript.

**Comment by sjrd** [comment]
We could have sbt do the detection and generate a json report of what tests to execute.

**Comment by gzm0** [comment]
Good thinking. I guess that would be useful in general. On the other hand, we might need some sbt foo anyway to do this in a convenient way...

**Comment by gzm0** [comment]
Ironically, the biggest difficulty seems to be where to put the HTML file that the users can open :S

An additional sbt plugin would of course trivially fix that, but I was trying to avoid yet another plugin  ...

**Comment by sjrd** [comment]
What's wrong with `crossTarget.value`, i.e., `target/scala-2.11/`?

**Comment by gzm0** [comment]
If the HTML runner is a library, the HTML file is just inside the JAR as a resource and wont get unpacked. If we want to generate/unpack/place it, we need sbt instrumentation. This can either be done via a plugin or by telling the user. (We could also tell the user to just create/place the file...)

I don't like either of these options...

**Comment by sjrd** [comment]
Oh, because you want to put implement that outside of core? I don't see why.

**Comment by gzm0** [comment]
If it doesn't have to be in core, it shouldn't. Also, it would be nice to rely at least on the statically typed DOM and maybe jQuery to do this...

**Comment by sjrd** [comment]
In that case, I'm pretty sure we do need an additional sbt plugin. I don't think asking people to do it by hand is an option, if we can instead provide an sbt plugin that does it for them.

**Comment by mysticfall** [comment]
Maybe it won't be a very helpful comment, but I had the exact same requirements for my project.

So I had to implement a HTML based test UI, with which you can run individual tests and get visual feedback.

I think it looks and works quite nice, but it depends on specific libraries and there's no test case detection. So, I'm definitely interested in learning how to do it in more generalized/standardized way.

**Comment by InTheNow** [comment]
FWIW - I sort-of added support for [saucelabs](https://github.com/InTheNow/zcheck/tree/master/saucelabs) and got the tests running there. Any solution might want to take this into scope. 
![sauce](https://cloud.githubusercontent.com/assets/5887373/8147918/0073ccd4-1283-11e5-8cc0-8810a73fccce.png)

**Comment by InTheNow** [comment]
Oh, also [here as well](https://github.com/InTheNow/scalatest-jasmine/blob/master/modules/jasmine/jvm/src/main/scala/com/github/inthenow/jasmine/scalatest/JasmineUtil.scala) This just uses scalatest's DSL for selenium to load the tests into browers - real or virtual

**Comment by InTheNow** [comment]
and here's [a link to a test](https://saucelabs.com/tests/05c25bf57de74ca78fa7d9775124934a)

**Comment by nicolasstucki** [comment]
This would also solve #2361.

**Comment by gzm0** [comment]
As discussed with @sjrd on gitter, I'll use what we already have and move it to the sbt plugin.

Test detection to JSON will remain unchanged. However, instead of writing detected tests to a json file, we'll add tasks `testHtmlFastOpt`, `testHtmlFullOpt` that generate respective HTML runners. The test descriptions will be included in there.

Further, the tasks `testHtmlFastOpt` and `testHtmlFullOpt` should default to the `Test` configuration - just like the `test` task - for easy invocation.
