### ISSUE TITLE
Val named apply in raw js type causes application

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#1717]
Consider this:

```scala
trait A extends js.Object {
  val apply: Int = js.native
}
```

reading `apply` on a value like this will actually result in an application:

Scala:
```scala
val a: A = // ...
a.apply
```

JavaScript:
```javascript
var a = // ...
a()
```

This is definitely not reasonable. We should select the property named `apply` or force the user to use `@JSName("apply")`. Further, `@JSExport` should mirror this behavior (it currently exports these as property, see #1647).

I am slightly in favor of forcing `@JSName`, to avoid accidental misunderstanding. (And properties named `apply` are not so common in JS).

**Comment by sjrd** [comment]
Sounds reasonable.
