### ISSUE TITLE
null as input for primitive types in exports should be allowed

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#1719]
When exporting a method taking as parameter a primitive type, we currently disallow explicitly `null` as a valid input.
Tests: https://github.com/scala-js/scala-js/blob/8cab6bbbe3c33afca2fd52874428096b07810a76/test-suite/src/test/scala/org/scalajs/testsuite/jsinterop/ExportsTest.scala#L827-L836
Implementation: https://github.com/scala-js/scala-js/blob/8cab6bbbe3c33afca2fd52874428096b07810a76/compiler/src/main/scala/org/scalajs/core/compiler/GenJSExports.scala#L517-L520

This is in contradiction with the general semantics that JavaScript is an erased generic context. Exports should `asInstanceOf` their parameters, which means unboxing for primitive types, which means `null` is a valid value and becomes the zero of the type.

The inconsistency appeared to me while working on #1715. Also, it is highlighted by the fact that the code in `GenJSExports` differs from `fromAny` only in that it specifically disallows `null` from primitive types.

**Comment by gzm0** [comment]
I think this actually raises an interesting concern about this specification:

If I write:

```scala
trait MyFacade {
  def doSomething(x: Int): Unit = js.unit
}
```

It actually means that `doSomething` might receive `null` and is to interpret it as 0 (and a sufficiently convoluted example + optimizer might also result in that). While this is perfectly valid according to specification, it is definitely not what users (and your average JS library) expect. Maybe we have to reconsider some parts of the spec...

**Comment by sjrd** [comment]
I assume from the name `MyFacade` that you intended it to `extends js.Object`?

In that direction, there is no problem, because the argument given to `x` is a primitive `Int` and is therefore not null. It just can't be. It is "boxed" by our backend because it is given to a facade, but we know it can't be null anyway. It doesn't matter whether the optimizer comes into play.

What *can* happen, though, is if you give, say, a `js.Array[Int]` to JavaScript, and you have filled this array with a convoluted series of generic operations that put `zero[Int]` everywhere, *then* JavaScript will receive an array with `null`s inside, yes. But there's nothing we can do about that, I fear. This could also happen on Scala/JVM when giving a `zero[Int]` in a collection to Java code.

**Comment by gzm0** [comment]
I was more thinking of something like this:

```scala
def foo[T](f: js.Function1[T, Unit]): Unit = f(null.asInstanceOf[T])
```

There will be some bridge generation such thatc this actually works. However, the optimizer might be able to inline all this and remove all the unboxing --> Bad

**Comment by sjrd** [comment]
This will not work, indeed, even without optimizer.

Note that the optimizer will *never* remove an unboxing unless it can prove that its input is already an `Int`, and hence not null. The optimizer will never introduce such bad behavior. But, the bad behavior could be there before.
