### ISSUE TITLE
Compiling code with scalatest leads to a compiler crash

### ISSUE THREAD

**Issue by ramnivas** [scala-js/scala-js#1722]
Here is a minimalist project to reproduce.
https://github.com/ramnivas/scalajs-scalatest-large-method-bug

When I run "test" in sbt, I get the following crash:
```
> test

...

[info] Compiling 1 Scala source to /Users/ramnivas/test-dev/scalajs-scalatest-large-method-bug/target/scala-2.11/test-classes...
[trace] Stack trace suppressed: run last test:test for the full output.
[error] Could not run test paya.ScalaJSExampleTest: InternalError: Encountered code generation error while compiling script: generated bytecode for method exceeds 64K limit. (Lorg_scalatest_Resources$.sjsir#1)
[trace] Stack trace suppressed: run last test:executeTests for the full output.
[error] (test:executeTests) java.util.concurrent.TimeoutException: Futures timed out after [4625269705 nanoseconds]
[error] Total time: 22 s, completed Jun 15, 2015 2:18:58 PM
```

I tried switching to scalatest 3.0.0-SNAP5, but got the same crash.

**Comment by sjrd** [comment]
You're hitting a limitation of Rhino, against we just can't do anything. You have to switch to *always* using Node.js or PhantomJS, and never Rhino.

**Comment by ramnivas** [comment]
Yep, that was it. 

I wonder if this situation can be detected so that users can be pointed in the right direction.

**Comment by sjrd** [comment]
Well, actually, we can do something about it. Simply prevent Rhino from using its "optimizations".
