### ISSUE TITLE
A scalajsp command/task in the sbt plugin

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#1736]
I find myself wanting this all the time when I work on the compiler/optimizer. It's only the only feature that the CLI provides and the sbt plugin doesn't.

**Comment by gzm0** [comment]
Make sure autocomplete works ;)

**Comment by sjrd** [comment]
Yeah that's the main point. And it's *really* tricky, because I want to autocomplete on the classpath, but the classpath is a Task, and the Parser can only depend on Settings. I'll need a hack somewhere.

**Comment by gzm0** [comment]
Look at how sbt autocompletes `testOnly`. Basically autocomplete only works after the relevant tasks have been run.

**Comment by sjrd** [comment]
Oh god point. Thanks for the tip. I had concluded I would have to make it work only after some task had been run, but I didn't realize `testOnly` had the same requirements.

**Comment by gzm0** [comment]
Basically the idea is: Have the task you depend on write its results to a file, look at the file if it is there for autocomplete, otherwise no autocomplete.
