### ISSUE TITLE
js.Dynamic.literal.applyDynamic("apply")(map.toSeq: _*) causes optimizer to crash

### ISSUE THREAD

**Issue by ramnivas** [scala-js/scala-js#1743]
Take a look at https://github.com/payalabs/scalajs-react-bridge/blob/22784f7f17625015378d01e09d9fc88875152584/src/main/scala/com/payalabs/scalajs/react/bridge/ReactBridgeComponent.scala#L113

Replacing the current code with the one commented there causes optimizer to crash:

```
> test
[info] Compiling 1 Scala source to /Users/ramnivas/open-source/scalajs-react-bridge-aggregate/scalajs-react-bridge/target/scala-2.11/test-classes...
[trace] Stack trace suppressed: run last test:loadedTestFrameworks for the full output.
[error] (test:loadedTestFrameworks) org.scalajs.core.tools.optimizer.OptimizerCore$OptimizeException: The Scala.js optimizer crashed while optimizing Lcom_payalabs_scalajs_react_bridge_ReactBridgeComponent$$anonfun$toLiteral$1.applyOrElse__O__F1__O
[error] Methods attempted to inline:
[error] Total time: 9 s, completed Jun 19, 2015 4:15:35 PM
```

**Comment by ramnivas** [comment]
Just a bit more info. If I change the line from
```
js.Dynamic.literal.applyDynamic("apply")(map.toSeq: _*)
```
to
```
js.Dynamic.literal(map.toSeq: _*)
```

I get `applyDynamic does not support passing a vararg parameter`. I wonder if that is the root of the problem i.e. trying to get around this limitation of `applyDynamic` simply postpones the error. Of course, in any case, a better message will be nice.

Also, is there a more succinct way to implement creating js.Dynamic from a set of key-value pairs?

**Comment by sjrd** [comment]
Note: you can work around this by using `js.Dictionary.apply` instead. It might even be an improvement over your current code.

**Comment by ramnivas** [comment]
@sjrd Done. It is indeed an improvement over the current code.
