### ISSUE TITLE
Unexpected token new

### ISSUE THREAD

**Issue by chrismurrph** [scala-js/scala-js#1745]
```scala
/** @constructor */
var $c_Lscal new $c_sci_Traversable$().init___()
  };
  return $n_sci_Traversable$
});
```

The above JavaScript does not compile because of the 'new' it seems:
Uncaught SyntaxError: Unexpected token new
Getting problems on fast and full. Only on remote deployment which currently makes no sense to me.

**Comment by chrismurrph** [comment]
```scala
/** @constructor */
var $c_Lscalacity$2 !== 0) && (this.capacity$2 === this.size$2)) ? this.elems$2 : this.mkArray__p2__I__AB(this.size$2))
});
```

This time the error is `Uncaught SyntaxError: Unexpected token !==`. Unfortunately I don't know Javascript syntax. But if the syntax is correct then maybe the webserver is throwing in bad invisible characters or something?? I'm using apache2 / jetty8 / Spray-Router.

**Comment by chrismurrph** [comment]
And now its come good with Fast. I'll close this as not a bug. But still an issue of some sort...

**Comment by sjrd** [comment]
These snippets look like the js files were corrupted by partially overriding their content. It's probably an issue with your deployment somewhere. You might have two tasks trying to write different outputs to the same file.

**Comment by chrismurrph** [comment]
I have an sbt dos box with `~package` in it. I ^S to save in IntelliJ, to prompt the automatic compilation. And sometimes I impatiently ^C multiple times. Perhaps that is what is causing the two processes to be writing to the same file.

**Comment by chrismurrph** [comment]
Could this issue could be due to having > 1 'dos boxes' open at the same time all doing `~package`. Or even with just one and IntelliJ (using SBT) having its go at compiling at the same time. Would locking on Scala code production fix this? One less frustration for new users...

**Comment by sjrd** [comment]
No, multiple `package` at the same time shouldn't do that. But multiple `fastOptJS` definitely could.

**Comment by chrismurrph** [comment]
The thing is fastOptJS is run when you run package. I know because I do it all the time. fastOptJS is a dependency of package. Anyway that's not really the issue here. Weird errors are not good things and new users (and old ones sometimes) will make many mistakes and it is not good for them to be confused. A simple lock would give the user an error he/she would understand. Users like good error messages and don't like being confused. I tried to recommend someone from the recent course I did at your University to use Scala.js for some project but he said it was 'clunky'. When everything is new you need everything to be on your side - that's the definition of not clunky.

**Comment by sjrd** [comment]
> The thing is fastOptJS is run when you run package.

That comes from your build, then. I don't have that behavior.

> A simple lock would give the user an error he/she would understand.

sbt does not have a culture of locking all the files it manipulates. For example there's no locking of .class files generated by compile, or the .jar file generated by package. And in general there's no locking of any file. sbt simply is not meant to have several instances running at the same time on the same build, or at least not have those instances *run commands* at the same time.

This is a problem generally acknowledged by sbt, though, as discussed in [this talk](https://www.parleys.com/tutorial/the-road-sbt-1-0-paved-server), in which they also present the general shape of the solution they envision. I think this would also solve this particular problem.

**Comment by chrismurrph** [comment]
I can see from the talk that a C/S architecture would have [fast|full]OptJS tasks being queued at the Server so no JavaScript overwriting could occur. The problem is still that the user would not be informed of his mistake. His computer would just slow down due to the needless extra compiles. Users appreciate early feedback and guidance, and are not getting it here.  
What I was thinking is not to rely on SBT. The start of the OptJS task would look for a file and put it down if it is not there. The file would have in it a number indicating the current time. At the end of the task the file would be deleted. If there is a file that is already there whose `time-stamp + 30secs < now` then the task would not proceed and the computer would emit a 'beep'. If the file is older than 30 secs then the assumption is that there is no lock so the files contents would get overwritten and the task proceed and of course not beep.  
When asked about this 'silly' solution it could be explained that we are doing the best we can for the user in an environment (SBT) that does not allow user feedback.  
The ideal would be a message in the SBT window stating why the compile was refused. It is a pity that SBT is not capable of that.
