### ISSUE TITLE
isInstanceOf[js.Array] uses JS 'instanceof'

### ISSUE THREAD

**Issue by colinrgodsey** [scala-js/scala-js#1750]
This was found in v0.6.1 - will confirm in 0.6.3 soon.

*instanceof Array* doesnt work with all types of arrays. This is most commonly seen in v8 implementations, especially node.js. There are a few ways you can make arrays in javascript that wont be identified with *instanceof*. These are even more prominent (if i remember correctly) with Arrays created via the C++ v8 'bridge'. The recommend way is *Array.isArray* (ES5). Can probably make a convenience function for this check and have it fall back to instanceof.

I dont see any such code produced in the scala collections library- only seems to surface if you do the check manually against js.Array

Some history, including the code for the old Node.js util.isArray convenience function:

http://stackoverflow.com/questions/22798826/in-node-js-why-is-there-a-util-isarray-and-an-array-isarray

This was actually found in pattern matching, have not confirmed it with isInstanceOf[js.Array] itself, just assuming. 

```scala
x match {
    case arr: js.Array[_] =>
}
```

produces

```javascript
if (ScalaJS.uZ((v instanceof ScalaJS.g["Array"]))) 
```

If it's agreed, I could submit a PR.

**Comment by sjrd** [comment]
This is by design. `isInstanceOf[T]` for `T` being a raw JS class translates to `instanceof`.
Use [`js.Array.isArray(x)`](http://www.scala-js.org/api/scalajs-library/0.6.3/index.html#scala.scalajs.js.Array$@isArray%28arg:scala.scalajs.js.Any%29:Boolean) if this is what you want.
