### ISSUE TITLE
More comprehensive error message if serialization fails due to binary compat

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#1760]
If a library that uses a newer version of Scala.js is on the classpath, the user is likely to get an error message of this kind:

```
java.io.IOException: Failed to deserialize info of /home/nick/.ivy2/cache/org.scala-js/scalajs-library_2.11/jars/scalajs-library_2.11-0.6.3.jar#scala/math/Ordering$Byte$.sjsir
```

The real reason of this failure is hidden in the cause. The sbt plugin should catch this specific exception and display a more comprehensive error message.

**Comment by nicolasstucki** [comment]
@gzm0 how can I reproduce this exception?

**Comment by nicolasstucki** [comment]
Never mind, I've reproduced it.
