### ISSUE TITLE
BigInt / BigInteger modInverse always throw an Exception

### ISSUE THREAD

**Issue by ndesmoul** [scala-js/scala-js#1764]
A call to method modInverse in BigInt systematically throws an exception.
Scala.js version : 0.6.3

Code sample to reproduce the bug:

     // test Scala BigInt available since scala.js 0.6.3
     import scala.math.BigInt
     val size = 32  // small size here as prime generation is very long 
     val n = BigInt(size, 50, rand)  // our modulus is a prime number

     val g = BigInt(size, rand)
     val e = BigInt(size, rand)
     println("n = " + n.toString(16))
     println("g = " + g.toString(16))
     println("e = " + e.toString(16))
     
     val res = g.modPow(e, n)  // modPow is OK
     println("g^e mod n = " + res.toString(16))
     
     // compute inverse of g mod n
     val inv = g.modInverse(n)  // pb -> exception
     println("g^-n mod n = " + inv.toString(16))  
    

Javascript console output:

Uncaught java.lang.ArithmeticException: BigInteger not invertible.
$c_Ljava_math_BigInteger.modInverse__Ljava_math_BigInteger__Ljava_math_BigInteger @ BigInteger.scala:532
$c_s_math_BigInt.modInverse__s_math_BigInt__s_math_BigInt @ BigInt.scala:275
$c_Lorangelabs_TestApp$.main__V @ TestApp.scala:140

The problem seems to occur in Division.modInverseMontgomery(...)

**Comment by sjrd** [comment]
Tentatively scheduling this for 0.6.4. We'll see whether we find the solution before the release.
Thanks for the report.

**Comment by ndesmoul** [comment]
The problem indeed come from method modInverseMontgomery in Division.
Doing a direct conversion from the original Java source code seems to produce a valid result.
Note however I did not extensive tests.

Here is the code:

    def modInverseMontgomery(a: BigInteger, p: BigInteger): BigInteger = {
    if (a.sign == 0) {
      // ZERO hasn't inverse
      // math.19: BigInteger not invertible
      throw new ArithmeticException("BigInteger not invertible.");
    }

    if (!p.testBit(0)) {
      // montgomery inverse require even modulo
      return modInverseLorencz(a, p);
    }

    val m = p.numberLength * 32;
    // PRE: a \in [1, p - 1]
    
    var u = p.copy(); // make copy to use inplace method
    var v = a.copy();
    val max = Math.max(v.numberLength, u.numberLength);
    var r = new BigInteger(1, 1, new Array[Int](max + 1))
    var s = new BigInteger(1, 1, new Array[Int](max + 1));
    s.digits(0) = 1;
    // s == 1 && v == 0

    var k = 0;

    var lsbu = u.getLowestSetBit();
    var lsbv = v.getLowestSetBit();
    var toShift:Int = 0

    if (lsbu > lsbv) {
      BitLevel.inplaceShiftRight(u, lsbu);
      BitLevel.inplaceShiftRight(v, lsbv);
      BitLevel.inplaceShiftLeft(r, lsbv);
      k += lsbu - lsbv;
    } else {
      BitLevel.inplaceShiftRight(u, lsbu);
      BitLevel.inplaceShiftRight(v, lsbv);
      BitLevel.inplaceShiftLeft(s, lsbu);
      k += lsbv - lsbu;
    }

    r.sign = 1;
    while (v.signum() > 0) {
      // INV v >= 0, u >= 0, v odd, u odd (except last iteration when v is even
      // (0))

      while (u.compareTo(v) > BigInteger.EQUALS) {
        Elementary.inplaceSubtract(u, v);
        toShift = u.getLowestSetBit();
        BitLevel.inplaceShiftRight(u, toShift);
        Elementary.inplaceAdd(r, s);
        BitLevel.inplaceShiftLeft(s, toShift);
        k += toShift;
      }

      import scala.util.control.Breaks._
      breakable{
      while (u.compareTo(v) <= BigInteger.EQUALS) {
        Elementary.inplaceSubtract(v, u);
        if (v.signum() == 0) {
          break;
        }
        toShift = v.getLowestSetBit();
        BitLevel.inplaceShiftRight(v, toShift);
        Elementary.inplaceAdd(s, r);
        BitLevel.inplaceShiftLeft(r, toShift);
        k += toShift;
      }
      }
    }
    if (!u.isOne()) {
      // in u is stored the gcd
      // math.19: BigInteger not invertible.
      throw new ArithmeticException("BigInteger not invertible.");
    }
    if (r.compareTo(p) >= BigInteger.EQUALS) {
      Elementary.inplaceSubtract(r, p);
    }

    r = p.subtract(r);

    // Have pair: ((BigInteger)r, (Integer)k) where r == a^(-1) * 2^k mod
    // (module)
    val n1 = calcN(p);
    if (k > m) {
      r = monPro(r, BigInteger.ONE, p, n1);
      k = k - m;
    }

    r = monPro(r, BigInteger.getPowerOfTwo(m - k), p, n1);
    return r;
    
  }

Looking back at the Scala version, the problem seems to come from the last lines of the method.

**Comment by ndesmoul** [comment]
Updated test:

     import scala.math.BigInt
     val size = 32
     val n = BigInt(size, 50, rand)

     val g = BigInt(size, rand)
     val e = BigInt(size, rand)
     println("n = " + n.toString(16))
     println("g = " + g.toString(16))
     println("e = " + e.toString(16))
     
     val res = g.modPow(e, n)
     println("g^e mod n = " + res.toString(16))
     
     val inv = g.modInverse(n)
     println("g^-1 mod n = " + inv.toString(16))  
     val ingtg = (inv * g).mod(n)
     println("g * g^-1 = " + ingtg.toString(16)) //should be 1
     println(if(ingtg == BigInt(1)) "success" else "failure")

**Comment by sjrd** [comment]
@ndesmoul Where did you find the code of `modInverseMontgomery` that you cited above? I moved it to a gist because it's possibly a GPL spoiler, if you took it from OpenJDK or OracleJDK, in which case *we must not look at it* to implement ours.

**Comment by ndesmoul** [comment]
I'm well aware of licence problems.
I took it from: https://github.com/gwtproject/gwt/blob/master/user/super/com/google/gwt/emul/java/math/Division.java which the source indicated in the comments of the original Scala code.
This code (the java version) was originally written by the Apache Harmony project.
If you compare the two Scala versions (the original and mine), it's almost the same.

The internal implementation of BigInteger from Oracle/OpenJDK is completely different. You don't have any Division object for example. So even if I wanted I couldn't have so easily taken some source code from the GPL version and make it work so easily.

**Comment by sjrd** [comment]
OK, good. I just wanted to make sure ;-)

**Comment by nicolasstucki** [comment]
I've identified a couple of bugs due to miss-translation in `modInverseMontgomery` method:
* ` r.sign = 1` assigned at the wrong line.
* `m - (k - m)` written as `k` instead of `2*m - k`

Unfortunately it is still buggy.

**Comment by nicolasstucki** [comment]
The bugs listed in the las comment fix this particular issue.

Another bug related with the snippet above was found (#1771). It involves the randomly generated `BigInt`.
