### ISSUE TITLE
Invalid tree in JSDesugar.transformExpr() of class class org.scalajs.core.ir.Trees$UndefinedParam

### ISSUE THREAD

**Issue by aborg0** [scala-js/scala-js#1768]
[Using](https://github.com/aborg0/underscore.scala.js/blob/failing/build.sbt) scala.js `0.6.3` with utest `0.3.1` and a test something like [this](https://github.com/aborg0/underscore.scala.js/blob/failing/src/test/scala/underscore/UnderscoreTest.scala) (comments removed):

    object UnderscoreTestSuite extends TestSuite{
      val tests = TestSuite{
        import com.mind_era.underscore.{___ => __}
        import collection.mutable.{IndexedSeq => List}
        'uniq{
          print(__)//fails without this too
              val list = js.Array(1, 2, 1, 3, 1, 4)
              assert(__.uniq(list)
                  == (js.Array(1, 2, 3, 4)));
        }
      }
    }

Fails during test with the following [error message](https://github.com/aborg0/underscore.scala.js/blob/failing/test_executeTests.out):
> java.lang.RuntimeException: Invalid tree in JSDesugar.transformExpr() of class class org.scalajs.core.ir.Trees$UndefinedParam

(To be honest I am not sure this could be further reduced, pretty new to this.) Before I got this exception, I had problems with `___` being `undefined` (which is probably problem in my code), though that state was not committed unfortunately and most probably is not relevant for this issue (just wanted to signal the error might be in the main, not in the test). The code `compile`s, only it fails during test.

**Comment by sjrd** [comment]
Here is a much smaller reproduction that does not depend on the whole Underscore thing. It just depends on uTest:
```scala
import utest._
import scala.scalajs.js
import js.annotation.JSExport

trait WithDefaultParams extends js.Object {
  def add(a: Int, b: Int = 5): Int = js.native
}

class ImplementationWithDefaultParams {
  @JSExport
  def add(a: Int, b: Int = 5): Int = a + b
}

object UnderscoreTestSuite extends TestSuite {
  val tests = TestSuite {
    'rawJSMethodWithDefaultParams {
      def obj =
        new ImplementationWithDefaultParams().asInstanceOf[WithDefaultParams]
      assert(obj.add(3, 10) == 13) // works
      assert(obj.add(3) == 8) // crashes
    }
  }
}
```
So this is a bad interaction with uTest's `assert` macro and default parameters in raw JS types. At this point, I don't whether I can do anything about it in Scala.js. It would be uTest's job to deal in a specific way for calls to default parameter methods of raw JS types (or possibly of all types).
