### ISSUE TITLE
Random BigInt does not return the same numbers in the JVM.

### ISSUE THREAD

**Issue by nicolasstucki** [scala-js/scala-js#1771]
The `BigInt` random number constructor does not return the same numbers in JS or JVM.
```scala
BigInt(32,  new scala.util.Random(4))
```
On the JVM this has value `2889353659` while on Scala.js it has value `3137943724`.

**Comment by InTheNow** [comment]
I would question whether this is a Bug, as we are not sure what should be returned as we do not know how the jvm implements `BigInteger(numBits, rnd)`

**Comment by nicolasstucki** [comment]
I'm was also questioning it for that same reason. But it might be good to have the pseudo-random numbers on the jvm and js just as we do with `Random`

**Comment by InTheNow** [comment]
I agree that it would be great to have same behaviour on JS/JVM, but I'm concerned here about licences. The implementation of the API for `Random` is clearly defined - eg "... See Donald Knuth, The Art of Computer Programming, Volume 2, Section 3.2.1.)". So a compatible implementation can be made without inspecting "other" code. 

For the implementation of `BigInteger(numBits, rnd)` it is not defined hence one cannot implement an exact mirror.

Unless, of course, there is a public implementation specification that I am unaware off.

**Comment by nicolasstucki** [comment]
You are right. I also haven't been able to find public implementation specifications for this.
