### ISSUE TITLE
Implement java.util.Locale

### ISSUE THREAD

**Issue by andreaTP** [scala-js/scala-js#1773]
I definitely need some help on the Locale port... 
unfortunately I've checked that toLowerCase on the JVM is related to the default Locale
and realised that there is no real standard Internationalisation for string on the js vm
most advanced references are on 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl
but there is no reference to string ...
what I need basically is this:
andreaTP/scala-js@65b52f5
but I do not know if it is acceptable

To let you aware of the problem with this code 

```
"I".toLowerCase
```

JVM answer differently following the default Locale so that (for example):

```
val tr = java.util.Locale.getAvailableLocales.find(_.toString == "tr_TR").get
java.util.Locale.setDefault(tr)
"I".toLowerCase
```

result in:

```
ı //without the dot
```

**Comment by mdedetrich** [comment]
I am also in need for `java.util.Local` for a port of `JodaTime` that I am working on.

Maybe you may need to do stuff like detect the javascript client (i.e. the browser) and work from there? It may be the only option

**Comment by sjrd** [comment]
I told people `Locale` was tough luck ...

**Comment by andreaTP** [comment]
Locale management for strings is crappy and inconsistent, btw,Intl:
https://developer.mozilla.org/it/docs/Web/JavaScript/Reference/Global_Objects/Intl

will be good for porting JodaTime....

**Comment by andreaTP** [comment]
@sjrd can we schedule a chat on the topic?

**Comment by sjrd** [comment]
I don't really have anything to say on that topic. I just know that it's hard. I have not the slightest idea about how to approach this problem. A chat with me will not help. You might want to chat with people who have done a bit of intl in JS before.

**Comment by andreaTP** [comment]
ok, at this point could you just check my implementation linked in the first post, and check if you could accept this at this step or you want anything more?

**Comment by sjrd** [comment]
Hum, what does the implementation linked above achieve? On its own, it looks pretty useless. And the implementation of `toLowerCase` and `toUpperCase` ignoring their `locale` parameter are just not correct.

**Comment by andreaTP** [comment]
usually js vm are not sensitive to Locale, so an implementation that ignores Locale just follow what usually happens in js.
I need to use a function like:
```
"STRING".toLowerCase(java.util.Locale.ROOT)
```
and this implementation completely satisfy my target.

**Comment by sjrd** [comment]
> and this implementation completely satisfy my target.

You can't use that argument. It wouldn't comply for Turkish, for example:

```scala
"STRING".toLowerCase(new java.util.Locale("tr", "TR"))
```
must return `strıng`, not `string`.

**Comment by mdedetrich** [comment]
I think we also may need to step back, and consider whether a `locale` is useful in the JS context or not. There may be a good argument that we specify that `locale` doesn't make sense (we can provide opt in libraries for javascript clients that support it properly, like node.js?) and that libraries which use `java.util.Local` have to recode the relevant parts for `Scala.js`.

If `java.util.Local` is completely inconsistent and doesn't make sense, its not work it to make a library that works on false assumptions

**Comment by mdedetrich** [comment]
Will have a look at implementing/researching this on the weekend. From initial impressions, it seems like there may not be any point in implementing `java.util.Locale`, mainly due to client inconsistencies. Will take a stab at this anyways though

**Comment by cquiroz** [comment]
Hi, I have been hitting the lack of `Locale` with my attempts to get `threetenbp` to work on scala.js. After doing some research and experiments I'd like to propose an idea for a `Locale` implementation. In summary it would be to do a native implementation using the metadata from CLDR.

Here is a [longer explanation](https://gist.github.com/cquiroz/1aac347d2277fddbc8c8ca4347844b83)

I'm already doing a very initial implementation but I'd like feedback if you think this is acceptable before investing more time

[locale-branch@cquiroz](https://github.com/scala-js/scala-js/compare/master...cquiroz:locale-with-cldr)

**Comment by gzm0** [comment]
This seems reasonable to me (as far as I understand locales and such). However, I think just like `java.time`, this should probably live in its own repository. Mainly for the following reasons (same as `java.time` AFAIK):

1. The interface is very well defined and won't change (JDK interface), so no bootstrapping hell.
2. The library is likely to move faster than Scala.js itself (at least at first), so Scala.js' release cycle would slow down development and usage.
3. Even in-between Java-shims, there is no dependency hell, because each individual shim will happily compile without the dependency. For example `java.time` can accept `java.util.Locale` in its methods and query relevant fields. If a project doesn't pull in scala-js-java-locale, it can't create a locale, so it can't invoke the method, so there won't be a linker error. If it pulls it in, the method will happily link.
4. Having a separate library would leave it open to have two parallel libraries, should L10n support in ES improve.

There is one thing I'm still fuzzy about though if we go with the separate library approach: How do we implement `java.text.NumberFormat` and `java.time.format.DateTimeFormatter` (et al.)?

Since they only see the interface of `java.util.Locale`, they'd need their own way of pulling (partial) CLDR data in, which seems redundant. Of course we can provide dynamically typed escape hooks to call into that data from a `java.util.Locale`, since we know it is a `scala-js-java-locale` style `Locale`. However, this nukes all but point 2 in the above list.

WDYT?

**Comment by andreaTP** [comment]
my 2 cents on this:
the problem here are the defaults, since JVM takes environment variables and V8 do not you do not have any(I talked about that with V8 devs...) clean and portable way to get default parameters(i.e. Default Locale), so the semantics of the API will be different from what JavaDocs says...

**Comment by cquiroz** [comment]
At the moment, development is being done at https://github.com/soc/threetenbp to ensure it can work with the date formatters there. Once complete, it could go either to its own repository or as part of scala.js. I expect to extract the data required to build proper `DecimalFormatSymbols` and `DateFormatSymbols` that are needed for `NumberFormat` as part of this work

If you prefer to use `scala-js-java-locale` in the meantime, that's fine with me but I think a subset will go to to scala.js core to let, e.g. `NumberFormat` work, That would require including some of the CLDR data into the core and the loader too

One idea is to have the basic classes on scala.js with the minimum set of `Locale` to satisfy the javadocs, but you could add any other locales generated form CLDR data from another repository. This will reduce the code size considerably and I expect this data to be automatically generated out CLDR's XML

**Comment by cquiroz** [comment]
@andreaTP That is correct, there is no reliable or portable way to get the default locale on JS. I'm ok with that limitation and it basically requires you to define your default with `Locale.setDefault` or use the System properties to select it via `user.country` and `user.language`

**Comment by cquiroz** [comment]
Of course, an option is that you cannot implement a Java API that differs from the original spec in which case I don't really know how to proceed

**Comment by gzm0** [comment]
> Of course, an option is that you cannot implement a Java API that differs from the original spec in which case I don't really know how to proceed

We usually prefer leaving a method out than implementing it in a way which doesn't conform to the spec. So as a first step, we could simply not implement `getDefault` :)

**Comment by gzm0** [comment]
As a second step, third-party libraries could provide ways to figure out locales on given platforms (locale in browser, in Node.js, etc.)

**Comment by mdedetrich** [comment]
> We usually prefer leaving a method out than implementing it in a way which doesn't conform to the spec. So as a first step, we could simply not implement getDefault :)

Well if you wanted to be truely conforming, `getDefault` would return `null` on Javascript. Not sure Scala people would like that, but it is the "Java" way. It can be argued that you should write a wrapper over `java.util.Locale` anyways.

**Comment by cquiroz** [comment]
I guess leaving out `getDefault` is a way to go. I'm afraid though that may require leaving out many other API calls that assume you have a default locale, e.g.

[Formatter.format(String format,Object... args)](https://docs.oracle.com/javase/7/docs/api/java/util/Formatter.html#format(java.lang.String,%20java.lang.Object...))

And only keep the one with locale
[Formatter.format(Locale l, String format, Object... args)](https://docs.oracle.com/javase/7/docs/api/java/util/Formatter.html#format(java.util.Locale,%20java.lang.String,%20java.lang.Object...))

On the other hand, the first will be undefined if you haven't set a locale

**Comment by mdedetrich** [comment]
Is there any issues with having `getDefault` just return `null`? Isn't already documented to do something along those lines if it can't get the default locale (this is just for keeping the API consistant)

**Comment by mdedetrich** [comment]
It may also be a good idea to have a look at the typical libraries that use `java.util.Locale` to see if they detect if `getDefault` returns `null` and they handle it apprporiately

**Comment by gzm0** [comment]
Nothing in the JavaDoc I can see says anything about `getDefault` returning `null`. However, note that calling `setDefault` with `null` will aggressively throw a NPE.

**Comment by andreaTP** [comment]
I pass though this and I guess to don't implement the ```getDefault``` methods.
Unfortunatelly that leads to missing default constructors (expecially for Singleton AKA ```object``` instances) ...

**Comment by cquiroz** [comment]
Scala.js in practice assumes that there is a default locale since there is an implementation of `java.util.Formatter.format` without the locale parameter and you can also do

`String.format("abc: %s", s)`

**Comment by cquiroz** [comment]
If you change the locale when starting sbt some tests fail as the JVM will obey the value

```
sbt -Duser.language=fi -Duser.country=FI "testSuiteJVM/test-only org.scalajs.testsuite.javalib.util.FormatterTest"
```
This produces 3 errors on [FormatterTest](https://github.com/scala-js/scala-js/blob/master/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/FormatterTest.scala#L178):
```
[info] Test org.scalajs.testsuite.javalib.util.FormatterTest.should_provide_e_conversion started
[error] Test org.scalajs.testsuite.javalib.util.FormatterTest.should_provide_e_conversion failed: org.junit.ComparisonFailure: expected:<1[.]000000e+03> but was:<1[,]000000e+03>, took 0.003 sec
[error]     at org.scalajs.testsuite.javalib.util.FormatterTest.assertF(FormatterTest.scala:60)
[error]     at org.scalajs.testsuite.javalib.util.FormatterTest.should_provide_e_conversion(FormatterTest.scala:178)
[error]     ...
[info] Test org.scalajs.testsuite.javalib.util.FormatterTest.should_fail_with_bad_format_specifier started
[info] Test org.scalajs.testsuite.javalib.util.FormatterTest.should_provide_f_conversion started
[error] Test org.scalajs.testsuite.javalib.util.FormatterTest.should_provide_f_conversion failed: org.junit.ComparisonFailure: expected:<3[.]300000> but was:<3[,]300000>, took 0.0 sec
[error]     at org.scalajs.testsuite.javalib.util.FormatterTest.assertF(FormatterTest.scala:60)
[error]     at org.scalajs.testsuite.javalib.util.FormatterTest.should_provide_f_conversion(FormatterTest.scala:209)
[error]     ...
[info] Test org.scalajs.testsuite.javalib.util.FormatterTest.should_provide_g_conversion started
[error] Test org.scalajs.testsuite.javalib.util.FormatterTest.should_provide_g_conversion failed: org.junit.ComparisonFailure: expected:<5[.]00000e-05> but was:<5[,]00000e-05>, took 0.0 sec
[error]     at org.scalajs.testsuite.javalib.util.FormatterTest.assertF(FormatterTest.scala:60)
[error]     at org.scalajs.testsuite.javalib.util.FormatterTest.should_provide_g_conversion(FormatterTest.scala:199)
```

The same command line for JS works fine
```
sbt -Duser.language=fi -Duser.country=FI "testSuite/test-only org.scalajs.testsuite.javalib.util.FormatterTest"
```

In my opinion this indicates that scala.js has a _de facto_ default locale (essentially english) since the [java.util.Formatter constructor](https://docs.oracle.com/javase/8/docs/api/java/util/Formatter.html#Formatter--) uses the default locale.

What do you think?

**Comment by mkotsbak** [comment]
I think we should just fix this, so we can get further on the issue of not having any proper full date/time classes in SJS. Usually in browsers you either default to English or the locale native language for the user group and let the user change language by clicking links/flags or by saving it in settings. Thus it would be sufficient that the SJS code itself would be required to run Locale.setDefault() before using any Locale based functions, and consider if english locale should be used if it isn't run first.

**Comment by sjrd** [comment]
@mkotsbak How exactly do you suggest we "just fix this"?

I'm fine with assuming English is the de facto default default locale (double "default" intended), i.e., the initial value of `Locale.getDefault()` is English. But that does not really solve the problem of implementing `Locale`.

**Comment by mkotsbak** [comment]
As I understand the discussion here, the blocker issue is that the browser/js has no default locale, so if making English the default locale solves that, I think we should do that.

Then it seems we must choose one of the solutions proposed here: https://gist.github.com/cquiroz/1aac347d2277fddbc8c8ca4347844b83 I think I'm leaning towards a native implementation.

**Comment by sjrd** [comment]
I think the main "blocker" issue is the sheer amount of implementation work that is required.

I think @cquiroz's Native implementation approach is undeniably the best, since the other ideas do not allow to implementation `Locale` as such.

**Comment by mkotsbak** [comment]
Can't we convert the java code from Harmony?: http://svn.apache.org/repos/asf/harmony/enhanced/java/trunk/classlib/modules/luni/src/main/java/java/util/Locale.java

**Comment by sjrd** [comment]
`Locale` itself is not the main problem. It's a small class that is mostly a struct with not behavior. The hard parts are all the algorithms using `Locale`s, which require the CLDR data.

**Comment by mkotsbak** [comment]
Ok, but the ones from Harmony are they of no use in SJS?:
https://svn.apache.org/repos/asf/harmony/enhanced/java/trunk/classlib/modules/text/src/main/java/java/text/DateFormatSymbols.java
http://svn.apache.org/repos/asf/harmony/enhanced/classlib/branches/java6/modules/text/src/main/java/java/text/DecimalFormatSymbols.java?p=820841

**Comment by cquiroz** [comment]
I made an initial release of [scala-java-locales](https://github.com/cquiroz/scala-java-locales).

It contains basic support for `Locale`, `DecimalFormatSymbols` and `DateFormatSymbols` on `Scala.js` reading from CLDR data, mostly to support work on scala-java-time.

**Comment by soc** [comment]
Shall we close this?

**Comment by sjrd** [comment]
I suggest a PR be made to [scalajs-website](https://github.com/scala-js/scala-js-website) to add `scala-java-locales` to the JDK Extensions section of https://www.scala-js.org/libraries/libs.html

**Comment by soc** [comment]
That's done!

**Comment by sjrd** [comment]
Closing, as this is supported by the separate repo https://github.com/cquiroz/scala-java-locales
