### ISSUE TITLE
Bug with java.util.LinkedList.size when larger than Int.MAX_VALUE.

### ISSUE THREAD

**Issue by nicolasstucki** [scala-js/scala-js#1777]
If the size of the `LinkedList` is larger than `Int.MAX_VALUE` the then `size` should return `Int.MAX_VALUE`. 

The current implementation uses a `var _size: Int` to track the size and updates it with `_size += 1` which loops back to `Int.MIN_VALUE` when the list grows to a size of `Int.MAX_VALUE` + 1.

**Comment by nicolasstucki** [comment]
It seams that `LinkedList` does not require constant time `size` computation.
I would propose to change every `if (_size <= 0) ...` with `if (isEmpty) ...`, remove the field `private var _size` along with all updates to it and redefine the size as:
```scala
override def size(): Int = 
  iterator().take(Int.MAX_VALUE).size
```

**Comment by andreaTP** [comment]
the javadocs refer to limit on sizes explicitly for throwing exceptions:
http://docs.oracle.com/javase/7/docs/api/java/util/LinkedList.html#add(int,%20E)

so in LinkedList the use of ```_size``` is correct

**Comment by andreaTP** [comment]
maybe the bug must be fixed only on ConcurrentLinkedQueue, and I'm going to do that!

**Comment by nicolasstucki** [comment]
The problems are with the other `add` (as well as `addFirst` and `addLast`), the ones that do not take an index.

**Comment by nicolasstucki** [comment]
And that exception is for the input index, not for the size.

**Comment by nicolasstucki** [comment]
My previous solution is quite inefficient because it requires recomputing the size each time. The new approach is to convert the `_size` to a `Double`.

```scala
private var _size: Double = 0.0
...
override def size(): Int =
  _size.toInt
```
and replace the `if (_size <= 0)` by `if (isEmpty)`

**Comment by andreaTP** [comment]
actually ```addLast``` and ```addFirst``` doesn't make any check on size...

btw I will check which number generates my jvm on int overloads

**Comment by sjrd** [comment]
> btw I will check which number generates my jvm on int overloads

If it doesn't give `Int.MinValue` for `Int.MaxValue + 1`, your JVM is buggy ;-) This is part of the JVM specification, the Java Language Specification, as such also of the Scala Language Specification, and even true in the Scala.js Semantics.

**Comment by andreaTP** [comment]
I obviously mean what will happens into a java.util.LinkedList when adding an element over MaxValue

**Comment by andreaTP** [comment]
Just to satisfy that:
http://docs.oracle.com/javase/7/docs/api/java/util/Collection.html#size()
I will check that every increment of ```_size``` will not do anything if ```_size == Int.MaxValue```

**Comment by sjrd** [comment]
That doesn't work, because you can first add `MaxValue` elements, which brings, `_size` to `MaxValue`. Then add an element--`_size` remains `MaxValue`--then *remove* an element -> `_size` decreases to `MaxValue - 1` but there are `MaxValue` elements in the collection.

I believe the `Double` solution is the best one. Doubles are only marginally slower than Ints in Scala.js, and have full precision until 2^53.

**Comment by gzm0** [comment]
Why is this labeled "missing javalib"? I think this is misleading. (I'd consider "missing javalib" as a replacement for "enhancement" for missing java libraries).
