### ISSUE TITLE
5mb Scala = 30min fullOptJS

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#1779]
I've been doing some benchmarking recently.
I have two files with hardcoded data values that the benchmarks use. They aren't small:
```
> finds 100 | xargs wc   
   9028   40828 4662912 ./benchmark/shared/src/main/scala/benchmark/data/Project_1000.scala
    769    3434  394118 ./benchmark/shared/src/main/scala/benchmark/data/Project_100.scala
   9797   44262 5057030 total
```

Running `fullOptJS` takes a miserably long time, (avg 30min on a 3.40GHz i7-3770), nearly all of which is spent single-threadedly in the google closure compiler.

```
benchmark-js> last fullOptJS
[info] Full Optimizing /home/golly/xxx/projects/xxx/Code/benchmark/js/target/benchmark.js
[debug] Linker: Read info: 304613 us
[debug] Linker: Check Infos: 4900293 us
[debug] Linker: Compute reachability: 934614 us
[debug] Linker: Assemble LinkedClasses: 1156028 us
[debug] Linker: cache stats: reused: 0 -- invalidated: 15934 -- trees read: 15934
[debug] Linker: 7315726 us
[debug] Check IR: 4442944 us
[debug] Inc. optimizer: Batch mode: true
[debug] Inc. optimizer: Incremental part: 460673 us
[debug] Inc. optimizer: Optimizing 33239 methods.
[debug] Inc. optimizer: Optimizer part: 16996053 us
[debug] Inc. optimizer: 17490240 us
[debug] Refiner: Compute reachability: 540522 us
[debug] Refiner: Assemble LinkedClasses: 41011 us
[debug] Refiner: 582535 us
[debug] Emitter: Class tree cache stats: reused: 0 -- invalidated: 3825
[debug] Emitter: Method tree cache stats: resued: 0 -- invalidated: 24106
[debug] Emitter (write output): 11034710 us
[info] Closure: 0 error(s), 0 warning(s)
[debug] Closure: Compiler pass: 1645358389 us
[debug] Closure: Write result: 1017227 us
```

Is it possible to reduce this somehow? I read through the closure docs hoping for a way to disable it for a block but there doesn't seem to be anything. You're pretty resourceful so I thought it'd be worth a shot asking. Any ideas?

**Comment by sjrd** [comment]
I'm afraid Closure does not let you do anything like that. Which is logical, given its global nature. It just could not disable its work on a local part, just as much as Scala.js cannot disable its linking on a local part.

I think you're out of luck as far as proper solutions are concerned. Possible workaround: put your data in a file (blob or something) and read it at runtime.

**Comment by vendethiel** [comment]
(I'm surprised it doesn't run out of memory, how much did it use at most?)

**Comment by ngbinh** [comment]
I am seeing a lot of slowness even on `fastOptJs`. @japgolly can you please try on `fastOptJs` too?

**Comment by japgolly** [comment]
@sjrd Oh noes, no `@Export`-related tricks or anything possible? Also, how would one best couple JS with a static blob? Scala.js doesn't provide a facade to `src/test/resources` or anything. You could create a big string (partitioned at compile-time to avoid Scala limits)... Being a Scala guy more than a JS guy, how would JS people normally load a binary blob and process via JS?

@vendethiel I don't know but my main PC has 16GB ram and it runs. I also ran it on my 9-yr old laptop with 3.5'ish GB ram and it ended up crashing after running out of memory.

@ngbinh `fastOptJs` does feel slow to me too lately but if you compare it to a 30min `fullOptJS` it feels like lightning!
```
benchmark-js> last fastOptJS
[info] Fast optimizing .../benchmark.js
[debug] Linker: Read info: 314099 us
[debug] Linker: Check Infos: 4598351 us
[debug] Linker: Compute reachability: 870221 us
[debug] Linker: Assemble LinkedClasses: 1334167 us
[debug] Linker: cache stats: reused: 0 -- invalidated: 15936 -- trees read: 15936
[debug] Linker: 7142563 us
[debug] Check IR: 4064124 us
[debug] Inc. optimizer: Batch mode: true
[debug] Inc. optimizer: Incremental part: 278919 us
[debug] Inc. optimizer: Optimizing 33239 methods.
[debug] Inc. optimizer: Optimizer part: 18139407 us
[debug] Inc. optimizer: 18455573 us
[debug] Refiner: Compute reachability: 499911 us
[debug] Refiner: Assemble LinkedClasses: 43588 us
[debug] Refiner: 544547 us
[debug] Emitter: Class tree cache stats: reused: 0 -- invalidated: 3826
[debug] Emitter: Method tree cache stats: resued: 0 -- invalidated: 24107
[debug] Emitter (write output): 3474782 us
[success] Total time: 36 s, completed 01/07/2015 7:01:51 PM
```

**Comment by lihaoyi** [comment]
@japgolly 

SBT plugin: https://github.com/lihaoyi/roll/blob/master/project/Build.scala#L12-L52
Facades: https://github.com/lihaoyi/roll/blob/master/src/main/scala/roll/bundle.scala

This was originally a separate project `scala-js-resource`, but I folded it in to Roll because I wasn't using it anywhere else. 

This base64 encodes the binary data from those files. Not ideal but there's no way around it if you don't have a webserver, and in this case I didn't.

It's arguable whether such a facade should live in the standard Scala.js distribution; I think it'd be handy, but if you're the second one to ask for such a thing in the last two years then maybe not =P Perhaps you could revive `scala-js-resource` and publish it for others to use, wouldn't be hard!

**Comment by japgolly** [comment]
Thanks @lihaoyi !
