### ISSUE TITLE
Binary compatibility check failing in nightly

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#1804]
The nightlies have been failing for a while. The later ones claim there is some kind of binary incompatibility issue.

This needs immediate attention. @sjrd, do you have a couple of cycles?

**Comment by sjrd** [comment]
Ah. I will take care of that this afternoon.

**Comment by sjrd** [comment]
The failures happen with earlier versions of the Scala compiler, which are not used to actually *publish* the artifacts. So they are irrelevant.
