### ISSUE TITLE
V8/Node.js does not display stack traces for uncaught Throwables

### ISSUE THREAD

**Issue by yawnt** [scala-js/scala-js#1810]
as per discussion with @gzm0, [here's a simple example that demos the issue](https://github.com/yawnt/node-sourcemap-fail)

```
$ git clone https://github.com/yawnt/node-sourcemap-fail.git && cd node-sourcemap-fail
$ npm i source-map-support
$ build.sbt  node_modules  project  src
$ node
> require('source-map-support').install()
$ node -v 
v2.3.1
$ npm -v
2.11.3
$ sbt run
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
[info] Loading global plugins from /home/yawnt/.sbt/0.13/plugins
[info] Loading project definition from /tmp/node-sourcemap-fail/project
[info] Set current project to node-sourcemap-fail (in build file:/tmp/node-sourcemap-fail/)
[info] Updating {file:/tmp/node-sourcemap-fail/}node-sourcemap-fail...
[info] Resolving org.eclipse.jetty#jetty-continuation;8.1.16.v20140903 ...
[info] Done updating.
[info] Compiling 1 Scala source to /tmp/node-sourcemap-fail/target/scala-2.11/classes...
[info] Fast optimizing /tmp/node-sourcemap-fail/target/scala-2.11/node-sourcemap-fail-fastopt.js
[info] Running hai.App
[error] 
[error] /tmp/node-sourcemap-fail/target/scala-2.11/node-sourcemap-fail-fastopt.js:1029
[error]   throw new $c_jl_Error().init___T("hi, i'm error")
[error]                           ^
[error] java.lang.Error: hi, i'm error
org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: node.js exited with code 1
	at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.waitForVM(ExternalJSEnv.scala:96)
	at org.scalajs.jsenv.ExternalJSEnv$ExtRunner.run(ExternalJSEnv.scala:143)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.org$scalajs$sbtplugin$ScalaJSPluginInternal$$jsRun(ScalaJSPluginInternal.scala:479)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$45$$anonfun$apply$27$$anonfun$apply$28.apply(ScalaJSPluginInternal.scala:539)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$45$$anonfun$apply$27$$anonfun$apply$28.apply(ScalaJSPluginInternal.scala:533)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: node.js exited with code 1
[error] Total time: 7 s, completed Jul 20, 2015 9:30:11 AM
```
it works, however, in Chromium (funny thing, Firefox doesn't seem to support stacktraces, although it does correctly load the source map file)
![chromeworksssss](https://cloud.githubusercontent.com/assets/148907/8771689/d95353c8-2ec4-11e5-8c42-c07a3c89d4f7.png)

**Comment by gzm0** [comment]
You are throwing a `java.lang.Error` which is not recognized as JavaScript error by the VM. Therefore, it does not display (or resolve) any stack trace.

You probably meant to throw a `js.Error` (which you cannot throw, since it doesn't extend throwable). I'm not sure if the following does the right thing:

```scala
throw JavaScriptException(new js.Error ("foo"))
```

@sjrd?

**Comment by yawnt** [comment]
the stacktrace is correctly resolved in chromium, however, as you can see from the image :|

**Comment by yawnt** [comment]
my problem is that errors coming from Akka are not under my control, they could be java.lang.Error as far as I know :/

**Comment by sjrd** [comment]
> I'm not sure if the following does the right thing:

Yes it does the right thing, i.e., actually throw the underlying `js.Error`.

Both Chromium and V8 *resolve* the stack traces correctly. The problem is that V8 does not even *display* the stack trace in the console because the exception is not a `js.Error`, whereas Chromium always displays stack traces. If my analysis is correct, I'm not sure there's anything we can do about it. :s

**Comment by gzm0** [comment]
I think we can:

1. Define a `ScalaJSError` which extends `js.Error` and takes a throwable as argument
2. When creating a throwable, create such an `Error` (we need it anyway for traces).
3. At export boundaries, "unwrap" the error
4. At interop boundaries re-wrap the error

Or now that I think of it: Maybe we should only throw these around. We need special handling in Scala `try ... catch` blocks anyway...

**Comment by sjrd** [comment]
Hum ... That's a substantial change in the core mechanism for exceptions. I'll have to think about that.

**Comment by yawnt** [comment]
i'm not familiar with the topic, but V8 does provide some stacktrace API, maybe those could be leveraged?
https://code.google.com/p/v8-wiki/wiki/JavaScriptStackTraceApi

**Comment by sjrd** [comment]
Again, if Node.js doesn't *display* the stack trace in the first place, that doesn't help.
