### ISSUE TITLE
Support secondary constructors in JS classes

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#1811]
Currently an implementation restriction wrt. #1795, coming from the implementation in #1809.

**Comment by sjrd** [comment]
This is technically very involved, although there's nothing fundamentally impossible about it.

The tricky part is that we must have exactly one super constructor call, at the top-level. Consider this first class with only a primary constructor:
```scala
@ScalaJSDefined
class Foo(val x: Int) extends js.Object {
  println("primary ctor")
}
```
Its IR constructor will look like this:
```scala
"constructor"(arg1) {
  val x: int = arg1.asInstanceOf[I];

  super();
  this["x"] = x;

  println("primary ctor")
}
```
Now, if we add a secondary constructor:
```scala
@ScalaJSDefined
class Foo(val x: Int) extends js.Object {
  println("primary ctor")

  def this(y: String) = {
    this(parseInt(y));
    println("secondary ctor");
  }
}
```
Then we need to have something like that:
```scala
"constructor"(arg1) {
  var overload: int = 0;
  var primCtor_x: int = 0;
  if (isInt(arg1)) {
    overload = 1;
    primCtor_x = arg1.asInstanceOf[I];
  } else if (typeof arg1 === "string") {
    overload = 2;
    val secondCtor_y: T = arg1.asInstanceOf[T];
    primCtor_x = parseInt(secondCtor_y)
  } else {
    throw "no overload"
  }

  super();
  this["x"] = primCtor_x;

  println("primary ctor");

  if (overload === 2) {
    println("secondary ctor");
  }
}
```
This gets even more hairy when a third constructor calls a *secondary* constructor. In general, there can be a *tree* of constructors, rooted in the primary ctor, where each ctor is the child of the ctor it calls. In that case, we must:

1. first detect which overload is taken
2. have a tree structure of ifs, in which the leaf constructors extract their parameters first, then perform all the statements they do until they call their "parent" ctor, and prepare the actual parameters for their parent
3. have the statements of the primary ctor until it calls super, with the appropriate arguments
4. have the rest of the primary ctor
5. have again a tree structure of ifs, in the other direction, for the statements in the secondary constructors happening after they call their "parent" ctor

This is going to be a lot of complicated code to handle all that, but it can be done.

**Comment by sjrd** [comment]
Given the technical difficulty of implementing this, I'll delay that to 0.6.6.

**Comment by gzm0** [comment]
This should also forbid adding `@JSExport` annotations on these ctors.
