### ISSUE TITLE
Implement java.util.Arrays utility methods for scala.scalajs.js.Array

### ISSUE THREAD

**Issue by mdedetrich** [scala-js/scala-js#1814]
A lot of the utility methods that are used in Scala/Java (such as `java.util.Arrays.equals`) don't have an equivalent operation for `Scala.js` `Javascript` arrays (`scala.scalajs.js.Array`).

Any problem with implementing a `js.Arrays` object, that has commonly used utility methods that make sense for `Javascript`?

Currently I have to do stuff like

```scala
java.util.Arrays.equals(someJSArray.toArray,anotherJSArray.toArray)
```
Which I assume would have terrible performance for larger arrays since it has to convert it

More than willing to do a PR for this

**Comment by gzm0** [comment]
Hmm... most of the things are available via the Scala collections API... You could for example do:

```scala
val x: js.Array[Int] = // ...
val y: js.Array[Int] = // ...
x.sameElements(y)
```

Which other methods are you missing?

**Comment by mdedetrich** [comment]
Wasn't aware of the `sameElements` method, it was mainly `Arrays.equals` (I am dealing with Java to Scala ported code, so this is the first time I have used scala `Array` non trivially)

**Comment by sjrd** [comment]
Er ... we do have all of `java.util.Arrays` since 0.6.4.

**Comment by sjrd** [comment]
Oops, didn't read carefully enough.

So yes, just use the methods of the Scala collection api. You should have everything you need there.

**Comment by mdedetrich** [comment]
@sjrd , @gzm0 I actually just realized, that there are some methods (particularly specific to Arrays) which is located in `java.util.Arrays`, that people might find handy for `Javascript` arrays.

As an example, `java.util.Arrays.sort` allows you to sort an array according to low index and a high index. As far as I am aware, no such method really exists in Scala collections.

If there is nothing against implementing a `scalajs.js.util.Arrays`, would it be possible to reopen a pull request (I would be willing to go through the various methods in `java.util.Arrays` which don't really exist for Scala collections and implement them through a pull request)
