### ISSUE TITLE
Build for 2.12.0-M2

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#1816]
To add in our build/CI/publish scripts for the next version.

**Comment by sjrd** [comment]
@bvenners, @milessabin Do you typically continue to build new versions of your libraries for earlier milestones of Scala? In other words, do you remove 2.12.0-M1 from your builds/publish'es when you add 2.12.0-M2, or do you accumulate all milestones of 2.12.0 until the final is released?

If you accumulate, we'll accumulate too. But if you don't, we'll probably also not bother.

**Comment by milessabin** [comment]
I only build for the most recent milestone.

**Comment by bvenners** [comment]
I also only build for the most recent milestone.

**Comment by SethTisue** [comment]
I don't think anyone accumulates, that I'm aware of anyway.

M1 is an especially good one to drop, since it was such an oddball (we called it 2.12, but it was still Java 6 based).

**Comment by xuwei-k** [comment]
+1

**Comment by matanster** [comment]
Can you please now publish for M3?

**Comment by sjrd** [comment]
0.6.5 *is* published for M3.

**Comment by matanster** [comment]
Thanks!

**Comment by SethTisue** [comment]
I added it to https://github.com/scala/make-release-notes/blob/2.12.x/projects-2.12.md
