### ISSUE TITLE
Allow nesting objects, traits, and classes inside objects that extend js.Object

### ISSUE THREAD

**Issue by benjaminjackman** [scala-js/scala-js#1820]
Currently ScalaJS prevents nesting objects, traits, and classes inside objects, traits, and classes that extend js.Object.

It would be nice to relax this restriction abit for modeling certain javascript APIs inside facade types in a way that more naturally maps to their own style.

In code form, it is requested that this:
```
object A extends js.Object {
  object B extends js.Object
  class B extends js.Object
}
class A extends js.Object
```
compiles

Consideration should be given to how the mapping of names occurs but I think generally the names should map for the class B / object B as though they are nested under whatever `@JSName` is assigned to object A

--Or--

a `@JSName` could be required for them as well

**Comment by lihaoyi** [comment]
lol I remember asking for this 2 years ago when I was first facading chipmunk.js, just so I wouldn't need to `@JsName` everything in https://github.com/lihaoyi/roll/blob/master/src/main/scala/roll/cp/Facades.scala

Cool to see it finally happening =D =D =D
