### ISSUE TITLE
Finally block not executed in a partest case

### ISSUE THREAD

**Issue by nicolasstucki** [scala-js/scala-js#1828]
The code is supposed to print a sting in the `finally` block but there is no output.

Bug found in partest run/t6102.scala
```scala
// SI-6102 Wrong bytecode in lazyval + no-op finally clause

object Test {

  def main(args: Array[String]) {
    try {
      val x = 3
    } finally {
      print("hello")
    }
  }
}
```

**Comment by nicolasstucki** [comment]
This is on 2.12.0-M2

**Comment by sjrd** [comment]
This turns out not to be a bug. It's just that the test uses `print` instead of `println`, which means the string is not flushed and not sent to the output.
