### ISSUE TITLE
Function value for a function returning a type projection isn't translated correctly

### ISSUE THREAD

**Issue by virtualirfan** [scala-js/scala-js#1831]
Here's a quick example:
```Scala
object D3Types {
  type OrdinalValue = String
  type NumericalValue = Double
}

sealed class AcceptableScale[X] private()
object AcceptableScale {
  implicit object OAcceptable extends AcceptableScale[OrdinalValue]
  implicit object NAcceptable extends AcceptableScale[NumericalValue]
}
sealed trait D3ChartValueT {
  type T
  def x: T
  def y: Double
}
object D3ChartValueT {
  def x[T: AcceptableScale](v: D3ChartValueT): D3ChartValueT#T = {
    println(v.x)
    v.x
  }
  def y[T: AcceptableScale](v: D3ChartValueT): NumericalValue = {
    println(v.y)
    v.y
  }
}
```
While fine at compile time, at runtime, y is an actual function whereas x is an Object containing a function. Here's some output from JS console in Chrome:
```javascript
> x
$c_sjsr_AnonFunction1 {}
> x
$c_sjsr_AnonFunction1 {}f$2: (v$2$21)arguments: (...)caller: (...)length: 1name: ""prototype: Object__proto__: ()<function scope>__proto__: $h_sr_AbstractFunction1
> x.f$2
anonymous(v$2$21)
> y
$c_Lcom_payalabs_scalajs_react_bridge_GeneratedImplicits$$anon$2.toJs__F1__sjs_js_Any(arg1)
```
Calling y in JS works as expected, returning an integer.
```javascript
y.call(stack, v, i)
4
```

**Comment by sjrd** [comment]
What are your `@JSExport`s? You're taking about about calling from JavaScript but I don't see any export. Non exported stuff cannot be called from JS; how they're translated is an implementation detail.

How do you construct `x` and `y` in your js snippet?

**Comment by virtualirfan** [comment]
My bad for not explaining. No exports. I'm passing to D3 via scalajs-react-bridge like below. D3 receives my functions by value and not by name and calls them. Note this machinery works for lots and lots of functions where I create a partial function to pass the function value to D3. Even in this example, the function `y` gets passed correctly, just not function `x`.

```Scala
case class BarChart(
                   // unrelated params removed 
                    data: js.UndefOr[D3BarChartDataT] = js.undefined,
                    x: js.UndefOr[Any] = js.undefined,
                    y: js.UndefOr[D3ChartValueT => NumericalValue] = js.undefined
                    )
  extends ReactD3Component // from scalajs-react-bridge
```
Used like this:
```
      BarChart(
        // unrelated params removed 
        , data = d3d  // has a member Seq[D3ChartValueT] on which D3 does a map to call x and y below
        , x = D3ChartValueT.x[OrdinalValue] _
        , y = D3ChartValueT.y[NumericalValue] _
      )()
```
where D3 is going to call it's `x` which has been initialized to point to D3ChartValueT.x.

Too much detail here but I wanted to over-communicate. Bottom line is that `x` and `y` are different in how they are compiled into JS.

**Comment by virtualirfan** [comment]
Argh ... user error. Turns out this was the culprit:
```Scala
                    x: js.UndefOr[Any] = js.undefined,
```
Once switched over to:
```
                    x: js.UndefOr[D3ChartValueT => D3ChartValueT#T] = js.undefined,
```
things are fine. Sorry.
