### ISSUE TITLE
Qml & ScalaJs ? :-)

### ISSUE THREAD

**Issue by swhgoon** [scala-js/scala-js#1832]
It seems a bad idea as i tried and blocked by qml's **JavaScript Environment Restrictions**.
[List of objects, functions and properties supported by the QML engine](http://doc.qt.io/qt-5/qtqml-javascript-functionlist.html)
Functions&Callbacks between qml's objects and scalajs's have been tested and passed by converting `fastOpt.js`...
Maybe another way?

**Comment by sjrd** [comment]
This should probably be discussed on the mailing list, or on gitter. Not in the issue tracker.

**Comment by swhgoon** [comment]
[quickly/quickly: ES6 and Node.js-like environment for QML](https://github.com/quickly/quickly)
