### ISSUE TITLE
Target asm.js

### ISSUE THREAD

**Issue by mdedetrich** [scala-js/scala-js#1834]
Links
https://en.wikipedia.org/wiki/Asm.js
http://asmjs.org/

It may be useful, at some point in time, to consider targeting `asm.js`. Doing so should provide better performance, as well as compatibility.

Thoughts?

**Comment by sjrd** [comment]
http://www.scala-js.org/doc/faq.html

**Comment by mdedetrich** [comment]
Just letting you know, that `asm.js` has updated their faq, specifically what they say (now) about supporting managed languages

>
Q. Can asm.js serve as a VM for managed languages, like the JVM or CLR?
A. Right now, asm.js has no direct access to garbage-collected data; an asm.js program can only interact indirectly with external data via numeric handles. In future versions we intend to introduce garbage collection and structured data based on the ES6 structured binary data API, which will make asm.js an even better target for managed languages.

So I suppose if and when that ever happens, it might be worth looking at

**Comment by mkotsbak** [comment]
Maybe Scala Native is a better source for targeting asm.js?
