### ISSUE TITLE
@ScalaJSDefined  classes constructor name is empty

### ISSUE THREAD

**Issue by chandu0101** [scala-js/scala-js#1840]
```scala

@ScalaJSDefined
class Hello extends ReactComponent[Any,Any] {
  val displayName = "Hello"
}

val dummyHello = new Hello()
val ctor = dummyHello.asInstanceOf[js.Dynamic].constructor
js.Dynamic.global.Hello = ctor

```
In browser console

```js
 Hello.name = ""
```

In js world 

ES6 class : 
```js
class Hello  {
}
```
Transpiled code (https://babeljs.io/repl/) 

```js
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var Hello = function Hello() {
  _classCallCheck(this, Hello);
};
```

In browser console 

```js
var x = new Hello()
x.constructor.name = "Hello"
```

I also created an issue in react : https://github.com/facebook/react/issues/4574

**Comment by chandu0101** [comment]
>This is something that needs to be solved at the scala-js language compatibility level. Ideally it should preserve the "function" name when it exports a JS class

is it possible to emit function with name ? 

currently the generated code looks like this 

```js
var $c_Lchandu0101_scalajs_examples_WebApp$Hello = (function () {
  $c_Lchandu0101_scalajs__ReactComponent["call"](this);
}
```
when i modified output to 

```js
var $c_Lchandu0101_scalajs_examples_WebApp$Hello = 
(function  $c_Lchandu0101_scalajs_examples_WebApp$Hello() {
  $c_Lchandu0101_scalajs_ReactComponent["call"](this);
}

```
now apparently constructor name is non empty in console

Hello.name =  ``$c_Lchandu0101_scalajs_examples_WebApp$Hello``

**Comment by chandu0101** [comment]
@sjrd  any love for this in initial version of scalajsdefined ?

**Comment by sjrd** [comment]
No. It requires changes that are unrelated to Scala.js-defined JS classes, so that'll be for a separate PR.

**Comment by chandu0101** [comment]
oh ok :)

**Comment by chandu0101** [comment]
:+1:
