### ISSUE TITLE
Useful toString for JSDependency in sbt> show jsDependencies

### ISSUE THREAD

**Issue by dwalend** [scala-js/scala-js#1844]
I'm trying to debug why I don't get .js files included from my local resources directory (probably something simple I haven't spotted yet) using sbt's show command. 

JSDependency has an uninformative default toString() that only shows me its memory address.

> showj sDependencies
[info] List(RuntimeDOMDep(None), ProvidedJSModuleID(org.scalajs.core.tools.jsdep.JSDependency@39b81da,None))

I'd much prefer something that shows me the list of what's included.

> show libraryDependencies
[info] List(org.scala-lang:scala-library:2.11.7, org.eclipse.jetty:jetty-websocket:8.1.16.v20140903:phantom-js-jetty, org.eclipse.jetty:jetty-server:8.1.16.v20140903:phantom-js-jetty, org.scala-js:scalajs-compiler:0.6.4:plugin->default(compile), org.scala-js:scalajs-library:0.6.4, org.scala-js:scalajs-dom:0.8.1, com.lihaoyi:utest:0.3.0:test)

Thanks,

Dave

**Comment by gzm0** [comment]
That is a very reasonable request indeed :)

**Comment by dwalend** [comment]
Thanks!
