### ISSUE TITLE
Setting/task to prepend and append stuff in the emitted .js

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#1845]
So that we can do stuff like http://stackoverflow.com/questions/26637600/how-to-convert-scala-js-application-to-commonjs-module trivially.

We could also follow up with a shortcut `nodeModuleSettings` that automatically adds the appropriate prepend/append to turn the code emitted by Scala.js into a Node.js module.

**Comment by gzm0** [comment]
Hahaha, I just thought that we should probably do this today :P
