### ISSUE TITLE
java.util.concurrent.ThreadLocalRandom

### ISSUE THREAD

**Issue by andreaTP** [scala-js/scala-js#1859]
In scala there is a java implementation of ThreadLocalRandom ( https://github.com/scala/scala/blob/0b47dc2f28c997aed86d6f615da00f48913dd46c/src/forkjoin/scala/concurrent/forkjoin/ThreadLocalRandom.java ) if this implementation of Random (that basically uses Date.now()) satisfy you ( https://github.com/gwtproject/gwt/blob/master/user/super/com/google/gwt/emul/java/util/Random.java ))
I will go for an implementation in pure Scala.

**Comment by sjrd** [comment]
Are you talking about implementing [`java.util.concurrent.ThreadLocalRandom`](http://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ThreadLocalRandom.html)?

There is no real difficulty in implementing it. There is just one thread, so `current()` always returns a singleton instance, whose seed is initialized using `js.Math.random()`, just like that of `Random` at https://github.com/scala-js/scala-js/blob/master/javalib/src/main/scala/java/util/Random.scala#L164

There's no need to look at GWT's `Random.java`. We already have ours in `java.util.Random.scala`, and it has been optimized for Scala.js.

The only difficulty lies in additional methods declared in `ThreadLocalRandom`, *especially* `nextDouble(least, bound)`, for which obtaining a uniform distribution is less than trivial.

**Comment by andreaTP** [comment]
I mean exactly ```scala.concurrent.forkjoin.ThreadLocalRandom``` from scala repo, and there ```nextDouble``` is simply implemented in function of the ```java.util.Random.nextDouble``` .
So it will be trivial.

I'll go for it!

**Comment by sjrd** [comment]
Hum but we don't include `scala.concurrent.forkjoin` at all. And that library disappears in 2.12. I don't see why we should add it now.

**Comment by sjrd** [comment]
See https://github.com/scala/scala/pull/4629

**Comment by andreaTP** [comment]
argh... I wasn't aware of this,
I definitely need ```nextInt``` that should be trivial even for java implementation, and maybe  we can add the ```scala.concurrent.forkjoin``` in overrides of scala 2.10, 2.11 adding also it's unchecked distribution of Doubles.
What do you think?

**Comment by sjrd** [comment]
Why not simply use (and implement) `java.util.concurrent.ThreadLocalRandom`?

**Comment by andreaTP** [comment]
I'll go for an implementation of ```java.util.concurrent.ThreadLocalRandom``` but, as usual, akka does use ```scala``` one, so code cross compatibility again....

**Comment by andreaTP** [comment]
but I can ask Akka's guys how do this sounds to them!

**Comment by andreaTP** [comment]
ok, I go for the java one!

**Comment by andreaTP** [comment]
Do I have to check anything special in the ```nextDouble``` implementation?
https://github.com/andreaTP/scala-js/blob/threadLocalRandom/javalib/src/main/scala/java/util/concurrent/ThreadLocalRandom.scala

in the implementation in the scala lib they wrote:
```
     * Returns a pseudorandom, uniformly distributed value between the
     * given least value (inclusive) and bound (exclusive).
```
so basically all it's needed by the java one, correct?

**Comment by sjrd** [comment]
I guess you don't need anything fancy if the implementation you found was correct.

**Comment by andreaTP** [comment]
good! I write the tests and PR
