### ISSUE TITLE
Await.result should work

### ISSUE THREAD

**Issue by lihaoyi** [scala-js/scala-js#186]
``` scala
import concurrent.duration._
Await.result(Future(1), 10 seconds)
```

This results in 

```
TypeError: Cannot find function java_lang_Thread in object [object Object].
```

It should probably just be an alias for `Future.get` in ScalaJS since we can't block. That would save manually writing `Future` wrappers which do the same thing anyway in order to get code cross-compiling on JS/JVM.

**Comment by SemanticBeeng** [comment]
May I see your (code :-) wrapper please?
