### ISSUE TITLE
Default constructor params don't work with @ScalaJSDefined classes

### ISSUE THREAD

**Issue by russpowers** [scala-js/scala-js#1876]
This code compiles with no errors:

```scala
@ScalaJsDefined
class TestClass(val a: Int = 5) extends js.Object
```

But then it throws this runtime error when you try to instantiate `TestClass` without arguments:

`Uncaught scala.scalajs.runtime.UndefinedBehaviorError: An undefined behavior was detected: undefined is not an instance of java.lang.Integer`

**Comment by sjrd** [comment]
Hi,

Thanks for the report. I discovered that a few hours earlier. I have a PR where it doesn't compile anymore. We'll make it compile and do the right thing in a future version.

**Comment by russpowers** [comment]
Ok, thanks!
