### ISSUE TITLE
Provide implementations for missing Javascript Native statements

### ISSUE THREAD

**Issue by mdedetrich** [scala-js/scala-js#1882]
This is mainly for performance considerations, which aren't an issue for most use cases, but definitely is an issue for other use cases (my current use case is implementing like `TimSort` for Scala.js)

A lot of these high performant algorithm implementations tend to use stuff like `break`, `continue` and `break to label`, i.e. in java this looks like

```java
first:
for( int i = 0; i < 10; i++) {
  second:
  for(int j = 0; j < 5; j ++ )
  {
    break first;
  }
}
```

Unfortunately Scala doesn't labelled `while`/`for` loops. Scala also doesn't implement `break`, there is an implementation of `break` in `scala.util.Control.Breaks`, however this throws an exception (i.e. its not an actual `break` in the Java/C/Javascript sense). Stuff like continue to label can be implemented using functions/closures, however it will have less performance than your `break to label` implementation.

Scala did not implement the Java/C/Javascript `break` because in context of closures/lambda's, the behaviour of break isn't defined. Regarding `break to label`, you can get around this in Scala by just implementing that code in Java and then interfacing with it in Scala. You can't really do this in `Scala.js`, you are forced to use 100% Scala.

Is there merit in providing a library that allows you to implement this functionality in Scala.js so it maps direct correct statements in Javascript. That is, being able to write a `break` in Scala.js so that is compiles to an actual `break` in `Javascript`, and same deal with `continue`/`break to label`? Note that this may not be an issue if the optimizer does actually do this automatically (I will have to verify myself when I actually finish `Timsort`), however I remember with my other work on soda-time, even with full optimizations, stuff generally doesn't get compiled down to `break`/`break to label`/`continue`.

**Comment by sjrd** [comment]
Er ... no.

You might not realize it, but Scala *does* have all the features you need to generate exactly what you want. Typically using some form of tail-recursion and/or local defs and return.

For example, your snippet above can be written as:
```scala
@inline
def loop(): Unit = {
  var i = 0
  while (i < 10) {
    var j = 0
    while (j < 5) {
      return
      j += 1
    }
    i += 1
  }
}
loop()
```
The `return` acts as a `break to label`. `continue`s can be implemented with tail-recursive functions. With `@inline`, at least in Scala.js, your local def will be inlined away.

**Comment by mdedetrich** [comment]
I will have to investigate further then, when working on Soda-Time I was hitting cases where this wasn't happening, although it may have been user error
