### ISSUE TITLE
Compiler crash

### ISSUE THREAD

**Issue by SRGOM** [scala-js/scala-js#1886]
Repro:

    git clone https://github.com/ochrons/scalajs-spa-tutorial/
    curl http://sprunge.us/eOFB --output scalajs-spa-tutorial/client/src/test/scala/spatutorial/client/ukko/DelayerSpec.scala
    cd scalajs-spa-tutorial
    sbt client/test

I should note that the project above uses a slightly older version of scalajs but I get the same crash with the latest version too.

**Comment by sjrd** [comment]
Thanks. I will look into that after the 0.6.5 release.

**Comment by sjrd** [comment]
This is not a Scala.js bug. It is either a scalac or a uTest bug (probably uTest and its macros). Here is a minimal reproduction requiring only uTest 0.3.1, and it blows up when compiling with Scala/JVM:
```scala
package test

import utest._

object DelayerSpec extends TestSuite {
  val tests = TestSuite {
    def byName(body: => Any): Any = body

    def executionCallback(callParams: Int): Unit = {
    }

    'CrashCompiler {
      byName {
        val f = executionCallback _
      }
    }
  }
}
```
I will close this here. You should report this bug to uTest.
