### ISSUE TITLE
Build hangs on full GC then OOMs

### ISSUE THREAD

**Issue by holograph** [scala-js/scala-js#1888]
While I don't know if this is a regression in 0.6.4 since it's the first I've used it (making this potentially related to #1788), the build (and especially test) run time has skyrocketed for me since including Scala.js in my latest work on [Accord](https://github.com/wix/accord/issues/19). On the [js-example](https://github.com/wix/accord/tree/js-example) branch, the build consistently hangs while running tests, churning FGC and eventually crashing on OOM.

I've extracted a quick heap dump and ran it through MAT (it's still available, but at 1.3GB pre-compression it'll probably be easier to just repro and generate your own...), and the following picture emerges:

Label | Number of Objects | Used Heap Size | Retained Heap Size | Retained Heap, %
----- | ----------------- | -------------- | ------------------ | ----------------
org.scalajs.core.ir.Infos$ClassInfo | 24,318 | 972,720 | 191,923,984 | 23.06%
sbt.Execute | 1 | 64 | 166,774,008 | 20.04%
org.scalajs.core.ir.Infos$MethodInfo | 181,233 | 8,699,184 | 72,845,432 | 8.75%
org.scalajs.core.tools.classpath.builder.JarTraverser$$anon$1 | 6,505 | 208,160 | 72,231,136 | 8.68%
org.scalajs.core.tools.optimizer.Linker | 12 | 480 | 71,143,720 | 8.55%

The way this behaves, plus the fact that upping the memory limit even to 4GB only delays but does not eliminate the issue for me, seems more indicative of a leak somewhere than mere memory usage.

**Comment by holograph** [comment]
A few extra details: running on latest Mac OS X with Oracle JDK 1.8.0_60 64-bit, and with `export SBT_OPTS='-Xmx1536m'`.

**Comment by InTheNow** [comment]
+1 Same issues from me.

**Comment by sjrd** [comment]
@holograph It seems to me that you are testing with Rhino. I don't see any mention of `scalaJSStage` in your repo, especially not in `.travis.yml`. On reasonably large projects, there's no way Rhino is an acceptable solution. It's extremely slow and consumes much too much memory.

You should use `scalaJSStage in Global := FastOptStage` to run and test with Node.js (which is available on Travis machines).

If that doesn't solve the problem, then we can start investigating in Scala.js.

**Comment by holograph** [comment]
Alas, same result (though it *does* seem to get further into the build). I haven't even tested on Travis because it fails locally, where I can get much more rapid feedback.

Repro steps:

```
git clone git@github.com:wix/accord.git
git checkout js-example
export SBT_OPTS="-XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC -XX:MaxPermSize=2G -Xmx4G -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=$HOME"
sbt +test
```

Result: `java.lang.OutOfMemoryError: Java heap space`. Running the heap dump (available [here](http://we.tl/b1qtvwcXUs) for a week or so) through MAT paints a different picture, with a single `org.scalajs.core.tools.optimizer.ScalaJSOptimizer` now the dominating heap utilization (largely due to `org.scalajs.core.tools.optimizer.Linker#files`).

It seems I'm getting in way over my head, but if there's something I can do to assist in figuring this out, let me know and I'd be happy to help (especially as this is a real issue with Accord...)

**Comment by sjrd** [comment]
I will have a look at it, although I won't be able to do anything before September 14, as I'll be traveling.

**Comment by holograph** [comment]
No worries, I'll update if I find anything useful out in the meantime.

**Comment by sjrd** [comment]
We (mostly @gzm0) are working on large-scale changes to reduce memory consumption, but it takes time, and we're far from being done.

**Comment by ngbinh** [comment]
We are having the same problem.

**Comment by sjrd** [comment]
Does this still happen with 0.6.6?

**Comment by holograph** [comment]
Sorry for the delay; I'm happy to report it does not -- problem solved :-)

**Comment by gzm0** [comment]
Closing this, since 0.6.6. solved it.
