### ISSUE TITLE
Actors and Akka

### ISSUE THREAD

**Issue by lihaoyi** [scala-js/scala-js#189]
Now that ScalaJS has a (mostly) working implementation of Futures, Promises and ExecutionContexts (#88) it would be cool to flesh out the other abstractions in the Akka toolkit to see how well we can get them working in ScalaJS. Although Javascript is single threaded, the fact that the bulk of Akka's abstractions also rely on non-blocking event loops should make them much more transferrable.

Some work in progress [here](https://github.com/sjrd/scala-js-actors)

**Comment by gzm0** [comment]
https://github.com/unicredit/akka.js
