### ISSUE TITLE
Class with constructors with optional parameters can't be embedded in Objects that extend js.Object

### ISSUE THREAD

**Issue by benjaminjackman** [scala-js/scala-js#1891]
```scala
@js.native object A extends js.Object {
  @js.native class B(x : Int = ???) extends js.Object
}
```

produces

> Native JS objects cannot contain inner Scala traits, classes or objects (i.e., not extending js.Any)

**Comment by sjrd** [comment]
That would happen because the default accessor is sent to an automatically generated companion object, which does not extend `js.Any`. That companion object is invisible in the code, but the Scala.js checks choke on it. We should avoid complaining about synthetic companion objects in those cases.

**Comment by benjaminjackman** [comment]
Ok so as work around I should be able to define a companion that does extend js.Object and has @js.native?

**Comment by benjaminjackman** [comment]
To answer my own question:
```
@js.native object A extends js.Object {
  @js.native object B extends js.Object
  @js.native class B(x : Int = ???) extends js.Object
}
```
does indeed compile

**Comment by sjrd** [comment]
Ah ah! Yep ...
