### ISSUE TITLE
Support for getting a Future completed by dom.setTimeout()

### ISSUE THREAD

**Issue by mkotsbak** [scala-js/scala-js#1898]
Since SJS has no Thread.sleep(), it would be nice to have an easy way to get a Future that completes after x milliseconds, so you don't need to mix in dom.setTimeout() inside a Future chain.

Here is a proposed solution:

```scala
  def delayedFuture[T](millis: Double, param: T = Unit): Future[T] = {
    val p = Promise[T]()

    dom.setTimeout( () => p.success(param), millis)
    p.future
  }
```

Maybe it should be placed at Future, like
Future.delayed(millis: Double, param: T = Unit): Future[T]

**Comment by mkotsbak** [comment]
What I wanted to use this for was in recoverWith() after an Ajax request to add a delay before a retry. It seems like the result of delayedFuture then must be applied to flatMap, but I fail to get that to compile...

**Comment by jducoeur** [comment]
Hmm.  Would the [jsext](https://github.com/jducoeur/jsext) library's `withTimeout` suffice?  In general, I'm not sure this problem is common enough to need to be in the SJS core...

**Comment by mkotsbak** [comment]
Ah, haven't looked at that library yet. withTimeout is the opposite really, but you may add my function(s) above to RichFuture yes.

It is probably a bad idea to add it into Future if it isn't supported on the JVM. There you might not see so many requests for this since you have Thread.sleep().

**Comment by jducoeur** [comment]
Pull requests are welcomed -- since you've got an idea of what you're looking for, I'd recommend that you submit a PR for that on RichFuture...

**Comment by sjrd** [comment]
As discussed above, I don't think this should be part of the Scala.js standard library.
So I'll close this here. We can reconsider if many people want to push such a sugar to the std lib.

**Comment by kevinwright** [comment]
Okay, I know it's closed...

But for future reference of anyone else discovering this ticket, I've found that AsyncScheduler from [scala.rx](https://github.com/lihaoyi/scala.rx) solves this rather neatly.

**Comment by cuzfrog** [comment]
I'm happy to see `Thread.sleep` implemented in scala.js as a representation of `delay/setTimeout` in javascript

**Comment by sjrd** [comment]
@cuzfrog `Thread.sleep` *cannot* be implemented in Scala.js, because it's a blocking API, and JavaScript doesn't do blocking.

**Comment by cuzfrog** [comment]
Blocking is generous disastrous. However blocking has some debug/dev value. Or it can be a shorthand in such: 
```scala
Future{
   Thread.sleep(?)
   //setTimeout to execute.
}
```

**Comment by sjrd** [comment]
It's impossible to implement `Thread.sleep`. Besides, even if you could, *nothing* would happen in the elapsed time: handlers are not executed, events are not triggered, other futures waiting to run don't get to run. So it doesn't have debug value either.

This is *impossible*.

**Comment by ochrons** [comment]
A naive implementation of `Thread.sleep` is possible, but pretty much useless since it blocks everything, including the browser UI 😜 

```
def sleep(ms: Long): Unit = {
  val expTime = System.nanoTime + ms*1000000
  while(System.nanoTime < expTime) {}
}
```

**Comment by cuzfrog** [comment]
I'm very happy and honored to discuss with you guys here. 

>Web Workers provide a simple means for web content to run scripts in background threads.

Js + its env together is literally multi-threaded. `Thread` as a concept is able to be used in js context. When Thread blocks in "js main thread", compiler should yield an error or at least warning. For other threads, `sleep` actually represents `setTimeout`, but may be used in scala code more conveniently. Because `setTimeout` belongs to dom in js, using it directly in scala code is sort of awkward. In these senses, it has some degree of debug/dev value, though little.

May later version of javascript bring this concept to the table and provide native block or delay(prefered) function in background threads.

Btw, `while(System.nanoTime < expTime) {}` is not acceptable, it consumes CPU power.

**Comment by mkotsbak** [comment]
Webworkers has been discussed before and does not correspond to a java Thread. I think the issue is that they can't share data.

**Comment by sjrd** [comment]
> For other threads, `sleep` actually represents `setTimeout`, but may be used in scala code more conveniently.

You can't implement that. There is no way to implement `sleep` on top of `setTimeout`, even in Web Workers. I challenge you to give it a try.

**Comment by cuzfrog** [comment]
@sjrd Your challenging encourages and honors me. I uses a timer, to partially make it into action:
[js-block-toy-implementation](https://scalafiddle.io/sf/17rx0od/1)

**Comment by sjrd** [comment]
@cuzfrog Ah but you cheated. You didn't implement the `Thread.sleep` API nor its contract. Your experiment there is not enough to show that `Thread.sleep` can be implemented.

In fact, your implementation is still asynchronous and non-blocking, as you demonstrate yourself with the "broken" message.

**Comment by andreaTP** [comment]
I know it is pretty hackish and specific,  but Akka. Js testkit implement Thread.sleep on top of a custom event loop.
