### ISSUE TITLE
A Reactive UI Library

### ISSUE THREAD

**Issue by lihaoyi** [scala-js/scala-js#190]
Scala's a really nice language to use for building GUIs and exploring new programming paradigms. One such paradigm is a UI based around change-propagation/[FRP](http://en.wikipedia.org/wiki/Functional_reactive_programming). There are several Javascript libraries such as [AngularJS](http://angularjs.org/), [Knockout.js](http://knockoutjs.com/) and [React](http://facebook.github.io/react/) which support this style of programming, as well as Scala libraries like [Scala.Rx](https://github.com/lihaoyi/scala.rx) and [Scalatags](https://github.com/lihaoyi/scalatags) which are compatible with ScalaJS and can be used to build client-side GUIs. 

It would be cool to explore the design space to see what kind of libraries and frameworks can be built around the idea of a Reactive UI in the browser using ScalaJS

Previous Discussion:
[Angular-like bindings / UI-updating](https://groups.google.com/forum/#!topic/scala-js/2QT-Ia3OaIY)
[facebook react](https://groups.google.com/forum/#!topic/scala-js/UsgqB7WRtjE)
[scala.js and reactjs](https://groups.google.com/forum/#!topic/scala-js/zS7jAUSeuCg)

**Comment by Sergey80** [comment]
```
 form(
            inputBox, 
```

not suppose to work if 

```
 val inputBox = input(
    id:="new-todo",
    placeholder:="What needs to be done?",
    autofocus:=true
  ).render
```

already rendered in html
