### ISSUE TITLE
Static class properties should be inherited

### ISSUE THREAD

**Issue by spicyj** [scala-js/scala-js#1900]
In ES6 classes, static properties should be inherited. That is,

```js
class Foo {
}
Foo.x = 5;

class Bar extends Foo {
}

console.log(Bar.x);
```

should log "5". This can be done by looping over the properties and copying, but that's subpar because updating the static properties on the superclass should update them on the subclass too. Babel sets `__proto__` to achieve this:

https://github.com/babel/babel/blob/554fda00c179eea72121cafe4b90fac85c1bb244/packages/babel/src/transformation/templates/helper-inherits.js#L13

It doesn't look like the ES5 emitter makes any attempt to get the same behavior:

https://github.com/scala-js/scala-js/blob/bb2e2a7a53bbd1de5f12cbb899c0ea320fe98c37/tools/shared/src/main/scala/org/scalajs/core/tools/javascript/ScalaJSClassEmitter.scala#L202-L257

This means scala-js does not work with React 0.14+ which checks for a static flag on classes extending React.Component:

http://stackoverflow.com/questions/32509891/warning-react-component-classes-must-extend-react-component-0-14-rc1

**Comment by spicyj** [comment]
(updated, sorry)

**Comment by sjrd** [comment]
Hum, this is pretty annoying. Why would they even specify something like that in ES6 in the first place?

My main concern about this is that there is no standard way to implement this behavior in ES5.1. Neither `__proto__` nor `setPrototypeOf` are standard in ES 5.1 ([`setPrototypeOf` is standard in ES 6](http://www.ecma-international.org/ecma-262/6.0/#sec-object.setprototypeof); and [`__proto__` is standard in web browser ES 6](http://www.ecma-international.org/ecma-262/6.0/#sec-additional-properties-of-the-object.prototype-object)). Choosing to use one or the other, or both, would therefore make us not comply to ES 5.1 anymore.

It seems like a small thing, but so far we have successfully avoided to rely on even the slightest non-standard feature. Breaking this here, even for a "widely supported non-standard extension" such as `__proto__`, would set a precedent for breaking more things like that in the future, and I don't like that.

Note that "widely supported" does *not* include IE < 11. So any code relying on this just can't work in IE 10 and earlier (and *no*, this is not bashing against IE; on the contrary, IE was the only browser to not deviate from the standard, here; everybody else is to blame). It is also unclear whether Rhino supports it.

And that's even without even considering the fact that setting `__proto__` or using `setPrototypeOf` causes severe performance issues on the target objects.

On the other hand, it seems we don't even have a choice, if frameworks like React start relying on this prototype chain behavior. Why would they do such a thing when there is no workaround on IE 10!?

**Comment by spicyj** [comment]
My mistake, I didn't realize this wasn't supported in IE10. We'll reconsider for React 0.14 final.

**Comment by sjrd** [comment]
Cool, [they changed React](https://github.com/facebook/react/pull/5021) not to rely on static property inheritance anymore :) So I believe we can close this on our end.

Thanks React's team :-)

**Comment by spicyj** [comment]
I still suggest that you at least copy over static properties at class creation time.

**Comment by sjrd** [comment]
Without a compelling use case needing inheritance but not the ability to define static members (as React requiring us to do so would have been), a solution to this problem should be part of #1902 anyway.

**Comment by spicyj** [comment]
Okay, sounds great!
