### ISSUE TITLE
Support for static fields in @ScalaJSDefined classes

### ISSUE THREAD

**Issue by chandu0101** [scala-js/scala-js#1902]
Tracking issues for  https://groups.google.com/forum/#!topic/scala-js/v3gue_-Tms4

**Comment by xsistens** [comment]
:+1:

**Comment by chandu0101** [comment]
@sjrd 

I working on mutation's in Relay (https://facebook.github.io/relay/docs/api-reference-relay-mutation.html#fragments-static-property), 

Relay.Mutation class has static field `fragments` in our mutation class we must define fragments. 

```scala
@ScalaJSDefined
class AddTodoMutation(props : js.Dynamic) extends RelayMutation(props) {
... 
}

val addTodoCtor = js.constructorOf[AddTodoMutation]
val addTodoFragFunction: js.Function = ..
addTodoCtor.fragments = js.Dictionary("viewer" -> addTodoFragFunction)
 
``` 

this indeed solved one of two problems but for other problem  react-relay looking for `fragments` field in base class(RelayMutation) constructor https://github.com/facebook/relay/blob/fbf8c50825ff609a5ab101a934f0b9e165ab5d9b/src/mutation/RelayMutation.js#L230

can we work around this problem .. ?

**Comment by sjrd** [comment]
I don't understand what *is* the problem? Can you elaborate?

**Comment by chandu0101** [comment]
sure , 
https://github.com/facebook/relay/blob/fbf8c50825ff609a5ab101a934f0b9e165ab5d9b/src/mutation/RelayMutation.js#L230

```js

 var fragments = RelayDeprecated.getMutationFragments(this.constructor);

  getMutationFragments: function getMutationFragments(Mutation) {
	    var queries = Mutation.queries;
	    if (queries && !Mutation.fragments) {
	      RelayDeprecated.warn({
	        was: Mutation.name + '.queries',
	        now: Mutation.name + '.fragments'
	      });
	      Mutation.fragments = queries;
	    }
	    return Mutation.fragments;  // its looking for static fragments field
	  }
```
in runtime fragments is undefined for `AddTodoMutation`  , what i really want is my fragments should be available in constructor. 

 `addTodoCtor.fragments = js.Dictionary("viewer" -> addTodoFragFunction)`   this line is not useful in above scenario.

**Comment by sjrd** [comment]
Isn't `this.constructor` exactly `eq` to `js.constructorOf[AddTodoMutation]` at that point?

**Comment by chandu0101** [comment]
no

**Comment by sjrd** [comment]
Er then ... what *is* it? Maybe that's the problem?

**Comment by chandu0101** [comment]
hmm , this.constructor returning RelayMuttion(BaseClass) constructor
<img width="1122" alt="screen shot 2015-10-08 at 3 33 12 pm" src="https://cloud.githubusercontent.com/assets/2179670/10363426/11132e9a-6dd2-11e5-9de7-251936be9001.png">

**Comment by chandu0101** [comment]
in theory my guess is that   `js.constructorOf[AddTodoMutation].fragments = ..`  this should copy fragments to all base class constructors if possible ?

**Comment by sjrd** [comment]
No, definitely not. That is not at all how things are supposed to work. If `this.constructor` is `RelayMutation`, it is normal that `this.constructor.fragments` would not take the `fragments` from `AddTodoMutation` which is a subclass of `RelayMutation`. Imagine what would happen if that were the case, and there were *two* sublcasses of `RealyMutation`, each defining their own `fragments`. That just does not make sense.

I guess the bug is somewhere else, and `this` does not refer to the appropriate thing, at that point.

**Comment by chandu0101** [comment]
>I guess the bug is somewhere else, and this does not refer to the appropriate thing, at that point

yeah , i just tested pure [js classes](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=false&code=class%20RelayMutation%20%20%7B%0A%20static%20fragments%3B%0A%20checkThis()%20%7B%0A%20%20%20console.log(this.constructor)%0A%20%20%20console.log(this.constructor.fragments)%0A%20%7D%0A%7D%0A%0Aclass%20AddTodoMutation%20extends%20RelayMutation%20%7B%0A%0A%20%20static%20fragments%20%3D%20%22addtodo%22%0A%7D%0A%0A%0A%0A) , super class this.constructor is referring to subclass constructor . may be its related to @ScalaJSDefined / ???,  i'll do more research tomorrow :)

**Comment by chandu0101** [comment]
Its happening in `fullOptJS` mode only 

**fullOptJS** : 

<img width="707" alt="screen shot 2015-10-09 at 3 36 04 am" src="https://cloud.githubusercontent.com/assets/2179670/10381423/428dc0be-6e38-11e5-8cb8-39a90fedf776.png">

**fastOptJS** : 

<img width="725" alt="screen shot 2015-10-09 at 3 34 59 am" src="https://cloud.githubusercontent.com/assets/2179670/10381427/53332f62-6e38-11e5-94d3-3c50a7baa46b.png">

Steps to reproduce : 

js code
```js

<script>
    "use strict";

    function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

    var BaseMutation = (function () {
        function BaseMutation() {
            _classCallCheck(this, BaseMutation);
        }

        BaseMutation.prototype.checkThis = function checkThis() {
            console.log(this.constructor);
            console.log(this.constructor.fragments);
        };

        return BaseMutation;
    })();
</script>
```

scala code : 

```scala
@js.native
class BaseMutation extends js.Object {
  def checkThis(): Unit = js.native
}

@ScalaJSDefined
class ScalaMutation extends BaseMutation

  new ScalaMutation().checkThis() // check console this is referring to different constructors in two output modes

```

**Comment by chandu0101** [comment]
@sjrd  relay team  fixed `fastOptJS`  issue https://github.com/facebook/relay/issues/445  , atleast we can work in `fastOptJS` mode for now until we hit by another road block(if any) ;) ,  can we target this `fullOptJS` issue for 0.6.6 ?

**Comment by mardo** [comment]
+1
