### ISSUE TITLE
Remove `noWarnMissing` option of linker

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#1903]
The option was originally introduced to allow to run partests which do not link properly. Since we support much more of the Java lib now, this should be less of an issue.

I'll investigate the impact on partests.

**Comment by gzm0** [comment]
The following tests fail after removing `noWarnMissing` (on 2.11.7)

```
run/valueclasses-manifest-existential.scala
run/existentials3-old.scala
run/value-class-extractor-seq.scala
run/t3493.scala
run/t2236-old.scala
run/interop_manifests_are_classtags.scala
run/valueclasses-manifest-generic.scala
run/private-inline.scala
run/valueclasses-manifest-basic.scala
run/t1195-old.scala
run/t3758-old.scala
run/t4110-old.scala
```

**Comment by gzm0** [comment]
We can classify these tests in the following groups.

## Use Manifests (which use `Class.getInterfaces`)
They are not supported anyway. Removing is OK.

```
run/valueclasses-manifest-existential.scala
run/existentials3-old.scala
run/t2236-old.scala
run/interop_manifests_are_classtags.scala
run/valueclasses-manifest-generic.scala
run/valueclasses-manifest-basic.scala
run/t1195-old.scala
run/t3758-old.scala
run/t4110-old.scala
```

## Use `ScalaRunTime.stringOf`
This method uses reflection very heavily, so it wouldn't work anyways on Scala.js.
A quick grep on the Scala (2.11.7) codebase shows that this method is only used in tests and in the REPL.
Therefore, dropping "support" is probably fine.

```
run/value-class-extractor-seq.scala
run/t3493.scala
```

## Use `Class.forName`
This is an optimization test for Scalac making sure that private lambdas are properly inlined.
Since we have our own handling for lambdas, this is hardly a useful test to Scala.js.

```
run/private-inline.scala
```

**Comment by gzm0** [comment]
Based on this, I will remove `noWarnMissing` unless anyone objects.

**Comment by sjrd** [comment]
Sounds good. 

Eventually, we should support `getInterfaces()`. It can be implemented similarly to `getSuperclass()`, with support from the reachability analysis.
