### ISSUE TITLE
Using @js.native on a non-js.Any should be an error

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#1905]
It seems I forgot to report an error in this case:
```scala
@js.native
class Foo
```
which is very disturbing.

**Comment by gzm0** [comment]
Picking this as test run for Google OSS processes.

**Comment by sjrd** [comment]
?

**Comment by gzm0** [comment]
Think of Google as an employer who allows their employees to do fun OSS work. But of course, there are procedures involved...

**Comment by sjrd** [comment]
Ah OK.
