### ISSUE TITLE
JsExported methods in IR get erased by optimizer.

### ISSUE THREAD

**Issue by andreaTP** [scala-js/scala-js#1907]
You can have a try of this here:
https://github.com/andreaTP/scalajs-ir-patcher
go under ```plugin``` and ```sbt publishLocal```
then go under main ```sbt``` and you can check ```scalajsp demo/unicredit/Foo.sjsir```
against the JS generated after a ```sbt usage/fastOptJs```.

**Comment by sjrd** [comment]
Add this in `usage`'s settings:
```scala
scalaJSOptimizerOptions ~= { _.withCheckScalaJSIR(true) }
```
then clean and then re-`usage/fastOptJS`. You will see the following IR check errors:
```
[error] MockFooHello.scala(8:10:This): this of type ClassType(Ldemo_unicredit_Foo) typed as ClassType(Ldemo_unicredit_MockFooHello)
[error] MockFooHello.scala(6:13:This): this of type ClassType(Ldemo_unicredit_Foo) typed as ClassType(Ldemo_unicredit_MockFooHello)
[error] MockFooHello.scala(12:2:This): this of type ClassType(Ldemo_unicredit_Foo) typed as ClassType(Ldemo_unicredit_MockFooHello)
[error] MockFooHello.scala(6:13:This): this of type ClassType(Ldemo_unicredit_Foo) typed as ClassType(Ldemo_unicredit_MockFooHello)
[error] MockFooHello.scala(12:2:This): this of type ClassType(Ldemo_unicredit_Foo) typed as ClassType(Ldemo_unicredit_MockFooHello)
[error] MockFooHello.scala(12:2:MethodDef): ClassType(Ldemo_unicredit_Foo) expected but ClassType(Ldemo_unicredit_MockFooHello) found for tree of type org.scalajs.core.ir.Trees$Block
[error] MockFooHello.scala(6:13:This): this of type ClassType(Ldemo_unicredit_Foo) typed as ClassType(Ldemo_unicredit_MockFooHello)
```
As long as you have IR check errors, the linker will go berserk. The bug comes from your IR patcher.

**Comment by andreaTP** [comment]
Thanks for the hint,
I get it working but the IR checker is not yet happy if I use the suggested setting in ```usage``` I don't know where to change the informations it get....

**Comment by andreaTP** [comment]
Ok, I think I'm close to a solution but, when using:
```scalaJSOptimizerOptions ~= {
	_.withCheckScalaJSIR(true)
}``` 
in the user library it still throws errors, maybe because it does checks against the class files?
Is there any way to avoid this?

**Comment by sjrd** [comment]
`withCheckScalaJSIR` checks the IR, not the class files. That's the whole point. It must pass. As I said before, as long as that check fails, it means you have a bug. And the linker can and will break whatever expectations you have about the output you want. 

The IR check is a precondition to the linker. If you violate it, the linker can do anything.

**Comment by andreaTP** [comment]
ok, but can I ask you some help on finding the point?
```scalajsp``` shows the right output, both infos and defs are modified accordingly into the IR, so I have no more clue on where to search for other informations.

**Comment by gzm0** [comment]
What are the errors you are seeing?

**Comment by andreaTP** [comment]
```
[info] Fast optimizing /Users/andrea/Documents/workspace/temp/ir-patcher/usage/target/scala-2.11/irpatchereraserdemousage-fastopt.js
[error] Method info mismatch for Ldemo_unicredit_Foo.hello$und$eq__T__
[error] Expected:
[error] hello$und$eq__T__:
[error]   methodsCalled:
[error]     Ldemo_unicredit_MockFooHello: [hello$und$eq__T__V]
[error]
[error] Got:
[error] hello$und$eq__T__:
[error]   methodsCalled:
[error]     Ldemo_unicredit_Foo: [hello$und$eq__T__V]
[error]
```

**Comment by andreaTP** [comment]
but I'm pretty sure I'm replacing all the needed info:
https://github.com/andreaTP/scalajs-ir-patcher/blob/master/plugin/src/main/scala/unicredit/IrPatcherPlugin.scala#L66

**Comment by sjrd** [comment]
For infos, I suggest you just reconstruct them automatically from scratch using [`Infos.generateClassInfo`](https://github.com/scala-js/scala-js/blob/v0.6.5/ir/src/main/scala/org/scalajs/core/ir/Infos.scala#L253). Then you'll be certain that the infos are correct.

**Comment by andreaTP** [comment]
ok, thanks for the support, will check it this evening!

**Comment by andreaTP** [comment]
ok, solved all my problems, instead of modifying in place the IR traversing it at the end I choose to separate compilation units of patch and real library.
Doing so I can make class names clash and this ease a lot the whole process.
Also the implementation result quite nice:
https://github.com/andreaTP/scalajs-ir-patcher/blob/master/plugin/src/main/scala/unicredit/IrPatcherPlugin.scala

Thanks for the support guys!
