### ISSUE TITLE
Partially enable -Xfatal-warnings for IR, tools, partest and library

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#1915]
On CI, the pattern matcher exhausts its analysis budget for IR and tools, which causes a warning. This does not happen on my local machine.

We should investigate why and whether there is a way we can still guard against deprecation in these projects.

**Comment by sjrd** [comment]
I have the warnings with 2.11.2 but not anymore with 2.11.5. (2.11.3 is banned, and 2.11.4 cannot compile the tools).

**Comment by sjrd** [comment]
The warnings are also present in 2.10.5.

**Comment by gzm0** [comment]
Ah, nice! So we can just enable `-XfatalWarnings` in 2.11.5 upwards. The main use-case is to protect against deprecated usage anyways. And it is enough to do that in one version.
