### ISSUE TITLE
There's something fishy in SourceMapWriter.startSegment().

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#1922]
As commented in #1920, there seems to be something awfully wrong with the name index generation in source maps in `SourceMapWriter.startSegment()`. Repeating the comment here:

About the assignment to `pendingName`: hum ... it seems this code is just plain wrong. The initial test
```scala
if (startColumn != pendingColumnInGenerated)
```
can never be true because we just did
```scala
pendingColumnInGenerated = startColumn
```
which means that once `pendingName` has been set once to non-null/`Some`, it will be forever unchanged. -_-'

We need to investigate this and fix it.

**Comment by nicolasstucki** [comment]
Profile with this fix show a small increase in performance of the `startSegment` method on top of the changes in  #1920. I will add this fix in a RP after #1920 is merged.
