### ISSUE TITLE
SBT linking error when depending on local project

### ISSUE THREAD

**Issue by Jegp** [scala-js/scala-js#1925]
In an build.sbt file:
```
val that = RootProject(file("../that"))
val project = 
  Project("this", file("."))
    .enablePlugins(ScalaJSPlugin)
    .dependsOn(that)
````
I'm experiencing linking errors when refering to code from the ``that`` dependency. If I symlink the files in the ``src`` directory it compiles without any complaints. Is this a know issue?

**Comment by sjrd** [comment]
Is `that` a Scala.js project, i.e., with `.enablePlugins(ScalaJSPlugin)`?
Linking errors would indicate that it cannot find the `.sjsir` files coming from `that`, which would definitely happen if `that` is in fact not a Scala.js project.

Other question, what does `show this/compile:fullClasspath`? Does it include the classes directory of `that`? Does this directory contain `.sjsir` files?

**Comment by Jegp** [comment]
Thanks for the quick reply!
And nope, it's not a scala-js project :-) Honestly I assumed it was an inherent mechanism of scala-js to compile and link external source code as well. Is that not how it's normally done with dependencies?

**Comment by sjrd** [comment]
No, dependencies are *compiled* separately, although they are all *linked* together. This is like Maven dependencies (because they *are* Maven dependencies). That means you can only depend on external projects targeting the same platform, i.e., Scala.js-enabled projects.
