### ISSUE TITLE
Build for 2.12.0-M3

### ISSUE THREAD

**Issue by nicolasstucki** [scala-js/scala-js#1937]

**Comment by sjrd** [comment]
2.12.0-M3 seems to have landed on Maven Central: https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.0-M3/

**Comment by holograph** [comment]
Is there a build, though? It doesn't show up on [central](https://repo1.maven.org/maven2/org/scala-js/).

**Comment by sjrd** [comment]
Now it is.
