### ISSUE TITLE
Null values cannot be undefOr ?

### ISSUE THREAD

**Issue by MikaelMayer** [scala-js/scala-js#1938]
Recently, I had a code doing this:

     val backwardChanges = getDynamic().asInstanceOf[js.UndefOr[js.Array[String]]].getOrElse(new js.Array[String]())

The problem is that when getDynamic() returns null (for some reason, it did Linux machines but it was not the case on windows machines), the comparison in the compiled code:

    null == (void 0)

### Expected result

    true

#### Actual

    false

which is undesirable since I wanted to return a new array in this case.

### Current workaround:

My current workaround is the following:

    val bg = getDynamic().asInstanceOf[js.UndefOr[js.Array[String]]].getOrElse(new js.Array[String])
    val backwardChanges = if(bg == null) new js.Array[String] else bg

Is there anything better than that? `getDynamic()` either returns an object (including null) or undefined depending on the machine.
Thank you !

**Comment by sjrd** [comment]
The behavior is as designed. `null == js.undefined` should be `false`, as these two things are not the same.

`js.UndefOr[A]` models `undefined` or `A`, so `null` belongs to the `A` part, and is therefore considered as non-empty. Your workaround is one the right ways to do it.

A better way would be to "filter out" `null` like this:
```scala
getDynamic().asInstanceOf[js.UndefOr[js.Array[String]]].filter(_ != null).getOrElse(new js.Array[String])
```

**Comment by MikaelMayer** [comment]
Thank you for the clarification. I like your solution better.
I even looked at the code and it's optimized the right way (without closures) so this is awesome.
