### ISSUE TITLE
require('a/b'): Is this possible?

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#1945]
Hi. As of React 0.14 there is a new file `react-dom.js` which is [used like this](https://www.npmjs.com/package/react-dom):

``` js
// In the browser
var ReactDOM = require('react-dom');

// In server-side Node
var ReactDOMServer = require('react-dom/server');
```

When writing scalajs-react unit tests, it is important to have both `ReactDOM` and `ReactDOMServer` available as they have different, useful methods.

With this ↓ `ReactDOM` works but I can't seem to find a way to get `ReactDOMServer` to work in Scala.JS at all, let alone alongside `ReactDOM`.

``` scala
jsDependencies += "org.webjars.npm" % "react-dom" % "0.14.0" / "react-dom.js" commonJSName "ReactDOM"
```

Is it possible? Is there a way?

_(Btw, http://www.scala-js.org/ could really benefit from a search feature. I wanted to just search for `require` there but no such luck. Manually scanning each page I didn't find anything pertinent.)_

**Comment by sjrd** [comment]
@gzm0 Out the top of your head, do you think the `/` in the `require` invocation could cause trouble?

**Comment by gzm0** [comment]
The Node.js inclusion mechanism throws all libraries in the same directory (since originally the assumption was, that they are only selected by the same file name).

In this case, the following should work:

```scala
jsDependencies += "org.webjars.npm" % "react-dom" % "0.14.0" / "react-dom/server.js" commonJSName "ReactDOMServer"
```

**Comment by japgolly** [comment]
Hey @gzm0. I tried that snippet above and it doesn't work. Looking at the webjar contents (and ignoring React's own doc) it looks like just `server.js` should work but it doesn't either. Unfortunately I don't get enough error info for me to chase this down further so I don't know.

If you have time, would you be able to try the project at this branch?
https://github.com/japgolly/scalajs-react/tree/dom-server

If you can configure `jsDependencies` such that `sbt test` doesn't crash, you win! :D

**Comment by gzm0** [comment]
@japgolly Are you feeding the generated js into any post processor from react? It is indeed *not* possible to generate the exact string `require('react-dom/server')` in the code.

I'll have a look at your project now.

**Comment by gzm0** [comment]
Look at the content of `server.js`:

```javascript
'use strict';

module.exports = require('react/lib/ReactDOMServer');
```

There lies your problem... Our dependency management cannot handle transitive includes like this (again, since this depends on the exact system and JS VM you are using).

I'll try to hack patch it :)

**Comment by gzm0** [comment]
I fail to bring up sbt on this branch:

```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: commons-io#commons-io;2.0.1: configuration not found in commons-io#commons-io;2.0.1: 'master(compile)'. Missing configuration: 'compile'. It was required from com.github.mpeltonen#sbt-idea;1.6.0 compile
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		commons-io:commons-io:2.0.1
[warn] 		  +- com.github.mpeltonen:sbt-idea:1.6.0 (sbtVersion=0.13, scalaVersion=2.10) (/tmp/scalajs-react/project/plugins.sbt#L5-6)
[warn] 		  +- default:scalajs-react-build:0.1-SNAPSHOT (sbtVersion=0.13, scalaVersion=2.10)
```

**Comment by japgolly** [comment]
> Our dependency management cannot handle transitive includes like this (again, since this depends on the exact system and JS VM you are using).

Oh that seems like a very serious restriction. Does that mean that all the other JS libs I've used up until now have never used `require` in them? I wouldn't imagine so but maybe I've been lucky :) Is there a plan to fix this properly? It would be ideal if we were able to feed dependencies to node/phantom in a way that their `require` functions just worked normally.

> I fail to bring up sbt on this branch:

That's weird, Travis runs SBT without that error. Hmm I'll just remove the sbt-idea plugin. Please try again.

**Comment by sjrd** [comment]
This should now be possible with [scalajs-bundler](https://scalacenter.github.io/scalajs-bundler/).
