### ISSUE TITLE
Missing toString() methods in tools.jsdeps.*

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#1949]
A few classes in https://github.com/scala-js/scala-js/tree/master/tools/shared/src/main/scala/org/scalajs/core/tools/jsdep miss proper `toString()` implementations. This is a pity, as they sometimes appear in error messages, and can also be displayed with `show` commands in sbt.
* [`FlatJSDependency`](https://github.com/scala-js/scala-js/blob/master/tools/shared/src/main/scala/org/scalajs/core/tools/jsdep/FlatJSDependency.scala)
* [`JSDependencyManifest`](https://github.com/scala-js/scala-js/blob/master/tools/shared/src/main/scala/org/scalajs/core/tools/jsdep/JSDependencyManifest.scala)
* [`ResolutionInfo`](https://github.com/scala-js/scala-js/blob/master/tools/shared/src/main/scala/org/scalajs/core/tools/jsdep/ResolutionInfo.scala)

**Comment by matthughes** [comment]
Here's my PR: https://github.com/scala-js/scala-js/pull/1950
