### ISSUE TITLE
Honor call-site @inline and @noinline

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#1961]
The feature was introduced in Scala/JVM in https://github.com/scala/scala/pull/4801

**Comment by gzm0** [comment]
Can we move this post-v1?

**Comment by sjrd** [comment]
We should at least figure out now how we are going to represent that information in the IR. Could they be two additional flags in the `ApplyFlags` of `Apply*` nodes? Currently the `ApplyFlags` are all semantically binding, whereas `@inline` and `@noinline` would be optimization hints.

**Comment by gzm0** [comment]
Ah, OK fair enough.

**Comment by sjrd** [comment]
Thinking more about this, I'm confident we can use the `ApplyFlags` for this purpose, so delaying to post-v1.0.0.

**Comment by gzm0** [comment]
I've started looking into this:

- Changes in the IR/optimizer seem trivial.
- It seems we have forgotten flags on the `New` tree. So we cannot do this for class inlining.
