### ISSUE TITLE
Linking to some external doc fails

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#1969]
The following seem to fail (as if the symbols did not exist):
- `scala.Null`
- `scala.Nothing`
- `scala.util.Left`
- `scala.util.Right`
- `scala.Some` (`scala.None` works, note that it's not a type like all the others)
- `java.lang.Runtime.exit`
- `java.lang.String.copyValueOf` (not needed, just for testing)

Currently they are not represented as links, but just as code fragments.

**Comment by sjrd** [comment]
Should we close this as won't fix? I don't see this being ever addressed. If Scaladoc is not able to resolve those links, there's nothing we can do about it.
