### ISSUE TITLE
Buggy range

### ISSUE THREAD

**Issue by fancellu** [scala-js/scala-js#1974]
0.0 to 2*Math.PI by 0.2

Gives error 
      Uncaught java.lang.IllegalArgumentException: More than Int.MaxValue 

No such problem with native Scala 2.11.7

    (0.0 to 2 by 0.1).map(_*Math.PI)  

works fine

Looks like the non integer end value is making it unhappy

    0.0 to Math.PI

gives same error

**Comment by fancellu** [comment]
0.0 to 2*3.1415 by 1.0  

in scala 2.11

NumericRange(0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0)

in scala.js

NumericRange(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...)

**Comment by mseddon** [comment]
See: https://issues.scala-lang.org/browse/SI-8620, in short, floating point ranges are strongly discouraged in Scala since they tend to blow up numerically.

**Comment by fancellu** [comment]
Works fine for me in Scala 2.11. Its in scala-js that it goes super mental.

**Comment by mseddon** [comment]
Hmm, yes, I'm fairly sure it should definitely terminate!

**Comment by sjrd** [comment]
@nicolasstucki Could you investigate this?

**Comment by nicolasstucki** [comment]
The problem is in the `length` of the range. I will investigate why this is returning a wrong result.

**Comment by nicolasstucki** [comment]
In every case tested so far, the source of this bug is #1979.
