### ISSUE TITLE
Inner function in @ScalaJSDefined method doesn't get parameter

### ISSUE THREAD

**Issue by phlegmaticprogrammer** [scala-js/scala-js#1975]
Using Scala.js 0.6.5, Scala 2.11.7: 

It seems that when writing a @ScalaJSDefined class, when a method has inner functions, undefined values are passed to those inner functions for the methods parameters:

    @ScalaJSDefined
    class ProofDocMode extends js.Object {
     
      def token(stream : js.Dynamic) : String = {
        // stream is fine here
        def peek() : String = {
          // stream will be undefined here
          ....
        }
        peek()
        ....
      }

    }

**Comment by sjrd** [comment]
Ouch, that's bad! Thanks for the report.
