### ISSUE TITLE
The IR printer does not print {Int|Long}Literal correctly

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#1976]

**Comment by gzm0** [comment]
Could we have a description of the problem here, please?

**Comment by gzm0** [comment]
Also see #1157

**Comment by nicolasstucki** [comment]
`IntLiteral` values are being printed using the `print(c: Char)` overload. For example `5` would print the character `5.toChar`.

`LongLiteral` is simply missing from the match cases.
