### ISSUE TITLE
-8 % 8 evaluates to negative 0, which then blows up if cast to Integer

### ISSUE THREAD

**Issue by SethTisue** [scala-js/scala-js#1984]
Was: java.util.Collections.sort tests failing in Scala community build

the failures can be seen in the 2.11.x-jdk8 build (https://scala-ci.typesafe.com/job/scala-2.11.x-jdk8-integrate-community-build/72/consoleFull) and the the 2.12.x build (https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/187/consoleFull)

I have not seen it fail in the 2.11.x build on JDK 6. That might be because the change that caused the regression is very recent and hasn't run yet in that build, or there might be a JDK 6 vs 8 issue here.

see logs for full stack traces, but the first few lines of one of the failures look like:

```text
[scala-js] [info] java.util.Collections.sort
[scala-js] [error]  x should implement sort[T<:Comparable[T]](List[T]) and behave correctly with java.util.ArrayList
[scala-js] org.scalajs.jasminetest.JasmineTestException: scala.scalajs.runtime.UndefinedBehaviorError: An undefined behavior was detected: 0 is not an instance of java.lang.Integer
[scala-js] 	at <jscode>.(file:/home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.1/project-builds/scala-js-6327675135cdd35cb027d800490dac65bc9af680/library/src/main/scala/scala/scalajs/runtime/StackTrace.scala:39)
```

**Comment by SethTisue** [comment]
#1984 #BigBrotherIsWatchingYou

**Comment by sjrd** [comment]
Do we have a range of commits of Scala/Scala.js in which the failure was introduced?

I cannot reproduce this issue with Scala.js' commit 3b6d6eef9f740010140210c39cbfca08546b12c2 (which the 2.11.x failed build mentions) on a JDK 8 and Scala 2.11.7 nor 2.12.0-M3.

**Comment by sjrd** [comment]
I suspect https://github.com/scala/scala/commit/37eacec819e38cc29357a31ee99b592f31e0702f because the failure happens at https://github.com/scala-js/scala-js/blob/3b6d6eef9f740010140210c39cbfca08546b12c2/test-suite/src/test/scala/org/scalajs/testsuite/javalib/util/CollectionsTest.scala#L1320, where there is an implicit conversion `int2Integer(value % 8)`, although I don't know why the code would blow up (I review that PR myself).

**Comment by sjrd** [comment]
OK I minimized it. It was not related, but that change brought up the bug to the surface. The minimization is:
```scala

object HelloWorld extends js.JSApp {
  var value: Int = -8

  def main() {
    println((value % 8).asInstanceOf[java.lang.Integer])
  }
}
```
Apparently `value % 8` returns a *negative* 0 there (as a result of a bad encoding of the integer % in JavaScript), which is indeed not a `java.lang.Integer` (only positive 0 is).
