### ISSUE TITLE
Tried using Lift's JSON DSL in Scala.js but can't compile

### ISSUE THREAD

**Issue by eje211** [scala-js/scala-js#1988]
I have this build.sbt:

    enablePlugins(ScalaJSPlugin)
    
    name := "Scala.js Tutorial"
    
    val liftVersion = "2.6.2"
    
    scalaVersion := "2.11.7" // or any other Scala version >= 2.10.2
    
    libraryDependencies += "org.scala-js" %%% "scalajs-dom" % "0.8.0"
    libraryDependencies += "be.doeraene" %%% "scalajs-jquery" % "0.8.0" 
    libraryDependencies += "com.lihaoyi" %%% "utest" % "0.3.0" % "test"
    libraryDependencies += "net.liftweb" %% "lift-json" % liftVersion % "compile->default" 
    libraryDependencies += "net.liftweb" %% "lift-common" % liftVersion % "compile->default" 
    
    jsDependencies += "org.webjars" % "jquery" % "2.1.3" / "jquery.js"
    
    scalaJSStage in Global := FastOptStage
    skip in packageJSDependencies := false
    
    jsDependencies += RuntimeDOM
    
    testFrameworks += new TestFramework("utest.runner.Framework")

But then, when I try to compile, I get:

    > fastOptJS
    [trace] Stack trace suppressed: run last compile:scalaJSPreLinkClasspath for the full output.
    [error] (compile:scalaJSPreLinkClasspath) org.scalajs.core.tools.classpath.JSLibResolveException: Some references to JS libraries could not be resolved:
    [error] - Ambiguous reference to a JS library: jquery.js
    [error]   Possible paths found on the classpath:
    [error]   - scala/tools/nsc/doc/html/resource/lib/jquery.js
    [error]   - META-INF/resources/webjars/jquery/2.1.3/jquery.js
    [error]   originating from: root:compile
    [error] Total time: 1 s, completed Oct 30, 2015 4:53:55 PM

I'm guessing I must exclude something somehow, but I don't know what. I tried several solutions for other frameworks that produce jQuery conflicts but so far nothing has worked.

**Comment by sjrd** [comment]
Use `scalajs-jquery` 0.8.1.

Btw, questions are best asked [on StackOverflow](http://stackoverflow.com/questions/tagged/scala.js). The issue tracker is dedicated to tracking bugs and enhancements.
