### ISSUE TITLE
Port more Octane benchmarks

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#1989]
https://developers.google.com/octane/benchmark

Especially:
- [ ] NavierStrokes
- [ ] Crypto
- [ ] Splay #1992
- [ ] zlib (an asm.js benchmark)

Bigger ones:
- [ ] GB Emulator? (fun)
- [ ] TypeScript compiler <- good to benchmark our pattern matching (and if we "win", that would be a _huge_ buzz)

**Comment by lihaoyi** [comment]
Porting the typescript compiler seems like a humungous undertaking O.o isn't that a *lot* of code?

**Comment by sjrd** [comment]
Bah, it's only 25 kLoC. ^^ A weekend hackathon with 10 compiler hackers, and we'll be done :-p

We're not *too* serious about this. But if we manage, and we are *faster* than the original compiler, that would be the buzz of the year ^^

**Comment by sjrd** [comment]
Keeping this in our issue tracker is not really useful. Closing.
