### ISSUE TITLE
Need @JSSymName(..) annotation

### ISSUE THREAD

**Issue by bblfish** [scala-js/scala-js#1997]
In order to implement iterators one needs a way to tie a a method to a symbol as explained in [my comment on issue 1141: Add js.Iterator according to ES6's iterator protocol](https://github.com/scala-js/scala-js/issues/1141#issuecomment-152741877).
Something like this perhaps:

```
@js.native
trait Iterable[+A] extends js.Object {
  @JSSymName("Symbol.iterator")
  def iterator(): Iterator[A] = js.native
}
```

or perhaps

```
@js.native
trait Iterable[+A] extends js.Object {
  @JSName(Symbol.iterator)
  def iterator(): Iterator[A] = js.native
}
```

when a `Symbol` class has been created.

Workarounds using using `JSBracketAccess` do not seem to work: I tried in this [JSIterable](https://github.com/read-write-web/rww-scala-js/blob/akka.js/src/main/scala/org/scalajs/js/collection/JSIterable.scala) class, and somehow am always getting a function back when I want a value.  The context ends up missing as discussed [on gitter](https://gitter.im/scala-js/scala-js?at=56363fc6643ae8fb655b9af4).

**Comment by sjrd** [comment]
Define `JSIterable` as:
```scala
@js.native
trait JSIterable[+A] extends js.Object {
  @JSBracketAccess
  def method[R](symbol: js.Any)(): R = js.native
}
```

**Comment by bblfish** [comment]
With the changes to [JSIterable](https://github.com/read-write-web/rww-scala-js/blob/6dfbd31a37676022034ca4de750782d93d926489/src/main/scala/org/scalajs/js/collection/JSIterable.scala)  that is called by [ServiceWorkerAuth](https://github.com/read-write-web/rww-scala-js/blob/6dfbd31a37676022034ca4de750782d93d926489/src/main/scala/rww/auth/ServiceWorkerAuth.scala) I get the following output in the console:
![screen shot 2015-11-02 at 21 34 27](https://cloud.githubusercontent.com/assets/124506/10894983/831d1fce-81a9-11e5-9f71-1c06e84141b5.png)

**Comment by bblfish** [comment]
Ah the error was elsewhere: my logger was creating the function. This diff fixed it
https://github.com/read-write-web/rww-scala-js/commit/c8ae2c226728b6d1b4fcdbf3929c888a1974fba5

**Comment by bblfish** [comment]
I did not find any documentation for `@JSBracketCall` in the online docs. How does that differ from `@JSBracketAccess`? I suppose this can be closed.

**Comment by sjrd** [comment]
There is no documentation for `@JSBracketCall` (see [issue](https://github.com/scala-js/scala-js-website/issues/165)). Briefly, for a method

```scala
@JSBracketCall
def foo(method: T)(arg1: U1, ..., argN: UN): R

obj.foo(someMethod)(arg1, ..., argN)
```
has the same semantics as the js:
```scala
obj[someMethod](arg1, ..., argN)
```
Whereas your previous formulation would translate to
```scala
(0, obj[someMethod])(arg1, ..., argN)
```
which indeed (intentionally) looses the `this` value.

**Comment by sjrd** [comment]
Let's leave this open, though. Having to use `@JSBracketCall` is a bit of a last resort hack. `method` is known statically, so we should be able to store its info somewhere. Hopefully ...

**Comment by sjrd** [comment]
Oh and, FTR, `@JSBracketCall` is the thing that powers [`js.Dynamic.applyDynamic`](https://github.com/scala-js/scala-js/blob/v0.6.5/library/src/main/scala/scala/scalajs/js/Dynamic.scala#L29-L31).
