### ISSUE TITLE
after method fails to insert element 

### ISSUE THREAD

**Issue by kindlychung** [scala-js/scala-js#2003]
Here is the code (using jquery-facade):

```
$("ul li").after((elem: dom.Element, idx: Int) => ("index: " + idx: ElementDesc))
```

If I break down the call as:

```
    val tf: js.ThisFunction1[dom.Element, Int, ElementDesc] = (e: dom.Element, i: Int) => {
      println("adding index...")
      ("index: " + i): ElementDesc
    }
    val ulli = $("ul li")
    println(ulli)
    println(tf)
    // not working
    ulli.after(tf)
    // this works
    $("ul li").after("<p>hello</p>")
```

Then I can see "adding index..." printed in the console, but the elements were not added. 

But if I use jquery directly in javascript:

```
        $("ul li").after(function(i) {return "index" + i })
```

Everything works. Is it possible that scala.js made a mistake somewhere?

**Comment by kindlychung** [comment]
Also see here: https://github.com/jducoeur/jquery-facade/issues/5#issuecomment-153873858

**Comment by jducoeur** [comment]
Really not a scala-js issue, unless you can demonstrate that the wrong JavaScript is being emitted.  (Which I think is extremely unlikely.)

**Comment by sjrd** [comment]
I agree with @jducoeur.
