### ISSUE TITLE
An easy way to compile Scala.js at runtime

### ISSUE THREAD

**Issue by marvelm** [scala-js/scala-js#2017]
I'm working on a project that generates Javascript. I would like an easy function that looks like this:
```def compile(obj: js.Object): String```.

The closest solution I could find was the scala-js-fiddle compiler code.
https://github.com/lihaoyi/scala-js-fiddle/blob/master/server/src/main/scala/fiddle/Compiler.scala

**Comment by sjrd** [comment]
At runtime on the JVM? Or at runtime on the JS platform?

For the JVM, scala-js-fiddle's code is as simple as it can get. There is no such thing as "compile that Scala.js source code to JS". At the very least, you need a classpath, i.e., a library.

The need for such a `compile` function is pretty rare, and in each instance, the specifics of how to deal with scalac, the classpath, the emitted JS, etc. are so different that you can't decide on *one* `def compile` to give to everybody. You should take the bits that you care about from scala-js-fiddle's code, and make your own `def compile` suited to your needs.

To compile at runtime *in Scala.js*, on the JS platform, you're out of luck. scalac does not work with Scala.js.

**Comment by marvelm** [comment]
I need this feature on the JVM. Thank you for the advice. I will try to pick apart scala-js-fiddle code.
