### ISSUE TITLE
Charset decoding tests failing on JVM.

### ISSUE THREAD

**Issue by nicolasstucki** [scala-js/scala-js#2041]
At first glance it seems that the JDK implementation do not respect the specs.
Tests were filtered on JVM in #2038.

**Comment by nicolasstucki** [comment]
Still need to fix tests filtered with `if (!executingInJVM) ... ` in:
- [ ] UTF8Test
- [ ] BaseUTF16Test

**Comment by sjrd** [comment]
Fixed in 888a0028fc2ba63ef506479ef72a691e3db0ad71.
