### ISSUE TITLE
BigInt.pow(31) return the negative of the expected number.

### ISSUE THREAD

**Issue by kastoestoramadus** [scala-js/scala-js#2045]
Hi I got code:

val r = (2 to 100).flatMap(a => (2 to 100).map(b => BigInt(a).pow(b))).distinct.length
assert(r == 9183, r)
r

On jvm the assertion passes, but on chrome it fails with: 9197 as result.
Is it a bug?

**Comment by sjrd** [comment]
It is most likely a bug in the implementation of big integers. Could you minify this to one or more pairs of `a` and `b` for which `BigInt(a).pow(b)` does not produce the expected result?

**Comment by kastoestoramadus** [comment]
hmm.. from jvm save output to file, from file to source as array of tuples and compare results on chrome.
ok. I'll do so.

**Comment by kastoestoramadus** [comment]
(2, 31, 2147483648, -2147483648)
(6, 31, 1326443518324400147398656, -1326443518324400147398656)
(10, 31, 10000000000000000000000000000000, -10000000000000000000000000000000)
(14, 31, 338820052976784335907174521413566464, -338820052976784335907174521413566464)
(18, 31, 819308872942260126404286866009182175232, -819308872942260126404286866009182175232)
(22, 31, 412195366437884247746798137865015318806528, -412195366437884247746798137865015318806528)
(26, 31, 73143171433403393900724146770015259539275776, -73143171433403393900724146770015259539275776)
(30, 31, 6176733962839470000000000000000000000000000000, -6176733962839470000000000000000000000000000000)
(34, 31, 299120672332806228664106719451209941853702979584, -299120672332806228664106719451209941853702979584)
(38, 31, 9403542573537726518107430106299028013391242330112, -9403542573537726518107430106299028013391242330112)
(42, 31, 209280132851277227501988209234026802122409700753408, -209280132851277227501988209234026802122409700753408)
(46, 31, 3511500884366740741319133039278240178576180323024896, -3511500884366740741319133039278240178576180323024896)
(50, 31, 46566128730773925781250000000000000000000000000000000, -46566128730773925781250000000000000000000000000000000)
(54, 31, 506065294155818620736861073598206564100925778982600704, -506065294155818620736861073598206564100925778982600704)
(58, 31, 4637327846799278236670872192076827363889989062064340992, -4637327846799278236670872192076827363889989062064340992)
(62, 31, 36655772330592763634761960703670067260691176347075084288, -36655772330592763634761960703670067260691176347075084288)
(66, 31, 254602111920194024074608072436520292411608321458245206016, -254602111920194024074608072436520292411608321458245206016)
(70, 31, 1577753820348458066150427430000000000000000000000000000000, -1577753820348458066150427430000000000000000000000000000000)
(74, 31, 8834527189046832235111793967905673549914435952573440589824, -8834527189046832235111793967905673549914435952573440589824)
(78, 31, 45178591114249246247586564082566675634351386842854034767872, -45178591114249246247586564082566675634351386842854034767872)
(82, 31, 212926357082684736739001958018156479208723534954410612359168, -212926357082684736739001958018156479208723534954410612359168)
(86, 31, 932077423069356600613638517985466381386224250613386901979136, -932077423069356600613638517985466381386224250613386901979136)
(90, 31, 3815204244769458316286498988090000000000000000000000000000000, -3815204244769458316286498988090000000000000000000000000000000)
(94, 31, 14688026979666490706013120620116013181398990926787758935506944, -14688026979666490706013120620116013181398990926787758935506944)
(98, 31, 53457463299478843772698340895799619497091241802562139431370752, -53457463299478843772698340895799619497091241802562139431370752)

**Comment by sjrd** [comment]
Thanks!
