### ISSUE TITLE
Methods from java.net.URI return wrong empty values.

### ISSUE THREAD

**Issue by nicolasstucki** [scala-js/scala-js#2048]
Methods:
- getAuthority
- getPath
- getRawAuthority

are returning different empty values in JS and JVM. In some cases they return `""` when they should return `null` and in other cases it is the other way around. 

Tests for these cases exist in #2047 with the `!executingInJVM ` filter.

**Comment by gzm0** [comment]
You mean `java.net.URI`?

**Comment by nicolasstucki** [comment]
Yes
