### ISSUE TITLE
java.lang.Math.{nextUp|upl} bug using Doble.{MinValue|MIN_VALUE}.

### ISSUE THREAD

**Issue by nicolasstucki** [scala-js/scala-js#2052]
On JVM (at least in JDK8) `nextUp(0.0)` and `nextUp(-0.0)` return `4.9E-324` (the smalest larger representable double) instead of the [documented](https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#nextUp-double-) `Double.MinValue`. The same happens with the the `0.0f` and `-0.0f`.

**Comment by sjrd** [comment]
Is this a known JDK bug?

**Comment by sjrd** [comment]
No it's not a bug, actually. `java.lang.Double.MIN_VALUE` is not the same as `scala.Double.MinValue`. The Scala equivalent is `scala.Double.MinPositiveValue`.

**Comment by nicolasstucki** [comment]
Then it is our implementation and tests that are buggy because they do use `scala.Double.MinValue`.

**Comment by sjrd** [comment]
Ah yes, if that's what they do, they're buggy.

**Comment by soc** [comment]
https://github.com/scala-js/scala-js/pull/2055
