### ISSUE TITLE
js.Object building macro

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#2054]
If you're happy with idea I can submit a PR. It's annoying to build JS object; what would you think about a macro that translated this:

```scala
case class ReactCollapse(isOpened: Boolean,
                         fixedHeight: UndefOr[Double] = undefined,
                         springConfig: UndefOr[Array[Double]] = undefined) {

  // Manually specify properties:
  def toJs: js.Object =
    ExampleMacro.makeObject('isOpened, 'fixedHeight, 'springConfig)

  // Automatically from the case class params
  def toJs: js.Object =
    ExampleMacro.makeObjectFromCaseClassArgs
}
```

into this:
```scala
case class ReactCollapse(isOpened: Boolean,
                         fixedHeight: UndefOr[Double] = undefined,
                         springConfig: UndefOr[Array[Double]] = undefined) {

  def toJs: js.Object = {
    val o = Dictionary.empty[Any]
    o("isOpened") = isOpened
    fixedHeight  foreach (o("fixedHeight")  = _)
    springConfig foreach (o("springConfig") = _)
    o.asInstanceOf[js.Object]
  }
}
```

Is that something you'd like/accept into Scala.JS?

**Comment by sjrd** [comment]
I don't think such a macro should go into the core. It doesn't need to be, so it's better if it's maintained as a separate library.

If it gathers users and the community reaches some consensus that this the best way, we can move it into the standard library later.

**Comment by japgolly** [comment]
Well `js.Dictionary` exists; I think this should exist in Scala.JS for the
same reason.
Every time one writes a JS facade, this Scala -> JS wrapping process
involves the same tedious boilerplate; something to mitigate that should be
useful to nearly all Scala.JS users.

I don't know if everyone agrees with this macro as the solution. But even
if a solution takes a completely different form, there should be *some*
solution in Scala.JS itself. It's such a pain every time we write a facade.

Re: a library, it's a good idea on paper but realistically I wouldn't
create a library to do this. Libraries have too much overhead to maintain
and release, and then you have to spam everywhere to inform the community
and still only reach a small portion. I don't think it's worth it for this.

I'd be happy to contribute *something* to address this Scala.JS interop
problem, but only to Scala.JS itself or an existing, reliable library if an
appropriate one exists.

**Comment by ramnivas** [comment]
No real opinion about where it should land, but there is definitely a need for this. 

I am doing essentially what @japgolly may be looking for in https://github.com/payalabs/scalajs-react-bridge/blob/master/src/main/scala/com/payalabs/scalajs/react/bridge/ReactBridgeComponent.scala and that required a bit of going to hoops such as https://github.com/payalabs/scalajs-react-bridge/blob/master/build.sbt#L35. I think I am still missing a few cases (such as https://github.com/payalabs/scalajs-react-bridge/issues/5). So something more robust and readily available will definitely help the interop story.

**Comment by chandu0101** [comment]
i agree with @sjrd  its good to have a separate library for this type of use cases , i rolled my own for this use case https://github.com/chandu0101/macros

>a library, it's a good idea on paper but realistically I wouldn't
create a library to do this. Libraries have too much overhead to maintain
and release,

same goes for scala.js core, its even more harder because scala.js core team is too small

>I'd be happy to contribute *something* to address this Scala.JS interop
problem, but only to Scala.JS itself or an existing, reliable library if an
appropriate one exists.

IMO a new repo(scalajs-extras/helpers/???) under scal-js org similar to scalajs-dom will be a good option!

**Comment by japgolly** [comment]
Just to refute Chandra's point quickly:

>> a library, it's a good idea on paper but realistically I wouldn't
create a library to do this. Libraries have too much overhead to maintain
and release,
>
>same goes for scala.js core, its even more harder because scala.js core team is too small

No: Scala.JS already has a release schedule and process. Adding a class and a unit-test will not affect the release process, nor be negatively impacted by a small team size, any more than the patches the library already receives and accepts.

**Comment by chandu0101** [comment]
>No: Scala.JS already has a release schedule and process. Adding a class and a unit-test will not affect the release process, nor be negatively impacted by a small team size, any more than the patches the library already receives and accepts.

hmm any change to macro/new code needs a new build of scala-js , If it breaks in new versions for unknown reasons and if u/community not available at that time its more work for core team!.also this use case is already(circe)/can be  covered in scala.js picklers!

**Comment by japgolly** [comment]
> hmm any change to macro/new code needs a new build of scala-js , If it
breaks in new versions for unknown reasons and if u/community not available
at that time its more work for core team

That's true of any code going into Scala.JS, or any other open-source
project for that matter. It's not like we're going to stop all new code
from entering Scala.JS. It's mitigated here by code review and a
requirement of sufficient unit testing.

They may be many valid reasons for this functionality *not* to land in
Scala.JS itself, but I fail to see how the reason you've provided is one.

**Comment by sjrd** [comment]
You could contribute to @jducoeur's jsext library of you don't want your own. There are similar utilities in there IIRC

**Comment by chandu0101** [comment]
>That's true of any code going into Scala.JS, or any other open-source
project for that matter. It's not like we're going to stop all new code
from entering Scala.JS. It's mitigated here by code review and a
requirement of sufficient unit testing.

my point is we can't easily add/delete in scala.js core like we do in our own libraries :) 

>They may be many valid reasons for this functionality *not* to land in
Scala.JS itself, but I fail to see how the reason you've provided is one.

well may be!,love to know other ***valid*** reasons ..

**Comment by sjrd** [comment]
From our point of view, there two reasons to resist including this in the standard library (or should I say, core library?):

First, it requires macros, by construction. We try very hard not to have macros in the core library because they make it more difficult to quickly react to new versions of Scala. And we need to stay *very* up to date to the Scala version (in fact, thanks to the community build, we basically track scala's master).

Second, and most importantly, we've reached a point where Scala.js is *stable*, in the sense that we have strict backwards compatibility requirements on the core library. Anything that gets in its really hard to get out later if it proves not to be the right thing after all. Therefore, we want to limit the core to things that can't go outside of the core (because they need compiler support or because we need them ourselves, e.g., in the javalib) and things that are standardized in es 6 (because they're externally standardized anyway). So utilities like this, that can be outside of the core, should be.

**Comment by japgolly** [comment]
> love to know other valid reasons

See the 3rd comment in this thread. My points there haven't been rebutted yet which is why I'm still not convinced (or understand why) it shouldn't be included in SJS core.

Just as I typed that @sjrd replied. Ok I get understand that logic; those points make complete sense. (Thank you.)

Chandu's suggestion of having a module like scala-js-dom seems like it might be the next best thing? I think there's benefit in having unity in this approach as opposed to various hodge-podge libraries all addressing the same thing (although to be honest, given the use-case here I haven't reflected to discover any logic that really supports it).

**Comment by jducoeur** [comment]
As @sjrd says, this sort of thing is pretty much the purpose of jsext -- utilities that are "core-ish" but don't really need to be there.  Contributions would be welcome: while the proposed macros are probably redundant with JSOptionBuilder, they're likely a better option in the long run.  (My inexperience with macros is the only reason I didn't go down something like this road in the first place.)
