### ISSUE TITLE
Optimize isInstanceOf on Scala objects

### ISSUE THREAD

**Issue by siriux** [scala-js/scala-js#2066]
Hi,

I'm being hit by the slow performance of isInstanceOf in tight loops when using scala objects. If I use @ScalaJSDefined objects it's really fast, but using normal scala objects I get a 5x performance hit.

I remember reading somewhere that @sjrd was aware of this problem and that it would be improved in the future, but I could not find any issue tracking this.

So, how is the current status? Are all the obvious optimizations already applied, or there is room for improvement?

Thanks

**Comment by sjrd** [comment]
The status is that I need time (or students' time) to completely change the way `isInstanceOf` is implemented. I know exactly what to do, but I don't have the time to do it.

**Comment by siriux** [comment]
That's good to know. At least there is room for improvement.

Thanks

**Comment by gzm0** [comment]
@sjrd @paullepoulpe Are you guys still working on this? Otherwise I might start working on this. If you would like me to do that, please give me a couple of pointers on where to put what (I'm assuming you have thought this through quite well) so I can get started faster.

**Comment by sjrd** [comment]
https://github.com/scala-js/scala-js/compare/master...SebsLittleHelpers:isInstanceOf looks like @paullepoulpe's most recent version. It at least needs a rebase and probably polish, but most of the implementation strategy, if not all, should be in there already.

**Comment by paullepoulpe** [comment]
I haven't had a lot of time to work on it these days. Will be working on it this weekend. The current implementation in SebsLittleHelpers is missing support for incremental compilation.

**Comment by gzm0** [comment]
@paullepoulpe Ok, so I'll let you work on it. Make sure to sync with @sjrd and @tOverney on making the Emitter incremental.

**Comment by gzm0** [comment]
@sjrd Isn't this still an open issue w.r.t. to tagging interfaces instead of fully naming them? IIUC this could still improve instance checks on interface tests and potentially also reduce code size.

**Comment by gzm0** [comment]
(re-opening so this doesn't get lost, if you think there is really no room for improvement anymore, feel free to close)

**Comment by sjrd** [comment]
There is indeed still room for improvement for interfaces.

I had closed this issue because the OP was referring to the performance issue that `isInstanceOf[C]` is slower for Scala classes than for JS classes. That issue is fixed, since there are no JS interfaces to compare against.

But we can leave it open too.
