### ISSUE TITLE
java.util.LinkedHashMap with access order tests fail on JVM.

### ISSUE THREAD

**Issue by nicolasstucki** [scala-js/scala-js#2077]
The tests specifically fail for `java.util.LinkedHashMap` when it has access order and no limit assigned.

**Comment by andreaTP** [comment]
can you point out a branch where I can find a repro?

**Comment by nicolasstucki** [comment]
https://github.com/nicolasstucki/scala-js/blob/port-java.util.Collection-tests/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/LinkedHashMapTest.scala#L143
