### ISSUE TITLE
java.util.concurrent.ConcurrentHashMap.containsValue(null) should throw NPE.

### ISSUE THREAD

**Issue by nicolasstucki** [scala-js/scala-js#2078]

**Comment by sjrd** [comment]
NPEs are undefined behavior in SJS. We don't really care. Any reason we should specifically test for this.

**Comment by nicolasstucki** [comment]
It implies a small rewrite of in the `testSuite` to make it fully cross compilable. The test suite has a couple of tests that assume that it would not fail and return false.

**Comment by nicolasstucki** [comment]
The same applies to `containsKey`.
