### ISSUE TITLE
java.util.Collections.{empty*|singleton*} fail immutability tests on JVM.

### ISSUE THREAD

**Issue by nicolasstucki** [scala-js/scala-js#2080]

**Comment by nicolasstucki** [comment]
This also affects issue also involves `nCopies`.

**Comment by nicolasstucki** [comment]
Some operations fail with a `ClassCastException` instead of `UnsupportedOperationException`.

**Comment by andreaTP** [comment]
when I have a little time I will help on these topics
but it will be good to me to have a link to a branch with a repro for each

**Comment by sjrd** [comment]
They come from progressively porting tests to JUnit+Shared. So you'd better wait until those ports are over and merged. Then the failing tests will be (deactivated) in master.

**Comment by nicolasstucki** [comment]
I'm additionally marking in the port commits the number of the issues that caused the insertion of an 
`if (!executingOnJVM)`.
