### ISSUE TITLE
Rogue test for String.charAt.

### ISSUE THREAD

**Issue by nicolasstucki** [scala-js/scala-js#2100]
Test in [StringTest.scala](https://github.com/scala-js/scala-js/blob/master/test-suite/js/src/test/scala/org/scalajs/testsuite/javalib/lang/StringTest.scala#L126) for `"charAt() should throw with out-of-bound indices"` are actually throwing `ClassCastException`.

**Comment by sjrd** [comment]
As designed. If there was compliant index out of bounds, it would have to throw that. But there isn't, so it can do whatever it wants.

**Comment by nicolasstucki** [comment]
Then I don't understand the existence of this test in the first place.

**Comment by sjrd** [comment]
True. It's a rogue test ^^

**Comment by nicolasstucki** [comment]
Then I assume that It should be deleted.

**Comment by sjrd** [comment]
Yes, it can be deleted.
