### ISSUE TITLE
Defer identifier name mangling until desugaring

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2108]
Currently, the IR maintains a list of keywords that are reserved in JS, and forbids them in its identifiers. This is too low-level a concern for the IR, and is not robust with future versions of JS adding new reserved keywords. We also forbid leading digits.

We should defer the mangling currently performed by `mangleJSName` in [`JSEncoding`](https://github.com/scala-js/scala-js/blob/master/compiler/src/main/scala/org/scalajs/core/compiler/JSEncoding.scala) to the desugaring.

This a backward binary incompatible change, so it will be for the next major version.

**Comment by gzm0** [comment]
Note: Make sure that things are in the right place (e.g. [`isValidJSIdentifier`, `Definitions` -> `Names`][1]) once this is done.

[1]: https://github.com/scala-js/scala-js/pull/3804#discussion_r333098501
