### ISSUE TITLE
package object XYZ is exported with JSName "package" but should be "XYZ"

### ISSUE THREAD

**Issue by aha66** [scala-js/scala-js#2117]
Use case:

Based on the `package object THREE extends js.Object` declaration in https://github.com/antonkulaga/threejs-facade/blob/master/facade/src/main/scala/org/denigma/threejs/threejs.scala, the SCALA code

> material.side = threejs.THREE.DoubleSide

translates to

> material["side"] = $g["package"]["DoubleSide"];

but should

> material["side"] = $g["THREE"]["DoubleSide"];

**Comment by sjrd** [comment]
Hi, 

This is more or less as-designed. Package objects were never designed to be used in facades for objects. They used to be designed for members in the global scope, but even that is being passed out #1892.

So, basically, don't use package objects in facade types,  they're not supported.

I recognized this can be considered as a bug, given the current situation, but I'll close this as won't fix.

**Comment by OndrejSpanel** [comment]
Is there any benefit or reason for generating `$g["package"]` code?

**Comment by sjrd** [comment]
No, but there is also no benefit in fixing a situation that has been deprecated for more than a year. package objects extending `js.Any` have been deprecated in https://github.com/scala-js/scala-js/pull/2165

**Comment by OndrejSpanel** [comment]
Should some deprecation warning be issued when compiling against a library / facade which uses this? I have deprecation warnings enabled in my project, but I did not get any warning on this.

**Comment by sjrd** [comment]
Yes, a deprecation should be issued. Your IDE might not show it, though. A compilation from sbt would definitely show it.

**Comment by OndrejSpanel** [comment]
I did not try to compile the library, but as a user of the library I am definitely not given any deprecation warning even when compiling from SBT.

**Comment by sjrd** [comment]
No, as a user of the library, you do not get any warning, same as you do not get a warning when using a (non-deprecated) library function that itself uses a deprecated function. Deprecation is not transitive.

The library is buggy if it is published that way, and should be fixed. There's nothing we can do about it.

**Comment by OndrejSpanel** [comment]
In case this is of any interest to anyone, I have create a small example demonstrating the issue in https://github.com/OndrejSpanel/ThreeJSTest

I think in this case some warning could be issued when the code `$g["package:"]` is generated, as such code is never any good, but I understand you may decide this is not worth the effort, as there are probably not many libraries out there with this issue.
