### ISSUE TITLE
Implement a generic way to pass an environment to testSuite.

### ISSUE THREAD

**Issue by nicolasstucki** [scala-js/scala-js#2119]
Currently it is possible to give `Jasmine` flags like `"typedarray"` or `"strict-floats"` but not to JUnit. The idea would be to have a single mechanism that would inject those flags into the js file and have some facade to access them.

**Comment by sjrd** [comment]
Idea: through [system properties](https://docs.oracle.com/javase/7/docs/api/java/lang/System.html#getProperties%28%29)?

**Comment by gzm0** [comment]
Please not. This is done a lot in practice and ends up terribly unreadable. `SystemProperties` is like global variables, except that they are not typed.
Very soon, test code that says:

```scala
sys.props("foo") = "bar" // override foo for whatever reason
```

starts popping up. It goes pretty much downhill from there.

IMO a slightly better approach to doing this via arguments (what we do in the `JasmineTestFramework`). Of course that means each individual test framework needs to understand that, but IMO there is hardly a way around this. (How exactly we abort / skip a test given a tag is test framework specific anyways).

**Comment by sjrd** [comment]
The problem is that JUnit does not support any kind of user-defined argument that tests can then inspect. Docs recommend to use system properties for that purpose (written with `-D` arguments, read-only from the tests).

**Comment by gzm0** [comment]
Ok. But in that case it is not a generic way, but a JUnit specific way. I'm fine with that.

**Comment by nicolasstucki** [comment]
I agree with @gzm0, this should be a special case for JUnit.
