### ISSUE TITLE
Rewrite toolsJS/test to not use eval anymore

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#2135]
Currently, we roughly do:

```javascript
var code = linker.link(...);
eval(code + "<invoke tests>");
```

This is probably much less efficient in terms of the VM than:
 
```javascript
var code = linker.link(...);
writeToFile("myLib.js", code);
require("myLib.js");
```

**Comment by sjrd** [comment]
Is there any source backing this claim? I don't see why `require` would be any faster than `eval`. We might want to use an indirect `(0, eval)` which might be faster in scrict mode, though.

**Comment by gzm0** [comment]
No, there is not. I hope to get data once I do this. I currently run into memory issues when emitting the trees (after the tools refactoring).
I'll play with it and we'll see :)

**Comment by gzm0** [comment]
Closing this. Doesn't seem to actually be useful.
