### ISSUE TITLE
Parsing very large Long does not fail properly

### ISSUE THREAD

**Issue by ochrons** [scala-js/scala-js#2158]
```scala
val l = java.lang.Long.parseLong("45248643522829592471")
```
This fails on JVM with `NumberFormatException` but succeeds on Scala.js with an invalid result. Happens with many numbers that are exactly 20 digits.

See https://github.com/ochrons/boopickle/issues/48

**Comment by sjrd** [comment]
This is already fixed in master. In was fixed as part of https://github.com/scala-js/scala-js/pull/1985, I believe.
