### ISSUE TITLE
Unify error handling in Analyzer

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#2162]
There are three ways the analyzer currently handles errors (i.e. bad state on the classpath, not bad internal state):

- Populate `errors`
- `sys.error("Fatal error: could not find java.lang.Object on the classpath")`
- Throw `CyclicDependencyException`

This is a strange interface and we should unify it taking advantage of the binary compat break.

**Comment by gzm0** [comment]
Proposal: Only populate `errors`.

Replace fatal error by a new type of error `MissingJavaLangObject` set `_allAvailable` to false and return immediately. That means no class will be `neededAtAll` and `allAvailable` will be false.

I don't really know how to handle the cyclic dependency without potentially introducing very nasty non-determinism... Maybe we should actually throw the error internally, catch, clean state and return with that single error (which we populate from the exception data).

@sjrd WDYT?

**Comment by sjrd** [comment]
The problem is that the linker cannot recover from a missing `java.lang.Object`. It can recover from pretty much everything when `bypassLinkingErrors` is true, but that is a show stopper.

**Comment by gzm0** [comment]
> The problem is that the linker cannot recover from a missing java.lang.Object. It can recover from pretty much everything when bypassLinkingErrors is true, but that is a show stopper.

Wouldn't it just not create any class at all? Since nothing was reached, nothing `isNeededAtAll`, therefore [nothing is included](https://github.com/scala-js/scala-js/blob/master/tools/shared/src/main/scala/org/scalajs/core/tools/optimizer/Linker.scala#L147).

The cyclic dependency would be a bit trickier indeed...

**Comment by sjrd** [comment]
Nothing is reached ... except the `scalajsenv.js`. And that guy references stuff that is supposed to be there. At least in strong mode it would blow at load time. Non strong mode outputs might be able to pull through (for now).

We could report those things in `errors`, but then throw an exception if any "fatal" error happened, even when `bypassLinkingError` is true. Missing `Object` and cyclic dependencies would be fatal. Anyway, I think we should deprecate `bypassLinkingError`. Our ecosystem is large enough that people don't need codebases that do not link in the first place anymore. Eventually, all linking errors should end up in the linker throwing, unable to continue.

**Comment by gzm0** [comment]
> Anyway, I think we should deprecate bypassLinkingError.

Ok. So you are saying we should wait and refactor later? Or would you want to deprecated `bypassLinkingErrors` in 0.6.6?

**Comment by sjrd** [comment]
I'm saying we should deprecate `bypassLinkingErrors` now; and do the refactoring now, but throw anyway after having displayed the `errors` if any of them is a fatal error.

**Comment by gzm0** [comment]
Ok. Makes sense. And then we can get rid of the ugly "is it a fatal error check" once we get rid of `bypassLinkingErrors`.

**Comment by sjrd** [comment]
Yep.
