### ISSUE TITLE
Feature request: Selenium support

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#2168]
As I've rambled, ranted and cried about previously, certain things are impossible to simulate/test with {Node,Phantom}.JS. It would be really awesome if Scala.JS came with similar support for Selenium so I could run tests in a real browser.

**Comment by ramnivas** [comment]
Does http://www.scalatest.org/user_guide/using_selenium match what you are looking for?

**Comment by sjrd** [comment]
From what I know about Selenium, it is more an integration testing facility, which is designed to work on the final server serving html as well as js. For that purpose, Scala.js has nothing special, as it's just the means to create the js served by that server. I don't see what else you would like Scala.js to support wrt Selenium.

**Comment by japgolly** [comment]
@sjrd Selenium is often used for integration testing but that's not its exclusive utility; that is more browser automation. What would be really useful would be if Scala.JS had a runner for Selenium that would work in a similar way that the Node/Phantom.JS runners do, specifically:

* open a browser via Selenium
* make it open a generated html which loads and executes the generated test JS
* get the results back and display them in SBT
* close browser via Selenium (unless failure and/or options ask to keep it open)

An example of why this would be useful over Node/Phantom is you can't write unit tests that affect/use DOM focus as neither support it, where as real browsers obviously do, to which Selenium would serve as an interface.

@ramnivas Thanks for the link. I've done that before but that only allows you to control the browser from pure Scala - that doesn't help you get your `test:fastOptJS` output loaded and executed.

**Comment by nicolasstucki** [comment]
This feature will be supported by the project `scala-js/scala-js-env-selenium` https://github.com/scala-js/scala-js-env-selenium.

**Comment by nicolasstucki** [comment]
This feature is now available on at https://github.com/scala-js/scala-js-env-selenium.

**Comment by japgolly** [comment]
Fantastic! It won't be for another two weeks but I'm really looking forward to trying this. I had a bunch of tests that I had to disable entirely last year because Node/Phantom didn't handle them. Switching them back on and running them in a real browser is going to be valuable indeed. Thank you!
