### ISSUE TITLE
Feature Request: Better typing of Long in facades

### ISSUE THREAD

**Issue by mseddon** [scala-js/scala-js#2170]
Quite often in an IDL definition we might find something typed as `long`, but of course, we cannot actually use this, since `Long` in Scala.js is a complex opaque type consisting of a high and low 32-bit integer.  Instead we are forced to declare this type as `Double` which not only moves us from integers into rationals, but also introduces +Infinity, -Infinity and NaN.

It would be nice to have a trick for this that lets us declare something as e.g. a `js.Long`, but which underneath can be efficiently cast (via `.asInstanceOf`) between `js.Long` and `Double`, while assuring (statically) that the type is still a 53-bit integer as permitted by a double (which as I understand it, is as close to a 64-bit `long` as JS allows).  Of course, this might have an unacceptable performance impact, so I'm really just thinking aloud here.  Could such a type exist, with some implicit conversions for example from `Int` onto `js.Long` and `Long` onto `js.Long` (where the latter reduces to 53 bits)?

**Comment by sjrd** [comment]
You can do this in user-space.
```scala
@js.native
sealed trait JSLong extends js.Any

object JSLong {
  implicit def fromInt(x: Int): JSLong = x.asInstanceOf[JSLong]

  implicit def fromLong(x: Long): JSLong = {
    if (x >= 0) (x & ((1L << 53) - 1)).toDouble
    else -((-x) & ((1L << 53) - 1)).toDouble
  }

  implicit def toLong(x: JSLong): Long =
    x.asInstanceOf[Double].toLong
}
```
You won't have a guarantee that something typed as a `JSLong` actually fits in 53 bits of precision, though (not even that it's a `number` at all), since one could cast anything to `JSLong` without check.

You also probably do *not* want the implicit conversion from `Long` to `JSLong`. Most likely, you want an explicit `.toJSLong` for that, since it's a narrowing conversion:
```scala
implicit class LongJSOps(val x: Long) extends AnyVal {
  def toJSLong: JSLong = {
    if (x >= 0) (x & ((1L << 53) - 1)).toDouble
    else -((-x) & ((1L << 53) - 1)).toDouble
  }
}
```

**Comment by gzm0** [comment]
@mseddon does this need follow-up, or can we close this? Are you happy with the user-space solution?

**Comment by mseddon** [comment]
Oh, I completely missed this one, sorry.  Yes- this solution seems good.  I may propose to use this in `scala-js-dom` in the future, but for now, that's good enough for my purposes.
