### ISSUE TITLE
Integrating with JS module systems

### ISSUE THREAD

**Issue by ochrons** [scala-js/scala-js#2175]
# Goal

Seamlessly integrate Scala.js applications with existing JavaScript module systems.
# Background
### JS module systems

Until quite recently the use of _modules_ in JavaScript was not the common. Instead, all libraries polluted the global namespace with their entrypoints. Nowadays there are several competing module systems including AMD, CommonJS and ES6's own module syntax. Traditionally AMD has been a favorite amongs frontend devs due to its dynamic nature, whereas Node.js users went with CommonJS (as it's natively supported by Node).

Latest in the game is the ES6 module syntax, but as it's the only language level module system, it's bound to become the standard in the future.
### Bundling

JS modules tend to be small and numerous, so it makes sense to bundle them together to create one downloadable JS file (just like what Scala.js does) instead of browser downloading potentially dozens of individual files. The bundling process also allows removal of unused exports, reducing the final code size.

Most common tools for bundling these days are [browserify](http://browserify.org/) and [webpack](https://webpack.github.io/), plus a few others like [JSPM](http://jspm.io/) and [RollUp](http://rollupjs.org/).

Due to bundling, the build process of a modern JS web app is quite close to what happens in Scala.js, including dependency/version management, compilation (TS/ES6 to ES5) and linking (bundling).
### Current Scala.js situation

Scala.js is totally oblivious to JS modules and related bundling activities. It operates in its own sandbox, producing a single JS file that assumes dependencies will be available at runtime through the global namespace. The build process supports simplistic bundling (concatenation) of JS libs, to create a single JS dependencies file to be included as part of the application.

Luckily most frontend JS libs today are available in the "ready-to-use" format that you can directly include in the website (or in Scala.js jsdeps), but recently more and more libs have been published only in the module format (for example [Material UI](https://github.com/callemall/material-ui)). On Node.js CommonJS is ubiquitous, so most libs publish only in the module format. To use these libraries in a Scala.js project, developers need to package them separately using the JS toolchain.
# Solutions
## Simple ad-hoc

A quick-and-dirty way of using JS modules in a Scala.js project is to pre-bundle them using the regular JS tools like `webpack`. All you need to do is to define a short JavaScript file serving as an entry point for bundling (and have the dependencies available in the npm style). For example to use React, you would define following:

``` js
window.React = require('react');
```

Running `webpack` produces a `bundle.js` which can be included as part of `jsDependencies` and it will expose React in the global `window` object so it can be used in the Scala.js application.

**Pros**
- Backwards compatible
- No changes required to Scala.js tool chain
- Simple to implement
- Easy to support different module formats (by choosing proper JS tools)

**Cons**
- Requires use of JS tools such as `npm` and `webpack`
- Doesn't really integrate
- No optimization possible (everything is bundled, regardless of real usage)
- Scala.js exports are not available to JS components
## ES6 module output

Next option is to have the Scala.js tool chain output a compatible ES6 module, which can then be included in the normal ES6 processing chain. Of course we could also do this with CommonJS syntax (which is what the vast majority of JS modules are currently using), but at this point it probably makes more sense to go all-in with ES6 modules.
#### Changes required

For this to work, Scala.js would need to produce a JS file with valid ES6 style `import`/`export` statements. 

As there is currently no _import_ mechanism for JS except the dynamic runtime binding using global namespace, new syntax needs to be introduced. For example to import `React` one would write something like:

``` scala
@JSImport("react")
@js.native
object React extends React

@js.native
trait React extends Object { ... }
```

which would generate JS code like

``` javascript
import __JSImport_React from "react";
```

where `__JSImport_React` is an internal generated name for this import, to be used in the code instead of the usual `$g["React"]`.

Similarly anything that is exported with `@JSExport` would be exposed using the ES6 `export` syntax.

The launcher source would also need to change to use `import` instead of accessing the code directly from the global namespace. This launcher would then be the entrypoint for the JS bundler.

**Pros**
- True support of ES6 modules
- Optimization is feasible due to explicit `import` definitions
- Scala.js exports are available to JS modules in the bundling process
- Backwards compatible (if optional)

**Cons**
- Still requires use of JS tools
  - Most current bundling tools support CommonJS, but not ES6 modules
- Bundling must be performed to actually use the JS generated by Scala.js
- JS tools have _very low_ performance when dealing with large JS files produced by Scala.js (for example running webpack on a 4MB `client-fastopt.js` file takes 10-15 seconds, even though there is nothing for it to do. Browserify is even slower.
- CommonJS modules must be converted to ES6 before bundling (or ES6 modules to CJS)
## Full ES6 module bundler

To fully take advantage of ES6 modules we would need to do the bundling part ourselves. In this solution the Scala.js output would be a true ES6 module (as in the previous solution) but instead of using JS tool chain to bundle the final application, we would have our own tool.
#### Changes required

Module dependencies would need their own definition in the build file (in addition to `jsDependencies`) because module archives need to be fully extracted before bundling. For example:

``` scala
jsModules += "org.webjars.npm" % "react" % "0.14.6"
```

WebJar extraction would need custom implementation, to produce a suitable directory structure for bundling. For example the `react` NPM webjar has a directory structure like `META-INF/resources/webjars/react/0.14.6/` whereas what we really need is just `react`. The dependencies of NPM webjars have to be handled as well, to produce a flat structure. One issue is that NPM WebJar generation is not automatic for dependencies (https://github.com/webjars/webjars/issues/1186), so if dependencies are missing, the developer must manually go and add them on the webjar org website.

Actual bundling logic must be implemented. This involves parsing JS files to produce ASTs, then transforming ASTs, replacing any `import`s with appropriate calls and storing modules in their own scopes. Also any CommonJS modules must first be converted into ES6 format.

**Pros**
- True support of ES6 modules
- Optimization is feasible due to explicit `import` definitions
  - Native JS code can also be optimized via DCE
- Scala.js exports are available to JS modules in the bundling process
- No need for JS tools
  - Should have much better performance
- Allows incremental builds
- Backwards compatible (if optional)

**Cons**
- Bundling must be performed to actually use the JS generated by Scala.js
- CommonJS modules must be converted to ES6 before bundling
- Use of GCC is challenging
- Lot of work to implement everything :)

**Comment by sjrd** [comment]
I think that what we want for scala-js/scala-js is your intermediary proposal: produce ES6 modules from Scala.js code. Then let other tools do what they do best: bundling ES6 modules.

Even if we do want a JVM-based solution for ES6 bundling, it can and should be done outside of Scala.js core. Besides, this should probably be part of the sbt-web sub-system.

**Comment by ochrons** [comment]
Yea, that sounds the most reasonble path to take. Allows devs to utilize ES6 modules if they need, but doesn't put too much load to the Scala.js team.

For practical reasons, a JVM based solution (or some clever tricks) is needed...

To give an idea how slow the JS tool chain is, I ran webpack, browserify and babel on the 3.8MB client-fastopt.js produced from the SPA tutorial by Scala.js
```
webpack = 10s
browserify = 11s
babel = 28s
rollup = 2.5s
```
And note that these tools didn't really do anything with the source code since it was ES5 code with no module dependencies. Rollup benefits from being ES6 only, so it doesn't need to find `require` calls throughout the source code etc.

**Comment by ochrons** [comment]
This also relates to #1787, #1703, #1945 and #1751.

**Comment by ochrons** [comment]
Looks like GCC might provide a great platform for the module bundling: https://github.com/google/closure-compiler/wiki/Working-With-Multiple-Module-Systems

**Comment by asazernik** [comment]
I'd like to add that, even if ES6 modules are not supported natively by bundlers or runtimes, they are supported by the very popular Babel transpiler, which translates them into either AMD or CommonJS syntax.

Going by comparison of NPM stats for the browserify bundler and its babelify plugin, Babel is used by around 10% of the browserify userbase, so approach 2 has a large userbase even among users of relatively old bundlers, as well as a usable solution for combination with legacy module systems.

**Comment by gzm0** [comment]
What is the proposals take on file structure of the modules? One problem we currently have is that libraries assume a certain structure in their transitive includes (see #1945). So even if we have something to represent ES6's `import lib from 'lib'`, we do not have story on what happens if `b` says `import foo from 'my/shady/submodule/I/assume/is/just/there'`. IIUC, ES6 does not mandate a module structure like that, neither do webjars.
Individual package managers / repositories of course do so, but then we have to either restrict ourselves to one package manager or risk directory collisions.

**Comment by sjrd** [comment]
@gzm0 At the language level, we can simply spec that whatever comes in your `@JSImport` is what is used as the ES6 module `import` statement. Then, at the language and IR level, directory structures don't matter. It's up to the packager to deal with it. We could optionally provide linking options to "rename" imported files, if necessary.

The `@JSImport` annotation should have 2 parameters: the file, and the export name. So
```scala
@JSImport("react.js", "React")
@js.native
class MyReact
```
means
```js
import {React as $c_MyReact} from "react.js"
```
The second argument could default to either a) `default` (for the ES6 default's import) or to the name of the annotated entity. I would be in favor of the first option.

**Comment by gzm0** [comment]
Yes of course. I completely agree on this part. All I am saying is that this does by far not solve all the problems we currently have. Only half of them.

Btw. could we make the `@js.native` implicit with the `@JSImport`? It seems to be redundant.

**Comment by sjrd** [comment]
It can probably be implicit, yes.

**Comment by mdedetrich** [comment]
I would agree with @sjrd about option number 2. My own personal POV (after having to deal with frontend processing of require.js/webpack/browserify/babel) is that the entire ecosystem for frontend modules and processing is a mess. A new "webpack" gets released roughly once every 2 years, and I think if we try to implement one of the more sophisticated solutions, it would put too much effort onto Scala.js devs and it would be setting a precedent which I don't think is useful for Scala.js.

I like the idea of supporting ES6 modules because ES6 is just a new version of Javascript, so we are essentially just making the code backend support a newer version of Javascript.

**Comment by gzm0** [comment]
Can we consider this as done? I think with module support on the core side and with scalajs-bundler, this has been sufficiently addressed.

**Comment by sjrd** [comment]
Let's keep it open until we actually have ES2015 module support. However, that doesn't have to be in 1.0.0.

I keep it in the 1.0.0 milestone as a reminder that I must not leave in 1.0.0 anything that would prevent us from implementing ES2015 module support in the future. For example, the `exportsNamespace` thing.

**Comment by sjrd** [comment]
Node.js 8.5.0 now has native support for ES modules, under a flag: http://2ality.com/2017/09/native-esm-node.html

An implementation on our side will be able to leverage that for tests.

**Comment by sjrd** [comment]
It seems we have now evicted from the language all the things that would prevent us from providing full ES module support, so now we can forget about this until after 1.0.0 is out.
