### ISSUE TITLE
Add first-class support for running with Node

### ISSUE THREAD

**Issue by dwijnand** [scala-js/scala-js#2199]
Currently (from http://stackoverflow.com/q/34763039/463761) the way to run an application with Node requires this added to the build:

``` scala
scalaJSOutputWrapper := ("", "example.ScalaJSExample().main();")
```

However this causes `run` to run the script twice.

@sjrd Recommends this workaround:

``` scala
inConfig(Compile)(Seq(
  packageScalaJSLauncher := {
    val file = (artifactPath in packageScalaJSLauncher).value
    sbt.IO.write(file, "", Charset.forName("UTF-8"))
    Attributed.blank(file)
  }
))
```

It would be nice to have first class support here for both output files (`fastOptJS`/`fullOptJS`) and `run` (and similar..).

**Comment by gzm0** [comment]
Hmmm... I'm thinking of how we can make this a bit more general. Best would probably be to have some form of `OutputMode` (not like we use that name already :-/):

```scala
case object CommonJSModule extends OutputMode
case object StandaloneRunnable extends OutputMode
case class Custom(pre: String, post: String) extends OutputMode
```

What is unclear, is how this interacts with the rest of sbt. A couple of things sbt would need to understand:
- `StandaloneRunnable` means that there is no need for a runner
- `CommonJSModule` means the runner and how the file is fed to the JSEnvs needs to be different
- `StandaloneRunnable` means no tests can be executed (if it is set in the `Test` configuration)

This is of course all doable, but it is very ad-hoc. It is also unclear how this would interact with the emitter's output mode (imagine it supports ES6 modules at some point in time).

Maybe it is better if we teach the emitter to do all this directly...

**Comment by dwijnand** [comment]
Perhaps the workflow could emulate what is required for runnable jars (sbt-assembly), ie. `fastOptJS`/`fullOptJS` remains the same, but there's a (tentatively named) `{fast,full}AssemblyJS` that just makes the previous output runnable.

**Comment by sjrd** [comment]
@dwijnand That is actually very easy to implement, including in user-land (i.e., in your own `build.sbt`):
```scala
val fastAssemblyJS = settingKey[File]

settings(inConfig(Compile)(Seq(
  fastAssemblyJS := {
    val fastOptJSFile = fastOptJS.value
    val runnerLine = "my.main.Object().main();\n"
    val targetFile = crossTarget.value / "my-assembly.js"
    IO.copyFile(fastOptJSFile, targetFile)
    IO.append(targetFile, runnerLine)
    targetFile
  }
))
```
The main problem is that it does a lot of unnecessary I/O (writing `-fastopt.js`, reading `-fastopt.js`, before finally writing `-assembly.js`).

**Comment by dwijnand** [comment]
WFM for now, thanks.
