### ISSUE TITLE
Concurrent use of `scalaJSLinker` in sbt plugin

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#2202]
The Scala.js sbt plugin does not ensure that a project's linker instance is not used concurrently. A typical scenario where this arises is the following (discovered thanks to @reid-spencer):

```scala
val client = project.enablePlugins(ScalaJSPlugin, ScalaJSPlay)
val server = project.enablePlugins(PlayScalaJS).settings(scalaJSProjects += client)
val root = project.aggregate(client, server)
```
Then invoke:
```sh
sbt test
```

sbt now concurrently invokes the `client/test:loadedJSEnv` and the `client/test:fastOptJS` task. The former in order to detect the necessary tests for the `client` project, the latter to satisfy `server`'s dependency<sup id="a1">[1](#f1)</sup>.

These tasks in turn invoke `linkUnit`, `link` respectively on `client/test:scalaJSLinker` concurrently. This is not an allowed use of the linker. "Fortunately" an assert in `GenIncOptimizer` caught this:

```
java.lang.AssertionError: assertion failed
        at scala.Predef$.assert(Predef.scala:165)
        at org.scalajs.core.tools.linker.frontend.optimizer.GenIncOptimizer.withLogger(GenIncOptimizer.scala:97)
        at org.scalajs.core.tools.linker.frontend.optimizer.GenIncOptimizer.update(GenIncOptimizer.scala:107)
        at org.scalajs.core.tools.linker.frontend.LinkerFrontend$$anonfun$5.apply(LinkerFrontend.scala:71)
        at org.scalajs.core.tools.linker.frontend.LinkerFrontend$$anonfun$5.apply(LinkerFrontend.scala:71)
        at org.scalajs.core.tools.logging.Logger$class.time(Logger.scala:28)
        at org.scalajs.sbtplugin.Implicits$SbtLoggerWrapper.time(Implicits.scala:9)
```

# Workarounds

- Disable Rhino entirely (`scalaJSUseRhino in Global` := false). This will cause `loadedJSEnv` to depend on the `fastOptJS` task as well and sbt will properly linearize it.
- Disable sbt's parallel execution (`parallelExecution := false`). Exact required configuration and whether this works at all is untested.

# Possible fixes
## Teach sbt to not run the tasks concurrently
This is probably the optimal solution if feasible. It might be doable by using tags. However, [sbt's docs](http://www.scala-sbt.org/0.13/docs/Parallel-Execution.html) present tags more like a "global" thing, so it is unclear whether having a tag per configuration is feasible / reasonable and whether the sbt's scheduler can cope with so many tags.

## Synchronize usage of the linker
Dirty ad-hoc solution that completely ignores sbt's scheduler. Probably "good enough", but might expose speed degradations due to non-optimal scheduling (tasks blocking on other tasks while occupying execution slots).

---
<sup id="f1">1</sup>sbt-play-scalajs makes `server/test:resourceGenerators` depend on `client/test:fastOptJS`. [⬆](#a1)

**Comment by reid-spencer** [comment]
I'm happy to confirm that the first workaround .. works :+1:

**Comment by reid-spencer** [comment]
Would you like me to validate the fix on my project? If so: what do I need to change? Just pull out the ```scalaJsUseRhino := false``` lines?

**Comment by sjrd** [comment]
If you can spare the time, that would be nice!

> what do I need to change? Just pull out the `scalaJsUseRhino := false` lines?

That, plus of course using 0.6.7-SNAPSHOT, which you need to locally published as described [here](https://github.com/scala-js/scala-js/blob/master/DEVELOPING.md#publish-locally).

**Comment by reid-spencer** [comment]
Right .. will try to get this done while waiting for things today.
