### ISSUE TITLE
ECMAScript 3 Output

### ISSUE THREAD

**Issue by schmitch** [scala-js/scala-js#2205]
Hello, currently ScalaJS only outputs to ECMAScript 5+ is there any chance to get ECMAScript 3 output aswell?

We develop for some embedded devices which are using their internal browsers (ie. printers) however their browsers will only support ecmascript 3. It would be great to write code for these in javascript, too.

**Comment by sjrd** [comment]
Unless you `@JSExport` `val`s, `var`s, or getters/setters, or use getters/setters in `@ScalaJSDefined` classes, the output should mostly be valid ES3.

What exact issues are you running into?

Officially supporting ES3 is definitely not a priority, and not a goal we want to achieve. But we can think of a way to "make it work", for some definition of "work", if you're careful what subset of Scala.js you use.

**Comment by gzm0** [comment]
How hard would it be to make the emitter complain when it can't generate ES3 compliant code?
That might be a compromise, to do something like that on a best effort basis (I.e. but thoroughly tested).

**Comment by ochrons** [comment]
GCC can transpile to ES3, so it should be trivial to do it.

**Comment by mseddon** [comment]
Also probably worth looking at #2051

**Comment by schmitch** [comment]
Currently the worst part is that the embedded browser will do *nothing* if somewhere in the code is a `console.log` statement (i think he will do nothing if any javascript isn't es3, too and with nothing i mean he will print a blank page). Not sure if that is against the ECMAScript 3 compliance.

Looks like that is non standart: https://developer.mozilla.org/en-US/docs/Web/API/Console

@sjrd currently we didn't tried that yet, since we used javascript before. However saying that it couldn't generate ES3 code would be *enough* for us and would help us more than using plain javascript since we currently don't validate for correct es3 code.

**Comment by sjrd** [comment]
Scala.js does not assume the presence of a `console`. `println` calls are silently, well, silent, if there is no `console`.

> GCC can transpile to ES3, so it should be trivial to do it.

One cannot compile ES5 getters and setters down to ES3. Simply not possible.

> How hard would it be to make the emitter complain when it can't generate ES3 compliant code?
> That might be a compromise, to do something like that on a best effort basis (I.e. but thoroughly tested).

It's probably easy to make it complain for `PropertyDef`s, assuming we can tell the emitter that we want them, in the first place. As for API calls that were not present in ES3, that's undecidable, of course.

**Comment by schmitch** [comment]
hm, I will take a try on and, I will post some updates here, later.

**Comment by schmitch** [comment]
@sjrd I tried to have a simple output on the browser:

```
import org.scalajs.dom

import scala.scalajs.js
import scala.scalajs.js.annotation.JSExport


object Main extends js.JSApp {

  @JSExport
  def main(): Unit = {
    dom.window.alert("Hello World")
  }
}
```

And then I only included client-opt.js or client-fastopt.js however I can't get any alert window to pop up.

**Comment by sjrd** [comment]
You also need to include the `-launcher.js` file, or something that calls `pack.of.Main().main();`

**Comment by schmitch** [comment]
I had, I also tried onload= or something like:
```
        <script type="application/javascript">
                var main = Main();
                main.main();
        </script>
```
I have a emulator for that browser (only works in windows ;/) but I'm not sure if I could share that.

**Comment by sjrd** [comment]
Try at least adding a polyfill for `Object.freeze` *before* the `-fastopt.js` code:
```js
Object.freeze = Object.freeze || (function(obj) { return obj; });
```

**Comment by schmitch** [comment]
Wow thanks, that worked.

**Comment by gzm0** [comment]
@schmitch does this still need follow-up, or can we close this?

**Comment by schmitch** [comment]
I close it. ;) Still thanks.
