### ISSUE TITLE
Format of negative Byte gives different results in ScalaJs and Scala

### ISSUE THREAD

**Issue by naksu** [scala-js/scala-js#2206]
Formatting of negative Byte gives different results in JVM and JS:
```scala
println(s"%02x".format(133.toByte))
```
JVM `85` vs JS `ffffff85`

Also applies to Short. 

Introduced by 000fb141b309e7567f2458e32f003281122948a5. The commit also changed the unit tests to use incorrect values, so maybe there's a good reason behind this behavior. If it cannot be fixed, would be at least good to document, for example, in http://www.scala-js.org/doc/semantics.html.

**Comment by sjrd** [comment]
Yes, it is as-designed. It is a consequence of "Runtime type tests are based on values" in the Semantics, though a non-obvious one. We should indeed document it.

**Comment by sjrd** [comment]
Moved to an issue on the website to document the discrepancy. Closing here.
