### ISSUE TITLE
Stack trace for UndefinedBehaviorError

### ISSUE THREAD

**Issue by naksu** [scala-js/scala-js#2208]
Scala-js throws UndefinedBehaviorError in some cases. No stack trace is provided, which makes the bug very difficult to solve.

For example:
.../target/scala-2.11/uijs-fastopt.js:176
  throw new $c_sjsr_UndefinedBehaviorError().init___jl_Throwable(
`scala.scalajs.runtime.UndefinedBehaviorError: An undefined behavior was detected: undefined is not an instance of java.lang.String`

It would be useful to get a full stack trace. If it cannot be provided, what would be a good way to debug the issue?

**Comment by sjrd** [comment]
It does have stack traces. But if it reaches the top-level of Node.js, for some reason Node.js does not display it.

If you explicitly try/catch it in some strategic places (e.g., in `main()`), you can get nice stack traces:
```scala
def main(): Unit = {
  try {
    theWholeApp()
  } catch {
    case th: Throwable =>
      th.printStackTrace()
      throw th
  }
}
```

**Comment by sjrd** [comment]
This is actually a duplicate of #1810.
