### ISSUE TITLE
this["require"]() and fastOptJS

### ISSUE THREAD

**Issue by zifeo** [scala-js/scala-js#2217]
As explained on https://github.com/facebook/react-native/issues/465 some scala-js interfaces cannot be used with `fastOptJS` due to lack of `this["require"]()` syntax support. Any chance to have now a solution on scala-js side?

**Comment by sjrd** [comment]
It's actually `$g["require"](...)` that we use (not `this`), and `$g` resolves to the global scope (`global` on Node.js and `window` in browsers)

Would it work if it was `$g.require(...)` instead of `$g["require"](...)`? Or do they really need `require(...)` without qualifier?

**Comment by chandu0101** [comment]
>Would it work if it was `$g.require(...)` instead of `$g["require"]( .. .)` ?

yeah it will work if it was `$g.require(..)`

**Comment by sjrd** [comment]
OK then we can fix it. We just have to change the emitter to "optimize" bracket selects into dot selects when possible, if `useClosureCompiler` is `false`.

**Comment by gzm0** [comment]
Hmmm... That's a bit of a strange option to the emitter, but ok... So you would say the `BasicBackend` would just always to that?

**Comment by sjrd** [comment]
Yes, `BasicBackend` would always do it.

It makes sense as an optimization in general. It's just that this optimization is not valid when using Closure.

**Comment by chandu0101** [comment]
:+1:  :clap:

**Comment by zifeo** [comment]
thanks @sjrd!
