### ISSUE TITLE
Allow direct JS embedding

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#2218]
```scala
val omgjsx = js.eval( """(function () { return "ah"; })();""")
```
produces
```js
  this.omgjsx$1 = $g["eval"]("(function () { return \"ah\"; })();");
```

I want a similar function that I can use like this
```scala
val omgjsx = js.embed( """(function () { return "ah"; })();""")
```
to produce
```js
  this.omgjsx$1 = (function () { return "ah"; })();
```

##### Why?
As part of https://github.com/japgolly/scalajs-react/issues/192 I'm trying to mimic what Babel does which is to insert a helper function (see: 
https://github.com/babel/babel/commit/d1b8db1532d82b5d533732412b1bb9b9b6987251#diff-ba75bd4d116cc90ad8c8002e3010e821).

I want to just be able to copy the helper JS verbatim to use in scalajs-react.

##### Why not `js.eval`?
I can use `js.eval` as is but that fact that it produces a string means:
* `fullOptJS` isn't able to optimise the JS snippet. ← Big deal
* there's a performance hit for string eval in JS-land ← Small deal

I understand that such a function would result in invalid/corrupt output JS but in the rare cases that it's used, the developer accepts full responsibility. Can we have this?

**Comment by sjrd** [comment]
No, we cannot have this. This has been discussed before, most notably in #1846.

> I want to just be able to copy the helper JS verbatim to use in scalajs-react.

The right way to do it would be to simply rewrite the helper in Scala.js code, as a `def`, then call it.

**Comment by japgolly** [comment]
Oh. No worries.
