### ISSUE TITLE
Linker/optimiser performance in 0.6.6

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#2222]
Linker/optimiser is doing weird stuff and taking a *looong* time.

Here is a graph of CPU load x time:
![CPU load x time](https://cloud.githubusercontent.com/assets/202935/12770681/91804508-ca76-11e5-97db-b0409063a1fa.png)

Here is a stack trace when low:
[stack2.txt](https://github.com/scala-js/scala-js/files/114981/stack2.txt)

Here is a stack trace when high:
[stack3.txt](https://github.com/scala-js/scala-js/files/114982/stack3.txt)

You could probably reproduce this - I was working on scalajs-react and using this command: 
```
~test/test-only -- japgolly.scalajs.react.experimental
```

**Comment by sjrd** [comment]
Uh oh ... [`OptimizerCore.scala:205`](https://github.com/scala-js/scala-js/blob/v0.6.6/tools/shared/src/main/scala/org/scalajs/core/tools/linker/frontend/optimizer/OptimizerCore.scala#L205) was last touched by #2022. And somehow your threads stay so long in this `map` that you always capture snapshots there :-s

That PR stopped trying to do manual memory management of the states that `tryOrRollback` has to restore. The theoretical consequence was that it might have to keep more states than actually necessary, and then "in theory" spend more time doing useless work there. But I did not think it could be noticeable, in the sea of everything else the optimizer does :-s

**Comment by sjrd** [comment]
Note-to-self: possible explanation: a method (or a lot of methods) in the codebase perform an undue amount of rollbacks. Rollbacks would, I think, keep growing the set of states in use. If things get as bad as I can imagine, the number of states would grow exponentially with the number of rollbacks. In that case, 10/15 rollbacks might already be enough to cause serious slowdowns.

**Comment by sjrd** [comment]
@japgolly There's a possible fix in #2233. You could try to [publishLocal](https://github.com/scala-js/scala-js/blob/master/DEVELOPING.md#publish-locally) the branch of that PR and use 0.6.7-SNAPSHOT in scalajs-react if this is currently a serious issue for you. (Avoid publishing a version of your library built with a Scala.js SNAPSHOT, though.)

**Comment by japgolly** [comment]
Ok, I'll give it a try now.

**Comment by japgolly** [comment]
Tested 0.6.6 and the PR twice:
* 65s → 17s
* 70s → 12s

You fixed it. :+1:

**Comment by ngbinh** [comment]
Lovely!
