### ISSUE TITLE
Test interface communication protocol.

### ISSUE THREAD

**Issue by nicolasstucki** [scala-js/scala-js#2224]
@gzm0, right now I'm working on implementing a new `ComJSRunner` based `ComPhantomRunner` WebSockets communication (but on Jetty 9). I'm having some issues with the communications because the JS client seems to initialize the connection send the first message and immediately close the communication channel. And hence does never receive the first message from the the JVM side.

To be a bit more explicit, on the JS side I have this sets of functions:
```javascript
scalajsCom = {
    init: function(recvCB) { ... },
    send: function(msg) { ... },
    close: function() { ... } 
}
```
Which is the protocol used to call these function? When does it call `close`?

The same questions apply for `ComJSRunner.open`, `ComJSRunner.send`, `ComJSRunner.receive`, `ComJSRunner.close`.
 
You can find the relevant of the communication code that I've implemented so far for the `ComJSRunner` at [WebsocketComJSRunner.scala](https://github.com/nicolasstucki/scala-js/blob/add-selenium-env/js-envs/src/main/scala/org/scalajs/jsenv/websocket/WebsocketComJSRunner.scala).

**Comment by gzm0** [comment]
The com works as follows:

If the client wants to use the com, it has to call `init` before the event loop returns. The com will then keep the VM running until the other side (i.e. the JVM) closes the connection. Calling close on the JS side will release calls to `receive` on the JVM side (with an exception).

If the JS client terminates, this is probably a problem in the auto termination behavior of PhantomJS. Unlike Node.js, PhantomJS is not smart about whether to keep running even if there is no code to execute. So you have to terminate the VM yourself when appropriate.you tell it to

**Comment by nicolasstucki** [comment]
I see.

In my case the JS sends the string: 
```json
{"name":"Jasmine for Scala.js","fingerprints":[{"fpType":"SubclassFingerprint","isModule":true,"superclassName":"org.scalajs.jasminetest.JasmineTest","requireNoArgConstructor":true}]}
```
and immediately calls close. The implementations waits for the connection to open before performing the actual `socket.close` and sends all buffered message.

On the JVM side, once the message is received, the connection is closed. Immediately after that it starts the connection again and tries to send the string `newRunner:{"remoteArgs":[],"args":[]}` and hangs there waiting for the JS side to connect. 

As for the closing of the JS (in this case a Firefox instance through Selenium), I'm leaving it open after the all scripts have finished executing. But I do finish the the async run by completing the future.

Is there something that sounds wrong so far? Or, is the problem is that the JS side should be trying to receive that message? Is the `run` script supposed to finish before communication is finished (i.e. continues though asynchronously), if so when do I know that all communication has ended and that it is safe to terminate?

**Comment by gzm0** [comment]
I think you are mixing things. The JSRunner that replies the fingerprints and the one that actually executes the tests are two different instances of the runner.

The first comes from [`fetchFrameworkInfo`][1], the second one comes from [`createRemoteRunner`][2].

[1]: https://github.com/scala-js/scala-js/blob/master/test-adapter/src/main/scala/org/scalajs/sbttestadapter/ScalaJSFramework.scala#L50
[2]: https://github.com/scala-js/scala-js/blob/master/test-adapter/src/main/scala/org/scalajs/sbttestadapter/ScalaJSRunner.scala#L216
