### ISSUE TITLE
-jsdeps.min.js not produced anymore after upgrading from 0.6.5 to 0.6.6 and 0.6.7

### ISSUE THREAD

**Issue by gabriel-bezerra** [scala-js/scala-js#2243]
In version 0.6.5, running `sbt fastOptJS fullOptJS` used to produce both -jsdeps.js and -jsdeps.min.js.

After upgrading to 0.6.6 and 0.6.7, the -jsdeps.min.js stopped being generated.

After further investigating, I could see that

* running `sbt fastOptJS` (without `fullOptJS`) would produce just the -jsdeps.js -- as expected.
* running `sbt fullOptJS` (without `fastOptJS`) would produce just the -jsdeps.min.js, but not -jsdeps.js.
* running `sbt fastOptJS fullOptJS` would produce just the -jsdeps.js, but not -jsdeps.min.js.

Please check this repository for reproducing the bug: https://github.com/gabriel-bezerra/scalajs-067-minified-jsdeps-bug

**Comment by sjrd** [comment]
Thanks for the report!

**Comment by gabriel-bezerra** [comment]
You're welcome!

**Comment by sjrd** [comment]
Some more information: first executing `fullOptJS` *then* `fastOptJS` will produce `-jsdeps.min.js` but not `-jsdeps.js`. Basically, whatever is produced first wins. Reloading or rebooting sbt between one task and the next has the same results, so it's not some internal in-memory state of the sbt plugin.

**Comment by gzm0** [comment]
Probably some doubly used cache file location.

**Comment by gzm0** [comment]
`stream.value` instead of `(stream in task).value` maybe?

**Comment by gabriel-bezerra** [comment]
Thank you, folks!
