### ISSUE TITLE
Run JUnit tests in HTML test-suite runner

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#2248]
Our HTML test-suite runner currently relies on `run-jasmine-tests.js` which (so says the name), does not run JUnit tests.

**Comment by sjrd** [comment]
This would be addressed by #1709, wouldn't it?

**Comment by gzm0** [comment]
Yes. I thought about #1709 as something more user facing, but maybe it is a good way to get some experience with writing HTML runners.

**Comment by gzm0** [comment]
I'll take a stab at implementing something simple that exports detected tests from sbt and then runs them in the browser today.
