### ISSUE TITLE
Publish js-envs tests.

### ISSUE THREAD

**Issue by nicolasstucki** [scala-js/scala-js#2250]
It will be required for the tests of `scala-js/scala-js-env-selenium`.

**Comment by sjrd** [comment]
A workaround would be for scalajs-js-env-selenium to fetch the sources of scala-js/scala-js, and source-in the js-envs tests from there.

**Comment by gzm0** [comment]
I actually think publishing tests would be a good thing anyways for compliance: AFAICS, we don't have tests that are specific to a given `JSEnv` (the ones in Node can be moved to relevant sub-traits). So anyone implementing a `JSEnv` should be able to use them for compliance checking.
