### ISSUE TITLE
Enable `dependsOn` for CrossProject

### ISSUE THREAD

**Issue by nlhkh** [scala-js/scala-js#2255]
When I want to make a `CrossProject` depend on another plain Scala project (within the same build), I have to do this
```scala
lazy val jvm = myCrossProject.jvm dependsOn dependency

lazy val js = myCrossProject.js dependsOn dependency
```

Would it be nicer to have a `dependsOn` method on a `CrossProject` object that also returns a CrossProject?

**Comment by sjrd** [comment]
That shouldn't even happen. A JS project must not depend on a JVM project (nor conversely).

**Comment by lihaoyi** [comment]
@sjrd if it was a pure-macro-library like Async or scalaxy shouldn't it work? Those aren't really "JVM" or "JS", they just are

**Comment by sjrd** [comment]
True, but nothing seems to indicate this is the case, here. Pure-macro libraries are pretty rare. Most also contain some runtime code.

**Comment by nlhkh** [comment]
I see your point.
