### ISSUE TITLE
Operators `in` and `instanceof` for `js.Dynamic`

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2264]
The `in` operator is a bit weird. We offer it as a method `js.Object.hasProperty`. But it is supposedly only useful for `js.Dynamic` situations anyway. Assuming a clean design, we could declare it as method on `js.Dynamic`:

``` scala
trait js.Dynamic extends js.Any with scala.Dynamic {
  ...
  def in(that: js.Dynamic): js.Dynamic
}
```

and handle `in` in the same way we handle all the symbolic operators on JS types. It would sort-of be one primitive less, although it's replaced by a magic name, so not much better. However, it's definitely more consistent wrt the other JS operators. And we could then write:

``` scala
import js.DynamicImplicits._
if ("foo" in myDynamic)
```

:-p

`instanceof` is in a worse situation. I realize _we do not have_ any construct allowing the user to emit a _dynamic_ `instanceof` operator, i.e., where the right-hand-side is not statically known as a facade class. We can fix this hole in our interop offering in the same way as `in`.

Now, adding two methods on `js.Dynamic` would be a potentially serious source incompatible change. If someone had an implicit pimp with `in` or `instanceof`, it would be destroyed; that's unlikely. However, since they would be magic _names_, the same treatment would apply to all facade types declaring a `def in` or a `def instanceof`. And this is actually likely, as in JS it's perfectly OK to use `in` and `instanceof` as property names (even without quotes):

``` js
> var o = {in: function() { console.log("in"); }, instanceof: function() { console.log("instanceof"); }};
> o.in()
in
> o.instanceof()
instanceof
```

What we could do is to provide a smooth migration path is:
- In 0.6.x:
  - Offer the methods as opt-in pimps on `js.Dynamic` through `js.DynamicImplicits`. That would include an implicit from `String` to give it the `in` operator with a rhs which is a `js.Dynamic`.
  - Emit a warning for `def in` or `def instanceof` in JS types that do not have an explicit `@JSName`, telling that the behavior of such a definition will change in 1.0.0.
- In 1.0.0:
  - Turn `in` and `instanceof` into magic operator names
  - Declare `in` and `instanceof` on `js.Dynamic`
  - Deprecate the pimps from `js.DynamicImplicits`

Globally, I like the idea, but I'm worried about the long-term implications of making `in` and `instanceof` magic names. It makes sense compared to the treatment of other symbolic JS operators. But unlike symbolic operators, there's a real chance these are used as normal methods in JS things. Then again, we _do_ have an admittedly worse precedent with `apply`!

WDYT?

**Comment by gzm0** [comment]
What is the status on this? Should it be on the 1.0.0 milestone?

**Comment by sjrd** [comment]
It should at least be there so that we think about it, yes.

However, I'm less convinced we need this. The `in` thing is cosmetic, and the `instanceof` thing will be solved by an `@JSLoadVia`, as we can define in user-space:
```scala
def instanceof(lhs: js.Dynamic, rhs: js.Dynamic): Boolean = {
  @js.native
  @JSLoadVia(rhs)
  class Rhs extends js.Any

  lhs.isInstanceOf[Rhs]
}
```

**Comment by sjrd** [comment]
I'm pretty convinced now that we should not do this. It has several practical issues, for only theoretical benefits.
