### ISSUE TITLE
User-space implementation of js.Array.apply

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2266]
Continuing my quest against compiler primitives!

`js.Array.apply` (almost) does not need to be a primitive. It could be implemented in user-space as a pimp (herein called `make`, but it would be `apply`):

``` scala
implicit class MyJSArray(val self: js.Array.type) extends AnyVal {
  @inline
  def make[A](elems: A*): js.Array[A] = elems.toJSArray
}
```

(or, without requiring the fix of #2265, as:)

``` scala
@inline
implicit class MyJSArray(val self: js.Array.type) {
  @inline
  def make[A](elems: A*): js.Array[A] = elems.toJSArray
}
```

Because `toJSArray` is inlined and specializes the case `js.WrappedArray`, a call such as

``` scala
val array = js.Array.make(5, 6, 7)
```

reduces to:

``` js
  var self = $g.Array;
  var array = [5, 6, 7];
```

(seriously, it does)

The only disappointment is that `$g.Array` cannot be eliminated. With an `AnyVal`, the `var self =` disappears, so only `$g.Array` remains. But that _could_ have a side-effect is some evil person replaced the global `Array` variable by a _getter_ on the global object.

Note that this happens because `object js.Array` is a JS native, and not a Scala object. An alternative would be to turn it into a Scala object instead. (in the next major version, in that case)

Opinions?

**Comment by gzm0** [comment]
I vote for turning `js.Array` into a Scala object and just forwarding `isArray`. We can make the raw array object a member of the Scala object or something.

**Comment by sjrd** [comment]
I have changed my mind about this. It makes sense to have a primitive that is guaranteed to generate a `JSArrayConstr`. Also it only has a ~4 LoC tax on the compiler source code, so it's not like it's a maintenance burden.
