### ISSUE TITLE
runtime.environmentInfo could be a member of runtime.linkingInfo

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2267]
It was top-level because `linkingInfo` was invented later. But it really could be a member of `linkingInfo`. That makes it a non-primitive as well. Better: that's one less IR node!

The desugaring can constant-fold it away, like it already does for `<envinfo>.global`.

We can do this in 0.6.x. There would be a deserialization hack to turn a `JSEnvInfo()` into `JSBracketSelect(JSLinkingInfo(), StringLiteral("envInfo"))`.

**Comment by gzm0** [comment]
I first wanted to object to the name. But with some afterthought, this makes sense: The location of the `envInfo` object is just linker-supplied static information like everything else in there. Even how the values are populated could be specific to a given backend.
