### ISSUE TITLE
Write unit tests for the IR printers

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2272]
See https://github.com/scala-js/scala-js/pull/2258#issuecomment-189242905

**Comment by mrmiywj** [comment]
Maybe it is a good start to pick it up and write some tests? I could try this I think. It helps me understand IR.

**Comment by sjrd** [comment]
That could be a good start, yes.

**Comment by mrmiywj** [comment]
Yep, I will try to pick it up.
