### ISSUE TITLE
Need something to invoke the "debugger" statement

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#228]
Personally, I'm more in favor of using breakpoints, but that's not a good reason to prevent people from using an equivalent to the `debugger` statement of JavaScript. So we should have something that maps to this statement.

I think `js.debugger()` is a good equivalent.

**Comment by ebruchez** [comment]
In case someone finds this old closed issue via a web search, note that in recent versions of Scala.js this is `js.special.debugger()`.
