### ISSUE TITLE
artifactPath of packageMinifiedJSDependencies is computed from packageJSDependencies

### ISSUE THREAD

**Issue by nicolasstucki** [scala-js/scala-js#2282]
`artifactPath` is currently computed from `crossTarget` and `moduleName` in `packageJSDependencies`. But it should be computed from `crossTarget` and `moduleName` in `packageMinifiedJSDependencies`. Currently nothing is failing because `crossTarget` and `moduleName` are always equals.

**Comment by sjrd** [comment]
It's not internal. People could redefine `crossTarget/moduleName in packageMinifiedJSDependencies` in their builds.
