### ISSUE TITLE
Facilitate jsEnv-dependant testing

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#2295]
*(Background)* Now that we have env-selenium, I can re-enable some old tests that I had to disable long ago. Selenium isn't fast so I'd want to keep the majority of my tests running fast on PhantomJS, and then less frequently, run all those tests + those that don't work in PhantomJS, on Selenium. I don't imagine I'll be the only one with these requirements so I'd like to work something out and finally add some doc to the scala-js website. I didn't raise this in the sjs-selenium repo because it also applies to any new jsEnvs that get added in future, and I didn't raise this in the website repo because I'm guessing a little support might need to be added to SJS to facilitate this.

One thought was, it might be an idea to expose some details about the jsEnv like we do with `{development,production}Mode`. Then one could write something like `if (jsEnv.name contains "selenium") { … }`. Not the nicest.

Another idea could be adding new test configs to SBT settings with each one having their own jsEnvs and their own source folders. It would be nice to have `test-firefox` and `test-chrome`, and be able to `test-firefox:test-only a.b.c`. A `test-all` aggregate would be nice too. (If I bang something together for my own needs, I'll likely do something like this.)

Any ideas?

**Comment by sjrd** [comment]
You can reuse existing mechanisms of sbt for this: use a different configuration (such as `it`) and configure that one to use selenium, and include the sources of both tests. 

We don't need anything more than what we already have, I believe.

**Comment by gzm0** [comment]
Maybe have a look in [Scala.js' build][1] for inspiration.

[1]: https://github.com/scala-js/scala-js/blob/master/project/Build.scala#L1074

**Comment by japgolly** [comment]
Can I ask a question? I'd like to add SBT test configurations `firefox` and `chrome` that don't have their own source dirs and reuse the normal `test` config's JS artifact. For example, when I run `firefox:test` or `firefox:test-only` it will trigger a normal `test:compile` and `test:fastOptJS` then reuse the `test-fastopt.js` without recompilation. Do you know how?

All the SBT doc I read teaches how to add new source dirs and depend on other ones, but in this case I think it might be a custom SJS issue to have the `jsEnv` reuse the output from another task. I'm not quite sure how.

**Comment by japgolly** [comment]
> One thought was, it might be an idea to expose some details about the jsEnv like we do with {development,production}Mode. Then one could write something like if (jsEnv.name contains "selenium") { … }. Not the nicest.

By the way for anyone else reading, this ↑ is easily done by doing the same thing all other JS does when it wants to find out it's operating environment: check `navigator.{userAgent,appVersion,appName}`, use platformjs, etc. Silly of me not to realise that in the first place :laughing: .

**Comment by sjrd** [comment]
> I'd like to add SBT test configurations firefox and chrome that don't have their own source dirs and reuse the normal test config's JS artifact.

You could try doing the normal sbt thing to add a configuration, then override `fastOptJS` and `fullOptJS`:
```scala
fastOptJS in Firefox := (fastOptJS in Test).value
fullOptJS in Firefox := (fastOptJS in Test).value
```
There might be other settings to rewire in the same way. Check out what tasks are defined by `ScalaJSPluginInternal.scala` for inspiration.

**Comment by japgolly** [comment]
Wow, that was easy. Thank you! I'm down to one last problem. The tests run without additional compilation :+1: and Firefox pops up :+1: , but output doesn't appear in the SBT console and on completion it says 0 tests ran :-1:. Any suggestions for that?

**Comment by sjrd** [comment]
> There might be other settings to rewire in the same way. Check out what tasks are defined by ScalaJSPluginInternal.scala for inspiration.

^^

**Comment by japgolly** [comment]
Solved! I delegated the following SBT's test keys and it did the trick.

```scala
  definedTests         := (definedTests         in Test).value,
  definedTestNames     := (definedTestNames     in Test).value,
  testOptions          := (testOptions          in Test).value,
  testForkedParallel   := (testForkedParallel   in Test).value,
  testResultLogger     := (testResultLogger     in Test).value,
  testGrouping         := (testGrouping         in Test).value,
```

Ok, I'll clean up what I've got and then put it online soon for others.

As always, thank you for the guidance here and for great work you all do to make this possible, @sjrd  @gzm0 @nicolasstucki. :bow:
