### ISSUE TITLE
Type errors should be NonFatal

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#2304]
Consider this in JVM Scala:
```
scala> scala.util.Try(3.asInstanceOf[String]) getOrElse "X"
res0: String = X
```

And now, the same code in JS:
```
 
```
It hangs; no output (#2305). This is because Fatal errors escape `Try` and UBE's are fatal. 

So firstly, JS doesn't match JVM behaviour.
Secondly, when dealing with JS libraries and DOM, type errors are common and certainly aren't fatal.

Either:
1) `UndefinedBehaviorError` is used exclusively for JS type errors in which case it really shouldn't extend `ControlThrowable`. It doesn't implement flow control and doing so means that it slips through the fingers of `case NonFatal(_)`. 
2) If UBE's have all kinds of other uses, then JS type errors should be throwing `ClassCastException`s (or similar and *NonFatal*) instead.

**Comment by sjrd** [comment]
No, the existing behavior (type errors throw `UBE` and they are fatal errors) is intentional and as designed.

Now the hanging/silent behavior in JS is not good. We should display *something*, somewhere. But that's another issue.

**Comment by japgolly** [comment]
I know it's intentional but the problem is that it's wrong. A type error isn't fatal, specially in JS-land where duck-typing. It's very easily recoverable.

**Comment by gzm0** [comment]
![Brace Yourself](https://i.imgflip.com/118iol.jpg)

**Comment by sjrd** [comment]
(about the picture, lol ...)

The problem is not that it's not easily recoverable. It is that, in production, it becomes UB, where it *is* unrecoverable (because there won't be a check in the first place).

There is no such thing as JS-land casts vs Scala casts. All are equal: because of erasure, cats for "inner" type parameters are delayed, so there is no way to know whether something was originally a "JS cast" or a "Scala cast".

Duck typing is a different thing. It can throw `TypeError`s, a kind of JavaScript exception, which *is* non-fatal, as it is wrapped in a `JavaScriptException`. Here you have *cast* errors, which come because you or someone else mistyped JavaScript facade types or performed illegal casts. Those are *undefined behavior*, and therefore are fatal.

**Comment by japgolly** [comment]
*(hahaha @gzm0)*

@sjrd What's the difference between a cast/type exception in production at runtime, and an exception of any other kind? I don't see why there should be a difference. If you're saying that at production there aren't SJS-based type checks well won't we just end up with a `TypeError`? So:

> in production, it becomes UB, where it is unrecoverable (because there won't be a check in the first place).

Wouldn't it be the same as this in production:
```js
var x = 3; x.ww.ww
// VM664:2 Uncaught TypeError: Cannot read property 'ww' of undefined(…)
```

> There is no such thing as JS-land casts vs Scala casts. All are equal: because of erasure, casts for "inner" type parameters are delayed, so there is no way to know whether something was originally a "JS cast" or a "Scala cast".

We might have a misunderstanding somewhere if you think that's what I meant :) I don't want to differentiate JS/Scala cast exceptions. What I meant was why not make any cast exception (Scala or JS) throw a `ClassCastException`?

> Here you have cast errors, which come because you or someone else mistyped JavaScript facade types or performed illegal casts. Those are undefined behavior, and therefore are fatal.

That's not always true. A facade can be typed correctly according to a contract and you could have someone else in JS-land slip something in and expect it to work (which is does) because duck-typing is common. For example, React have interfaces for event shims but their own test utils don't always implemented everything required. So sometimes you get `undefined`s and if you take it a step further you get a `TypeError`. Neither cases are fatal.

Also to make sure I'm understanding your argument correctly, is it that because SJS type checking can be turned on & off, and so is not always catchable? Thus you're making it (generally) uncatchable by avoiding `NonFatal`?

**Comment by sjrd** [comment]
See the Undefined Behaviors section of the [Scala.js semantics](https://www.scala-js.org/doc/semantics.html).

> What I meant was why not make any cast exception (Scala or JS) throw a ClassCastException?

Because it's too slow. It makes your *entire* program up to twice as slow. If you want it, you can get it with
```scala
scalaJSSemantics ~= { _.withAsInstanceOfs(
  org.scalajs.core.tools.sem.CheckedBehavior.Compliant) }
```
but your program will be much slower.

> Wouldn't it be the same as this in production:

No, it wouldn't. It's UB. *Anything* can happen.

> Thus you're making it (generally) uncatchable by avoiding NonFatal?

Yes.

> A facade can be typed correctly according to a contract and you could have someone else in JS-land slip something in and expect it to work (which is does) because duck-typing is common.

Then the facade is not correctly typed anymore.

**Comment by japgolly** [comment]
Will read UB section, think, and respond later.

But for now quickly:

>> A facade can be typed correctly according to a contract and you could have someone else in JS-land slip something in and expect it to work (which is does) because duck-typing is common.
>
> Then the facade is not correctly typed anymore.

Ideally yes, but not always true. Example (before I forget tonight's JS shenanigans): React event has a `.target`, which is populated with a `HTMLTextAreaElement` which has a `.tabIndex`. `tabIndex` is typed in scalajs-dom as `Int` which matches the spec but the instance that React's testing stuff provides somehow has a `tabIndex` of `undefined`. The facade of `HTMLTextAreaElement` is correctly typed. In JS usage you don't notice because of the zoo that allows `-1 < 0` and `undefined < 0` to both be `true`, but in this case SJS is pre-emptive and unforgiving.

**Comment by sjrd** [comment]
> but in this case SJS is pre-emptive and unforgiving.

Yes, it has to, to protect its own abstractions. If it wasn't, the optimizer could never rely on *anything* being soundly typed, and that means no optimization whatsoever.
