### ISSUE TITLE
Adapt to Scala 2.12.0-M4: a Function node can have any SAM type, not just FunctionN

### ISSUE THREAD

**Issue by adriaanm** [scala-js/scala-js#2309]
The community build has [revealed](https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/357/consoleFull) a problematic interaction between https://github.com/scala/scala/pull/4971 and scala-js:

```
[scala-js] Running "test" in: jasmineTestFramework
[scala-js] java.lang.RuntimeException: First argument to init must be a function
[scala-js] 	at scala.sys.package$.error(package.scala:27)
[scala-js] 	at org.scalajs.jsenv.rhino.RhinoJSEnv$$anonfun$org$scalajs$jsenv$rhino$RhinoJSEnv$$setupCom$2.apply(RhinoJSEnv.scala:344)
[scala-js] 	at org.scalajs.jsenv.rhino.RhinoJSEnv$$anonfun$org$scalajs$jsenv$rhino$RhinoJSEnv$$setupCom$2.apply(RhinoJSEnv.scala:338)
[scala-js] 	at org.scalajs.jsenv.rhino.package$ScriptableObjectOps$$anon$1.call(package.scala:32)
[scala-js] 	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1473)
```

@retronym suggests this may be because Function nodes are now allowed to have any SAM type. During uncurry, we expand those that LambdaMetaFactory can't handle into an anonymous subclass as before. The others will reach the scala-js plugin.

The most recent commit in the PR is available from `"pr-scala snapshots" at "https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/"` as `2.12.0-3ae3903-SNAPSHOT`.

We're hoping to release M4 very soon (in the next day or two) -- please let us know if you consider this a showstopper!

**Comment by sjrd** [comment]
> @retronym suggests this may be because Function nodes are now allowed to have any SAM type.

Yes, that is probably the reason. I'll work on this today.

**Comment by adriaanm** [comment]
Thanks!

**Comment by sjrd** [comment]
After some fixes in how scalac deals with SAMs, our test suite passes out-of-the-box.

However, we still have the problem that we do not support the trees generated for LambdaMetaFactory-capable SAMs. So this ticket is still valid, but not a blocker for scalac M4 anymore.

**Comment by sjrd** [comment]
WiP for supporting all SAMs at https://github.com/scala-js/scala-js/compare/master...sjrd:new-sams
It "should work", but I have not had time to write tests yet. I will continue after my vacations.
