### ISSUE TITLE
Migrate away from our Build.scala build definition

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2311]
It seems sbt folks have simply decided they'd drop support for `Build.scala` build definitions: https://github.com/sbt/sbt/pull/2524

So we should at least investigate now whether it's possible for our build to survive in those conditions.

**Comment by dwijnand** [comment]
I'd be happy to have a go at this if you'd like.

**Comment by gzm0** [comment]
I guess nobody will oppose to that (unless @sjrd or @nicolasstucki has already started). But be aware: You might run into weird cyclic dependencies in places where we still use the old `Project` creation style (ping me or @sjrd  if you do).

**Comment by sjrd** [comment]
We haven't started. @dwijnand By all means you can take a stab at it ;)

**Comment by dwijnand** [comment]
Cool. I'll take a stab at it. Would you say Travis passing is a good
indicator of a successful migration or shall I run some additional tests,
and if so which?

**Comment by nicolasstucki** [comment]
I have not started either. Feel free to take it ;)

**Comment by sjrd** [comment]
It's not Travis, it's Jenkins. But yes, that is a very good indicator. There is nothing sbt-related we test besides what Jenkins does.

As a simple local test, just run `testSuite/test`. For the full thing, look at `ci/matrix.xml`.
