### ISSUE TITLE
Loading multiple SJS-generated programs

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#2326]
Suppose I have:
* SJS project A, I run `fullOptJS`, get `a-opt.js` as output.
* SJS project B, I run `fullOptJS`, get `b-opt.js` as output.

If they both export `example_pkg.ExampleObject.main()` how can I load both `a-opt.js` and `b-opt.js` into a single JS environment (without SJS) and call both `main()`s?

**Why?** As part of https://github.com/japgolly/scalajs-benchmark/issues/5 I'd like to create a framework for regression testing and rather than recording BM results and having to worry about env/hw differences I think it would be smarter to export and save the full JS for each point in time you want measured. As an example, that would allow you to have performance regression for SJS itself; imagine a matrix of Scala.JS x Scala versions in your browser, then when you run it it loads the JS for each, meaning that changes in browsers over time don't skew past results (because there are no past results). That's the motivation here.

Using a JS AST inspector I see that SJS fullOptJS is just a single function (great!) that is called with `this`. Does  that mean we're nearly there and that I'd just need to replace the `this` with something else? If not (and I don't know much about this) but if we export JS in such a way that AMD or CommonJS or similar (?) can handle it should be possible and hopefully trivial.

**Comment by sjrd** [comment]
Just use different `__ScalaJSEnv` before loading each, with different exports namespaces:
```scala
var exports1 = {};
var __ScalaJSEnv = { exportsNamespace: exports1 };
// import first Scala.js output file

var exports2 = {};
var __ScalaJSEnv = { exportsNamespace: exports2 };
// import second Scala.js output file
```
That said, for benchmarking, they might still be polluting each other just because they run in the same VM.

**Comment by japgolly** [comment]
Fantastic! Thanks.

> That said, for benchmarking, they might still be polluting each other just because they run in the same VM.

How would they pollute each other or the JS VM? Is there some kind of global state that namespacing won't avoid?

**Comment by sjrd** [comment]
Yes: profiles, code cache, and who knows what other internal global state of the JIT.

**Comment by japgolly** [comment]
Ah all that is to be expected.

Ok cool, it looks like when I get the time I have everything I need. Thanks as always! :beer:
