### ISSUE TITLE
ES6 functions seem to be missing from JSStringsOps

### ISSUE THREAD

**Issue by a-tsioh** [scala-js/scala-js#2329]
for example, check normalize()

**Comment by sjrd** [comment]
Thanks for the report.

**Comment by sjrd** [comment]
AFAICS, only [`normalize()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize) is useful.

There are 2 others additions in ES6, namely [`includes`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes) and [`repeat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat), but those are already available in Scala as `contains` and `*`, respectively.
