### ISSUE TITLE
Different hashCode in JS and JVM for case class with big Long 

### ISSUE THREAD

**Issue by LMnet** [scala-js/scala-js#2345]
I have a case class with the long value. If this long is less than `Int.MaxValue` I have the same results of `hashCode` invocation in the JVM and in the JS runtimes.
But if this long is bigger than `Int.MaxValue`, I have different results in different runtimes

Minimal example:
```scala
case class A(long: Long)

val big = 1461126709984L
val small = 1L

val bigClass = new A(big)
val smallClass = new A(small)

println(big.hashCode())
println(bigClass.hashCode())
println(small.hashCode())
println(smallClass.hashCode())
```
Results for JVM:
```
837829556
259268522
1
818387364
```
Results for JS:
```
837829556
509963985
1
818387364
```
Only `bigClass.hashCode()` is different.

**Comment by sjrd** [comment]
Thanks for the report!
