### ISSUE TITLE
Get rid of EmptyTree

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2359]
The only valid uses of `EmptyTree` in the IR are:
* The getter and setter of a `PropertyDef` -> better use `Option`s
* The catch and/or finally parts of a `Try` -> better split `Try` in `TryCatch` and `TryFinally`
* The body of an abstract method -> annoying, but it would probably be better to use `Option` anyway

**Comment by gzm0** [comment]
Yay! I though exactly the same when reviewing your code yesterday :)

**Comment by gzm0** [comment]
@sjrd, can I steal this from you?

**Comment by sjrd** [comment]
Sure. I'm on modules, atm.
