### ISSUE TITLE
RhinoJSEnv does not support setTimeout without second argument

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#2368]
This will crash:

```javascript
setTimeout(myFunction);
```

But [is valid](https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/setTimeout).

```
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.scalajs.jsenv.rhino.RhinoJSEnv$$anonfun$setupSetTimeout$1.apply(RhinoJSEnv.scala:290)
	at org.scalajs.jsenv.rhino.RhinoJSEnv$$anonfun$setupSetTimeout$1.apply(RhinoJSEnv.scala:286)
```

**Comment by gzm0** [comment]
Discovered while investigating #2322.

**Comment by nafg** [comment]
FTR - If I have `"org.webjars" % "jquery" % jQueryVersion / "jquery.js" minified "jquery.min.js"` in my `jsDependencies` where `jQueryVersion` >= 2.2, this causes `test` to fail even if I have no actual tests written [that call setTimeout].

**Comment by Enalmada** [comment]
I just hit this problem without having any idea what caused it.  Thanks to nafg, going back to older jquery (in my case 1.11.1) made the problem go away.
