### ISSUE TITLE
Move CustomInitFilesTest to jsEnvTestSuite

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#2375]
I don't know why they ended up in the kit in the first place. At lest the Node.js and PhantomJS instantiations of the test should be in the suite not the kit.

**Comment by nicolasstucki** [comment]
Yes, `NodeJSWithCustomInitFilesTest` and `PhantomJSWithCustomInitFilesTest` should be test suite and `CustomInitFilesTest` in the kit. I will use `CustomInitFilesTest` to test the `SeleniumJSEnv`.
