### ISSUE TITLE
Compile error to outlaw user-space use of RawJSType

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2387]
The compiler should prevent developers from using `@RawJSType` (and other compiler-inserted annotations).

**Comment by gzm0** [comment]
Hahahaha, Katrin, you did not seriously use this??

**Comment by katrinsharp** [comment]
I used it big time, ask Sebastian :) Now seriously speaking when I accidentally stumbled upon this thing yesterday I thought that 'RawJSType' is a new replacement for 'ScalaJSDefined' and I actually liked the name :) cc @gzm0
