### ISSUE TITLE
Experiment with sbt 1.0.0-M4

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2390]
http://notes.implicit.ly/post/144270218979/sbt-100-m4

Since we have one of the most complicated open source sbt builds, we really should vet sbt 1.0.0-x against it.

**Comment by sjrd** [comment]
Ongoing at https://github.com/scala-js/scala-js/compare/sbt1

**Comment by sjrd** [comment]
Bunch of issues reported to sbt in the process:

* https://github.com/sbt/sbt/issues/2616
* https://github.com/sbt/sbt/issues/2617
* https://github.com/sbt/librarymanagement/issues/42
* https://github.com/sbt/zinc/issues/124

and critically:

* https://github.com/sbt/zinc/issues/125

**Comment by dwijnand** [comment]
You can assign this to me btw. I'm basically working on this and the leaf issues you've enumerated. :)

**Comment by sjrd** [comment]
Cool. I can't actually assign you on GitHub because you're not a member of the scala-js organization, but it's noted :)

**Comment by dwijnand** [comment]
All the issues in your checklist have been closed.

**Comment by sjrd** [comment]
Superseded by #3065 and #3069.
