### ISSUE TITLE
Better support for nested JavaScript classes

### ISSUE THREAD

**Issue by ebruchez** [scala-js/scala-js#2398]
Following [this Gitter question](https://gitter.im/scala-js/scala-js?at=573be45fe2996a5a42c95a92).

Here is an example of the original JavaScript:

``` js
var port = tessel.port.A;
var i2c = new port.I2C(slaveAddress)
```

Assume we have:

``` scala
trait Port extends js.Object {
  ...
}
```

We can use `js.Dynamic` to create an instance of class defined within another JavaScript object:

``` scala
val port: Port = ???
val i2c = js.Dynamic.newInstance(port.asInstanceOf[js.Dynamic].I2C)(DisplayI2CAddress)
```

But there is currently no way to simply express that there is a nested class. For example, the following doesn't compile:

``` scala
@js.native
trait Port extends js.Object {
  @js.native
  class I2C(address: Int) extends js.Object
}
```

As a workaround, I implemented the following:

``` scala
object Port {
  implicit class PortOps(val port: Port) extends AnyVal {
    def I2C(address: Int) =
      js.Dynamic.newInstance(port.asInstanceOf[js.Dynamic].I2C)(address)
  }
```

But it's a lot of boilerplate compared to just using a `@js.native` annotation.

**Comment by sjrd** [comment]
Fixed in 9e9883e4eb2f7e76e246d3fcf51e57bbeef45e42.
