### ISSUE TITLE
The pretransform for If nodes with one branch of type Nothing can be improved

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2453]
Take the beginning of the method `startTurn()` in the Reversi:
```scala
  def startTurn() {
    val (scoreWhite, scoreBlack) = computeScore()
    status.text(currentPlayer+"'s turn -- White: "+scoreWhite+
        " -- Black: "+scoreBlack)
    ...
  }
```
which contains the destructuring of a tuple. Currently, this produces unexpectedly bad JS code:
```js
$c_Lreversi_Reversi.prototype.startTurn__V = (function() {
  var x1 = this.computeScore__T2();
  if ((x1 !== null)) {
    var scoreWhite = x1.$$und1$mcI$sp__I();
    var scoreBlack = x1.$$und2$mcI$sp__I();
    var x$4_$_$$und1$f = null;
    var x$4_$_$$und2$f = null;
    var x$4_$_$$und1$mcI$sp$f = scoreWhite;
    var x$4_$_$$und2$mcI$sp$f = scoreBlack
  } else {
    var x$4_$_$$und1$f;
    var x$4_$_$$und2$f;
    var x$4_$_$$und1$mcI$sp$f;
    var x$4_$_$$und2$mcI$sp$f;
    throw new $c_s_MatchError().init___O(x1)
  };
  var scoreWhite$2 = x$4_$_$$und1$mcI$sp$f;
  var scoreBlack$2 = x$4_$_$$und2$mcI$sp$f;
  ...
});
```
If we look at the IR output by the *optimizer*, we can see what happens:
```scala
def startTurn__V() {
  val x$4: ($$und1$f: any, $$und2$f: any, $$und1$mcI$sp$f: int, $$und2$mcI$sp$f: int) = {
    val x1: T2 = this.computeScore__T2();
    if ((x1 !== null)) {
      val scoreWhite: int = x1.$$und1$mcI$sp__I();
      val scoreBlack: int = x1.$$und2$mcI$sp__I();
      ($$und1$f = null, $$und2$f = null, $$und1$mcI$sp$f = scoreWhite, $$und2$mcI$sp$f = scoreBlack)
    } else {
      throw new s_MatchError().init___O(x1)
    }
  };
  val scoreWhite$2: int = x$4.$$und1$mcI$sp$f;
  val scoreBlack$2: int = x$4.$$und2$mcI$sp$f;
  ...
}
```
Note how the tuple `x1` is first decomposed into `scoreWhite` and `scoreBlack` *if x1 is not null*, then recomposed back into another tuple, to be extracted again later! And *if it's null*, throw something. This apparent nonsense comes from how scalac desugars tuple destructuring, but that's not really my point.

The important point is that the second tuple *was reified as a record*. It's already much better than being allocated on the heap, of course, but it's still not perfect. At some point before reifying it as a record, it looks like this "in the optimizer's head":
```scala
def startTurn__V() {
  val x$4: T2 = {
    val x1: T2 = this.computeScore__T2();
    if ((x1 !== null)) {
      val scoreWhite: int = x1.$$und1$mcI$sp__I();
      val scoreBlack: int = x1.$$und2$mcI$sp__I();
      <virtual T2>($$und1$f = null, $$und2$f = null, $$und1$mcI$sp$f = scoreWhite, $$und2$mcI$sp$f = scoreBlack)
    } else {
      throw new s_MatchError().init___O(x1)
    }
  };
  val scoreWhite$2: int = x$4.$$und1$mcI$sp$f;
  val scoreBlack$2: int = x$4.$$und2$mcI$sp$f;
  ...
}
```
Unfortunately, in that situation, the virtual object *escapes from a branch of an `If`*. It's very cool that we can reify as a record (rather than allocating a heap object) for things like `if (x) (a, b) else (c, d)`, but in this case, it's non-optimal. The reason is that the `else` branch has type `NothingType`.

If you think about it for a second, that if/else can be rewritten as follows, precisely because the `else` branch has type `NothingType`:
```scala
  {
    if (!(x1 !== null)) { // note the inverted condition
      throw new s_MatchError().init___O(x1)
    };
    // note here: no else! the rest of the code follows through
    val scoreWhite: int = x1.$$und1$mcI$sp__I();
    val scoreBlack: int = x1.$$und2$mcI$sp__I();
    <virtual T2>($$und1$f = null, $$und2$f = null, $$und1$mcI$sp$f = scoreWhite, $$und2$mcI$sp$f = scoreBlack)
  }
```
Note how the virtual object does not escape from a branch of the `If` anymore. It "escapes" from a `{}` block, but that's no big deal, as it can stay a virtual object as the result of a `PreTransBlock`.

Thanks to the magic of `PreTransBlock` and `withNewLocalDef`, the above also rewrites as follows:
```scala
def startTurn__V() {
  val x1: T2 = this.computeScore__T2();
  if (!(x1 !== null)) {
    throw new s_MatchError().init___O(x1)
  };
  val scoreWhite: int = x1.$$und1$mcI$sp__I();
  val scoreBlack: int = x1.$$und2$mcI$sp__I();
  val x$4: T2 = <virtual T2>($$und1$f = null, $$und2$f = null, $$und1$mcI$sp$f = scoreWhite, $$und2$mcI$sp$f = scoreBlack);
  val scoreWhite$2: int = x$4.$$und1$mcI$sp$f;
  val scoreBlack$2: int = x$4.$$und2$mcI$sp$f;
  ...
}
```
And from there, the virtual object can completely disappear, giving:
```scala
def startTurn__V() {
  val x1: T2 = this.computeScore__T2();
  if ((x1 === null)) {
    throw new s_MatchError().init___O(x1)
  };
  val scoreWhite: int = x1.$$und1$mcI$sp__I();
  val scoreBlack: int = x1.$$und2$mcI$sp__I();
  val scoreWhite$2: int = scoreWhite;
  val scoreBlack$2: int = scoreBlack;
  ... // using scoreWhite$2 and scoreBlack$2
}
```
which can collapse through local val aliasing down to
```scala
def startTurn__V() {
  val x1: T2 = this.computeScore__T2();
  if ((x1 === null)) {
    throw new s_MatchError().init___O(x1)
  };
  val scoreWhite: int = x1.$$und1$mcI$sp__I();
  val scoreBlack: int = x1.$$und2$mcI$sp__I();
  ... // using scoreWhite and scoreBlack
}
```
And uh! Completely overhead- and boilerplate-free tuple extraction!

All of that thanks to a simple rewriting of `If` of which one of the branch has type `NothingType`! Everything else I described above is already supported by the optimizer :-D

**Comment by japgolly** [comment]
Regarding the lines
```scala
if ((x1 === null)) {
    throw new s_MatchError().init___O(x1)
  };
```
will setting `CheckedBehavior` to `Unchecked` in `scalaJSSemantics` omit this check?

**Comment by sjrd** [comment]
No, this is part of the semantics of pattern matching, which Scala.js observes. Note that it's not throwing an NPE, it's throwing a `MatchError`. `MatchError`s are well defined behavior, unlike NPEs.

**Comment by japgolly** [comment]
Ah ok. I was hoping to be able to turn it off for prod builds in order to reduce JS size.
