### ISSUE TITLE
Array.tabulate(2)(i => i) fails to compile.

### ISSUE THREAD

**Issue by nicolasstucki** [scala-js/scala-js#2465]
This is the bug that makes partest `run/vector1.scala` crash.

**Comment by nicolasstucki** [comment]
```scala
[error] ReferenceError: arg1 is not defined
[error]     at $c_Lhelloworld_HelloWorld$.main__V (/Users/nastucki/GitHub/scala-js/examples/helloworld/target/scala-2.11/file:/Users/nastucki/GitHub/scala-js/scalalib/overrides/scala/Array.scala:345:5)
[error]     at $c_Lhelloworld_HelloWorld$.$$js$exported$meth$main__O (/Users/nastucki/GitHub/scala-js/examples/helloworld/target/scala-2.11/file:/Users/nastucki/GitHub/scala-js/library/src/main/scala/scala/scalajs/js/JSApp.scala:18:4)
[error]     at $c_Lhelloworld_HelloWorld$.main (/Users/nastucki/GitHub/scala-js/examples/helloworld/target/scala-2.11/file:/Users/nastucki/GitHub/scala-js/examples/helloworld/HelloWorld.scala:11:8)
[error]     at Object.<anonymous> (/Users/nastucki/GitHub/scala-js/examples/helloworld/target/scala-2.11/helloworld-launcher.js:2:86)
[error]     at Module._compile (module.js:413:34)
[error]     at Object.Module._extensions..js (module.js:422:10)
[error]     at Module.load (module.js:357:32)
[error]     at Function.Module._load (module.js:314:12)
[error]     at Module.require (module.js:367:17)
[error]     at require (internal/module.js:16:19)
```

**Comment by nicolasstucki** [comment]
@sjrd do you have some idea if which commit could have introduced this issue?

**Comment by gzm0** [comment]
Does it fail to compile or run? This looks like a runtime failure.

**Comment by nicolasstucki** [comment]
I tried it in `run`.

**Comment by sjrd** [comment]
@nicolasstucki I cannot reproduce on master (8ceb36b074508dcc7bb6da39b71bf20c43b4f35e), neither in 2.11.8 nor 2.12.0-M4. Maybe it was fixed "by chance" by #2458, in which case that would probably be because of https://github.com/scala-js/scala-js/pull/2458/files#diff-ce37eb8d8b260a77d05f1532255f5d4bR3909, despite my understanding that it shouldn't have been a problem before.

**Comment by sjrd** [comment]
It's clearly a run-time error, but it can be considered as a JavaScript "compile" error, since it's using a variable that is not declared.

**Comment by nicolasstucki** [comment]
I rebased and it also works for me. `run/vector1.scala` also works after this fix.

**Comment by sjrd** [comment]
Yep, and if I checkout 438ffee909d0144570768c79f7b7d48d98a3f780, I can reproduce.
