### ISSUE TITLE
Support for Source.fromFile for Node.js runtime environment

### ISSUE THREAD

**Issue by mkotsbak** [scala-js/scala-js#2477]
[error] Referring to non-existent class java.io.File
[error]   called from scala.io.Source$.fromFile(java.lang.String,scala.io.Codec)scala.io.BufferedSource

As file reading is supported in Node.js, this should also be possible to do with SJS?

**Comment by sjrd** [comment]
Only if we assume that Scala.js code will only ever execute on Node.js, which is clearly not the case. So no, this is not possible.

**Comment by mkotsbak** [comment]
Maybe this could instead then be provided by some external node.js specific dependency that implements these classes, so that the user can add that dependency only if the target platform is node.js?

**Comment by sjrd** [comment]
Yes, that is a possibility, although it definitely does not belong in core. You could write such a library if you need it. You can take inspiration from scalajs-java-time for the build architecture.

**Comment by mkotsbak** [comment]
Ah, I see some work on that as part of this PR: https://github.com/scoverage/scalac-scoverage-plugin/pull/158 Maybe the File stuff there could be extracted to a library.
