### ISSUE TITLE
Explicit type in JSON.parse

### ISSUE THREAD

**Issue by lastsys** [scala-js/scala-js#2487]
A common pattern when parsing JSON-strings is to write:

``` scala
scala.scalajs.js.JSON.parse(jsonString).asInstanceOf[T]
```

where `T` is the `trait` or `class` which describes the JSON-structure.

IMHO, a better and shorter way of writing this would be:

``` scala
scala.scalajs.js.JSON.parse[T](jsonString)
```

to avoid explicit casts in the code. Also, `asInstanceOf` is quite verbose.

To avoid breaking binary compatibility, is it possible to have a default value for `T` in Scala?

**Comment by gzm0** [comment]
As already mentioned on the chat, I think this is a very reasonable idea but we need to figure out the compatibility details so that existing code calling `parse` doesn't just break.

**Comment by lastsys** [comment]
Yeah, just added: To avoid breaking binary compatibility, is it possible to have a default value for T in Scala?

**Comment by gzm0** [comment]
No, unfortunately not.

**Comment by lastsys** [comment]
Would this be helpful? http://stackoverflow.com/questions/29414121/default-value-for-type-parameter-in-scala

**Comment by lastsys** [comment]
In code I have written I have a function called `getObject[T <: js.Any]()` and it is possible to write
```scala
dom.console.log(getObject())
```
without specifying `T`. But the returned value has type `Nothing`. I guess `console.log` doesn't care about the type being `Nothing` since it is a JS-function.

**Comment by sjrd** [comment]
Even if I understand the convenience benefit, I don't think this is a good idea. It would imply that `parse` makes some sort of effort to ensure that a proper `T` is parsed, where in fact, it can return arbitrary results. And if `T` is a JS type (which it should be), that won't even cause an error but trickle further in the code.

It seems much safer to keep the current return type. The fact that you need an `asInstanceOf[T]` should be a good warning that the conversion is not safe. If you want a convenience unsafe method, it is easy to define one yourself.

**Comment by lastsys** [comment]
Well, any interaction with the JS-world cannot be verified to be correct until runtime.

**Comment by sjrd** [comment]
Sure, but in most cases, we can be careful *once*, when we define the facade types. If the facades are sound wrt to the library, then any usage of the facade will be correct. Here, you are proposing to change the facade in a way that the facade itself is not sound anymore. That means we can to be careful every time we use it.

**Comment by lastsys** [comment]
Ok. So it is a convention that if you write
```scala
def f[T](): T = ...
```
then you have to guarantee that you get a `T` and not an exception later on in the code.
I have been using this pattern a lot when writing a facade for OpenUI5 since almost everything I am fetching needs to be cast to the correct class. This suggests that in order to dare to guarantee the correct type the best practice when writing a facade could be to build a middle layer in order to get a nice interface without having to resort to `asInstanceOf` all the time.

**Comment by ritschwumm** [comment]
on a side note: when i read the title of this issue my first thought was someone wanted express that JSON.parse returns a _subset_ of what's allowed in JS in the result type. that might actually be useful...

**Comment by sjrd** [comment]
@ritschwumm I don't understand what you mean. Would you care to elaborate?

**Comment by ritschwumm** [comment]
@sjrd what i mean is that every JSON value is a JS value, but not the other way round. JSON.parse will never return a Function or a Regex, for example.

**Comment by sjrd** [comment]
OK. But (so far) we do not have a type that says "this is a JSON value". The best approximation is `Any`.

**Comment by gzm0** [comment]
Closing this as wontfix since there has been no discussion and there seems to be some sort of agreement that defining `JSON.parse` as generic is probably taking it too far.
