### ISSUE TITLE
Produce source maps that reference local .scala files instead of online ones

### ISSUE THREAD

**Issue by jatcwang** [scala-js/scala-js#2489]
**Was: Produce sourcemaps that can be used by 3rd party bundlers such as Webpack**

Currently scalajs links to online sources for code belonging to Scala standard libraries. 
This is problematic for 3rd party bundlers such as Webpack because they do not support including sourcemaps which are on the web.

I am currently authoring a JS library with Scala-js, intended to be be loaded in as a normal JS module by a Javascript-centric frontend through webpack. 

With the help of [source-map-loader](https://www.npmjs.com/package/source-map-loader) Webpack can consume 3rd party sourcemaps and make sure they are included in the final sourcemap bundle. However, I am getting errors like the following because scala-js is using weblinks to the sourcemap:

```
WARNING in ../projectname/js/dist/elasticorm/projectname-opt.js
Cannot find source file 'https://raw.githubusercontent.com/scala/scala/v2.11.8/src/library/scala/collection/generic/IterableForwarder.scala': Error: Cannot resolve 'file' or 'directory' ./https://raw.githubusercontent.com/scala/scala/v2.11.8/src/library/scala/collection/generic/IterableForwarder.scala in /Users/jtcwang/Development/skedulo/projectname/js/dist/projectname
```

This is related to #2276.

I think a good solution is to add a scala-js option to download the Scala std library sources locally and point to them instead of using the web link. I think this can be done without the user needing to perform the cloning themselves.

The relevant section of code for this issue I found `project/Build.scala`:

```
          scalacOptions += {
            "-P:scalajs:mapSourceURI:" +
            (artifactPath in fetchScalaSource).value.toURI +
            "->https://raw.githubusercontent.com/scala/scala/v" +
            scalaVersion.value + "/src/library/"
          }
```

I'm happy to contribute code for this, however I'll need some help to understand scala.js's build pipeline.

**Comment by sjrd** [comment]
There is something I don't understand. Why do these tools even *want* to download the source files referenced by source maps? They should be happy with URL and just copy over the URL in the generated combined source map, shouldn't they?

**Comment by jtcwang** [comment]
I think their idea is to have one source map file containing all the relevant sourcemaps for the whole bundle. I'm not familiar enough with how sourcemaps work to judge whether it's a technical difficulty or just not done

**Comment by sjrd** [comment]
One source *map*, yes, that makes sense. But for that they only need to look at the source map files, not the sources that are linked from there.

**Comment by jtcwang** [comment]
I don't disagree with you, but do you think providing an alternative to online sourcemaps would be beneficial? I can think of several cases

* Offline debugging
* Company with tight proxy policies
* Error tracker which doesn't support web sourcemaps
* Company that doesn't want to host their original source file which is accessible publicly

If we were to add an option for this, does it introduce significant complexity? Correct me if I'm wrong, but here's what I think needs to be done to get this working:

* Download the source files for the scala std lib version used
* Change the base path of the sourcemap to the location of the lib source

**Comment by solomatov** [comment]
+1
Is there any progress on this?

P.S. Concerning storing source maps in a global location, there's another hypothetical but important for long lived projects point. Imagine, somethings bad happens either to github or this project, what would happen to people who use the old version of scalajs? They just won't be able to use the tool.

**Comment by solomatov** [comment]
Also, integration with webpack is very important for real projects. It's the best module bundler out there, and making it work with scalajs either by contributing integration with external source maps or by generating source maps locally, might substantially increase the size of scala.js community.

**Comment by gzm0** [comment]
@sjrd Maybe we should propose a linker option to re-attach relative trees. Essentially like `mapSourceURI` for the compiler but for the linker. This would be a generalized version of `relativizeSourceMapBase`.

@solomatov @jtcwang That would essentially mean that you could configure the Scala.js linker to re-attach source-maps with a specific prefix (e.g. `https://raw.githubusercontent.com/scala-js/scala-js/v0.6.12/`) to a different path of your choice.
With this option, `https://raw.githubusercontent.com/scala-js/scala-js/v0.6.12/` would only serve as a:

- canonical "namespace" for Scala.js sourcemaps
- reasonable default

Many other use cases would probably benefit from that as well.
At this point, you can fetch the Scala.js source artifact via sbt, unpack it and use the unpacked location as a replacement. These steps can all be done in user build space, at least for the beginning. From there, either an additional plugin can be created by someone in the community or integration into the Scala.js base plugin can be discussed.

However, to get this to work in a fully automated fashion (i.e. `useLocalSources := true` and done), we need a way to discover the base paths used in a project and the artifacts they point to (or include maven coordinates in `.sjsir`, but I'm not sure we really want to do this).

Just as a note aside: The reason why this is more complicated than on the JVM, is that on the JVM it is entirely left to the debugging tool to discover where the source code lies. That is, in the bytecode, there is just the name of the source file:

> The string referenced by the sourcefile_index item will be interpreted as indicating the name of the source file from which this class file was compiled. It will not be interpreted as indicating the name of a directory containing the file or an absolute path name for the file; such platform-specific additional information must be supplied by the run-time interpreter or development tool at the time the file name is actually used.

Unfortunately, we do not have this option for source maps.

**Comment by jtcwang** [comment]
We manage to work around this problem by loading our scalajs code directly into the page with a `<script>` tag, and then using `external` option in webpack to expose the module to our javascript code. For anyone that need it now it's an ok solution to the problem.

However the fundamental issue is that currently you cannot debug beyond your own code unless the library you use specifically setup a path to its sourcemap (e.g. Scala.js std lib and Scalaz), but this requires a separate release process and the sourcemap you get may not equal to the actual source code you're running. Is it possible to bundle the sourcecode along with the scalajs class files? Would that work?

**Comment by sjrd** [comment]
I think what we need to do is basically do what IDEs do for the JVM. We can and should be a bit smarter, though. We could store in the IR the *relative* path of the source file wrt. the `src/main/scala` directory (or similar). We could then find the appropriate sources in the source jars fetched from Maven.

The approach is not without issues, though:

* The relative source file cannot be found reliably from within the scalac compiler plugin. We would have to give `-P` options to specify a list of containing directories wrt which trying to relativize paths.
* Unlike relative paths of .sjsir files in jars, nothing prevents several libraries to have the same relative paths of .scala files in their source jars. Disambiguating those cases is virtually impossible.

**Comment by solomatov** [comment]
>I think what we need to do is basically do what IDEs do for the JVM. We can and should be a bit smarter, though. We could store in the IR the relative path of the source file wrt. the src/main/scala directory (or similar). We could then find the appropriate sources in the source jars fetched from Maven.

This seems to be an excellent solution to me.

**Comment by DominikGuzei** [comment]
Any news on this issue? Im having the same issues with Parcel as it doesn't work with sourcemaps pointing to github urls.

**Comment by gzm0** [comment]
From what I can read from the conversation:
- We do not have a clear idea of how to actually make this work.
- No work has been done and AFAIK nobody actively works on this.

**Comment by DominikGuzei** [comment]
@gzm0 from what i could read in the conversation it would be sufficient to download the files from github into a folder (e.g right beside the scala.js output) and let the sourcemap point to these relative files on disc, right?

Im a senior frontend dev and i love Scala but to be honest the debugging experience / project setup story with Scala.js could be massively improved to make it more popular.

I can also dedicate some time to help out on this task, my problem is that the SBT dsl is quite complex for a beginner and i don't have a good idea on what could be a simple, pragmatic approach to this.

**Comment by gzm0** [comment]
> from what i could read in the conversation it would be sufficient to download the files from github into a folder (e.g right beside the scala.js output) and let the sourcemap point to these relative files on disc, right?

Yes. But how do you make all parts of the pipeline work together to provide this? The source map is generated by the linker (look for Emitter.scala), while downloading would have to be done by the build tool (sbt or other).

I'll happily review designs you have, but unfortunately I do not have time to dedicate to design this. If you need concrete sbt help, I'll also happily provide guidance. However, if you would like to help, you'll have to come up with a design yourself.

To get started, have a look in these spots:
- [Scala.js compilation pipeline][1]: How the parts fit together (shameless plug).
- [Position][2]: tree position generated by Scalac ([code that generates it][3]).
- [`JSTreePrinterWithSourceMap`][4]: Thing that writes these positions into a source map.

No post-processing of source maps is done in sbt at all.

HTH

[1]: https://www.youtube.com/watch?v=nRswfBJL0dQ
[2]: https://github.com/scala-js/scala-js/blob/master/ir/src/main/scala/org/scalajs/ir/Position.scala
[3]: https://github.com/scala-js/scala-js/blob/3474756e10f796aae10e98e75ea4b7805e31fee4/compiler/src/main/scala/org/scalajs/nscplugin/GenJSCode.scala#L85-L103
[4]: https://github.com/scala-js/scala-js/blob/master/linker/shared/src/main/scala/org/scalajs/linker/backend/javascript/Printers.scala#L618

**Comment by DominikGuzei** [comment]
@gzm0 couldn't that be done based on the generated sourcemap? Basically nothing would change except for the file paths to be relative on the local machine. It might not be the final / nicest solution in the long rung (since it would mean that first useless sourcemap is created only to be fixed by another build transformation) … but it would be the easiest to do right now, without any changes in the current linker / build.

**Comment by sjrd** [comment]
Yes, that's indeed a reasonable soa stop gap measure. It is even possible to implement completely outside of the core sbt plugin. It would be possible to prototype directly inside your own build, then ported to an sbt plugin for everyone to enjoy.

**Comment by DominikGuzei** [comment]
@sjrd @gzm0 i tried the approach i outlined above (downloading the sourcemap files and rewrite the mappings to local files) but it fails because some of wrong mapping URLs for some third party libraries like `slinky`. I only have a very small example app but i can imagine that this might fail for other packages the same way.

**Comment by gzm0** [comment]
Well, there is not really anything you can do if a package publishes bad source maps. You could ignore (i.e. not translate) things that fail to resolve or maybe provide an option.

> This also means that the currently generated sourcemaps can easily be broken without anyone noticing (until you try to debug your app) == not good.

They will only be broken for that app. If a publisher does not test their source maps, than this can happen. It's not really anything fundamentally different than broken code.

**Comment by sjrd** [comment]
Libraries are not really published with source maps per se, but they are published as compiled code, containing information about where each "instruction" maps to. The linker uses that information to construct source maps. If that information is broken, there's nothing that can be done.

**Comment by DominikGuzei** [comment]
Ok, that's pretty bad :( basically this means there is no reliable method of generating sourcemaps from Scala.

**Comment by DominikGuzei** [comment]
Yeah that's true … im coming from Javascript land where debugging (e.g: in Chrome dev tools) works really well in most cases. Im evaluating Scala.js as an alternative to typed Javascript (Flow.js) and so far only the debugging experience is really bothering me. It's not only the broken sourcemaps (online mappings) also the generated JS is not very friendly to inspect if necessary.

I totally get why you are optimistic 😉but Scala.js still feels pretty rough in terms of tooling, dev experience and documentation.

For me it's still interesting because i see Scala basically as a nicer Javascript with great type system, IDE tooling etc. (the languages feel very similar too, especially compared to typed js) … and the dream of using the same language everywhere.

**Comment by aappddeevv** [comment]
I'm not 100% sure I understand what this is fixing. Can't you just translate the sourcemaps using a js bundler/utility (like webpack) and handle this completely outside of sbt? I'm trying to figure out if there is something I should be doing that I am not aware of based on this issue.

**Comment by gzm0** [comment]
Closing this, because the previous post seems to have addressed the issue. Further, any project providing this as a library should almost certainly be outside of the core repo.

**Comment by aappddeevv** [comment]
I also wrote a scalajs-friendly-source-map-loader webpack loader that downloads the remote source maps as needed.  It’s up on npm. Looks like this may have more caching than the npm version though.
