### ISSUE TITLE
js.Dictionary object does not extend anything.

### ISSUE THREAD

**Issue by onlyNexusHere** [scala-js/scala-js#2492]
All other js objects defined in this folder extend some type of js.Any, Dictionary does not. It would be great if it did extend js.Any.
Thanks!

Note: Writing a program with a map from string to js.Any. Cannot put in Dictionary object.

**Comment by sjrd** [comment]
Hum ... Yes, it does. `js.Dictionary` extends `js.Any`.

**Comment by onlyNexusHere** [comment]
Yes, the trait Dictionary extends js.Any. The object in the same file does not extend js.Any. The other javascript objects in the js folder extend js.Any or js.Object.

**Comment by sjrd** [comment]
That's because there is no such thing as a global variable named `Dictionary` is JavaScript's native global scope. The `object Dictionary` there is a Scala construct that does not have any correspondence in JavaScript. So it must not extend `js.Any`.
