### ISSUE TITLE
Default sourcemap pathing should be relative

### ISSUE THREAD

**Issue by jtcwang** [scala-js/scala-js#2493]
When looking at the paths to sourcemaps for 3rd party libraries, I often see paths pointing to the library author's local file system:

```
file:///home/[library author's username]/src/[library name]src/main/path/to/some/scala/file.scala
```

and this obviously breaks if for example an exception is thrown inside a 3rd party library.

I think for privacy reasons relative paths should be the default?

**Comment by sjrd** [comment]
Relative paths are completely useless, because js files move around, but not the sources, including locally. So you wouldn't be able to debug the app or library that you're developing.

Publishing local file names is the problem, but we have no control over that. Scala.js has no idea whether you're compiling a release version or a local version. That's why you have to tell it.

**Comment by jtcwang** [comment]
Looking at Scalaz's build.sbt, it seems like they took the same approach as scala-js to point to web sourcemaps.

In an ideal world there will be an option to pull in library sources and generate sourcemaps based off that. This is necessary for offline development as well as writing JS libraries using scalajs (my current usecase).

So I think having some of the following options would be helpful:
* `sourcemapsFromLocalSources`

  * Pull down source files of any dependencies marked with `source()`, and generate sourcemaps using the source files. This will override the sourcemap settings of any 3rd party libraries marked with `sources()` and instead generate sourcemap links that are absolute in the user's file system.

* `skipLibrarySourcemaps`

  * Only generate sourcemaps for source files of this project. Ignore any 3rd party libraries or Scala's std library (this would've been helpful for us)

We've found a workaround which is equivalent to loading the scalajs generated JS file globally onto the page but still allow our published module to be versioned through NPM.

I'll go ahead and close this and this can be revisited if there are more demand.
