### ISSUE TITLE
Exports overload resolution creates multiple local vars with the same name

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2506]
Example in `ExportsTest.disambiguate_overloads_involving_longs`:

``` scala
  def "foo"(arg$1: any): any = {
    if (arg$1.isInstanceOf[jl_Integer]) {
      val prep0: int = arg$1.asInstanceOf[I];
      this.$$js$exported$meth$foo__I__O(prep0)
    } else if (arg$1.isInstanceOf[jl_Long]) {
      val prep0: long = arg$1.asInstanceOf[J];
      this.$$js$exported$meth$foo__J__O(prep0)
    } else {
      throw "No matching overload"
    }
  }
```

`prep0` is defined twice (in different scopes). This happens not to be an issue in practice, but it's still technically invalid.

Discovered while addressing #2498, of course ...

**Note**: When we fix this, we should also completely enforce uniqueness of local variable names per method (instead of non-overlapping scopes), as was the initial plan of #2498.

**Comment by gzm0** [comment]
You know, I'm really happy that my "we should test this" pedantry discovers stuff most of the time (means I can keep doing it without anyone being able to complain :P).

**Comment by gzm0** [comment]
I guess either second or third option. Probably the second option is OK, since it is unlikely that we will start optimizing exported methods, right?

**Comment by sjrd** [comment]
> since it is unlikely that we will start optimizing exported methods, right?

Not anytime soon, at least. Probably not before 1.0.0 anyway.

**Comment by sjrd** [comment]
I just about a fourth alternative, which might be much better: instead of asserting that variable names are used only once, we could check that variables with the same have non-overlapping scopes. For example, 
```scala
if (b) {
  var x = 5
} else {
  var x = 6
}
```
is fine, but
```scala
if (b) {
  var x = 5
  var x = 6
}
```
is not.

This is true even in exported methods, and is what is actually relied upon by the desugaring. The optimizer doesn't care (in fact it *fixes* the issue by assigning new names). The desugaring relies on non-overlapping scopes because it translates to Javascript vars, which have function scope. For performance it might be better to ensure uniqueness (avoiding the variable to be polymorphic for no reason) but for correctness non-overlapping is sufficient.

**Comment by gzm0** [comment]
Ah, nice :) Might be indeed a better option.
