### ISSUE TITLE
Missing mechanism to define a native Class without a absolute JSName

### ISSUE THREAD

**Issue by daenenk** [scala-js/scala-js#2510]
The example is the use of  the class `Graph` of the project `graphlib` (https://github.com/cpettitt/graphlib). I can define `graphlib` as a native object (using `@JSName` to bind it) and define the native class `Graph` inside.
~~~ scala
@JSName("graphlib")
@js.native
object graphlib extends js.Object {

  val version: String = js.native

  @js.native
  class Graph extends js.Object {

    def setGraph(obj: js.Object): Graph = js.native
    def setNode(id: js.Any, obj: js.Object): Graph = js.native
    def setEdge(from: js.Any, to: js.Any): Graph = js.native
    // . . .
  }
}
~~~

However I would prefer to define `graphlib` this as a `trait`, such that it can be used as a view for a dynamically loaded object as well, using `require` in node-js. Defining such view to access the object loaded with `require` is a approach that I saw in a few scala-js projects. But, with a class definition in the module, I don't find a way to define a proper wrapper. Inside a native `trait` no class can be defined, even not a native one.

**Comment by sjrd** [comment]
Duplicate of #2398?

**Comment by daenenk** [comment]
Indeed, closed as duplicate.
