### ISSUE TITLE
org.scalajs.testsuite.compiler.LongTest fails in Chrome 51.0.2704.79 (64-bit)

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#2518]
```
Test org.scalajs.testsuite.compiler.LongTest.times_$times failed: expected:<8> but was:<1>, took 0.00043 sec
```

**Comment by sjrd** [comment]
Hum ... Works just fine on Chrome 54.0.2793.0 canary (64-bit), Windows. As well as Firefox 47.0 64-bits.

**Comment by gzm0** [comment]
Hahahaha, probably an issue with the underlying v8 build. I have the impression, that this did work before. I'll bisect.

**Comment by gzm0** [comment]
I can confirm that this did work before. 2cbc11ade38737b0e6e1ded8715b091fa2f707b8 comes out as good.

**Comment by gzm0** [comment]
Uh oh... It is likely the commit we do not want it to be... Currently testing:
3b7be49d9cea88d8c58b5efd7f97965e1631e850 (Extract pretransformApply with PreTransforms in a separate method.)

1 revision left after...

**Comment by sjrd** [comment]
Works for me in Chrome 51.0.2704.106 m (non 64-bits, apparently) on Windows.

It is probably the result of transforming `-1L * x` into `0L - x` then inlining that implementation. In other words, I suspect this variant of the code:
```js
  var this$72 = $m_Lorg_junit_Assert$();
  var b$68 = this.hideFromOptimizer$1__p1__J__J(new $c_sjsr_RuntimeLong().init___I__I((-8), (-1)));
  var lo$68 = b$68.lo$2;
  var hi$68 = b$68.hi$2;
  var lo$69 = ((-lo$68) | 0);
  var hi$69 = ((lo$68 !== 0) ? (~hi$68) : ((-hi$68) | 0));
  this$72.assertEquals__T__O__O__V(null, new $c_sjsr_RuntimeLong().init___I__I(8, 0), new $c_sjsr_RuntimeLong().init___I__I(lo$69, hi$69));
```
which should have the following vanilla JS simplicification:
```js
var lo$68 = -8;
var hi$68 = -1;
var lo$69 = ((-lo$68) | 0);
var hi$69 = ((lo$68 !== 0) ? (~hi$68) : ((-hi$68) | 0));
console.log([lo$69, hi$69]); // should display [8, 0]
```
Could you try those instructions in the console of your browser?

**Comment by sjrd** [comment]
Note that [this](https://github.com/scala-js/scala-js/blob/5deb596515835c7a4e855cccc4f655e63a339e8f/test-suite/shared/src/test/scala/org/scalajs/testsuite/compiler/LongTest.scala#L92) is the only test in `times_*` where the `expected` result is `8L`.

**Comment by gzm0** [comment]
I will try this as soon as I get home. Note that I must have done a mistake bisecting or I became victim of sbt's halfway incremental compilation: The bad commit now seems to work just fine.

**Comment by gzm0** [comment]
Humm... I cannot reproduce this now. This worries me a bit, since it might mean we have introduced a binary incompatibility with the long folding...
Closing this, since it is unlikely that we'll find anything with reasonable effort.
