### ISSUE TITLE
js.Object accepted as reflectiveCall parameter, though not supported

### ISSUE THREAD

**Issue by daenenk** [scala-js/scala-js#2534]
ReflectiveCalls are not supported for a native object.
~~~ scala
// scala 
@JSExport
@JSExportAll
object Test {
  def foo(p : { val x: Double, val y: Double }): Double = p.x + p.y
}
~~~
~~~ js
// js
Test().foo( { x:1, y:2 } ); // error
~~~
does not work; which is a pity, but anyway.

The following however does compile:
~~~ scala
// scala
@js.native
trait P extends js.Object {
  val x: Double = js.native
  val y: Double = js.native
}

@JSExport
@JSExportAll
object Test {
  def foo(p : { val x: Double, val y: Double }): Double = p.x + p.y
  def bar1(p: P): Double = foo(p) 
  def bar2(p: P): Double =  p.x + p.y
}
~~~
while the result in js 
~~~ js
// js
Test().bar1( { x:1, y:2 } ); // error
Test().bar2( { x:1, y:2 } ); // OK
~~~

The error is expected, given the fact that such reflective calls from js are not supported, but then a compiler error should be raised in the definition of `bar1`.

**Comment by sjrd** [comment]
I agree that it would be nice to have a compile error in `bar1` in an ideal world. But that would require changing the Scala type checker, and we cannot do this. So I'm afraid this is a Won't Fix.

**Comment by gzm0** [comment]
Couldn't we have an adaptation checker phase similar to (but much simpler) erasure that checks if a `js.Any` is used as a structural type?

**Comment by sjrd** [comment]
In theory, yes. In practice, this requires to rewrite a type checker for all possible scalac trees before erasure. This would be a huge undertaking, and a nightmare to maintain, especially for several versions of Scala at the same time. It would also likely add a significant compile-time cost, due to having to redo all the subtyping checks in the entire program one more time.

**Comment by gzm0** [comment]
Fair enough. But we don't need to do full subtyping checks, right? All we need to check is if we have something with `isStructuralRefinement` that is assigned to from something that `isJSType`...
Of course doing this in a generic context is **very** hard (and sometimes things will indeed just slip).

I agree that it is probably not worth the cost to implement this.
