### ISSUE TITLE
Make changing a JS Module to a Raw JS type a binary compatible change

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#2552]
Currently, we directly emit the access on the global when we emit an access to a Raw JS module. If we access a Scala.js defined JS Module, we emit a `LoadJSModule` tree. Further, raw js module classes do not emit their `jsName` into the IR. We should:

- Emit the `jsName` of the module into the IR.
- Emit a `LoadJSModule` irrespective of the module type.
- Defer replacing the `LoadJSModule` to the linking stage.

This will allow to change the representation of a JS module under the hood (native, Scala.js defined or ES6 module).

Since old versions of the IR do not emit the name for a JS module, we can only do this in a major version.

**Comment by sjrd** [comment]
Actually we can do this earlier at least for newly compiled native JS modules. And we also *need* to do it to generalize to ES6 modules, so we need to move the timetable earlier than 1.0.0. I have a pending fix in my branch for ES6 modules https://github.com/scala-js/scala-js/compare/master...sjrd:modules

**Comment by gzm0** [comment]
Ah, nice! I have been building the same for ES6 modules :P Although I didn't go through the pain to actually make it binary compat.

I'll adapt my work to this, once you are done.

**Comment by sjrd** [comment]
I'm done for the week, at least. I spent some time this week-end working on ES6 module support, and figured I had to get this issue over with beforehad. But for the next 6 days I won't be able to work on it any further, because I have to review papers + make the camera ready of the incremental optimizer paper. So if you want to take my branch from there, feel free to do so.

**Comment by gzm0** [comment]
Nah, will be busy with day job :) So just go ahead on this one. You'll be faster. But we should probably coordinate on ES6 module support, since we at least temporarily will need a JS bundler to be able to test it... (Unless you found a VM that supports them).
