### ISSUE TITLE
Constructing a String from a large byte array throws "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by jimmydivvy** [scala-js/scala-js#2553]
When constructing a string from a large buffer, the Javascript runtime will fail for large byte arrays. (125,056 bytes in V8/Chrome, 500,000 bytes in Firefox).

The culprit appears to be in RuntimeString.scala :: newString (https://github.com/scala-js/scala-js/blob/7441caa9727285f81428a6afab04d524df848b2c/library/src/main/scala/scala/scalajs/runtime/RuntimeString.scala#L309

In particular, line `309` 

    fromCharCode(charCodes: _*)

This translates to Javascript as 

    jsx$2.fromCharCode.apply(jsx$2, charCodes);

In Summary - It's calling `fromCharCode` with each byte in the array being passed as a separate parameter to the function. So constructing a string with `Array[Byte](1,2,3,4,5)` is essentially calling `String.fromCharCode(1,2,3,4,5)`

Unfortunately, Javascript has a limit on the number of arguments that can be passed to a function (See https://mathiasbynens.be/demo/javascript-argument-count), putting a hard limit on the number of bytes that can be decoded.

Example Scala Code to replicate.

    val buffer = Array.fill[Byte](1000000)('x')
    val str = new String(buffer, "UTF-8")

**Comment by gzm0** [comment]
Are you able to construct a string of that size in any of these JS runtimes any other way? Otherwise I hardly see what we can do about it.

**Comment by sjrd** [comment]
Well we *could* split the byte array in chunks of 1k elements (or some more appropriate value), build strings for those chunks separately, then concatenate the strings. But that seems quite involved.

**Comment by jimmydivvy** [comment]
> Are you able to construct a string of that size in any of these JS runtimes any other way?

Certainly. The problem has nothing to do with strings. As a contrived example this works perfectly well, for example. 

    var str = "";
    for( x=0; x<100000; x++) str += "x";

The problem is that you cannot pass more than 125,000 arguments to a function in Javascript, not that JS Strings have a specific limit. 

The simplest solution that comes to mind is to chunk the calls to `fromCharCode`. It may also be possible to use the Encoding API with ArrayBuffers to do this far more efficiently, although it would still need a fallback since that's not supported across all browsers at this point.

**Comment by jimmydivvy** [comment]
(On that note, what's the ScalaJS teams position on using experimental APIs? I can throw together a pull-request that uses the Encoding API with a fallback if there's some consensus on it being an acceptable approach)

https://developers.google.com/web/updates/2014/08/Easier-ArrayBuffer-String-conversion-with-the-Encoding-API

**Comment by jtcwang** [comment]
There's a similar issue with making a string from an array of codepoints (Ints) too.

```
def newString(codePoints: Array[Int], offset: Int, count: Int): String
```

**Comment by sjrd** [comment]
> On that note, what's the ScalaJS teams position on using experimental APIs?

For core, only standard ECMAScript is allowed. The Encoding API is a Web API, not an ECMAScript one, so it's definitely off-limit.
