### ISSUE TITLE
firstElementChild always returns undefined

### ISSUE THREAD

**Issue by Narigo** [scala-js/scala-js#2557]
The following test shows the issue I'm facing right now. While the `div` should always be an `Element`, the first (and only) child of `container`, the `firstElementChild` does not return it.

```scala
val container = dom.document.createElement("div")
val div = dom.document.createElement("div")
container.appendChild(div)
dom.console.log("container", container)
dom.console.log("container.firstChild", container.firstChild)
assert(container == container)
assert(div == container.firstChild)
assert(div == container.firstChild.asInstanceOf[dom.Element])

dom.console.log("container.firstElementChild", container.firstElementChild)
// yields org.mozilla.javascript.Undefined@30b8f383 -> assert(div == container.firstElementChild) throws
```

**Comment by ochrons** [comment]
When I run this in ScalaFiddle, it works just fine (both Chrome and Firefox). In what environment are you testing this?

**Comment by Narigo** [comment]
I have this as code in a Scala project. Does the [`build.sbt`](https://github.com/Narigo/scalajs-fun/blob/29af4054e99b1b2c586dc2f61f0c88843b821a00/build.sbt) with the dependencies suffice ?
Here is [an example test](https://github.com/Narigo/scalajs-fun/blob/29af4054e99b1b2c586dc2f61f0c88843b821a00/src/test/scala/com/campudus/scycle/vdom/VirtualDomTest.scala#L10-L23)

I guess then I'm just missing some dependencies or something like the `jsDependencies += RuntimeDOM` line in `build.sbt`...?

**Comment by ochrons** [comment]
Are the tests running on PhantomJS then? It's not really a full browser environment and you may encounter some inconsistencies. Also you should update to the latest DOM library 0.9.1

**Comment by Narigo** [comment]
I guess I'm using Rhino then, as I can't remember setting up anything like NodeJS or PhantomJS in ScalaJS context.

So Rhino is not only slow but generally not really working?
I have NodeJS installed, but it tries to run PhantomJS if I use `set scalaJSUseRhino in Global := false` as explained in [the documentation](http://www.scala-js.org/tutorial/basic/#run-with-nodejs-optional-but-recommended).
Do I need PhantomJS? Can I use Chrome or Firefox engines? I've used karma-chrome in NodeJS land...

**Comment by ochrons** [comment]
Version 0.6.10 introduced [HTML test runners](http://www.scala-js.org/news/2016/06/17/announcing-scalajs-0.6.10/) that run the tests in real browsers, which is probably what your would want for tests like these.

**Comment by ochrons** [comment]
In this case Rhino is not at fault, but the dummy DOM implementation that is being used with Rhino. It's more of a mock-up than a real DOM implementation, just to provide a rudimentary DOM API.

**Comment by Narigo** [comment]
Thanks a lot @ochrons - after installing PhantomJS (`npm i -g phantomjs`) and `set scalaJSUseRhino in Global := false`, the errors in sbt went away. Using the test runner works as well with Chrome. Sorry for the noise in the issues here, I was under the impression that there was a lot less to set up initially to use / test everything... ;)
