### ISSUE TITLE
Throwable constructor with Throwable not in spec.

### ISSUE THREAD

**Issue by andreaTP** [scala-js/scala-js#2559]
just to report...
https://github.com/scala-js/scala-js/blob/master/javalanglib/src/main/scala/java/lang/Throwables.scala#L330

in javadocs I read 
```Constructs a new exception with the specified cause and a detail message of (cause==null ? null : cause.toString()) (which typically contains the class and detail message of cause).```
https://docs.oracle.com/javase/7/docs/api/java/lang/ReflectiveOperationException.html#ReflectiveOperationException(java.lang.Throwable)

that is not the case.

**Comment by nicolasstucki** [comment]
The issue is actually with all the `Throwable`s.
