### ISSUE TITLE
java.util.Date.toString() result is missing dd part

### ISSUE THREAD

**Issue by gigiyy** [scala-js/scala-js#2565]
just to report, according to 
http://docs.oracle.com/javase/7/docs/api/java/util/Date.html#toString()

> Converts this Date object to a String of the form:
>  dow mon dd hh:mm:ss zzz yyyy

but the  implementation is missing the `dd` part:
 https://github.com/scala-js/scala-js/blob/master/javalib/src/main/scala/java/util/Date.scala#L119

**Comment by sjrd** [comment]
Duh. Thanks for the report.
