### ISSUE TITLE
Make scalaJSUseRhino := false by default

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2579]
The only reason we have `scalaJSUseRhino := true` by default is the out-of-the-box experience. We've always wanted to say: hey, you don't *need* to install anything but sbt, and Scala.js just works.

But, in practice, no one keeps using Rhino. Everyone installs Node.js and rolls with it. So the "default" build includes `scalaJSUseRhino in Global := false` anyway. Besides, sometimes beginners are baffled by how slow Scala.js is, and at some point veterans realize they're still using Rhino, and tell them not to.

I believe it would do everyone a favor to disable Rhino by default. Yes, our tutorial should then say that users need to install Node.js by default, but that is what every reasonable Scala.js user does anyway.

Note: this only affects users who actually use the `run` and/or `test` tasks from sbt.

**Comment by gzm0** [comment]
Ok, works for me. But what do we need Rhino for at all in this case? Maintaining the hooks in the linker for Rhino's lazy loading to work is quite some overhead (and for example sanitizing the Emitter phase might be more complicated as well).

Is actually anyone using Rhino except for toy projects?

**Comment by andreaTP** [comment]
Probably you can also try to download and install node on-the-fly using Sbt?

**Comment by sjrd** [comment]
Well at least in 0.6.x we need it for backwards compatibility.

We could consider removing it entirely in 1.0.0, indeed. So we should even deprecate `scalaJSUseRhino` as well as the Rhino JS env.

Note that currently there's at least one place where we use Rhino: in the Scala community build. We did that because it was easier to set up. We should make sure we can get Lightbend top install a recent enough version of Node.js on the community build machines.

**Comment by sjrd** [comment]
> Probably you can also try to download and install node on-the-fly using Sbt?

We considered that a long time ago but had quickly dismissed it, because that would require a lot a system-dependent logic in the sbt plugin, and we do not have the expertise nor the wish to implement and maintain such a thing.

**Comment by andreaTP** [comment]
System dependent code is limited to choose between the versions listed here: https://nodejs.org/en/download/

You can also consider a "best effort" approach where you try to download and execute the standalone package and if it doesn't work just display an error...

**Comment by gzm0** [comment]
Maybe this?
![Universal Installer](http://imgs.xkcd.com/comics/universal_install_script.png)

**Comment by sjrd** [comment]
Ah ah! Good one :P

I'd rather just tell people: you need to install Node.js, maybe give the website download URL, and let them do it. Anyway, they also have to install sbt to begin with (and a a JRE), so it's not like we're changing from 0 dependency to at least one.

**Comment by gzm0** [comment]
Yeah, I agree. So we'd say:

- Set `scalaJSUseRhino := false` by default
- Deprecate `scalaJSUseRhino` <br/>
    I would do this in any case, since the setting does not make an awful lot of sense if it is not `true` by default. We can move it to a setting of our build if we still need Rhino in CI.
- Consider deprecating `RhinoJSEnv` (depending on how much users scream and whether we can make the community build work).

**Comment by sjrd** [comment]
Sounds good to me.

> I would do this in any case, since the setting does not make an awful lot of sense if it is not true by default.

Good point.
