### ISSUE TITLE
Use JSDOMNodeJSEnv by default when requestsDOM is true (instead of PhantomJS)

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2583]
Since we're breaking defaults around JS envs anyway (#2579), maybe we should consider switching the default JS env when `requestsDOM` is true to be `JSDOMNodeJSEnv` instead of `PhantomJSEnv`.

I don't know whether the jsdom env has been seriously adopted so far. But we definitely know that [PhantomJS is unnerving people](https://github.com/scala-js/scala-js/issues/1881) who actually try to use it. Switching to jsdom by default will probably have a positive net result. For people who still prefer PhantomJS, it's a one-line config to enable it back:
```scala
jsEnv := PhantomJSEnv().value
```
Hopefully, in 1.0.0 we can move `PhantomJSEnv` out of core, like `SeleniumJSEnv`. With the removal of `RhinoJSEnv` altogether, that would leave us with only Node.js-based envs (with and without jsdom) in core, which would be nice.

**Comment by jducoeur** [comment]
:+1:  I was a serious Phantom aficionado in my early days of using Scala.js, but was driven away from it by the many-months-long chaos surrounding the 2.x Linux release.  And if jsdom on Node is reasonably reliable at this point (IIRC it was iffy when I looked at it, but that was long ago), then I agree that standardizing on one non-browser platform would be smart...
