### ISSUE TITLE
BigDecimal is not distributive

### ISSUE THREAD

**Issue by non** [scala-js/scala-js#2587]
It seems like there's a bug in the `BigDecimal` implementation, possibly related to the fact that `Int.MinValue` equals `-Int.MinValue`:

``` scala
object TestCase extends scala.scalajs.js.JSApp {
  def main(): Unit = {
    val x = BigDecimal(Int.MinValue)
    println(x * (x + x))
    println(x * x + x * x)
  }
}
```

Here's the output:

> -9223372036854775808
> 9223372036854775808

(The correct answer is `9223372036854775808`.)

This is using Scala 2.11.8 and Scala.js 0.6.11.

**Comment by sjrd** [comment]
Thanks for the report. I'll try to have a look into it when I get some time. I've never ventured into the implementation of `BigDecimal`, so this is going to be fun ^^

**Comment by non** [comment]
@sjrd I can try to take a look too -- I don't have as much scala.js experience but I've worked with a bunch of number types in the past.

**Comment by non** [comment]
I think I've located the problem: https://github.com/scala-js/scala-js/blob/master/javalib/src/main/scala/java/math/BigDecimal.scala#L677

The problem here is that there's exactly one case where the bit lengths are < 64 but the multiplication is unsafe: when both integers are `MinValue`.

Here's an ugly implementation that I think has a better chance of working:

```scala
  def multiply(multiplicand: BigDecimal): BigDecimal = {
    val newScale = this._scale.toLong + multiplicand._scale
    if (this.isZero || multiplicand.isZero) {
      zeroScaledBy(newScale)
    } else if (this._bitLength + multiplicand._bitLength >= 64 ||
          this._smallValue == Int.MinValue && multiplicand._smallValue == Int.MinValue) {
      val unscaled = this.getUnscaledValue.multiply(multiplicand.getUnscaledValue)
      new BigDecimal(unscaled, safeLongToInt(newScale))
    } else {
      valueOf(this._smallValue * multiplicand._smallValue, safeLongToInt(newScale))
    }
  }
```

**Comment by sjrd** [comment]
Ah! Indeed, that looks plausible. If you get around to submit a PR, that would awesome :D Otherwise I'll try that fix tomorrow.

**Comment by non** [comment]
Ok I'll do it.
