### ISSUE TITLE
Move java.io.DataInputStream to javalib

### ISSUE THREAD

**Issue by andreaTP** [scala-js/scala-js#2595]
It should be trivial, I hope in help from somebody :-)
Asking because it is a prerequisite to have Akka Typed link on Scala.Js.

**Comment by sjrd** [comment]
It is already available in `"org.scala-js" %% "scalajs-javalib-ex" % scalaJSVersion.value`: https://github.com/scala-js/scala-js/blob/master/javalib-ex/src/main/scala/java/io/DataInputStream.scala

**Comment by andreaTP** [comment]
Thant's great! 
Does the rationale to have a separate ```javalib-ex``` is that it uses ECMA 6 ?

**Comment by gzm0** [comment]
Yes. Be aware that some stuff in there also pulls in some other JS dependencies. (`JSZip` if I recall correctly).

**Comment by sjrd** [comment]
I think we should review the implementation of `DataInputStream` and move it to `javalib/`. We now have the tools needed to implement it correctly even when typed arrays are not there, specifically the polyfills for `Double.longBits2Double` and friends.

**Comment by gzm0** [comment]
Yeah, agree.

**Comment by andreaTP** [comment]
:+1:
