### ISSUE TITLE
Code ported from JUnit under EPL 1.0 license?

### ISSUE THREAD

**Issue by sgustafsson** [scala-js/scala-js#2609]
I noticed that there are several files markes as "Ported from https://github.com/junit-team/junit". Wouldn't this port make those files a derivative work of Junit, and hence the requirements of Junit's declared license - Eclipse Public License 1.0 - would apply?

**Comment by gzm0** [comment]
Fixed in 82e87d973c592e6507788910283273f965bdfc96
