### ISSUE TITLE
Porting java.util.Timer

### ISSUE THREAD

**Issue by axel22** [scala-js/scala-js#2610]
It seems like it should not be too hard to port `java.util.Timer` and `java.util.TimerTask` to `javalib`.

Is this planned? Do you accept contributions?

**Comment by sjrd** [comment]
We certainly accept contributions, as long as they follow [the rules](https://github.com/scala-js/scala-js/blob/master/CONTRIBUTING.md) :)

**Comment by sjrd** [comment]
Implemented in #2614.
