### ISSUE TITLE
Outer pointer checks fail in 2.12

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#2625]
Take the following:

```scala
class A {
  def call() = f(Foo.B(1))

  private def f(x: Foo) = x match {
    case Foo.B(x) => println(x)
  }

  sealed abstract class Foo

  object Foo {
    case class B(x: Int) extends Foo
  }
}

object HelloWorld extends js.JSApp {
  def main() {
    (new A).call()
  }
}
```

This will fail with a `MatchError` in 2.12.0-RC1, but works as expected (prints 1) in 2.11.8.

**Comment by gzm0** [comment]
Potentially related to #2382.

**Comment by gzm0** [comment]
This also works in 2.10.6

**Comment by gzm0** [comment]
Suspicion of relation to #2382 is confirmed: Both `A#Foo` and `A#Foo.B` get a field `$$outer$f`. But they do not refer to the same outer class.

Open questions:
- Why does the IR checker not catch this (both field collision and type mismatch)?
- Why does this change in 2.12?

**Comment by gzm0** [comment]
> Why does the IR checker not catch this (both field collision and type mismatch)?

- The IR checker does not check for field collisions (should it?)
- There is no type mismatch, since each class' constructor assigns to its own field.

**Comment by gzm0** [comment]
The problem seems not to be the outer pointer name clash (that was already present in 2.11), but that 2.12 starts actually checking the outer pointers in the pattern matches.

**Comment by sjrd** [comment]
> The IR checker does not check for field collisions (should it?)

It definitely should, but due to the existence of #2382 we cannot enable such a check right now :(

**Comment by sjrd** [comment]
This bug is extremely concerning :s We might not be able to fix it without fixing #2382, but we cannot fix #2382 without breaking binary compat.

Maybe we could fix #2382 only for 2.12.0-RC2 onwards? Since Scala versions are not binary compatible anyway, we can take a leap in backward compat with RC2 without affecting the ecosystem. That would solve the present issue.

**Comment by gzm0** [comment]
Yes. I thought about this as well. I think it is the only choice we have. And at second thought not such a bad one. It will allow us to "roll out" the fix to #2382 "gradually". So if we really mess it up, we get another chance for 1.0.0.

**Comment by gzm0** [comment]
/ping @adriaanm Just to double check that the Scala team is aware of the change in pattern matching behavior in this case. (It seems like a bug fix to me, so nothing alarming, but safety first :)).

**Comment by sjrd** [comment]
> I think it is the only choice we have.

I'll get to it right away, then. Because RC2 is basically about to be released, and I'd like not to roll such a change for 2.12.0 final without having tried with RC2.

**Comment by gzm0** [comment]
Yep :S

**Comment by gzm0** [comment]
Filed field collisions IR checking as #2627.

**Comment by sjrd** [comment]
And with that scenario, we basically *must not* release 0.6.12 for 2.12.0-RC2. So we must be *real fast* on getting 0.6.13 out the door right now. In that case, I'd only consider the following other PRs for 0.6.13:

* #2620: quite important, as the change with `@JSGlobalScope` will be slightly harder to do binary-compat-wise if it does not come in the same release as the introduction of `jsNativeLoadSpec`.
* #2621: less important, but it would be nice to bundle this non-forward-compat change in the same release as the other changes. Will depend on whether it's ready.

Anything else will have to wait for the next release.

**Comment by adriaanm** [comment]
Thanks for the ping! I'll take a look today.

**Comment by adriaanm** [comment]
Yes, the change to check the outer ref LGTM -- was fixed by https://github.com/scala/scala/pull/4974 (see also https://github.com/scala/scala/pull/4265 for an interesting test)
