### ISSUE TITLE
custom exception 

### ISSUE THREAD

**Issue by glipka** [scala-js/scala-js#2637]
Hi  

I would like to throw an custom javascript exception  
The exception name must be  SubmissionError ( a  native javascript class) 

Code : 
@js.native
@JSName("SubmissionError")
class SubmissionError(val error: js.Dynamic) extends Exception with js.Any 

But class Exception does not extend js.Any  

Any Idea to declare SubmissionError as Exception and native javascript class ? 

Best regards

**Comment by sjrd** [comment]
Hello, 

Thanks for your interest. GitHub issues are reserved for actual bugs and feature requests. Usage questions should be asked [on StackOverflow](http://stackoverflow.com/questions/tagged/scala.js). Please repost your question there and I will answer.
