### ISSUE TITLE
ThisFunction passing Scala-this instead of JS-this when using Scala 2.12.0

### ISSUE THREAD

**Issue by shogowada** [scala-js/scala-js#2643]
I have a code like this, and the ```foo``` function gets called from native JavaScript:
```scala
js.Dynamic.literal(
  "foo" -> js.ThisFunction.fromFunction1((that: js.Dynamic) => {
    foo(that)
  })
)
```

With Scala 2.11.8 and Scala JS 0.6.13, it compiles down to the following and JS-this is properly passed to the ```ThisFunction```.
```scala
"foo": (function(f$1) {
  return (function() {
    return f$1.apply__O__O(this)
  })
})
```

However, with Scala 2.12.0 and Scala JS 0.6.13, it compiles down to the following, and ```this``` is being Scala-this instead of JS-this:
```scala
"foo": (function(f$1) {
  return (function() {
    return f$1.apply__O__O($thiz)
  })
})
```

Only difference between the 2 builds are Scala version (2.11.8 vs. 2.12.0), so I am assuming that's the cause.

Let me know if you need some additional information.

**Comment by sjrd** [comment]
Thank you for the bug report. I will have a look at it the coming week. I haven't tried to reproduce yet, but it looks like a genuine bug. I am baffled that nothing in our test suite caught that :-s

**Comment by shogowada** [comment]
It took me a while to figure out conditions to reproduce it, but here is the test that fails on 2.12 but succeeds on 2.11.

```scala
import org.scalatest.path

import scala.scalajs.js

class ThisFunctionTest extends path.FunSpec {

  override def newInstance = new ThisFunctionTest

  describe("calling ThisFunction") {
    var maybeActualThis: Option[js.Any] = None

    trait FooFactory {
      def create = js.Dynamic.literal(
        "bar" -> js.ThisFunction.fromFunction1((passedThis: js.Dynamic) => {
          maybeActualThis = Option(passedThis)
        })
      )
    }
    class FooFactoryImpl extends FooFactory
    val fooFactory = new FooFactoryImpl()
    val foo = fooFactory.create

    val expectedThis: js.Any = "baz"
    foo.bar.call(expectedThis)

    it("should pass JS 'this' to the function") {
      assert(maybeActualThis == Option(expectedThis))
    }

    it("should not pass Scala `this` to the function") {
      assert(maybeActualThis != Option(fooFactory))
    }
  }
}
```

I could reproduce it only if:

- I had a trait that creates some JS object with ```ThisFunction```,
- I had a class that extends the trait,
- I created the JS object via the class, and
- I called the ```ThisFunction``` with custom ```this```.

so I am not surprised tests didn't catch this 😐

**Comment by sjrd** [comment]
Reproduced and identified the issue.
