### ISSUE TITLE
Nightly fails: Could not fetch scala-library sources for version 2.10.5

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#2649]
Related to: #2606?

**Comment by gzm0** [comment]
Note that the last weekly has also failed, but the failure seems spurious and unrelated (pos test failure, not the same failures in the two runs).

**Comment by sjrd** [comment]
Well Weekly doesn't run any 2.10.x job. So since the bug is 2.10.5-specific, it wouldn't affect Weekly.

Maybe there was a bug in the published POMs of 2.10.5?

**Comment by sjrd** [comment]
https://github.com/scala-js/scala-js/pull/2606#issuecomment-249429553

@gzm0:

> I take it we do not need to run a nightly?

@sjrd:

> No, there's no reason to. The important thing was to check that it could be resolved for every Scala version. So we just needed 1 arbitrary job per Scala version to run.

/me feels very stupid right now :s

**Comment by sjrd** [comment]
Unpopular suggestion: should we remove 2.10.5 from the nightly build until we find a solution? (caveat: we might not take this seriously enough and not actually look for a solution)

Possibly more popular suggestion: should we revert to the old scheme of resolving the library specifically for 2.10.5? (quirky, but does not compromise on test coverage)

**Comment by gzm0** [comment]
I have been looking through this over the weekend a bit and the behavior is *very* strange. So just to start with: 2.10.5 is not any different on maven than any other scala version. So it's unlikely a bug there; in fact, the resolution and download of the source package seems to work fine. The exception comes from our own build.

```scala
val scalaLibSourcesJar = report.select(
    configuration = Set("compile"),
    module = moduleFilter(name = "scala-library"),
    artifact = artifactFilter(classifier = "sources")).headOption.getOrElse {
  sys.error(s"Could not fetch scala-library sources for version $ver")
}
```

This suggests that either of the following:

- The artifact filter is wrong
- The sources do not appear in the update report.

Inspecting the update report for 2.11.8 and 2.10.5 seems fine:

```
> ++2.11.8
> show scalalib/update
[info] Updating {file:/Users/tschlatt/20p/scala-js/}scalalib...
[info] Resolving org.eclipse.jetty#jetty-continuation;8.1.16.v20140903 ...
[info] Done updating.
[info] Update report:
[info] 	Resolve time: 448 ms, Download time: 16 ms, Download size: 0 bytes
[info] 	compile:
[info] 	org.scala-lang:scala-library
[info] 		- 2.11.8
[info] 			(Artifact(scala-library,jar,jar,None,ArraySeq(),None,Map()),~/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.8.jar)
[info] 			(Artifact(scala-library,jar,jar,Some(sources),ArraySeq(),None,Map()),~/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.8-sources.jar)
[info] 			status: release
[info] 			publicationDate: Fri Mar 04 16:26:33 CET 2016
[info] 			resolver: sbt-chain
[info] 			artifactResolver: sbt-chain
[info] 			evicted: false
[info] 			homepage: http://www.scala-lang.org/
[info] 			textraAttributes: Map(info.apiURL -> http://www.scala-lang.org/api/2.11.8/)
[info] 			isDefault: false
[info] 			configurations: default, compile, runtime, default(compile), master
[info] 			licenses: (BSD 3-Clause,Some(http://www.scala-lang.org/license.html))
[info] 			callers: org.scala-js:scala-library-for-scalajs_2.11:0.6.14-SNAPSHOT ()
// snip
[success] Total time: 1 s, completed Nov 13, 2016 10:15:48 PM
```

```
> ++2.10.5
> show scalalib/update
[info] Updating {file:/Users/tschlatt/20p/scala-js/}scalalib...
[info] Resolving org.eclipse.jetty#jetty-continuation;8.1.16.v20140903 ...
[info] Done updating.
[info] Update report:
[info] 	Resolve time: 198 ms, Download time: 7 ms, Download size: 0 bytes
[info] 	compile:
[info] 	org.scala-lang:scala-library
[info] 		- 2.10.5
[info] 			(Artifact(scala-library,jar,jar,Some(sources),ArraySeq(),None,Map()),~/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.10.5-sources.jar)
[info] 			(Artifact(scala-library,jar,jar,None,ArraySeq(),None,Map()),~/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.10.5.jar)
[info] 			status: release
[info] 			publicationDate: Fri Feb 27 02:54:00 CET 2015
[info] 			resolver: sbt-chain
[info] 			artifactResolver: sbt-chain
[info] 			evicted: false
[info] 			homepage: http://www.scala-lang.org/
[info] 			textraAttributes: Map(info.apiURL -> http://www.scala-lang.org/api/2.10.5/)
[info] 			isDefault: false
[info] 			configurations: default, compile, runtime, default(compile), master
[info] 			licenses: (BSD-like,Some(http://www.scala-lang.org/downloads/license.html))
[info] 			callers: org.scala-js:scala-library-for-scalajs_2.10:0.6.14-SNAPSHOT ()
// Snip
[success] Total time: 1 s, completed Nov 13, 2016 10:18:07 PM
```

So really, the only difference seems to be the order in which the artifacts appear (which is deterministic). However, it becomes more interesting: If we patch the `fetchScalaSources` task to output all files:

```scala
val report = update.value
println(report.allFiles)
```

```
// 2.11.8
List(~/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.8.jar, ~/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.8-sources.jar, /* snip */)
```

```
// 2.10.5
ArraySeq(~/.sbt/boot/scala-2.10.5/lib/scala-library.jar, /* snip */)
```

We note 3 things:
1. In 2.10.5 the source JAR is missing (that is what is causing our bug).
2. In 2.10.5 the scala-library comes from a different location. N.B. **this is not the case in the update report**.
3. In 2.10.5 we get an `ArraySeq` instead of a `List`.

To me, this very heavily suggests that sbt is not executing the same code for `allFiles` in 2.10.5 and 2.11.8. However, nothing in [`UpdateReport.scala`][1] suggests that.

Anyone knows what is going on here? @eed3si9n @SethTisue 

As a last resort, I'll try and upgrade sbt (0.13.9 -> 0.13.13).

[1]: https://github.com/sbt/sbt/blob/v0.13.9/ivy/src/main/scala/sbt/UpdateReport.scala

**Comment by gzm0** [comment]
Upgrading to 0.13.13 seems to fix this.

**Comment by gzm0** [comment]
So does upgrading to 0.13.10.

**Comment by sjrd** [comment]
> Upgrading to 0.13.13 seems to fix this.

Does it then not break 2.10.6?

The `~/.sbt/boot/scala-2.10.5/lib/scala-library.jar` suggests that this happens precisely because it's the version of Scala used by sbt itself.

**Comment by gzm0** [comment]
> Does it then not break 2.10.6?

Spot on! But this clearly means this is an sbt bug.
