### ISSUE TITLE
Unable to use underscore as key name with UndefOr unioned type

### ISSUE THREAD

**Issue by cretz** [scala-js/scala-js#2666]
Run the following (via [fiddle](https://scalafiddle.io/sf/gKgxQY0/702)):

```scala
import scala.scalajs.js
import scala.scalajs.js.{UndefOr, |}

@js.native
trait Temp extends js.Object
object Temp {
  def apply(foo: UndefOr[String | Int]): Temp =
    js.Dynamic.literal(`_` = foo).asInstanceOf[Temp]
}

println("Temp: " + Temp(foo = "foo"))
```

This errors with:

```
ScalaFiddle.scala:8: error: type mismatch;
 found   : scala.scalajs.js.UndefOr[scala.scalajs.js.|[String,Int]]
 required: scala.scalajs.js.Any
error after rewriting to scala.scalajs.js.Dynamic.literal.applyDynamicNamed("apply")(scala.Tuple2("_", ))
possible cause: maybe a wrong Dynamic method signature?
      js.Dynamic.literal(`_` = foo).asInstanceOf[Temp]
```

Note, this works just fine without the union type. My use case for underscore-based object key names is [datatables](https://datatables.net/reference/option/columns.render#object).

**Comment by cretz** [comment]
A workaround appears to be to add `.asInstanceOf[js.Any] during the `literal` invocation, e.g.:

```scala
import scala.scalajs.js
import scala.scalajs.js.{UndefOr, |}
import scala.scalajs.js.annotation.JSName

@js.native
trait Temp extends js.Object {
  @JSName("_")
  val foo: String | Int = js.native
}
object Temp {
  def apply(foo: UndefOr[String | Int]): Temp =
    js.Dynamic.literal(`_` = foo.asInstanceOf[js.Any]).asInstanceOf[Temp]
}

println("Temp: " + Temp(foo = "foo").foo)
```

**Comment by sjrd** [comment]
This is expected. `A | B` is not convertible to `C` even if both `A` and `B` have implicit conversions to `C`. The reason is that to apply the correct implicit conversion, we would need to be able to decide whether an arbitrary `x` is in fact an `A` or a `B`, and that's not possible because those types are abstract.

The workaround is actually the way to go in this case.

**Comment by sjrd** [comment]
Note that this has nothing to do the underscore. If the field was named `babar` you would have the same issue.

**Comment by cretz** [comment]
@sjrd - Ah, I see. Maybe there should be something in addition to `UnionOps.merge` that checks for view/context bounds to do implicit conversion instead of requiring a strict supertype for the unioned types.

**Comment by sjrd** [comment]
As I explained above, this is *not possible* to implement.

> The reason is that to apply the correct implicit conversion, we would need to be able to decide whether an arbitrary x is in fact an A or a B, and that's not possible because those types are abstract.
