### ISSUE TITLE
Minimize the number of IIFEs generated by Desugar for Closure IR nodes

### ISSUE THREAD

**Issue by Atry** [scala-js/scala-js#2675]
Was:  Scala.js with Scala 2.12.0 creates too many unnecessary IIFE

I created a web framework [Binding.scala](https://github.com/ThoughtWorksInc/Binding.scala), which generates deeply nested blocks for XHTML literal.

These kind of blocks will be converted to IIFE for ECMAScript 5 like this:

``` javascript
                              x(function(a, b, c) {
                                return function(e) {
                                  var f = B();
                                  return S((new G).d(P(C(new D, function(a) {
                                    return function() {
                                      return (new G).d(P(C(new D, function() {
                                        return function() {
                                          return (new F).g(U(Q(), "\n        "));
                                        };
                                      }(a))));
                                    };
                                  }(a, f)))), x(function(a, b, c, e) {
                                    return function(b) {
                                      return E((new G).d(P(C(new D, function(a) {
                                        return function() {
                                          return x(function() {
                                            return function(a) {
                                              return a;
                                            };
                                          }(a));
                                        };
                                      }(a)))), x(function(a, b, c, e) {
                                        return function(a) {
                                          var f = (new F).g((new J).n([b, c, e]));
                                          return (new Eb).Y((new Fb).Y(f, a), x(function() {
                                            return function(a) {
                                              return a;
                                            };
                                          }(f)));
                                        };
                                      }(a, c, e, b)));
                                    };
                                  }(a, b, c, e)));
                                };
                              }(a, b, c))
```
The entire JS file can be found at https://github.com/ThoughtWorksInc/todo/blob/3f173cd/js/js-opt.js

These IIFEs are very slow. In [some benchmarks](https://github.com/Atry/js-framework-benchmark/tree/binding.scala), even the output ECMAScript 2015 code (which creates `const` instead of IIFE) with fast optimizer runs two times faster than ECMAScript 5 code with full optimizer!

I expect that Closure Compiler would inline IIFE, or enabling Closure Compiler for ECMAScript 2015.

**Comment by sjrd** [comment]
I don't really understand what you want Scala.js to do here? Could you make that more precise? We don't develop Closure, so changing what it does is not within our ability.

**Comment by sjrd** [comment]
It's also not clear to me what "the ECMAScript 2015" code is. Generated how, by what, from what?

**Comment by Atry** [comment]
I mean some benchmarks runs faster with the option `scalaJSOutputMode := org.scalajs.core.tools.linker.backend.OutputMode.ECMAScript6`, which disabled Closure Compiler, than the default setting. I guess the reason is that `OutputMode.ECMAScript6` avoids IIFE.

I noticed that Closure Compiler supports ECMAScript 2015 input format. I wonder if we could enable Closure Compiler for `OutputMode.ECMAScript6`, so that the output JavaScript would eliminate IIFE along with other optimizations from the Closure Compiler.

**Comment by sjrd** [comment]
> I guess the reason is that OutputMode.ECMAScript6 avoids IIFE.

It doesn't, so that's not the actual reason.

The actual reason is that Closure typically degrades performance a bit, up to 50% in some of our benchmarks. If you want to fairly compare the ES5 version versus ES2015, you should either compare their `fastOpt` variants, or explicitly disable Closure in `fullOpt` for ES5.

That said, we should indeed enable Closure in the ES2015 output now that it supports it.

**Comment by Atry** [comment]
@sjrd I re-checked the ECMAScript 2015 output. You are right, there are many IIFEs in the output.

 I used to think that ECMAScript 2015 target does not use IIFE in favor of `const` and `let`.

**Comment by Atry** [comment]
AFAIK, the Scala.js compiler inline regular functions, however, it brings more IIFE function calls.
I wonder what the purpose is for so many IIFEs.

**Comment by sjrd** [comment]
In general, they are necessary so that captures are truly immutable (and not a read-only version of a variable whose value changes in each iteration of a loop). Not all of them are necessary. A more sophisticated translation in `JSDesugaring` could avoid some of them. I have never done so because I lack proper macro benchmarks doing lots of anonymous functions to evaluate the changes.

**Comment by Atry** [comment]
I noticed that Scala 2.11.x does not create IIFEs (creating prototype classes instead), and has better performance for most cases than Scala 2.12.x.
FYI.

**Comment by Atry** [comment]
The result of the benchmark can be found at https://atry.github.io/scala-js/table.html , and the source code is at https://github.com/krausest/js-framework-benchmark

You may notice that Scala 2.12 is slower than 2.11 for almost every benchmark.

**Comment by sjrd** [comment]
Could you also benchmark with 2.11 with the `-Ydelambdafy:method` flag? It should cause 2.11 to emit lambdas using a scheme closer to what 2.12 does. That would give more insight on whether it is the lambda encoding's fault or something else in 2.12.

**Comment by Atry** [comment]
Yes, Scala 2.11 with `-Ydelambdafy:method` yields the same result as Scala 2.12

**Comment by sjrd** [comment]
Thanks. I guess it would be worth trying to improve the emitter about that, then.

**Comment by Atry** [comment]
@sjrd , As long as Closure compiler supports ECMAScript 6 input, which allows scoped `let` and `const`, is it possible to not generate any IIFE at all?

**Comment by sjrd** [comment]
With the `ECMAScript6` output mode, yes.

**Comment by gzm0** [comment]
Is this still an issue? My understanding of the discussion is that using ES6 entirely mitigates the need for this.

@sjrd This had me toying with the idea of always generating ES6 when using closure and have closure compile ES6 down to ES5.1.

This would:
- Probably give some shorter code to ES5 users in fullOptJS
- Let us remove the `javascript.Trees.DocComment` tree.

WDYT?

**Comment by sjrd** [comment]
> Is this still an issue? My understanding of the discussion is that using ES6 entirely mitigates the need for this.

ES6 has the features that *would* allow us not to generate IIFEs, but we don't leverage them.



> This had me toying with the idea of always generating ES6 when using closure and have closure compile ES6 down to ES5.1.
> 
> This would:
> 
>     * Probably give some shorter code to ES5 users in fullOptJS
>     * Let us remove the `javascript.Trees.DocComment` tree.
> 
> WDYT?

In general, one cannot compile down ES 2015 semantics entirely accurately to ES 5.1. There are choices involved, and not all compilers agree. We cannot guarantee that GCC makes the same choices (and will continue to make the same choices) regarding the particular semantics to give to things that do not have an exact equivalent in ES 5.1. Therefore I think that giving ES 2015 to GCC while we give ES 5.1 in fastOpt would be dangerous. We could leave things go unchecked/broken in production mode.

**Comment by gzm0** [comment]
We might be able to leverage a similar mechanism than for `ApplyDynamicImport` in #4380 to avoid IIFEs for closures where all captures are (trivially) pure (which AFAICT is the case in the original example).

**Comment by gzm0** [comment]
Looping back the discussion from here: https://github.com/scala-js/scala-js/pull/4654#issuecomment-1069549483

Another thought I had: Would it be helpful to define "local ref" captures on Closures nodes? They would essentially "mark" a local def to traverse a closure boundary (very similar to by ref captures in C++, e.g. `[&x]() {...}`).

**Comment by sjrd** [comment]
I don't think it would really help. AFAICT, that would not bring more information than having the a formal capture param def with the same name as the corresponding actual closure argument, would it?

**Comment by gzm0** [comment]
>  AFAICT, that would not bring more information than having the a formal capture param def with the same name as the corresponding actual closure argument, would it?

No, I don't think so. Unless we restrict this more than a `VarRef` (e.g. it cannot be in loops).
