### ISSUE TITLE
Standalone distribution missing for Scala 2.12

### ISSUE THREAD

**Issue by vossad01** [scala-js/scala-js#2677]
I don't need the standalone distribution, but I noticed on http://www.scala-js.org/doc/internals/downloads.html that there are no distributions for 2.12 so figured I should report it.

I tried hacking the URL to see if they are hosted under the same pattern, just with out a link, and it appears they are not hosted in that way.

**Comment by sjrd** [comment]
No they have not been built yet. We're waiting on scopt to be published for 2.12.

**Comment by sjrd** [comment]
scopt has now been released for 2.12: http://search.maven.org/#artifactdetails%7Ccom.github.scopt%7Cscopt_2.12%7C3.5.0%7Cjar
So this is unblocked and can be addressed.

**Comment by gzm0** [comment]
Why is this in 0.6.15? Is it more complicated than just adding it to `publish.sh`?

**Comment by gzm0** [comment]
Ok, I see this is more work, since it can't find scopt.
