### ISSUE TITLE
Be compatible with Scala 2.13

### ISSUE THREAD

**Issue by SethTisue** [scala-js/scala-js#2687]
although the Scala 2.13 effort is only just now getting underway, there are already nightly builds and a 2.13 community build

in the community build, Scala.js is failing, as you'll see here: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/81/consoleFull

perhaps you just need to make a trivial change to your build to make it 2.13 aware...?

**Comment by sjrd** [comment]
Ah!

Or should be trivial, yes. Normally we're very careful about writing tests like `!version.startsWith("2.11.")` rather than `version.startsWith("2.12.")`. My first hunch would be that we need to copy `scalalib/overrides-2.12/` to `scalalib/overrides-2.13/`. Maybe that's all that's needed.
