### ISSUE TITLE
Inconsistent behaviour of .toFloat

### ISSUE THREAD

**Issue by vpavkin** [scala-js/scala-js#2700]
Hi!

Just found this weird issue. When truncating a `Double`, `toFloat` adds some fractions from nowhere.

For this code:
```scala
val a = 5.71

println(a)  
println(a.toFloat)
```

JVM outputs:
```
5.71
5.71
```

JS:
```
5.71
5.710000038146973
```
fiddle: https://scalafiddle.io/sf/vqa4TX7/1

Don't know what scala-js version is on scala-fiddle, but locally I reproduce it on 0.6.13.

If you want, I can try 0.6.14, though I haven't found anything related fixed since 0.6.13

**Comment by vpavkin** [comment]
maybe issue is not with `toFloat`, but with `Float#toString`.

**Comment by sjrd** [comment]
This is [a documented deviation](https://www.scala-js.org/doc/semantics.html) of `Float.toString`. If you want reliable printing of `Float`s, you should use `String.format` (or the `f` interpolator) with an explicitly specified precision.
