### ISSUE TITLE
Hide stuff in library doc

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#2703]
Internal namespaces:

- `scala.scalajs.runtime`
- `scala.scalajs.js.annotation.internal`

"Obvious" extensions of arity. Just like in the standard libarary:
- `js.Function3+`
- `js.ThisFunction3+`
- `js.Tuple3+`

**Comment by sjrd** [comment]
Is that even possible? Is there a Scaladoc option for that, or something like that?

**Comment by gzm0** [comment]
Well, it works for the scala library. For `runtime`, they just filter `sources in doc`. For `FunctionN` etc. I do not know.
