### ISSUE TITLE
Multi line strings content inconsistent with Scala

### ISSUE THREAD

**Issue by mkotsbak** [scala-js/scala-js#2707]
The following snippet:

```scala
println(
"""12345
6""".toList
)
```
does in SJS print: `List(1, 2, 3, 4, 5, , , , 6)`: https://scalafiddle.io/sf/elRy4Bv/0
while in normal Scala prints:
`List(1, 2, 3, 4, 5, 
, 6)`

**Comment by mkotsbak** [comment]
Workaround is to run trim on each line, but it is supposed to work:
```

  /** Return all lines in this string in an iterator, excluding trailing line
   *  end characters; i.e., apply `.stripLineEnd` to all lines
   *  returned by `linesWithSeparators`.
   */
  def lines: Iterator[String] = [...]
```

**Comment by sjrd** [comment]
Is this happening on Windows and/or with a file containing Windows line endings?

**Comment by mkotsbak** [comment]
No, I was testing on Linux using Chromium.

**Comment by mkotsbak** [comment]
Here are the ASCII values:
List(49, 50, 51, 52, 53, 10, 32, 32, 54)
https://scalafiddle.io/sf/elRy4Bv/1

**Comment by mkotsbak** [comment]
I only reproduce this in ScalaFiddle, so closing it here.

Comment:
Otto Chrons @ochrons 12:12
it's not a bug, the lines get indented automatically if you use a template
