### ISSUE TITLE
Reflective call `eq` and `ne` on value class

### ISSUE THREAD

**Issue by LukasKellenberger** [scala-js/scala-js#2709]
`eq` and `ne` are defined on `AnyRef` and not `Any`, which means that they can be implemented in value classes.

This leads to a wrong behaviour when doing a reflective call on one of these methods.

```scala
class Foo(val f: Int) extends AnyVal {
  def eq(other: AnyRef) = true
}

def callEq(obj: Any { def eq(other: AnyRef): Boolean }, other: AnyRef) = obj.eq(other)

callEq(new Foo(0), List())
``` 

This should return `true`, but returns `false`.

**Comment by sjrd** [comment]
Wow. How on earth did you notice that!? IMO both these things (defining `eq` on a value class + using reflective calls) are bad ideas to being with ^^ The likelihood of combining the two seems so low.

Anyhow, this is clearly a bug. Thanks for the report.

**Comment by gzm0** [comment]
I *love* this one!

**Comment by densh** [comment]
@LukasKellenberger Nice find!

**Comment by sjrd** [comment]
There is also a problem with `synchronized`. But at least this one fails to link rather than generating wrong code:
```scala
class Foo(val f: Int) extends AnyVal {
  def synchronized[T](a: T): Any = a + "there"
}

def callSynchronized(obj: Any { def synchronized[T](a: T): Any }) = obj.synchronized("hello")

println(callSynchronized(new Foo(0)))
```
Note that JVM is broken for the reverse problem: when `eq`, `ne` or `synchronized` inherited from `AnyRef` are called reflectively:
```scala
class Foo(val f: Int) extends AnyVal {
  def eq(other: AnyRef) = true

  def synchronized[T](a: T): Any = a + "there"
}

class Bar(val f: Int) extends AnyRef {
}

def callEq(obj: Any { def eq(other: AnyRef): Boolean }, other: AnyRef) = obj.eq(other)
def callSynchronized(obj: Any { def synchronized[T](a: T): Any }) = obj.synchronized("hello")

scala>     println(callEq(new Foo(0), List()))
true

scala>     println(callSynchronized(new Foo(0)))
hellothere

scala> 

scala>     println(callEq(new Bar(0), List()))
java.lang.NoSuchMethodException: Bar.eq(java.lang.Object)
  at java.lang.Class.getMethod(Class.java:1786)
  at .reflMethod$Method1(<console>:7)
  at .callEq(<console>:7)
  ... 33 elided

scala>     println(callSynchronized(new Bar(0)))
java.lang.NoSuchMethodException: Bar.synchronized(java.lang.Object)
  at java.lang.Class.getMethod(Class.java:1786)
  at .reflMethod$Method1(<console>:7)
  at .callSynchronized(<console>:7)
  ... 33 elided
```

**Comment by sjrd** [comment]
Adding `eq__O__Z`, `ne__O__Z` and `synchronized__O__O` to the hard-coded IR of `java.lang.Object` fixes it: https://github.com/scala-js/scala-js/compare/master...sjrd:fix-eq-ne-synchronized-reflective-call

But I'm not sure I *want* to do that ...
