### ISSUE TITLE
jsDependencies resolves maven dependencies incorrectly

### ISSUE THREAD

**Issue by dstibbe** [scala-js/scala-js#2710]
**Problem:** 
I have a jsDependencies configuration as following: 
```
 jsDependencies ++= Seq(
      "org.webjars.npm" % "angular" % angularVersion / s"${angularVersion}/angular.js", 
      "org.webjars.npm" % "angular-material-icons" % "0.7.1" / "angular-material-icons.min.js" dependsOn  s"${angularVersion}/angular.js"
    ))
```

where angularVersion=1.4.9.

This configuration however provides me with an `org.webjars.npm:angular` of version 1.6.1 (instead of the expected 1.4.9).
This should not happen, since `angular-material-icons` has a maven dependency on [1.3,) ; it does not require 1.6.1 when an explicit version of 1.3 or higher is already present.

**Probable cause:**
The tree listing shows the following:
```
  +-org.webjars.npm:angular-material-icons:0.7.1
  | +-org.webjars.npm:angular:1.6.1
  |
  +-org.webjars.npm:angular:1.4.9 (evicted by: 1.6.1)
  +-org.webjars.npm:angular:1.6.1
```
It somehow , when resolving the dependencies for _org.webjars.npm:angular-material-icons:0.7.1_ ignores the fact that there already is an explicit dependency for _org.webjars.npm:angular:1.4.9_ , and therefore simply determines that it depends on _org.webjars.npm:angular:1.6.1_ .
Eventually, when he then notices that there are two angular version, it simply evicts the oldest one.

It is as if each maven dependency tree is resolved in isolation.

Resources:
- [Gitter discussion](https://gitter.im/scala-js/scala-js?at=586c9dcb9e6f00e74af49f13)
- [org.webjars.npm:angular-material-icons:0.7.1](https://search.maven.org/#artifactdetails%7Corg.webjars.npm%7Cangular-material-icons%7C0.7.1%7Cjar)

**Comment by sjrd** [comment]
The resolution of `jsDependencies` is entirely delegated to `libraryDependencies`. Your configuration:
```scala
jsDependencies ++= Seq(
    "org.webjars.npm" % "angular" % angularVersion / s"${angularVersion}/angular.js", 
    "org.webjars.npm" % "angular-material-icons" % "0.7.1" / "angular-material-icons.min.js" dependsOn  s"${angularVersion}/angular.js"
))
```
causes the following `libraryDependencies` to be automatically added:
```scala
libraryDependencies ++= Seq(
    "org.webjars.npm" % "angular" % angularVersion, 
    "org.webjars.npm" % "angular-material-icons" % "0.7.1"
))
```
From there, it's sbt who is responsible for resolving those things, and then we take whatever it comes up with.

There is nothing we can do in Scala.js to alter that resolution mechanism. If it is faulty, it is sbt's or ivy's fault.

**Comment by dstibbe** [comment]
It actually seems like it ...

It seems like this same (!) issue is actually reported at the sbt github: https://github.com/sbt/sbt/issues/2291

But, when I read their reasoning... I fear for sbt
