### ISSUE TITLE
Create literals from new @ScalaJSDefined trait instead of new Object

### ISSUE THREAD

**Issue by chandu0101** [scala-js/scala-js#2715]
```scala
@ScalaJSDefined
trait Point extends js.Object {
  var x: js.UndefOr[Double] = js.undefined
  var y: js.UndefOr[Double] = js.undefined
}
 val p = new Point {x = 3; y = 5}

//fullOptCode
a=new f.Object;a.x=3;a.y=5;
```

from this SO answer : http://stackoverflow.com/a/21436082/986387 , looks like literal creation is faster! , can we get this in future versions of scala.js /GCC  ?

**Comment by sjrd** [comment]
Yes, we can. We should have from the beginning, actually.

That said, I do not believe for a second the benchmark in that SO answer. It does not even make any kind of attempt at avoiding the benchmarked code to be dce'ed away. It would be easy for a VM do dce away `var x = {}` if `x` is unused, but not `var x = new Object()`.

**Comment by chandu0101** [comment]
>Yes, we can. We should have from the beginning, actually.

👍 

>That said, I do not believe for a second the benchmark in that SO answer. It does not even make any kind of attempt at avoiding the benchmarked code to be dce'ed away. It would be easy for a VM do dce away var x = {} if x is unused, but not var x = new Object().

oh ok , thanks for info :)
