### ISSUE TITLE
JSImport requiring whole package instead of importing sub module

### ISSUE THREAD

**Issue by chandu0101** [scala-js/scala-js#2722]
```scala

@js.native
@JSImport("react-native","AppRegistry")
object AppRegistry extends js.Object

dom.window.console.log(AppRegistry)

//fastOptJS
var $i_react$002dnative = require("react-native");

//fullOptJS 
var Ha=require("react-native")
```

**Comment by gzm0** [comment]
What would you expect it to do?

```javascript
require("react-native").AppRegistry
```

?

**Comment by chandu0101** [comment]
yes

**Comment by gzm0** [comment]
If you look later in the output, we will select `$i_react$002dnative.AppRegistry` whenever you use `AppRegistry`. This is just a strategy to not import stuff needlessly.

Is it an issue with the react native compiler?

**Comment by chandu0101** [comment]
my understanding is  when react-native package finds `require(react-native)` it will add whole react-native to my bundle even though  i am using only few modules from package. which will effect in bundle size and startup of app(parsing javascript)!

**Comment by julienrf** [comment]
@chandu0101 To my knowledge this kind of optimizations can only be implemented with ES6 modules. Which module bundler are you using?

**Comment by gzm0** [comment]
I'm assuming the react-native module bundler. It does a lot of textual stuff and doesn't honor typical JS equivalences (also see #2217). So I'm assuming the following two are note the same for it:

```javascript
var x = require('a');
var y = x.B;

// v.s.

var y = require('a').B;
```

**Comment by sjrd** [comment]
In theory at least, @julienrf is right: sub-module dependencies are really possible only with ES6 modules.

That said, some bundlers try to effectively treat CommonJS modules as if they were ES6 modules, and perform similar optimizations. Depending on the bundler, they might either:
* Not do any sub-module dce at all
* Do sub-module dce only if it's evident from the AST, e.g., `require('a').B` is optimized but not `var x = require('a'); x.B` (note, @gzm0, that in this case, they're not altering the semantics; it's only a limitation of the optimizer -- we have similar limitations with arithmetic simplifications, e.g., we can optimize away `val z = -1 * (-x)` but not `val y = -x; val z = -1 * y`)
* Do sub-module dce in more complex cases such as `var x = require('a'); x.B`. I know that Rollup.js does this; it works on ES6 modules only but it can dce away `import * as x from 'a'; x.B` into `import { B } from 'a'; B`.

If the bundler you're using is in the first or third case, changes in Scala.js would not affect the outcome. Only if it's in the second case would the situation would be improved if Scala.js emitted `require('a').B`.

**Comment by sjrd** [comment]
@chandu0101 Do you have any evidence that the react-native packager is in the second case (able to optimize `require('a').B` but not `var a = require('a'); a.B`)? Otherwise I would close this issue, as it would be useless to change anything to how Scala.js emits its code.

**Comment by chandu0101** [comment]
@sjrd  sorry for delay , i just tested and i don't see any change in output file size with `require('react-native).x` .
