### ISSUE TITLE
Proposal: Principled replacement for "reflective" instantiation

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2733]
The discussion in Proposal #2720 raised an interesting point: `@JSExport`ing Scala classes and objects is weird if we deprecate instance member exports. However, testing frameworks (ab)use `@JSExportDescendantClasses` and `@JSExportDescendantObjects` to "reflectively" instantiate test classes.

I have checked the following testing frameworks:

- ScalaTest
- ScalaCheck
- catalysts/SpecLite
- uTest
- MiniTest
- GreenLight
- ScalaProps

All of them use our [`TestUtils`](https://github.com/scala-js/scala-js/blob/master/test-interface/src/main/scala/org/scalajs/testinterface/TestUtils.scala) to instantiate test classes and loading test modules. Moreover, for those that use `newInstance()` (as opposed to `loadModule()`), they always use 0 arguments to the constructor.

Besides testing frameworks, it seems that `@JSExportDescendantClasses` is basically unused, except by Akka.js. I will come back to the topic of Akka.js later.

## The proposal

I propose we introduce a new core API specifically addressing the needs of reflective class instantiation/module loading. Its public API would look like the following. Names and signatures are tentative; I'd love to receive suggestions for better names.
```scala
package scala.scalajs.reflect

/** Enable `Reflect.lookupInstantiatableClass()` for all descendants of the annotated class
 *  that have a public constructor with 0 argument or that are singleton objects.
 */
class EnableReflectiveInstantiation extends StaticAnnotation

final class InstantiatableClass[T <: AnyRef] private (
    val runtimeClass: Class[T],
    val isModule: Boolean,
    newInstanceFun: js.Function0[T]
) {
  // Intended to be used with non-module classes
  def newInstance(): T = newInstanceFun()
  // Intended to be used with module classes
  def loadModule(): T = newInstanceFun()
}

object Reflect {
  def lookupInstantiatableClass(fqcn: String): Option[InstantiatableClass[_ <: AnyRef]] =
    ???
}
```
Alternatively, we could separate classes from module classes in the API.

## Implementation

Implementation-wise, `Reflect` maintains a lookup dictionary, and has an internal method to register classes:
```scala
object Reflect {
  private val instantiatableClasses = js.Dictionary.empty[InstantiableClass[_]]

  // `protected[reflect]` makes it public in the IR
  protected[reflect] def registerInstantiatableClass[T <: AnyRef](
      fqcn: String, runtimeClass: Class[T], isModule: Boolean, newInstanceFun: js.Function0[T]): Unit = {
    instantiatableClasses(fqcn) = new InstantiatableClass(runtimeClass, isModule, newInstanceFun)
  }

  def lookupInstantiatableClass(fqcn: String): Option[InstantiatableClass[_ <: AnyRef]] =
    instantiatableClasses.get(fqcn)
}
```
The missing part is ... who calls `Reflect.registerInstantiatableClass` and when? Well, now that our IR has static initializers anyway, we can build on top of those in our back-end. For every class `pack.C` extending a type annotated with `@EnableReflectiveInstantiation` with a public no-arg constructor, we synthesize a static initializer with (pseudo-IR with pretty names):
```scala
def clinit___() {
  scala.scalajs.reflect.Reflect.registerInstantiatableClass(
      "pack.C", classOf[pack.C], false, lambda<>() = { new pack.C() })
}
```
And for every module class `pack.O$`, we generate:
```scala
def clinit___() {
  scala.scalajs.reflect.Reflect.registerInstantiatableClass(
      "pack.O$", classOf[pack.O$], true, lambda<>() = { mod:pack.O$ })
}
```
The nice thing about this strategy is that only the `compiler/` and `library/` need to be changed. In other words, the IR spec is unchanged, and consequently the analyzer, optimizer and emitter do not need to be aware of all of this.

## Migration path

Since testing frameworks all use `TestUtils`, we can provide a pretty easy migration path. We simply have to update `TestUtils.loadModule()` and `TestUtils.newInstance()` to try `Reflect.lookupInstantiatableClass` before the `exportsNamespace`.

`@JSExportDescendantObjects` and `@JSExportDescendantClasses` would be deprecated with a message telling to use `@EnableReflectiveInstantiation` instead.

In 1.0.0, we can remove `@JSExportDescendantObjects` and `@JSExportDescendantClasses` as well as the backup path in `TestUtils`. We will also be able to remove `exportsNamespace`, which will be a relief when emitting ES6 modules.

## Akka.js

Akka.js, as always, uses more reflection than everything else. The crucial part is concentrated in [`ReflectiveDynamicAccess.scala`](https://github.com/akka-js/akka.js/blob/354902581e0a7068a09f9f4f2017f5631689794a/akka-js-actor/js/src/main/scala/akka/actor/ReflectiveDynamicAccess.scala). Contrary to testing frameworks (and other rare uses of `@JSExportDescendantClasses`), Akka.js does use constructors with 1 ore more arguments.

Such a use case is not supported by the replacement `@EnableReflectiveInstantiation`. However, it is supported by [`scalajs-reflect`](https://github.com/sjrd/scalajs-reflect), which was specifically developed for the use cases of Akka.js quite a while ago.

## Alternative with all public constructors

Alternatively to the above proposal which restricts itself to the no-arg constructors, we could bring in the full feature of [`scalajs-reflect`](https://github.com/sjrd/scalajs-reflect) and support all declared public constructors. The API and implementation would look like the following. Here we really need to separate normal classes from module classes for sanity.
```scala
final class LoadableModuleClass[T <: AnyRef] private (
    val runtimeClass: Class[T],
    loadModuleFun: js.Function[T]
) {
  def loadModule(): T = loadModuleFun()
}

final class InstantiatableClass[T <: AnyRef] private (
    val runtimeClass: Class[T],
    val declaredConstructors: immutable.Seq[InvokableConstructor[T]]
)

final class InvokableConstructor[T <: AnyRef] private (
    val parameterTypes: immutable.Seq[Class[_]],
    newInstanceFun: js.Function
) {
  def newInstance(args: Any*): T =
    newInstanceFun.asInstanceOf[js.Dynamic].apply(args.asInstanceOf[Seq[js.Any]]: _*)
}

object Reflect {
  private val loadableModuleClasses = js.Dictionary.empty[LoadableModuleClas[_]]
  private val instantiatableClasses = js.Dictionary.empty[InstantiableClass[_]]

  // `protected[reflect]` makes it public in the IR
  protected[reflect] def registerLoadableModuleClass[T <: AnyRef](
      fqcn: String, runtimeClass: Class[T], loadModuleFun: js.Function0[T]): Unit = {
    loadModuleClasses(fqcn) = new LoadableModuleClass(runtimeClass, newInstanceFun)
  }

  protected[reflect] def registerInstantiatableClass[T <: AnyRef](
      fqcn: String, runtimeClass: Class[T],
      constructors: js.Array[js.Tuple2[js.Array[Class[_]], js.Function]]): Unit = {
    instantiatableClasses(fqcn) = new InstantiatableClass(runtimeClass,
        constructors.map(c => new InvokableConstructor(c._1.toList, c._2)).toList)
  }

  def lookupLoadableModuleClass(fqcn: String): Option[LoadableModuleClass[_ <: AnyRef]] =
    loadableModuleClasses.get(fqcn)

  def lookupInstantiatableClass(fqcn: String): Option[InstantiatableClass[_ <: AnyRef]] =
    instantiatableClasses.get(fqcn)
}
```
This would be slightly more complicated to implement, but would provide Akka.js with everything it needs out of the box.

**Comment by BennyHill** [comment]
@sjrd For catalysts.SpecLite, I would be happy to update with either proposal, as neither require that much work, even if one does indeed need a _bit_ more work.

So I would be happy to go with the _best, longterm_ solution, which I'm guessing is the second proposal. 

/cc @bvenners @cheeseng @rickynils @kailuowang @lihaoyi @alexandru @xuwei-k and @andreaTP,

**Comment by andreaTP** [comment]
Even if I understand your point my only concern is the needs to ask the user to import explicitly the linker plugin, if this is not the case, standardizing something that is an hack will be really appreciated :-)

If not I need to drop support for things really cool like scalafiddle and such. that is a not good to me.

**Comment by sjrd** [comment]
@andreaTP With the first version (only supporting 0-arg constructors), Akka.js would need scalajs-reflect and its linker plugin.

With the alternative version (supporting all public constructors), the core would contain everything Akka.js needs (AFAICT) and so Akka.js would not need scalajs-reflect nor its linker plugin.

**Comment by andreaTP** [comment]
Thanks, in this case my choice is obvious :-) second one :+1:

**Comment by sjrd** [comment]
WiP: https://github.com/scala-js/scala-js/compare/master...sjrd:reflective-instantiation
Basically works (see the hello world), but needs proper tests.

**Comment by antonkulaga** [comment]
Of course I vote for the second one=)

**Comment by sjrd** [comment]
Despite #2720 being rejected, I believe this is still valuable on its own right.

**Comment by andreaTP** [comment]
:+1:
