### ISSUE TITLE
Proposal: Allow @JSExportTopLevel on JS classes and objects

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2734]
In the let's-rething-`@JSExport` series, here is another one: allow `@JSExportTopLevel` on top-level JS classes and objects. For classes, that would be the same as `@JSExport`. On objects, they would be exported as *variables* rather than as a 0-arg function.

In other words: this becomes valid:
```scala
@JSExportTopLevel("Foo")
@ScalaJSDefined
class Foo(val x: Int) extends js.Object

@JSExportTopLevel("Bar")
@ScalaJSDefined
object Bar extends js.Object {
  def baz(x: Int): Int = x + 1
}
```
and these can be used from JS as:
```js
var foo = new Foo(5);
console.log(foo.x);

console.log(Bar.baz(5)); // note `Bar` and not `Bar()`
```
Note that, given that we now export fields to the top-level, this does not add any expressive power to Scala.js (only convenience), as we can already do:
```scala
object ExportsFromAboveAsFields {
  @JSExportTopLevel("Foo")
  val foo = js.constructorOf[Foo]

  @JSExportTopLevel("Bar")
  val bar = Bar
}
```
At the same time, we deprecate `@JSExport` on classes and objects. For JS classes/objects, it should be replaced by `@JSExportTopLevel`. For Scala classes/objects, it should become basically useless because of #2720.

Together with #2720 and #2733, *all* uses of `@JSExport` will be deprecated. `@JSExportTopLevel` replaces `@JSExport` for all cases where it provides interoperability semantics for the `export` directives of ES 2015 modules. When `@JSExport` is definitely dead, we can re-alias the name `@JSExport` to the semantics of `@JSExportTopLevel`, which are closer to the JS concept of `export`.

**Comment by jducoeur** [comment]
At first look, this seems quite nice -- it's *intuitive* from an API point of view, often moreso than the existing scheme for exporting top-level fields...

**Comment by gzm0** [comment]
Hahahaha, I thought of this yesterday without having looked at this proposal. Absolutely agree.

**Comment by sjrd** [comment]
Since #2720 was rejected, this should be updated to also allow `@JSExportTopLevel` on Scala classes and objects.
