### ISSUE TITLE
Failure when accessing protected buf in ByteArrayOutputStream

### ISSUE THREAD

**Issue by travisbrown** [scala-js/scala-js#2737]
I've got some Scala code that extends `ByteArrayOutputStream` to add access to the buffer without copying. In my real code I'm returning a `ByteBuffer`, but this simplified version shows the issue:

```scala
import java.io.ByteArrayOutputStream
import org.scalatest.FlatSpec
import org.scalatest.prop.GeneratorDrivenPropertyChecks

class EnhancedByteArrayOutputStream extends ByteArrayOutputStream {
  def getBuf(): Array[Byte] = buf
}

class EnhancedByteArrayOutputStreamSpec extends FlatSpec
  with GeneratorDrivenPropertyChecks {
  "getBuf" should "provide access to the buffer" in forAll { b: Byte =>
    val bytes = new EnhancedByteArrayOutputStream()
    bytes.write(b.toInt)
    bytes.close()

    assert(bytes.getBuf()(0) === b)
  }
}
```

This works fine on the JVM, but fails on Scala.js:

```
[info] EnhancedByteArrayOutputStreamSpec:
[info] getBuf
[info] - should provide access to the buffer *** FAILED ***
[info]   JavaScriptException was thrown during property evaluation.
[info]     Message: TypeError: Cannot read property 'u' of undefined
[info]     Occurred when passed generated values (
[info]       arg0 = 0 // 1 shrink
[info]     )
```

This is easy enough to work around with a Scala.js-specific implementation that uses `toByteArray` instead of `buf`, and I haven't investigated why it's happening, but I thought it might be worth reporting.

**Comment by sjrd** [comment]
Thanks for the report. I'll have a look at it in the coming days.

**Comment by gzm0** [comment]
Isn't this, because it tries to read a non private Java class *field*? We have a bug open for this, no?

**Comment by sjrd** [comment]
Ah, yes. The bug is #2532. However that does not explain why the snippet here fails at run-time. It should fail to link 😕

**Comment by gzm0** [comment]
Do we even know what kind of tree GenJSCode sees on JVM field access? We might make assumptions about the class we select on or something.

**Comment by sjrd** [comment]
It's a `Select`, so it's handled by [this code](https://github.com/scala-js/scala-js/blob/34a5a0669c0b825c607cd0b2097a58f40130e7e9/compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala#L1747-L1748). I don't think the field selection is to blame. It's the field *definition* which is wrong (because the field is made private no matter what).

**Comment by sjrd** [comment]
Ah but it does link because the `Analyzer` does not analyze fields! The IR checker does, but it is not enabled by default (only in our own build). Sure enough, if I put this in our hello world:
```scala
class EnhancedByteArrayOutputStream extends ByteArrayOutputStream {
  def getBuf(): Array[Byte] = buf
}

class EnhancedByteArrayOutputStreamSpec {
  def test(): Unit = {
    val b = 1.toByte
    val bytes = new EnhancedByteArrayOutputStream()
    bytes.write(b.toInt)
    bytes.close()

    assert(bytes.getBuf()(0) == b)
  }
}

object HelloWorld extends js.JSApp {
  def main() {
    new EnhancedByteArrayOutputStreamSpec().test()
  }
}
```
I get an IR checker error:
```
> helloworld/run
[info] Compiling 1 Scala source to scalajs\examples\helloworld\target\scala-2.11\classes ...
[info] Fast optimizing scalajs\examples\helloworld\target\scala-2.11\helloworld-fastopt.js
[error] file:scalajs/examples/helloworld/HelloWorld.scala(14:31:Select): Class Lhelloworld_EnhancedByteArrayOutputStream does not have a field buf$f
```
