### ISSUE TITLE
Non-native JS traits produce undesirable extra fields for vals from outer Scala code

### ISSUE THREAD

**Issue by helllamer** [scala-js/scala-js#2748]
I'm unsure, bug it is or not.

Look at this test code:
```scala
/** Public Domain. */

package helloworld

import minitest.SimpleTestSuite

import scala.scalajs.js
import scala.scalajs.js.annotation.ScalaJSDefined
import scala.scalajs.js.{JSON, UndefOr}


@ScalaJSDefined
trait TheOuter extends js.Object {
  val id: String
  val paint: js.UndefOr[TheInner] = js.undefined
}

@ScalaJSDefined
trait TheInner extends js.Object {
  val `the-options`: UndefOr[String] = js.undefined
}

object SomeTest extends SimpleTestSuite {

  def VALUE = "some-value"

  test("render json") {
    val pcFn = VALUE

    val r0 = new TheOuter {
      override val id: String = "some-" + pcFn
      override val paint: UndefOr[TheInner] = {
        new TheInner {
          override val `the-options`: UndefOr[String] = {
            "{" + pcFn + "}"
          }
        }
      }
    }

    val jsonStr = JSON.stringify(r0)
    println("JSON = " + jsonStr)

    assert( !jsonStr.contains("pcFn"), jsonStr )
  }

}
```

This test fails and prints to stdout:
```
JSON = {"id":"some-some-value","paint":{"the-options":"{some-value}"},"pcFn$1$f":"some-value"}
```
As you can see, everything looks fine, but there are an unexpected field named `pcFn$1$f` from outer test function.

In some cases, this will lead to errors:
I'm used `@ScalaJSDefined` traits as described [in 0.6.14 release notes](http://www.scala-js.org/news/2016/12/21/announcing-scalajs-0.6.14/) as "JavaScript configuration objects" for interop with JS-code. For example, mapbox-gl.js API methods fails, if there are any unexpected/unsupported fields in the incoming objects, passed as method arguments.

**Comment by sjrd** [comment]
Technically, it's not a bug. See the documentation at https://www.scala-js.org/doc/interoperability/sjs-defined-js-classes.html

> `private`, `private[this]` and `private[EnclosingScope]` methods, getters and setters are not visible at all from JavaScript. Private fields, however, will exist on the object, with unpredictable names. Trying to access them is undefined behavior.

However, I understand this is not desirable. We should create non-enumerable fields for private fields, at least. Ideally we would also give them random, unforgeable names.

This is related to #2680 (which really is a bug). Both issues would be solved with the same fix (non-enumerable, unforgeable fields).

**Comment by helllamer** [comment]
Interesting thing, when I replace `pcFn` with `VALUE`:
```
  override val id: String = "some-" + VALUE
```
```
  "{" + VALUE + "}"
```
then `pcFn$1$d` field silently goes away. This is a simple workaround.
