### ISSUE TITLE
Make include paths in testHtmlFastOpt relative

### ISSUE THREAD

**Issue by OndrejSpanel** [scala-js/scala-js#2750]
The `testHtmlFastOpt` is a great idea, it makes test debugging and standalone running very convenient. Kudos.

There is one small issue I am experiencing with it (or perhaps a bad setup on my side)? The paths to js files in the html runner are absolute file:/// paths. and therefore the browser refuses to run them "as is", as it (rightfully) complaints it cannot load resource:

        <link rel="stylesheet" type="text/css"
              href="file:/C:/Test/JSTest/target/scala-2.11/resource_managed/test/test-runner.css" />

        <script type="text/javascript"
                src="file:/C:/Test/JSTest/target/scala-2.11/jstest-test-jsdeps.js"></script>
        <script type="text/javascript"
                src="file:/C:/Test/JSTest/target/scala-2.11/jstest-test-fastopt.js"></script>
        <script type="text/javascript">

Results in:

```
Not allowed to load local resource: file:///C:/Test/JSTest/target/scala-2.11/resource_managed/test/test-runner.css
Not allowed to load local resource: file:///C:/Test/JSTest/target/scala-2.11/jstest-test-jsdeps.js
Not allowed to load local resource: file:///C:/Test/JSTest/target/scala-2.11/jstest-test-fastopt.js
```

Would it be possible to generate relative paths instead, like this?

```
        <link rel="stylesheet" type="text/css"
              href="./resource_managed/test/test-runner.css" />


        <script type="text/javascript"
                src="./jstest-test-jsdeps.js"></script>
        <script type="text/javascript"
                src="./jstest-test-fastopt.js"></script>
        <script type="text/javascript">

```

**Comment by gzm0** [comment]
I do not fully understand why your browser does not allow you to load a local resource from a local file. But the request is fair: Having relative URLs there is probably better anyways.

**Comment by OndrejSpanel** [comment]
The Chrome security policy is a page cannot use `file:///` unless the page itself is a `file:///` (same origin policy, I understand other browser implement more or less the same). I use IntelliJ IDEA to run the file, which provides a local web server when debugging a web page. The runner is therefore running using `http://`, and such page is unable to use local files.

**Comment by gzm0** [comment]
Ah, that explains it :)
