### ISSUE TITLE
`test` task crashes if there is no testing framework (instead of succeeding with 0 test)

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2752]
Discovered by the community build, see https://github.com/scala/community-builds/issues/465
Reproducible with `library/test`.

> The thing is: `library/test` is empty; it doesn't have any test. Most importantly, it doesn't have any testing *framework*, and that means it doesn't depend on our testing interface. The changes in https://github.com/scala-js/scala-js/pull/2740 cause the `test` task to crash if the testing interface is not in scope, whereas before it would silently (and correctly) return an empty list of testing frameworks, and hence execute 0 test.

**Comment by gzm0** [comment]
Nice! I so would have hit this with #2645 :P
