### ISSUE TITLE
Global NPM modules should be available

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#2756]
When running tests in nodejs, it seems that each SJS project is expected to install ` jsdom` & `source-map-support` locally and gitignore `node_modules`. Instead, (or rather: additionally), a user should be able run `npm install -g jsdom source-map-support` once on their system.

Related: #2642, #2665 .

**Comment by sjrd** [comment]
This seems to be a misconfiguration of Node.js. I can solve this problem on my machine by applying the solution described here: http://stackoverflow.com/a/14515868/1829647

**Comment by japgolly** [comment]
Confirmed, thanks.

Instructions here: https://gist.github.com/japgolly/775314a0cb24e33653b059b8f8540250
