### ISSUE TITLE
Allow @JSExport from build files for multiple projects sharing source code

### ISSUE THREAD

**Issue by Randelung** [scala-js/scala-js#2757]
I'm working on a large project that should produce 75 standalone JS files. The projects share a lot of code. At the moment I have to annotate each root object, compile, remove annotations, and repeat for each output file. Is there a way to designate root classes as arguments to sbt? I was hoping for something to include in build scripts, like 

sbt fullOpt class1.scala outFile1.js
sbt fullOpt class2.scala class3.scala outFile2.js

The only alternative I can think of is creating 75 projects and linking files, but that seems a little drastic. Thanks!

**Comment by sjrd** [comment]
> The only alternative I can think of is creating 75 projects and linking files, but that seems a little drastic.

That is the expected way to do it, I'm afraid.

**Comment by andreaTP** [comment]
Don't know if this can help but probably you could benefit from the annotation_adder compiler plugin used in Akka.js, but there is some work to do to achieve your goal.

**Comment by Randelung** [comment]
Hm, that's too bad... Makes automation somewhat cumbersome.

I guess I should be thankful scala-js exists in the first place, though. :D So thanks! And thanks for the quick answer!
