### ISSUE TITLE
`UndefOr` could have `contains` implemented like `Option`

### ISSUE THREAD

**Issue by OndrejSpanel** [scala-js/scala-js#2758]
Currently `UndefOr` has many members similar to `Option`, but I do not see `contains`. The workaroud is easy, either I can use `.toOption.contains(x)` or `.exists(_ == x)`, however as direct implementation should be straightforward, I think it could be added (unless there is some reason not to do so).

**Comment by sjrd** [comment]
That's probably because `Option.contains` was added in a later version of Scala, and we haven't ported that addition. We should definitely do it.
