### ISSUE TITLE
Micro optimisation: identity function reuse

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#2781]
When compiling with `CheckedBehavior.Unchecked`, I think it would be a tiny improvement to output JS size and runtime memory to generate a single JS function `function(x){return x}` and have all calls to `Predef.identity` simply reference it. At the moment, every time `identity` is supplied as an argument to an `A => B`, It seems that a new anonymous fn is generated.

What do you think?

**Comment by sjrd** [comment]
Unfortunately, that is not a semantics-preserving rewriting, so it's outlawed for an optimizer. The reason is that it would change the result of an `eq` or `==` test between two eta-expansions of `identity`.

**Comment by japgolly** [comment]
Yeah right, fair enough. Oh well, thanks, I'll close this now. Good thing is that it's easy enough to implement in userland for one's own usage (i.e. excluding classpath usage).
