### ISSUE TITLE
FastOpt is not consistent with fullOpt in Module enclosing function, when emitting CommonJSModule

### ISSUE THREAD

**Issue by cuzfrog** [scala-js/scala-js#2785]
When `scalaJSModuleKind := ModuleKind.CommonJSModule`,
`fullOptJS` produces module with an enclosing function, while `fastOptJS` does not.

BTW: 

Suggest adding enclosing functions rather than not. It provides better consistency when `-opt.js` acts as a chunk file containing many modules. As it provides one more ways to emit multiple modules within one scala/sbt project without sub-project. See [MDN strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode)

**Comment by sjrd** [comment]
`ClosureLinkerBackend` indeed [unconditionally adds the IIFE](https://github.com/scala-js/scala-js/blob/v0.6.15/tools/jvm/src/main/scala/org/scalajs/core/tools/linker/backend/closure/ClosureLinkerBackend.scala#L144-L145). It shouldn't do this when `moduleKind == CommonJSModule`.

> Suggest adding enclosing functions rather than not.

When the module kind is `CommonJSModule`, Scala.js emits a CommonJS module. Unlike scripts, CommonJS modules cannot be freely concatenated anyway, strict mode or no strict mode. To combine several CommonJS modules, you need bundler such as Webpack.
