### ISSUE TITLE
Cannot access `class`es, `let`s and `const`s in the global scope

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2800]
See http://stackoverflow.com/q/42745118/1829647

To fix this, we really need to access the global *scope*, not the global *object*.

For some relevant theory, read: http://www.2ality.com/2015/02/es6-scoping.html#the_global_object

Basically, since ES 2015, there are things that are in the global *scope* but not in the global *object*: top-level `let`s, `const`s and `class`es. This means that our internal scheme and surface semantics of only allowing access to the global object is not enough.

This is a major, severe, critical and whatever-you-wanna-call-it limitation, which we absolutely need to fix by 1.0.

**Comment by sjrd** [comment]
So ... this is going to be hard. Language-wise, I would propose the following (spoiler: it's a breaking change):

First, we change our "spec" so that we do not refer to the global *object* anymore. Instead, everything that was referring to the global object now represents the global scope. In particular:
* `js.Dynamic.global`
* `@JSGlobal`-annotated things
* `@JSGlobalScope`-annotated things (fitting, isn't it?)

Concretely, this incurs the following breaking change, language wise: it is not possible to grab the *value* of a global scope thing anymore. Any reference to a global scope must be immediately followed by a `Select` (i.e., `foo.bar`) that selects a member of the global scope. That thing must, in addition, have a JS name which is a constant, valid JS identifier (a fortiori, not a symbol). The whole selection becomes a reference to that identifier in the global scope.

For example:
```scala
val x = js.Dynamic.global // illegal: cannot load the value of `global` without a `.`
val y = js.Dynamic.global.selectDynamic("[") // illegal: "[" is not a valid JS identifier
val ybis = js.Dynamic.global.selectDynamic(someVal) // illegal: not constant
val z = js.Dynamic.global.foo // legal, and represents `foo` in the global scope

@js.native @JSGlobal
object Bar extends js.Object

val bar = Bar // legal, and it means `Bar` in the global scope (as opposed to `<global>.Bar` in the current spec)

@js.native @JSGlobalScope
object Glob extends js.Object {
  val foobar: String = js.native
}

val glob = Glob // illegal: Glob is like `js.Dynamic.global`
val foobar = Glob.foobar // legal, represents `foobar` in the global scope
```
In the IR, we could have a new IR node `GlobalRef`, similar to `VarRef`, but that guarantees that it accesses a global variable.

Now the *really* tricky part is, how to *implement* it in `FunctionEmitter`?

If we have for example `GlobalRef(Ident("Foo"))`, potentially we can just emit `Foo` in the resulting .js, if we make sure not to "allocate" the name `Foo` to any local variable (doable with a simple scan per method).

But if we have `GlobalRef(Ident("$c_sci_List"))`, how do we prevent it from clashing with the definition of the class `List`!?

**Comment by gzm0** [comment]
Just a note aside: I really like that this will allow us to get away with the stupid "global detection" :)

> But if we have GlobalRef(Ident("$c_sci_List")), how do we prevent it from clashing with the definition of the class List!?

Pull all the globals in in the top-level scope and use an IIFE to protect the names? Like so:

```javascript

let safe_auto_determined_id1 = Foo;
let safe_auto_determined_id2 = $c_sci_List;

(function() {
// all of Scala.js, using safe_auto_determined_idN when finding a GlobalRef(...)
});
```

**Comment by sjrd** [comment]
> Just a note aside: I really like that this will allow us to get away with the stupid "global detection" :)

That is one nice side effect of the whole thing, yes.

> Pull all the globals in in the top-level scope and use an IIFE to protect the names? Like so:

Well they'd have to be 0-arg functions so that they reflect changes, plus we need the setter versions as well. But yes, that works. However I'm afraid of the consequences in CommonJS modules, and even more so in ES modules later: how do we export things out of that IIFE without preventing JS bundlers from dce across the boundary?

> Will we allow to refer to the global `this`?

I hope we can avoid it, but I haven't thought through the consequences of that.

**Comment by gzm0** [comment]
Ok, even dumber solution: We know all the needed `GlobalRefs` at emission time (put them in Infos?). Therefore, we can construct magic identifiers for these that:
- We look up in a map.
- Are in their own namespace.

The performance implications to make a set lookup each time we refer to the env would have to be measured, but it wouldn't astonish me if the JIT would simply get rid of it when running on a normal codebase.

**Comment by sjrd** [comment]
Er ... how do you put them in the map in the forest place? Assuming we want to keep the Scala.js internals at the top level of the module, accessing the globals is already shadowed by the internals.

I think we have no choice but to rename the internals if there is a `GlobalRef` that happens to have an internal name :-s

**Comment by gzm0** [comment]
> I think we have no choice but to rename the internals if there is a GlobalRef that happens to have an internal name :-s

Yeah that's what I meant.

**Comment by sjrd** [comment]
Ah I see. I had *completely* misunderstood your previous comment. I thought the map was at run-time, in the generated .js ^^

**Comment by sjrd** [comment]
I actually think we can implement this in 0.6.x. The legal parts will be compiled with the new scheme, and the illegal parts will be compiled as before, but issue a deprecation warning.

**Comment by sjrd** [comment]
I have a wip in https://github.com/scala-js/scala-js/compare/0.6.x...sjrd:global-scope

It turns out that change is *not* backward source compatible (though it is backward binary compatible). There is a behavior change for references to global variables that do not exist:
```scala
val x = js.Dynamic.global.foo
// old behavior: x <- undefined
// new behavior: a ReferenceError is thrown

js.Dynamic.global.foo = 42
// old behavior: a new global `foo` is created
// new behavior: a ReferenceError is thrown
```
A typical pattern that gets broken is:
```scala
if (js.isUndefined(js.Dynamic.global.foo))
```
which now throws a `ReferenceError` instead of returning `true`. The fix for this pattern is to write
```scala
if (js.typeOf(js.Dynamic.global.foo) == "undefined")
```
And that's because `js.typeOf(x)` becomes more magical than it was if it is given as a direct argument a reference to a global variable (as magic as `typeof x` in JS). In fact it must now be reasoned about as if it were a macro, since its evaluation model is not consistent with method calls in Scala: `js.typeOf(x)` is not always equivalent to `val y = x; js.typeOf(y)`.

For that reason, we cannot change the *implementation* of `isUndefined` in any way that would fix the issue. We could make it a macro that desugars `js.isUndefined(x)` into `(js.typeOf(x) == "undefined")`, which is actually reasonable. (because we don't want macros in core, it would actually be made a primitive, just like `js.typeOf` itself).

Regardless of the `js.isUndefined` pattern, we need to find a migration path. I would suggest a compiler flag `-Pscalajs:useGlobalScopeSemantics` to activate the new semantics of selecting in the global scope. And we could issue a deprecation warning if that compiler flag is not specified.

Also, we'll need a `-Pscalajs:suppressGlobalObjectValueDeprecations` flag to suppress the above deprecation, as well as all the deprecations triggered when the global object is loaded as a value (rather that used in a `.`-selection).

**Comment by sjrd** [comment]
Almost done: https://github.com/scala-js/scala-js/compare/master...sjrd:global-scope

Now it will actually globally rename the internal `$c_O` (for example) if somewhere in the program someone refers to the global variable `$c_O`.

Still to do:
* Rename internal variables in `scalajsenv.js` if they're used as global variables
* List used global variables as externs for GCC
* Consider `@JSGlobal` stuff as global variables (currently it's only for `js.Dynamic.global.Foo` and `@JSGlobalScope`s)
* Options to suppress deprecations
* Possibly make `js.isUndefined` a primitive

**Comment by gzm0** [comment]
How does this affect facades that do this:

```scala
@JSGlobalScope
object Foo extends js.Object {  // Note aside: This extending js.Object is terrible :P
  var x: Int = js.native
}

Foo.x = 1  // Reference error?
```

Or even:

```scala
@JSGlobalScope
object Foo extends js.Object {
  def x: js.UndefOr[Int] = js.native
}

println(Foo.x)  // Reference error?
```

Will there be a way to have a facade for a global variable that is maybe defined?

**Comment by sjrd** [comment]
Yes those will throw `ReferenceError`s.

> Will there be a way to have a facade for a global variable that is maybe defined?

We cannot introduce such a feature without re-baking in the language the detection of the global object. Indeed, from a *module* (CommonJS our ES), one needs the global object to create a new field in the global scope. In a top-level *script*, a `var`/`let`/`const`/`class`/`function` will create a new identifier in the global scope, so our *exports* should make sure to do that when emitting in `NoModule`.

**Comment by sjrd** [comment]
`extends js.Object` can be `extends js.Any`, which is already much better ;)

**Comment by gzm0** [comment]
LOL, I just got an upvote for this:
http://stackoverflow.com/questions/38766317/how-to-create-global-javascript-variable-in-scala-js/38767015#38767015

**Comment by sjrd** [comment]
I'm facing yet another setback with this, related to `@JSGlobal`. Unlike `js.Dynamic.global` and `@JSGlobalScope`, which are compile-time (`@JSGlobalScope` used to be link-time but it now has to be compile-time), the way we load `@JSGlobal` stuff is a link-time decision, because we emit `LoadJSConstructor`/`LoadJSModule` for those.

But, now we want to have a compile-time flag `-Pscalajs:useGlobalScopeSemantics` to switch on the global scope-based semantics. Since that flag is at compile-time, we cannot influence the semantics of the loading through `LoadJSConstructor`/`LoadJSModule`. One solution would be to introduce temporary (to disappear in 1.x) additional IR nodes `LoadJSConstructorGSSemantics`/`LoadJSModuleGSSemantics`. Under compilation with the new semantics, those IR nodes will be used. The linker can therefore know which one to use.

*However*, those IR nodes do not account for all link-time decisions to load from the global scope. We also have all the super references in Scala.js-defined JS classes: `JSSuperConstructorCall`, `JSSuperBracketSelect` and `Assign(JSSuperBracketSelect, _)`, which indirectly have to generate the same as a `LoadJSConstructor`. Do we also create new IR nodes for those?

The worst happens in the "extends clause" of a Scala.js-defined JS class, as that is not even an IR node (it's directly in the `ClassDef`). Should we add a flag in the `ClassDef` node to use the new semantics when loading the superclass?

All of that is possible, but it's getting ugly. At least that ugliness will only last during the 0.6.x series, whose lifespan is getting short.

### Alternative: link-time flag

Now we have a completely different alternative which would be to have a *link-time* flag to decide to use the new semantics. This solves all the technical problems outlined above. However, it creates one "eco-system" issue. Indeed, if you want to apply the flag to use the new semantics, they will also apply to all your dependencies. And that might (likely will, for Scala.js-specific deps) break them. This means that migration to the new semantics cannot happen in parallel in the entire eco-system. Instead, you have to wait for your dependencies to publish a new version ready for the new semantics. Basically, this won't work; people won't migrate.

**Comment by gzm0** [comment]
Shouldn't the decision how to load an `@JSGlobal` class be made when the class is compiled, rather than when usage code is compiled?

So just to be clear, given this:

project 1
```scala
@JSGlobal
@js.native
class Foo extends js.Object
```

project 2
```scala
val x = new Foo()
```

IMO whether `new Foo()` gets translated to `new Foo()` or `new global.Foo()` should depend on `project 1`'s compilation settings, no? Otherwise we create the same "eco-system" issue IIUC.

So in that case IIUC the loading semantics is "just" a flag in `JSNativeLoadSpec.Global`, which seems acceptable.

**Comment by sjrd** [comment]
No I thought about that too, and IMO it's worse for the eco-system. Now we have the opposite issue: a library cannot upgrade to the new semantics without doing a "semver major version bump", because the new version of the library is not backwards compatible with its previous version. Indeed: the call `js.constructorOf[Foo]`, which used to give `undefined`, now throws.

Since libs don't want to do breaking changes like that for the sake of their users, they also won't upgrade. Which means as a user I never get to experience/test the new semantics.

**Comment by gzm0** [comment]
Hmmm... This all makes me wonder: Do we really need to target 0.6.17 with this? Because it seems like this has the potential to cause havoc in the ecosystem dependency tree. It really seems like it is better to solve this by bumping the sjs major version. Have you considered making a 0.7.0 if we are uncomfortable with launching this in 1.0.0 untested? It would put some additional burden on library maintainers, but it seems that even for them it would be easier than having to juggle flags and not knowing how downstream consumes their things... :-/

Not sure which is a larger burden for us though: Having another branch or dealing with the ugly IR...

**Comment by sjrd** [comment]
I'm pretty sure an additional branch is the bigger burden. So I think 0.7 is not the solution. If it's about the not release it untested, that's also why we have milestones and RCs.

I wanted to have it in 0.6.x to allow people who need this feature to use it now. But sure we could implement this only in 1.x. The migration path might be a bit abrupt, maybe no more than this flag juggling anyway.

**Comment by gzm0** [comment]
> I wanted to have it in 0.6.x to allow people who need this feature to use it now. But sure we could implement this only in 1.x

It might be better to focus on getting 1.x out faster in this case. I'm having a hard time gauging the annoyance this causes, so it is hard to see whether we are in a "there is only a deprecated and a not ready path" or a "this feature is just not yet implemented" situation.

**Comment by sjrd** [comment]
Honestly I don't know either how annoying this is. Supposedly, not *very* annoying, since most real-world websites need to emit ES5.1 at the end of the day even for their ES6 code, through Babel or some other compiler. I guess this is mostly annoying in the dev cycle of people using an ES6 codebase alongside Scala.js, as they need to add `window/global.Foo = Foo;` after `class/const/let Foo`.

My plan for 1.x is definitely to have an M1 soon (like beginning of June at the latest). In that milestone we would have removed/extracted everything that will eventually be removed/extracted (so jsdom, PhantomJS, jsDependencies), so that further milestones are (almost) backward *source* compatible with M1. We could throw in this feature instead of getting it in 0.6.x. People who need this feature would be highly encouraged to migrate to 1.x ahead of the others ;)

**Comment by gzm0** [comment]
After a good night's sleep, I think we should target 1.0.0 only with this. The main reason is that the transition semantics we can offer are probably too complicated for someone to really understand (I still have a hard time understanding all the implications). It is probably much easier for everyone if we say: "1.0.0 will have this semantic change" and everybody tests that their stuff still works with this (which they will anyways, because it is a major version upgrade) and we can kill two birds with one stone.

**Comment by sjrd** [comment]
OK let's do that, then.
