### ISSUE TITLE
js.constructorOf[Foo].x blows up with a "stub" error

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2804]
```scala
println(js.constructorOf[Foo].x) // blows up
println(js.constructorOf[Foo].y) // works!
```
I'm pretty sure that's because the hack in the compiler plugin that gets around `someDynamic.x` fails to recursively transform the receiver, or something like that.

**Comment by gzm0** [comment]
Hmmm... I'm looking into this and the thing is, there is nothing special about anything in `js.Dynamic`. It's just `@JSBracketAccess` for the dynamic things and a plain old facade type for `x` and `x_=`. :-/

**Comment by sjrd** [comment]
There is a bit of magic in `PrepJSInterop`: https://github.com/scala-js/scala-js/blob/0fc3654b315fad0d7d22c02fe9ad50a0dac126ef/compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala#L330-L351
