### ISSUE TITLE
Ability to create new JavaScript classes dynamically

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#2805]
How can I create a function that creates and return new ES6 classes?

This approach (obviously) doesn't work:
```scala
  def newClass(nameArg: String): js.Dynamic = {
    @ScalaJSDefined
    class X extends js.Object {
      def name = nameArg
    }
    js.constructorOf[X]
  }

newClass("A") eq newClass("B") // returns true
```

One solution is to use macros. Any other ideas or suggestions?

**Comment by sjrd** [comment]
Ah ah! @gzm0 I've told you someone would end up needing this ^^

@japgolly We've discussed this internally. It's not yet possible. It's a gap in our interoperability features. It is scheduled for 1.0, with precisely the syntax you suggest above.

If you desugar down to ECMAScript 5.1 for now, a workaround is to create it manually as a `js.ThisFunction`, and then patching its `prototype`:
```scala
val X = (((thiz: js.Dynamic) => ()): js.ThisFunction).asInstanceOf[js.Dynamic]
X.prototype.name = nameArg
X
```
If however you're actually emitting ECMAScript 6, you're out of luck until Scala.js supports it in 1.0.

**Comment by japgolly** [comment]
Cool, thanks for the workaround. I think I'll just leave it for now. Do you have a rough idea of when 1.0.0 will be out?

**Comment by sjrd** [comment]
A rough idea would be 3-4 months. As soon as 0.6.15 is published, the master branch of the repo will target 1.0.0.
