### ISSUE TITLE
Adjust to Scala 2.13 moving parallel collections into a module

### ISSUE THREAD

**Issue by SethTisue** [scala-js/scala-js#2811]
we are interested in keeping Scala.js in the Scala 2.13 community build continuously throughout the 2.13 cycle, if at all possible, because Scala.js is so important in itself, and because so many other projects in the community build depend on it

after the merge of https://github.com/scala/scala/pull/5603, Scala.js no longer compiles on 2.13 because of the references to parallel collections in scalalib/overrides-2.13/scala/collection/immutable/Range.scala (see [example failure log](https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/283/consoleFull))

I thought I might try to patch it myself, but I don't really understand what the `overrides` directories are for, and when I diff your Range.scala against the one in Scala 2.13 HEAD, I see other differences besides just ones related to parallel collections.

so... is this a change y'all could do yourselves...? 🙏

**Comment by SethTisue** [comment]
you can reproduce the failure outside of dbuild with:

```
set resolvers += "scala-integration" at "https://scala-ci.typesafe.com/artifactory/scala-integration/"
++2.13.0-pre-e2a2cba
scalalib/compile
```

**Comment by gzm0** [comment]
The overrides are replacements for scalalib implementations when we can't take them as they are (for JDK dependencies or efficiency reasons). So it's probably as simple as just backporting the changes made in the 2.13 branch. I'll look into it.

**Comment by sjrd** [comment]
The fix for this issue has now been made its way to master as well.
