### ISSUE TITLE
Revisit visibility in tools API

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#2812]
We probably should split the tools in two different levels of compatibility:

- User interface (stuff used by sbt plugin, etc.). This has very strong compatibility requirements to make sure normal users do not break.
- Plugin interface (stuff internal to phases, etc.). This should have more relaxed compatibility requirements to allow us to still do stuff. Plugin writers will have to (to a hopefully mild extent) deal with breaking changes here.

**Comment by sjrd** [comment]
We can probably remove `Linker.linkUnit`, as someone who really wants that method can just use the `LinkerFrontend.link` method. `Linker.linkUnit` is a direct forwarder to `frontend.link` anyway (with a concurrent-use guard).

**Comment by sjrd** [comment]
I think #2998 has basically taken over the topic of this issue.
