### ISSUE TITLE
Shave off some (public) sbt keys

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#2813]
There are way too many keys for JS dependency loading and JS Env loading. Candidates for removal:

- `scalaJSConfigurationLibs` (only used for `scalaJSJavaSystemProperties`).
- `loadedJSEnv` (only used due to `LinkingUnitJSEnv`).
- `scalaJSPhantomJSClassloader` (only used for PhanomJS).
- `resolvedJSEnv` (can be replaced by a default value on `jsEnv`).

**Comment by sjrd** [comment]
The above four candidates have been removed (or moved to a separate sbt plugin in the case of `scalaJSPhantomJSClassLoader`). Here are a few more, though:

* `scalaJSConsole`: there does not seem to exist an equivalent feature for JVM projects (a setting providing easy redirection of the console), so it seems like this is just useless complexity.
* `relativeSourceMaps` and `emitSourceMaps`: they could be part of `scalaJSOptimizerOptions` (which should really be renamed to `scalaJSLinkerOptions` anyway)
