### ISSUE TITLE
Source Maps bug - wrong column in the generated file

### ISSUE THREAD

**Issue by Gralfim** [scala-js/scala-js#2821]
There seems to be a bug in the class `JSTreePrinterWithSourceMap` causing that the source maps does not exactly match the generated file.
The class has two purposes:
1. it generates the output javascript code using its base class `JSTreePrinter`
2. it maintains the position in the javascript (in `private var column`) and uses it to generate source map (using `sourceMap: SourceMapWriter`)
To serve well for both these functions, there is necessary to keep `var column` synchronized with the position in `out` stream (see `override protected def print(s: String): Unit`). However, in the function `override protected def print(ident: Ident): Unit` (and one similar place) there is some writing to `out` without change of `var column`.

**Comment by sjrd** [comment]
Thanks for filing the issue :+1:

**Comment by Gralfim** [comment]
We tried to fix the issue in request #2819, however some formalities need to be fixed yet.

**Comment by sjrd** [comment]
Fixed in #2819.
