### ISSUE TITLE
Remove support for Rhino

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2823]
Rhino was deprecated in Scala.js 0.6.13 because it has an insane amount of influence on our internal design, and is taxing our maintenance costs.

**Comment by sjrd** [comment]
This one is for me. I've been waiting so long to get rid of this.

**Comment by ritschwumm** [comment]
is there any other way to unit-test scala-js code without having to install a secondary VM like node.js?

and if not, is or will there at least be a way to run specs2 tests from sbt on a cross projects without getting an exception when node.js is not installed?

if possible in any way, i'd like to be able to tell people "you build it like any other scala project. if you have a JVM and SBT installed, you're good to go".

**Comment by sjrd** [comment]
Unfortunately no, there won't be a way to test Scala.js without Node.js or another secondary VM.

It is perfectly possible to run Specs2 tests on a cross-project without exception: simply only run `specs2JVM/test`, or something like that. But to test the `specs2JS/test` part of it, you will need a JS VM (preferably Node.js, which is the easiest to install and the fastest).

> if possible in any way, i'd like to be able to tell people "you build it like any other scala project. if you have a JVM and SBT installed, you're good to go".

This will still be true for the JVM part of the builds. Unfortunately, it is my impression that many library maintainers have chosen a route where `foo` is an *aggregate* of `fooJVM` and `fooJS`, causing `foo/test` (or simply `test`) to execute *both* `fooJVM/test` and `fooJS/test`. I think this is a mistake.

The main reason is that it increases the time taken by `test` a great deal. This is really not what you want to happen *by default* on a build. By default, I want fast tests. I want to assume that whatever I'm doing, if it works on the JVM, will also work on JS. And I expect my CI to notify me otherwise. If and when I need to debug something that works only on the JVM, then I'm willing to pay the time tax of executing the JS tests (obviously). But really, by default, I only want to run the JVM tests.

The fact that Node.js will be required for `fooJS/test` to work is only a secondary reason why `foo` should not be an aggregate.

Instead, I would recommend that library authors configure `foo` to be an aggregate of `fooJVM` alone. This will help everyone in the common cases, and only the CI script might get a tad more verbose (but it should anyway, so that the logs of the JVM and JS run are not interleaved, so ...)

**Comment by ritschwumm** [comment]
right, not aggregating the fooJS/test is indeed a good and simple solution for my immediate problem. thanks, for some reason i did not think about that.

do i assume correctly that replacing rhino with nashorn (even if it didn't have the bytecode-per-method-size problem) would not help much converning your design impact and therefore maintenance costs?

**Comment by sjrd** [comment]
Actually, if it weren't for the bytecode-per-method-size problem, we could support either or both of Rhino and Nashorn for an almost zero cost. And we could even do that in a separate repo like we did for Selenium.

This issue is the root cause of all of our problems. It is the reason we needed to build the Rhino support in a way that hijacks the internals of the linker to build parts of the result piecemeal, to feed them to Rhino in small portions. And this is why we have to keep one of our output modes (our "backends", so to speak), the one that is fundamentally different from the others. That's the part that is really taxing us, because any change to our backends requires duplicate effort just for the sake of Rhino.

Who knows, with Rhino gone from the core, maybe someone dedicated enough will manage to build an integration like we have for Selenium on their own repo despite the bug, either for Rhino or Nashorn...

**Comment by ritschwumm** [comment]
you mean https://github.com/scala-js/scala-js-env-selenium i guess -
i'll have a look at what's being done there.

**Comment by ritschwumm** [comment]
i wasn't aware how much rhino support costs, complexity wise. thanks for the explanation.

with selenium integration mean https://github.com/scala-js/scala-js-env-selenium i guess -
i'll have a look at what's being done there.

**Comment by sjrd** [comment]
Yes that's the right link for Selenium ;)

**Comment by vn971** [comment]
Does something work out-of-the-box now that Rhino is gone? Like only requiring sbt and java?

**Comment by sjrd** [comment]
> Unfortunately no, there won't be a way to test Scala.js without Node.js or another secondary VM.

**Comment by vn971** [comment]
@sjrd sorry, got it, thanks.
