### ISSUE TITLE
Missing addSbtFiles method for crossProject

### ISSUE THREAD

**Issue by Atry** [scala-js/scala-js#2824]
There is a `addSbtFiles` method on `sbt.Project`. However, `CrossProject.Builder` does not have the method.

I use method to share sbt settings between cross project.
https://github.com/ThoughtWorksInc/Binding.scala/blob/8d0815e/build.sbt#L13

It would be nice if the method can be written on `crossProject`

**Comment by sjrd** [comment]
Note that you can always use `configureAll` to apply some esoteric functions on all `Project`s of a `CrossProject`. For example, `.configureAll(_.addSbtFiles(file("...")))`.

**Comment by Atry** [comment]
Thank you. It's a very useful tip.

**Comment by sjrd** [comment]
[`Project.addSbtFiles` was removed in sbt 1.x](https://github.com/sbt/sbt/pull/3068/files#diff-de5d62c45e935f985b9d89ee74531dedL213), so I'll close this issue as a won't fix. No point in adding now a forwarder to a method that disappears in sbt 1.
