### ISSUE TITLE
Move PhantomJS out of the core

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2839]
`PhantomJSEnv` should go in a separate library, just like Selenium. Unlike Selenium, though, it requires special help from the sbt plugin to resolve jetty8, so we need to also publish an accompanying sbt plugin to ease the use site of `PhantomJSEnv`.

Basically the same API should be supported, but would require an additional `addSbtPlugin(...)` in builds that want to use PhantomJS.

We can do this in two steps:

- [x] Logically extract the parts of the sbt plugin that deal with PhantomJS in a separate `AutoPlugin`, but still in the same repo
- [ ] Physically move `PhantomJSEnv` and that new `AutoPlugin` to a separate repo

**Comment by gzm0** [comment]
By the way, I'm not sure we need to do the whole plugin thingy. Maybe we should see if anyone even needs this (the reason we do this is to insulate jetty8 from the classpath, we do not need to do so).

Might be hard to try out in 0.6.16 though :S

**Comment by sjrd** [comment]
We could remove the plugin (or not publish it) once PhantomJS is in its own repo, and see what happens in M1. Anyway once it is on its own repo, it will be easy to quickly publish a new version if people ask for it.
