### ISSUE TITLE
Move javalib-ex out of the core (or just plain remove it?)

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2840]
Historically, `javalib-ex` has contained parts of the JDK that were implemented on top of non-standard JS features, or even depending on some JS libraries. Today, though, the only remaining thing is `ZipInputStream`, and it's not even complete.

The reason this thing exists in Core is that we need for the bootstrap test. Indeed, we need to unzip the .jars containing the .sjsir files in the bootstrapped linker, and we do that through `ZipInputStream`. However, for the purposes of the bootstrap tests, I think we should simply integrate zip reading in the bootstrap test classpath (which is not published), rather than depending on `javalib-ex` for that purpose.

This would then allow us to move `javalib-ex` out of the core. Since it's so small and rather incomplete, maybe it should just be removed. [Scaladex suggests that no one depends on it](https://index.scala-lang.org/scala-js/scala-js/scalajs-javalib-ex?target=_2.11). That said, to keep our promise on backward source compatibility, we should probably still publish it somewhere in a separate repo (possibly even a personal repo rather than one under `org.scala-js`).

Action items:

- [ ] Remove the dependency on `javalib-ex` in the bootstrap test
- [ ] Move javalib-ex out of the core

**Comment by gzm0** [comment]
I vote for remove it. Can we simply not publish it for 0.6.16 and see if someone complains?

**Comment by sjrd** [comment]
We could do that, lol.

**Comment by gzm0** [comment]
> Can we simply not publish it for 0.6.16 and see if someone complains?

I mean of course we should also write this explicitly in the release notes. I'm not talking about a ninja-remove. But our release processes are definitely not overhead free. So if we can save ourselves some work that is not useful to anyone, why not do it :)

**Comment by sjrd** [comment]
Well, given our current infrastructure, it would be more work *not* to publish it for 0.6.16. :P

I suggest we simply remove it now, and let people complain in M1. Even if they complain after 1.0.0 final is out, it's still possible to start it off as a separate project afterwards. But let's not "experiment" with removals in 0.6.x.

**Comment by gzm0** [comment]
Good point. Let's do that.
