### ISSUE TITLE
Too many different reactive DOM libraries with similar goals

### ISSUE THREAD

**Issue by fdietze** [scala-js/scala-js#2843]
(Sorry for posting this here, I don't know a better place. Please tell me if I should move the discussion elsewhere.)

Hi everyone,

I noticed that there are several ScalaJS libraries following the approach of mapping reactive variables to the DOM: [Binding.scala](https://github.com/ThoughtWorksInc/Binding.scala), [Outwatch](https://github.com/OutWatch/outwatch), [monadic-html](https://github.com/OlivierBlanvillain/monadic-html), [scalatags-rx](https://github.com/rtimush/scalatags-rx), [MetaWeb](https://github.com/MetaStack-pl/MetaWeb) (and probably some more I don't know, please post them here).
Involved contributors: @Atry, @LukaJCB, @OlivierBlanvillain, @olafurpg, @rtimush, @lihaoyi, @tindzk

Every library introduces some advantages and therefore defines shortcomings for the others at the same time (again, this list is probably incomplete):
- Virtual DOM for efficient updates (Outwatch)
- Delta updates of reactive lists and DOM (MetaWeb)
- Let the user access the reactive values as monads (monadic-html, scalatags-rx)
- Prevent memory leaks (scalatags-rx)
- Avoiding unnecessary updates by handling the diamond-case in the reactive dataflow graph (https://github.com/lihaoyi/scala.rx/issues/79)
- The markup is written in XML/Scalatags/some other DSL
- Macro-based to avoid boilerplate / Library-based to avoid long compile-times and obscure errors

So each library is basically a compromise, because it lacks the advantages of the others.
I would like to see more collaboration between the authors and libs, since the goals are all very similar, although I'm unsure how this would look like in practice. Or is this already the case? I guess every library author has something to say here.

**Comment by Atry** [comment]
I don't want to criticise other Scala libraries here 😏

**Comment by sjrd** [comment]
This issue tracker is definitely not the right place to discuss this, as it has nothing to do with the scala-js/scala-js repo. The mailing list might be more appropriate: https://groups.google.com/forum/#!forum/scala-js

**Comment by SRGOM** [comment]
@Atry I'd like to point out that your statement here https://gitter.im/ThoughtWorksInc/Binding.scala?at=581b6367eed0c3125f30d57b about scala.rx recreating the entire dom on data update is inaccurate. Just pointing out.

**Comment by fdietze** [comment]
I'm sorry. I just posted the same in the mailing list:
https://groups.google.com/forum/#!topic/scala-js/77J_RdnWu_k

Let's continue the discussion there.

**Comment by Atry** [comment]
@SRGOM I don't think I said anything about scala.rx.
