### ISSUE TITLE
Support Scala 2.11.9

### ISSUE THREAD

**Issue by xuwei-k** [scala-js/scala-js#2847]

**Comment by sjrd** [comment]
Let's wait until there's at the very last an internal announcement. Maven artifacts are not enough to be called a release for such big projects.

**Comment by sjrd** [comment]
FYI, Scala.js 0.6.15 has been released for 2.11.9.

We still need to add it in the codebase for later versions.

**Comment by xuwei-k** [comment]
I got linking error :frowning:

```
[error] Referring to non-existent class scala.collection.immutable.FilteredTraversableInternal
[error]   called from scalaz.std.ListTest$.$$anonfun$9(scala.Function1,scala.collection.immutable.List,scala.Int)scala.collection.immutable.List
[error]   called from scalaz.std.ListTest$.$$anonfun$7(scala.collection.immutable.List,scala.Int)scala.Unit
[error]   called from scalaz.std.ListTest$.$$anonfun$6()org.scalacheck.Prop
[error]   called from scalaz.std.ListTest$.<init>()
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   scalaz.std.ListTest$
java.lang.RuntimeException: There were linking errors
	at scala.sys.package$.error(package.scala:27)
	at org.scalajs.core.tools.linker.frontend.BaseLinker.linkInternal(BaseLinker.scala:158)
```

- https://github.com/scalaz/scalaz/compare/scalaz:d3efbe9...xuwei-k:343b867
- https://travis-ci.org/xuwei-k/scalaz/jobs/217230517#L675
- https://github.com/scala/scala/commit/eb5c51383a63c5c3420e53ef021607ff5fd20296

**Comment by sjrd** [comment]
Uh oh ... seems Scala 2.11.9 is not forward binary compatible with 2.11.8. The Scala stdlib compiled with Scala.js 0.6.15 was built from Scala 2.11.8 (there's only one; we cannot change that now). So you're *compiling* against the 2.11.9 stdlib but *linking* against the 2.11.8 stdlib. According to the forward binary compatibility guarantee of Scala, this should be fine. But apparently it is not in this case.

/cc @adriaanm

**Comment by adriaanm** [comment]
That must be the result of some inlining, right? This class was introduced in https://github.com/scala/scala/pull/5664, which was merged under the assumption that user code won't directly refer to that *Internal class.

**Comment by sjrd** [comment]
> That must be the result of some inlining, right?

That's not possible. We don't use the inliner of scalac, so it's not possible that scalac would have inlined some of the methods accessing *Internal before Scala.js gets to emit its IR. The above linking errors happen before any kind of inlining is attempted (either by scalac or Scala.js' optimizer).

**Comment by adriaanm** [comment]
ok, wow -- we'll look into it before we announce 2.11.9 publicly

**Comment by sjrd** [comment]
@xuwei-k Could you post the output of

    > testsJS/test:scalajsp scalaz/std/ListTest$.sjsir

(in sbt)?

**Comment by xuwei-k** [comment]
https://gist.github.com/xuwei-k/69d917d03549692e53e860977679b3fe

**Comment by sjrd** [comment]
Thanks:

Relevant excerpt:
```scala
@hints(1) def $$anonfun$9__p3__F1__sci_List__I__sci_List(
    isEven$1: F1, a$2: sci_List, b$1: int): sci_List = {
  mod:Lscalaz_syntax_std_ListOps$
    .intersperse$extension__sci_List__O__sci_List(
        mod:Lscalaz_std_list$listSyntax$.ToListOpsFromList__sci_List__sci_List(a$2),
        b$1
    )
    .zipWithIndex__scg_CanBuildFrom__O(
        mod:sci_List$.canBuildFrom__scg_CanBuildFrom()
    )
    .asInstanceOf[sci_FilteredTraversableInternal]
    .filter__F1__O(
        ...
    )...
}
```
@adriaanm Looks like there's a `.asInstanceOf[FilteredTraversableInternal]` (most likely erasure-generated) that crept out on the result of `zipWithIndex`.

**Comment by adriaanm** [comment]
Drad. Thanks for the analysis!!

**Comment by xuwei-k** [comment]
https://github.com/xuwei-k/Scala-2.11.9-FilteredTraversableInternal
