### ISSUE TITLE
java.util.Date return localized values instead of UTC

### ISSUE THREAD

**Issue by andreaTP** [scala-js/scala-js#2858]
From [JavaDocs](https://docs.oracle.com/javase/8/docs/api/java/util/Date.html) : 

> the Date class is intended to reflect coordinated universal time (UTC)

even if there are exceptions mentiond I believe Scala.Js is built ground up assuming default English and UTC Locale.
Probably instead of using methods like `getHours()` we should call `getUTCHours()`.

**Comment by andreaTP** [comment]
Ok I have a repro to discuss on:
https://github.com/andreaTP/scala-js/tree/tz

changing this between these 2 lines:
https://github.com/andreaTP/scala-js/blob/tz/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/DateTest.scala#L19

make the last test consistently succeed/fail.

Run it with something like `testSuite/testOnly *Date*` since no other date method should be called before that line is executed.

**Comment by andreaTP** [comment]
unfortunately it will be hard to find a way... since:
https://github.com/nodejs/node-v0.x-archive/issues/3286
(last comment)

**Comment by sjrd** [comment]
I think you misunderstood the meaning of

> the Date class is intended to reflect coordinated universal time (UTC)

which is actually followed by

> it may not do so exactly

Given the lengthy discussion that follows between the subtle differences between UTC and UT/GMT and UT1, I am pretty sure the "not exactly" part means that it can deviate by 1s from UTC (if it follows UT or something like that).

That said, the `new Date()` constructor definitely returns the timestamp adjusted for the current timezone. On my computer, it definitely returns a date in GMT+2. That's 2 hours away from UTC, not 1 second, so I'm pretty sure this is not what's intended as "it may not do so exactly". Instead, I am pretty sure `new Date()` is supposed to return the date in the current time zone.

Although in Scala.js we have standardized the default locale on English (for practical reasons), the current time zone is definitely the current time zone of whatever environment it is run in. It is not standardized on UTC. Changing that would be an unnecessary deviation from the JVM.

**Comment by andreaTP** [comment]
After a whole evening playing around this, I believe you are right and I checked JVM behavior that is accordingly. I believe I can close this.
