### ISSUE TITLE
ArrayIndexOutOfBoundsException on Safari (iPad)

### ISSUE THREAD

**Issue by nremond** [scala-js/scala-js#2895]
Hello,

The following snippet: https://scalafiddle.io/sf/aIBFLrQ/1 crashes with an ArrayIndexOutOfBoundsException on Safari iPad.

I have tested with ScalaJS 0.6.14 and 0.6.15.

Works fine until iOS 10.3. Only iOS 10.3.1 is impacted from what I have been able to test.

 From what I have been able to see with the debugger, is that an offset is computed as 8 while the array as 8 elements. Very weird, but the same expression returns 7 when evaluated in the debugger.
<img width="1680" alt="screen shot 2017-04-18 at 15 43 34" src="https://cloud.githubusercontent.com/assets/600102/25135166/dfbe42f2-2451-11e7-8d15-61f186659112.png">

I have try to debug further, but I'm a bit confused by the definition of `$imul` and `$g["Math"]["imul"]`

How can I debug that further?

**Comment by sjrd** [comment]
Thanks for the report. However, this definitely looks like a bug in the JavaScript engine. Probably a wrong optimization or codegen bug in general. There's nothing we can do about it.

**Comment by nremond** [comment]
I tried looking at the JS and with the following code, I can't reproduce

```javascript
  var $imul =   (function(a, b) {
    // See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/imul
    var ah = (a >>> 16) & 0xffff;
    var al = a & 0xffff;
    var bh = (b >>> 16) & 0xffff;
    var bl = b & 0xffff;
    // the shift by 0 fixes the sign on the high part
    // the final |0 converts the unsigned value into a signed value
    return ((al * bl) + (((ah * bl + al * bh) << 16) >>> 0) | 0);
  });

  function bitCount(i) {
    var t1 = ((i - (1431655765 & (i >> 1))) | 0);
    var t2 = (((858993459 & t1) + (858993459 & (t1 >> 2))) | 0);
    return ($imul(16843009, (252645135 & ((t2 + (t2 >> 4)) | 0))) >> 24)
  };

  const bitmap = -1588583920;
  const mask = -2147483648;
  const offset = bitCount((bitmap & (((-1) + mask) | 0)));

  console.log("NICO offset["+i+"]="+offset);
```

What I am missing to be able to be sure that's the browser ?

**Comment by sjrd** [comment]
If it's an optimization bug, it might be extremely tricky to reproduce worth any kind of simplification of the code.

If it works in every single other JavaScript engine, that's as good a proof as any that it's a browser bug.

**Comment by nremond** [comment]
OK, closing it

For my culture, what is the definition of the associated function of `$g["Math"]["imul"]` in https://github.com/scala-js/scala-js/blob/741e7c4317ed3e9328505598af1a8040f886626e/tools/scalajsenv.js#L88 ?

**Comment by sjrd** [comment]
That's 32-bit integer multiplication.

**Comment by nremond** [comment]
Ahhh, it's the `Math.imul` Javascript function! Sorry, that was a silly question.
