### ISSUE TITLE
DCE and/or developmentMode broken with 0.6.15 & 2.12

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#2896]
Since upgrading to 0.6.15, scalajs-react has started failing on Travis for Scala 2.12 only (2.11 remains fine).

[There exists](https://github.com/japgolly/scalajs-react/blob/master/core/src/main/scala/japgolly/scalajs/react/vdom/TagMod.scala#L63-L67) a method to create attributes that only work when `LinkingInfo.developmentMode` is set:
```scala
  def devOnly(m: => TagMod): TagMod =
    if (developmentMode)
      m
    else
      Empty
```

Then in order to test it, there is a [test case](https://github.com/japgolly/scalajs-react/blob/master/test/src/test/scala/japgolly/scalajs/react/core/vdom/DevOnlyTest.scala) and then [a script that runs from Travis](https://github.com/japgolly/scalajs-react/blob/master/bin/checkDevOnly) that scans the fastOptJs & fullOptJs output to confirm the absence/presence of the dev-only code.

Since upgrading to 0.6.15, it's begun failing against both Scala 2.12.1 and 2.12.2.
Log is here: https://travis-ci.org/japgolly/scalajs-react/builds/223497088
Relevant ouput is right down the bottom.

This is as far as my investigation goes for tonight. I don't know whether it's the devMode flag or DCE or what yet.

**Comment by sjrd** [comment]
Thanks for the report. I'm have a look when I'm back from vacation, next week.

**Comment by japgolly** [comment]
np, enjoy your vacation!

**Comment by sjrd** [comment]
This is related to the nesting of lambdas involved in writing tests themselves. If I extract the contents of the test in `def`s, the problem does not appear:
```scala
    'tagMod - testTagMod1()
    def testTagMod1() =
      test(div(1, TagMod devOnly p("DEVONLY-TEST"), 2))(
        "<div>1<p>DEVONLY-TEST</p>2</div>",
        "<div>12</div>")

    'tagMod - testTagMod2()
    def testTagMod2() =
      test(div(1, TagMod devOnly TagMod(cls := "DEVONLY-TEST", p("DEVONLY-TEST")), 2))(
        """<div class="DEVONLY-TEST">1<p>DEVONLY-TEST</p>2</div>""",
        "<div>12</div>")

    'attr - testAttr()
    def testAttr() =
      test(div(VdomAttr.devOnly("data-devonly-test") := "!DEVONLY-TEST!", 123))(
        """<div data-devonly-test="!DEVONLY-TEST!">123</div>""",
        "<div>123</div>")

    'style - testStyle()
    def testStyle() =
      test(div(VdomStyle.devOnly("devonly-test") := "!DEVONLY-TEST!", 123))(
        """<div style="devonly-test:!DEVONLY-TEST!;">123</div>""",
        "<div>123</div>")
        
    ()
```
Moreover, when the problem appears, I see that some instances of `AnonFunction0` are allocated, even though they are not even used. This means that those `AnonFunction0`s are not virtualized by the optimizer.

So it seems there is a limitation in the optimizer with virtualizing nested `AnonFunction0`s or something like that.

**Comment by japgolly** [comment]
Ah thanks, I didn't get a chance to revisit this. Firstly, thanks for the idea to extract `def`s, I'll do that.

More importantly though, seeing as this wasn't an issue before 0.6.15, is this a regression in the optimiser?

**Comment by sjrd** [comment]
Ate you sure it wasn't an issue before 0.6.15? Or was it not an issue with 2.11 and you happened to upgrade both at the same time? Because lambdas are emitted very differently between 2.11 and 2.12, but they haven't changed in years across versions of Scala.js.

**Comment by japgolly** [comment]
Yeah this was fine before 0.6.15. When I was looking into this, I kept master as is and downgraded SJS (and annotations) to ensure there were no other changes causing it. Of combinations of SJS 0.6.1{4,5} and Scala 2.1{1,2}, only 0.6.15 x 2.12 exhibited this issue.

**Comment by sjrd** [comment]
Hum ... at least that means we should be able to nail it down with a git bisect. Looking at the list of commits affecting `OptimizerCore` in 0.6.15, the only commit that looks plausible is https://github.com/scala-js/scala-js/commit/e0eeb70d79753a8d9c621ba34abb496d7406783d (from a very shallow inspection). I'll try and nail it down further some time this week.

**Comment by gzm0** [comment]
What is the state on this?

@japgolly does this still happen with the newest version?
@sjrd was this fixed by the fixes to Virtualize JSArrayConstr (#2964)?

**Comment by sjrd** [comment]
I don't think #2964 would have changed anything about this. Except for the capping of the last commit, that PR is not supposed to change the output of the optimizer whatsoever.

**Comment by gzm0** [comment]
@sjrd what is the state on this?

**Comment by sjrd** [comment]
Probably exactly in the same state as it was in 2017. I have never looked at this issue since then. I suggest we close it as won't fix, and perhaps it will resurface later in the 1.x cycle?

**Comment by gzm0** [comment]
SG.
