### ISSUE TITLE
Incremental compilation fails to detect and recompile macro-compiled code.

### ISSUE THREAD

**Issue by cuzfrog** [scala-js/scala-js#2897]
When using `uPickle` and associated class changes, after project has been compiled. Incremental compilation will be triggered to compile that class, but not including `uPickle` generated macro. Thus such error is thrown during imcremental compilation:
```
[error] Referring to non-existent method ...
[error] called from...
...
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes: ...

java.lang.RuntimeException: There were linking errors
	at scala.sys.package$.error(package.scala:27)
	at org.scalajs.core.tools.linker.frontend.BaseLinker.linkInternal(BaseLinker.scala:158)
	at org.scalajs.core.tools.linker.frontend.BaseLinker.linkInternal(BaseLinker.scala:107)
	at org.scalajs.core.tools.linker.frontend.LinkerFrontend$$anonfun$4.apply(LinkerFrontend.scala:62)
...
```
Giving it a full compilation solved the problem, but takes time.
I tried to seek and remove files containing broken part, but no luck to solve it all. I don't have full understanding of linking process.

I haven't test macros as subproject depended on by js project.

**Comment by sjrd** [comment]
This is a known issue with sbt's incremental compilation, which Scala.js has no control over, not with Scala.js per se. The appropriate repo to track this is https://github.com/sbt/zinc (and I'm sure there are already several open issues on the topic), so I'm going to close this here.
