### ISSUE TITLE
Scala.js-defined JS class extending native JS class: `this` undefined

### ISSUE THREAD

**Issue by daniel-shuy** [scala-js/scala-js#2904]
I have a Scala.js-defined JS class (`@ScalaJSDefined`) which extends a native JS class (`@js.native`), which is a Facade for a Javascript library.

Everything else works as expected, except that when the actual Javascript library tries to reference `this`, it complains that `this` is `undefined`.

**Comment by daniel-shuy** [comment]
Should I convert the native JS class to a trait instead and do:
```scala
js.use(new MyClass()).as[NativeJSTrait]
```
instead?

**Comment by sjrd** [comment]
We would need more information here. In particular a reproducible test case that demonstrates the bug.

**Comment by daniel-shuy** [comment]
In my case I'm creating a Facade for Vue.js, and trying to extend the Facade (native JS class) with a Scala.js-defined JS class.

If I have the time, I'll try it with some other library (eg. JQuery) and see if I can pinpoint whether the fault lies with Vue.js or not.

**Comment by sjrd** [comment]
Knowing whether or not it works with another library is a plus, but what I really need to understand your issue is a code snippet that demonstrates your issue. Without that I am blind.

**Comment by sjrd** [comment]
Closing this as we are lacking information. Feel free to reopen with a snippet that fails to behave as expected.
