### ISSUE TITLE
Add JSEnv for headless Chrome

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#2920]
Chrome 59 can now be used headlessly. Hoorah.
https://developers.google.com/web/updates/2017/04/headless-chrome

**Comment by sjrd** [comment]
I thought this could be leveraged directly using Selenium, and hence https://github.com/scala-js/scala-js-env-selenium. It's that not the case?

If it isn't, it should anyway be provided in a separate repo, just like scala-js-env-selenium. I welcome contributions in that space. I can't afford to work on this myself.

**Comment by japgolly** [comment]
You might be able to use it via Selenium but I'm more interested in using it as a Node/PhantomJS replacement. Ok in the future (when I have time + after Phantom.JS support is externalised) I'll look at this in a separate repo.
