### ISSUE TITLE
JUnit assertEquals(_: Double, _:Double) not failing for JS, only for JVM

### ISSUE THREAD

**Issue by mkotsbak** [scala-js/scala-js#2927]
For JVM it gives:

`Use assertEquals(expected, actual, delta) to compare floating-point numbers`

but it does not fail for the Scala.Js version.

**Comment by gzm0** [comment]
It seems like adding this is a problem: If we add an overload `assertEquals(_: Double, _:Double)`, all assertions testing **integers** will use this overload and fail (many of these in our test suite). Note that JUnit does *not* define an overload of `assertEquals` for ints.

Not sure what to do about this.

**Comment by gzm0** [comment]
Duh, wasn't my smartest moment. JUnit has a `assertEquals(long, long)` overload. Pretty sure this one takes precedence over `assertEquals(double, double)` when using ints.

**Comment by sjrd** [comment]
They don't define an overload for `Int`s but they do define one for `Long`s (http://junit.org/junit4/javadoc/4.8/org/junit/Assert.html#assertEquals(long,%20long)). Experiments in the console suggest that, when giving `Int`s, the overload with `Long`s is preferred.

**Comment by sjrd** [comment]
Ah ah cross-post :P

**Comment by gzm0** [comment]
Fixed in 08119ab19664489fc4afa8be028710af70690600
