### ISSUE TITLE
Improve sbt support for sourcemaps

### ISSUE THREAD

**Issue by MasseGuillaume** [scala-js/scala-js#2941]
I often find project with incorrect source map setup. I propose to add a key and an optional setting definition to solve this problem.

* add a sbt setting for source map (`mapSourceURI`)
* optionally add a way to guess the sourcemap based on github. (`sourceMapFromGithub`)

```scala
val mapSourceURI = SettingKey[Map[URI, Option[URI]]](
  "mapSourceURI", "substitutions to be applied to the source map"
)

def sourceMapFromGithub = {
  def githubFromScmInfo(browseUrl: URI): Option[GithubRepo] = ???

  val githubMapping = 
    scmInfo.value.flatMap{info =>
      githubFromScmInfo(info.browseUrl).map( github =>
          val ver = version.value
          val from = (baseDirectory in LocalRootProject).value.toURI.toString
          val to = s"https://raw.githubusercontent.com/${github.org}/${github.repo}/v$ver/"
          from -> Some(to)
      )
    }

  mapSourceURI :=
    githubMapping match {
      case Some(mapping) => mapSourceURI + mapping
      case _ => mapSourceURI
    }
}
```

**Comment by sjrd** [comment]
That can already be done with this snippet in your build:
```scala
scalacOptions ++= {
  if (isSnapshot.value)
    Seq.empty
  else {
    val a = baseDirectory.value.toURI
    val g = "https://raw.githubusercontent.com/scala-js/scala-js-dom"
    Seq(s"-P:scalajs:mapSourceURI:$a->$g/v${version.value}/")
  }
}
```
See for example in https://github.com/scala-js/scala-js-dom/blob/master/build.sbt

**Comment by MasseGuillaume** [comment]
Yeah, I know it's possible. I want to improve the user experience.

**Comment by sjrd** [comment]
I don't think we need more complexity in the sbt plugin. We're trying to make it *simpler* in 1.x, not more complex.

Hard-coding GitHub into the core, general-purpose plugin to save a couple of lines for those who do use GitHub does not seem like a good direction to head towards.
