### ISSUE TITLE
Scala.js SBT plugin ignores logBuffered setting

### ISSUE THREAD

**Issue by djspiewak** [scala-js/scala-js#2945]
History: https://github.com/typelevel/cats-effect/pull/51

The `logBuffered in Test := false` SBT setting is designed to allow test frameworks (and really anything with outputs) to produce feedback incrementally, typically as each individual test case completes, rather than exclusively as the test suite completes.  This is really really useful for extremely long running test suites, both from a usability and from a "it works in Travis" standpoint.  For context, Travis watches stdout/stderr, and if it doesn't see any new output in 3 minutes, it will assume the process is hung and kill it.  You can delay this through various dodgy mechanisms, but it doesn't work all that well.  Incremental output is the more scalable solution for long-running suites comprised of numerous fast test cases.

Unfortunately, the setting has no effect with `.js` projects.  It appears that the setting is being overridden by Scala.js somehow, and it's not entirely clear how.  Alex reported on some more minimized testing [here](https://github.com/typelevel/cats-effect/pull/51#issuecomment-300745288).

**Comment by sjrd** [comment]
@gzm0 Does that ring a bell to you?

**Comment by gzm0** [comment]
Yeah, I had to implement buffering in the adapter itself, so output from the test frameworks does not end up interleaved (from different threads).

So currently, Scala.js completely ignores the setting, but only outputs all the logs, once a test is complete. This is a hack to work around the interleaving issue that survived until now.

Ideally, we do not car about buffering at all but just forward everything to the appropriate logger and sbt decides whether to buffer or not.

I can try and take a look in the following days.

**Comment by gzm0** [comment]
Relevant code is in: https://github.com/scala-js/scala-js/blob/master/test-adapter/src/main/scala/org/scalajs/sbttestadapter/ScalaJSTask.scala

**Comment by gzm0** [comment]
I have investigated this and I still do not understand why I introduced this in the first place.

When testing on our test-suite now, it seems that, after removing the buffering logic in Scala.js, the `logBuffered` setting does exactly what it is supposed to: If on, output comes nicely per suite, if off output lines are interleaved as they show up. This behavior is consistent on both JS and JVM.

@sjrd do you think we should investigate how other major test frameworks behave under this or should I just nuke our buffering logic? The risk is that people start complaining at the next release that they can't understand their test output :S

**Comment by sjrd** [comment]
IIUC, they will complain only if they explicitly set `logBuffered in Test := false`, right? In which case it's they own problem, and we can tell them to remove the setting. Or are you afraid that we might destroy the output even under `logBuffered in Test := true`, because of some corner case we don't see?

If the latter, what about we introduce a "backdoor" during 0.6.x, based on a Java system property, to reactivate the internal buffering? And if we don't get complaints in 0.6.x, we definitively nuke it in 1.0.0.

**Comment by gzm0** [comment]
> Or are you afraid that we might destroy the output even under logBuffered in Test := true, because of some corner case we don't see?

Yes. I think the backdoor is a reasonable solution.

**Comment by gzm0** [comment]
Fixed in 74c9af0d85b08e92435b488b97c8f6ac5392002f
