### ISSUE TITLE
Remove js.use(x).as[T]

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2948]
There are 3 good reasons for that:

* It definitely *can* be implemented and tested outside of the core, so it should.
* With Scala.js-defined JS classes, this feature has lost a lot of its usefulness (GitHub reports *2* occurrences of `js.use` in .scala files in the wild, and one of them should really be a Scala.js-defined JS class).
* It is the only macro in the core library, so getting rid of it means getting rid of all macros in the core lib.

**Comment by gzm0** [comment]
I definitely agree. I'm wondering whether we should just remove it and revive it if somebody asks for it.

**Comment by gzm0** [comment]
I propose the following:
- Deprecate in 0.6.17.
- Remove in 1.0.0 (without replacement).
- Revive if necessary.

**Comment by sjrd** [comment]
I'm not a big fan of deprecating without replacement in 0.6.17. Because if people do use it and use fatal warnings, it's too much breakage in a minor release.

I'd actually rather just remove it in 1.0.0 without replacement, and revive if necessary.

**Comment by gzm0** [comment]
Fair enough :)
