### ISSUE TITLE
Move the CLI out of the core

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2949]
This could be controversial but ... what about moving the CLI out of the core? Rationale:

* It does not need to be in core. We build and test everything else without requiring the CLI. By our general policy of "everything that does not need to be in core shouldn't be in the core", the CLI shouldn't be there.
* It is the only thing that depends on a non-critical Scala dependency: `scopt`. This means we typically cannot even build the CLI for new milestones of Scala at the time we upgrade. And after that, it's kind of too late to publish them.
* It is also the only thing that makes us depend on the sbt plugin `sbt-assembly`.
* Out of the core, we could consider using more fancy things, like [`sbt-native-packager`](https://github.com/sbt/sbt-native-packager), which means we might be able to fix #703, our oldest open issue.

FTR, other Scala--`%%`--dependencies that we have are:

* `scala-partest` which is super core to scala/scala, so guaranteed to be published in a timely manner, and
* `scala-parallel-collections`, which currently is considered critical enough to be published in a timely manner, but we'll probably have to move away from those at some point too.

and other sbt plugins we use are:

* `sbt-bintray`
* `sbt-mima-plugin`
* `scalastyle-sbt-plugin`

**Comment by gzm0** [comment]
Totally agree on that, but only if the CLI is able to just use the tools API that remains backwards compatible between minor versions (which seems totally doable).
