### ISSUE TITLE
scalaJSUseMainModuleInitializer with custom configurations

### ISSUE THREAD

**Issue by andriyvnester** [scala-js/scala-js#2951]
I know that using custom SBT configurations with Scala.js is not documented but it works fine with `persistLauncher` but not with `scalaJSUseMainModuleInitializer`.

Consider project setup:
```scala
val Custom = config("custom") extend Compile
inConfig(Custom)(Defaults.compileSettings)
inConfig(Custom)(ScalaJSPluginInternal.scalaJSCompileSettings)
```
---

Using persistLauncher always produces correct -launcher.js file:
```scala
persistLauncher in Compile := true
persistLauncher in Custom := true
```
---

scalaJSUseMainModuleInitializer in global config works correctly too but gives no option to disable for individual configs:
```scala
scalaJSUseMainModuleInitializer := true
```
---

Enabling scalaJSUseMainModuleInitializer for each config separately produces inconsistent results.

When running `compile:fastOptJS` or `custom:fastOptJS` task, **-fastopt.js file can include initializer from `src/main/scala`, initializer from `src/custom/scala` or both**. It varies for each compilation.
```scala
scalaJSUseMainModuleInitializer in Compile := true
scalaJSUseMainModuleInitializer in Custom := true
```

**Comment by sjrd** [comment]
You'll need the following addition setting, *before* `inConfig(Custom)(ScalaJSPluginInternal.scalaJSCompileSettings)`:
```scala
// Do not inherit module initializers from Compile in Custom
scalaJSModuleInitializers in Custom := scalaJSModuleInitializers.value
```

**Comment by andriyvnester** [comment]
It looks like they are two different things: project configuration and inconsistency that I mentioned.

Your answer solves the issue with configuration. Thank you.

As for inconsistency - it looks like it is not currently possible to `fastOptJS` different configurations and get correct initializer without changing a file or running `clean` 

For example
```scala
clean
compile:fastOptJS
custom:fastOptJS
compile:fastOptJS
```
results in custom intializer since no recompilcation triggered in last line


---
```scala
clean
compile:fastOptJS
custom:fastOptJS
// change file or run clean
compile:fastOptJS
```
results in compile initializer included as expected

**Comment by sjrd** [comment]
Oh you absolutely need to redirect the output of your `custom:fastOptJS` to a different file than that of `compile:fastOptJS`. You can do that with
```scala
moduleName in (Custom, fastOptJS) := moduleName.value + "-custom"
```
or variations thereof.
