### ISSUE TITLE
Handling AnyVals and nulls

### ISSUE THREAD

**Issue by Starzu** [scala-js/scala-js#2962]
There is a difference between JVM and Scala.js behavior:

```scala
case class T(t: Long) extends AnyVal

val f = (t: T) => if (t != null) t.t else 42

val t: Any = null
t.asInstanceOf[T] // It's OK in Scala.js; JVM throws NPE
f(t.asInstanceOf[T]) // Anyway it fails when passed to `f`
// ERROR: Cannot read property 't$1' of null
```

Bigger examples:
https://scalafiddle.io/sf/06SziIo/7
https://scastie.scala-lang.org/lXhELabFRiGfdkXARjc1Jg

Related issue: https://issues.scala-lang.org/browse/SI-8097

**Comment by sjrd** [comment]
That is expected. In Scala.js, [`NullPointerException`s are Undefined Behavior](https://www.scala-js.org/doc/semantics.html#undefined-behaviors). So anything that throws an NPE on the JVM is allowed to (and will) behave in arbitrary ways in Scala.js.

**Comment by Starzu** [comment]
Anyway behavior of `f(t.asInstanceOf[T])` is surprising, because it fails in generated code:
```javascript
function(t$2) {
  var t = $as_LScalaFiddle$T(t$2).t$1;
  ...
}
```

It might push this `null` forward in this case, don't you think?

**Comment by sjrd** [comment]
Undefined Behavior is surprising. Once you reach UB, the compiler is allowed to do whatever pleases it. Sometimes that's surprising, but it's still valid.

Your code must not try to cast `null` to `T` which is a value class. As soon as you try to do that, surprising things can happen.
