### ISSUE TITLE
Migrate to sbt-crossproject

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#2987]
https://github.com/scala-native/sbt-crossproject

Work-in-Progress at https://github.com/scala-js/scala-js/compare/master...sjrd:sbt-crossproject
Requires sbt-crossproject 0.2.0 to be published.

**Comment by gmethvin** [comment]
Is there any chance this will be backported to 0.6? This would help us a lot to avoid forcing a dependency on scalajs in our plugins without pulling in all the scalajs plugin dependencies.

**Comment by sjrd** [comment]
No, that is not possible without breaking backwards binary compatibility of the Scala.js sbt plugin in the 0.6.x series.

**Comment by gmethvin** [comment]
So would you recommend an sbt plugin that wants to support scalajs include the entire scalajs plugin? or is there another solution available for 0.6 I'm not aware of?

**Comment by sjrd** [comment]
I'm wondering why an sbt plugin would need to "support Scala.js" to begin with. Usually it should just compose, so it would work out of the box without your plugin ever knowing about Scala.js. Could you clarify your scenario?

**Comment by gmethvin** [comment]
The plugin (in this case the sbt-twirl plugin) should add the scalajs twirl library to scalajs projects and the jvm library to jvm projects. Currently we need to add the scalajs plugin to get the `%%%` syntax: https://github.com/playframework/twirl/blob/master/build.sbt#L71. I'm hoping to avoid creating conflicts with the extra dependencies brought in by the scalajs plugin. There's no reason people not using scalajs should have to deal with that issue.

In particular we've run into the protobuf dependency issue mentioned here: https://github.com/scalapb/ScalaPB/issues/150#issuecomment-245408884

**Comment by sjrd** [comment]
I see. Yeah that's a reasonable thing to do.

You could do it with a hack. First, note that `%%%` is not magical. It does two things:
* Detect if the current project is a Scala.js project (reading the setting `isScalaJSProject.value`
* If it is, apply `cross ScalaJSCrossVersion.binary` to the `ModuleID`, and `cross CrossVersion.binary` otherwise

Of course, both of those things need sbt-scalajs on the classpath. However, it is possible to hack around it.

There is another way to detect if the current project is a Scala.js project, that does not need sbt-scalajs on the classpath: it is to inspect the value of `crossVersion.value`, and detect if that is a Scala.js `CrossVersion`. You can tell a Scala.js `CrossVersion` from a non-Scala.js one through the fact that it appends `_sjs0.6` somewhere in the artifact name. In an sbt setting value, you can therefore detect Scala.js like this:
```
val crossVer = crossVersion.value
// The values 2.12.3 and 2.12 are completely arbitrary
val isScalaJS = CrossVersion(crossVer, "2.12.3", "2.12") match {
  case Some(f) => f("foo").contains("_sjs0.6")
  case None    => false
}
```
Once you have that, you can apply the very same `crossVer` to the module ID only if `isScalaJS` is true. Therefore you would get:
```scala
libraryDependencies += {
  val crossVer = crossVersion.value
  val isScalaJS = ...
  val baseModuleID = "com.typesafe.play" %% "twirl-api" % twirlVersion.value
  if (isScalaJS) baseModuleID cross crossVer
  else baseModuleID
}
```
This is not completely foolproof. A Scala.js project could override its `crossVersion` to something else than `ScalaJSCrossVersion.binary`, in which case this hack will either fail to detect that it is a Scala.js project, or produce the wrong module ID anyway because `cross crossVer` does not do what we want it to do. However it should work for most cases.
