### ISSUE TITLE
partest does not honor --noOpt, it uses fastOpt

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#3000]
This was actually broken in the Great Tools Refactoring of 0.6.6, see https://github.com/scala-js/scala-js/commit/f7f6de10a489c41bd8a6f5c3838c7cea60227e64#diff-b005d9edc9a46cb997a70eb2aab7dea5. This refactoring allowed Rhino to run in fastOpt, and `linkUnit` did the fastOpt by default. We specifically altered `MainGenericRunner` to use Rhino under `--noOpt`, but failed to disable the optimizer in the linker at the same time.

I discovered that while working on #2999. At this point we should wait for that one to be merged before fixing this issue on top of that.

**Comment by sjrd** [comment]
And that's issue #3000 :smile:

**Comment by sjrd** [comment]
Oh it gets better. That very same commit also deactivated the use of `semantics.optimized` in --fullOpt (instead of `semantics` non-optimized).

**Comment by gzm0** [comment]
Fixed in 1ae82be52e251aa5420a01138ed7e0a707835949
