### ISSUE TITLE
Super call to a mixin of an outer class confuses the codegen in 2.12+

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#3013]
Same bug as https://github.com/scala/scala/pull/5944 on the JVM side, for exactly the same reason.

**Comment by sjrd** [comment]
The same fix as what was done in the JVM fixes our issue for Scala classes inside Scala classes. But our situation is further complicated by non-native JS classes.

**Comment by gzm0** [comment]
Fixed in e02799b636b577eb56593d08c21a7cb2e68719e8
