### ISSUE TITLE
@noinline breaks optimizer

### ISSUE THREAD

**Issue by ochrons** [scala-js/scala-js#3025]
When using `@noinline` on a method, optimizer throws at OptimizerCore.scala:1837

```scala
  private def inline(allocationSites: List[AllocationSite],
      optReceiver: Option[PreTransform],
      args: List[PreTransform], target: MethodID, isStat: Boolean,
      usePreTransform: Boolean)(
      cont: PreTransCont)(
      implicit scope: Scope, pos: Position): TailRec[Tree] = {

    require(target.inlineable)
```

Scala.js version 0.6.17

To reproduce, clone https://github.com/suzaku-io/suzaku/tree/505779808afcc5c85b5e23a59b9b623226a5d2b2

and add `@noinline` to `core/shared/src/main/scala/suzaku/ui/WidgetBlueprint.scala` on line 22
```scala
  @noinline final def <<(styleProperty: StylePropOrClass*): this.type = {
```
and run `webDemo/fastOptJS` in sbt

**Comment by gzm0** [comment]
Fixed in 917afe3f2ddbe0879139fa38f8433438f465bc73
