### ISSUE TITLE
Rethink JSEnv implementation APIs

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#3033]
Notably `AbstractNodeJSEnv` and `ExternalJSEnv` can probably be improved. Notably use less inheritance.

**Comment by sjrd** [comment]
Other things that can be improved, IMO:
* Get rid of the synchronous APIs (`jsRunner`). All our JS envs support asynchronous runs. In general, it's always possible to implement an asynchronous API on top of a synchronous API anyway.
* The arbitrary distinction between arguments given to `{js,async,com}Runner` and those given to their `run`/`start` methods. IMO all the arguments should go to the method in `JSEnv`, and that method should start immediately the runner. A `JSRunner` would always be running or stopped (but not yet-to-be-started).

**Comment by gzm0** [comment]
>  IMO all the arguments should go to the method in JSEnv, and that method should start immediately the runner.

Not 100% convinced about that one. Can be hard if you need two runners that communicate with each other. Mainly because you can't get references to both without starting them (and messages already piling up).

An API like this is OK for apparently immutable things like `Future.apply`. But for things that have state (as in `ComJSEnv.send`) this can lead to very difficult setup sequences. Maybe we can add some final helper methods that do this?

**Comment by sjrd** [comment]
How does the current scheme fare better for that use case? AFAICT, if you call `send()` before `start()`, you just block. You might just as well buffer your messages yourself if you have a use case of communicating between two runners.

**Comment by gzm0** [comment]
Stuff to also add:

- Expected thread safety guarantees.
- Exact exception semantics (what get's thrown when, send after close, receive after close, send while close, receive while close).

**Comment by gzm0** [comment]
I have given this quite some thought and think something like this would be sufficient:

```scala
trait JSEnv {
  val name: String // should really be stable -> val.

  def start(files: List[VirtualJSFile], console: JSConsole, logger: Logger): JSRun
}

trait JSRun {
  // Future completes if run completes.
  def future: Future[Unit]

  // Stops run without interrupting an operation. I.e. it inserts a `stop` operation on the event-loop.
  // Idempotent, async.
  def stop(): Unit

  // Forcefully stops the run. If the run is not stopped, will make run fail with error.
  // Idempotent, async.
  def kill(): Unit

  // Send a message to the JS end, async.
  // "Eventually throws" if the run is completed.
  def send(msg: String): Unit

  // Blocking receive. Throws if the run is completed but buffers incoming messages since completion.
  def receive(): String
  def receive(timeout: Duration): String

  // Immediate receive. "eventually throws" if the run is completed.
  def tryReceive(): Option[String]
}
```

Notes:
- No "unstarted" state anymore (as you mentioned, indeed much cleaner).
- No "close" concept anymore (was in practice always the same than `stop`). Note that JS-side will not be allowed to "close" anymore. It can just terminate in this case.
- Com API is required: in practice any serious `JSEnv` needs to implement the Com API, otherwise it can't be used for testing. Envs that really don't want to do this can just throw a `NotImplementedException`.
- "Eventually throws" means that if the run is completed and you call this method repeatedly at some point it will start throwing and always throw from there.

**Comment by sjrd** [comment]
Could we make `receive()` methods non-blocking? Something like returning a `Future[String]`? Concurrent `receive()` calls would be put in a queue, so that they are first-come first-served. (gives good semantics, although in practice a reasonable user will always want to sequence their calls to `receive()`). The `receive(timeout)` would be unnecessary.

That would give us an API that we can potentially cross-compile one day.

Also, what is the purpose of `tryReceive()`?

**Comment by gzm0** [comment]
`tryReceive()` receives a message if it does not need to block, otherwise returns `None`. If message reception fails, it throws, just like `receive`. Can be used to implement event-loop style code (useful if you need to interact with something that is not multithreaded).

The difficulty with `receive(): Future[String]` is essentially what happens in this case:

```scala
List.fill(5)(x.receive())
```

Now the `JSEnv` needs to retain a list of "requested receives", also getting ordering correct is hard. Essentially we'd need a reactive stream for this :-/
But I do see the appeal of us being able to cross-compile the API. How do other async APIs handle message interfaces? I'd really like to not go down the callback route here :S

**Comment by gzm0** [comment]
What I mean by "getting ordering correct" is that if you want to receive messages in a loop (which is what you want most of the time), you need to be very careful for your calls to receive to be in a proper order such that incoming messages don't get reordered.

So to continue the example:

```
List.fill(5)(x.receive()).map(_.foreach(println))  // oops, I just nuked ordering :S
```

**Comment by sjrd** [comment]
That's what I meant by the first-come first-served semantics in case of concurrent `receive()`s.

The only good solution is callback-based at the core. On top of that one can build reactive streams or Observables or things like that. But essentially it's a callback. And we definitely don't want to depend on some streaming library in the core, so I'd say callback.

The callback version also makes `tryReceive()` unnecessary, since as a user of the API, if you want a `tryReceive()`, you can build it yourself on top of the callback and some mutable state. There's no need to push the requirement to provide it to the `JSRun`s.

**Comment by sjrd** [comment]
> oops, I just nuked ordering :S

Yes, hence what I was saying about a "reasonable" consumer of the API, which should probably sequence calls to `receive()` in all cases.

This is a non-issue with a callback-based API, though.

**Comment by gzm0** [comment]
Yeah, but a callback-based API is dangerous in JVM land for deadlocks and call-stack explosions, no? For example, is a callback allowed to call `send` on the same runner? Also, would you put the callback in the `start` call then?

**Comment by gzm0** [comment]
> hence what I was saying about a "reasonable" consumer of the API

I know. But with a future based API like this, a "reasonable" consumer of the API is strange to write:

```scala
def loop(): Unit = {
  // When and how do I abort this "loop"
  x.receive().onComplete { x => doStuff(x); loop() }
}
```

**Comment by gzm0** [comment]
:-/ I need to think about this more...

**Comment by sjrd** [comment]
> Yeah, but a callback-based API is dangerous in JVM land for deadlocks and call-stack explosions, no?

I don't see why. Not any more than other solutions.

> For example, is a callback allowed to call send on the same runner?

Yes, definitely. With lockless algorithms or reentrant locks, this shouldn't be a problem.

> Also, would you put the callback in the start call then?

Probably.

I think we need two start methods anyway. One that enables Com and one that doesn't. It's orthogonal to this issue; we'll want a start without com for the `run` task and other stuff.

**Comment by gzm0** [comment]
> With lockless algorithms or reentrant locks, this shouldn't be a problem.

Just FTR: `send` and `receive` will not be lockless for all `JSEnv`s. For example the NodeJSEnv needs to write multiple things into a stream for a `send`. The only way to make this lockless is by adding more threads with a message queue. But fair enough about the re-entrant locks.

> Not any more than other solutions.

I don't think this is entirely true. In a fully asynchronous solution with an execution pool, the call-stack gets freed and operations that can execute independently do execute independently. In a call-back based solution things might be tied together more than necessary (imagine two envs that mutually call each others `send` handler on receive. In that case there might be a thread holding locks for both envs. This wouldn't happen in a stream or future based solution).

Not sure either of them are relevant though :P

**Comment by sjrd** [comment]
I think the problematic situation you describe can be avoided by specifying that `x.send()` must complete in a finite time even if `x.onReceive` does not. In practice this means that `send()` cannot call `onReceive()` itself. Instead it must make sure that the call to `onReceive` is queued up for asynchronous execution.

**Comment by gzm0** [comment]
> Instead it must make sure that the call to `onReceive` is queued up for asynchronous execution.

Yeah, a stream or future based solution would essentially ensure this. Maybe it is indeed sufficient if we just require this from the implementation.

> I think we need two start methods anyway. One that enables Com and one that doesn't.

Fair enough. But do we have two different `JSRun` traits then? We can of course drop the `send` method (`receive` will be replaced by callback), but what about the `stop` method? `stop` is essentially only implementable with a com and usually only reasonable with a com (otherwise how do you know when to stop).

So we would have:

```scala
trait JSEnv {
  val name: String // should really be stable -> val.

  def start(files: List[VirtualJSFile], console: JSConsole, logger: Logger): JSRun

  def startWithCom(files: List[VirtualJSFile], onMessage: String => Unit,
    console: JSConsole, logger: Logger): JSComRun
}

trait JSRun {
  // Future completes if run completes.
  def future: Future[Unit]

  // Forcefully stops the run. If the run is not stopped, will make run fail with error.
  // Idempotent, async.
  def kill(): Unit
}

trait JSComRun extends JSRun {
  // Stops run without interrupting an operation. I.e. it inserts a `stop` operation on the event-loop.
  // Idempotent, async.
  def stop(): Unit

  // Send a message to the JS end, async.
  // "Eventually throws" if the run is completed.
  def send(msg: String): Unit
}
```

Was hoping to avoid having two `JSRun` traits but if we want a setup with and one without com it's probably unavoidable. It's still much simpler than what we have now.

Also: Any thought on the argument count? `startWithCom` has quite a lot of arguments :S

WDYT?

**Comment by sjrd** [comment]
That looks good, I think.

Maybe you can bundle `console` and `logger` into a `Config` object. They are not essential parts of the API and they can have good defaults (`console` forwards to stdout, and `logger` is a `NullLogger`). That would reduce the number of arguments to `startWithCom` (and `start`) and would allow binary and source compatible improvements to those configuration things.

**Comment by gzm0** [comment]
Two things are not fully done yet with this:

- How to handle the event loop with non-com runs? I.e. what happens if the event loop is empty but stuff could be added.
- How to handle modules / libraries / etc.

**Comment by gzm0** [comment]
Other thing TODO on this: Provide a way to release resources of the runner (i.e. close or similar). That **must** be called by the user (see scala-js/scala-js-env-selenium#77).

**Comment by gzm0** [comment]
Ok, I think we can go even simpler:

```scala
trait JSRun {
  // Future completes if run completes.
  def future: Future[Unit]

  // Stops the run and releases all the resources.
  // This *must* be called to "close" the runner.
  //
  // Whether or not this makes the run fail or not is up to the implementation.
  // However, in the following cases, calling `stop` may not fail the run:
  // - `future` is already completed when `stop` is called.
  // - This is a `JSComRun` and the event loop inside the VM is empty.
  // Idempotent, async.
  def stop(): Unit
}

trait JSComRun extends JSRun {
  // Send a message to the JS end, async.
  // "Eventually throws" if the run is completed.
  def send(msg: String): Unit
}
```

This solves the following:

> How to handle the event loop with non-com runs
We use `stop` in `sbt run` by allowing some means of interruption by the user (^C, or maybe enter, depending on what is feasible). This is easy, since we do not redirect stdin to the VMs.

> Provide a way to release resources of the runner
`stop` does this now.

We are left with module handling. Essentially we need to solve two problems:
- How does the `JSEnv` know how it has to load stuff / prepare stuff for loading (i.e. do the files require each other internally, if yes, which one is the "main", or should it just include everything like `<script>`)? This depends on the module style of the SJS code.
- How can generated code know how to load stuff (does it need to require, global scope, etc.). While this is a big concern for notably our test adapter, it might be better solved entirely outside of `JSEnv`.

**Comment by gzm0** [comment]
Two questions:

- Should we call `stop` `close` instead so that we can implement `AutoCloseable`?
- Is it worth to specify `send` to throw? It might be easier for everybody to just say "never throws".

TODO at this point:

- Answer questions above.
- Figure out module stuff.
- Clarify expected message delivery guarantees (ordered, exactly once, no intermittent message dropping, dropping messages at the "end of the run" is OK).

**Comment by gzm0** [comment]
Just a quick update of where this is in my head:

- `stop` should probably be called `close`.
- `send` should not throw.
- I do not believe that we can/want to solve the module mess with this. However, I'd like to find an interface that we can adjust to a better solution as we go forward. Since this is an interface that we expect others to implement this might be non-trivial. Ideas below.
- Message delivery guarantees:
    - If p1 sends exactly `m_1, ..., m_n` and p2 receives `m_k (k <= n)` but not `m_{k+1}`, p2 must receive exactly `m_1, ..., m_k` in this order.
    - If p1 sends an infinite number of messages, p2 receives an infinite number of messages.

For module forward evolution, I am considering something like:

```scala
sealed trait Input {
  def filesToExplicitlyLoad: List[VirtualJSFile]
}

object Input {
  final case class Fileset(files: List[VirtualJSFile]) extends Input {
    def filesToExplicitlyLoad: List[VirtualJSFile]
  }
}
```

We could then later extend this to hold files that do not need to be explicitly loaded but available. The referring to loaded code is unsolved by this (and probably should remain unsolved, it's not the JSEnv's responsibility).

**Comment by gzm0** [comment]
Developing further on this idea. We could have this:

```scala
/** Input files to a [[JSEnv]]
 *
 *  This trait is open to inheritance, however, we only provide compatibility guarantee
 *  for inheritance in patch versions. Minor versions may break code inheriting from
 *  this trait (by adding methods).
 *  Usage of the interface will retain full compatibility (i.e. methods will not go away).
 */
trait Input {
  /** Files to be explicitly loaded by the JSEnv into the global scope.
   *  How additional files needed by modules are loaded is deliberately unspecified
   *  by this method since, at the time of writing, we did not know how to do it.
   */
  def filesToLoad: List[VirtualJSFile]
}
```

And later, this might be evolved into:

```scala
trait Input {
  /** Files to be explicitly loaded by the JSEnv into the global scope.
   *  How additional files needed by modules are loaded is deliberately unspecified
   *  by this method since, at the time of writing, we did not know how to do it.
   */
  def filesToLoad: List[VirtualJSFile]

  def mainFile: VirtualJSFile
  def availableModules: List[VirtualJSFile with RelativeFile]
}
```

The one thing I do not at all like about this is that it completely fails to model that most of the time, whether module support is needed or not is almost a property of the `JSEnv`. So pretending that the `JSEnv` can do both, or that we can provide both (with the same files) is a lie. I don't like lies :-/

**Comment by sjrd** [comment]
Maybe the `Input` with only `filesToLoad` should really be `SimpleInput`, that all `JSEnv`s are supposed to be able to deal with. And then later we add an unrelated `ModuleEnabledInput`, which can be consumed by subclasses of `JSEnv` that extend some `ModuleEnabledJSEnv`?

**Comment by gzm0** [comment]
So this is essentially similar than what we had with async/com environments until we realized that really any serious environment needs to support both (or runtime failure is enough).

Now in this case it's actually the other way around: The `JSEnv`s really only support one style at the moment. Node.js does not really support non-module includes (and the efforts to export things in the top-level scope rather than object have shown this).

So in practice, it seems that developers chose one inclusion style and stick with it (or we encourage this by having a `ModuleKind` setting).

So currently we are in the state where at compile time, we can be agnostic of whether we are in a module or not (`@JSExport` works for both, `@JSImport` has a fallback). However, at link time, one has to make a decision and that is fine.

But that in turn means that it is probably not too much to ask from developers to use a `JSEnv` that supports the module style they are using. Probably in practice they already do that.

Now how to model this is another question :)

**Comment by sjrd** [comment]
Indeed, that's a good point.

If a run-time failure is enough, then maybe declare the methods for all inclusion styles right in `JSEnv`, as concrete and throwing an `UnsupportedOperationException`. Then each `JSEnv` can choose to override the ones it supports. If we add one more in the future, it will be a new concrete method in a `class`, which is binary compatible.

**Comment by gzm0** [comment]
Hmmm... In that case why not just make an ADT `Input` with a private constructor (so specifically *not* sealed). Prudent users will add a default clause in their implementations, others will just get a `MatchError` which is not that bad.

An ADT seems notably easier to deal with if we have to construct and pass inputs before we pass them to the `JSEnv` (think for example in the test adapter, but probably also in the sbt plugin).

So it would look something like this:

```scala
/** Input to a [[JSEnv]] */
abstract class Input private[scalajs] ()

object Input {
  /** The given files are to be loaded into the global scope in the order given. */
  final case class FilesToLoad(files: List[VirtualJSFile]) extends Input
}
```

For the time being, Node.js can support `FilesToLoad` with a comment saying that this is a lie. Once we can transition Node.js to a better scheme (with actual module support), we can still support `FilesToLoad` but warn or maybe even require to set an option. Alternatively, depending on the speed we can swtich, we might even fully drop support for `FilesToLoad` in Node.js (of course we will always be able to support `FilesToLoad` with 0 or 1 files :)).

WDYT?

**Comment by sjrd** [comment]
Yes that makes sense. It looks good to me.

**Comment by gzm0** [comment]
There is still one open point about how to handle stdin/stdout/stderr or `JSConsole`.

Things that are clear so far:
- We should drop the `JSConsole` abstraction and use an stdin/stdout/stderr abstraction instead.
- stderr should not go to the `logger` anymore (see #3206).
- `JSRun` should not expose the streams, but they should be put in the `Config` for `start`.
- The default should be the equivalent of `java.util.ProcessBuilder#inheritIO`.

Things that are unclear:
- How to design the `Config` such that this does not put an unnecessary threading burden on the `JSEnv` implementation.

**Comment by gzm0** [comment]
I'm afraid there seems to be no clean way of doing what we want to do for stream handling in JSEnvs (at least for external envs, which seems to be the majority). `ProcessBuilder` allows us to inherit IO, which would cover the default behavior. However, there is no way of specifying a stream to input. Further, we cannot put an arbitrary stream in non-blocking mode (only sockets support this IIUC), so processing the stream forwarding on a shared thread-pool is not an option either.

The options I can currently think of are (cons are in bullets):
1. Add a "output stream sink" to the config which is essentially a set once variable.
    - `Config` becomes mutable and cannot be shared.
1. Force external envs to spawn threads to forward IO in case a special stream is requested.
    - Threads are likely to cause performance penalties.
    - `Config` becomes mutable due to stream closing semantics.
1. Do not allow stream forwarding at all.
    - API very limited to SJS's use case.
    - We cannot add stream forwarding later in a backward compatible manner.
    - It will be hard to test `JSEnv`s if we cannot easily capture their output.
1. Expose the streams on `JSRun`, if `inheritIO` behavior (via `Config`?) was not triggered.
    - Not very streamlined usage.
    - Not type safe or a lot of path dependent type magic.
1. Always just expose the streams on `JSRun` let it be the callers problem.
    - Does not support SJS's use case which would be happy with `inheritIO`.
    - SJS will need to add threads on its end, likely causing performance penalties.

None of them are really good. @sjrd any ideas?

**Comment by sjrd** [comment]
Have you considered the following variant of (1): have an option in the `Config` which is a callback, something like:
```
class Config(...) {
  ...
  def withOnPipeOpened((Option[InputStream], Option[InputStream]) => Unit): Config = ...
}
```
The `JSRun` that starts a process where either the stdout, the stderr or both are not inheritIO will invoke that callback with the two relevant streams given by `Process.getInputStream()` and `getErrorStream()`.

That should prevent the `Config` from becoming mutable per se, although of course the event is likely tied to one particular invocation, but that's the caller's problem, if they should something else than inheritIO.

**Comment by gzm0** [comment]
Fair enough. I guess that'll do. I wonder though if we need to make them optional.

**Comment by sjrd** [comment]
Not necessarily, but then we cannot quite offer to support inheritIO for stdout while piping stderr, or vice versa.

**Comment by gzm0** [comment]
Fair enough. I'll come up with something.
