### ISSUE TITLE
No linking error reported for conflicting export names with @JSExportTopLevel object.

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#3050]
The following fails to link:
```scala
@JSExportTopLevel("Foo")
class Foo

@JSExport("Foo")
object Foo
```
with
```
[error] Conflicting top-level exports to Foo from the following classes:
[error] - helloworld.Foo
[error] - helloworld.Foo$
```
but this variant with `@JSExportTopLevel` on the object does not:
```scala
@JSExportTopLevel("Foo")
class Foo

@JSExportTopLevel("Foo")
object Foo
```
This is because a `case TopLevelModuleExportDef` is missing in [`LinkedClass.topLevelExportNames`](https://github.com/scala-js/scala-js/blob/06ddd281863c96183cf2037cc66bcd942bb90aed/tools/shared/src/main/scala/org/scalajs/core/tools/linker/LinkedClass.scala#L64-L74).

Note that we don't have any tests for this because we lack infrastructure to test linking errors :(

**Comment by gzm0** [comment]
Fixed in 8881c24a0847424945bd3803ac5e6aebbab5234b
