### ISSUE TITLE
Anon JS class does not correctly initialize `= _` fields

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#3051]
```scala
@ScalaJSDefined
class Foo extends js.Object {
  var bar: Int = _
}

val foo = new Foo
println(foo.asInstanceOf[js.Dynamic].bar)

val foobar = new js.Object {
  var bar: Int = _
}
println(foobar.asInstanceOf[js.Dynamic].bar)
```
prints
```
0 // correct
null // incorrect
```
That's because `genAnonJSClass` [uses `fdef.tpe`](thttps://github.com/scala-js/scala-js/blob/06ddd281863c96183cf2037cc66bcd942bb90aed/tools/shared/src/main/scala/org/scalajs/core/tools/linker/LinkedClass.scala#L64-L74)--which is always `NoType`--instead of `fdef.ftpe`.

**Comment by gzm0** [comment]
Fixed in e5597ee5a09ffe52fc20de557ea09f8f5daba220
