### ISSUE TITLE
Wrong IR type for `this` local of @tailrec methods in the presence of self type in 2.12

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#3058]
With a combination of:

* Scala 2.12
* An `@tailrec` method
* In a class or trait that has a self-type

the codegen produces code with invalid IR.

Reproduction (`Parent` can be a `class` or a `trait`):
```scala
trait Parent { this: Child =>
  @tailrec final def bar(i: Int, acc: Int): Int = {
    println(s"bar($i, $acc)")
    if (i <= count)
      bar(i + 1, acc + i)
    else
      acc
  }
}

class Child extends Parent {
  def count: Int = 5
}

object HelloWorld extends js.JSApp {
  def main(): Unit = {
    val obj = new Child
    println(obj.bar(1, 0))
  }
}
```
gives the IR error:
```
[error] HelloWorld.scala(13:7:VarRef): Variable _$this of type ClassType(Lhelloworld_Parent) typed as ClassType(Lhelloworld_Child)
```
The tree that we receive from scalac is properly typed with `_$this` of type `Child` (the self-type), but we erroneously assume `currentClassType` for the type of `_$this` in some places (in the `VarDef` and in `genThis()`), rather than using the type of the symbol.

**Comment by gzm0** [comment]
Fixed in 1518b704802ea95c3521831d91610905f022ca25.
