### ISSUE TITLE
The IR checker must not check field existence on classes without instances

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#3060]
The following snippet reports a spurious IR checking error:
```scala
class Outer(f: Int) {
  class Inner {
    def get(): Int = f
  }
}

object HelloWorld extends js.JSApp {
  def main() {
    println(classOf[Outer])
    test(null)
  }

  def test(outer: Outer): Unit = {
    if (outer == null) {
      println("null")
    } else {
      val inner = new outer.Inner
      println(inner.get())
    }
  }
}
```
The error is:
```
[error] HelloWorld.scala(13:22:Select): Class Lhelloworld_Outer does not have a field helloworld$Outer$$f$f
```
In fact `Outer` *does* have such a field, so how come the IR checker got confused?

The reason is that `Outer` is *needed at all* (because of the `classOf[Outer]`) but *does not have any instances*. It is therefore trimmed down by the `BaseLinker` to an empty `class` definition, which does not have any field. The IR checker then complains about the access to that field from `Inner`, which *does* have instances (at least as far as our reachability analysis is concerned) and hence whose `get()` method is reachable.

The fix is easy: the IR checker must simply ignore checking field existence in classes that have no instances.

**Comment by gzm0** [comment]
Fixed in d8fc6f02f6d5e3e1e3d0572c80690fe96998b3fd.
