### ISSUE TITLE
IR check that the rhs of Is/AsInstanceOf nodes makes sense

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#3064]
They cannot be primitive types nor JS types.

**Comment by gzm0** [comment]
Nice!

**Comment by sjrd** [comment]
What's nice? The fact that I filed an issue to make the IR checker stricter, instead of waiting for you to tell me to? :smile:

**Comment by gzm0** [comment]
It's nice that we find more stuff to harden the IR checker (and the cause of one of the last "euh... we don't know why this really works and it's kind of suspicious, but it works...")

I like making things more restrictive :) It prevents things from blowing up.

**Comment by sjrd** [comment]
Fixed in 35bce57119b783a48e5c4900969ac9fff64061bb.
