### ISSUE TITLE
Upgrade our own build to sbt 1.x, when it's good enough

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#3069]
This should only be done on master, not in 0.6.x. At the same time, we should drop the cross-building of the sbt plugin, and only publish it for sbt 1.x.

Definitively migrating to sbt 1.0 implies dropping support for JDK 6 and 7, since sbt 1 requires JDK 8.

According to release notes, this might also require dropping support for Scala 2.11.0 and 2.11.1. sbt 1 does not support them.

See also: http://www.scala-sbt.org/1.0/docs/sbt-1.0-Release-Notes.html#sbt+1.0.0-RC2

**Comment by gzm0** [comment]
I will take a look at this. #3714 might require this.
