### ISSUE TITLE
New Analyzer, bye bye Infos

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#3078]
Scary title, uh?

Background: `Infos` are summaries of each method in a class, telling which other methods it calls, which classes it instantiates, etc. Those Infos are used by the `Analyzer` (aka reachability analysis or DCE) to perform its job. `Infos` are computed at compile-time, and stored in `.sjsir` files. That way, at link-time, only the Infos need to be read from all the `.sjsir` files, then the Analyzer can run, and only used classes need to be fully deserialized into Trees.

Sounds like a good idea, right? And it is, from a performance and memory consumption point of view. However, it has one major drawback: we cannot improve the Analyzer in binary compatible versions of Scala.js in ways that would require *more* information to be stored in the Infos. Indeed, we could deserialize old `.sjsir` files not containing all the infos we need, and be stuck. This is the reason things like #2227 cannot be implemented in minor versions of Scala.js.

How do we solve this? Easy: we compute the infos at link-time rather than at compile-time, and we don't store them in `.sjsir` files. New problem: we need to deserialize all the trees on the classpath, which costs memory and time. New solution: be *much* smarter.

## Goals of the new analyzer

* Not require Infos to be stored in `.sjsir` files
* Be at least as fast as the current analyzer
* Be at most as much memory-hungry as the current analyzer

### Read files and construct infos lazily

Currently, we read the infos of all the `.sjsir` files on the classpath, and the trees of those that are "needed at all" after `BaseLinker`. Ideally we should only read even the infos of classes that are "needed at all". That is in theory possible, because a class that is not needed at all does not participate in the reachability algorithm anyway.

How do we do that? Well, we start the reachability without having loaded anything. We only load the entry points of the classpath. Entry points are:

* `symbolRequirements`
* *Top-level* exports
* Static initializers of Scala classes

The first thing, we know in advance in which classes they are, by definition, so we know which files we have to read. For top-level exports and static initializers, we don't know, as that information is in the files themselves.

We can fix that with an extremely stripped down notion of "infos". The Infos reduce to 1 bit, telling whether or not the class has any entry point. That way, we only need to read that 1 bit from all `.sjsir` files on the classpath.

After that, we can have the reachability analysis algorithm start from the entry points. And every time it refers to a new class (via `lookupClass`), we load the corresponding `.sjsir` file, deserialize it to a tree, and derive the infos from the tree. At this point we know said class is needed at all, by construction. Of course, we cache the tree and infos for incremental runs.

For batch mode, we spend some additional time on deriving the infos from the trees, but we deserialize less, so it's unclear what the impact is on processing time. In an incremental run, we already win on processing time because:
* The time spent to derive the infos at link-time is only for changed classes, which necessarily come right from the compiler, which would previously have to derive those infos itself
* We save the time spent to serialize and deserialize the infos, as well as the I/O those additional bytes incur

**Achievement:**
* Infos are not in `.sjsir` files anymore
* less memory consumption, since only the infos of needed-at-all classes are deserialized and kept in memory
* faster in incremental runs
* potential cost: processing time in batch mode maybe increases

### Parallelism

When we lazily load a class, the reachability algorithm per se is blocked on several tasks to be performed on a single file:

1. Read the bytes from the disk, and uncompress them if them come from jars (not exactly true in our case for .jars, because all the files in jars are eagerly loaded and uncompressed in memory by `IRFileCache`)
2. Deserialize to build the tree
3. Derive the infos from the tree

These operations don't need to touch the data structure used by the reachability algorithm. Therefore, in theory they can be done in parallel. But that's assuming the algorithm can continue doing some work while waiting for the given infos.

That's possible because a reachability algorithm is essentially a fixed point computation, which can be organized with a work list of edges to be processed. Currently the analyzer maintains this work list implicitly on the stack, through recursion. However, it can be (partially) turned into a reified work list processed by a loop. If we do this, when we want to touch a new class, instead of processing the edge that goes to that class right away, we store it in a to-do list for that class, to be processed later when the class has been loaded.

Transforming the algorithm to support that won't be trivial, but it will allow to deserialize the trees and derive the infos in parallel with the actual reachability analysis.

**Achievement:**
* Faster in both batch and incremental runs, due to deserialization being performed in parallel. This should in particular have a major impact on batch mode, and reclaim the potential loss from the previous section.

**Comment by gzm0** [comment]
Have you considered "entry point files" that say something has an entry point rather than the first byte?

Pro: Probably better wherever a file is an atomic unit, n.b. inside JARs and behind the `IRCache`.
Con: Ugly.

**Comment by sjrd** [comment]
Yes I have considered that. I'll put if off until everything else is implemented, as it can be easily swapped independently of everything else. Then we'll be able to measure what difference it makes.

**Comment by gzm0** [comment]
SG
