### ISSUE TITLE
@JSExportTopLevel causes Node.js exited with code 1 in test:loadedTestFrameworks

### ISSUE THREAD

**Issue by olafurpg** [scala-js/scala-js#3092]
To reproduce

```
git clone https://github.com/olafurpg/Scalatex.git
cd Scalatex

 # @JSExportTopLevel on object
git checkout db82174c69288d5f0c7af2ecb1f0950339c21c5d
sbt scrollspy/test # [error] (scrollspy/test:loadedTestFrameworks) org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js exited with code 1

 # @JSExport on object
git checkout 2951caee649869a6b7986e87322a2d0f0bcb6516
sbt scrollspy/test # Success
```

Here are links to each of the commits
- https://github.com/lihaoyi/Scalatex/commit/2951caee649869a6b7986e87322a2d0f0bcb6516 success, but emits deprecation warning
```scala
[warn]  [E1] scrollspy/src/main/scala/scalatex/scrollspy/Controller.scala
[warn]       @JSExport on objects is deprecated and will be removed in 1.0.0. Use @JSExportTopLevel instead. Note that it exports the object itself (rather than a 0-arg function returning the object), so the calling JavaScript code must be adapted.
[warn]         (you can suppress this warning in 0.6.x by passing the option `-P:scalajs:suppressExportDeprecations` to scalac)
[warn]       L28:@JSExport
[warn]       L28: ^
```
- https://github.com/lihaoyi/Scalatex/commit/db82174c69288d5f0c7af2ecb1f0950339c21c5d errors after acting on the deprecation warning

**Comment by sjrd** [comment]
That's probably because the constructor of the object cannot be run in the given environment. With `@JSExportTopLevel`, the object will be initialized when the .js file is loaded. Here it seems its constructor accesses the DOM, and if you don't have DOM support in the environment you run on, it will of course crash, preventing `loadedTestFrameworks` to complete.

Seems pretty legit to me.

**Comment by olafurpg** [comment]
Aha, I see. That makes sense. I suppose the reason this worked before is that the object was never initialized? 

Closing then, but maybe this issue can help other who hit on the same situation.

**Comment by sjrd** [comment]
> I suppose the reason this worked before is that the object was never initialized?

Yes, indeed.
