### ISSUE TITLE
Calling evaluate function on Puppeteer from results in a ReferenceError

### ISSUE THREAD

**Issue by josdirksen** [scala-js/scala-js#3108]
I've been playing and experimenting with Scala.js and wanted to check out the new Puppeteer API from the chrome guys to automate Chromium. Most of it works as expected, but when I try and call the `evaluate` function (https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageevaluatepagefunction-args). I've tried different approaches of providing the js.Function, but all result in the same error.

```
ReferenceError: $this$5 is not defined
```

The code for this example can be found in: https://github.com/josdirksen/scalajs-puppeteer

@sjrd already mentioned in gitter that it is probably because of some serialization magic in puppeteer. 

```
@josdirksen So ... from https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#
pageevaluatepagefunction-args it seems that it indeed does some serialization magic. I'm afraid 
that won't be supported by Scala.js as such, because it means puppeteer peeks into the 
compiler's internal encoding, which a reasonable library should never do.
```

If this is really something out of the scope of scala.js feel free to immediately close this :)

**Comment by sjrd** [comment]
I did some digging, and it is indeed what I was afraid of. After some indirections, `evaluate` ends up calling [`evaluationString(fun, ...)`](https://github.com/GoogleChrome/puppeteer/blob/1f9b4fb4c83ad9f5963507675e6ad9011c4301ff/lib/helper.js#L25-L31). That function basically calls `fun.toString()`, which for a function returns the raw JS source code of the function. It then, I guess, sends that string over the wire and tries to execute it in a completely different environment, where it has lost its lexical scope.

I'm afraid puppeteer is doing something *evil* here, that cannot be supported by Scala.js. So I'll close this as a won't fix.

**Comment by josdirksen** [comment]
Completely agree. Will work around this, and pass in `Strings` instead of functions. Thanks for the quick reply and explanation.
