### ISSUE TITLE
Use CrossVersion.patch to depend on scalajs-compiler

### ISSUE THREAD

**Issue by dwijnand** [scala-js/scala-js#3140]
sbt-scalajs adds a dependency on scalajs-compiler using `CrossVersion.full`:

https://github.com/scala-js/scala-js/blob/v0.6.20/sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala#L1220-L1221

Would you be ok to switching that to `CrossVersion.patch`, instead?

See:
* "CrossVersion.patch" in http://www.scala-sbt.org/0.13/docs/Cross-Build.html
* or, if you prefer, its PR: https://github.com/sbt/sbt/pull/2757.

The context is trying to find a setup for Travis CI that builds projects using the latest nightly builds of Scala - https://github.com/scala/community-builds/issues/599.

**Comment by dwijnand** [comment]
Actually... even with CrossVersion.patch I'm still stuck as it would look for `scalajs-compiler_2.12.4` which still doesn't exist..

http://repo1.maven.org/maven2/org/scala-js/

Hmm.. any ideas?

**Comment by sjrd** [comment]
I have already declined to change this in #2954, because it is not sound. https://github.com/scala-js/scala-js/pull/2954#issuecomment-302743801 shows how to override sbt-scalajs' decision with your own custom dependency, for special cases like yours.

**Comment by dwijnand** [comment]
Ah, thank you for the links.
