### ISSUE TITLE
Tests on Travis CI succeed then throw a TimeoutException

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#3143]
This happens 90% of the time, the tests complete successful, log "X tests: X passed, 0 failed" then a TimeoutException is thrown by the SJS test adaptor.

It only happens on Travis CI, never locally (probably, simply because local is faster).
It happens with both 0.6.18 and 0.6.20.

Example:
https://travis-ci.org/japgolly/scalajs-react/jobs/277215211#L2643-L2684

**Comment by gzm0** [comment]
Sorry, I didn't see this. I'll try to have look this week. First guess is that the VM stop timeout is too low.

**Comment by gzm0** [comment]
This looks very much like #2640 (i.e. the timeout is too low when waiting for JSEnvs to terminate).

I'm starting to wonder if timeouts here really help us anything or whether we should just block indefinitely on everything (and rely on the CI environment to timeout).

OTOH, that means that some sbt operations (`loadedTestFrameworks`) would block as well and that's probably bad.

I guess the other viable long-term solution is to make timeouts arbitrarily configurable.

@sjrd WDYT?

**Comment by sjrd** [comment]
IMO we can give a shot at removing timeouts altogether. Even when something stalls in my sbt console, I tend to kill it before any timeout kicks in.
