### ISSUE TITLE
scala-js sbt plugin structure (use of managedClasspath) forces fullOptJs

### ISSUE THREAD

**Issue by mdedetrich** [scala-js/scala-js#3145]
Related issues are https://github.com/sbt/sbt-web/issues/154 and https://youtrack.jetbrains.com/issue/SCL-12594.

Not entirely sure if this is happening due to sbt-web or Scala-js, but currently when you use sbt-web where you have to put `managedClasspath in Runtime += (packageBin in Assets).value` in your `build.sbt`, this forces Intellij (and maybe other IDE's that have direct SBT support?) to trigger a `fullOptJs`. In Intellij's case, it evaluates `managedClassPath` to figure out what dependencies your project has and this causes a `fullOptJs` (according to Intellij there is no way around this, its how you are meant to evaluate dependencies with SBT).

The result is that when you try and load/refreshes a scala-js project that uses sbt-web in Intellij, it takes 25+ minutes and sometimes it freezes the IDE.

**Comment by sjrd** [comment]
This is either an issue in sbt-web or sbt-web-scalajs or IntelliJ, but definitely not in sbt-scalajs. sbt-scalajs does not have any task that depends on `fullOptJS`, except `run` and `test` (and then only if `scalaJSStage` is `FullOptStage`, which is unlikely to be the case at the time of the IntelliJ import). Also sbt-scalajs doesn't even know what `Assets` is (that's an sbt-web thing and sbt-scalajs does not depend on sbt-web).
