### ISSUE TITLE
Support building on JDK 9

### ISSUE THREAD

**Issue by SethTisue** [scala-js/scala-js#3147]
I am working on a new Scala 2.12 community build on JDK 9 (https://github.com/scala/community-builds/issues/609)

Naturally, one of the first projects I would like to include is Scala.js

but I'm getting `loaded from class ExposedValues$ in package with name ExposedValues$ and classloader java.net.URLClassLoader@2f29400e` when loading the build definition

the underlying cause is https://github.com/scala/scala-dev/issues/304

one rather slow possible way forward here is to wait for Scala 2.12.4 to be released with the fix for 304, then wait for a sbt 1.0.x release with the upgrade to 2.12.4, then upgrade Scala.js from sbt 0.13.x to 1.0.x

a faster, but more annoying, way forward would be to figure out which sbt plugin that Scala.js uses has its code in an empty package, and fix that plugin. (there could be more than one)

I see there is a ticket on upgrading Scala.js's own build to sbt 1.0.x: https://github.com/scala-js/scala-js/issues/3069

**Comment by sjrd** [comment]
Looks like it is [our own `ExposedValues` plugin](https://github.com/scala-js/scala-js/blob/b8fc74515491880c7b54ff31b7afb7a8b7fa3311/project/Build.scala#L37), part of the build itself (not part of an sbt plugin that we use). We also have another one `MyScalaJSPlugin` a few lines below.

I guess the whole ` Build.scala`, and the other `.scala` files in `project/`, should be in a `package build` or something.

**Comment by SethTisue** [comment]
another possible path: @retronym has [backported the empty-package fix to the Scala 2.10.x branch](https://github.com/scala/scala/pull/6113). if that results in a 2.10.7 release, then an sbt 0.13.17 release could use it, and we'd be good to go

**Comment by sjrd** [comment]
PR available at https://github.com/scala-js/scala-js/pull/3151. Note that this PR targets 0.6.x, but the community build is based on master. The changes will only be available when 0.6.x is merged into master, after that PR lands.

**Comment by gzm0** [comment]
Leaving open while waiting to land on master.
