### ISSUE TITLE
Method signature should alias to MDN

### ISSUE THREAD

**Issue by hepin1989** [scala-js/scala-js#3165]
Eg:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

In scala-js 

```scala
  def defineProperty(o: Object, p: String, attributes: PropertyDescriptor): o.type = native
```

and at `MDN`

```js
Object.defineProperty(obj, prop, descriptor)
```

I more like keep them in sync .

**Comment by sjrd** [comment]
How are they not in sync?

**Comment by sjrd** [comment]
Ah I guess you mean the parameter names?

But those are in sync with [the ECMAScript 2015 specification](http://www.ecma-international.org/ecma-262/6.0/#sec-object.defineproperty), which is the ultimate reference for APIs standardized in JavaScript.

**Comment by hepin1989** [comment]
Yes, the parameter name, but yes, I see。
I was wandering refer the doc to the MDN doc link instead of `MDN` placeholder.

**Comment by sjrd** [comment]
The `MDN` mark is not a placeholder. It is a reference to the fact that the Scaladoc was copied from MDN and is therefore under the same copyright as MDN, as mentioned at the top of the files:
```scala
 /**
 * All doc-comments marked as "MDN" are by Mozilla Contributors,
 * distributed under the Creative Commons Attribution-ShareAlike license from
 * https://developer.mozilla.org/en-US/docs/Web/Reference/API
 */
```

**Comment by hepin1989** [comment]
So how does the Scaladoc sync with the MDN by hands or some scripts?

**Comment by sjrd** [comment]
By hand.

**Comment by sjrd** [comment]
Closing this as it seems there is nothing that needs to be acted upon.
