### ISSUE TITLE
Improve the setup for importing in Eclipse

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [scala-js/scala-js#3176]
1) when following eclipse setup:
https://github.com/scala-js/scala-js/blob/master/DEVELOPING.md#eclipse

sbt runs fine, but eclipse produces error on project import:
```
Some projects cannot be imported because they already exist in the workspace or their project description file is corrupted
  Invalid project description.
  Resource '/Scala.js IR' already exists.
  Resource '/Scala.js tools' already exists.
  ```

that is due to same project name  (used by sbt eclipse plugin) being shared by:
https://github.com/scala-js/scala-js/blob/0.6.x/project/Build.scala#L555
both `js` 
https://github.com/scala-js/scala-js/blob/0.6.x/project/Build.scala#L587
and `jvm`
https://github.com/scala-js/scala-js/blob/0.6.x/project/Build.scala#L573

the solution is to use unique `name := "Scala.js XXX"` stanza for all projects

same problem also happens with IR:
https://github.com/scala-js/scala-js/blob/0.6.x/project/Build.scala#L474
https://github.com/scala-js/scala-js/blob/0.6.x/project/Build.scala#L482
https://github.com/scala-js/scala-js/blob/0.6.x/project/Build.scala#L491

2) project names are rather inconsistent:
```
[info] Successfully created Eclipse project files for project(s):
[info] Scala.js IR
[info] Scala.js JS Envs
[info] JavaLib Ex Test Suite
[info] Scala.js test interface
[info] Hello World - Scala.js example
[info] Scala library for Scala.js
[info] Scala.js compiler
[info] Tests for Scala.js JUnit output in JVM.
[info] Scala.js JS Envs Test Suite
[info] Scala.js
[info] Scala.js aux library
[info] Java library for Scala.js
[info] Scala.js tools
[info] java.lang library for Scala.js
[info] scalaTestSuite
[info] Scala.js sbt plugin
[info] Scala.js test suite on JVM
[info] Scala.js JavaLib Ex
[info] Testing - Scala.js example
[info] Reversi - Scala.js example
[info] Scala.js not IR checked tests
[info] Scala.js JUnit test runtime
[info] Scala.js library
[info] Scala.js JUnit test plugin
[info] Scala.js tools
[info] Scala.js JS Envs Test Kit
[info] Scala.js partest suite
[info] Tests for Scala.js JUnit output in JS.
[info] Scala.js CLI
[info] Scala.js IR
[info] Scala.js sbt test adapter
[info] Scala.js test suite
[info] Scala.js Stubs
[info] Partest for Scala.js
```

can you please use `name := "Scala.js XXX"` pattern everywhere?

in eclipse work spaces with few thousands projects that would make life easier:
* easy to locate project
* ensure no name collisions

**Comment by Andrei-Pozolotin** [comment]
alternatively use eclipse.org convention: `eclipse.project.name==maven.project.artifactId`

**Comment by sjrd** [comment]
We could indeed improve the situation for the Eclipse import.

I use it all the time, though, so it can't be fundamentally broken. The way I do 1. is that I only import the JVM version of IR and tools (when selecting them in the Eclipse import wizard).

For 2., I have no idea how you deal with workspaces of thousands of projects. I create distinct workspaces instead.

**Comment by Andrei-Pozolotin** [comment]
1) no, import is not fundamentally broken, only 2x2 projects name collisions
2) if not too much trouble, please use `Scala.js` as project `name:=` prefix

thank you

**Comment by sjrd** [comment]
I now recommend to use [Metals](https://scalameta.org/metals/) to develop Scala.js. It's also possible to use IntelliJ. Therefore I don't plan to change anything for Eclipse, whose support for Scala had been abandoned for a while. As such, I will close this issue as won't fix.
