### ISSUE TITLE
Method names as parameters

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [scala-js/scala-js#3190]
1) some js libs (vue, vuex, ...) rely on use of method names as parameters:
```
// 1. declare some methods
  val mutations = new js.Object {
    def increment(state: State) = state.count+=1
    def decrement(state: State) = state.count-=1
  }
// 2. describe method names, again
  val calls =js.Array(
    "increment",
    "decrement",
  )
// 3. use these methods by name references
val methods : js.Object = Vuex.mapMutations(calls)
```

2) surely one can roll out custom macro for this
to remove need for names re-declarations

3) but since `scala-js` is already a compiler plugin
it would help perhaps to have a standard feature, similar to:
```
import js.Method.name // compile-time reflector

  val calls =js.Array(
    name(mutations.increment),
    name(mutations.decrement),
  )
```

**Comment by sjrd** [comment]
> surely one can roll out custom macro for this to remove need for names re-declarations
> but since scala-js is already a compiler plugin it would help perhaps to have a standard feature

That's not how we work. If we used that criteria, Scala.js would be full of "stuff" that are potentially useful for this or that library. The way we decide was goes into Scala.js is the following criteria:

* If it *can* be implemented *outside* of Scala.js, then it should not be implemented *inside* Scala.js

Therefore, most things that can be implemented as macros do not make the cut to be put inside Scala.js. You are encouraged to experiment with macros in a separate library instead.

**Comment by Andrei-Pozolotin** [comment]
ok, got it, thank you.
found some jvm/js macro library: https://github.com/dwickern/scala-nameof
