### ISSUE TITLE
Structured types method access

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [scala-js/scala-js#3196]
structured types are properly generated,
but their methods are improperly referenced:
https://gist.github.com/Andrei-Pozolotin/d206bca719e74302f073455d0f4b9095

**Comment by gzm0** [comment]
Reflective calls on JS types are not supported in Scala.js.

See: https://www.scala-js.org/doc/interoperability/sjs-defined-js-classes.html (search for "reflective calls").

**Comment by Andrei-Pozolotin** [comment]
can perhaps an annotation be provided 

which reverses  the 
```Reflective calls on JS types are not supported in Scala.js```
behavior? 

the desired result is "almost there".

**Comment by Andrei-Pozolotin** [comment]
https://github.com/scala-js/scala-js/issues/956

**Comment by Andrei-Pozolotin** [comment]
the work around (for the gist above) is:
https://gitter.im/scala-js/scala-js?at=5a1459b471ad3f87361245c6
```
Sébastien Doeraene @sjrd 10:52
Have your macros generate structural Scala types (extending AnyRef) instead of structural JS types (extending js.Object).
```

replace 
```
  val commits = { // structured type provided by macro
    class Commits extends js.Object {}
    new Commits()
  }
```
with
```
  val commits = { // structured type provided by macro
    class Commits extends AnyRef {}
    new Commits()
  }
```
