### ISSUE TITLE
Use mapSourceURI in exception message file paths

### ISSUE THREAD

**Issue by cornerman** [scala-js/scala-js#3208]
When I compile (`fullOptJS` in this example), the javascript source contains my local absolute project pathes in the exception messages:

```javascript
function rv() {
    var a = pv();
    if (0 === (2 & a.zc)) throw (new js).d("Uninitialized field: /home/cornerman/projects/outwatch/src/main/scala/snabbdom/h.scala: 220");
    return a.q
}
```

Can I control these pathes? Or would it make sense to set these pathes to the value provided by `-P:scalajs:mapSourceURI` by default?

**Comment by sjrd** [comment]
That string comes from a macro. The Scala.js compiler does not put source paths in the generated .js file (in source maps, yes, and that is controlled with `-P:scalajs:mapSourceURI`). You need to report this to the corresponding macro library.

**Comment by cornerman** [comment]
Oh thanks, you are right. These exceptions were generated by the scalac option `-Xcheckinit`.
