### ISSUE TITLE
How to make sourcemap work?

### ISSUE THREAD

**Issue by doofin** [scala-js/scala-js#3241]
Is it required to enable ScalaJSWeb to make sourcemap work?I see the generated sourcemap like xxx.js.map,but browser can not load it

**Comment by doofin** [comment]
Following instructions of ScalaJSWeb I can make it work almost flawlessly for library functions,but the main scala file can not be shown.How to make that work?

**Comment by sjrd** [comment]
The GitHub Issues in this repo are for bug reports and feature requests only. Please ask questions [on StackOverflow](https://stackoverflow.com/questions/tagged/scala.js) or [on Gitter](https://gitter.im/scala-js/scala-js), where more than just the core developers can see and answer.
