### ISSUE TITLE
Really need a nicer construction API for Scala-js

### ISSUE THREAD

**Issue by NicolasRouquette** [scala-js/scala-js#3245]
I wanted to use Scala-js to create sketches of GIT workflows using this nice JS library: 
http://gitgraphjs.com/

The caveat here is that most operations require a JS Object.
For example:

```
var gitgraph = new GitGraph({
  template: "blackarrow",
  reverseArrow: false,
  orientation: "horizontal",
  mode: "compact"
});
```

How does one construct such a thing from Scala-js? 

This problem is related to a closed issue: https://github.com/scala-js/scala-js/issues/336 

There was a comment that this isn't really difficult to do in user space:
https://github.com/scala-js/scala-js/issues/336#issuecomment-37095130
But the link is broken: http://www.scala-js-fiddle.com/gist/9428904

Can someone shed light on how to do this?

**Comment by sjrd** [comment]
The GitHub Issues in this repo are for bug reports and feature requests only. Please ask questions [on StackOverflow](https://stackoverflow.com/questions/tagged/scala.js) or [on Gitter](https://gitter.im/scala-js/scala-js), where more than just the core developers can see and answer.

(This is a generic message.)
