### ISSUE TITLE
Scala.js leaks memory

### ISSUE THREAD

**Issue by Atry** [scala-js/scala-js#3268]
A have a project that aggregates many sub-projects.
When I run `sbt test`, A java.lang.OutOfMemoryError is thrown from Scala.js linker during fastOptJS.

https://travis-ci.org/ThoughtWorksInc/feature.scala/builds/332139064

**Comment by Atry** [comment]
The Scala.js is 0.6.21 https://github.com/ThoughtWorksInc/feature.scala/blob/2.3.x/project/plugins.sbt

**Comment by sjrd** [comment]
That just means it uses a lot of memory, not necessarily that it *leaks* memory. Please, until you can identify an actual *leak* (which would be a bug), ask on gitter or StackOverflow for guidance on how to increase your available memory and/our reduce the used memory at any given point in time.

**Comment by Atry** [comment]
It looks like memory leaks because:

1. Memory usage increase when compiling more sub-projects in a sbt batch command.
2. `set parallelExecution := false` does not reduce memory usage.

**Comment by sjrd** [comment]
That's because the Scala.js linker retains a lot of data structures in memory for incremental linking. You can disable that with the setting
`scalaJSLinkerConfig ~= { _.withBatchMode(true) }
```
in each of your Scala.js projects. But of course iterative re-linking will become slower, though that's not an issue on the CI.

**Comment by Atry** [comment]
@sjrd It works. Thank you.

It seems that Scalatest + Scala.js is very slow at both run-time and compile-time.
