### ISSUE TITLE
numeric parsing is stricter on js

### ISSUE THREAD

**Issue by tpolecat** [scala-js/scala-js#3271]
This works on the JVM but throws `NumberFormatException` on JS.

```scala
@ "໒".toInt 
res0: Int = 2
```

It looks like you're just delegating to the JS `parseInt` method here. Anyway I don't know if it's worth fixing but it's probably worth documenting. 

Thanks!

**Comment by sjrd** [comment]
Pretty sure this is a Duplicate of #2935.

**Comment by tpolecat** [comment]
Ah so it is. Thanks.
