### ISSUE TITLE
toJSArray JIT performance of generated arrays

### ISSUE THREAD

**Issue by fdietze** [scala-js/scala-js#3279]
I just read http://voidcanvas.com/javascript-array-evolution-performance/, which basically says that if you use `.push` on an array it probably won't be optimized to a real array by the JIT.

I'd like to know if this is relevant for the `.toJSArray` implementation, which uses push:

https://github.com/scala-js/scala-js/blob/92047803783759bbe817d822575924e6608fa977/library/src/main/scala/scala/scalajs/js/JSConverters.scala#L46-L68

Would it make more sense to implement it like this instead?

```scala
         case _ => 
           val result = new js.Array[T](col.size)
           col.copyToArray(result)
           result 
```

**Comment by sjrd** [comment]
> which basically says that if you use .push on an array it probably won't be optimized to a real array by the JIT.

This is not what I read. I read that if you push a new element *of a different type* and thereby make the array *heterogeneous*, then you destroy its performance. This also corresponds to my previous understanding of JS arrays.

In the case of `.toJSArray`, the array is kept homogeneous, so there shouldn't be any issue.

Moreover, the author is doing it *really* wrong. They first allocate an array with `new Array(N)`, then `push`, then only fill in the elements in the middle. This causes the array to go into *sparse* mode in addition to *heterogeneous*. And that is even worse than just heterogeneous. So I don't think they are measuring what they think they are.

**Comment by fdietze** [comment]
Ok, I guess you are right. That's why I asked. Thank you for the explanation.
