### ISSUE TITLE
scalaJSModuleKind setting unable to be set using scalaJSVersion tricks for migration support between 0.6 and 1.x

### ISSUE THREAD

**Issue by aappddeevv** [scala-js/scala-js#3282]
When migrating between 0.6 and 1.x, we can use `if(scalaJSVersion) ...` to help manage the `-P:scalajs:sjsDefinedByDefault` flag issue but there is no way to conditionally set `scalaJSModuleKind := `. There is no way to write a sbt build file that can build either version when one wants to emit commonjs modules.

**Comment by sjrd** [comment]
You're supposed to use
```scala
scalaJSLinkerConfig ~= { _.withModuleKind(ModuleKind.CommonJSModule) }
```
Doesn't that work?

**Comment by aappddeevv** [comment]
Oh, is that for 0.6.22 as well? Thought it was a 1.x thing only.

**Comment by sjrd** [comment]
Yes, it is also for 0.6.18+.
