### ISSUE TITLE
How to make scalajs emit smaller js?

### ISSUE THREAD

**Issue by doofin** [scala-js/scala-js#3284]
Bucklescript([https://github.com/BuckleScript/](url)) seems to emit quite small js code which is quite amazing.what currently prevents scala js from doing better?

**Comment by gzm0** [comment]
See: https://stackoverflow.com/a/48425441/1149944

Also please try use Gitter or Stackoverflow for questions in the future. This is for feature requests and bugs.

**Comment by doofin** [comment]
Thanks
