### ISSUE TITLE
1.0.0-M3: calling prototype on null object

### ISSUE THREAD

**Issue by aappddeevv** [scala-js/scala-js#3287]
I compile my project under 0.6.22, no error. Switch to 1.0.0-M3, error. Errors occur in the browse once the code vs compilation: `Uncaught TypeError: Cannot read property 'prototype' of null`

This is placeholder issue until I can figure out under what conditions this occurs.

**Comment by sjrd** [comment]
As such, this issue is not actionable. It is not even developed enough to know *whether* it is an issue in Scala.js or in your own code (there *are* intended breaking changes in 1.x, see the release notes).

Therefore, I am closing this.
