### ISSUE TITLE
www.scala-js-fiddle.com is unregistered 

### ISSUE THREAD

**Issue by lordmat0** [scala-js/scala-js#3289]
Sorry if this is not the correct place to report this.

www.scala-js-fiddle.com is unregistered there is a link to it on http://www.scala-js.org/

**Comment by sjrd** [comment]
Thanks for the report. The link should have been changed to https://scalafiddle.io/ months ago, but there was a redirection so we didn't notice.

PR most welcome. I won't have a computer until Monday with which to do it myself.

**Comment by gzm0** [comment]
@lordmat0 feel free to review scala-js/scala-js-website#405 as well.

**Comment by gzm0** [comment]
Fixed in scala-js/scala-js-website#405.
