### ISSUE TITLE
Can't throw JS Errors

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#3290]
Doesn't work (obviously):
```scala
throw js.Error("blah")
```

I grepped through the code base and didn't find a method to throw native JS errors. I think there should be something this this:
```scala
js.`throw`(js.Error("blah"))
```

**Comment by sjrd** [comment]
```scala
throw js.JavaScriptException(new js.Error("blah"))
```

**Comment by japgolly** [comment]
D'oh. Thanks @sjrd
