### ISSUE TITLE
Proposal: Start TestAdapter's bridge via module initializers

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#3294]
In Scala.js 1.0.x, with the advent of `scalaJSMainModuleInitializer` (aff7dcf2440da9f9134f6d85060cfba2fe322553) we have removed:
- The need to export main methods
- The capability of dynamically (i.e. after linking type) deciding which main is run.

I propose to do the same for testing:

- Define `TestAdapter.bridgeModuleInitializer` that starts the bridge.
- Add an sbt setting `scalaJSTestModuleInitializer`
  - defaulting to `true` in the `Test` configuration
  - mutually exclusive with `scalaJSMainModuleInitializer`
  - required to run `test*`
  - wire it to add `TestAdapter.bridgeModuleInitializer` to `scalaJSModuleInitializers`
- Remove `TestAdapter.ModuleIdentifier` without replacement.
- Simply take a `JSEnv.Input` in `TestAdapter` (after #3255) and wire it to `JSEnv.startWithCom`.
- Always add `test-interface` to `libraryDependencies in Test` (since it doesn't have an export anymore, that is fine).

This would simplify the `TestAdapter` and make it less dependent on how we build JS modules in the future. It would align the semantics/capabilities of `test` with `run` / `runMain`.

The major pain point here is how to deal with `testHTML`: It currently invokes a different exported method (from within `testadapter`) that builds the HTML UI. Solutions are:
1. Create another initializer for `testHTML`
1. Make `TestAdapter`'s initializer depend on a global, private flag injected in the template to dispatch to HTML instead.

While solution (1) seems cleaner, it is probably prohibitively annoying to users (and ourselves). Solution (2) seems to be a reasonable trade-off, especially since the HTML template is versioned together with the initializer definition. Therefore, we can change the interaction between them in a fully compatible manner. (Further, note that the HTML template already relies on global variables for test definitions).

If we go with solution (2), we should probably name the initializer `testadapter.moduleInitializer` or something.

**Comment by gzm0** [comment]
@sjrd WDYT?

**Comment by sjrd** [comment]
> Always add `test-interface` to `libraryDependencies in Test` (since it doesn't have an export anymore, that is fine).

Er ... it now has a module initializer, which in terms of DCE is just as bad as an export. It should probably be conditioned on the value of `scalaJSTestModuleInitializer`.

> Make TestAdapter's initializer depend on a global, private flag injected in the template to dispatch to HTML instead.

If we do that, could we go further and have a 3-way flag, which also has a position for "don't start a test bridge"? Would that make sense? It could even be the default.

That said, if `TestAdapter` is able to inject a global flag used by the bridge in a module-kind-independent way, how come the Java system properties thing isn't able to do so?

**Comment by gzm0** [comment]
> Er ... it now has a module initializer, which in terms of DCE is just as bad as an export. It should probably be conditioned on the value of scalaJSTestModuleInitializer.

That's what I meant. Just like `scalaJSMainModuleInitializer`, the build tool would only add it if requested. So merely adding the library would not do anything (isn't the other thing called static initializer?).

> If we do that, could we go further and have a 3-way flag, which also has a position for "don't start a test bridge"? Would that make sense? It could even be the default.

Yes, we could have that. Not sure if it should be the default though.

> That said, if TestAdapter is able to inject a global flag used by the bridge in a module-kind-independent way, how come the Java system properties thing isn't able to do so?

Well, the idea was that we only need to inject the global flag for HTML runner tests (and the internal bootstrap tests) which only work for a limited type module kinds anyways (which is why the default should maybe not be "don't start the bridge").

It is true that the `HTMLRunner` in terms of code loading interface it provides is a `JSEnv` and would need to deal with different types of `Input` individually. There is the difference that we could write the injection using the `@JSImport` fallback so depending on how the output module is linked, we could also properly import the test information module (which for `__ScalaJSEnv` we don't have and probably also doesn't make sense).

**Comment by sjrd** [comment]
OK, I understand now. That sounds reasonable.

Let's go for a 2-way flag like you suggested in the beginning, if the default needs to be execute the normal bridge anyway. We can add a third option later if requested.

My only concern is that, if done only in 1.x and not in 0.6.x, this change will significantly complicate https://github.com/sjrd/sbt-dynscalajs. Currently it abuses the fact that the *protocol* is the same between 0.6.x and 1.x, to only use 1.x' test-adapter, even to talk to a 0.6.x bridge. If the protocols deviate, this won't be possible anymore. But I'll figure something out. We shouldn't condition improvements in Core based on that alternative plugin.

**Comment by gzm0** [comment]
> If the protocols deviate, this won't be possible anymore. 

Oh, I think that will probably happen anyways :S (and definitely is already the case for pre 0.6.20 or something).

**Comment by gzm0** [comment]
FYI: I have a WIP change for this.
