### ISSUE TITLE
Missing details from ex.printStackTrace under fullOptJS compiled with Google Closure Compiler

### ISSUE THREAD

**Issue by mgilbertnz** [scala-js/scala-js#3297]
**Background**
I use sentry.io with my ScalaJS app to track runtime errors.  In development mode with fastOptJS I get the full exception stack trace sent to the server.  However when running with fullOptJS in production mode the stack trace misses calls within code compiled with Closure.

I've stripped my application back to a minimal example that demonstrates the behaviour.

**To reproduce:**

To run in **development** mode to produce success case:
```
git clone git@github.com:mgilbertnz/scalajs-stacktrace-test.git
cd scalajs-stacktrace-test
sbt run
```
Browse to http://localhost:9000
In debugging tools observe that we have 3 lines relating to our exception
https://github.com/mgilbertnz/scalajs-stacktrace-test/raw/master/nonclosure.png

To run in **production** mode to produce failure case:
```
sbt stage
cd application/server/target/universal/stage/bin
./crm-stacktrace-test
```
Browse to http://localhost:9000
In debugging tools observe that we have no mention of the calls within optimised code
https://github.com/mgilbertnz/scalajs-stacktrace-test/raw/master/withclosure.png

Due to the closure compiler producing sourcemaps I expected calls within my app to be present in the stack trace so they can be translated with the sourcemaps.

Apologies if this isn't a bug or belongs elsewhere.

**Comment by sjrd** [comment]
Source maps produce information about source positions, but do not preserve other information. In particular, when inlining a method `m2` inside `m1`, `m2` will not show up in stack traces anymore. Only `m1` will.

So this is not a bug. At least the situation cannot be improved until the source map specification is enhanced with the ability to record more information.
