### ISSUE TITLE
Compile scala-js compiler to javascript

### ISSUE THREAD

**Issue by ryan-williams** [scala-js/scala-js#3301]
Discussed this in [scalafiddle gitter](https://gitter.im/scalafiddle/scalafiddle?at=5aa912d953c1dbb743debab1) recently, and think it's worth having an issue around.

Highlights from @sjrd:

> The hard parts are within scalac.
> Dependencies on the file system, on reflection (for macros and compiler plugins), on the ASM library, etc.
> …
> The part about macros and compiler plugins requires some cleverness. Everything else is probably relatively dumb work.
> Like, instead of reflection, the compiler would have to be re-linked on the fly with the project's dependency classpath, with macro entry points being reified in dictionaries.

For further motivation, I was just reading [a ReasonML post](http://blog.klipse.tech/reason/2018/03/12/blog-reason-types.html#ordinary-variants---brief-recap) featuring static, interactive code widgets powered by [klipse](https://github.com/viebel/klipse), which [supports a bunch of languages](https://github.com/viebel/klipse#supported-languages):

> - clojure[script]: evaluation is done with [Self-Hosted Clojurescript](http://swannodette.github.io/2015/07/29/clojurescript-17)
> - ruby: evaluation is done with [Opal](http://opalrb.org/)
> - C++: evaluation is done with [JSCPP](https://github.com/felixhao28/JSCPP)
> - python: evaluation is done with [Skulpt](http://www.skulpt.org/)
> - scheme: evaluation is done with [BiwasScheme](http://www.biwascheme.org/)
> - PHP: evaluation is done with [Uniter](https://asmblah.github.io/uniter/)
> 
> The code editing inside the interactive snippets is powered by [CodeMirror](http://codemirror.net/).

Python! PHP! Scala seems like a conspicuous absence here, and afaict the story now is "we can't do it because we don't have the right abstractions in scalac", which would be nice to fix!

**Comment by sjrd** [comment]
While I sympathize with the desire to have a self-hosted Scala.js compiler, this issue tracker is not the right place:

* It is not something the core Scala.js team ever intends to do themselves
* Implementing it would be in a separate repository anyway

This issue tracker is meant to track actionable issues whose solution would have to be implemented in this repository. Everything else is "wishful thinking" as far as this repository is concerned, and clutters our list of open issues. Examples of other issues that have been closed on the same grounds are #2920, #1703, #440, #239, etc.

The [Scala.js mailing list](https://groups.google.com/forum/#!forum/scala-js) is a better avenue for such a discussion.
