### ISSUE TITLE
Add some tests for Longs in fullOpt stage

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#3312]
#3311 blacklisted LongTest in fullOpt stage because it generates too much code for GCC to handle.

We should have some tests for Longs just to make sure GCC doesn't break our implementation.

**Comment by sjrd** [comment]
We probably don't cover the corner cases, but the normal behavior is probably reasonably well tested by all the `Long`s in the library that are used to implement other stuff we do test. For example, the big numbers extensively rely on `Long`s.

**Comment by gzm0** [comment]
Ok, fair enough.
