### ISSUE TITLE
Introduce `org.scalajs.testing` package

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#3340]
Currently we have the following packages that are intimately related:
- `org.scalajs.testcommon`
- `org.scalajs.testadapter`
- `org.scalajs.testinterface`

Since the latter two share common functionality in the first one, there is a lot of `private[scalajs]` stuff in there. This is odd, since it gives the impression that the testing integration treats entire Scala.js as a special snowflake (which it doesn't #3337 is an example of us actively working to not make it special).

If we add a dot to all the packages above (e.g. `org.scalajs.test.common`, etc.) we can make them `private[test]`, which makes much more sense IMO.

**Comment by gzm0** [comment]
@sjrd WDYT?

**Comment by sjrd** [comment]
Sounds good. Not sure about `test` itself, though. It's awfully generic for something that's supposed to be rather internal. Maybe `testinfra`, or even `sbttesting` (it's not related to sbt, but it *is* related to sbt-test-interface).

**Comment by gzm0** [comment]
How about just `testing`? Just like `sbt.testing`?

**Comment by sjrd** [comment]
:+1:
