### ISSUE TITLE
Add support for Java CompletableFuture

### ISSUE THREAD

**Issue by hepin1989** [scala-js/scala-js#3343]

**Comment by sjrd** [comment]
[`CompletableFuture`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html) is a sizable API with a non-trivial implementation, that we do not need in the core. So we won't integrate that in the core repo. This is why I'm closing this issue.

You can provide support for it in a separate library without depending on us, for example see https://github.com/scala-js/scala-js-java-logging as a small example, and https://github.com/cquiroz/scala-java-locales for another externally provided part of the JDK (not administered by the scala-js organization).

**Comment by hepin1989** [comment]
Thanks for that information.
