### ISSUE TITLE
Allow setting module.exports for CommonJS module

### ISSUE THREAD

**Issue by asoltysik** [scala-js/scala-js#3345]
## Problem

Currently
`scalaJSModuleKind := ModuleKind.CommonJSModule`
used together with
``` scala
@JSExportTopLevel("foo")
def foo...
```
generates code that's equivalent of
`exports = foo`.
However, according to this SO answer: https://stackoverflow.com/questions/7137397/module-exports-vs-exports-in-node-js if we want to allow required modules to be called like a function, for example:
`var x = require('./our_scalajs_module.js')()`
we need to generate code that does equivalent of:
`module.exports = foo`.

This is required for interopability with some js frameworks (probot in my case).

## Possible solution
Additional annotation that would allow this?

**Comment by sjrd** [comment]
`@JSExportTopLevel` without string parameter does not exist. Please give a full example.

Besides, Scala.js cannot do either `exports = foo` nor `module.exports = foo`, because ECMAScript 2015 modules cannot do that.

**Comment by asoltysik** [comment]
Sorry, I meant it currently does `exports.foo = foo`, like in my generated file by fastOptJS:
``` javascript
var $e = exports;
// ...and at the end of the file:
$e.foo = (function(arg$1) {
  var prep0 = arg$1;
  $m_Lscalafmtprobot_Lib$().foo__Lscalafmtprobot_Robot__V(prep0)
});
```
I work around this problem by manually editing the generated file by adding:
``` javascript
module.exports = $e.foo
```


> Besides, Scala.js cannot do either exports = foo nor module.exports = foo, because ECMAScript 2015 modules cannot do that.

As mentioned I am using `scalaJSModuleKind := ModuleKind.CommonJSModule` setting in sbt.

**Comment by sjrd** [comment]
Yes, I'm afraid this is a won't fix.

ECMAScript 2015 modules do not allow to export an arbitrary object/function as the module itself. They only allow exporting *members* of a special module-object. Since Scala.js semantically follows ES 2015, it does not provide any language feature that cannot be translated to ES 2015, and therefore does not provide any way to export an arbitrary value as `module.exports
