### ISSUE TITLE
Doubles in hex notation fail to parse

### ISSUE THREAD

**Issue by martijnhoekstra** [scala-js/scala-js#3348]
reproducer:

`scala.util.Try("0x0p1".toDouble)`

expected:

`Success(0.0)`

actual:

`Failure(java.lang.NumberFormatException: For input string: "0x0p1")`

**Comment by sjrd** [comment]
Thanks for the report. There is no fundamental reason that this should not be supported.

**Comment by sjrd** [comment]
This is trickier than it looks. Wip here: https://github.com/scala-js/scala-js/compare/0.6.x...sjrd:parse-double-hex
Needs more tests.

**Comment by sjrd** [comment]
I have stopped looking at Harmony to be as independent as possible license-wise. I generated random test cases on the JVM, so now I've enough of them.

**Comment by sjrd** [comment]
Fixed in 2175de9e05da2a88cd3a0deb289f09adee7e76dd.
