### ISSUE TITLE
A nicer Javascript object/JSON AST/API

### ISSUE THREAD

**Issue by lihaoyi** [scala-js/scala-js#336]
I've been wrestling with structured JSON: taking it from and returning it to the github gist API. I'm not sure whether i'm doing something wrong, but AFAIK the inbuilt constructs (js.Dynamic, js.Object, js.Any, js.Dictionary) are all extremely hard to use:
- js.Dictionary doesn't let you iterate over keys/values, and doesn't allow recursive types 
- js.Object doesn't do, well, anything
- js.Dynamic has breaks when your keys have special characters, since dynamicThing.`my key` doesn't work right

Are there any thoughts about providing a nicer API for dealing with nested JS structures? Something like the Play/Spray/whatever Json AST where you can easily put together a nice hierarchical structure as well as navigating it using strings. Currently I'm doing things like:

``` scala
          data = js.JSON.stringify(
            lit(
              description = "Scala.jsFiddle gist",
              public = true,
              files = js.Dictionary(
                ("Main.scala": js.String) -> lit(
                  content = code
                )
              )
            )
          )
```

For constructing stuff, and 

``` scala
    val allFiles = result.files.asInstanceOf[js.Dictionary[js.Dynamic]]

    val mainFile = allFiles("Main.scala")

    val firstFile = allFiles(js.Object.keys(allFiles)(0).toString)

    val content = (if (!mainFile.isInstanceOf[js.Undefined]) mainFile else firstFile).selectDynamic("content").toString
```

For querying with my JSON, and it looks really gross both ways.

**Comment by sjrd** [comment]
It seems that in 2.5 years, no one ever cared enough to submit a small PR about this, so I'm going to close it.
