### ISSUE TITLE
Incorrect test count summary with Scalatest 3.0.5 and Scala.js 0.6.22

### ISSUE THREAD

**Issue by sbusard** [scala-js/scala-js#3363]
With Scala.js 0.6.22 and Scalatest 3.0.5, the number of tests reported when running JS tests is incorrect.

This can be reproduced on the standard Scala.js cross-compile example with https://github.com/sbusard/scalajs-cross-compile-example/commit/355644d883ae2024f10c5ef54c707b583bb3e3c1 .

When running the `test` command in sbt, the following is reported:
```
[info] DummySpec:
[info] A succeeding dummy test
[info] - should pass
[info] A failing dummy test
[info] - should fail *** FAILED ***
[info]   Should fail (DummySpec.scala:13)
[info] Run completed in 525 milliseconds.
[info] Total number of tests run: 2
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 1, canceled 0, ignored 0, pending 0
```
for JVM tests (note that the number of run tests is correct), and
```
[info] DummySpec:
[info] A succeeding dummy test
[info] - should pass
[info] A failing dummy test
[info] - should fail *** FAILED ***
[info]   Should fail (DummySpec.scala:13)
[info] Run completed in 140 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
```
for JS tests; note that 0 tests are reported, even if the information of passing/failing is printed above.

This issue is linked with the following (on Scalatest side): https://github.com/scalatest/scalatest/issues/1330

Note that the number of reported tests is correct with Scala.js 0.6.21 and Scalatest 3.0.5.

**Comment by gzm0** [comment]
Thank you for the report. After investigation it seems that this is a latent ScalaTest bug that surfaced with a different invocation scheme caused by 22a8d7dc52669c537154f21519752a8b6680a174 / #2645. More details are on the ScalaTest issue.

**Comment by sbusard** [comment]
Thanks for the investigation!
