### ISSUE TITLE
Unexpected behaviour - When a promise is completed, associated code executes in reverse chronological order

### ISSUE THREAD

**Issue by rdc247** [scala-js/scala-js#3365]
Take the following code extract :-
```scala
import client.websockets.WebSocket.Status
import org.scalajs.dom
import org.scalajs.dom.raw
import shared.websockets.Protocol
import shared.websockets.Protocol._
import scala.concurrent.{Future, Promise}
import scalajs.concurrent.JSExecutionContext.Implicits.queue

private class WebSocket( msgReceiver : Protocol.Message => Unit, statusReceiver : Status.Value => Unit )
{
  private val wsProtocol = if (dom.document.location.protocol == "https:") "wss" else "ws"
  private val wsUri = s"$wsProtocol://${dom.document.location.host}/stream"
  private val connection = new raw.WebSocket(wsUri)
  private val chatIsInitialised = Promise[Boolean]
  private val fChatIsInitialised : Future[Boolean] = chatIsInitialised.future

  connection.onopen = ( _ : dom.Event) => {
    chatIsInitialised.success( true )
    statusReceiver( Status.Opened )
  }

 def send( msg : String ): Unit =
  {
    fChatIsInitialised.foreach( _ => connection.send( msg ) )
  }
}
```
So `connection.send()` is only called when the connection is open, and the `chatIsInitialised` promise has been completed. The unexpected behaviour is that if `send( "A") ; send("B") ; send( "C" ) ; send( "D" )` is called before the connection has been initialised, then when the connection opens, the messages will be sent in order `"D";"C","B","A"`. I presume this is because the code is executed in reverse to the order of association. (Stacked instead of queued?)

**Comment by sjrd** [comment]
This is a correct behavior. `Future`s do not guarantee any ordering of the callbacks. This is explicitly specified in the documentation of [`Future.onComplete`](https://www.scala-lang.org/api/2.12.6/scala/concurrent/Future.html), which is called by `foreach`.

Btw, if you're not sure whether something is actually a bug, [StackOverflow](https://stackoverflow.com/questions/tagged/scala.js) or [Gitter](https://gitter.im/scala-js/scala-js) are better venues. This issue tracker is for actual bugs, not for questions.
