### ISSUE TITLE
Remove dependency on apigee's fork of rhino

### ISSUE THREAD

**Issue by wongelz** [scala-js/scala-js#3373]
This dependency was committed in 2015 (https://github.com/scala-js/scala-js/commit/f9e618a37c8f4e94bbec13b1b6cf4880a15f3b96#diff-215113124f1de02f228327ba7abb45f7) but sbt-js-engine now depends on a later version of the standard Rhino (Mozilla rather than Apigee).

This is causing the sort of problem the original commit was trying to avoid. eg. https://github.com/sbt/sbt-less/issues/95

**Comment by sjrd** [comment]
As mentioned at https://github.com/sbt/sbt-less/issues/95#issuecomment-395419033, as a workaround a user can put the following in `project/plugins.sbt`:
```scala
excludeDependencies += "io.apigee" % "rhino"
```

**Comment by sjrd** [comment]
https://github.com/mozilla/rhino/issues/448 means that using Rhino >= 1.7.7 with Scala.js causes integer multiplication to be faulty.

**Comment by sjrd** [comment]
Fixed in d07204e2c1184ddbb43069dce4b7ae2dc0377c42.
