### ISSUE TITLE
The website could mention sharing code with backend in the "Interoperability" section

### ISSUE THREAD

**Issue by kubukoz** [scala-js/scala-js#3397]
e.g. something like this:

![image](https://user-images.githubusercontent.com/894884/42106325-f430de36-7bd3-11e8-99b6-e50e2d340591.png)

Although it's understandable if it doesn't add much :P

**Comment by sjrd** [comment]
I don't think it makes much sense, no.

Anyway, this should be an issue in [scala-js-website](https://github.com/scala-js/scala-js-website/issues), not here, so I'm going to close this issue.

**Comment by kubukoz** [comment]
Sorry, I was misled due to the github link on the website leading here ;)
