### ISSUE TITLE
Limitations of java.util.Formatter (and String.format)

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#3407]
After the big rewrite of #3380 and its numerous fixes, there are still a few things that are not supported in `java.util.Formatter` and therefore in `String.format`:

* Hexadecimal format for floating point numbers with `%a`.
* Formatting of `BigInteger`s and `BigDecimal`s.
* Formatting of date/times with the `%t.` family.

The first two might be doable at some point. Formatting dates would bring in way to much code in every Scala.js application, and there are better APIs for that now in `java.time` anyway.

See also #3202 which records that `%f`, `%e` and `%g` have rounding discrepancies compared to the JVM.

**Comment by pfcoperez** [comment]
I had a patch for `BigInteger` formatter and I was opening an issue to describe what it fixes when I found this issue so I ended up not opening another issue :sweat_smile: 

This is the PR with the patch fixing `b.formatted("%d")`, `b.formatted("%o")` and `b.formatted("%x")`.

**Comment by sjrd** [comment]
An update here:

* `BigInteger` support was implemented in #4255, as mentioned above.
* `BigDecimal` support was implemented in #4444.
* The `%a` conversion was implemented in #4440.

In addition, the related issue #3202 was fixed in #4443.

That leaves only the date/time conversions, for which I have created a separate issue #4447.

So this one can be closed now.
