### ISSUE TITLE
Crash in jsDependencies resolution on Windows due to some path issue

### ISSUE THREAD

**Issue by vi-kas** [scala-js/scala-js#3417]
While trying to test my scala-js application, I was facing this issue where tests were running on Mac but not on windows. The issue was happening because of the `jsDependencies` resolution, while materializing  js files on windows system, the path was not correct.

I tried to reproduce the same with a minimal example where my scala-js app depends on:

     `libraryDependencies += "superfoo" %%% "foo" % "0.1-SNAPSHOT"`

This dummy module `foo` has `moment.js` as a `jsDependency`. I executed tests for the application on windows as well as on Mac.

**Windows** - Didn't work!
-------

```
VirtualFileMaterializer :: path => C:\Users\VIK\.ivy2\local\superfoo\foo_sjs0.6_2.12\0.1-SNAPSHOT\jars\foo_sjs0.6_2.12.jar:moment.js
                           name => C:\Users\VIK\.ivy2\local\superfoo\foo_sjs0.6_2.12\0.1-SNAPSHOT\jars\foo_sjs0.6_2.12.jar:moment.js
```
    Results in Exception:
    `C:\Users\VIK\AppData\Local\Temp\1532419615932-0\C:\Users\VIK\.ivy2\local\superfoo\foo_sjs0.6_2.12\0.1-SNAPSHOT\jars\foo_sjs0.6_2.12.jar:moment.js (The filename, directory name, or volume label syntax is incorrect)`
    
    Cuz it searches for 
           `C:\Users\VIK\AppData\Local\Temp\1532419615932-0\foo_sjs0.6_2.12.jar:moment.js`
    but it gets
           `C:\Users\VIK\AppData\Local\Temp\1532419615932-0\C:\Users\VIK\.ivy2\local\superfoo\foo_sjs0.6_2.12\0.1-SNAPSHOT\jars\foo_sjs0.6_2.12.jar:moment.js`

                           
Mac - Works!
---
```
VirtualFileMaterializer :: path => /Users/vika/.ivy2/local/superfoo/foo_sjs0.6_2.12/0.1-SNAPSHOT/jars/foo_sjs0.6_2.12.jar:moment.js
                           name => foo_sjs0.6_2.12.jar:moment.js
                           
```
                           
The problem is this function in 
https://github.com/scala-js/scala-js/blob/v0.6.24/tools/shared/src/main/scala/org/scalajs/core/tools/io/VirtualFiles.scala#L47
```

def nameFromPath(path: String): String = {
    val pos = path.lastIndexOf('/')
    if (pos == -1) path
    else path.substring(pos + 1)
  }
```

**Comment by sjrd** [comment]
Fixed in 65c123d2a016d08e28637b9796ed0bac7e0b3a60.
