### ISSUE TITLE
Unexpected output when importing js module

### ISSUE THREAD

**Issue by allantl** [scala-js/scala-js#3428]
I created a facade for this (https://atlaskit.atlassian.com/packages/core/button) button react component to use with scalajs-react. Everything was working perfectly.

So I upgraded to their latest version(8.2.7 -> 9.0.5). Things just break (Never had this issue before).
I didn't notice any change in their import compared to the previous version.

So, the equivalent import in javascript is

```
Import Button from "@atlaskit/button"

<Button>Hello</Button>
```

and my Scala js Module is 

```
object Button {

  @JSImport("@atlaskit/button", JSImport.Default)
  @js.native
  object RawComponent extends js.Object

}
```

In version, 8.2.7 when I tried to print `RawComponent`, the result is:
<img width="1002" alt="screen shot 2018-08-14 at 21 18 47" src="https://user-images.githubusercontent.com/14335852/44095659-f61cc53c-a00b-11e8-91e0-8084008e44b3.png">

But, with the latest version
<img width="898" alt="screen shot 2018-08-14 at 21 21 25" src="https://user-images.githubusercontent.com/14335852/44095706-14055294-a00c-11e8-8a03-5de58b20e7b0.png">

Could this be a scalajs issue?

To reproduce, I created a repo: https://github.com/allantl/scala-js-interop

**Comment by sjrd** [comment]
It's very unlikely to be an issue in Scala.js. The very fact that your changing the version of `atlaskit/button` is causing your issue should be a very strong intel that `atlaskit/button` is the cause, not Scala.js.

**Comment by allantl** [comment]
Alright, thanks. I'll close the issue.
