### ISSUE TITLE
UTF-8 CharsetDecoder doesn't handle incomplete character ranges correctly

### ISSUE THREAD

**Issue by martijnhoekstra** [scala-js/scala-js#3433]
Trying to consume a bytebuffer with an incomplete character at the end of a buffer should result in rejecting the buffer and returning underflow, rather than handling it as an invalid byte sequence.

As seen on https://scalafiddle.io/sf/WsaQcxb/0

I have not minimized whether the issue is in CharsetDecoder's `decode` method, or in the `decodeLoop` method of the UTF-8 decoder.

**Comment by martijnhoekstra** [comment]
The issue is at https://github.com/scala-js/scala-js/blob/4868d380d83e2f22fb7a940611c9f7fe909b74a9/javalib/src/main/scala/java/nio/charset/UTF_8.scala#L109 which returns malformed on an incomplete byte sequence. It should return CoderResult.UNDERFLOW, but care must be taken that the leading character isn't consumed in that case

**Comment by sjrd** [comment]
Fixed in 7afff5db87a3aa26cfd8fd3ec36a967e618c6c14.
