### ISSUE TITLE
Double with zero-decimals converted to Int ??

### ISSUE THREAD

**Issue by ThijsBroersen** [scala-js/scala-js#3460]
I noticed a different behavior between Scala en Scala-js when executing the following code:
```
println(((0.1: Double): Any) match {
  case v: Int => "int"
  case v: Double => "double"
  case v: Long => "long"
})
println(((0.0: Double): Any) match {
  case v: Int => "int"
  case v: Double => "double"
  case v: Long => "long"
})
println(((1.0: Double): Any) match {
  case v: Int => "int"
  case v: Double => "double"
  case v: Long => "long"
})
println(((4l: Long): Any) match {
  case v: Int => "int"
  case v: Double => "double"
  case v: Long => "long"
})

println(((0.1: Double): Any).getClass)
println(((0.0: Double): Any).getClass)
println(((1.0: Double): Any).getClass)
println(((4: Int): Any).getClass)
println(((4l: Long): Any).getClass)
println(4.getClass)
println(4.0.getClass)
```

Scala: https://scastie.scala-lang.org/BFB7BroMR7qVmfuLAXoB4w
Scala-js: https://scalafiddle.io/sf/CE9ngkX/2

Scala-js converts to different types when the numeric values are viewed as Any.
Scala-js uses java.lang.Float instead of java.lang.Double
Scala-js uses java.lang.Byte instead of java.lang.Integer
Long is working fine.

Why is this?

**Comment by sjrd** [comment]
That is as-designed. It's all explained here: https://www.scala-js.org/doc/semantics.html
