### ISSUE TITLE
stackoverflow error when using scalajs 1.0.0-M6

### ISSUE THREAD

**Issue by pjfanning** [scala-js/scala-js#3475]
I tried the play-json build with scalajs 1.0.0-M6 instead of 0.6.x and the build fails with a stackoverflow.

Other logging seems to indicate that there is an incompatibility with sbt-scalajs-crossproject 0.6.0.

It's probably easiest to view the stacktrace at https://travis-ci.org/pjfanning/play-json/jobs/443898586

There are a lot of repeated calls to this:
```
at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3194)
	at scala.tools.nsc.typechecker.Typers$Typer.handleOverloaded$1(Typers.scala:3191)
```

**Comment by sjrd** [comment]
1.0.0-M6 has not been announced yet. You should try 1.0.0-M5 and read [its release notes](https://www.scala-js.org/news/2018/08/13/announcing-scalajs-1.0.0-M5/). In particular the bullet that reads

> * Drop compatibility with sbt-crossproject v0.4.x and earlier (v0.5.0 or later is required)

You need to upgrade sbt-crossproject (and sbt-scalajs-crossproject) to 0.5.0 or later (latest is 0.6.0).
