### ISSUE TITLE
Outdated documentation on Cross-Building

### ISSUE THREAD

**Issue by AlexanderArendar** [scala-js/scala-js#3479]
I am using scala.js 0.6.25
When I try to compile I see the following among other output in my console:
```
ssd2/projects/scalajstest/build.sbt:14: warning: method crossProjectFromBuilder in trait CrossProjectExtra is deprecated (since 0.6.23): The built-in cross-project feature of sbt-scalajs is deprecated. Use the separate sbt plugin sbt-crossproject instead: https://github.com/portable-scala/sbt-crossproject
lazy val app = crossProject.in(file(".")).
               ^

```
In the [current documentation](https://www.scala-js.org/doc/project/cross-build.html) it is said that `sbt-crossproject` is used with Scala.js 1.x
So it is not clear why with 0.6.25 the built-in crossProject is complained as deprecated. Could you advice?

**Comment by sjrd** [comment]
Indeed, the documentation is out of date, although that's an issue for https://github.com/scala-js/scala-js-website instead of this repo. You should use sbt-crossproject both in 0.6.x and 1.x.
