### ISSUE TITLE
regex_replace for replacing case insensitive strings not working

### ISSUE THREAD

**Issue by nityanands** [scala-js/scala-js#3484]
SO i have been using the custom regex_replace function to replace a substring within my actual string.
Here is how i am using it.
regexp_replace(col, pattern, replacement)
where col: is the column name where i am passing employee name: My name is Nitya
pattern: is what i am searching for: Nitya 
replacement: what is to be replaced with: NS
The moment the col comes up with a value 'My name is nitya', it fails to replace the string. I have tried using lower on both sides, but the problem is the entire string in the col is converted to lowercase which is not what i want. Is this doable using regex_replace at all or there is another alternative to achieve this ?

**Comment by sjrd** [comment]
I don't think I understand your problem. There does not seem to be anything named `regex_replace` related to Scala.js. Are you perhaps posting an issue in the wrong repository?

**Comment by nityanands** [comment]
My query was related to spark scala

**Comment by sjrd** [comment]
Then I'm afraid you're definitely in the wrong repo. This repo is about Scala.js, which has literally nothing to do with Spark.
