### ISSUE TITLE
Shared Scalajs facade for types defined by Typescript core?

### ISSUE THREAD

**Issue by benhutchison** [scala-js/scala-js#3498]
Is there interest in a small, shared/central Scalajs library for types defined by Typescript core, such as [ReadonlyArray](https://github.com/Microsoft/TypeScript/blob/release-3.1/src/lib/esnext.array.d.ts#L1) and [PromiseLike](https://github.com/Microsoft/TypeScript/blob/release-3.1/lib/lib.es5.d.ts#L1316)?

Something along the lines of [scala-js-dom](https://github.com/scala-js/scala-js-dom)..

When working with the Typescript to Scalajs Importer, Im noticing that it references such types, but they aren't defined anywhere, leading to duplicated copies within projects, such as this [metabrowse example](https://github.com/scalameta/metabrowse/blob/master/metabrowse-js/src/main/scala/monaco/PromiseLike.scala#L11).

The reasons such a library makes sense to be centralized is:
- The scope or charter is clearly defined, it'd only contains Scalajs versions of basic types defined by Typescript
- To align it with the importer so the importer-emitted references to such types aligned with the libraries names
- Typescript looks to play a leading role in the future of JS ecosystem; good Typescript <-> Scalajs interop will be important for Scalajs success in future in my estimation.

**Comment by sjrd** [comment]
`PromiseLike[A]` is called `js.Thenable[A]` in Scala.js. This name aligns with the ECMAScript specification.

`ReadonlyArray[A]` is adequately represented as `js.Array[_ <: A]` in Scala.js.

**Comment by benhutchison** [comment]
Currently, https://github.com/sjrd/scala-js-ts-importer emits refs to `PromiseLike` & `ReadonlyArray` when those types are in the input TS. 

Where there is an existing type defined in Scala.js, one solution is to be to teach the importer a rewrite mapping from TS-name to Scalajs name. @sjrd does your response above suggest you think that approach is the one to pursue?

How confident can we be that all the types defined in TS already have corresponding Scalajs forms? `Uint32Array` is another example Ive encountered emitted from Monaco TS.

**Comment by sjrd** [comment]
> @sjrd does your response above suggest you think that approach is the one to pursue?

Yes, basically.

> How confident can we be that all the types defined in TS already have corresponding Scalajs forms? Uint32Array is another example Ive encountered emitted from Monaco TS.

As long as they have a spec equivalent, they are supposed to receive a type definition in the Scala.js standard library, although we are missing some at the moment, such as `Map` and `Set`.

Typed arrays are in the subpackage `js.typedarray.*`.

**Comment by benhutchison** [comment]
The best library is the one you dont have to maintain. Closing in favor of names translation in the importer.
