### ISSUE TITLE
Proposal: `@js.native` vals and defs

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#3500]
Currently, we can use `@js.native` only on `class`es and `object`s (and `trait`s, but with a different story). We can do that if they are at the top-level of a package, or within a static Scala `object`. For example:
```scala
object Container {
  @js.native
  @JSImport("foo.js", "bar")
  object Bar extends js.Object
}
```
This allows to easily import (or fetch from the global scope) *classes* and *objects* from JavaScript. However, for values and functions, we have to use an artificial enclosing object, and then use members of that object. For example:
```scala
@js.native
@JSImport("foo.js", JSImport.Namespace)
object Foo extends js.Any {
  val bar: Int = js.native
  def baz: String = js.native
  def add(x: Int, y: Int): Int = js.native
}
```
This is an inconsistent limitation, especially when contrasted with:
* `@JSExportTopLevel`, which can be used on any static term definition, and
* the fact that in Scala, every level of scoping obeys the same rules.

I propose that we allow `@js.native` (together with `@JSGlobal` or `@JSImport`) on `val`s, getter `def`s and method `def`s (not on setter `def`s) enclosed in a static Scala object (just like we do for `class`es and `object`s). And if Scala ever supports top-level `val`s and `def`s, we would extend `@js.native` to those as well. The right-hand side must in that case be `= js.native`. For example:
```scala
object Container {
  @js.native
  @JSImport("foo.js", "bar")
  val bar: Int = js.native

  @js.native
  @JSImport("foo.js", "baz")
  def baz: String = js.native

  @js.native
  @JSImport("foo.js", "add")
  def add(x: Int, y: Int): Int = js.native
}
```
In addition to the consistency argument, the above definition, while more verbose given the multiple imports, will allow to emit (and guarantee) better code for ES modules. Indeed, we will be able to avoid namespace imports, which have poor properties in terms of cross-module dead-code-elimination, something that is supposed to be one of the flagship advantages of ES modules.

Such definitions would naturally also be allowed in `package object`s, which will compensate the fact that we forbade package objects from extending `js.Any`.

**Comment by ramnivas** [comment]
This is excellent! One more way it will help is avoid casting. In our code base, we have several instances of the following kind:
```scala

object LandingPage extends StatelessComponentWrapper {
  @js.native
  @JSImport("resources/img/logo-banner.png", JSImport.Default)
  object LogoBanner extends js.Object

  ...
  img(src := LogoBanner.asInstanceOf[String], alt := "LearnRaga")
  ...

}
```

With the proposal, I believe, we will be able to do the following:

```scala
object LandingPage extends StatelessComponentWrapper {
  @js.native
  @JSImport("resources/img/logo-banner.png", JSImport.Default)
  val logoBanner: String = js.native

  ...
  img(src := logoBanner, alt := "LearnRaga")
  ...

}
```

**Comment by sjrd** [comment]
> With the proposal, I believe, we will be able to do the following:

Indeed.

**Comment by dispalt** [comment]
Oh that will eliminate a lot of casts, I like it!

**Comment by gzm0** [comment]
I'm tentatively scheduling this post-1.0.0. @sjrd if there are binary compatibility concerns, please revise.
