### ISSUE TITLE
Remove __ScalaJSEnv

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#3504]
There are currently 3 usages:

- `exitFunction` to fill `System.exit`; this was introduced for #958 as a means to terminate PhantomJS in async tests. Testing support has improved substantially since then, so it is not needed anymore. If a platform agnostic termination is required a library should be created for it.
- `sourceMapper` introduced as a stop-gap solution to support source mapping in Rhino. Unused.
- `javaSystemProperties` introduced as a hack to allow to pass in tags for testing. Already made more SJS internal in the past (by not honoring `javaOptions` in sbt anymore). Should be replaced by a fully SJS internal solution.

Any objections?

**Comment by sjrd** [comment]
For `exitFunction` and `sourceMapper`, no objection. I guess `System.exit()` and `Runtime.exit()` should be removed, causing a linking error in the future.

For `javaSystemProperties`, it's trickier. What would be the replacement? Would we just say that everyone's `main()` method should start by filling up `System.getProperties()` with their own notion of how to get system properties from an "environment"?

Also, currently the `JSEnv` test kit relies on `__ScalaJSEnv.exitFunction()`. What will happen to those tests? Will they be removed?

**Comment by gzm0** [comment]
For `javaSystemProperties` I see multiple options (depending on the end user need):

- JS `main` fills required things statically (SJS does this for version information).
- JS `main` fills required things via external file (via `@JSImport`).
- Use source code generation.
- Use a wrapper that only uses system properties on JVM and uses something else on JS (similar to how we deal with reflection).

> Also, currently the JSEnv test kit relies on __ScalaJSEnv.exitFunction(). What will happen to those tests? Will they be removed?

I was going to add back the option that allows a `JSEnv` to specify a statement that terminates it. If the option is set, the tests are enabled.

**Comment by sjrd** [comment]
That sounds reasonable.
