### ISSUE TITLE
fullOptJS generates invalid JS with SyntaxError

### ISSUE THREAD

**Issue by exoego** [scala-js/scala-js#3508]
After I recently updated just dependencies of [my Scala.js project (a Scala.js port of scala-js-ts-importer)](https://github.com/exoego/scala-js-ts-importer/tree/5e45a9db40737c4440a3bacf2565c4e58dd42304), 
the `fullOptJS`-generated script raises `Uncaught SyntaxError: Label 'b' has already been declared`.

`fastOptJS` has no broblem.

I assume this is caused by latest Scala.js or combination problem with Google Closure Compiler since my code is not modified during updates.
* Scala.js 0.6.26
* Scala 2.12.8
* sbt 1.2.7
* Please find other dependencies in [(my repository)](https://github.com/exoego/scala-js-ts-importer/tree/5e45a9db40737c4440a3bacf2565c4e58dd42304), 

# How to reproduce

1. Clone and build.
```bash
git clone https://github.com/exoego/scala-js-ts-importer.git
cd scala-js-ts-importer
git reset --hard 5e45a9db40737c4440a3bacf2565c4e58dd42304
sbt fullOptJS
```
2. Run any http server to server html and JS. 
For example:
```bash
npm install -g http-server
http-server
```
3. Open http://localhost:8080/index.html
4. Enter `F12` to open the browser's devtool.
5. Click "zip.js" on the left sidebar of web page.
6. You will see `Uncaught SyntaxError: Label 'b' has already been declared` in devtool.
![image](https://user-images.githubusercontent.com/127635/49780158-a27b4a00-fd50-11e8-9e8c-9fcc91ebe534.png)

# The generated probelmatic code

Below is the problematic part of full-optimized JS (formatted for readability).
Label `b:` is defined twice in same function.

```js
function zg(a, b) {
  var d = !1, e = null;
  a:if (b && b.$classData && b.$classData.l.$e) Hf(a, b); else if (Ag(b)) b:{ // HERE "b:"
    if (null !== b && (e = b.gd, d = b.ce, G().g(d))) {
      b = (new M).$((new L).w(["", ""]));
      e = Sf(Tf(), (new L).w([e]));
      a = a.Y;
      d = O().ta;
      vg(P(), b, e, a, d);
      break b
    }
    Bg || (Bg = (new Cg).a());
    e = Bg.mg(b);
    if (e.j()) if (Dg || (Dg = (new Eg).a()), e = Dg.mg(b), e.j()) if (e = jd().ck, null === e ? null === b : e.g(b)) b = (new M).$((new L).w(["this.type"])), a = a.Y, e = O().ta, vg(P(), b, G(), a, e); else if (e = Ce().mg(b), e.j()) if (e = Od().mg(b), e.j()) if (null !== b) {
      e = b.gd;
      b = b.ce;
      d = (new M).$((new L).w(["", "[", "]"]));
      a = a.Y;
      var f = O().ta;
      vg(P(), d, (new L).w([e, b]), a, f)
    } else throw(new y).k(b); else e = e.qa(), b = (new M).$((new L).w(["", "*"])), e = Sf(Tf(), (new L).w([e])), a = a.Y, d = O().ta, vg(P(), b, e, a, d); else e = e.qa(), b = (new M).$((new L).w(["", ".type"])), e = Sf(Tf(), (new L).w([e])), a = a.Y, d = O().ta, vg(P(), b, e, a, d); else b = e.qa(), e = O().ek, vg(P(), (new M).$((new L).w(["", ""])), (new L).w([b]), a.Y, e); else b = e.qa(), e = O().ao, vg(P(), (new M).$((new L).w(["", ""])), (new L).w([b]), a.Y, e)
  } else if (b && b.$classData &&
    b.$classData.l.ak) b:{ // And HERE "b:"
    if (null !== b && (e = b.og, K() === e)) {
      b = (new M).$((new L).w(["_"]));
      a = a.Y;
      e = O().ta;
      vg(P(), b, G(), a, e);
      break b
    }
    if (null !== b && (e = b.og, Hc(e))) {
      e = e.A;
      b = (new M).$((new L).w(["_ \x3c: ", ""]));
      e = Sf(Tf(), (new L).w([e]));
      a = a.Y;
      d = O().ta;
      vg(P(), b, e, a, d);
      break b
    }
    throw(new y).k(b);
  } else {
    if (b && b.$classData && b.$classData.l.Zj && (d = !0, e = b, null !== e.Ta && 0 === e.Ta.mb(4))) {
      var g = e.Ta.ja(0), k = e.Ta.ja(1), m = e.Ta.ja(2), f = e.Ta.ja(3), n = wd().Dd;
      (null === n ? null === g : n.g(g)) ? (g = wd().lm, (null === g ? null === k : g.g(k)) ? (k = wd().Wi,
        m = null === k ? null === m : k.g(m)) : m = !1) : m = !1;
      if (m) {
        a.Pf.ig("js.");
        a.Pf.pg("" + f);
        break a
      }
    }
    if (d && null !== e.Ta && 0 === e.Ta.mb(2) && (f = e.Ta.ja(0), m = e.Ta.ja(1), k = wd().Dd, null === k ? null === f : k.g(f))) {
      a.Pf.pg("" + m);
      break a
    }
    if (d && null !== e.Ta && 0 === e.Ta.mb(3) && (f = e.Ta.ja(0), d = e.Ta.ja(1), e = e.Ta.ja(2), m = wd().pl, (null === m ? null === f : m.g(f)) ? (f = wd().vl, d = null === f ? null === d : f.g(d)) : d = !1, d)) {
      a.Pf.pg("" + e);
      break a
    }
    a.Pf.pg("" + b)
  }
}
```

# Note
If I manually edit one of duplicated label `b:` into `b1:` and `break b` to `break b1`, 
`fullOptJS`-generated code runs perfectlly.

**Comment by sjrd** [comment]
It looks like it's a GCC bug. I'm afraid this probably cannot be fixed other than by upgrading the GCC we use in fullOpt. :(

**Comment by sjrd** [comment]
Interestingly, Firefox is not bothered by this double declaration. The app appears to work fine in Firefox with fullOpt. In fact, the spec seems to agree with Firefox. The spec function [`ContainsDuplicateLabels`](http://www.ecma-international.org/ecma-262/#sec-labelled-statements-static-semantics-containsduplicatelabels), which is defined recursively, only returns `true` (so failure) if LabelledStatements with the same label are *nested one within the other*. The spec says it is OK to define twice the same label as long as they are siblings, not ancestors.

So I guess this is a V8 bug, not a Scala.js nor GCC bug.

In fact the latest version of GCC (as of this writing) still actively creates duplicate labels like that. [See it online here](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Afunction%2520hello(name)%2520%257B%250A%2520%2520xyz%253A%2520%257B%250A%2520%2520%2520%2520if%2520(name.length%2520%253E%25203)%2520%257B%250A%2520%2520%2520%2520%2520%2520if%2520(name%2520%253D%253D%253D%2520'one')%250A%2520%2520%2520%2520%2520%2520%2520%2520break%2520xyz%253B%250A%2520%2520%2520%2520%2520%2520if%2520(name%2520%253D%253D%253D%2520'two')%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520alert('two')%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520break%2520xyz%253B%250A%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%2520%2520alert('four')%253B%250A%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520alert('three')%253B%250A%2520%2520%257D%250A%2520%2520alert('foo')%253B%250A%2520%2520zyx%253A%2520%257B%250A%2520%2520%2520%2520if%2520(name.length%2520%253E%25203)%2520%257B%250A%2520%2520%2520%2520%2520%2520if%2520(name%2520%253D%253D%253D%2520'one')%250A%2520%2520%2520%2520%2520%2520%2520%2520break%2520zyx%253B%250A%2520%2520%2520%2520%2520%2520if%2520(name%2520%253D%253D%253D%2520'two')%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520alert('two%25202')%253B%250A%2520%2520%2520%2520%2520%2520%2520%2520break%2520zyx%253B%250A%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%2520%2520alert('four%25202')%253B%250A%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520alert('three%25202')%253B%250A%2520%2520%257D%250A%257D%250Ahello(window.document.title)%253B%2520%252F%252F%2520do%2520not%2520constant-fold%250A%250A)

**Comment by exoego** [comment]
@sjrd 
Thanks for an examination.
I opend a bug report on Chromium.
https://bugs.chromium.org/p/chromium/issues/detail?id=917215
