### ISSUE TITLE
someRx.map(o.get().func(_)) != someRx.map(o.get().func)

### ISSUE THREAD

**Issue by scalway** [scala-js/scala-js#3512]
compiling two such lines gives different results:
```scala
state.position.map(lastSong.get().getSlide(_)) //#1 OK
state.position.map(lastSong.get().getSlide) //#2 WRONG
```

i've made diff on result files and this are changes:
```scala
//#1  OK
var f$1 = new $c_sjsr_AnonFunction1().init___sjs_js_Function1((function(arg$outer$1) {
    return (function(x$3$2) {
      var x$3 = $uD(x$3$2);
      var this$13 = arg$outer$1.lastSong$2;
      return $as_Lmodel_vio_VioSong(this$13.cache$3).getSlide__D__Lmodel_Slide(x$3)
    })
  })(this));

//#2 WRONG
  var this$13 = this.lastSong$2;
  var eta$0$1 = $as_Lmodel_vio_VioSong(this$13.cache$3);
  var f$1 = new $c_sjsr_AnonFunction1().init___sjs_js_Function1((function(eta$0$1$1) {
    return (function(pos$2) {
      var pos = $uD(pos$2);
      return eta$0$1$1.getSlide__D__Lmodel_Slide(pos)
    })
  })(eta$0$1));
```

context of this line looks like this:
```scala
class Ctrl() { 
    val player = new Player() {
        val lastSong = Var.stateful(VioSong.empty)
        val xxx = state.position.map(lastSong.get().getSlide(_)) // ----- this line :) ----- 
    }
} 
```

**Comment by sjrd** [comment]
Could you provide a stand-alone reproduction? At the moment you don't say what `lastSong.get()` nor how `getSlide` is defined, nor what type is `position` hence what its `map` method is. This makes it virtually impossible to understand the issue, I'm afraid.

Also, it appears that the code you're compiling is not Scala.js-specific. Could you try your reproduction on the JVM, and make sure that Scala.js behaves differently than Scala/JVM. If they behave the same, it is *always* intended behavior as far as Scala.js is concerned (it *could* be a bug in Scala/JVM).

**Comment by scalway** [comment]
Sorry... i see that this is proper behavior. I've tested it on JVM... i though that java in this place works differently. My fault.
