### ISSUE TITLE
Question: Generate JS code and use in TS project

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [scala-js/scala-js#3525]
I am building a large project for IoT, the backend has Node.js/TypeScript, Akka/Scala, Spark/Scala, Kafka/Scala, Front end Angular/TypeScript layers. 

Now, I need to build few domain classes and core SDKs that talks to REST APIs, certain definitions in both TypeScript and Scala, I see a pain with two different languages, I need to define same classes, relationships in TypeScript and also in Scala.

However, we cannot fully switch to Scala.js,  our client (customers) will be using our SDK, I like to continue using Angular/TypeScript, as we expect more developers to build application on Angular/TypeScript eco-system. 

I want to see if I can write code (domain classes, core SDK) in Scala.js, compiles to JS Code with TypeScript Declaration (.d files) then import the generated JS code into our TypeScript/Angular project. 

Any pointer or best practices would be really great. I really appreciate what Scala.js is doing, I am sure with Scala.js, we can reduce our burden with reusable code.

**Comment by sjrd** [comment]
Hello,

The GitHub Issues in this repo are for bug reports and feature requests only. Please ask questions [on StackOverflow](https://stackoverflow.com/questions/tagged/scala.js) or [on Gitter](https://gitter.im/scala-js/scala-js), where more than just the core developers can see and answer.

Thank you for your understanding.
