### ISSUE TITLE
Allow users to limit how many Scala.js linker tasks can run at once in sbt

### ISSUE THREAD

**Issue by DavidGregory084** [scala-js/scala-js#3539]
SBT will happily run lots of fastOptJS or fullOptJS tasks at once. These tasks use a lot of memory so it would be useful for users to be able to limit how many of these tasks can run concurrently to work around resource limits in continuous integration.

**Comment by sjrd** [comment]
Fixed in c9390707efbe19f9ad17faba21ca93695f26d56e.
