### ISSUE TITLE
Custom SBT configurations with fastOptJS

### ISSUE THREAD

**Issue by evbo** [scala-js/scala-js#3545]
Similar to [this issue](https://github.com/scala-js/scala-js/issues/2951), I need environment-specific settings for [a "build info" plugin](https://github.com/sbt/sbt-buildinfo) I'm using.

When I run `Dev:fastOptJS` on the following project, it loads both `inConfig(Dev)` and `inConfig(Prod)` settings, resulting in the latter being applied, but when I only wanted `Dev` settings applied.

According to [that previous issue](https://github.com/scala-js/scala-js/issues/2951), I need to include `scalaJSModuleInitializers in Dev := scalaJSModuleInitializers.value`, and `moduleName in (Dev, fastOptJS) := moduleName.value + "-dev"`, but still I get the same result.

minimal example:
```
lazy val Dev = config("Dev") describedAs("dev environment settings") extend(Compile)
  lazy val Prod = config("Prod") describedAs("prod environment settings") extend(Compile)


  lazy val client = (project in file("client"))
    .configs(Dev, Prod)
    .enablePlugins(BuildInfoPlugin)
    .enablePlugins(ScalaJSBundlerPlugin)
    .enablePlugins(ScalaJSPlugin)
    .settings(clientSettings)
    .settings(
      // This is an application with a main method
      scalaJSUseMainModuleInitializer := true,
      
      scalaJSModuleInitializers in Dev := scalaJSModuleInitializers.value,
      moduleName in (Dev, fastOptJS) := moduleName.value + "-dev",

      scalaJSModuleInitializers in Prod := scalaJSModuleInitializers.value,
      moduleName in (Prod, fastOptJS) := moduleName.value + "-prod",
    )
    .settings(
      inConfig(Dev)(
        Defaults.compileSettings ++
        ScalaJSPlugin.compileConfigSettings ++
        Seq(
          mainClass in Dev := Some("com.Main"),
          buildInfoKeys in Compile := Seq[BuildInfoKey]("contentHost" -> "localhost")
        )
      )
    )
    // because this is occurs 2nd, it is applied. If I delete these settings, the above is applied
    .settings(
      inConfig(Prod)(
        Defaults.compileSettings ++
        ScalaJSPlugin.compileConfigSettings ++
        Seq(
          mainClass in Prod := Some("com.Main"),
          buildInfoKeys in Compile := Seq[BuildInfoKey]("contentHost" -> "prodhost")
        )
      )
    )
```

Still even after I call `Dev:fastOptJS` it applies the `Prod` settings, but if I move `Dev` settings below `Prod` then the `Dev` settings are applied.

Also, after adding [the recommended settings](https://github.com/scala-js/scala-js/issues/2951#issuecomment-301450281), I'm now getting `LinkingException: There were linking errors`:

```
[error] Referring to non-existent method com.Main()scala.Unit
[error]   called from core module module initializers
[error] org.scalajs.core.tools.linker.LinkingException: There were linking errors

```

**Comment by sjrd** [comment]
Hello,

This looks like a question on using Scala.js, rather than a bug report. The GitHub Issues in this repo are for bug reports and feature requests only. Please ask questions [on StackOverflow](https://stackoverflow.com/questions/tagged/scala.js) or [on Gitter](https://gitter.im/scala-js/scala-js), where more than just the core developers can see and answer.

Thank you for your understanding.

**Comment by evbo** [comment]
not sure what happened here, but I think I hit some chrome shortcut keys in quick session. In any case, thanks - you're probably right i just need to get more familiar with sbt and scalajs. chances are this isn't an issue with this repo. I'll keep investigating this and post something on SO if there's a clear question I can formalize for it.
