### ISSUE TITLE
Dump a list of all linked classes

### ISSUE THREAD

**Issue by dispalt** [scala-js/scala-js#3556]
Hi, I am not having a specific problem but our codebase is getting rather big (10mb fastOptJS) and I'm starting to look at ways to trim things down.  One thing I was thinking about was basically making sure I am not including classes that I wouldn't expect to be including. 

In the same way webpack can dump a set of the dependencies it includes during the building process, it would be nice to be able to get some visibility around linked classes with scalajs.

Has anyone done any work on exposing either low level primitives or some ideas about how one would go about exposing this?

**Comment by sjrd** [comment]
What about
```bash
$ grep '^function \$c\_' project-fastopt.js | cut -c 13- | sed 's/() {$//'
```
?

**Comment by ramnivas** [comment]
@dispalt You may want to try source-code-mapper. See more at https://youtu.be/zU5_jXaM2Zs?t=2035

**Comment by japgolly** [comment]
That looks really interesting. Where can we find this source-code-mapper
tool? Google yields nothing.

**Comment by ramnivas** [comment]
Oops. I got the name wrong. Here it is: https://www.npmjs.com/package/source-map-explorer

**Comment by dispalt** [comment]
@ramnivas thanks a bunch looks like a decent solution!

**Comment by gzm0** [comment]
Seems like this is addressed.
