### ISSUE TITLE
Support common filename for source and minified JS dependencies

### ISSUE THREAD

**Issue by ddworak** [scala-js/scala-js#3569]
It is currently possible to avoid including different JS(impl) files in `index.html` with:
```scala
Compile / fastOptJS / artifactPath := (Compile / fastOptJS / target).value / "frontend.js",
Compile / fullOptJS / artifactPath := (Compile / fullOptJS / target).value / "frontend.js",
```
The same approach cannot be applied to JS dependencies, since `fullOptJS` does not only depend on `packageMinifiedJSDependencies` but also to `packageJSDependencies` due to `org.scalajs.sbtplugin.ScalaJSPluginInternal#scalaJSStageSettings`:
```scala
key := key.dependsOn(packageJSDependencies, packageScalaJSLauncherInternal).value,
```
The latter overwrites the result of the former when their `artifactPath` is the same.

I've made some attempts with `skip`, but I'm not sure it's possible to only skip packaging in `fullOptJS`, e.g.:
```
skip in (Compile / fullOptJS / packageJSDependencies) := true
```
skips in `fastOpt` as well.

I'd expect that since `fullOptJS` only outputs minified JS files, it should only package minified dependencies, but obviously there are a few possible solutions (one of which is me using a separate SBT module for full packaging and skipping packaging JS dependencies there, but I'd rather avoid that :wink:)

**Comment by sjrd** [comment]
I'm afraid the whole `jsDependencies`-related tasks are on life support. We do not change them anymore.

We encourage users to use [scalajs-bundler](https://github.com/scalacenter/scalajs-bundler) instead.
