### ISSUE TITLE
Tutorial Broken

### ISSUE THREAD

**Issue by kolotyluk** [scala-js/scala-js#3574]
So I downloaded the latest tutorial from https://github.com/scala-js/scalajs-tutorial, followed the directions at http://www.scala-js.org/doc/tutorial/basic/ At first I had the https://github.com/scala-js/scala-js/issues/2642 problem, and I tried to follow the saga. Now when I try to run the tutorial I get
```
Erics-MacBook-Pro:scalajs-tutorial-0.6.x eric$ sbt
[info] Loading settings for project scalajs-tutorial-0-6-x-build from plugins.sbt ...
[info] Loading project definition from /Volumes/Repos/leaderboard/scalajs-tutorial-0.6.x/project
[info] Loading settings for project scalajs-tutorial-0-6-x from ._build.sbt,build.sbt ...
[info] Set current project to Scala.js Tutorial (in build file:/Volumes/Repos/leaderboard/scalajs-tutorial-0.6.x/)
[info] sbt server started at local:///Users/eric/.sbt/1.0/server/ebc0f25c03394ee7f65a/sock
sbt:Scala.js Tutorial> run
[info] Running tutorial.webapp.TutorialApp
[success] Total time: 6 s, completed Feb. 22, 2019, 10:19:16 a.m.
sbt:Scala.js Tutorial> 
```
Which does not seem correct. I was expecting to see something like
```
$ sbt
> run
[info] Compiling 1 Scala source to (...)/scala-js-tutorial/target/scala-2.12/classes...
[info] Fast optimizing (...)/scalajs-tutorial/target/scala-2.12/scala-js-tutorial-fastopt.js
[info] Running tutorial.webapp.TutorialApp
**Hello world!**
[success] (...)
```

This tutorial would be better if it just worked by following the instructions. Apparently there is something missing from the instructions and/or the GitHub project.

One problems seems to be
```
Erics-MacBook-Pro:scalajs-tutorial-0.6.x eric$ npm install
npm WARN saveError ENOENT: no such file or directory, open '/Volumes/Repos/leaderboard/scalajs-tutorial-0.6.x/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Volumes/Repos/leaderboard/scalajs-tutorial-0.6.x/package.json'
npm WARN scalajs-tutorial-0.6.x No description
npm WARN scalajs-tutorial-0.6.x No repository field.
npm WARN scalajs-tutorial-0.6.x No README data
npm WARN scalajs-tutorial-0.6.x No license field.

audited 437 packages in 1.291s
found 0 vulnerabilities
```
But I am way out of my depth here. I understand this is still only beta, but some help would be greatly appreciated.

**Comment by sjrd** [comment]
> Which does not seem correct.

It is correct. When you clone that repo, you end up at the last commit which corresponds to the last Step in the tutorial. At the last step, everything happens in an HTML page, not in the console.

To get the hello world in the console, you should use `git checkout` to navigate to the appropriate commit for Step 1. As of this writing that's

    $ git checkout eb8ae0572ae9b33be79c39b59fc8e6f8c80e9e74

For future readers, use `git log` to see the list of commits for all steps.
