### ISSUE TITLE
Remove relativePath from VirtualIRFiles

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#3580]
Currently, `relativePath` is only used to identify files for the `scalajsp` task. As a result, we have [code like this][1] that basically fakes it.

I propose instead of using the `relativePath` to identify files for `scalajsp`, we use the `encodedName` in the `EntryPointInfo` (with conversion to/from decoded names if feasible).

This will simplify the virtual IR API for a little inconvenience of the debug-only scalajsp.

[1]: https://github.com/scala-js/scala-js/blob/b3f250494d1c49743002bbc766ec9a3de74c5131/test-suite-linker/src/main/scala/org/scalajs/bootstrap/TestSuiteLinker.scala#L57-L59

**Comment by gzm0** [comment]
@sjrd WDYT?

**Comment by gzm0** [comment]
An alternative would be to identify it by the full name.

**Comment by sjrd** [comment]
Don't we use `relativePath` to perform classpath shadowing? I.e., earlier entries on the classpath shadow later entries on the classpath, when they have the name relative path.

**Comment by gzm0** [comment]
Nope, we use encodedName: https://github.com/scala-js/scala-js/blob/481a53d8683224ac07d4f8e5c0399e469c69b87e/linker/shared/src/main/scala/org/scalajs/linker/frontend/BaseLinker.scala#L223-L225

**Comment by sjrd** [comment]
Ah OK. Yes, then we should definitely remove `relativePath` from virtual IR files.

For `scalajsp`, we can use `encodedName`, I suppose, yes. (while being a bit careful not to crash while constructing completions in case we cannot deserialize the `EntryPointsInfo` in a file) Using the full names would be annoying when using `scalajsp`, I think.
