### ISSUE TITLE
Array Specializitation

### ISSUE THREAD

**Issue by DirkToewe** [scala-js/scala-js#3587]
One of the many amazing things about ScalaJS is that it allows to write fast data analysis code for the JVM while still being able to run that code in the Browser, allowing for interactive, shareable visualization and exploration of data and models. The performance difference between Scala and ScalaJS however, is a minor hindrance to that.

Array Specialization seems to be one of the reasons that ScalaJS performance lags behind Scala. To verify that I've taken [this project](https://github.com/DirkToewe/gaupros) and replaced `Array[Double]` with a custom `Vec` class wherever possible. I then compared the test time using the following implementations of Vec:

|                                             | AMD A10-7850k | AMD FX-8150  |
|---------------------------------------------|---------------|--------------|
| `Vec( data: Array[Double] ) extends AnyVal` | 22662&nbsp;s  | 22549&nbsp;s |
| `Vec( data: Float64Array  ) extends AnyVal` | 14490&nbsp;s  | 13230&nbsp;s |

Using the `Float64Array` implementation, running the tests seems to take roughly 40&nbsp;% less time, which is quite significant. My hypothesis is that the type information given by `Float64Array` allows for better JIT optimization in contrast to `js.Array[Number]`. The memory overhead should be same in both cases as I believe most JSVMs optimize `js.Arrays` only containing `Numbers`, see `ElementsAccessor` in this [Blog Post](https://v8.dev/blog/fast-properties).

The intention of this issue is to put Array Specialization up for consideration when it comes to performance optimization.

Array Specialization would not only affect `Array[Double]` but even more so `Array[Int]`, `Array[Char]`, `Array[Byte]`, ... where it would not only affect performance but also memory overhead. That means that Array Specialization would have performance benefits outside of numeric applications, e.g. in `Base64` encoding and other I/O and text processing operations.

**Comment by sjrd** [comment]
It's something I've been considering for a long time.

That said, our priority at the moment is not on performance-related tasks, so I can't say when I'll eventually put my mind to it.

**Comment by gzm0** [comment]
So just to check my understanding: This is about the backing implementation of `scala.Array`, right? So we can change it at any time in the linker in a fully binary compatible manner?

**Comment by sjrd** [comment]
Yes that's right.
