### ISSUE TITLE
Use java.nio.file.Path in JSEnv API

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#3589]

**Comment by gzm0** [comment]
Unfortunately I don't think we can do this. Mainly because the `Path` API is not "async enough".

**Comment by gzm0** [comment]
I am re-opening this with the narrower scope of the `JSEnv` API only. I would like to make a case to *not* have the `JSEnv` API cross compile to JS.

When we look at the usages of the `JSEnv` API, we have:
1. Running code from a build tool.
2. Testing via the `TestAdapter`.

Addressing use case 1: Any JS based build tool will almost certainly already have its own abstractions of how to run JS code (as it is likely to already build and run other JS code). Therefore, this abstraction should be used.

Addressing use case 2: There is no need for the `TestAdapter` in JS land, as the testing tool can (and should) be called directly. In case there is a JS build tool that wants to isolate testing in a different VM, context, etc. again this tool already has its own abstractions that should be used.

Therefore, I'd like to propose to commit to making the `JSEnv` API JVM only and hence being able to simplify it and taking full advantage of the JVMs abstractions.

In practice, this means allowing the use of `java.nio.Path` instead of our own `VirtualFile` abstraction and not altering the abstraction with respect to stdio/stderr forwarding (it currently uses blocking streams).

@sjrd WDYT?

**Comment by gzm0** [comment]
Note that further this would allow to remove the `io` artifact as it would be entirely linker only at this point.

**Comment by sjrd** [comment]
Yes, that sounds reasonable, indeed. Let's commit the JSEnv API to be JVM-only.
