### ISSUE TITLE
Event constructor mismatches MDN

### ISSUE THREAD

**Issue by evbo** [scala-js/scala-js#3592]
It does not appear possible to construct an Event object like documented in MDN:
https://developer.mozilla.org/en-US/docs/Web/API/Event/Event

Also, `initEvent` is currently deprecated, so the `Event` constructor allowing expected arguments would be especially good to have as documented on MDN:
https://developer.mozilla.org/en-US/docs/Web/API/Event/initEvent

**Comment by evbo** [comment]
I've seen [alternative methods](https://stackoverflow.com/questions/24619945/creating-custom-dom-events-with-scalajs) of instantiating an Event in scalajs, but none of them currently appear to work for dispatching the event:

```scala
val input= document.evaluate(/*xpath query*/).singleNodeValue.asInstanceOf[HTMLInputElement]

val event = js.Dynamic.newInstance(js.Dynamic.global.CustomEvent)("change").asInstanceOf[CustomEvent]

input.dispatchEvent(event)
```

The above doesn't trigger my `onChange` function for that input

**Comment by sjrd** [comment]
This is not the appropriate repo for DOM-related stuff. This repo is for the core compiler only. Did you mean https://github.com/scala-js/scala-js-dom?
