### ISSUE TITLE
Incrementally compiling after certain code changes produces LinkingException

### ISSUE THREAD

**Issue by ramnivas** [scala-js/scala-js#3596]
As reported on the gitter channel, I and many others are seeing `LinkingException`s being thrown. Now I have a reasonably easy reproducible case.

Steps:
1. Clone https://github.com/payalabs/scalajs-tutorial/tree/linking-error
2. From sbt, ~fastOptJS
3. Rename `count` in the `Data` class to `countx`. You will see a compilation error (as expected).
4. Rename `countx` back to `count`.

You will see a `LinkingException`.

This exception won't go until you do one of the following:
1. `clean` followed by `fastOptJS`
2. Change (adding a line is fine) **both** `Data.scala` and `TutorialApp.scala`

One caveat: In our app, when we get an error, `clean` has rarely helped. So there may be another condition under which such an exception is produced, but for now, I don't have a reproducible case for that.

**Comment by cquiroz** [comment]
I see this every now and then but haven't been able to reproduce tit, I'm glad you are able to

**Comment by sjrd** [comment]
Thanks for the report. I'll have a look at it ... when I find time.

**Comment by gzm0** [comment]
I will tentatively classify this as bug and 0.6.28 so we do not forget.

**Comment by ramnivas** [comment]
@gzm0 Thanks for scheduling it for 0.6.28. Lately it has been very frequent issue for us (today we had to do full clean 20 times and it is just 3 PM :-( ).

**Comment by nafg** [comment]
While a proper solution to this would be really nice, it would help a LOT if instead of outputting screenfulls of information I don't need, it would just say "X refers to non-existent Y." Log everything else at debug level or something. If I would see that right away it would take five seconds to do the faux-edit-to-trigger-recompilation dance. The hard part almost is just finding which files to re-jigger in the first place.

**Comment by ramnivas** [comment]
An additional issue triggered by this: Every time we clean classes to fix a linking error, Metals gets into a state where everything is in error and doesn't recover after recompilation.

**Comment by dispalt** [comment]
> it would help a LOT if instead of outputting screenfulls of information I don't need

I agree, my current solution is to wade through the text to find the classes, then change the file by adding a comment or something, usually I can get it to work, or I delete my classes directory.

**Comment by sjrd** [comment]
For what it's worth, I can indeed reproduce this with sbt 1.2.8, as in the reproducing project; but it works fine in sbt 0.13.18. sbt 1.0.4, which is in our CI, exhibits a totally different problem which is clearly an sbt bug

I tend to believe that sbt broke something at some point, but it could also be our `incOptions` that are broken for sbt 1.x.

It's worth noting that with sent 1.2.8, after the second fastOptJS (the one with the compiler error) we can see with `find target/scala-2.12/classes` that sbt deleted `TutorialApp$.sjsir`, although `TutorialApp$.class` is still there. The third compilation does not restore the file either, which causes the linking error.

**Comment by sjrd** [comment]
Fixed in 78682118e626ec729836ecffa19f55f6e07ed369.

**Comment by ramnivas** [comment]
Thanks a lot!

**Comment by cquiroz** [comment]
👏 Great
