### ISSUE TITLE
Unable to import function

### ISSUE THREAD

**Issue by evbo** [scala-js/scala-js#3603]
I've tried following the docs suggestion to use `JSImport.Namespace`  but it doesn't seem possible to correctly import [this function](https://github.com/vitalyq/react-trigger-change/blob/master/lib/change.js#L9): `reactTriggerChange`

According to the docs, this should import the module itself
```scala
@js.native
@JSImport("react-trigger-change", JSImport.Namespace)
object ReactTriggerChange extends js.Object {
  def reactTriggerChange(node: js.Object): Unit = js.native
}
```

But actually my object gets compiled as the function, so in order to _trick_ scalajs into allowing me to call the object with the argument, I pretend it's a class:

```scala
@js.native
@JSImport("react-trigger-change", JSImport.Default)
class ReactTriggerChange(val node: js.Object) extends js.Object

object ReactTestEvent {
  def trigger(node: js.Object) = {
    new ReactTriggerChange(node)
  }
}
```

So is this a bug or an expected limitation? I noiced [this issue](https://github.com/scala-js/scala-js/issues/3500) indicates functions don't have a lot of support yet, but it does indicate it should still be possible using the `JSImport.Namespace` work around.

**Comment by sjrd** [comment]
This is a known limitation, inherited from the fact that ECMAScript modules themselves do not have a notion for `module.exports =` with something that is not an object.

There is a better workaround, though:
```scala
object ReactTestEvent {
  @js.native
  @JSImport("react-trigger-change", JSImport.Default)
  private object ReactTriggerChange extends js.Any

  val reactTriggerChange = ReactTriggerChange.asInstanceOf[js.Function1[js.Object, Unit]]
}
```
Also, please note that the GitHub Issues in this repo are for bug reports and feature requests only. Please ask questions [on StackOverflow](https://stackoverflow.com/questions/tagged/scala.js) or [on Gitter](https://gitter.im/scala-js/scala-js), where more than just the core developers can see and answer.

Thank you for your understanding.

**Comment by evbo** [comment]
Thanks, to me this limitation wasn't clear, which is why I opened an issue. Perhaps it's somewhere in the documentation but this is the only line I found describing how `JSImport.Namespace` should be used for functions:

>The latter is particularly useful if you want to import members of the modules that are neither classes nor objects (for example, functions)

That and [this issue](https://github.com/scala-js/scala-js/issues/3500) both indicate it's possible to import functions with no caveats, so a quick one-liner explaining the requirement you mentioned above would be helpful.
