### ISSUE TITLE
Scaladoc with Scala.js 0.6.x and Scala 2.13.0-RC1 emits a warning

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#3612]
which means it fails when a build has `-Xfatal-warnings`. A workaround is to add
```scala
scalacOptions in (Compile, doc) -= "-Xfatal-warnings"
```

The warning is:
```
[warn] dropping dependency on node with no phase object: mixin
```
The problem does not appear in Scala.js 1.x.

**Comment by gzm0** [comment]
Fixed in 2027c36fdaad191a1fda94f296c6991b8a721af5
