### ISSUE TITLE
System.nanotime implementation does not use performance.now in nodejs

### ISSUE THREAD

**Issue by fdietze** [scala-js/scala-js#3623]
The System.nanotime implementation does not use `performance.now()` in nodejs.

When I use `System.nanotime` in a test, I get numbers like `1555594268163000064`, which clearly shows the multiplication with `1000000`.

The code is already checking and using `performance.now`, but this only works in the browser:
https://github.com/scala-js/scala-js/blob/master/javalanglib/src/main/scala/java/lang/System.scala#L58

It does not work in node. Nodejs added the [Performance Timing API](https://nodejs.org/api/perf_hooks.html#perf_hooks_performance_timing_api) in 8.5.0 and can be used like this:

```javascript
require('perf_hooks').performance.now()
```

**Comment by sjrd** [comment]
The Performance Timing API of Node.js is still Experimental, as highlighted at the top of the page you link. We cannot use that yet.

**Comment by sjrd** [comment]
I'm going to close this for now, since there's nothing we can do in this repo as long as the API is experimental upstream.
