### ISSUE TITLE
Ablitity to pass js.| Union type 'A | B' to js.Any

### ISSUE THREAD

**Issue by exoego** [scala-js/scala-js#3632]
This is a feature request.

I would like to pass a value of type `A | B` to function argument of type `js.Any`, when both `A` and `B` are subtype of `js.Any`.

However, current `js.|` does not allow this. Type mismatch occurs like the below.
```
[error]  found   : String | Int
[error]  required: scala.scalajs.js.Any
[error]     js.JSON.stringify(a)
```

I wonder it is possible to convert `A | B` to `js.Any` implicitly only when both `A` and `B` is subtype of `js.Any`.

**Comment by sjrd** [comment]
This has been requested before, and unfortunately cannot be soundly implemented. See https://github.com/scala-js/scala-js/pull/2070 for a previous attempt and a counter-example.
