### ISSUE TITLE
Report causes of failed testinterface RPC call better

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#3644]
Otherwise this can lead to very hard to debug problems.

**Comment by gzm0** [comment]
E.g. #3174

**Comment by gzm0** [comment]
Digging more into #3174 it seems that the confusion mostly stems from not having the original message and it *looking* like the RPC subsystem failed (even though the cause is pretty clear).

Further note that in default setup, the stderr of all `JSEnv`s is already inherited to stderr, so there is probably little value to doing this.

I'll investigate if there are places where we can forward the causing message better.

**Comment by sjrd** [comment]
Fixed in e48a146ae8bd49fd79074d7d8254405b3de1f4d8.
