### ISSUE TITLE
Determine compatibility guarantees and naming of irio package

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#3656]
Ideally, we would have a way to make changes to some of the lower level APIs (notably `WritableVirtualBinaryFile`).

However, some other parts definitely need to be super-stable, as they are required to link (and mentioned in the other parts of the super stable API).

**Comment by sjrd** [comment]
Even `WritableVirtualBinaryFile` is referenced by the super-stable API in `LinkerOutput`. As far as I can tell, everything in `irio` needs to be super-stable. Isn't that the case?

**Comment by sjrd** [comment]
Ah, I see. Yes, I guess that makes sense, indeed.
