### ISSUE TITLE
System.getProperty in test code cannot get the property set in production code

### ISSUE THREAD

**Issue by exoego** [scala-js/scala-js#3657]
I want to define my own system propety using `java.lang.System.[gs]etProperty` but it seems that the property defined in production code cannot retrieved from test code.

```scala
// production code
object File {
  System.setProperty("my.var", "foo")
}
class File {
}

// test code
assert(System.getProperty("my.var") != null) // fail
```

Property can be defined and retrieved in test code.

```scala
// test code
System.setProperty("my.var", "foo")
assert(System.getProperty("my.var") != null) // pass
```

* Scala.js 0.6.27
* Scalatest 3.0.7
* Scala 2.12.8
* Java 11.0.2

**Comment by sjrd** [comment]
The constructor body of `object`s is lazy. It does not execute until you load the `File` object instance, for example by calling one of its methods, or just mentioning it in code that executes. Here it seems your test code doesn't access the `File` object, and hence its constructor is not executed.

**Comment by exoego** [comment]
My real problem is  that some system properties like `java.io.tmpdir` are missing in Scala.js's `System`.
I am buliding a library that required `java.io.tmpdir` so I want to initialize it like `System.setProperty("java.io.tmpdir", os.tmpdir())` on Node.js when library is loaded.
`System` object is already defined in Scala.js's javalib, so I could not initialize `properties` in my own `System` object...

Any ideas?

**Comment by sjrd** [comment]
That's the same as any other initialization code that needs to be executed before other code can run. There is absolutely nothing specific to system properties. It doesn't even have anything to do with Scala.js. I don't have any specific suggestion, but I think this discussion needs to be moved outside of this repository.
