### ISSUE TITLE
Make ECMAScript2015 the default in Scala.js 1.x

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#3659]
There are real advantages to using ECMAScript 2015 now:

* `Throwable`s, by virtue of properly extending JavaScript's `Error`, have an `[[ErrorData]]` internal slot, and therefore receive proper debugging info in JS engines, allowing better display of stack traces and error messages in interactive debuggers.
* Static fields and methods in JS classes are properly inherited. See https://github.com/scala-js/scala-js/issues/2771.
* Overall, Scala.js is *specified* in terms of ES2015. The ES 5.1 output that we emit is already, conceptually, a desugaring of the ES2015 *meaning* of Scala.js programs.

For those reasons, I think we should make it the default in Scala.js 1.x.

Reverting any particular build to emitting ES 5.1 would be as easy as using the following sbt setting:
```scala
scalaJSLinkerConfig in ThisBuild ~= { _.withESFeatures(_.withUseECMAScript2015(false)) }
```

Any objection?

**Comment by gzm0** [comment]
Will this work in my browser? :P

**Comment by sjrd** [comment]
Probably, unless you're using something very old: https://caniuse.com/#feat=es6 :P

**Comment by gzm0** [comment]
Good. Then I'm happy :P
