### ISSUE TITLE
Split org.scalajs.testing.* from test-interface in a separate artifact from sbt.testing.*

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#3668]
The testing subsystem contains the following components:

* `org.scalajs.testing.adapter`: a JVM component implementing `sbt.testing` on the JVM side, by connecting through a protocol to the JS side
* `org.scalajs.testing.interface`: a JS component *using* `sbt.testing` on the JS side, connecting through the same protocol to the JVM side
* `org.scalajs.testing.common`: cross-compiling code that is shared by the two above components
* `sbt.testing`: a JS clone of the standard JVM sbt-testing-interface

Currently, `org.scalajs.testing.interface` and `sbt.testing` live in the same artifact, `scalajs-test-interface`. This artifact plays two very different roles at once:
* the `sbt.testing` part is implemented by concrete testing frameworks, which must therefore depend on it
* the `testing.interface` part needs to be on the classpath when linking tests, because the test adapter relies on its implementation of the protocol.

The protocol of `testing.interface` and `testing.adapter` must be in sync, at all times. In practice, a version *x* of the sbt plugin forces the test adapter version to be *== x*, and the interface version to be *>= x*. That means that we have to deal with version mismatches when defining and implementing the protocol: the interface can be newer than the test adapter. This is a significant problem when we try to fix issues with the protocol itself, such as recently found in #3667.

We can however get rid of this problem for good by splitting `testing.interface` and `sbt.testing` in two different artifacts:
* `sbt.testing` is an independent artifact, depending only on scalajs-library. Concrete testing frameworks depend on that artifact to implement `sbt.testing.Framework`.
* `org.scalajs.testing.interface` (and `testcommon`) are another artifact, that depends on the one for `sbt.testing`

The latter artifact (let's call it `scalajs-testing-interface-impl`) is not on the dependency graph of concrete testing frameworks. Therefore the sbt plugin can always force it to be of version *== x*. With this system, we guarantee that the JVM and JS side of the implementation of the protocol are always exactly equal, and that means we can evolve the protocol itself completely freely, with breaking changes in any directions.

**Comment by sjrd** [comment]
Maybe we can even do this already in 0.6.x. We'll just have to put `testinterface.TestUtils` and `testinterface.ScalaJSClassLoader` in the same artifact as `sbt.testing` (the "public" one).

**Comment by gzm0** [comment]
Definitely something we should do. I think we should even then add a handshake to `RPCCore` that makes sure the versions actually match.

**Comment by gzm0** [comment]
TBH not sure it is worth doing this in 0.6.x though.

**Comment by sjrd** [comment]
> TBH not sure it is worth doing this in 0.6.x though.

Depends whether we want to fix #3667 in 0.6.x or not, I guess.

**Comment by sjrd** [comment]
Fixed in 2240515b60390591fba83be88fab67a31b25adf7.
