### ISSUE TITLE
GCC + ES6 produces invalid identifier (in very big files)

### ISSUE THREAD

**Issue by dvkndn** [scala-js/scala-js#3669]
After turned the ECMA2015 option on, one of our full-opted JS cannot be executed:

![Screenshot from 2019-05-25 14-28-41](https://user-images.githubusercontent.com/5953369/58366234-6b14ea00-7ef9-11e9-8499-837ac473519b.png)

I think it's because the result JS tried to define a constant named `top` at global scope, which is illegal since `window.top` is defined by browsers already:

![Screenshot from 2019-05-25 14-20-21](https://user-images.githubusercontent.com/5953369/58366168-8f23fb80-7ef8-11e9-8103-7f1d32825d81.png)

I guess this is because GCC renamed variables and eventually reached this `top` name when we produced enough (global) variables (there are names like `toq` and `too` nearby).

In fact, the crashed app has about 40k globally-defined identifiers (`Object.keys(window).length`). Our other apps have 20k and 4k identifiers and they are fine with ECMA2015.

So.. what should we do? Should we file an issue to GCC to avoid this name?

**Comment by sjrd** [comment]
Er, what kind of module are you using? `NoModule` aka Script (the default), or `CommonJSModule` (default with scalajs-bundler)?

If the former, then all of the output of GCC should be enclosed in a giant IIFE (Immediately Invoked Function Expression), which means that "top-level" `const`s like `top` are actually local to the function and should not be redefined.

If the latter (CommonJS module), then how come you're trying to load the file globally in a browser? It should be loaded as a CommonJS module, which protects its scope from the global scope (hence "top-level" `const`s are *also* local). If you're trying to load a CommonJS module as a script in the browser, you're breaking the spec of CommonJS, and there's nothing Scala.js nor GCC can do for you.

**Comment by dvkndn** [comment]
@sjrd I think the latter. This is my settings:

```scala
  val scalac = List(
    scalacOptions += "-language:existentials",
    scalacOptions += "-P:scalajs:sjsDefinedByDefault"
  )

  val scalacMacro = List(
    scalacOptions += "-Yrangepos"
  )

  val scalajs = List(
    emitSourceMaps := false,
    scalaJSLinkerConfig ~= { _.withESFeatures(_.withUseECMAScript2015(true)) },
    scalaJSUseMainModuleInitializer := true,
  )

  val scalajsBundler = List(
    useYarn := true,
    webpack / version := Dependencies.Versions.webpack,
    webpackEmitSourceMaps := false,
    webpackBundlingMode := BundlingMode.LibraryOnly(),
    webpackConfigFile in fastOptJS := Some(baseDirectory.value / "webpack.dev.js"),
    webpackConfigFile in fullOptJS := Some(baseDirectory.value / "webpack.prod.js"),
    webpackCliVersion := Dependencies.Versions.webpackCli,
    startWebpackDevServer / version := Dependencies.Versions.webpackDevServer
  )
```

and because I use `LibraryOnly()` mode, I included the generate js files as below:

```html
<body>
    <div id="root">...</div>
    <script type="text/javascript" src="./doc-library.js"></script>
    <script type="text/javascript" src="./doc-loader.js"></script>
    <script type="text/javascript" src="./doc.js"></script> <!-- full opt -->
</body>
```

So.. is having them in `script` tag like this wrong?

**Comment by sjrd** [comment]
From https://scalacenter.github.io/scalajs-bundler/reference.html#bundling-mode-library-only, in a big orange warning box:

> The inclusion of a CommonJS module in the web browser is not guaranteed to work. In particular, in `fullOptJS` mode the name mangler might produce names that could clash with other existing global names. For this reason, we don’t recommend using the `LibraryOnly` bundling mode in `fullOptJS`, or in production.

So basically, don't use `LibraryOnly` in `fullOptJS` mode. It can and will cause exactly the kind of issues you're running into.

Since there's nothing Scala.js can do, I'm going to close this issue.

**Comment by dvkndn** [comment]
Thanks :+1:

**Comment by glmars** [comment]
Hi @dvkndn. It's known problem with `scalajs-bundler` and `LibraryOnly` mode https://github.com/scalacenter/scalajs-bundler/issues/282
Unfortunately, there aren't any workarounds :(
