### ISSUE TITLE
RPCException when running tests with Graal

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#3673]
When Scala.js runs tests, it blows up with an RPCException if no tests are found (or at least that's what I'm assuming is the reason).

### Reproduction
1. Check out https://github.com/japgolly/scala-graal
2. `sbt extBoopickleJS/test`.

### Full error message

```
[error] org.scalajs.testcommon.RPCCore$RPCException: scala.scalajs.js.JavaScriptException: TypeError: Access to host class org.scalacheck.ScalaCheckFramework is not allowed or does not exist.
[error] 	at org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$4(RPCCore.scala:79)
[error] 	at scala.Option.foreach(Option.scala:257)
[error] 	at org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$1(RPCCore.scala:77)
[error] 	at org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$1$adapted(RPCCore.scala:57)
[error] 	at org.scalajs.testcommon.Serializer$.withInputStream(Serializer.scala:60)
[error] 	at org.scalajs.testcommon.RPCCore.handleMessage(RPCCore.scala:57)
[error] 	at org.scalajs.testadapter.ComJSEnvRPC$$anon$1.run(ComJSEnvRPC.scala:34)
[error] Caused by: scala.scalajs.js.JavaScriptException: TypeError: Access to host class org.scalacheck.ScalaCheckFramework is not allowed or does not exist.
[error] 	at <jscode>.@TypeError: Access to host class org.scalacheck.ScalaCheckFramework is not allowed or does not exist.(Unknown Source)
[error] 	at <jscode>.file:///home/golly/projects/public/scala-graal/ext-boopickle/js/target/scala-2.12/ext-boopickle-test-fastopt.js:5804:111@$c_Lorg_scalajs_testinterface_internal_FrameworkLoader$.loadFramework__T__Lsbt_testing_Framework(Unknown Source)
[error] 	at <jscode>.(file:///home/golly/projects/public/scala-graal/ext-boopickle/js/target/scala-2.12/ext-boopickle-test-fastopt.js:5528)
[error] 	at <jscode>.(file:///home/golly/projects/public/scala-graal/ext-boopickle/js/target/scala-2.12/ext-boopickle-test-fastopt.js:5550)
[error] 	at <jscode>.file:///home/golly/projects/public/scala-graal/ext-boopickle/js/target/scala-2.12/ext-boopickle-test-fastopt.js:20828:11@$c_sjsr_AnonFunction1.apply__O__O(Unknown Source)
[error] 	at <jscode>.(file:///home/golly/projects/public/scala-graal/ext-boopickle/js/target/scala-2.12/ext-boopickle-test-fastopt.js:3916)
[error] 	at <jscode>.file:///home/golly/projects/public/scala-graal/ext-boopickle/js/target/scala-2.12/ext-boopickle-test-fastopt.js:20828:11@$c_sjsr_AnonFunction1.apply__O__O(Unknown Source)
[error] 	at <jscode>.(file:///home/golly/projects/public/scala-graal/ext-boopickle/js/target/scala-2.12/ext-boopickle-test-fastopt.js:8667)
[error] 	at <jscode>.file:///home/golly/projects/public/scala-graal/ext-boopickle/js/target/scala-2.12/ext-boopickle-test-fastopt.js:20828:11@$c_sjsr_AnonFunction1.apply__O__O(Unknown Source)
[error] 	at <jscode>.(file:///home/golly/projects/public/scala-graal/ext-boopickle/js/target/scala-2.12/ext-boopickle-test-fastopt.js:20183)
[error] 	at <jscode>.file:///home/golly/projects/public/scala-graal/ext-boopickle/js/target/scala-2.12/ext-boopickle-test-fastopt.js:20828:11@$c_sjsr_AnonFunction1.apply__O__O(Unknown Source)
[error] (extBoopickleJS / Test / loadedTestFrameworks) org.scalajs.testcommon.RPCCore$RPCException: scala.scalajs.js.JavaScriptException: TypeError: Access to host class org.scalacheck.ScalaCheckFramework is not allowed or does not exist.
```

**Comment by sjrd** [comment]
> it blows up with an RPCException if no tests are found (or at least that's what I'm assuming is the reason).

It is very unlikely that that is the reason, because we explicitly have tests in our CI for this scenario. The error message you get is

    TypeError: Access to host class org.scalacheck.ScalaCheckFramework is not allowed or does not exist.

Is it something GraalJS-specific? There's no such thing as a "host class" in Scala.js or Node.js.

**Comment by japgolly** [comment]
I was about to say "I'm seeing the same exception in another code base too that's unrelated to Graal" but I just realised I think I may have been using Graal as my default `java` at that time. Silly me, you're probably right. A quick google of the error msg without the class name only returns Graal results.

I'll do some more testing in a few days, I'm exhausted tonight. I guess Scala.JS or probably more likely SBT is detecting test frameworks in a way that's incompatible with Graal.

**Comment by sjrd** [comment]
Brainstormed offline about this issue with @gzm0 today. Just dumping raw ideas so that I don't forget them.

This is probably happening during test framework detection. sbt has a list of frameworks to look for by default, even when they're not there. Scala.js 0.6.x first tries to load stuff with the `Reflect` API (like 1.x), but it will fallback on the old JS export-based system if `Reflect` does not find anything (unlike 1.x). The fallback tries to read a top-level `org.scalacheck.ScalaCheckFramework` (for example), which is what we need to do for the JS export-based system. That probably runs into a GraalJS-specific feature to load actual JVM classes from the host system (hence the "Access to host class" error). Instead of silently returning `undefined` like any normal JS engine would do, apparently GraalJS throws that error.

If we're right, solutions include:

* Not using GraalJS (duh...)
* Using Scala.js 1.x (which does not have the fallback on JS export-based test loading
* Include some option in Scala.js that would disable the fallbacks (would prevent from using testing frameworks built using the JS export system)
* Somehow detect GraalJS and automatically disable the fallbacks in that case (same caveat; introduces a "knowledge dependency" from Scala.js 0.6.x to GraalJS, not nice)

**Comment by sjrd** [comment]
As a workaround, you could also actually depend on ScalaCheck in the test configuration of the JS project, even if you don't actually use it. Just having it on the classpath will make the reflection-based lookup succeed, and so Scala.js won't try the JS export-based mechanism.

@japgolly could you try that?

**Comment by japgolly** [comment]
Hi, I gave it a try and it doesn't make a difference. Trying to narrow down the cause has gotten really bizarre. Have a look at [this branch](https://github.com/japgolly/scala-graal/tree/sjs-3673).

* I've removed the Graal SDK as a dependency
* I've added scalacheck to the extBoopickleJS test classpath
* I've stopped testing this with Graal and switched back to OpenJDK

And I'm still getting this error. Check this out!

```
> java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)

> sbt clean extBoopickleJS/test
[info] Loading settings for project global-plugins from plugins.sbt,metals.sbt ...
[info] Loading global plugins from /home/golly/.sbt/1.0/plugins
[info] Loading settings for project scala-graal-build-build from plugins.sbt ...
[info] Loading project definition from /home/golly/projects/public/scala-graal/project/project
[success] Generated .bloop/scala-graal-build-build.json
[success] Total time: 3 s, completed 01/06/2019 6:24:28 PM
[info] Loading settings for project scala-graal-build from plugins.sbt ...
[info] Loading project definition from /home/golly/projects/public/scala-graal/project
[success] Generated .bloop/scala-graal-build.json
[success] Total time: 3 s, completed 01/06/2019 6:24:31 PM
[info] Loading settings for project root from version.sbt,build.sbt ...
[info] Set current project to scala-graal (in build file:/home/golly/projects/public/scala-graal/)
[success] Total time: 0 s, completed 01/06/2019 6:24:33 PM
[info] Compiling 1 Scala source to /home/golly/projects/public/scala-graal/ext-boopickle/js/target/scala-2.12/classes ...
[info] Done compiling.
[info] Compiling 2 Scala sources to /home/golly/projects/public/scala-graal/ext-boopickle/js/target/scala-2.12/test-classes ...
[info] Done compiling.
[info] Fast optimizing /home/golly/projects/public/scala-graal/ext-boopickle/js/target/scala-2.12/ext-boopickle-test-fastopt.js
[error] org.scalajs.testcommon.RPCCore$RPCException: scala.scalajs.js.JavaScriptException: TypeError: Access to host class org.scalacheck.ScalaCheckFramework is not allowed or does not exist.
[error] 	at org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$4(RPCCore.scala:79)
[error] 	at scala.Option.foreach(Option.scala:257)
[error] 	at org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$1(RPCCore.scala:77)
[error] 	at org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$1$adapted(RPCCore.scala:57)
[error] 	at org.scalajs.testcommon.Serializer$.withInputStream(Serializer.scala:60)
[error] 	at org.scalajs.testcommon.RPCCore.handleMessage(RPCCore.scala:57)
[error] 	at org.scalajs.testadapter.ComJSEnvRPC$$anon$1.run(ComJSEnvRPC.scala:34)
[error] Caused by: scala.scalajs.js.JavaScriptException: TypeError: Access to host class org.scalacheck.ScalaCheckFramework is not allowed or does not exist.
[error] 	at <jscode>.@TypeError: Access to host class org.scalacheck.ScalaCheckFramework is not allowed or does not exist.(Unknown Source)
[error] 	at <jscode>.file:///home/golly/projects/public/scala-graal/ext-boopickle/js/target/scala-2.12/ext-boopickle-test-fastopt.js:5804:111@$c_Lorg_scalajs_testinterface_internal_FrameworkLoader$.loadFramework__T__Lsbt_testing_Framework(Unknown Source)
[error] 	at <jscode>.(file:///home/golly/projects/public/scala-graal/ext-boopickle/js/target/scala-2.12/ext-boopickle-test-fastopt.js:5528)
[error] 	at <jscode>.(file:///home/golly/projects/public/scala-graal/ext-boopickle/js/target/scala-2.12/ext-boopickle-test-fastopt.js:5550)
[error] 	at <jscode>.file:///home/golly/projects/public/scala-graal/ext-boopickle/js/target/scala-2.12/ext-boopickle-test-fastopt.js:20828:11@$c_sjsr_AnonFunction1.apply__O__O(Unknown Source)
[error] 	at <jscode>.(file:///home/golly/projects/public/scala-graal/ext-boopickle/js/target/scala-2.12/ext-boopickle-test-fastopt.js:3916)
[error] 	at <jscode>.file:///home/golly/projects/public/scala-graal/ext-boopickle/js/target/scala-2.12/ext-boopickle-test-fastopt.js:20828:11@$c_sjsr_AnonFunction1.apply__O__O(Unknown Source)
[error] 	at <jscode>.(file:///home/golly/projects/public/scala-graal/ext-boopickle/js/target/scala-2.12/ext-boopickle-test-fastopt.js:8667)
[error] 	at <jscode>.file:///home/golly/projects/public/scala-graal/ext-boopickle/js/target/scala-2.12/ext-boopickle-test-fastopt.js:20828:11@$c_sjsr_AnonFunction1.apply__O__O(Unknown Source)
[error] 	at <jscode>.(file:///home/golly/projects/public/scala-graal/ext-boopickle/js/target/scala-2.12/ext-boopickle-test-fastopt.js:20183)
[error] 	at <jscode>.file:///home/golly/projects/public/scala-graal/ext-boopickle/js/target/scala-2.12/ext-boopickle-test-fastopt.js:20828:11@$c_sjsr_AnonFunction1.apply__O__O(Unknown Source)
[error] (extBoopickleJS / Test / loadedTestFrameworks) org.scalajs.testcommon.RPCCore$RPCException: scala.scalajs.js.JavaScriptException: TypeError: Access to host class org.scalacheck.ScalaCheckFramework is not allowed or does not exist.
[error] Total time: 20 s, completed 01/06/2019 6:24:53 PM
```

Looking at the referred line in the stack trace it's:
```js
$c_Lorg_scalajs_testinterface_internal_FrameworkLoader$.prototype.loadFramework__T__Lsbt_testing_Framework = (function(frameworkName) {
  var this$1 = $m_sjs_reflect_Reflect$().lookupInstantiatableClass__T__s_Option(frameworkName);
```

**Comment by sjrd** [comment]
Hum, I can't reproduce the crash. I did:
```bash
$ git clone git@github.com:japgolly/scala-graal.git
$ cd scala-graal/
$ git checkout sjs-3673
$ npm install jsdom
$ sbt clean extBoopickleJS/test
```
and it completed successfully. On both Windows and Linux.

---

I see that you added the JVM dependency on ScalaCheck at https://github.com/japgolly/scala-graal/blob/f9623ab1e05b8683c93705a72ae929072c71d1f3/project/Build.scala#L85 (with `%%`). My workaround above assumes that you're using the JS dependency instead, with `%%%`.

**Comment by japgolly** [comment]
Oh that was a silly copy-paste on my part. I've changed to `%%%` and that seems to workaround it. It then moves on to complaining about the specs2 test runner instead :)

```
[error] org.scalajs.testcommon.RPCCore$RPCException: scala.scalajs.js.JavaScriptException: TypeError: Access to host class org.specs2.runner.Specs2Framework is not allowed or does not exist.
```

---

Regarding that it worked for you, I tried doing a new checkout and starting with OpenJDK and sure enough the problem didn't manifest. I guess sbt's `clean` isn't to be trusted (sigh) - there must be some state that was being left behind.

So with a brand-new with the updated branch (i.e. the `%%%` fix & removal of *all* src files):
* `extBoopickleJS/test` - OpenJDK works, Graal gets past ScalaCheck and fails on Specs2
* `extBoopickleJVM/test` - both OpenJDK and Graal work

**Comment by japgolly** [comment]
Also I've just modified the title slightly. Graal (VM) and Graal JS are different in that Graal is Java 8 plus a new JVMCI and Polyglot SDK, Graal JS is a JS -> Polyglot IR compiler. So just to be clear it's Graal the VM that's in scope; what I'm not doing (in the scope of this issue) is executing SJS output via Graal JS. I'd bet money you already know that but I prefer to clarify just in case :)

**Comment by sjrd** [comment]
I just realized that there is cleaner workaround, that will avoid stumbling on Specs2 after ScalaCheck, and then another one, etc.: simply empty the list of test frameworks that sbt looks for, and *only* include the ones you actually use. This line: https://github.com/japgolly/scala-graal/blob/f9623ab1e05b8683c93705a72ae929072c71d1f3/project/Build.scala#L66
```scala
testFrameworks += new TestFramework("utest.runner.Framework")))
```
can be replaced by
```scala
testFrameworks := List(new TestFramework("utest.runner.Framework"))))
```
to do that.

**Comment by japgolly** [comment]
Ah I've done that before but didn't think about it here. Thanks.

So working around it is easy enough. We're expecting this won't be an issue with Scala.JS 1.x because it has a different framework loading mechanism, is that right?

**Comment by sjrd** [comment]
> We're expecting this won't be an issue with Scala.JS 1.x because it has a different framework loading mechanism, is that right?

Yes that's right.

**Comment by japgolly** [comment]
Ok cool. I'm happy to close this then. Thanks for your time as always.
