### ISSUE TITLE
testInterface linking error in 2.12 community build

### ISSUE THREAD

**Issue by SethTisue** [scala-js/scala-js#3680]
in recent Scala 2.12 community build runs such as [this one](https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/4564/), scala-js has consistently been failing with:

```
[scala-js] Running "test" in: testInterface
[scala-js] [info] Fast optimizing /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.16/project-builds/scala-js-88da8c6fe8815e1303df7c5b6f01d6cd0572be74/test-interface/target/scala-2.12/scalajs-test-interface-test-fastopt.js
[scala-js] [error] Referring to non-existent class org.scalajs.testing.bridge.Bridge$
[scala-js] [error]   called from core module module initializers
[scala-js] [error] Referring to non-existent class org.scalajs.testing.bridge.Bridge$
[scala-js] [error]   called from core module module initializers
[scala-js] [error] Cannot access module for non-module org.scalajs.testing.bridge.Bridge$
[scala-js] [error]   called from core module module initializers
[scala-js] org.scalajs.linker.LinkingException: There were linking errors
```

any clue what this is about?

**Comment by sjrd** [comment]
Yes, it's https://github.com/scala/community-builds/issues/465 / #2752 coming back to haunt us, but this time with the `testInterface` project rather than `library`.

I'll fix it.

But honestly we're working around the fact that dbuild insists on running `x/test` for every `x` that `y` transitively depends on, when all we're asking is that it run `y/test`...

**Comment by SethTisue** [comment]
It sounds like I could work around it with:

```
      // Seb says it isn't appropriate to run tests in this subproject;
      // see https://github.com/scala-js/scala-js/issues/3680
      "set executeTests in testInterface in Test := Tests.Output(TestResult.Passed, Map(), Iterable())"
```

I'll try it

**Comment by SethTisue** [comment]
oh no wait duh, it's a problem compiling, not running, that won't help

**Comment by SethTisue** [comment]
maybe I can just ` "set test in testInterface in Test := {}"`

**Comment by SethTisue** [comment]
yeah that does it, scala/community-builds@82e1d1232d459a86a25fa224e081360c4d2f849f

**Comment by sjrd** [comment]
> maybe I can just set test in testInterface in Test := {}

Yes, that would work, since the fix in Scala.js is basically to do just that. See
https://github.com/scala-js/scala-js/blob/118a97b29f8e81c8fd43e3b98ab1c73f6e29fa0f/project/Build.scala#L1026-L1028

**Comment by sjrd** [comment]
> 
> 
> yeah that does it, [scala/community-builds@82e1d12](https://github.com/scala/community-builds/commit/82e1d1232d459a86a25fa224e081360c4d2f849f)

Thanks :)

**Comment by SethTisue** [comment]
LOL, https://github.com/scala/community-builds/commit/e071600dca13c1ff6e256e8767ecfb02a8f0c78f https://github.com/scala/community-builds/commit/311fa06252531425d1460a77832f7f87c6c5e28e
