### ISSUE TITLE
Rename js.special.globalThis

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#3685]
A proposal for a global variable `globalThis` was done in ECMAScript, see https://github.com/tc39/proposal-global, and is [about to reach stage 4](https://github.com/tc39/ecma262/pull/702). The trouble is: it *almost* corresponds to what we made available as `js.special.globalThis`, but not quite.

So `js.special.globalThis` is now very misleading. We should rename it.

Perhaps `enclosingThis`?

**Comment by gzm0** [comment]
Can we just call it `this`?

**Comment by sjrd** [comment]
No, that would suggest that it's equivalent to writing the JavaScript `this` *at the call site*, but our thing is the `this` *at the top-level* of what we generate.

**Comment by gzm0** [comment]
Hmm... maybe `topLevelThis` is also a candidate :S I don't really like any of these :(

**Comment by sjrd** [comment]
Since this value is useless in ES modules (it's `undefined`) and CommonJS modules (it's `=== exports`), perhaps we could call it `scriptThis`?

**Comment by gzm0** [comment]
`freeThis` just came to my mind... Probably too PLy though... :S

**Comment by sjrd** [comment]
Instead of `topLevelThis` (which is not always accurate), perhaps `scriptLevelThis`?

**Comment by gzm0** [comment]
TBH I'm a bit reluctant to chose a name that is based on usage on not meaning/semantics. Usage can vary, semantics doesn't: Using this in an ES module and/or a CommonJS module is allowed, just maybe not very useful (but even then, what about: `isCommonjs = this == exports`?

Maybe `fileLevelThis` / `fileScopeThis`?

**Comment by sjrd** [comment]
I could live with `fileLevelThis`.

**Comment by gzm0** [comment]
Let's do this then.

**Comment by sjrd** [comment]
Fixed in https://github.com/scala-js/scala-js/commit/e6db0ff7b85ae9c06b7c42b10f2233f2d60965be.
