### ISSUE TITLE
Multi-threading support with web workers

### ISSUE THREAD

**Issue by pitust** [scala-js/scala-js#3696]
As far as I know, there is no multi-threading in scala.js. However, this could be implemented using `child_process` in Node.JS and `Worker` in browsers.
Here is an example of launching a thread in a browser:
```js
function runInWorker(js) {
    let x = btoa(js)
    return new Worker(`data:text/javascript;base64, ${x}`);
}
runInWorker('console.log("Hello, world");')
```
And evaluating an expression:
```js
async function evalInWorker(js) {
    return new Promise((res, rej) => {
        let _ = new Worker('data:text/javascript, onmessage = ({data}) => postMessage(eval(data));');
        _.onmessage = ({data}) => res(data);
        _.postMessage(js);
    });
}
```

**Comment by sjrd** [comment]
Web Workers and child processes do not have shared memory at the level of the object graph. So no, threads as in `java.lang.Thread` cannot be implemented.

Other abstractions such as message passing/the actor model can be implemented on top of those low-level mechanisms, but that is a job for separate libraries, not for this repo, which focuses on the core language.

**Comment by pitust** [comment]
I thought of putting some proxy logic into the main thread.

**Comment by sjrd** [comment]
From years of experience building Scala.js, I am totally convinced that it cannot be done.

The only way you can convince me otherwise is to prove it to me by implementing it yourself. But try at your own risks; IMO this is not possible, so as far as I'm concerned, any attempt is a pure waste of time.
