### ISSUE TITLE
Improve error message when no main module initializer was found

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#3697]
Currently it says: "No main module initializer was specified (possibly because no or multiple main classes were found) [...]".

We should report the classes that were found for easier debugging.

**Comment by corwin-of-amber** [comment]
Also it may be worth including in that message that `mainClass` and `scalaJSMainModuleInitializer` should be set in `Compile`, not in `run` or `Compile / run` as a user might expect.

**Comment by gzm0** [comment]
Fixed in https://github.com/scala-js/scala-js/pull/3724/commits/03e21895f0da94639276ef3e097de9ee7fe30d4b
