### ISSUE TITLE
j.m.BigDecimal.divideToIntegralValue(bi, MathContext) returns value with bogus internal _precision

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#3706]
**Was: Investigate upstream JUnit test scala/collection/immutable/NumericRangeTest.scala with 2.13.0**

It was blacklisted in #3702/#2703, but it is unclear if it is caused by an actual bug in our implementation of `BigDecimal` or not at this point. We should investigate.

If someone wants to tackle this, use the following steps to reproduce:
* Move the line `scala/collection/immutable/NumericRangeTest.scala` from ` scala-test-suite/src/test/resources/2.13.0/BlacklistedTests.txt` to `WhitelistedTests.txt`
* Run sbt, and inside run:

      > ++2.13.0
      > scalaTestSuite/test

**Comment by iPomme** [comment]
The code from the test:
```
val aa = BigDecimal(1, new java.math.MathContext(40))
val bb = aa + BigDecimal("1e-30")
val c = BigDecimal("1e-38")

assert((aa to bb by c).drop(1).headOption == Some(BigDecimal("1." + "0" * 37 + "1")))
```
is running fine on Scala 2.13.0,
is running fine with Scala.js on 2.12.8
and is failing with Scala.js on 2.13 (java.lang.IllegalArgumentException: More than Int.MaxValue elements)

So, it might be a bug in the implementation of `BigDecimal`

**Comment by sjrd** [comment]
Reduced the above not to need `NumericRange` as:
```scala
    val start = BigDecimal(1, new java.math.MathContext(40))
    val end = start + BigDecimal("1e-30")
    val step = BigDecimal("1e-38")

    val limit = BigDecimal(Int.MaxValue)
    val diff = end - start
    val quotient = diff.quot(step)
    println(quotient)
    println(limit)
    val gt = quotient.compare(limit) > 0
    println(gt)
    if (gt)
      throw new IllegalArgumentException("More than Int.MaxValue elements.")
```
Next step: get rid of the `scala.math.BigDecimal` intermediary, and reproduce only with `java.math.BigDecimal`.

**Comment by sjrd** [comment]
I reduced it further to using only `java.math.BigDecimal`:
```scala
    import java.math.{BigDecimal, MathContext}

    val diff = new BigDecimal("1e-30")
    val step = new BigDecimal("1e-38")
    val quotient = diff.divideToIntegralValue(step, MathContext.DECIMAL128)
    val limit = new BigDecimal(Int.MaxValue)
    assert(quotient.compareTo(limit) <= 0)
```
Now it fails both on 2.12 and 2.13. It still passes on the JVM.

It might still be possible to reduce it further not to rely on the string parsing.

The `MathContext.DECIMAL128` argument to `divideToIntegralValue` is necessary to trigger the bug. If we use the overload without it, the snippet successfully completes:
```scala
    import java.math.{BigDecimal, MathContext}

    val diff = new BigDecimal("1e-30")
    val step = new BigDecimal("1e-38")
    val quotient = diff.divideToIntegralValue(step)
    val limit = new BigDecimal(Int.MaxValue)
    assert(quotient.compareTo(limit) <= 0)
```

**Comment by sjrd** [comment]
I have a solution for this one problem in my branch https://github.com/scala-js/scala-js/compare/master...sjrd:fix-bigdecimal. However, it seems there are other issues preventing `NumericRangeTest` to completely pass. (One of the three previously failing tests now passes, so there is progress.)

**Comment by gzm0** [comment]
Consider forking off individual issues if the original issue has multiple root causes (otherwise it is unclear where to continue the investigation).

**Comment by sjrd** [comment]
Yes, absolutely. I just want to finish investigating the other two failing tests to see how to organize that best.

**Comment by sjrd** [comment]
It turns out the rest was just a matter of updating our overrides for `NumericRange.scala`. So here's the PR: #4436.
