### ISSUE TITLE
Add TypedArray.of and TypedArray.from

### ISSUE THREAD

**Issue by exoego** [scala-js/scala-js#3709]
Those are factory ethods to create an instance of *TypedArray* from various arguments.

It is currently missing in `TypedArrayStatic`.
https://github.com/scala-js/scala-js/blob/1d96d3cc24250e874ebc9aa6f78eafb060678512/library/src/main/scala/scala/scalajs/js/typedarray/TypedArray.scala#L68-L70

# *TypedArray*.from
* https://www.ecma-international.org/ecma-262/6.0/#sec-%typedarray%.from
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/from

# *TypedArray*.of
* https://www.ecma-international.org/ecma-262/6.0/#sec-%typedarray%.of
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/of

**Comment by sjrd** [comment]
Fixed in cb013d07d9fc9059e361003e67d739c45e367465.
