### ISSUE TITLE
NoClassDefFoundError: org/scalajs/core/tools/linker/backend/ModuleKind

### ISSUE THREAD

**Issue by fdietze** [scala-js/scala-js#3726]
I'm trying to cross compile a facade for scalajs `0.6` and `1.0`: https://github.com/fdietze/scala-js-d3v4/pull/16

But on all scala versions I get the following error:
```
[error] java.lang.NoClassDefFoundError: org/scalajs/core/tools/linker/backend/ModuleKind
[error] 	at java.base/java.lang.Class.forName0(Native Method)
[error] 	at java.base/java.lang.Class.forName(Class.java:398)
[error] 	at sbt.internal.inc.ModuleUtilities$.getObject(ModuleUtilities.scala:20)
[error] 	at sbt.internal.inc.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:27)
[error] 	at sbt.internal.inc.ModuleUtilities$.$anonfun$getCheckedObjects$1(ModuleUtilities.scala:31)
[error] 	at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:414)
...
```
full error log: https://travis-ci.org/fdietze/scala-js-d3v4/jobs/560227943#L673

`0.6` compiles well: https://travis-ci.org/fdietze/scala-js-d3v4/builds/560227937

What could be wrong? Is this bundler related?

**Comment by sjrd** [comment]
You're most likely using another sbt plugin that depends on sbt-scalajs 0.6.x. Typical culprit: scalajs-bundler.

**Comment by fdietze** [comment]
Oh, you are totally right. Thank you. I have to adjust the bundler version according to the scalajs version. Having this in my `project/plugins.sbt` works:

```scala
val scalaJSVersion = Option(System.getenv("SCALAJS_VERSION")).getOrElse("0.6.28")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % scalaJSVersion)
val bundlerVersion = if (scalaJSVersion.startsWith("0.6.")) "0.15.0-0.6" else "0.15.0"
addSbtPlugin("ch.epfl.scala" % "sbt-scalajs-bundler" % bundlerVersion)
```
