### ISSUE TITLE
Cannot use require() when JSDOM is enabled

### ISSUE THREAD

**Issue by tindzk** [scala-js/scala-js#3729]
When I change the Scala.js environment to `JSDOMNodeJSEnv`, `require()` stops working in my test suite. I also cannot access environment variables anymore (via `js.Dynamic.global.process.env.ENV_VAR`).

This behaviour can be reproduced with 0.6 and 1.0. Here is a minimal example: https://github.com/tindzk/scalajs-jsdom

Removing the `jsEnv` line from `build.sbt` restores the expected behaviour.

**Comment by sjrd** [comment]
This is by design. The jsdom env is mostly a browser environment, *not* a Node.js environment. In a browser, such things don't exist.
