### ISSUE TITLE
scala's BigInt and BigDecimal are not implemented in Scala.js

### ISSUE THREAD

**Issue by emcastro** [scala-js/scala-js#373]
Classes _scala.math.BigInt_ and _scala.math.BigDecimal_ don't work. They are not documented as such in http://www.scala-js.org/doc/semantics.html

The problem arises from the heavy use of Java classes in BigInt dans BigDecimal scala source code.

**Comment by fommil** [comment]
:+1: I wanted to turn my little kerbal calculator into a webapp but I'm stopped because of this https://github.com/fommil/kerbal-calculator/tree/11620af869db57e1309d09097b1852a24f7e1035 this commitid is potentially a good testing ground for anyone wanting to implement this.

**Comment by sjrd** [comment]
@fommil Oops, I'm sorry, I accidentally deleted your comment :-s Fat fingers :-s

That said, if all you're using is `math.log`, I suggest you use `Math.log`, which works. (with a capital `M`)

**Comment by fommil** [comment]
ooh! I might try that. I've documented the ticket in my tracker so that's enough. I really just wanted to say :+1:

**Comment by fommil** [comment]
weird, the `log` wasn't causing the problem in the stacktrace, it was some code that looked like this

```scala
  private def candidates(
    engine: Engine, payloadMass: Double
  )(implicit allTanks: FuelTanks): Stream[EngineSolution] = for {
    numEngines <- (1 to 8).toStream // consider up to 8 radial engines
    if numEngines == 1 | engine.mount == Radial
    tank <- engine.validTanks ++ engine.internal
    fuel <- (0.0 to tank.max by tank.max / 100)
    if fuel > 0 & fuel <= tank.max // FIXME scala rounding errors
  } yield EngineSolution(payloadMass, engine, numEngines, tank, fuel)
```

and the `(1 to 8).toStream` and `numEngines == 1` lines seemed to be causing the problem.

**Comment by sjrd** [comment]
I would think it's the `0.0 to tank.max by tank.max / 100`. The ranges over `Double`s use indirectly `BigDecimal`, which you should therefore avoid. Ranges over `Int`s, such as `1 to 8`, should work without problem.

**Comment by fommil** [comment]
I'll maybe give this another try, and that line is crap anyway

**Comment by fommil** [comment]
@sjrd excellent, that was the line causing the problem! (the stacktrace was off by a few lines).

Yay, I can turn this into a webapp, I'm very pleased :smile:

**Comment by SemanticBeeng** [comment]
@lihaoyi Not quite sure, from this thread, what the plans are for BigDecimal in ScalaJS.
Would you say it is best to port to Scala or use something like this https://github.com/iriscouch/bigdecimal.js

**Comment by gzm0** [comment]
IIUC, bigdecimal.js just pulls it out of GWT and packages it nicely. Since the licenses of GWT and Scala.js are compatible, we probably should just port the implementation to Scala. (Just as we have done for Longs in the past).

**Comment by sjrd** [comment]
We could do that indeed.

**Comment by SemanticBeeng** [comment]
What would be a way to go about it? (turns out I really need a basic solution asap)

Is there a way to somehow make this new lib use Scala BigDecimal for "jvm" and a Scala.JS Dynamic wrapper for https://github.com/iriscouch/bigdecimal.js for "js"? All behind a shared Scala interface?

Or you mean to port the JS code to Scala?

**Comment by SemanticBeeng** [comment]
BigNum referenced about would not be a solution because of the Java dependencies, right?
https://github.com/techaddict/bignum/blob/master/project/Build.scala

**Comment by cheeseng** [comment]
+1 for this, the support of BigDecimal will be very useful.

**Comment by gzm0** [comment]
> BigNum referenced about would not be a solution because of the Java dependencies, right?

This project is a very unfinished project that actually has been created with the intention to put it into Scala.js eventually IIRC. However, it does - at least at this point - by far not meet Scala.js' quality standards.

For anyone who want's to contribute to Scala.js, this is a simple (yet important and high-visibility) task that does not require knowledge of the internals. Just add the relevant files in the `javalib` project, tests in `test-suite/src/test/scala/org/scalajs/testsuite/javalib` and we're good to go.

**Comment by SemanticBeeng** [comment]
I need this even unfinished and will try to advance but please clarify how can it work in ScaalJS given the Java dependencies listed here: https://github.com/techaddict/bignum/blob/master/project/Build.scala

**Comment by sjrd** [comment]
The Java dependencies listed there only apply to the Benchmarks subproject. You don't need the benchmarks to run to have it work.

**Comment by SemanticBeeng** [comment]
All right. I gave it a half ass try to use the Scala files outside the project and did not compile.
Will give it another one.

Please share if there is anything else needed to start or evolve a ScalaJS worthy project.
I need this asap so must get it to work on it's own project.
Will evolve over time if it flies.

**Comment by sjrd** [comment]
It's worth mentioning, about https://github.com/techaddict/bignum, that:

* It is not an implementation of `java.math.BigInteger`. It's a different implementation, initially thought of as an independent BigNum library for Scala that would *not* depend on the JDK.
* It is mostly based on `Long`s internally, and Longs have terrible performance in Scala.js. So with this implementation, the slowness of bignums will be multiplied by the slowness of Longs. (GWT's implementation uses Ints - although it has additional quirks that we don't need because GWT's Ints are not really 32-bit ints)

**Comment by lihaoyi** [comment]
I wonder if it'd be worth introducing a new 53-bit integer data type in
Scala.js just for cases like this =P

**Comment by sjrd** [comment]
@lihaoyi No, 32-bit ints are faster than 53-bit integers. You'll win in space, which means less time spent on going through the array of integers. But it's likely that internal manipulations will overflow your 53-bit precision anyway, so you'll lose time recovering these. I believe a 32-bit based implementation is best.

**Comment by sjrd** [comment]
So for reference, GWT's implementation is here:
https://github.com/gwtproject/gwt/blob/master/user/super/com/google/gwt/emul/java/math/BigInteger.java
with bits and pieces in the parent directory.

**Comment by lihaoyi** [comment]
Good point, I forgot that browsers probably do optimistic optimizations to
turn them into 32bit ints where possible

**Comment by sjrd** [comment]
It's not "probably". They do.

**Comment by InTheNow** [comment]
Quick update.... I'm actually **implementing** this :) FYI....

I am using a combination of the [gwt](https://github.com/gwtproject/gwt/tree/master/user/super/com/google/gwt/emul/java/math) and [android](https://android.googlesource.com/platform/libcore/+/master/luni/src/main/java/java/math/) versions. They both originate from the same source and both use native calls, so I mix'n'match to get a code set with no natives.

@sjrd @gzm0 One question. Given the relative complexity and size of this code, it's become apparent that I have to /should also port [the tests](https://github.com/gwtproject/gwt/tree/master/user/test/com/google/gwt/emultest/java/math), or at least some/most of them. But to where? I think the best is to add a new javalib-test-suite, are you OK with this?

This is in addition to turning on a few extra partests.

**Comment by sjrd** [comment]
Yes, this should definitely be tested. The appropriate place for these tests is in `test-suite/.../javalib/Big{Integer,Decimal}Test.scala`.

**Comment by InTheNow** [comment]
I've pushed the current state of my port to [my github](https://github.com/InTheNow/scala-js/tree/BigNumerics). Not all the tests have implemented, and not all those that have been are passing. Stiil, there is over 8000 LOC and some tests are OK. But.... 

I have a problem with an enumeration, [RoundingMode](https://github.com/InTheNow/scala-js/blob/BigNumerics/javalib/src/main/scala/java/math/RoundingMode.scala). it's failing in quite a few tests, including [its own](https://github.com/InTheNow/scala-js/blob/BigNumerics/test-suite/src/test/scala/org/scalajs/testsuite/javalib/math/RoundingModeTest.scala)

I've also added a copy and test in  [MyRoundingMode](https://github.com/InTheNow/scala-js/blob/BigNumerics/test-suite/src/test/scala/org/scalajs/testsuite/javalib/math/MyRoundingModeTest.scala)  and that seems ok-ish.

@sjrd @gzm0 I wonder if you could have a look at this, please?

**Comment by sjrd** [comment]
Enumerations in Java and in Scala have nothing in common. You cannot expect `extends Enumeration` to produce classes that are binary-compatible with the Java-emitted one.
Have a look at [TimeUnit](https://github.com/scala-js/scala-js/blob/master/javalib/src/main/scala/java/util/concurrent/TimeUnit.scala) to see how to do it properly.

**Comment by InTheNow** [comment]
@sjrd Thanks - I knew that was the "general" issue but was unsure of the actual solution, thanks!
