### ISSUE TITLE
Add JDK 8 higher-order methods in the JDK collections classes.

### ISSUE THREAD

**Issue by t5kaji** [scala-js/scala-js#3731]
When working on a cross project, there might be places where we want to implement something with `forEach` function of `java.util.HashMap` in `shared` folder for better performance.

**Comment by sjrd** [comment]
I have generalized the title to all higher-order methods of all the JDK collections.

**Comment by er1c** [comment]
Should this be closed via https://github.com/scala-js/scala-js/pull/3973 ?

**Comment by sjrd** [comment]
No, there are still a number of methods that are not implemented:

* `List.replaceAll`
* `List.sort`
* And a bunch of methods in `Map`

**Comment by gzm0** [comment]
@sjrd is this done now?

**Comment by sjrd** [comment]
Yes. It was done by:
* f9fc1aef1c9bb017f753d663d7a9ce86fbaeb978 `j.l.Iterable.forEach`
* 489180f87cdd53e239c92c875fdf97760620d713 `j.u.Optional` methods
* 43f6d381607f483dda179d56daa45142460980a6 `j.u.List.sort`
* ad7d82f4245f63f74cd1aa8a3217c01d7369279a `j.u.List.replaceAll`
* 6819668e8038a592e8a944b65fd09d232a145e3a `j.u.Iterator.remove`
* f86ed657f830de4b690e4437691b230a1870c008 `j.u.Iterator.forEachRemaining`
* f7be410503f87b402a86c92945dba37455f06853 `j.u.Map` methods
