### ISSUE TITLE
Cannot use annotations inside @JSGlobal annotation

### ISSUE THREAD

**Issue by fdietze** [scala-js/scala-js#3737]
I have this facade code:

```scala
import scala.scalajs.js
import scala.scalajs.js.annotation._

@js.native
@JSGlobal("$crisp")
object crisp extends js.Object
```

But I'm getting a `possible missing interpolator waring`. Therefore I tried to suppress the warning using https://github.com/ghik/silencer:

```scala
import scala.scalajs.js
import scala.scalajs.js.annotation._
import com.github.ghik.silencer.silent

@js.native
@JSGlobal("$crisp": @silent)
object crisp extends js.Object
```

But then ScalaJs complains that `"$crisp": @silent` is not a string literal anymore.

See https://github.com/ghik/silencer/issues/32

**Comment by sjrd** [comment]
See the discussion on gitter starting at https://gitter.im/scala-js/scala-js?at=5d416cdf20f75e7ba55aa4fc

Also see the workaround proposed at https://github.com/ghik/silencer/issues/32#issuecomment-516794311

**Comment by sjrd** [comment]
I believe this should be addressed upstream in `constantAtIndex` at
https://github.com/scala/scala/blob/2.12.x/src/reflect/scala/reflect/internal/AnnotationInfos.scala#L339-L343
to handle [`Annotated`](https://github.com/scala/scala/blob/58ce104566dc68b0c26eb18b8f6162017f8cf500/src/reflect/scala/reflect/internal/Trees.scala#L611) trees that (recursively) contain a `Literal` arg.

**Comment by sjrd** [comment]
@fdietze Perhaps you'd like to submit a PR to scala/scala for this?

**Comment by fdietze** [comment]
Sorry, I'm too busy right now. And this feature is currently not that important for my work.

But moving the bug to the scala compiler makes sense, I guess.

**Comment by gzm0** [comment]
https://github.com/scala/scala/pull/9342

**Comment by sjrd** [comment]
The upstream PR https://github.com/scala/scala/pull/9342 was merged. It is already included in 2.13.5, and will be part of 2.12.14 when that comes out. I believe we can close this issue here.

**Comment by gzm0** [comment]
Shouldn't we add a test to the Scala.js repo?

**Comment by sjrd** [comment]
It's probably not worth it, given the difficulty of setting up such a test (it has to be a source file that is conditionally enabled) versus what it tests. But we can if you think it's worth it.
