### ISSUE TITLE
Scala 2.12.9 support

### ISSUE THREAD

**Issue by xerial** [scala-js/scala-js#3738]
We need Scala.js 0.6.28 (or higher) with Scala 2.12.9 support:
org.scala-js:scalajs-compiler_2.12.9:0.6.28 

My working branch: https://github.com/xerial/scala-js/tree/scala-2.12.9

Blocker:
- [ ] Outer reference is now reported as a compile error: https://github.com/scala/bug/issues/11534

Related: https://github.com/wvlet/airframe/pull/576

**Comment by xerial** [comment]
@sjrd It seems we need to wait for Scala 2.12.10 if there is no workaround for scala/bug#11534

**Comment by sjrd** [comment]
I'm not sure what you're talking about. Scala.js 0.6.28 and 1.0.0-M8 are ready for Scala 2.12.9. I will publish them tomorrow. Tonight I was hosting guests and now I am going to sleep.

**Comment by xerial** [comment]
@sjrd That's good to know.

Actually I hit the following error with Scala 2.12.9:
```
sbt:Scala.js> ~testSuite/test
[info] Compiling 34 Scala sources to /Users/leo/work/git/scala-js/compiler/target/scala-2.12/classes ...
[error] /Users/leo/work/git/scala-js/compiler/src/main/scala/org/scalajs/nscplugin/GenJSCode.scala:4679:33: The outer reference in this type test cannot be checked at run time.
[error]         case JSUnaryOpMethodName(code) if argc == 0 =>
[error]                                 ^
[error] one error found
[error] (compiler / Compile / compileIncremental) Compilation failed
[error] Total time: 7 s, completed Aug 5, 2019 12:58:45 PM
1. Waiting for source changes in project scalajs... (press enter to interrupt)```

**Comment by sjrd** [comment]
FYI, Scala.js 0.6.28 and 1.0.0-M8 for Scala 2.12.9 are on their way to Maven Central.
