### ISSUE TITLE
 Unknown opcode: 7 with scalatest async testing

### ISSUE THREAD

**Issue by hsn10** [scala-js/scala-js#3763]
https://github.com/hsn10/scalajs-async-scalatest
run: `sbt test`

This bug is related to execution contexts, but it is only triggered when async test suite is invoked as nestedSuite. From investigation it seems it needs 2 different active ec to fail.

I have to do:
```scala
implicit override def executionContext = scala.concurrent.ExecutionContext.Implicits.global
```
because later I am using JS promises auto conversion to scala future.
```scala
import scala.scalajs.js.Thenable.Implicits._
```
and these conversions can't use user provided execution context. Not overriding it give error: future not finished but queue is empty.

Proposed fix add Execution context as implicit parameter to conversion functions, this is standard in scala.

**Comment by sjrd** [comment]
Hi, thanks for your interest.

The conversions in `js.Thenable.Implicits` do not accept custom `ExecutionContext`s because they don't need an `ExecutionContext` *at all*. It's not like they're using a hard-coded one. They're *not using* any `ExecutionContext`.

So if they were taking an implicit EC, as you suggest, they would simply ignore it.

**Comment by sjrd** [comment]
To me, it looks like a bug in ScalaTest. Or maybe some usage that you're doing of ScalaTest that is not supported?

In any case I don't think there's anything we can change in Scala.js for this.

If you still think that the conversions in `js.Thenable` are at fault, and that you could fix the problem with a custom EC given to them, I encourage you to copy-paste the conversion from https://github.com/scala-js/scala-js/blob/c72bf677d77472d8f9bb35bca217b5dcb8f7e731/library/src/main/scala/scala/scalajs/js/Thenable.scala#L45-L66, and adapt it until it works for you.

**Comment by hsn10** [comment]
What helps is to use:
implicit override def executionContext = scala.scalajs.concurrent.JSExecutionContext.Implicits.runNow

inside of _AsyncWordSpec_

**Comment by sjrd** [comment]
`runNow` is a fake EC. If using it helps, it means that some code somewhere is not actually ready to accept the fully asynchronous nature of Futures.

**Comment by hsn10** [comment]
http://www.scalatest.org/user_guide/async_testing

On JavaScript, where single-threaded execution is the only possibility, the default execution context is _scala.scalajs.concurrent.JSExecutionContext.Implicits.queue_.

scalatest async testing and its execution context works as long you do not call JS code returning promise.

**Comment by sjrd** [comment]
> scalatest async testing and its execution context works as long you do not call JS code returning promise.

So ... it looks like a bug (or limitation) in ScalaTest, doesn't it?

**Comment by sjrd** [comment]
I'm going to close this with the assumption that there's nothing actionable to do in this repo. Feel free to reopen if you have more evidence that there should be a fix in this repo.
