### ISSUE TITLE
Compilation failures on recent Scala nightlies

### ISSUE THREAD

**Issue by SethTisue** [scala-js/scala-js#3785]
seen at e.g. https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5084/artifact/logs/scala-js-build.log

```
[scala-js] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.16/project-builds/scala-js-be8a93dfcc3fee9feb6a481b3c6d36d81a0aacff/scalalib/target/scalaSources/2.12.11-bin-f13fdd7/scala/collection/immutable/TreeMap.scala:213: error: value foreachEntry is not a member of object scala.collection.immutable.RedBlackTree
[scala-js] [error]       RB.foreachEntry(tree, hasher)
[scala-js] [error]          ^
[scala-js] [error] one error found
[scala-js] [error] Nonzero exit code returned from runner: 1
[scala-js] [error] (scalalib / Compile / compile) Nonzero exit code returned from runner: 1
```

it started when we

```
-# September 11, 2019
-nightly=2.12.11-bin-1f19ef4
+# September 23, 2019
+nightly=2.12.11-bin-f13fdd7
```

'ed

**Comment by sjrd** [comment]
Oh, we have an override for `RedBlackTree.scala` in 2.12 (and 2.10 and 2.11, but not 2.13+). Looks like we need to catch up with the changes that happened in https://github.com/scala/scala/commit/c66e1d5af6acf190e93ab5ecd68ccb2a6eceec2e#diff-f99536a3327e638dcf239518f2c3f0ce.

**Comment by sjrd** [comment]
@SethTisue This should be fixed, now. Can you confirm, when you get the results of a new community build run?

**Comment by SethTisue** [comment]
confirmed, green after https://github.com/scala/community-builds/commit/eaa9d27c00f7a4b0588a24b7cf7d73371901d62f

**Comment by SethTisue** [comment]
hmm, but failing in 2.13.x: https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/2658/artifact/logs/scala-js-build.log

**Comment by sjrd** [comment]
It looks like that failure is an entirely different issue, and I actually suspect an actual issue in Scala upstream. I would rather you open a different issue, please.

**Comment by SethTisue** [comment]
sure. #3792
