### ISSUE TITLE
Check CLA fails (probably needs executable bit)

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#3798]
/home/runner/work/_temp/44fb6238-ada5-4758-bf69-ed2fceca0101.sh: line 1: ./ci/check-cla.sh: Permission denied

**Comment by gzm0** [comment]
e.g. #3790

**Comment by sjrd** [comment]
Fixed in 4b13cfe2a1398fc593ad1a54c221406f7af23cdd. Now it works, e.g., #3797.
