### ISSUE TITLE
Scala 3 support

### ISSUE THREAD

**Issue by ryanberckmans** [scala-js/scala-js#3807]
Does scala-js intended to support Scala 3 sooner than later? It'd be really cool to start trying out scala-js + dotty.

**Comment by sjrd** [comment]
Please see https://github.com/lampepfl/dotty/issues/7113. It's Scala 3 that needs to add support for Scala.js; not the other way around. ;)

**Comment by ryanberckmans** [comment]
Hah, good to know. Thanks @sjrd. Scala.js is amazing.
