### ISSUE TITLE
FunctionEmitter incorrectly classifies ArraySelect as side-effect free

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#3848]
Discovered while working on #3824.

https://github.com/scala-js/scala-js/blob/dacf08e14b0a856b89204d63d2b9450fa55a7e65/linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/FunctionEmitter.scala#L1147-L1148

This is incorrect, as it can throw an `ArrayIndexOutOfBoundsException`.

**Comment by sjrd** [comment]
Indeed, that should be conditioned on `semantics.arrayIndexOutOfBounds == Unchecked`

**Comment by sjrd** [comment]
Fixed in https://github.com/scala-js/scala-js/commit/f18a9b4c8a35bf3646643b919ed8c720eb3f2528
