### ISSUE TITLE
js.Dictionary should extends js.Object

### ISSUE THREAD

**Issue by exoego** [scala-js/scala-js#3870]
Currently, `js.Dictionary` extends `js.Any` instead of `js.Object`.
Therefore, `js.Object.assign` (or similar methods) can not be applied to `js.Dictionary` instances.
My usecase: I want to merge many dictionaries using `js.Object.assign(empty, dict1, dict2, dict3)` which is js.native efficient operation.

Sorry in advance, this had been perhaps asked many times, but I could not find a reason why it does not extends `js.Object`.
I only found #2492 which does not explain why `js.Any`.

**Comment by sjrd** [comment]
That is on purpose. If it extended `js,Object`, then the type system would let you call methods of `js.Object`, for example `hasOwnProperty`, but that would be unsound if the dictionary precisely contains an entry for the key `"hasOwnProperty"`.

**Comment by sjrd** [comment]
FTR, `git blame` points are https://github.com/scala-js/scala-js/commit/f3dbdc4f7c6bdb433681ece89f36c9ba45b95c66, which mentions the reason in the commit message.

**Comment by exoego** [comment]
Thanks !!
That sounds a fair reason not to extends `js.Object`.
So I will continue using something like this

```scala
val mergedDictionary = js.Object.assign(
  new js.Object(),
  dict1.asInstanceOf[js.Object],
  dict2.asInstanceOf[js.Object]
).asInstanceOf[js.Dictionary[js.Any]]
```

**Comment by gzm0** [comment]
FWIW: It might be a good idea to add a comment right on the definition of `js.Dictionary` rather than relying on blame-ing.
