### ISSUE TITLE
Investigate why #3832 needs a different file with a fix

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#3878]

**Comment by gzm0** [comment]
Touching the file does not fix the issue. If I change `test` to the following, it still fails:

```
$ copy-file Data.scala.good Data.scala
> fastOptJS
$ copy-file Data.scala.broken Data.scala
-> fastOptJS
$ copy-file Data.scala.good Data.scala
$ touch Data.scala
> fastOptJS
```

**Comment by gzm0** [comment]
- I cannot reproduce this with a normal sbt project (and copying files): Copying the original file back makes compilation succeed.
- Even when touching after every copy (and manually validating the timestamps are different), the scripted test fails.

The only thing suspicious is that on the system I'm using, is the access time does not have a fractional second part in `/tmp`, where it does in the working directory of Scala.js. I will try to change the directory scripted puts the test project in and see if it changes anything.

**Comment by gzm0** [comment]
Changing the FS does not change anything. Next thing to test: In my local reproduction I did not restart sbt between invocations. I should try that.

**Comment by gzm0** [comment]
Individual sbt invocations also work. I need a new theory :)

**Comment by gzm0** [comment]
@sjrd I'm tempted to close this. cost/benefit ratio seems too high. WDYT?

**Comment by sjrd** [comment]
Yes, I agree.
