### ISSUE TITLE
Bootstrap test broken in 0.6.x with Node.js 13

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#3908]
With Node.js 13.3.0 on the PATH, in 0.6.x, `toolsJS/test` fails one test, namely `StackTraceTest.decode_class_name_and_method_name`:
```
Test run started
Test org.scalajs.testsuite.library.StackTraceTest.decode_class_name_and_method_name started
Test org.scalajs.testsuite.library.StackTraceTest.decode_class_name_and_method_name failed: null, took 0.041000192 sec
Test org.scalajs.testsuite.library.StackTraceTest.decode_class_name_and_method_name finished, took 0.041000192 sec
Test run finished: 1 failed, 0 ignored, 1 total, 0.041000192s
```
This does not happen on Node.js v10, nor in 1.x (for `testSuite2_12/bootstrap:test` in that branch). Upgrading source-map-support to 0.5.7 (same as in 1.x) does not solve the issue.

My first guess would be that it's related to the fact that `toolsJS/test` executes everything in an `eval()`, whereas in 1.x `testSuite2_12/bootstrap:test` uses all the right setups to execute the bootstrapped test suite as a top-level script, just like the non-bootstrapped one.

If I can't nail it down quickly enough, I will first submit a PR to disable that test in the boostrap, to repair the CI.

**Comment by gzm0** [comment]
I also propose to close this one.
