### ISSUE TITLE
toplevel js.native js.Import object is not accessible

### ISSUE THREAD

**Issue by aappddeevv** [scala-js/scala-js#3915]
* Give code *and* reproducible steps to provoke the bug

```scala
package foo // <- if I leave this out, I cannot access someobject at the toplevel package
@js.native
@JSImport("somepackage", "someobject")
object someobject extends js.Object {
...
}
```

* Give the version of Scala and Scala.js you are using (if relevant, sbt as well)

0.6.31  

* What did you expect to happen?

I expected the object to be accessible. It is not accessible via `_root_` either.  

* What actually happened?

The compiler said that the object was not found. I had to add a toplevel package to be able to access it.

**Comment by aappddeevv** [comment]
Hmm...a note on gitter says this may be per the spec.

**Comment by sjrd** [comment]
What code are you using when trying to access the object? What's the error message? Can you reproduce the same problem with something that's not a JS object? If yes, can you reproduce the issue in Scala/JVM?

**Comment by sjrd** [comment]
Closing for lack of full reproduction. Feel free to reopen with an answer to my previous comment.
