### ISSUE TITLE
Wrong maxBytesPerChar for CharsetEncoder

### ISSUE THREAD

**Issue by pweisenburger** [scala-js/scala-js#3922]
The [auxiliary constructor](http://github.com/scala-js/scala-js/blob/69935b2781e5e8e249491d2483e1abcc42d9c877/javalib/src/main/scala/java/nio/charset/CharsetEncoder.scala#L25) of `CharsetEncoder` ignores its `_maxBytesPerChar` argument.

The line
```this(cs, _averageBytesPerChar, _averageBytesPerChar, Array('?'.toByte))```
should probably be
```this(cs, _averageBytesPerChar, _maxBytesPerChar, Array('?'.toByte))```

**Comment by gzm0** [comment]
Hah, nice find!

**Comment by sjrd** [comment]
@pweisenburger Thanks for the report! Fix available in #3923.

**Comment by sjrd** [comment]
Fixed in df335fc3ea1f8e1a05e5ebcb760e09b0d166e9d0.

**Comment by pweisenburger** [comment]
Thanks for fix. That was quick :-)
