### ISSUE TITLE
Static forwarders are not generated for static nested objects

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#3950]
This is a problem for implementations of Java libraries with nested statics:

```scala
object Locale {
  final class Category private (name: String, ordinal: Int) extends Enum[Category](name, ordinal)

  object Category {
    def DISPLAY: Category = new Category("DISPLAY", 0)
  }
}
```

**Comment by cquiroz** [comment]
It seems there maybe a regression about this on 1.2.0. I upgraded it on scala-java-locales and got this error

```
Error:  Referring to non-existent method static java.util.Locale$Category.DISPLAY()java.util.Locale$Category
Error:    called from testsuite.javalib.util.LocaleTest$$anonfun$52.apply()java.lang.NullPointerException
Error:    called from testsuite.javalib.util.LocaleTest$$anonfun$52.apply()java.lang.Object
Error:    called from static scala.collection.MapLike$class.getOrElse(scala.collection.MapLike,java.lang.Object,scala.Function0)java.lang.Object
```

For more details:
https://github.com/cquiroz/scala-java-locales/runs/1215176125?check_suite_focus=true#step:7:942

**Comment by gzm0** [comment]
See #4148 / #4152. This behavior needs to be enabled explicitly via flag now. @sjrd should we put this into the release notes?

**Comment by gzm0** [comment]
The option to re-enable the feature is: `-P:scalajs:genStaticForwardersForNonTopLevelObjects`

**Comment by sjrd** [comment]
Oh yes, that should have been in the release notes :s
