### ISSUE TITLE
JVM & JS disagree whether \u00a0 matches /\s/

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#3959]
If you run `160.toChar.toString.matches("\\s")` in both JVM and JS, you can that they return different results.

* JVM = false
* JS = true

**Comment by sjrd** [comment]
I'm afraid that's just one of the zillion cases where the JS engine differs from the JVM one. The fact that they're different is already tracked as #1201, so I'm going to close this issue as a duplicate.

**Comment by japgolly** [comment]
Ha! And raised by me nonetheless. I'd completely forgotten. Thanks @sjrd
