### ISSUE TITLE
Define the compatibility guarantees of minor/patch versions

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#3980]
It's pretty clear by now what constitutes a major version bump. Any of the following would trigger a major version bump:

* Backward incompatible changes in the IR
* Backward binary incompatible changes in the standard library
* Backward incompatible changes in the contract for calling JDK APIs

However, we have not precisely defined what would cause a minor version bump over a patch version bump.

**Comment by sjrd** [comment]
IMO, the following changes should definitely cause a minor version bump. Some of them I mark as "severe", in the sense that they can break the ecosystem of sbt plugins and other build tools, but not the ecosystem of libraries (which would be major):

* Backward binary incompatible changes in `logging.*`, `linker.interface.*` or `sbtplugin.*` (severe)
* Backward binary incompatible changes in `jsenv.*` or `testadapter.*` (severe)
* Backward source incompatible change at the language level or at the standard library level (including any addition of public API in the stdlib)
* Backward source incompatible change in `logging.*`, `linker.interface.*` or `sbtplugin.*` (including any addition of public API)
* Backward source incompatible changes in `jsenv.*` or `testadapter.*`
* Backward binary incompatible change in `ir.*`, `linker.interface.unstable.*`, `linker.*` or `linker.stable.*`

Severe changes should be done only if absolutely necessary (e.g., they could be justified to add module splitting support, if required).

The following changes should not, IMO, cause a minor version bump:

* Backward source incompatible change in `ir.*`, `linker.interface.unstable.*`, `linker.*` or `linker.stable.*`
* Backward source/binary incompatible changes elsewhere in `linker.**`
* Fixes or additions in the JDK libs (since they are always backward source and binary compatible)

**Comment by gzm0** [comment]
Overall this seems to be a good summary. Thoughts:

The changes you marked as "severe" should IMHO also trigger a major version bump. If we really need to do this, we should consider splitting the IR/lib versioning off.

[SemVer §7][1] says:

> Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API. [...] It MAY be incremented if substantial new functionality or improvements are introduced within the private code. [...]

This would mean adding JDK libs would cause a minor bump (except if we consider absence a bug). Its true that given how much goes into minor versions already, we maybe shouldn't apply the MAY clause at all.

So given all this, it is probably OK to leave the list as you proposed it.
