### ISSUE TITLE
Probably a bug near `@inline`

### ISSUE THREAD

**Issue by catap** [scala-js/scala-js#4000]
This behaviour is reproduced via https://github.com/sjrd/scalajs-benchmarks/pull/3 with current master.

`java.math.Division.monReduction` is something likes:
```
...
      val m = Multiplication.unsignedMultAddAdd(res(i), n2, 0, 0).toInt
      for (j <- 0 until modulusLen) {
        val nextInnnerCarry =
          unsignedMultAddAdd(m, modulusDigits(j), res(i + j), innnerCarry)
...
```
and `unsignedMultAddAdd` is very trivial:
```
  @inline def unsignedMultAddAdd(a: Int, b: Int, c: Int, d: Int): Long =
    (a & 0xFFFFFFFFL) * (b & 0xFFFFFFFFL) + (c & 0xFFFFFFFFL) + (d & 0xFFFFFFFFL)
```

But if we check that js is generated by `monReduction` we can see:
```
...
    $m_Ljava_math_Multiplication$();
    const a = res.get(arg1);
    const a0 = (65535 & a);
    const a1 = ((a >>> 16) | 0);
    const b0 = (65535 & n2);
    const b1 = ((n2 >>> 16) | 0);
    const a0b0 = $imul(a0, b0);
    const a1b0 = $imul(a1, b0);
    const a0b1 = $imul(a0, b1);
    const lo = ((a0b0 + (((a1b0 + a0b1) | 0) << 16)) | 0);
    let i$1 = 0;
    while ((i$1 < modulusLen)) {
...
```
and this call a function exists 
```
...
        var k = void 0;
        k = 0;
        R();
        var l = f.a[g],
            n = 65535 & l,
            r = l >>> 16 | 0,
            u = 65535 & d,
            t = d >>> 16 | 0;
        l = m(n, u);
        r = m(r, u);
        n = m(n, t);
        n = l + ((r + n | 0) << 16) | 0;
        for (l = 0; l < a;) {
...
```

This function is defined as:
```
function $m_Ljava_math_Multiplication$() {
  if ((!$n_Ljava_math_Multiplication$)) {
    $n_Ljava_math_Multiplication$ = new $c_Ljava_math_Multiplication$()
  };
  return $n_Ljava_math_Multiplication$
}
```

This call doesn't do anything at this case, because the body was inlined.

You can see some differences with and without this `R()` — I've cleaned it up by hand:
```
➜  scalajs-benchmarks git:(added-bignums) node bigNumbers/.js/target/scala-2.12/bigNumbers-opt.js  
bigNumbers.ModBenchmark$: Node.js;1499576.8605984747;250.7403228241497
➜  scalajs-benchmarks git:(added-bignums) node bigNumbers/.js/target/scala-2.12/bigNumbers-opt.js
bigNumbers.ModBenchmark$: Node.js;1323191.7049996555;244.21177772706403
➜  scalajs-benchmarks git:(added-bignums) 
```

**Comment by sjrd** [comment]
It's a call to load the module (`object`). It must be kept for correctness in case its constructor is not pure. For trivial constructors, the optimizer can figure out that they're pure and eliminate the call. But the constructor of `object Multiplication` is not trivial enough for that.

There are some more related information about module loading in this is ticket: #1588.

**Comment by catap** [comment]
@sjrd but why you need to call a constructor of inlined function that hasn’t call anything from object?

**Comment by sjrd** [comment]
Because the constructor of said object could have side effects or be impure. It is simply *not correct* to disregard those potential side effects. The linked issue discusses this in detail.
