### ISSUE TITLE
Linking error with Scala.js 1.0 & scalaJSUseMainModuleInitializer

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#4030]
Check out `https://github.com/japgolly/scalajs-react/tree/topic/sjs10`.

You can see in `project/Build.scala` that the `gh-pages` modules has :

```scala
      scalaJSUseMainModuleInitializer := true,
      mainClass in Compile := Some("ghpages.GhPages"),
```

However when I run `gh-pages/fastOptJS` or `gh-pages/fullOptJS` I get:

```
[info] Fast optimizing /home/golly/projects/public/scalajs-react/gh-pages/target/scala-2.13/gh-pages-fastopt.js
[error] Referring to non-existent class ghpages.GhPages
[error]   called from core module module initializers
[error] Referring to non-existent method static ghpages.GhPages.main([java.lang.String)void
[error]   called from core module module initializers
[error] There were linking errors
[error] (gh-pages / Compile / fastOptJS) There were linking errors
```

This is regardless of whether I have

```scala
  def main(): Unit = {
```

or

```scala
  def main(args: Array[String]): Unit = {
```

**Comment by sjrd** [comment]
You'll need the extended `main` definition, for one thing:
```scala
def main(args: Array[String]): Unit = {
```
In addition, your build has `-Xno-forwarders`, which disables the generation of static forwarder to the methods of `object`s. That also disables the generation of the `static def main(...)`, which is necessary for `scalaJSUseMainModuleInitializer`.

If I use the long main definition + add the following in the settings of `ghpages`:
```scala
scalacOptions -= "-Xno-forwarders"
```
then `gh-pages/fastOptJS` succeeds.

**Comment by sjrd** [comment]
It turns out that we interpret `-Xno-forwarders` slightly differently than Scala/JVM. In Scala.js, this disables *all* static forwarders. In Scala/JVM, it disables static forwarders only for `object`s that have a companion class. Objects without a companion class receive static forwarders anyway.

So we can reproduce a similar issue on the JVM, but only if we add a companion class:
```scala
package test

class Test

object Test {
  def main(args: Array[String]): Unit = println("hello")
}
```
Trying `sbt run` in a JVM project with `-Xno-forwarders` throws the following exception:
```
[info] running test.Test
[error] (run-main-2) java.lang.NoSuchMethodException: test.Test.main([Ljava.lang.String;)
[error] java.lang.NoSuchMethodException: test.Test.main([Ljava.lang.String;)
[error]         at java.lang.Class.getMethod(Class.java:1786)
[error] stack trace is suppressed; run last Compile / bgRun for the full output
[error] Nonzero exit code: 1
```
However, if we remove `class Test`, then it works:
```
[info] running test.Test
hello
```
I'll first enquire whether the JVM behavior is by design. If yes, I think we should adjust our behavior to match the JVM, even though it doesn't make much sense to me.

**Comment by japgolly** [comment]
Awesome, thank you @sjrd !

**Comment by sjrd** [comment]
I filed the inconsistency upstream as https://github.com/scala/bug/issues/11975. lryts says it's probably an oversight, so Scala.js is doing the right thing according to him.

**Comment by japgolly** [comment]
Cool, thanks @sjrd. So you're comfortable and happy with the change that `args: Array[String]` needs to be specified in the 1.0 world?

**Comment by sjrd** [comment]
> So you're comfortable and happy with the change that `args: Array[String]` needs to be specified in the 1.0 world?

Yes, this was an intentional change we made to get closer to the JVM.

**Comment by japgolly** [comment]
Ok in that case I'll close this issue here. Thanks as always!
