### ISSUE TITLE
Incorrect handling of negative 0

### ISSUE THREAD

**Issue by MaximeKjaer** [scala-js/scala-js#4034]
The following snippet produces different results on Scala.js and on the JVM:

```scala
val float = 0.0f
println(String.format("%.1f", -float))     // prints 0.0 on Scala.js, -0.0 on JVM
println(String.format("%.1f", -1 * float)) // prints -0.0 on both Scala.js and JVM
```

From the JS output, it looks like the first print is being constant folded incorrectly to `0.0` instead of `-0.0` in Scala.js. The second print is being constant folded correctly to `-0.0`:

```js
this$9.java$lang$JSConsoleBasedPrintStream$$printString__T__V((x$1 + "\n"));
const args$1 = $makeNativeArrayWrapper($d_O.getArrayOf(), [0.0]);
const x$2 = $m_jl_String$().format__T__AO__T("%.1f", args$1);
const this$11 = $m_s_Console$();
const this$12 = this$11.out__Ljava_io_PrintStream();
this$12.java$lang$JSConsoleBasedPrintStream$$printString__T__V((x$2 + "\n"));
const args$2 = $makeNativeArrayWrapper($d_O.getArrayOf(), [(-0)]);
const x$3 = $m_jl_String$().format__T__AO__T("%.1f", args$2);
```

I can try to prevent constant folding from taking place by placing the negation in a function:

```scala
def negate1(x: Float): Float = -x
def negate2(x: Float): Float = -1 * x
```

However, this also results in an incorrect translation. Both `-x` and `-1 * x` are translated to `Math.fround(0.0 - x)`, which produces an incorrect result when `x` is `0.0`.

```js
const $p_Lcom_test_Test__negate1$1__F__F = (function($thiz, x) {
  return $fround((0.0 - x))
});
const $p_Lcom_test_Test__negate2$1__F__F = (function($thiz, x) {
  return $fround((0.0 - x))
});
```

I am using Scala.js 1.0.1 on Scala 2.13.2.

**Comment by sjrd** [comment]
Fixed in 40e323accec22f0911a05876ceda4ae67fa66aef.
