### ISSUE TITLE
Put timeouts on TestAdapter await calls?

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#4059]
Awaiting indefinitely (current state) can cause things like: #4054. Putting a timeout on `await` calls will at least fail instead of hang.

Timeouts would probably need to be structured in:
- Timeouts depending on test execution (long).
- Timeouts not depending on test execution (short).

**Comment by gzm0** [comment]
Personally, I think there is little value to this. Reasons:

- Although there is a failure, it is not really more meaningful.
- In interactive execution, humans are better at "choosing" an appropriate timeout: It times out when "it hangs".
- In CI execution, a higher, overall timeout is needed anyways and probably more appropriate.

@sjrd WDYT?

**Comment by sjrd** [comment]
Yeah ... I agree that human/CI timeouts are better at handling these kinds of issues. Shorter timeouts built in the system tend to be flaky/inappropriate.
