### ISSUE TITLE
Extract the jsEnvs projects in a separate repo

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#4078]
I'd like to propose that we extract the jsEnvs projects (`jsEnvs`, `jsEnvsTestKit` and `nodeJSEnv`) in a separate repo, with its own release schedule.

## Technical feasability

* Those three projects are JVM-only projects (and with no hope of making them cross-compile, since we settled on keeping some synchronous APIs such as `InputStream`s)
* With the exception of `logging` (which I'll come back to below), they do not depend on anything else in the repo, neither for compiling nor testing (they have their own isolated tests)
* Their APIs are likely to stay *very* stable in the long term, without much change

### The problem of `logging`

The dependency on `logging` is problematic, because `logging` is a cross-project, so even though `jsEnvs` only depends on its JVM artifact, the `logging` sources must stay in the Scala.js repo. If I had noticed this before 1.0.0, I would have advocated for *duplicating* the very small API of `logging` in `linker` and `jsEnvs`. Of course we cannot do that anymore. However, what we can do is:

* Move the `logging` cross-project in a repo of its own, depending statically on Scala.js 1.1.0 forever.
* Publish it as 1.1.1 as is, independently of the rest of Scala.js, and probably it will stay at 1.1.1 forever.
* If we ever go to Scala.js 2.x, then re-source-in `logging` into scala-js/scala-js, as an integral part of `linker` (we would be able to do that then, because breakage would be allowed); the existence of this scenario means that it's not a blocker for moving to 2.x at some point.

What can go wrong? The only bad scenario I can think of is what happens when we have to support a new major version of Scala itself, such as 2.14 if it ever happens? We would have to publish logging_2.14 before we can use it in Scala.js' linker, but we'd have to publish a new version of Scala.js supporting 2.14 to be able to do that because logging is a cross-project. It is a bit circular, but we can break the circularity by publishing a version of Scala.js that can only compile Scala 2.14 code, but without publishing the linker itself for 2.14. We had been doing that for a long time in the 2.13 cycle, so we have precedent.

Alternatively, since 2.14 would be a different binary ecosystem anyway, we *could* duplicate logging into `linker` when moving to 2.14.

## Why do that

There are a few reasons:

* With the `MultiScalaProject`s, our build has now *a lot* of projects, hence *a lot* of settings. It takes a very noticeable and *annoying* time to load sbt now. I am looking for ways to reduce the number of projects/settings that our build contains. Getting rid of 5 `MultiScalaProject`s (loggingJVM, loggingJS, jsEnvs, jsEnvsTestKit and nodeJSEnv), i.e., 5x3 = 15 `Project`s, would be really nice.
* Other `JSEnvs` are in their own repos, with basically frozen (or very slowly-moving) code and versions. Some people wonder why they are not republished for newer versions of Scala.js although Node.js is.
* With the build sourcing in `jsEnvs`, it is now impossible to temporarily add an existing third-party JSEnv in the Scala.js build (for local testing purposes) because the classloader hierarchy that sbt spawns is such that things break. If `JSEnv` itself is in a third-party published artifact that we can just depend on in `project/build.sbt`, this will work.

@gzm0 WDYT?

**Comment by sjrd** [comment]
Building on your idea, but avoiding most gotchas, here is another possibility: publish loggingJS from a project in scala-js/scala-js, with same sources as loggingJVM, but using the same versioning as the rest of Scala.js. That way, it stays as a regular project within this repo, and we don't have to jump through zillions of hoops to give it a different versioning scheme.

We could even integrate the sources directly in `linkerJS`, getting rid of `loggingJS` altogether. It is highly unlikely that anyone would depend on scalajs-logging_sjs1 other than through scalajs-linker_sjs1, so that's probably safe.

**Comment by gzm0** [comment]
That would be the example where the JS version has a different version that the JVM version, right? Or would we simply give it a different artifact ID?

> We could even integrate the sources directly in linkerJS, getting rid of loggingJS altogether.

That might be the best option, yes. No weirdo circular dependencies, no ability for anything else in JS land to depend on `logging` so for any usage I can think of, it'll "just work".

**Comment by sjrd** [comment]
> That would be the example where the JS version has a different version that the JVM version, right? Or would we simply give it a different artifact ID?

Yes, that's right.

> > We could even integrate the sources directly in linkerJS, getting rid of loggingJS altogether.
> 
> That might be the best option, yes. No weirdo circular dependencies, no ability for anything else in JS land to depend on `logging` so for any usage I can think of, it'll "just work".

OK, let's try that, then.

**Comment by sjrd** [comment]
Done in the new repos https://github.com/scala-js/scala-js-logging and https://github.com/scala-js/scala-js-js-envs along with the PR #4083.
