### ISSUE TITLE
Invalid  top-level export name with scala-js 1.0

### ISSUE THREAD

**Issue by mathieuleclaire** [scala-js/scala-js#4080]
The following instructions with scalajs 1.1.0:
```scala
JSExportTopLevel("org.openmole.gui.plugin.authentication.sshlogin.LoginAuthenticationFactory")
```

raises this exception:

```The top-level export name must be a valid JavaScript identifier name```

I didn't have this exception with 0.6.xx and this naming does not seem to break the javascript variable naming rules.

**Comment by sjrd** [comment]
Namespaced exports were deprecated in 0.6.26 and removed in 1.x. See [the release notes of 0.6.26](https://www.scala-js.org/news/2018/11/29/announcing-scalajs-0.6.26/) for how to achieve the same effect differently.
