### ISSUE TITLE
Scala.js adds the ExposedJSMember annotation to NoSymbol

### ISSUE THREAD

**Issue by retronym** [scala-js/scala-js#4089]
As seen in https://github.com/sbt/zinc/issues/718#issuecomment-645841132 and worked around in Zinc in https://github.com/sbt/zinc/pull/798.

Calls to `sym.addAnnnotation` should be guarded with `sym != NoSymbol`. Ideally the compiler would drop the added annotations or give a hard error, but right now it leaves all this up to the caller.

**Comment by sjrd** [comment]
Ouch. That's terrible. :( Thanks for the report!

It might already be fixed in master because of #4056. I will investigate.

**Comment by sjrd** [comment]
Apparently this bug has been there since the very beginning:
https://github.com/scala-js/scala-js/blob/81c3cad759dfe0d03beba9adc4f7451a00a73439/compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala#L486-L494
part of 81c3cad759dfe0d03beba9adc4f7451a00a73439, the commit that added Scala.js-defined JS classes in the first place in v0.6.5. At that time, the latest Scala version we had [in our CI was 2.12.0-M2](https://github.com/scala-js/scala-js/blob/81c3cad759dfe0d03beba9adc4f7451a00a73439/ci/matrix.xml#L312-L315). Not sure whether the `fields` phase was already there in M2.

**Comment by retronym** [comment]
Another edge cases for `Symbol.accessed`

The accessed field of an accessor can be in a superclass (perhaps separately compiled) when parameter aliasing elides a field:

```
scala> val D_a = typeOf[C].decl(TermName("a"))
D_a: $r.intp.global.Symbol = value a

scala> assert(D_a.isAccessor); D_a.accessed.owner
res10: $r.intp.global.Symbol = class C
```

You might want to restrict addition of annotation to fields in the same class as the owner.

**Comment by sjrd** [comment]
Hum, but if I continue your example, `D_a` itself is already in `C`:
```scala
scala> D_a.owner
val res6: $r.intp.global.Symbol = class C
```
So we wouldn't encounter it, would we?

**Comment by sjrd** [comment]
Oh there was a typo in your example. It was looking up `a` in `typeOf[C]` instead of `typeOf[D]`. With that fixed, it seems that `D.a` is in fact *not* an accessor:
```scala
scala> val D_a = typeOf[D].decl(TermName("a"))
val D_a: $r.intp.global.Symbol = value a

scala> D_a.owner
val res7: $r.intp.global.Symbol = class D

scala> assert(D_a.isAccessor); D_a.accessed.owner
       ^
       warning: method assert in class SymbolTable is deprecated (since 2.12.5): consider supplying an explanatory message
java.lang.AssertionError: assertion failed:

     while compiling: <synthetic>
        during phase: globalPhase=terminal, enteringPhase=typer
     library version: version 2.13.2
    compiler version: version 2.13.2
  reconstructed args: -deprecation -feature -Wconf:cat=feature:w -Wconf:cat=deprecation:w -Wconf:cat=deprecation:ws -Wconf:cat=feature:ws -Wconf:cat=optimizer:ws

  last tree to typer: TypeTree(class Byte)
       tree position: line 5 of <synthetic>
            tree tpe: Byte
              symbol: (final abstract) class Byte in package scala
   symbol definition: final abstract class Byte extends AnyVal (a ClassSymbol)
      symbol package: scala
       symbol owners: class Byte
           call site: constructor $eval in object $eval in package $line43

== Source file context for tree position ==

     2 package $line43 {
     3 object $eval {
     4   lazy val $result = res8
     5   lazy val $print: _root_.java.lang.String = $r.phased.atCurrent {
     6     $iw
     7
     8 val sb = new _root_.scala.StringBuilder
  at scala.reflect.internal.SymbolTable.throwAssertionError(SymbolTable.scala:170)
  at scala.reflect.internal.SymbolTable.assert(SymbolTable.scala:156)
  ... 42 elided

scala> D_a.isAccessor
val res9: Boolean = false

scala> D_a.isPrivate
val res10: Boolean = true
```
not to mention it is private, so `shouldBeExposed` will return `false`.
