### ISSUE TITLE
"Parse error.  'identifier' expected" in fullOptJS on Scala.js 1.x

### ISSUE THREAD

**Issue by exoego** [scala-js/scala-js#4099]
This is a bug report.

## How to repro

```
git clone -b jsc-parse-error-with-macro https://github.com/exoego/scalajs1-errors.git
cd scalajs1-errors
sbt fullOptJS
```

## Background

In JS, it is relatively common to pass plain JS object to method.
To construct such JS objects in highly-optimized way, I am defining factory method like:

```scala
trait FooConfig extends js.Object {
  var a: String
  var b: Int
  var c: js.UndefOr[Boolean]
  var d: js.UndefOr[FooConfig.Bar]
}

object FooConfig {
  type Bar = js.Array[String | Int]

  def apply(a: String, b: Int, c: js.UndefOr[Boolean] = js.undefined, d: js.UndefOr[FooConfig.Bar] = js.undefined): FooConfig = {
     val _obj = js.Object.literal(
       "a" -> a.asInstanceOf[js.Any],
       "b" -> b.asInstanceOf[js.Any]
     )
     c.foreach(v => _obj.updateDynamic("c")(v.asInstanceOf[js.Any]))
     d.foreach(v => _obj.updateDynamic("d")(v.asInstanceOf[js.Any]))
     c.asInstanceOf[FooConfig]
  }
}
```

In the above, `FooConfig.apply` is type-safe factory method and generates highly optimized JS code (in terms of runtime  memory and speed).
However, this pattern bloat codebases and error-prone (if manually coded).

So, I am making [`@Factory` macro to reduce this boilerplate](https://github.com/exoego/scalajs-types-util/blob/cd7f10d7e751561b5dca7ee7903b2848fe706a7b/macros/src/main/scala/net/exoego/scalajs/types/util/Factory.scala
).
The below code with macro is identical to the above code without macro.

```scala
@Factory // THIS
trait FooConfig extends js.Object {
  var a: String
  var b: Int
  var c: js.UndefOr[Boolean]
  var d: js.UndefOr[FooConfig.Bar]
}

object FooConfig {
  type Bar = js.Array[String | Int]
}
```

## Actual behavior

On some of my Scala.js 1.1.0 project, `compile` and `fastOptJS` completed successfully, but `fullOptJS` failed with the following error:

```
[info] Full optimizing /home/vagrant/IdeaProjects/aws-lambda-scalajs-facade/target/scala-2.13/aws-lambda-scalajs-facade-opt.js
[error] JSC_PARSE_ERROR. Parse error. 'identifier' expected at ScalaJSExportExterns.js line 3 : 4
[error] Closure: 1 error(s), 0 warning(s)
[error] There were errors when applying the Google Closure Compiler
[error] (Compile / fullOptJS) There were errors when applying the Google Closure Compiler
[error] Total time: 20 s, completed 2020/06/22 11:54:55
```

## Expected behavior

`full-opt`-ed JS should be generated without error.

Or, if user (me) doing something wrong, Scala.js should provide more actionable error message.
For this error, I can not debug via generated-JS file, since JS file is not generated..

**Comment by sjrd** [comment]
Thanks for the report. This is the same error as #4061, but this time reported by Closure instead of by the JS engine. On master the reproduction produces a linking error:

> [error] Invalid top level export for name '`default`' in class `scala.meta.parsers.JSFacade$` when emitting a Script (NoModule) because it is not a valid JavaScript identifier (did you want to emit a module instead?)

Adding the following setting in the reproduction's `build.sbt` fixes the error:
```scala
scalaJSLinkerConfig ~= (_.withModuleKind(ModuleKind.CommonJSModule))
```
More generally, I think that if scala.meta.parsers is intended to be used as a Scala.js library, it should not export anything to the top-level, and *especially not* as default export. (Instead there could be separate module with just the `@JSExportTopLevel`s, for consumption as a JavaScript library.)

**Comment by exoego** [comment]
Thanks, that fixed the issue.
