### ISSUE TITLE
Implement java.util.concurrent.Semaphore and use it in IOThrottler

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#4102]
This is a follow-up to #4097 where we used an `AtomicInteger` as a poor-mans replacement for a `Semaphore` with `tryAcquire` (or maybe even `drainPermits`).

**Comment by hepin1989** [comment]
Better implement AQS first？

**Comment by gzm0** [comment]
What's AQS?

**Comment by hepin1989** [comment]
@gzm0 AbstractQueuedSynchronizer

**Comment by sjrd** [comment]
And why would we need this `AbstractQueuedSynchronizer` before implementing `Semaphore`? `Semaphore`'s API doesn't mention that class, so there is no dependency.
