### ISSUE TITLE
Surprisingly slow on GraalVM vs OpenJDK

### ISSUE THREAD

**Issue by djspiewak** [scala-js/scala-js#4121]
I have the least-minimized bug of all time for you. I'm going to *try* to minimize it at some point, but I wanted to file it here just to get it on your radar somewhere so you know it exists.

For some reason, some ScalaJS code takes an incredibly long time to *run* when the system JVM is GraalVM (20.1.0 CE, target 1.8, to be precise). To be very clear, I'm not running the *javascript* on GraalVM, I'm just running sbt. To be even more clear, it's the *running* of the generated javascript which is slow, not the compilation. No, it doesn't make any sense.

https://github.com/djspiewak/cats-effect/tree/bug/scalajs-weirdness

There's a tag where the problem is exhibited. Run `sbt 'testOnly *PureConcSpec'`. When running under GraalVM, it takes about 90-120 seconds to complete. When running under OpenJDK, it's closer to 15 seconds. This is part of why it's so weird: the disparity is *massive*. Also this happens in the `ubuntu-latest` runner in GitHub Actions as well, so it isn't just my laptop.

```
~/.../Scala/cats-effect (ce3) λ java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 25.252-b09-jvmci-20.1-b02, mixed mode)
~/.../Scala/cats-effect (ce3) λ node --version
v14.5.0
```

Oh, and if that wasn't weird enough, `ClockSpec` in that same project *also* exhibits the same disparity, but `IOSpec` does not. So it's like… very much not consistent.

I apologize for how completely unminimized this is.

**Comment by plokhotnyuk** [comment]
+1 https://github.com/oracle/graal/issues/2452

**Comment by sjrd** [comment]
This is a known issue and 100% Graal's fault. When a JVM running on Graal spawns a process named `node`, it chooses GraalJS' version of `node` over the system one. And GraalJS is *terrible* performance wise on startup.

There is no valid reason for Graal to impose its version of `node`. It shouldn't do that. Please report it to them that they should stop doing that because it's terrible.

**Comment by djspiewak** [comment]
@sjrd That… is… one of the worst things I've ever heard in my whole life. Seriously wtf.

**Comment by japgolly** [comment]
@sjrd Has an issue been raised that you know of regarding that crazy behaviour? If not I'll raise one, if so I'll pile on a bit :)

**Comment by japgolly** [comment]
@djspiewak They also install their own identically-named `node`, `npm` etc in `$JAVA_HOME/bin` so you have to be really careful about your `$PATH` ordering. I can't tell if its arrogance or thoughtlessness.

**Comment by djspiewak** [comment]
Hmm, I'm using `nvm`, so that's definitely not *how* this is getting intercepted. But yeah, that's also a good point.

**Comment by sjrd** [comment]
> @sjrd Has an issue been raised that you know of regarding that crazy behaviour? If not I'll raise one, if so I'll pile on a bit :)

AFAIK there's no report for that yet, although it might exist and I'm just not aware.

**Comment by shelajev** [comment]
> This is a known issue and 100% Graal's fault. When a JVM running on Graal spawns a process named `node`, it chooses GraalJS' version of `node` over the system one. And GraalJS is _terrible_ performance wise on startup.
> 
> There is no valid reason for Graal to impose its version of `node`. It shouldn't do that. Please report it to them that they should stop doing that because it's terrible.

Can you reproduce this? Can you share a reproducer example? 
Because I tried and I cannot reproduce: https://www.youtube.com/watch?v=MKkyrilQ_Z0

If system node is in the `$PATH` before node in the graalvm distribution, that's the node that gets to run. 
If no node is in the `$PATH` (neither GraalVM is on the path, nor any other node), I get an IOException: 
```
Exception in thread "main" java.io.IOException: Cannot run program "node": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at Main.main(Main.java:6)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 4 more
``` 

Not with `Runtime.getRuntime().exec()`, not with `ProcessBuilder`.

**Comment by sjrd** [comment]
@shelajev I've never tried myself; I only saw several reports on our Gitter channel about this behavior in the past few months. Perhaps @djspiewak has a repro.

**Comment by djspiewak** [comment]
I've been able to reproduce it using the Cats Effect **ce3** build (as linked above) in GitHub Actions, as well as locally on my laptop. Both are using NVM, and I've verified that, at least on my laptop, the Graal home `bin/` isn't on the PATH at all, so that can't be what's intercepting things. Is there a clean way to detect from *inside* `node` which runtime it's on? I'm currently just going off of the performance, which is lightyears worse when running under Graal.

**Comment by cquiroz** [comment]
I noted this behavior long ago in the context of bundling an app using scalajs-bundler. My workaround is to delete node and npm from Graal's
bin dir

**Comment by shelajev** [comment]
I think you can run `https://nodejs.org/docs/v0.10.12/api/process.html#process_process_execpath`, like: `console.log(process.execPath)` or maybe `process.version` could be a thing to print. 

Maybe if you can include something like the following logging: 

```
const child_process = require('child_process');

console.log("Process path = " + process.execPath);
console.log("Version = " + process.version);
console.log("cwd = " + process.cwd());
console.log("PATH = " + process.env.PATH);

child_process.execSync('which node', {stdio: [0,1,2]});
```
This will print -- absolute path to `node` executable currently running, the version (just to be sure), the current working dir, the `$PATH` and the result of executing a `which node` subprocess.

**Comment by djspiewak** [comment]
@sjrd @shelajev I ran `console.log(process.execPath)` within the following contexts:

- `node -e` from a fresh shell
- Ammonite `"node -e ...".!!` from the same shell
- Embedded within a `scala.scalajs.js.eval` statement in one of my tests which *doesn't* appear massively slower on Graal
- Embedded within a `scala.scalajs.js.eval` statement in one of my tests which *does* appear slower

`java -version` results on each:

```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 25.252-b09-jvmci-20.1-b02, mixed mode)
```

The results of the process on each were identical: `~/.nvm/versions/node/v10.5.0/bin/node` This almost definitively proves that the initial conclusion was in err: **Graal isn't redirecting anything.** I'll be noting that on my tweet thread.

This *does* still leave open the mystery of why we see such radical performance differences, but I have a theory there… First off, it's very possible that Graal somehow ends up ahead of NVM on the GitHub Actions runner path. That's testable, though I don't have time to go through those shenanigans right now. If that's the case, then Graal would indeed be intercepting `node` on GitHub Actions runs, but only due to the fact that its version of `node` (and `npm`) are first on the `PATH`. I still would prefer they didn't ship a `node`, but… this isn't really dodgy, just not what I would do.

Regarding my laptop… I went back and tried to reproduce the performance difference between VMs and wasn't able to. I do all my development on Graal and the performance was still *bad*, but as it turns out, `node` run from OpenJDK is just as bad now. It's very possible that I changed something weird in the implementation which caused the problem locally.

At any rate, at this point, I'm relatively certain that Sebastian's initial understanding ("When a JVM running on Graal spawns a process named node, it chooses GraalJS' version of node over the system one.") is in err. I think it's still worth digging into the GitHub Actions situation a little more closely, and I'll do that, but at the very least I'm not able to reproduce that symptom on my laptop.

I apologize for my misunderstanding.

**Comment by gzm0** [comment]
Note that while running tests, the JVM is still doing a lot (notably see #3123). The bottom line there is that more context switching alone can cause 60% longer execution time (clearly not as much as what you observe, but still).

Could you observe the slowdown while using `sbt run`?

**Comment by djspiewak** [comment]
> Could you observe the slowdown while using sbt run?

Good question. And possibly. I have nothing runnable in those projects. I feel like we would need something more minimal than Cats Effect in order to really experiment.
