### ISSUE TITLE
RPCCore$RPCException: UTFDataFormatException: encoded string too long

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#4127]
I'm trying to run my Scala.js tests and something is failing but the jsenv is only providing me with this:

```
[error] stack trace is suppressed; run last Test / executeTests for the full output
[error] (Test / executeTests) org.scalajs.testing.common.RPCCore$RPCException: java.io.UTFDataFormatException: encoded string too long: 65816 bytes
```

This error message doesn't help me at all. I really need to see what the test failure was. I'm in a position now where I have no idea which test is failing, let alone why.

I believe this is due to some limit in the WebSocket spec when you close a connection with a message right? Could you please, please, please either
1. send a message with the full error msg in it before closing, or
2. send a truncated message back so I can at least see the bulk of the error.

Thanks!!

**Comment by gzm0** [comment]
Dupe of #3667?

**Comment by japgolly** [comment]
Ah my bad. I'll close this one.
