### ISSUE TITLE
getTime on java.util.Date returns 0 when initialized with a value outside the ECMAScript Time Range

### ISSUE THREAD

**Issue by sbrunk** [scala-js/scala-js#4131]
Taken from #4130 which has exposed this behaviour, but is otherwise orthogonal.

```scala
println(new java.util.Date(8640000000000000L).getTime) // 8640000000000000 both JVM and JS
println(new java.util.Date(8640000000000001L).getTime) // 8640000000000001 on the JVM, 0 on JS
```

`js.Date` objects have a valid time range of ±8.64E15 as defined in [ECMAScript Time Values and Time Range](https://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.1). `js.Date` objects given a value outside of that range are an *invalid date* and calling getTime() on such an instance returns `NaN`.

Since the `java.util.Date` implementation of Scala.js is based on a `js.Date` internally, instantiating `Date` with a value `> 8640000000000000L` (or `< -8640000000000000L` will result in the backing `js.Date` instance being `NaN`. That in turn results in the `java.util.Date` instance being 0 (the Unix Epoch), because `getTime()` converts `NaN` to a `Long` and `Double.NaN.toLong == 0`.

https://github.com/scala-js/scala-js/blob/a4e7c455c29448de48c394865217a22dbd7a1a4a/javalib/src/main/scala/java/util/Date.scala#L85

So we get

`x <= 8640000000000000L // OK`
`x >  8640000000000000L   // getTime() always returns 0`

Analogous for negative values.

Tested on Scala 2.12.11/Scala.js master and 1.1.1

As `java.util.Date` seems to be backed by a `Long` on the JVM there's obviously no range check required when calling `new Date(date: Long)`.
Because the semantics is different on JS though, I'd argue that it could make sense to throw an `IllegalArgumentException` on the `Date` constructor if the timestamp is out of range.

**Comment by gzm0** [comment]
From what I can see, `ju.Date` only needs `js.Date` for its deprecated APIs (and `toString`). We shouldn't remove the deprecated APIs, but we could change the underlying representation to `Long` and only indirect via `js.Date` if necessary.

Further, we should probably make the deprecated APIs throw if the `Long` is out of range (and come up with a dummy `toString`, no throwing there IMO).

**Comment by sjrd** [comment]
That seems like a reasonable approach to fix most issues in a short time, indeed.
