### ISSUE TITLE
Export inner objects in Scala classes

### ISSUE THREAD

**Issue by swachter** [scala-js/scala-js#4142]
In the following example the `innerObj` field is not set, i.e. `new ClassWithInnerObj().innerObj` is undefined:

```
@JSExportTopLevel("ClassWithInnerObj")
@JSExportAll
class ClassWithInnerObj {
  val x = 1
  object innerObj extends js.Object {
    val y = 2
  }
}
```

The generated code contains only an assignment of `null` to the field. No other references exist in the generated code:

```
   this.LClassWithInnerObj__f_innerObj$module = null;
```

**Comment by sjrd** [comment]
Thanks for opening the issue. Could you also post here what happens when adding `@JSExport` directly on `object innerObj`, because that would be the root cause. `@JSExportAll` is merely a shortcut for many `@JSExport`s.

**Comment by swachter** [comment]
The compiler complains `@JSExport is forbidden on objects and classes.`

**Comment by sjrd** [comment]
As a workaround, it's possible to export a getter for the object instead:
```scala
class ClassWithInnerObj {
  val x = 1

  @JSExport
  def innerObj: innerObjInternal.type = innerObjInternal

  object innerObjInternal extends js.Object {
    val y = 2
  }
}
```

**Comment by swachter** [comment]
Thanks for the workaround. I use it in the adapter code generation of the ScalaTsPlugin. After this is fixed I would like to get rid of the workaround because causes now two members to be created in the TypeScript declaration file. There is the danger to access the 'object field' directly instead of the assigned value.
