### ISSUE TITLE
Assigning js.undefined to a type alias to js.UndefOr does not compile

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#4143]
```scala
import scala.scalajs.js.|
import scala.scalajs.js
type Foo = Int | String
type FooOpt = js.UndefOr[Foo]
val foo: js.UndefOr[Foo] = js.undefined // Works
val foo2: FooOpt = js.undefined // Doesn't work: "Expected `Nothing | Unit`,  got `Int | String | Unit`"
```

Unclear if we can do anything about this, but opening this so we have a centralized discussion point.

**Comment by frobinet** [comment]
Note that the following is valid
```
val foo: FooOpt = () 
```
Is there a reason why `js.undefined` can't just be `()`?

**Comment by gzm0** [comment]
Well, it is: https://github.com/scala-js/scala-js/blob/v1.1.1/library/src/main/scala/scala/scalajs/js/package.scala#L87-L89

It's just that it's ascribed to as `js.UndefOr[Nothing]`. Maybe we should change that.

**Comment by frobinet** [comment]
Sure, but I meant the actual type explicitly being `Unit`. 

Maybe it would cause issues with something like `js.UndefOr[Unit]` but we already have no way to distinguish that from `Unit` since `js.isUndefined(()) == true`.

**Comment by gzm0** [comment]
Yes, I think it makes sense to change the type to `Unit`. @sjrd?

**Comment by gzm0** [comment]
For context: I suspect this is an artifact from the time where `js.UndefOr` was it's own thing. Then it made sense to have this return type because it would *help* type inference.

**Comment by frobinet** [comment]
Actually, this wouldn't solve the root of the problem, which is related to `Nothing`: 
```
val x: Nothing | Int = 42 // Doesn't compile
```

**Comment by frobinet** [comment]
For some reason, Nothing causes issues with the implicit resolutions, so special casing it might help. The following works:

```scala
import scala.scalajs.js.|
import scala.scalajs.js
import scala.language.implicitConversions

implicit def fromNothingLeft[A](a: A): Nothing | A = a.asInstanceOf[Nothing | A] // A <: Nothing | A
implicit def fromNothingRight[A](a: A):  A | Nothing = a.asInstanceOf[A | Nothing] // A <: A | Nothing
implicit def reverseNothing[A](a: Nothing | A): A = a.asInstanceOf[A] // (Nothing | A) <: A, (A | Nothing) <: A not required
implicit def nothingTransitivity[A,B1,B2](a: Nothing | B1)(implicit ev: |.Evidence[B1,B2]): A | B2 = a.asInstanceOf[B2]

class A
class B

// Basic checks
def aOrB: A | B = new A
def aOrB2: A | B = new B
def bOrA: B | A = new A
def bOrA2: B | A = new B

// These are always good since Nothing <: A for any A
def nothingUnion: Nothing | Nothing = ??? // Nothing <: (Nothing | Nothing), just a check, doesn't need any implicit
def left2: Nothing | A = ??? // Nothing <: Nothing | A
def right2: A | Nothing = ??? // Nothing <: A | Nothing

// Nothing checks
val left: Nothing | A = new A // A <: Nothing | A
val right:  A | Nothing = new A // A <: A | Nothing
def reverseNothing: Nothing = nothingUnion // (Nothing | Nothing) <: Nothing
def doubleReverseNothing: Nothing | Nothing | Nothing = nothingUnion 

// js.undefined checks
type AOpt = js.UndefOr[A] // No need to change definition of `js.UndefOr`, but it might still be good to do so
val x: AOpt = js.undefined
```

I haven't tried putting the implicits in the scope of `js.|`, they might conflict with existing ones, and there might be cases not covered by them.

**Comment by sjrd** [comment]
> Yes, I think it makes sense to change the type to `Unit`. @sjrd?

We can't, because it would break "optional" members of non-native JS traits, i.e., ones with `= js.undefined`.

**Comment by frobinet** [comment]
Fixing all the issues with `|` inference and `Nothing` seemed like overkill, so I just fixed the one relevant to `js.undefined` which is most likely to bother people and only requires one more implicit conversion.

**Comment by sjrd** [comment]
I believe it would be worth creating a reproduction independent of Scala.js, and report it to Scala/JVM instead. AFAICT there is no reason for the implicit resolution to fail in the original scenario. Fixing it there upstream has the highest chance not to break zillions of other things.

**Comment by gzm0** [comment]
I propose to close this (and the related PR) as wontfix & upstream. Any objections?

/cc @frobinet

**Comment by sjrd** [comment]
No objection from me.

**Comment by frobinet** [comment]
Sure. I haven't had the bandwidth to reproduce and submit this issue to Scala/JVM, but closing it here is legitimate. I'll reference this issue if I ever get to reporting to Scala/JVM.
