### ISSUE TITLE
Very Long String in source results in cryptic error message. 

### ISSUE THREAD

**Issue by domaspoliakas** [scala-js/scala-js#4151]
Hello

When you have a very long string in the scala source, scala.js produces a very cryptic error message:

```
sbt:long-string> withSjs/compile
[info] Compiling 2 Scala sources to /home/dpoliakas/Dev/personal/long-string/withSjs/target/scala-2.13/classes ...
[error] encoded string too long: 525213 bytes
[error] one error found
[error] (withSjs / Compile / compileIncremental) Compilation failed
[error] Total time: 0 s, completed 18 Aug 2020, 11:12:18
```

The same error without scalajs produces a slightly better error message 

```
sbt:long-string> noSjs/compile
[info] Compiling 2 Scala sources to /home/dpoliakas/Dev/personal/long-string/noSjs/target/scala-2.13/classes ...
[error] Error while emitting example/Main$
[error] UTF8 string too large
[error] one error found
[error] (noSjs / Compile / compileIncremental) Compilation failed
[error] Total time: 0 s, completed 18 Aug 2020, 11:12:11
```

Minimal reproduction https://github.com/disblader/long-string

While this is not a big problem per se, it can definitely lead one on a wild goose chase. It would be good if this could be improved.

**Comment by sjrd** [comment]
Thanks for filing the issue :)

**Comment by gzm0** [comment]
So I understand correctly that the best we can do here is improve the error message, right? If so, should we do this upstream?

**Comment by sjrd** [comment]
Yes, we can only improve the error message.

Even if we do it upstream, apparently this error comes from the back-end, so the Scala.js back-end kicks in first and issues its own (worse) message, preventing the JVM back-end to run and issue its (better) message.
