### ISSUE TITLE
SecureRandom in Scala.js library

### ISSUE THREAD

**Issue by exoego** [scala-js/scala-js#4166]
I would like to implement `java.security.SecureRandom` as CSPRNG (cryptographically strong pseudo RNG), in Scala.js library.
Because CSPRNG is sometimes wanted e.g. when generating UUID/UULD or such purpose.
(Current Scala.js's `java.util.UUID` uses `Random` instead of `SecureRandom`).

I think the recent JS runtime potentially allow us to implement SecureRandom, since those offer API for CSPRNG:

* For web browsers, [Crypto.getRandomValues](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues)
* For Node.js, [crypto.randomFillSync](https://nodejs.org/dist/latest-v14.x/docs/api/crypto.html#crypto_crypto_randomfillsync_buffer_offset_size)

But I have several question so opinions from Scala.js core developers/users are appreciated.
 
## Q1. How should `seed` be handled?

IIUC, the above mentiond JS's CSPRNG APIs do not accept seed.

The easiest way is not to support `SecureRandom(seed)` constructor and `setSeed(seed)` method.

Other idea is to use the above CSPRNG only for setting initial seed, and delegate the seed to `Random` instance.
However, I do not know that the strong seed + current `Random` implementation is cryptographically strong...

## Q2. How should implementation switches between browsers and Node.js ?

Unfortunately, CSPRNG API differs between web browsers and Node.js, so it is required to switch implementation based on API availability.

To detect web browser's API, it is easy to use `js.Dynamic.global`.
However, IIUC, to detect/use Node.js API, it is required to use `@JSImport`.
But using `@JSImport` requires module support, which is disabled for Scala.js library.
I do not have idea how to detect and use Node.js API without module support.

----

If it is not appropriate to implement SecureRandom in Scala.js repository, I will create a separate repo.

**Comment by sjrd** [comment]
Having an implementation for browsers and for Node.js is not enough. Scala.js works in any ECMAScript 5.1/2015 compliant engine, and is actually used in esoteric environments.

So this should not go in the main repo, but feel free to implement it in a separate repository.

**Comment by sjrd** [comment]
To answer some of your questions anyway:

> But using `@JSImport` requires module support, which is disabled for Scala.js library.
I do not have idea how to detect and use Node.js API without module support.

In Scala.js 1.x you can use a type test on `js.Dynamic.global.require` and then use that if it's not `"undefined"`.

> However, I do not know that the strong seed + current Random implementation is cryptographically strong...

No idea, I'm not a security expert. However I know enough not to trust my own knowledge of crypto ever, and therefore never to come up with my own scheme. Always staying true to what the actual experts invented is the only safe thing to do.

**Comment by exoego** [comment]
Thanks. 
I will work in a separate repo.
