### ISSUE TITLE
Make js.Promise.then to return js.Promise instead of js.Thenable

### ISSUE THREAD

**Issue by unarist** [scala-js/scala-js#4188]
Currently, `js.Promise[T].then` is typed as it returns `js.Thenable[T]`.

https://github.com/scala-js/scala-js/blob/50ba45c1ed08dbd0c1e30ab80aed3fc27c722779/library/src/main/scala/scala/scalajs/js/Promise.scala#L49-L55

but I think `then` method of Promises returns Promise (unless prototype is modified).

Changing return type to Promise would allows `js.Promise(...).then(...).catch(...)` which can't be compiled for now.

**Comment by gzm0** [comment]
Thank you for filing this. Reading MDN, it seems pretty clear that these methods return indeed new promises. I haven't read through the standard though.
