### ISSUE TITLE
Typeof check output on DottyJS is incorrect

### ISSUE THREAD

**Issue by djspiewak** [scala-js/scala-js#4194]
Discovered this as part of trying to port Cats Effect 3's build to DottyJS on 0.27.0-RC1 (SJS 1.2.0). Rough minimization:

```scala
if (js.typeOf(js.Dynamic.global.setImmediate) == Undefined) {
```

(this is part of `PolyfillExecutionContext` btw)

On Scala 2.13.3 (SJS 1.2.0), this line results in the following:

```javascript
if (($as_T((typeof setImmediate)) === this.Lcats_effect_unsafe_PolyfillExecutionContext$__f_Undefined)) {
```

Which is exactly what I would expect. However, on 0.27.0-RC1 we get the following:

```javascript
if (($as_T((typeof (0, setImmediate))) === this.Lcats_effect_unsafe_PolyfillExecutionContext$__f_Undefined)) {
```

This obviously doesn't return `"undefined"` when `setImmediate` is in fact `undefined`, meaning that the test is failed and we end up in a code path that isn't expected. This was discovered with Gecko and `setImmediate` (which is only available on NodeJS 0.9+ and Edge 10+), but it should be reproducible with almost anything.

**Comment by sjrd** [comment]
Please report issues with DottyJS on the dotty repository. Just by the level of maturity of Scala.js for Scala 2 versus Scala 3, you have 99% chances to select the correct repository that way.

In this case it's indeed a problem in dotty, for which I have a fix waiting in a wip branch. I'll close this here, but feel free to reopen in the dotty repo.

**Comment by djspiewak** [comment]
For posterity: https://github.com/lampepfl/dotty/issues/9785
