### ISSUE TITLE
Matcher region not mutating the matcher

### ISSUE THREAD

**Issue by thesamet** [scala-js/scala-js#4203]
Matcher.region() is returning an instance of a new matcher with the given start and end position:

https://github.com/scala-js/scala-js/blob/92737aa24280fddb3e914937e9b02f50d2d01c8f/javalib/src/main/scala/java/util/regex/Matcher.scala#L228-L229

The behavior on the JVM is that the region is updated in-place: https://docs.oracle.com/javase/7/docs/api/java/util/regex/Matcher.html#region(int,%20int)

**Comment by sjrd** [comment]
Thanks for the report :)

**Comment by thesamet** [comment]
As a workaround, I changed my instance to `var` so I can re-assign the returned value to the same variable (rather than mutating). I then noticed at least one more inconsistency with the JVM object that triggered IllegalStateException. I'll file a separate bug later.
