### ISSUE TITLE
java.lang.Character toTitleCase(ch: Char) & toTitleCase(codePoint: Int)

### ISSUE THREAD

**Issue by er1c** [scala-js/scala-js#4208]
Missing implementations in `java.lang.Character`

* `def toTitleCase(ch: scala.Char): scala.Char`
* `def toTitleCase(codePoint: scala.Int): scala.Int`

**Comment by er1c** [comment]
I think this works: https://github.com/scala-js/scala-js/pull/4207

**Comment by sjrd** [comment]
Fixed in b726767011db291ce97a3e29668d62cc758027bb
