### ISSUE TITLE
Segmentation fault on produced binary

### ISSUE THREAD

**Issue by catap** [scala-js/scala-js#4215]
Let me share with you a bit strange but very simple code :

```
import java.util.Random

class RandomWrapper(impl: Random = new Random()) extends Random {
  def this(seed: Long) = {
    this()
  }
}

object Bug extends App {
  new RandomWrapper()
}
```

When I build it via M2 on my machine and try to run, it crashed with `segmentation fault`.

When I remove:
```
  def this(seed: Long) = {
    this()
  }
```

it works.

I guess it is a bug.

**Comment by sjrd** [comment]
Er ... Wrong repo?

**Comment by catap** [comment]
Wrong repo. Sorry.
