### ISSUE TITLE
When in NoModule mode, multiple public module IDs crash the linker

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#4224]
I haven't reproduced this, but I know it because I have written the code :P

@sjrd, IIRC, we have agreed that the best behavior here is to simply ignore any public module ID when emitting to `NoModule` kind. An alternative would be to reject more than one module when in `NoModule` mode (arguably the more conservative choice).

In any case, this needs to be fixed, because the condition must not crash the linker.

**Comment by sjrd** [comment]
I suggest rejecting for now. And if people complain, we can always make it more lenient in the future.
