### ISSUE TITLE
Generated module file names are not guaranteed to be unique on case insensitive file-systems

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#4242]

**Comment by sjrd** [comment]
IIUC this cannot happen with `MinModuleAnalyzer`. This would only be for `MaxModuleAnalyzer`, in case we're given as input module names for example `a`, `b` and `A-b`. Is that right?

**Comment by gzm0** [comment]
The `MinModuleAnalyzer` assumes class names are unique. But they are only unique in case sensitive comparison. Then again, it is true that it will be difficult to have classes that differ only in case (in the linker) with a case insensitive file system (but possible).

OTOH, if I were to define a public module called `java.lang.object`, `MinModuleAnalyzer` would also break.

**Comment by sjrd** [comment]
Ah, right. It seems all those cases are unlikely to happen by accident, but it would be good to fix those nevertheless.

**Comment by gzm0** [comment]
Hum... The longer I think about this, the more problematic fixing it becomes :-S Is there even a canonical way how "case insensitive file-systems" deal with case folding? I guess the simple answer is: no. But in that case, all we have is resorting to using the equality of `Path` (or even worse: `Files.isSameFile`). This in turn will completely break the abstractions we have in place :-S

**Comment by sjrd** [comment]
Case folding is universal in Unicode. It is not locale-dependent. An approximation of the official case folding algorithm is to use `s.toUpperCase(Locale.ROOT).toLowerCase(Locale.ROOT)`, although I think there may be a few discrepancies still. It should be good enough for 99.99% of cases, though.

**Comment by gzm0** [comment]
Well yes, maybe. But is that what the file-systems actually use? I'm starting to believe that if we make assumptions, we might as well stick to the ones we have right now. Because that already is very unlikely to happen by accident (although the nested static forwarder issue tells another story :-/).

**Comment by sjrd** [comment]
I believe it's not a big deal if we leave it as is. I agree that it's very unlikely to happen (already, the clash avoidance is unlikely to even be necessary most of the time on case-sensitive file systems).

But if we want to fix it, I believe it would be correct to use the universal Unicode case folding. We only need to be *as lenient as* the file system, i.e., we need "if the file system considers A and B equal, then we consider A and B equal". We do not need the converse to be true. I don't believe that any file system would consider equal two strings that would not be equal under the full Unicode case folding algorithm.

**Comment by gzm0** [comment]
I'll do a quick check if I can break this by using scala's case sensitivity. (this is a case where an external library could break a user when using `MinModuleAnalyzer`). If I can't, let's close this as wontfix and release 1.3.0.

**Comment by gzm0** [comment]
Seems I cannot without generating a warning in scalac. So I vote we close this as wontfix.
