### ISSUE TITLE
scalaJSLinkerOutputDirectory in fastLinkJS / fullLinkJS have bad suffixes

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#4243]
They have the suffixes `-dev` / `-prod` from when the tasks still were called `linkJSDev` / `linkJSProd`. IMHO at this point the suffixes are just confusing.

**Comment by gzm0** [comment]
@sjrd how shall we deal with this w.r.t. v1.3.0? Changing the defaults after the fact is maybe a bit annoying :S

**Comment by sjrd** [comment]
I can still cancel 1.3.0 if necessary.

**Comment by gzm0** [comment]
Should we for this?

**Comment by sjrd** [comment]
No, probably not. IMO we could still change the default in a subsequent version.
