### ISSUE TITLE
Files reachable by individual split module entry point combined are way larger than unsplit single file

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#4256]
I just tried out the new module splitting in 1.3.0. My app has four publicly export JS. These are the sizes of each (in bytes) using SJS 1.2.0 when I run `fastOptJS`:

```
public     3,927,283
home       4,468,949
project   30,411,891
ww         9,130,137
```

To use the new module splitting feature, I've added a new SBT module that depends on all the rest, and I've added unique module IDs to each `@JSExportTopLevel`. One of the modules (`ww`) however uses a module initialiser and I've used the following SBT config:

```scala
scalaJSModuleInitializers in Compile += {
  ModuleInitializer.mainMethod("shipreq.webapp.client.ww.Main", "main").withModuleID("ww")
}
```

Running `fastLinkJS` I get the following output:

```
> la /tmp/shipreq.sbt/webapp-client-exports/target/scala-2.13/webapp-client-exports-fastopt/
total 36360
drwxr-xr-x 2 golly users      240 Oct 17 12:29 .
drwxr-xr-x 5 golly users      100 Oct 17 12:33 ..
-rw------- 1 golly users   160464 Oct 17 12:29 home.js
-rw------- 1 golly users  2955960 Oct 17 12:29 home-project.js
-rw------- 1 golly users   794106 Oct 17 12:29 home-project-public.js
-rw------- 1 golly users  3978425 Oct 17 12:29 home-project-public-ww.js
-rw------- 1 golly users  9183839 Oct 17 12:29 home-project-ww.js
-rw------- 1 golly users 16528129 Oct 17 12:29 project.js
-rw------- 1 golly users   683909 Oct 17 12:29 project-public.js
-rw------- 1 golly users  1657654 Oct 17 12:29 project-ww.js
-rw------- 1 golly users  1000911 Oct 17 12:29 public.js
-rw------- 1 golly users   266871 Oct 17 12:29 ww.js
```

My understanding is that
* `home.js` will also load all of the `home-*.js` files
* `ww.js` will also load all of the `*-ww*.js` files
* etc

By doing a bit of selective addition we end up with the following comparison:

```
=========================================================
            combined splits      fastOptJS    improvement
=========================================================
public            6,457,351      3,927,283         -64.4%
home             17,072,794      4,468,949        -282.0%
project          35,782,022     30,411,891         -17.7%
ww               15,086,789      9,130,137         -65.2%
=========================================================
```

Despite having shared code being the modules, it seems each top-level module when combined with its dependencies, is way larger than just producing duplicated code with `fastOptJS`. There must be a bug in the module splitting.

If it would help, let me know how and I can privately send you the output files.

**Comment by sjrd** [comment]
I agree that some of the increases are very large, notably for `home`, and we can look into improving that. That said, I'm a bit confused by this sentence:

> Despite having shared code being the modules, it seems each top-level module when combined with its dependencies, is way larger than just producing duplicated code with fastOptJS.

along with fact that your last column is called "Improvement" (with negative values). Were you expecting the combined splits to be actually *smaller* than the original per project .js files? That wouldn't be possible. The individual .js files are as optimized as possible. By sharing code, it is expected that some code will be in the transitive dependencies of a public module, although they're not used. A typical example would be a method `m` in a class `A`, if `m` is dead code for a given page *p1* but used in page *p2*, but some other methods of `A` are used in *p1*. In that case, *p1* would not have `m` in the individual .js file, but it will be in the transitive dependencies, because we never split classes.

The only code size improvement we can expect is on the total size of all modules (or subsets thereof), because shared code need not be duplicated. And it seems that this is working pretty well here: with mental calculations, the total size of the individual files was about 47 MB, but the total size of the splits is only about 34 MB.

**Comment by japgolly** [comment]
Ah yes of course. I started just by wanting to compare and then once I saw that the differences were so large I just went into data collection mode and stopped thinking. Yeah we should be expecting the combined splits to be on par or slightly larger than unsplit versions, and the total size should be smaller - 100% agree. We are getting a total size reduction of 22.4% (47,938,260 → 37,210,268) so that's good. But I'm still surprised the re-bundled sizes are so much larger. `home` is huge like you say but so are `ww` and `public` at around 65%. Doesn't that seem a bit high too?

**Comment by japgolly** [comment]
Btw here are tjhe numbers will `fullOptJS` vs `fullLinkJS` (without Closure / minification):

```
=================================================
            fastOptJS     reduction   improvement
=================================================
public      5,980,874       709,200       -743.3%
home       15,526,001       793,157      -1857.5%
project    32,595,849    28,201,948        -15.6%
ww         13,692,692     8,463,662        -61.8%
  TOTAL    33,924,885    38,167,967         11.1%
=================================================
```

**Comment by gzm0** [comment]
@japgolly it would be very helpful for us to understand why the pulled in bundle size for `home.js` is so big. I suspect it is because we only split on classes, as @sjrd describes.

IIUC, the codebase is private, but maybe you can have a look which class is both pulled in by `home.js` and another entry point. (the easiest way to do this is to look at the `import`s / `require`s at the top of the file and then look for usages). E.g.:


```javascript
// Import of another module
import * as $j_main from "./main.mjs";

// Usage site, look for `$j_main.`
$j_main.$c_O
```

**Comment by gzm0** [comment]
@japgolly gentle ping? We'd really like to understand your use case better.

**Comment by japgolly** [comment]
Hey @gzm0, sorry about the delay. I won't have time to sit down and try to analyse this for a while. I can send you the files if that would be easier. Should I do that?

Also if this is just an artifact of my codebase being large, I'm happy to close this issue. I've decided that all things considered, it's not advantageous for my specific project to use module splitting.

**Comment by gzm0** [comment]
If you could send me the files, that'd work for me. I can probably pull some basic analysis just from that, yes.

**Comment by japgolly** [comment]
@gzm0 sure what's your email? Or you can ping me at japgolly@gmail.com and I'll reply with the files.

**Comment by gzm0** [comment]
An update on this: I have received the relevant files from @japgolly and will have a closer look.

**Comment by gzm0** [comment]
I have performed the following analysis:

- Extract names of classes (`$c_`) defined in:
  - `home-project.js` (with splitting)
  - `home.js` (without splitting)
- Retrieve the classes that are in `home-project.js` but not in `home.js` (over 100).
- Follow 2 very low-level classes in this list in reverse dependency order and see why they are included.
- Both of them have lead to a method in an object (module class) where the object is used by both `home.js` and `project.js` but the method only by `project.js`. The object is in the user's code base.

Observations/takeaways:
- This is as we have suspected.
- Without tools, this sort of analysis is very time consuming.
- It is plausible that many code bases not written with splitting in mind expose this pitfall.
- So far, there is no evidence as to whether the Scala standard library or other common libraries in the ecosystem expose this pitfall.

I do not believe that this is actionable for us at this point. So unless there are objections or further analysis is requested, I propose to close this issue as wontfix. I'd like to wait and hopefully develop a better feel of what would help most here (e.g. more analysis tools or more fine grained splitting, or?).

**Comment by sjrd** [comment]
Yes, I was also expecting something like that. To me, it seems that someone (tm) could implement a tool to help diagnose that kind of issue. In theory the analysis performed above could be done semi-automatically, like do steps 1 and 2, then let the user select one of the classes, then perform steps 3 and 4 on it.

I think such a tool could be implemented outside the repo, even if it would probably have to rely on non-standard APIs in the linker.
