### ISSUE TITLE
toString prints decimals as integers when the decimal portion is .0

### ISSUE THREAD

**Issue by Sciss** [scala-js/scala-js#4258]
For example:

```scala
Vector(0.0, 3.0, 6.0)
(-0.0).toString
(0.0).toString
```
Compare the worksheet printouts. [Scala 2.13 JVM](https://scastie.scala-lang.org/OKkwt8cxS9WswLLhNodxVw):
```
Vector(0.0, 3.0, 6.0)
-0.0
0.0
```
[Scala.js](https://scastie.scala-lang.org/1dwL9FXLSRyn2ZzSYa8RnA):
```
Vector(0, 3, 6)
0
0
```
I think Scala.js should follow mainline Scala here; it also puts extra effort in handling divering output in unit tests.

It seems that `-0.0` was intended, #151 is an older issue of the same nature.

**Comment by sjrd** [comment]
This behavior is as designed. Please see https://www.scala-js.org/doc/semantics.html
