### ISSUE TITLE
ScalaJS 1.3.0 fails to fastOptJS/fullOptJS when the project has no exports nor the module initializer

### ISSUE THREAD

**Issue by unarist** [scala-js/scala-js#4271]
1. Create a project with only build.sbt and plugins.sbt

    ```
    // build.sbt
    enablePlugins(ScalaJSPlugin)
    name := "Scala.js Tutorial"
    scalaVersion := "2.13.1"

    // plugins.sbt
    addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.3.0")
    ```

2. Run `sbt fastOptJS` or `sbt fullOptJS` 
    * v1.2.0: succeeds
    * v1.3.0: fails with `org.scalajs.linker.interface.ReportToLinkerOutputAdapter$UnsupportedLinkerOutputException: Linking did not return exactly one public module.`

It also works with 1.3.0 if I add `main()` method or `@JSExportTopLevel`.

(In my case, the project is only used by dependent projects and there is no need to fastOpt/fullOpt for the project actually.)

**Comment by sjrd** [comment]
Thank you for the report

@gzm0 Looks like we should tolerate the case where the `Report` contains no module at all, and in that case produce an empty JavaScript file. Does that seem reasonable?

**Comment by gzm0** [comment]
> Does that seem reasonable?

Yes, it seems so. Questions:
- Do we emit a source map link in this case?
- Do we emit a source map? (if yes, what does it contain?)

**Comment by sjrd** [comment]
I think we should emit a source map, which contains trivial data, in particular an empty array of names and sources, and an empty section for segments.
