### ISSUE TITLE
Local JS classes inside anonymous classes cause IR checking errors

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#4278]
Take the following:

```scala
val supplier = new Supplier[js.Dynamic]{
  def get(): js.Dynamic = {
    class LocalInsideAnonymousClass extends js.Object {
      def x: Int = 1
    }

    new LocalInsideAnonymousClass().asInstanceOf[js.Dynamic]
  }
}

val obj = supplier.get()

assertEquals(1, obj.x)
```

Causes:

```
file:/home/tschlatt/20p/scala-js/test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/NestedJSClassTest.scala(517:15:CreateJSClass): Invalid CreateJSClass of top-level class org.scalajs.testsuite.jsinterop.NestedJSClassTest$$anon$1$LocalInsideAnonymousClass$1
```

I suspect that the local class wrongly gets identified as anonymous class by later compiler phases because some checks are name based.

**Comment by gzm0** [comment]
Yep: https://github.com/scala/scala/blob/v2.13.3/src/reflect/scala/reflect/internal/Symbols.scala#L3354

So that means we cannot use `isAnonymousClass` post flatten anymore (at least without caveats).

**Comment by sjrd** [comment]
Ouch. I guess we'll need to do a more sophisticated check that does not look anywhere inside, but only at the end followed by digits only or something like that. (I'm not sure what's the exact format, but hopefully it's too hard to identify.)
