### ISSUE TITLE
Default parameters in non-native JS traits cause difficult to understand error message

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#4319]
Consider:

```scala
trait Foo extends js.Any {
  def foo(x: Int = 1): Unit
}
```

This fails with:

```
Members of non-native JS traits must either be abstract, or their right-hand-side must be `js.undefined`.
    def foo(x: Int = 1): Unit
                     ^
```

Adding `@js.native` to the trait makes compilation succeed.

**Comment by sjrd** [comment]
The error message could certainly be improved. But I don't see how to actually make it *work*.

**Comment by gzm0** [comment]
I'm not sure I understand. Isn't a default parameter in a facade merely a definition of a calling convention? So basically, the following two are equivalent IIUC:

```scala
trait Foo extends js.Any {
  def foo(x: Int = 1): Unit
}

trait Foo extends js.Any {
  def foo(): Unit
  def foo(x: Int): Unit
}
```

**Comment by sjrd** [comment]
The problem is when you implement that trait in a non-native JS class: you don't have to provide a default value, but the compiler also doesn't know where to get it from.

**Comment by gzm0** [comment]
Ah, I see. Fair enough. In this case, only the error message needs improvement indeed.

**Comment by gzm0** [comment]
Hah, this causes an IR checking error:

```scala
trait A extends js.Any {
  def foo(x: js.UndefOr[Int] = js.undefined): Int
}

object Impl extends A {
  def foo(x: js.UndefOr[Int]): Int = x.getOrElse(5)
}
```
