### ISSUE TITLE
JSOptional default parameters cause IR checking errors

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#4322]
```scala
trait A extends js.Any {
  def foo(x: js.UndefOr[Int] = js.undefined): Int
}

object Impl extends A {
  def foo(x: js.UndefOr[Int]): Int = x.getOrElse(5)
}
```

```
 Referring to non-existent method static org.scalajs.testsuite.jsinterop.JSOptionalTest$Impl$1$.foo$default$1(org.scalajs.testsuite.jsinterop.JSOptionalTest$Impl$1$)scala.scalajs.js.$bar
```

**Comment by gzm0** [comment]
As pointed out by @sjrd (https://github.com/scala-js/scala-js/pull/4324#issuecomment-744420914) we should simply force repetition of default parameters.

**Comment by gzm0** [comment]
I have been digging some more and this is quite puzzling: We seem to have code to exactly detect this condition with `@js.native` classes:

https://github.com/scala-js/scala-js/blob/5d363521ab2e07edadf27ddf1cb26a7f11d2e329/compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala#L768-L780

The original bug report was #2547.

However, the strange thing is that one would expect either of the following (in the example above):
- With default methods: The default getter is owned by `A`, which is a trait, triggering the (somewhat misleading) error.
- Without default methods: `B` has an impl forwarder for the default getter to the impl class of `A`, but the impl class of A is not emitted. This in turn would lead to an IR checking error.

However, neither of these two things happen: The owner of the default getter in this case is `Impl`, yet the resulting IR does not contain said getter.

**Comment by sjrd** [comment]
> However, neither of these two things happen: The owner of the default getter in this case is `Impl`, yet the resulting IR does not contain said getter.

Wild guess: maybe the getter forwarder in `Impl` gets the annotation `@JSOptional`, which it inherits from the default getter in the trait. And because of that, it is not emitted, due to this test:
https://github.com/scala-js/scala-js/blob/5d363521ab2e07edadf27ddf1cb26a7f11d2e329/compiler/src/main/scala/org/scalajs/nscplugin/GenJSCode.scala#L653-L656

**Comment by gzm0** [comment]
Yes, exactly. But that in turn means we can actually use this to emit the right thing :) If the (synthesized) getter has `@JSOptional` just put `js.Undefined()`. Otherwise, call it (because it will be there).

**Comment by sjrd** [comment]
Ah, that may well be the case, indeed.
