### ISSUE TITLE
Revisit Optimizer / Emitter "CallHelper" interface

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#4339]
See https://github.com/scala-js/scala-js/pull/4321#r545087286

**Comment by gzm0** [comment]
I'll have a stab at this. It seems that this would allow us to inline typed array / array conversions. IMO this would be in line with how we create simple array values. @sjrd any opinions on that?

**Comment by sjrd** [comment]
Yes, sure, we can do that. I'm not sure the new interface will *allow* us to do that, though, in the sense that I don't see why we can't do it with the current stringly-typed API (irrespective of the disadvantages of such an API).

**Comment by gzm0** [comment]
That is a good point. Indeed, I think a more strongly typed API is just more likely to "nudge" us in that direction (e.g. we can just pass `PrimRef`s around, rather than having a name per array type).

There are other improvements that become more obvious btw. for example it is much easier to judge certain things to be side effect free or even pure.

All that being said, none of this could not be done with the current API :)
