### ISSUE TITLE
Reconsider ArrayBuilder intrinsics

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#4340]
See https://github.com/scala-js/scala-js/pull/4321#r546409227

Post #4321, it is unclear whether they still improve performance. Further, the CoreJSLib maintains quite some machinery just for that:

- The `zero` field of type data.
- The `wrapArray` method.

**Comment by gzm0** [comment]
@sjrd do we have benchmarks that exercise this? I'm happy to do the modification (IIUC mostly removing code), but I'd need help selecting/running the right benchmarks.

**Comment by sjrd** [comment]
I'm not sure we have any benchmark that is particularly representative of the behavior of `ArrayBuilder`.

In general, the benchmarks are here: https://github.com/sjrd/scalajs-benchmarks
They can be run on Node.js with

    > richarsJS/run

or any other benchmark. They print a result line containing the mean and SEM of the running time. I have this other branch where they print the individual measurements, and they can also be sent to a file: https://github.com/sjrd/scalajs-benchmarks/tree/all-results

The fullOpt stage is not supposed to be used. Instead, we can change the `scalaJSLinkerConfig`, and everything else follows. For example,

    > set ThisBuild/scalaJSLinkerConfig ~= { _.withSemantics(_.optimized) }
    > set ThisBuild/scalaJSLinkerConfig ~= { _.withModuleKind(ModuleKind.ESModule).withOutputPatterns(org.scalajs.linker.interface.OutputPatterns.fromJSFile("%s.mjs")) }

and rerun.

An HTML runner can be create for a benchmark using

    > richardsJS/createHTMLRunner

which uses all the same configuration as above. It works for Scripts and ES modules.

**Comment by sjrd** [comment]
The best might be to take inspiration of the intMicro benchmark (possibly editing directly into it as a first step), to test a few scenarios:
* Fill an array using an ArrayBuilder,
* Map an array
* Filter an array

all of the above using Ints, Chars and a class SomeClass.

**Comment by gzm0** [comment]
Removing the intrinsics bumps the sizes in full opt quite a bit:

```
[info] fastLink size = 781663 (expected Range 781000 to 782000)
[info] fullLink size = 158665 (expected Range 148000 to 149000)
[info] fastLink gzip size = 91233 (expected Range 91000 to 92000)
[info] fullLink gzip size = 38838 (expected Range 36000 to 37000)
```

My understanding is that for a gain in performance, that would be acceptable.

**Comment by gzm0** [comment]
I have some preliminary results of sjrd/scalajs-benchmarks#5 against this branch: https://github.com/scala-js/scala-js/compare/master...gzm0:no-array-builder-intrinsic?expand=1 (Node.js v12.18.2)

1.7.0

```
ArrayBuilderFill5IntNoHint;Scala.js;es2015;script;dev;opt;no-gcc;Node.js;0.3505540499996333;0.0005783493555128827
ArrayBuilderFill5IntHint;Scala.js;es2015;script;dev;opt;no-gcc;Node.js;0.35186118227565977;0.0007250576326315517
ArrayBuilderFill100IntNoHint;Scala.js;es2015;script;dev;opt;no-gcc;Node.js;3.807762476255159;0.006821165347984902
ArrayBuilderFill100IntHint;Scala.js;es2015;script;dev;opt;no-gcc;Node.js;3.8511704035013046;0.006896965804565269
ArrayBuilderFill5CharNoHint;Scala.js;es2015;script;dev;opt;no-gcc;Node.js;0.3477718807418821;0.0005364555619725636
ArrayBuilderFill5CharHint;Scala.js;es2015;script;dev;opt;no-gcc;Node.js;0.3465881503080941;0.0006512296901984284
ArrayBuilderFill100CharNoHint;Scala.js;es2015;script;dev;opt;no-gcc;Node.js;3.789966746286677;0.006152815764770998
ArrayBuilderFill100CharHint;Scala.js;es2015;script;dev;opt;no-gcc;Node.js;3.85339287966597;0.006706401425043861
ArrayBuilderFill5StringNoHint;Scala.js;es2015;script;dev;opt;no-gcc;Node.js;0.39038998057044905;0.0018227989597269045
ArrayBuilderFill5StringHint;Scala.js;es2015;script;dev;opt;no-gcc;Node.js;0.3894001786202591;0.0017823335700830859
ArrayBuilderFill100StringNoHint;Scala.js;es2015;script;dev;opt;no-gcc;Node.js;3.837678692677668;0.007290554761293404
ArrayBuilderFill100StringHint;Scala.js;es2015;script;dev;opt;no-gcc;Node.js;3.9335457439820662;0.008120383785341767
```

1.7.1
```
ArrayBuilderFill5IntNoHint;Scala.js;es2015;script;dev;opt;no-gcc;Node.js;4.281048518773936;0.019517904401236217
ArrayBuilderFill5IntHint;Scala.js;es2015;script;dev;opt;no-gcc;Node.js;0.7963116467605256;0.001811518407148057
ArrayBuilderFill100IntNoHint;Scala.js;es2015;script;dev;opt;no-gcc;Node.js;33.24144432194187;0.251985556143141
ArrayBuilderFill100IntHint;Scala.js;es2015;script;dev;opt;no-gcc;Node.js;9.349788296660893;0.09113297189601144
ArrayBuilderFill5CharNoHint;Scala.js;es2015;script;dev;opt;no-gcc;Node.js;5.027311250905241;0.025041967454602118
ArrayBuilderFill5CharHint;Scala.js;es2015;script;dev;opt;no-gcc;Node.js;1.5718438715972773;0.0034070725082207018
ArrayBuilderFill100CharNoHint;Scala.js;es2015;script;dev;opt;no-gcc;Node.js;39.921613197826375;0.1716262160441755
ArrayBuilderFill100CharHint;Scala.js;es2015;script;dev;opt;no-gcc;Node.js;22.022714159262108;0.07164479310572215
ArrayBuilderFill5StringNoHint;Scala.js;es2015;script;dev;opt;no-gcc;Node.js;3.04364614323301;0.005619668077348892
ArrayBuilderFill5StringHint;Scala.js;es2015;script;dev;opt;no-gcc;Node.js;1.355655926212564;0.0027831203504525537
ArrayBuilderFill100StringNoHint;Scala.js;es2015;script;dev;opt;no-gcc;Node.js;23.068348830497072;0.03310928886917135
ArrayBuilderFill100StringHint;Scala.js;es2015;script;dev;opt;no-gcc;Node.js;9.986354224724321;0.009908813526987793
```

Observations:
- We can see how the size hint now matters, which is expected.
- Even with the size hint, we see a 2x slowdown.

Feels a bit like there's no point digging further and take this as reasonable evidence that the ArrayBuilder intrinsic has value.

@sjrd, WDYT?

**Comment by sjrd** [comment]
Indeed, that seems to be pretty strong evidence that the intrinsics have value, although it would have been nice to be able to get rid of them. I guess we can close this issue.

Thanks for looking into it!
