### ISSUE TITLE
Different behavior in Regex#replaceAllIn w.r.t. non-matching groups

### ISSUE THREAD

**Issue by nightscape** [scala-js/scala-js#4350]
I have a small case where Scala-JS (see [ScalaFiddle](https://scalafiddle.io/sf/CKvJ2Dq/1)) behaves differently than JVM (tested in Ammonite):
```scala
// JVM
println("(ab)|(a)".r.replaceAllIn("ab", "[1=$1][2=$2]")) 
[1=ab][2=]

// JS
println("(ab)|(a)".r.replaceAllIn("ab", "[1=$1][2=$2]")) 
[1=ab][2=null]
```
My naive guess is that the [`Matcher.group`](https://github.com/scala-js/scala-js/blob/5388c7b5cc1fa976a4e1b6741ec74716f9075083/javalib/src/main/scala/java/util/regex/Matcher.scala#L305) method returns `null` and `null` is formatted as `""` on JVM and `"null"` on JS.
If this is actually the problem, then it could be fixed by a rather precise change in `Matcher` that should not involve changes in code size.

Split out from https://github.com/scala-js/scala-js/issues/1201

@sjrd shall I give it a try?

**Comment by sjrd** [comment]
> shall I give it a try?

Sure, go ahead! Make sure to read [the very important notice about the javalib](https://github.com/scala-js/scala-js/blob/master/JAVALIB.md#very-important-notice-about-the-javalib).
