### ISSUE TITLE
Decide where to validate/document IR invariants

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#4388]
> The only guideline is "if we think it's not going to be a performance problem, put it in the Trees". That's not a very objective criteria.

That's fair. My concern with putting more in the IR checker is that it is much harder to find out how a tree is supposed to be used in the IR checker. Essentially, in terms of ease of use for a developer: type system > assertions > IR checker.

In any case, this is quite independent of this PR and definitely shouldn't block it. I'll review the rest and move this into a separate issue.

_Originally posted by @gzm0 in https://github.com/scala-js/scala-js/pull/4377#discussion_r560835155_

**Comment by gzm0** [comment]
To kick-off the discussion, I'd classify the invariants into the following loose categories:

1. Global invariants: Things that need a linking unit to be checked (e.g. proper target class type in  `LoadJSConstructor`).
2. Tree-local invariants: Things that can be checked for a subtree, but need arbitrary recursion (e.g. duplicate vals / labels).
3. Subfield-local invariants: Things that can be checked by iterating to fixed dept (e.g. class capture cannot be mutable).
4. Fully local invariants: Things that can be checked by looking at singular fields only (e.g. `classDef.nativeLoadSpec.nonEmpty <=> kind in {ClassKind.NativeJSClass | ClassKind.NativeJSModuleClass}`, `ArrayTypeRef` may not contain certain native types, allowed `lhs` trees for `Assign`).

Observations:
- (1) must be checked in the IR Checker.
- (2) could be, in theory, (partially) checked by local assertions, but its almost certainly a bad idea.
- The boundary between (3) / (4) is arguably not very clear.
- (4) is ATM sometimes checked in the IR Checker (e.g. `ClassDef` invariants), sometimes in assertions (e.g. `Assign` `lhs`), sometimes both (e.g. `MethodDef` may not have mutable flag).

Opinion: Checking (4) in assertions is much easier for a programmer, because the properties are local.

For example, looking at `MethodDef`, it is immediately clear where the invariants for names / namespaces are:

https://github.com/scala-js/scala-js/blob/0885360c6a9bed99b852affb4c91e17ba22ff50f/ir/shared/src/main/scala/org/scalajs/ir/Trees.scala#L1089-L1106

Another example is `Assign`, where the permitted LHSes are immediately clear form the definition.

https://github.com/scala-js/scala-js/blob/0885360c6a9bed99b852affb4c91e17ba22ff50f/ir/shared/src/main/scala/org/scalajs/ir/Trees.scala#L153-L165

As another example, take `ClassOf`:

https://github.com/scala-js/scala-js/blob/0885360c6a9bed99b852affb4c91e17ba22ff50f/ir/shared/src/main/scala/org/scalajs/ir/Trees.scala#L908-L911

From the definition alone, the restrictions on `typeRef` are unclear. We need to look at the IR Checker separately:

https://github.com/scala-js/scala-js/blob/0885360c6a9bed99b852affb4c91e17ba22ff50f/linker/shared/src/main/scala/org/scalajs/linker/checker/IRChecker.scala#L1137-L1145

However, it is unclear to me when this looses its value as the gradient moves towards (3) :-/

**Comment by sjrd** [comment]
I have a different way to look at things. To me, currently, there are two places that I need to look at to know the invariants. For example, for `MethodDef`, I have to look at the definition of `MethodDef` but *also* at `IRChecker.checkMethodDef`. Some restrictions are directly in `MethodDef`, but I have no idea whether they're complete, or there's more in the IR checker.

If we put everything in the IR checker, then it's immediately clear where to look to have *all* the invariants about `MethodDef`.

**Comment by gzm0** [comment]
Hmmm.... That's fair, but you'd still have to look at `MethodDef` to know basic things like its fields :S

It seams like this is mainly a code locality problem, should we investigate a polymorphic approach so that we write the checks in the trees themselves (while supplying some interface allowing to check other stuff). I'm not sure that will go well... OTOH if it moves the actual checking logic into `ir`, that might also make more sense.

**Comment by sjrd** [comment]
That seems overengineering to me, at that point. Plus we'd have to burn a bunch of concepts like the `Env` into the public API of `Trees`, whereas currently this is all just an implementation detail of the IR checker.

**Comment by gzm0** [comment]
Yeah, that's fair. So let's move all of it to the IR checker. I'll try to do that tomorrow.

**Comment by gzm0** [comment]
We forgot about the Analyzer :) Some things also need to be checked in the analyzer or at least worked around so that the IR checker can check them.

This has a couple of consequences:
- The Analyzer needs to be robust to all errors that aren't checked with the type system / assertions.
- Certain problems might go unnoticed, because the Analyzer removes the trees (see example below).
- The Analyzer has errors that are not linking problems but simply compiler bugs (in practice: `MissingJSNativeLoadSpec`, it is also checked twice).

For example, emitting a static initializer in the `Public` namespace would currently trigger this:

https://github.com/scala-js/scala-js/blob/bb39b49d0bc995fe9ec471fd79732b03e81fc59b/ir/shared/src/main/scala/org/scalajs/ir/Trees.scala#L1101-L1103

If that check were to be moved to the IR checker, a problem like this would likely go unnoticed, unless a corresponding (broken) `ApplyStatic` node was reached somewhere. (FWIW: the reasoning to get to that conclusion is *far* from trivial for something as simple as "two fields should be consistent").

**Comment by gzm0** [comment]
class initializers are an even worse example: we do have a check that they are not allowed in non-JS classes, but in practice, the Analyzer only reaches them for JS classes. So for the IR checker to catch the problem, some code would have to try and call a class initializer :-/

**Comment by sjrd** [comment]
Indeed, the fact that the IR checker only runs on what survives the Analyzer is a significant issue. At the same time, we cannot perform all the checks of the IR checker before dce either, because things like `java.lang.String.toLowerCase(Locale)` cannot be IR-checked when `Locale` is not on the classpath.

So we inevitably need some checks before DCE, and some after. Pre-DCE, I believe we should be able to check everything that doesn't involve `ParamDef`s, `Tree`s or `Type`s. That notably means class headers, method kinds and names (but not params nor body), field kinds (but not types), duplicate member defs.

That also means that the Analyzer and the IR checker are really only 2 faces of the same coin, and they have to work together to completely validate a codebase.

**Comment by gzm0** [comment]
Yeah, pretty much. But in practice that means we need to split the IR checker. I don't think it is a good idea to assert all pre-DCE checks in trees, merely for performance reasons.

So basically, this would mean we have:
- New thing (subtree checker): Validates 2-4 above. Notably, all `LocaName`s and all `LabelName`s. Maybe even `tpe` of `VarRef`?
- Analyzer establishes references (`MethodName`, `FieldName`, `ClassName`).
- IR Checker, checks things that need references for checking (notably full type checking).

I'll see if I can have a stab at this.
