### ISSUE TITLE
Extending a native inner class complains that it has no JS native load spec

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#4402]
The following code works fine:
```scala
import scala.scalajs.js

@js.native
trait Outer extends js.Object {
  @js.native
  class InnerClass extends js.Object
}

object HelloWorld {
  def main(args: Array[String]): Unit = {
    val outer = js.Dynamic.literal(
      InnerClass = js.constructorOf[js.Date]
    ).asInstanceOf[Outer]
    println(new outer.InnerClass)
  }
}
```
and prints the current date/time.

However, if I add
```scala
    class Subclass extends outer.InnerClass

    println(new Subclass)
```
to the main method, then the linker reports a linking error:
```
[error] helloworld.Outer$InnerClass is a native class but does not have a JSNativeLoadSpec
[error]   called from helloworld.HelloWorld$.main([java.lang.String)void
[error]   called from static helloworld.HelloWorld.main([java.lang.String)void
[error]   called from core module module initializers
[error] involving instantiated classes:
[error]   helloworld.HelloWorld$
[error] There were linking errors
```
Indeed, `InnerClass` is encoded as a `native js class` but without JS native load spec:
```scala
> helloworld2_12/scalajsp helloworld.Outer$InnerClass
native js class helloworld.Outer$InnerClass extends scala.scalajs.js.Object {
}
```
It is correct that it doesn't have a native load spec, since it must be accessed as a field of an `outer` variable. It should be marked as an `abstract js type` instead of a `native js class`.

The same goes for an inner native JS `object`, although I'm not sure how to write a failing test for those.

**Comment by sjrd** [comment]
Hum, so now the problem is that, if I do fix the above to use `AbstractJSType` for `InnerClass`, I get:
```
[error] helloworld.Outer$InnerClass (of kind AbstractJSType) is not a valid super class of helloworld.HelloWorld$Subclass$1 (of kind JSClass)
[error]   called from helloworld.HelloWorld$Subclass$1
[error]   called from helloworld.HelloWorld$.main([java.lang.String)void
[error]   called from static helloworld.HelloWorld.main([java.lang.String)void
[error]   called from core module module initializers
[error] involving instantiated classes:
[error]   helloworld.HelloWorld$
[error] There were linking errors
```
I can also amend the Analyzer to let `AbstractJSType` through as parent of a `JSClass`, at:
https://github.com/scala-js/scala-js/blob/92c453ddfadfe0e2d350f6361c14828e0f58c158/linker/shared/src/main/scala/org/scalajs/linker/analyzer/Analyzer.scala#L525-L531
(and same for native JS classes and abstract JS types below). But then I'm wondering what other check we need to introduce (like make sure that, when we extend an abstract JS type, that the `jsSuperclass` is defined).

At that point I'm not 100% anymore what's the best strategy. Here are a few options:
* Do as described above, i.e., make it an `AbstractJSType`, allow `AbstractJSType`s as `superClass`es, and check that `jsSuperclass.isDefined` when the `superClass` is an `AbstractJSType`
* Leave it as `NativeJSClass`, allow `NativeJSClass`es not to have a native load spec, and check that the `superClass` has a native load spec when `jsSuperclass.isEmpty` and when doing `LoadJSConstructor` (I'm not a fan of this one)
* Remove the distinction between `AbstractJSType`, `JSClass` and even `JSModuleClass`. They would all be `JSType` or something, and `LoadJSConstructor`/`LoadJSModule` would be equivalent and allowed only if the target has a native load spec.
* Go even further: completely get rid of native load spec on `ClassDef`s, and replace them by a `JSNativeMemberDef` with a magic `MethodName`. `jsSuperclass` would be mandatory for all `JSClass` and `JSModuleClass`; `LoadJSConstructor` and `LoadJSModule` would be replaced by a `SelectJSNativeMember` of that magic name.

The last option would require a fair bit of deser hacks, but perhaps it's the one that offers the nicest end result.

@gzm0 Opinions?

**Comment by gzm0** [comment]
A couple of quick observations (I'll keep thinking about this):

- What is `superClass` used for in JS classes except for default fallback of `jsSuperclass`? (something something reflection, I'm sure, but what exactly?).
- The idea of only having JS native members is very appealing. I think it would simplify some stuff.
- So far, changing a JS class from native back and forth was (IIUC) a binary compatible change. Are we committed to that? (if yes, that has implications for options 3/4 IIUC).

**Comment by sjrd** [comment]
>     * What is `superClass` used for in JS classes except for default fallback of `jsSuperclass`? (something something reflection, I'm sure, but what exactly?).

The most important thing is that it is required for subtyping of arrays of such things.

>     * So far, changing a JS class from native back and forth was (IIUC) a binary compatible change. Are we committed to that? (if yes, that has implications for options 3/4 IIUC).

Good point. I'm not sure we're really committed to that, though. It's very unlikely that this is even expected.

That said, it raises questions about the deser hacks that would be required for `LoadJSConstructor` and `LoadJSModule`. Unless we find a clever solution, they would need non-local information. :(

**Comment by gzm0** [comment]
The more I think about this, the more I feel that, the second option is actually very consistent with how our IR looks like today. (And options 3/4 are mere simplifications of the current IR).

I'll try to argue for that, by breaking down the pieces of the names:
- "native": The definition of this lies outside of Scala.js.
- "class": This is a class, it can be inherited from.

Allowing a JS native class without a `jsNativeLoadSpec` is essentially the same as a JS class with `jsClassCaptures`: There is no single statically known class (i.e. constructor) value anymore. It needs to be obtained by other means. For, non-native JS classes, Scala.js provides a mechanism (`CreateJSClass` to create a new class value (but no mechanism to manage created class values). So for a native JS class, it is natural that this mechanism doesn't exist.

Re-reading option 3, I guess you meant "Remove the distinction between `AbstractJSType`, `NativeJSClass` and even `NativeJSModuleClass`." (*native* added). This seems very similar to 2, but removes some "type" from the IR (which might be OK).

Re option 4: Maybe we can just re-specify `LoadJSConstructor` / `LoadJSModule` to call a special native member if the target is a `JSType`. I don't think we have precedent for *exactly* that, but it wouldn't be any more magic IMO than static initializers / class initializers.

**Comment by sjrd** [comment]
> Allowing a JS native class without a `jsNativeLoadSpec` is essentially the same as a JS class with `jsClassCaptures`: There is no single statically known class (i.e. constructor) value anymore. It needs to be obtained by other means. For, non-native JS classes, Scala.js provides a mechanism (`CreateJSClass` to create a new class value (but no mechanism to manage created class values). So for a native JS class, it is natural that this mechanism doesn't exist.

Hum, yes, that's pretty reasonable. I hadn't thought about the analogy with `jsClassCaptures`. I will try that approach.

> Re-reading option 3, I guess you meant "Remove the distinction between `AbstractJSType`, `NativeJSClass` and even `NativeJSModuleClass`." (_native_ added). This seems very similar to 2, but removes some "type" from the IR (which might be OK).

Yes, indeed, I meant `NativeJSClass` and `NativeJSModuleClass`.
