### ISSUE TITLE
Compiler emits abstract methods for JS classes

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#4409]
Discovered while working on #4388.

Example that fails: https://github.com/scala-js/scala-js/blob/b3b964ccdf2dd79038eaca98ce89fa9f8fbdcf8a/test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/ExportsTest.scala#L1520

**Comment by sjrd** [comment]
That's embarrassing...
