### ISSUE TITLE
Publish sbt-scalajs to Maven Central instead of Bintray

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#4412]
JFrog announced today that they are shutting down Bintray:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

I don't know yet what will come of the previously published artifacts. This is going to be a nightmare. In the meantime, we should publish to Maven Central from now on.

**Comment by gzm0** [comment]
Is there already some work on how sbt cross versions will map to maven? Or is this not necessary anymore since sbt 1.x? (IIUC, some ivy metadata something something for sbt cross versioning was the reason `sbt-scalajs` even is on bintray, right?).

**Comment by sjrd** [comment]
It has always worked, because sbt contains some magic to turn sbt-plugin-like metadata into Maven subdirectories. We even already use this mechanism for some of our later sbt plugins, for example:
https://repo1.maven.org/maven2/org/scala-js/sbt-jsdependencies_2.12_1.0/1.0.2/sbt-jsdependencies-1.0.2.jar
It's good enough for Maven per se, although Sonatype OSSRH gets confused about it in some cases (for example: it's impossible to check the download stats of sbt plugins published on Maven Central).

**Comment by EnverOsmanov** [comment]
Would be nice to have at least 1 version of 0.x.x on Maven Central to be able to compile old projects without migration of the code base to 1.x.x.

**Comment by sjrd** [comment]
I'm sorry, but we are not going to do this. Scala.js 0.6.x was EOL'ed 17 months ago.
