### ISSUE TITLE
java.lang.Class.getSimpleName() returns bad results for local classes

### ISSUE THREAD

**Issue by davidhulse** [scala-js/scala-js#4434]
When I call the Class.getSimpleName method, the return value is always "1".

scala versions: 2.12.12 and 2.13.4
scala-js versions: 1.4.0 and 1.5.0
sbt version: 1.4.6

I have the following code

```
package com.example

class packageSpec {

  def test() = {

    case class Test() 

    val test = Test()

    println(test.getClass.getName)
    println(test.getClass.getSimpleName")
  }
}
```

When compiled and run against the JVM, the output is

```
com.example.packageSpec$Test$1
Test$1
```

When compiled and run against JS, the output is

```
com.example.packageSpec$Test$1
1
```

**Comment by sjrd** [comment]
What is `packageSpec`?

**Comment by davidhulse** [comment]
`packageSpec` is the unit test class wrapped around the above code in my project
