### ISSUE TITLE
Different macro expansion behavior for managedSource (generated Scala code)

### ISSUE THREAD

**Issue by xerial** [scala-js/scala-js#4446]
## Problem

Probably since Scala.js 1.4.0 or 1.5.0 (I'm using sbt 1.4.7), if we generate Scala code that uses some Scala macros library (cross-built for ScalaJVM and Scala.js), macro expansion uses ScalaJVM specific dependencies, instead of Scala.js dependencies. This issue happens only when compiling sources contained in managedSources. 

## Expectation
Compilation of managedSources should use Scala.js dependencies so that Scala.js specific source code can be generated via Scala macros. 

## Minimization (TODO)

Currently, this issue happens to a large project using sbt-airframe https://wvlet.org/airframe/docs/airframe-rpc#sbt-airframe-plugin. I'll try to produce a minimization of this issue.

**Comment by sjrd** [comment]
Scala.js doesn't deal with any of that. It doesn't deal with macros, doesn't see separate source directories, and only sees the dependencies that you give it. It is very unlikely that this is an issue in Scala.js.

**Comment by xerial** [comment]
I'm not sure the current execution order. It seems just running the compilation task alone works. But after running fastLinkJS, it fails with an error: Referring to non-existent class scala.reflect.api.TypeTags$TypeTag, which is used in some dependent macro library for JVM.

**Comment by xerial** [comment]
I've found the cause. A library dependency was using '%%' (not '%%%') so JVM version of macro dependency was involved in the classpath. It's not a bug.
