### ISSUE TITLE
scalajs-compiler for Scala 2.13.5 is not published for Scala.js 1.0.0

### ISSUE THREAD

**Issue by sideeffffect** [scala-js/scala-js#4461]
The artifact `scalajs-compiler_2.13.5` is not published for Scala.js 1.0.0, like `scalajs-compiler_2.13.4` is:
https://repo1.maven.org/maven2/org/scala-js/scalajs-compiler_2.13.4/

`scalajs-compiler_2.13.5` is published for Scala.js >= 1.5 only:
https://repo1.maven.org/maven2/org/scala-js/scalajs-compiler_2.13.5/

It seems like an oversight and that it should be published for 1.0.0 (and other versions <= 1.5) too.

**Comment by sjrd** [comment]
It's not an oversight. We cannot publish older versions for 2.13.5 because of an internal breaking change.

See https://www.scala-js.org/news/2021/02/12/announcing-scalajs-1.5.0/

> Scala.js 1.5.0 adds support for the imminent Scala 2.13.5. **Previous versions of Scala.js, including Scala.js 0.6.x, will not work with Scala 2.13.5+.**
