### ISSUE TITLE
Missing java.util.BitSet

### ISSUE THREAD

**Issue by szeiger** [scala-js/scala-js#4463]
It would be useful to have a `java.util.BitSet` implementation. It looks like most Java collections are available but this one fell through the cracks (perhaps because it's not part of the `Collection` hierarchy).

**Comment by sjrd** [comment]
There is a PR https://github.com/scala-js/scala-js/pull/4217 but it has stalled. Would you like to pick it up?

**Comment by jyoo980** [comment]
@sjrd I'd be interested in picking this up. I'm wondering how best to copy over the work that's already been done, though.

**Comment by sjrd** [comment]
Whatever you see fit. You can fetch the PR branch and rebase, or just create a new branch from master and manually copy paste. It doesn't matter. In the end we'll need a squashed commit sitting in top of a recent commit from master anyway.

It would probably be nice of you too include the appropriate `Co-Authored-By` line in the commit message.

**Comment by jyoo980** [comment]
> Whatever you see fit. You can fetch the PR branch and rebase, or just create a new branch from master and manually copy paste. It doesn't matter. In the end we'll need a squashed commit sitting in top of a recent commit from master anyway.
> 
> It would probably be nice of you too include the appropriate `Co-Authored-By` line in the commit message.

Sounds like a plan

**Comment by er1c** [comment]
@jyoo980 I just updated the PR

**Comment by gzm0** [comment]
Fixed in c0be6b6bb7e579ae6381648673a8faac1386ecf6
