### ISSUE TITLE
java.lang.ref.WeakReference and friends

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#4477]
In https://github.com/scala-js/scala-js/tree/v1.5.1/javalanglib/src/main/scala/java/lang/ref we have "implementations" of `WeakReference` and its friends, `SoftReference` and `PhantomReference`. However, they are completely wrong, since they hold *strong* references to their referent. They were added in 2014, when our standards for compliance were really low:
https://github.com/scala-js/scala-js/commit/2bd2f173e0643a1abc344e3509848be90d749ded

Now that ECMAScript has `WeakRef`s, we can actually implement `WeakReference` in a compliant way. We can even make it correctly work with a `ReferenceQueue`. However, that *requires* `WeakRef`s to be available, i.e., ES 2021.

`SoftReference` and `PhantomReference`, however, still cannot be implemented.

`java.util.WeakHashMap` (#3503) can/should be implemented on top of `WeakReference`.

---

What should we do about those? Even ignoring the status quo, the ideal design is not clear.

We could implement `WeakReference`, `Reference` and `ReferenceQueue` only, in the core. But since they require `WeakRef`s, we would have to either
* make them crash at run-time if `WeakRef` is not available
* make them crash at run-time if `esVersion < ES2021`

We could also invent some kind of annotation to put on a class, that would make it fail to *link* if `esVersion < ES2021`.

An alternative would be to *not* put them in the core, but only in a third-party library. Adding that library in a project would be an implicit promise that `WeakRef`s are available.

Given the status quo, there are even more issues:
* What do we do about `SoftReference` and `PhantomReference`
* Should we "gracefully degrade" `WeakReference` to use a strong reference if `WeakRef` is not available (preserving the status quo)?
* We *can* move them to a separate library without creating a binary compatibility schism, but that does not invalidate the above two challenges.

---

To bootstrap the debate, my proposal would be to create *two* libraries:

`scalajs-weakreferences` would be a compliant implementation that assumes ES2021. It would contain `Reference`, `WeakReference`, `ReferenceQueue` and `WeakHashMap`, and assume that `WeakRef`s are available.

`scalajs-fake-weakreferences` would be a non-compliant implementation that preserves the status quo for codebases that currently rely on `WeakReference`s, `SoftReference`s and/or `PhantomReference`s to link and not crash without `WeakRef`s.

We would document `scalajs-weakreferences` as the normal way to get access to these features. `scalajs-fake-weakreferences` would be there as a stop-gap binary compatible alternative.

Opinions?

**Comment by gzm0** [comment]
Do we have any idea for how much of the JDK we will have a similar problem (as in we *must* have an underlying JS API to (reasonably) provide the required semantics)? I'm trying to gauge if per-API ad-hoc solutions are the right way to go here.

**Comment by sjrd** [comment]
From the APIs that already (incorrectly) implemented in this repo, AFAICT, `java.lang.ref.*` is the only one.

For other APIs that we have not implemented yet, it's hard to be sure that there will never be another one. But judging from [the current list of ECMAScript proposals](https://github.com/tc39/proposals), I don't see anything that is fundamentally providing new semantics that we would need in a JDK API. There is `Temporal`, but it would be used by `java.time`, which is already implemented as a separate library today.

**Comment by gzm0** [comment]
Ok, I think in that case, what you propose seems reasonable.

It does raise the question whether we want to support link time validation of ES library levels, but that's orthogonal to this issue at that point.
