### ISSUE TITLE
FullLink Scala.js-specific minifier

### ISSUE THREAD

**Issue by dispalt** [scala-js/scala-js#4482]
Since modules are now supported and work great with scala.js, but don't work great with the Closure compiler, and apparently won't ever work with it.  I think it would be great to have some sort of simple property name minifier.  Current, good javascript minifiers do well with ES imports and are able to tree shake most of the unused stuff. They do well with class name minification as well.  However, where they fail is property minification.  

In scala.js we have access to a lot more semantic information so it might not be too tough to create a simple minification of property names, I think it would drastically reduce the output javascript size.  Today the code is pretty compressable but it could be a lot better.

Another option could be some guidance on how to pass the right parameters to something like Terser if there were some conventions that were universally applicable. https://terser.org/docs/api-reference.html#mangle-properties-options

**Comment by gzm0** [comment]
Explanation of how mangling works: in terser: https://terser.org/docs/cli-usage#cli-mangling-property-names-mangle-props

**Comment by cquiroz** [comment]
I tried this and got a nice size reduction. However (I think this is expected) it doesn't work with dynamic loading. I think it won't know what names to call on the other js files if they are mangled independently

**Comment by dispalt** [comment]
@cquiroz if you are talking about `js.dynamicImport` it worked for me with webpack 5.  This is bundler specific, because it's highly dependent on how the bundler processes files, and nameCache being the "big" feature that makes it work.

**Comment by garhirunrat** [comment]
> @cquiroz if you are talking about `js.dynamicImport` it worked for me with webpack 5. This is bundler specific, because it's highly dependent on how the bundler processes files, and nameCache being the "big" feature that makes it work.

It works but not ideal, still need a solution for mangle properties `reserved` and `regex`.

**Comment by gzm0** [comment]
I've had a look at the terser options, and it seems we should be able to make it work with Scala.js:

Doc: https://terser.org/docs/api-reference#mangle-properties-options

- It supports closure style property renaming based on quoting (`mangle.properties.keep_quoted: "strict"`)
- It supports rewriting an existing source map.
- It supports not renaming top-level definitions.
- It supports reserved identifiers (which we might need for global scope idents in modules).
- It supports reserved properties (which we might need to avoid name clashes with exports).
- It supports multiple files as input.

Unclear to me is how to best integrate. To integrate it externally (based on the linking report only), we need to expose quite a bit of the guts of the linker:

- optimizeBracketSelects = false
- trackAllGlobalRefs = true (and add to report)
- assemble all required exported properties (unclear whether these need to be all to avoid clashes, or only the [ones for the corejslib](https://github.com/scala-js/scala-js/blob/e41949e96b91fb4d48e65e3cd9a15b57e518d673/linker/jvm/src/main/scala/org/scalajs/linker/backend/closure/ClosureLinkerBackend.scala#L254-L284)).

On the flipside, we wouldn't have to do anything for sourcemaps.

**Comment by viktor-podzigun** [comment]
Actually, multiple modules may also work with Clojure Compiler, there is `--chunk` option for some time already (former is `--module`), more details are in this [stackoverflow answer](https://stackoverflow.com/a/10401030/2992304). Basic idea is to specify multiple output files (modules) along with their dependencies:
```
--js commonfunctions.js
--chunk common:1
--js page1functions.js
--js page1events.js
--chunk page1:2:common
--js page2function.js
--chunk page2:1:common
```
and Scala.js has knowledge about inter-module dependencies, right?

**Comment by sjrd** [comment]
That's not the problem. We've known about that for a while.

The problem is mainly that GCC refuses to consider and preserve `import` statements to "the outside world" that is not under its control.

**Comment by ekrich** [comment]
Is this one of the issues? https://github.com/google/closure-compiler/issues/3707

**Comment by sjrd** [comment]
All the details are already in #3893.

**Comment by viktor-podzigun** [comment]
@sjrd I was thinking of [this limitation](https://github.com/scala-js/scala-js/blob/main/linker/jvm/src/main/scala/org/scalajs/linker/backend/closure/ClosureLinkerBackend.scala#L96) even when module kind is CommonJS.
