### ISSUE TITLE
Errors compiling in Scala 3 for Js, not present on Jvm.

### ISSUE THREAD

**Issue by Rich2** [scala-js/scala-js#4486]
So I'm getting errors when compiling for Scala.js with Scala 3 that I'm not getting when compiling for the Jvm or when compiling with Scala 2.13.6. Unfortunately urgent non- programming work commitments mean I can't try and isolate the issue at the current time. So as a temporary measure I've created a branch [openstrat/jsdiff](https://github.com/Rich2/openstrat/blob/jsdiff) to highlight the issue.

```
bridge generated for member method prolignObj(obj: ostrat.Arr[A], offset: ostrat.geom.ProlignMatrix): ostrat.Arr[A] in
 anonymous class Object with ostrat.geom.Prolign {...} [error]    
which overrides method prolignObj(obj: A, prolignMatrix: ostrat.geom.ProlignMatrix): A in trait Prolign
clashes with definition of the member itself; 
both have erased type (obj: Object, offset: ostrat.geom.ProlignMatrix): Object."
```
Similar error:
```
bridge generated for member method SlateXYT(obj: ostrat.Arr[A], dx: Double, dy: Double): ostrat.Arr[A] in
 anonymous class Object with ostrat.geom.Slate {...}
which overrides method SlateXYT(obj: T, xDelta: Double, yDelta: Double): T in trait Slate
clashes with definition of the member itself;
both have erased type (obj: Object, dx: Double, dy: Double): Object."
```

**Comment by sjrd** [comment]
Issues that are Scala 3-only should be filed in the Scala 3 repo at https://github.com/lampepfl/dotty/issues. Please reopen over there.
