### ISSUE TITLE
FewestModules can result in filenames that are greater than 255 Characters

### ISSUE THREAD

**Issue by dispalt** [scala-js/scala-js#4499]
So I have a private repository where I attempted to break a bunch of scalajs code into modules.  Alot of those modules reference  the same code, so it creates filenames longer than 255 characters which basically no filesystem supports.  I can't share the code but I do feel like someone on the maintainer team would understand how this might happen.  So I switched to smallest modules and the problem went away.

Happy to attempt to put something together but figured I'd file the issue first.

**Comment by gzm0** [comment]
Yeah... The problematic function is here:
https://github.com/scala-js/scala-js/blob/95c6419b2ddce046d7ee59b1b01345748ffd5538/linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/MaxModuleAnalyzer.scala#L53

For internal modules we can pretty much chose whatever ID we want, as long as it is somewhat stable (same code should go into same module ID).

I chose this ID pattern so it's easy to understand the origin. Maybe we need to switch to less human readable IDs.
