### ISSUE TITLE
Scala.js artifacts don’t declare a versionScheme

### ISSUE THREAD

**Issue by julienrf** [scala-js/scala-js#4513]
The Scala.js artifacts don’t declare a versionScheme, therefore I am not sure which conclusions can be drawn from dependency resolution tools.

See e.g. scala/scala-xml#533

**Comment by sjrd** [comment]
How can we do this while will using sbt 1.2.8 ourselves?

**Comment by julienrf** [comment]
The simplest solution regarding the declaration of the versioning scheme would be to upgrade to sbt 1.5. If this is not possible, I guess you would have to add something like:

~~~ scala
Compile / packageBin / artifact ~= _.extra("info.versionScheme" -> "early-semver")
~~~
(untested)
