### ISSUE TITLE
Implement java.util.concurrent.atomic.LongAdder

### ISSUE THREAD

**Issue by adamgfraser** [scala-js/scala-js#4515]
The lack of support for concurrency primitives like this makes it difficult to write cross-platform code. The implementation should be trivial.

**Comment by jgoday** [comment]
Hi, Might I take a look at it?

I am completely new to scala-js, but due js single thread nature:

* Could a naive impl (increment, reset, ...) of java.util.concurrent.atomic.LongAdder be valid ? (and maybe of other concurrent.atomic structures)

* Should be this implement under javalib/src/main/scala/java/concurrent/atomic folder?

**Comment by sjrd** [comment]
> Hi, Might I take a look at it?

Yes, of course.

> Could a naive impl (increment, reset, ...) of java.util.concurrent.atomic.LongAdder be valid ? (and maybe of other concurrent.atomic structures)

Yes.

> Should be this implement under javalib/src/main/scala/java/concurrent/atomic folder?

Yes. And tests should go in `test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/concurrent/atomic/LongAdderTest.scala`.

**Comment by adamgfraser** [comment]
Thank you! 🙏
