### ISSUE TITLE
Omit not needed `| 0` in produced JS

### ISSUE THREAD

**Issue by catap** [scala-js/scala-js#4543]
I have some scala code which make a lot of math.

For example just a pice of code:
```scala
      lastLeftBit = iVal >>> 31
      idx += 1
      i += 1
```
which is compiled to:
```js
      q = E >>> 31 | 0;
      u = 1 + u | 0;
      k = 1 + k | 0
```
everything is `Int`.

Does this really required for something? Can this `| 0` be avoided?

**Comment by sjrd** [comment]
The `| 0` it's really needed to implement correct 32-bit arithmetics.

Also, there are engines, at least V8, I think SpiderMonkey had well, where `(a + b) | 0` is *faster* than `a + b`. That's the because the optimizer can tell that it's an int 32 addition, and not a floating point addition.

**Comment by catap** [comment]
@sjrd any way to force sjs to not add `| 0` at some places?

**Comment by sjrd** [comment]
If you don't believe that those `| 0` are good for you, yes, there are two ways:

* use `Double`s and not `Int`s, or
* change the linker back-end yourself, publishLocal:
  https://github.com/scala-js/scala-js/blob/5370f0eb00044cef744dd7ffa9ccd561503726ba/linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/FunctionEmitter.scala#L2382-L2413

then benchmark.

**Comment by catap** [comment]
@sjrd I just try to understand why a quite complicated function which contains a low of low-level operations is much slower on node.js

The same scala code is working near identical time at JVM and Scala-Native, but in the case of Scala.JS and node it works 10 time longer.

The code made a lot of trivial operations with `Int` and `Long`. I can accept that it is 2 time slower, but 10 confused me.

Or it is expected?

**Comment by sjrd** [comment]
The `Int`s are not the problem. The `Long`s probably are, but other than avoiding having them cross method boundaries too often, there's not much you can do about that. Unless you can avoid `Long`s altogether.

**Comment by catap** [comment]
@sjrd thanks for confirming that.

**Comment by catap** [comment]
As promised, I'd like to share that rewriting this algorithm from `Int` and `Long` to `Short` and `Int` and increasing number of iteration doesn't help. It works for 15% longer than version with `Int` and `Long`.

Anyway, all this version is working about 10 time longer than JVM or Native version. And the last one (Native) has near the same wall clock time, if I use debug build.

=> I doubt that we can do anything here
