### ISSUE TITLE
Console output (e.g., println) not redirected to sbt client

### ISSUE THREAD

**Issue by adpi2** [scala-js/scala-js#4560]
Was: **Logs of `test` not redirected to sbt client**

## Reproduction Steps

```
# project/build.properties
sbt.version = 1.5.5
```

```scala
// plugins.sbt
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.7.0")
```

```scala
// build.sbt
lazy val example = project.in(file("."))
  .enablePlugins(ScalaJSPlugin)
  .settings(
    scalaVersion := "3.0.2",
    libraryDependencies ++= Seq(
      "org.scalameta" %%% "munit" % "0.7.29" % Test
    ),
    Test / scalaJSLinkerConfig ~= (_.withModuleKind(ModuleKind.CommonJSModule))
  )
```

```scala
// src/test/scala/example/ExampleTest.scala
package example

class ExampleTest extends munit.FunSuite {
  test("test 1") {
    assertEquals("123".size, 3)
  }
}
```

1. Start sbt client with `sbt -client`
2. Run `test`

The output is:
```
sbt:example> test
[info] Passed: Total 1, Failed 0, Errors 0, Passed 1
[success] Total time: 1 s, completed Sep 29, 2021 10:37:06 AM
```

## Expected output

```
sbt:example> test
example.ExampleTest:
  + test 1 0.00s
[info] Passed: Total 1, Failed 0, Errors 0, Passed 1
[success] Total time: 0 s, completed Sep 29, 2021 10:37:16 AM
```

## Notes

We probably need to investigate the code in the `sbt-scalajs` to determine if the cause of the bug is there or in sbt.

**Comment by sjrd** [comment]
I can indeed reproduce, and removing `enablePlugins(ScalaJSPlugin)` doesn't expose the same issue. So clearly it is Scala.js-specific. But it is not clear whether it's an issue in sbt-scalajs, or if it is sbt not correctly dealing with alternative `sbt.testing.Framework`s.

**Comment by sjrd** [comment]
From our side, all the test logs are sent through the `Logger`s that are passed to `Task.execute`. See
https://github.com/scala-js/scala-js/blob/ccd8cf09f608b5f6f373664caf965a5ff299c8df/test-adapter/src/main/scala/org/scalajs/testing/adapter/TaskAdapter.scala#L28-L57
I'm not sure what else we could possibly do.

**Comment by sjrd** [comment]
This is actually MUnit-specific. If I add a JUnit test like
```scala
package example

import org.junit.Assert._
import org.junit.Test

class SomeJUnitTest {
  @Test def test1(): Unit = {
    assertEquals(3.0, scala.scalajs.js.Math.sqrt(9), 0.0)
  }
}
```
with the additional sbt settings
```scala
lazy val example = project.in(file("."))
  .enablePlugins(ScalaJSPlugin, ScalaJSJUnitPlugin)
  .settings(
    scalaVersion := "3.0.2",
    libraryDependencies ++= Seq(
      "org.scalameta" %%% "munit" % "0.7.29" % Test
    ),
    Test / scalaJSLinkerConfig ~= (_.withModuleKind(ModuleKind.CommonJSModule)),
    testOptions += Tests.Argument(TestFrameworks.JUnit, "-a", "-s", "-v"),
  )
```
then `sbt` non-client shows
```
sbt:example> test
example.ExampleTest:
  + test 1 0.00s Test / loadedTestFrameworks 0s
  + test 2 0.00s
[info] Test run started
[info] Test example.SomeJUnitTest.test1 started
[info] Test run finished: 0 failed, 0 ignored, 1 total, 0.004999936s
[info] Passed: Total 3, Failed 0, Errors 0, Passed 3
[success] Total time: 2 s, completed Sep 29, 2021 1:04:07 PM
```
and `sbt -client` shows:
```
sbt:example> test
[info] Test run started
[info] Test example.SomeJUnitTest.test1 started
[info] Test run finished: 0 failed, 0 ignored, 1 total, 0.004s
[info] Passed: Total 3, Failed 0, Errors 0, Passed 3
[success] Total time: 2 s, completed Sep 29, 2021 1:04:24 PM
```
So I think this is an issue with MUnit.

/cc @olafurpg

**Comment by olafurpg** [comment]
MUnit uses `println` by default instead of the sbt logger. You can enable the sbt logger with

```scala
// build.sbt
Test / testOptions ++= List(Tests.Argument(TestFrameworks.MUnit, "+l"))
```

The sbt logger inserts an `[info]` prefix to messages that makes it awkward to copy-paste the output from diff assertions (which include copy-paste friendly syntax of the new obtained/actual output).

**Comment by sjrd** [comment]
Indeed, the `+l` option makes it work. Thanks!

That sent me in the direction of `println`. And indeed, text sent to `println` is not forwarded when using `sbt -client`. That also applies in `run`, not just in `test`.

The default behavior of `NodeJSEnv` (and other `ExternalJSEnv`s) is to inherit its IO for the standard output and standard error. Is that not what `sbt -client` does for the JVM? How does it do it?

**Comment by sjrd** [comment]
And here is how the first option looks like, at least in this repo: #4580. It also fixes the issue.
However that does not answer the question of what to do with `inheritOutput` and `inheritError` in SeleniumJSEnv.

**Comment by sjrd** [comment]
> However that does not answer the question of what to do with `inheritOutput` and `inheritError` in SeleniumJSEnv.

It is actually possible to bypass the redirections of `System.out` and `System.err` with `java.io.FileDescriptor`. We can replace
https://github.com/scala-js/scala-js-env-selenium/blob/afde640661b359483ad13868d4c2904a174e018e/seleniumJSEnv/src/main/scala/org/scalajs/jsenv/selenium/OutputStreams.scala#L21-L22
by
```scala
    val out = outp.fold[OutputStream](new UnownedOutputStream(new FileOutputStream(FileDescriptor.out)))(_._2)
    val err = errp.fold[OutputStream](new UnownedOutputStream(new FileOutputStream(FileDescriptor.err)))(_._2)
```
and that will force the Selenium JS env to print to the true stdout/stderr, irrespective of any redirection set up by `System.set{Out,Err}`.

**Comment by gzm0** [comment]
I agree that #4580 is the cleaner solution and it seems that we can actually make it work. So we probably want to go with that one.
