### ISSUE TITLE
IR checking error with scala-java-time

### ISSUE THREAD

**Issue by mattyjbrown** [scala-js/scala-js#4601]
Using [scala-java-time](https://github.com/cquiroz/scala-java-time) and ScalaJS 1.7.1, `sbt fullOptJS` fails with at something with the following code:

```
    import java.time.ZonedDateTime
    import java.time.format.DateTimeFormatter

    val formatter: DateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSSz")
    val s = formatter.format(ZonedDateTime.now())
    println(s)
```

with the error

```
[error] file:/home/runner/work/scala-java-time/scala-java-time/core/js/target/scala-3.0.0/src_managed/main/org/threeten/bp/format/DateTimeFormatterBuilder.scala(1536:4:Labeled): any expected but <notype> found for tree of type org.scalajs.ir.Trees$Block
[error] There were 1 IR checking errors.
```

External library in question is the recommended `java-time` library, and this is also raised as an issue there in case it helps:
https://github.com/cquiroz/scala-java-time/issues/319

The `match` I believe is causing the error (unless my IDE has dragged up the wrong source files): https://github.com/cquiroz/scala-java-time/blob/9d646d1fad57d318894eb823bbae4e03a66a1fb7/core/shared/src/main/scala/org/threeten/bp/format/DateTimeFormatterBuilder.scala#L1537

Minimal reproduction sbt project here: https://github.com/mattyjbrown/scalajs-minimal-repro

**Comment by sjrd** [comment]
Thank you for the report :)

**Comment by sjrd** [comment]
I started digging into this.

First, none of this can be reproduced with Scala 2.x. This is only reproducible with Scala 3.0.0. I still think it belongs to this repo, however, as I explain below.

I'm pretty sure this is "caused" by 3601272fd49d56d452e2b252d0ee171922031e00. I can reproduce the issue with Scala.js 1.6.0+, but not with Scala.js 1.5.1. That commit strengthened checking of trees in statement positions.

The good news is that Scala 3.1.0 already fixes the root issue of emitting invalid trees, just like the scalac plugin of Scala.js 1.6.0 fixed the root issue. So code compiled with Scala 3.1.0 will correctly link.

The bad news is: why does our deserialization hack not apply to the code emitted by Scala 3.0.0? There must be something about the shape of trees by Scala 3.0.0 that is not caught by our deserialization hack. This is what we need to identify and fix, and this is why this issue belongs to this repo. (It's going to be a pain to test, if not plain impossible.)

**Comment by sjrd** [comment]
OK, this is ironic: if I disable the hack altogether, we can read and validate the IR produced by Scala 3.0.0. So, in fact, Scala 3.0.0 was already producing valid IR. But the deserialization hack transforms it in a way that makes it invalid (sic!). Scala 3.1.0 doesn't do anything different, but since it emits IR version 1.7, it is not transformed by the deserialization hack, and so it remains valid.

I think this is because the hack does not apply to `Labeled` nodes.

**Comment by sjrd** [comment]
## Workaround

The deserialized IR can be linked and emitted despite being invalid due to this bug. It is only the IR checker that is complaining. It is not enabled by default in `fastOptJS`, but it is in `fullOptJS`. The IR check can be disabled for `fullOptJS` with the following sbt settings:
```scala
Compile / fullOptJS / scalaJSLinkerConfig ~= { _.withCheckIR(false) },
Test / fullOptJS / scalaJSLinkerConfig ~= { _.withCheckIR(false) },
```
