### ISSUE TITLE
0/0 should throw an exception

### ISSUE THREAD

**Issue by Atry** [scala-js/scala-js#4604]
```
def f() = {
  0/0
  println("unreachable code")
}

f()
```
I expect `f()` should throw an exception, but it does not actually throw an exception.
https://scastie.scala-lang.org/fbBfZpNVTEqb9B3LLrKAeg

## Workaround
```
def zeroDivZero() = 0/0

def f() = {
  zeroDivZero()
  println("unreachable code")
}

f()
```
https://scastie.scala-lang.org/FIBOOIQhRHWS37Ze49szJg
Now the exception can be thrown as expected

## Scala.js version
1.7.0
## Scala version
This bug is reproducible in both Scala 3.1.0 and Scala 2.13.7

**Comment by sjrd** [comment]
Thanks for the report.
