### ISSUE TITLE
Proposal: Make strict-floats the default, and deprecate non-strict floats

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#4612]
By default, Scala.js uses non-strict floats: floats can behave like doubles, in some places, in unpredictable ways. This can manifest itself in several ways:

* Float values may have more precision than expected
* Float computations may have more precision than expected
* Values that cannot be represented in 32-bit floats may answer `true` to `x.isInstanceOf[Float]`, and remain unchanged through `asInstanceOf`
* A Float value stored somewhere (for example in an array), then retrieved, may come back *different* from what it was

This was first implemented in 2014 in #1194. At the time, `Math.fround` was not yet commonly available, and ECMAScript 2015 had not even be finalized. Moreover, we targeted ECMAScript 5.1 by default, in which `fround` must be polyfilled with an expensive operation.

In addition, the JVM specification itself did not mandate strict 32-bit precision for float computations by default. (Although it would always *store* floats with 32-bit precision.) That gave us an additional license to have non-strict floats.

---

Today, a number of things have changed:

* We emit ECMAScript 2015 by default, which supports `Math.fround`
* VMs have been supporting `Math.fround` for several years, even before they supported all of ES 2015
* [Java 17 restored strict floating point operations everywhere](https://openjdk.java.net/jeps/306)
* We went through great lengths recently to provide exact 32-bit float accuracy for library methods such as `parseFloat` and core operations such as `Long.toFloat`

Given the above, I think that still defaulting to non-strict floats today has become a liability in the design.

---

I propose that:

* We make strict-floats the default in `Semantics`
* Deprecate `Semantics.withStrictFloats`, saying that strict-floats are now the default, and that non-strict float behavior will eventually be removed
* Eventually, in a future version, remove all code that deals with non-strict floats, and use strict-float semantics regardless of the value of `Semantics.strictFloats`

The last item is technically a backward incompatible change. Most aspects of non-strict floats are unspecified (they may or may not behave like actual floats), so we can make them behave like strict floats without breaking the spec. However, there is one thing that *is* specified: `x.isInstanceOf[Float]` is supposed to return `true` in non-strict float semantics when `x` is a valid Double but cannot be represented with 32 bits. Hopefully, if that change is an actual issue, we will find out about it long before we actually remove the non-strict float code from the codebase.

@gzm0 and others, WDYT?

**Comment by gzm0** [comment]
Overall, agreed, two points though:

> However, there is one thing that is specified: x.isInstanceOf[Float] is supposed to return true in non-strict float semantics when x is a valid Double but cannot be represented with 32 bits.

This feels like a specification bug: Shouldn't `isInstanceOf` check whether the receiver can be represented in the platform's representation of the target type?

Do we have any idea about the performance implications of this? (I assume size changes are minor if ES6 is assumed).

**Comment by sjrd** [comment]
> > However, there is one thing that is specified: x.isInstanceOf[Float] is supposed to return true in non-strict float semantics when x is a valid Double but cannot be represented with 32 bits.
> 
> This feels like a specification bug: Shouldn't `isInstanceOf` check whether the receiver can be represented in the platform's representation of the target type?

That specification was intentional and necessary. Otherwise, the following would cause an error:

```scala
def foo(a: Float, b: Float): Any = {
  val c = a * b // can be more precise than expected, and therefore not fit in 32 bits
  val x: Any = c
  x match {
    case x: Float => "ok"
  }
}
```

In other words, something that would have been computed as a Float would not be recognized as a Float after being upcast to `Any`. That would have caused serious issues.

> Do we have any idea about the performance implications of this? (I assume size changes are minor if ES6 is assumed).

Under ES2015, there is basically no size change, and performance can be slightly affected for `isInstanceOf[Float]` checks. Everywhere else, however, even our non-strict floats actually already use `Math.fround` when available, because it was assumed that engines would optimize it appropriately.

Only ES 5.1 should really be affected performance-wise, and only when run on a VM that does not support `Math.fround`. I'll try to run some benchmarks when I get back from vacation (about 2 weeks starting tomorrow).

**Comment by gzm0** [comment]
Ah, that snippet makes sense.

I have been thinking about `asInstanceOf` more in this sense:

```
val x: Any = // double that doesn't fit into a float.

if (x.isInstanceOf[Float])
  println(x.asInstanceOf[Float] == x)
```

Under non-strict floats (but with an implementation that *does* truncate on `asInstanceOf`), this could print `false`, which is counter-intuitive at best.

I think all-in-all, the key takeaway is that non-strict semantics are very hard to properly use in these edge cases, so the proposed plan is OK IMO.

RE performance and code size: If we are already using `Math.fround` even in non-strict mode, I'm not sure its even necessary to benchmark all that. Feel free to do it, of course, if you see the need.

**Comment by sjrd** [comment]
I added a version of the `tracer` benchmark that uses `Float`s instead of `Double`s here: https://github.com/sjrd/scalajs-benchmarks
I don't see any conclusive difference between sloppy floats and strict floats, so I think we should be good.

There is some significant difference, especially on V8 (not Firefox), wrt. replacing `$fround` by an identity function. That suggests that sloppy floats should in fact *not* use `Math.fround` when it's available. That said, we can also close quite a lot of the gap by replacing `$fround` by `Math.fround`. Currently we have
```js
var $fround = Math.fround;
// then, use everywhere:
$fround(x)
```
but it is significantly better to directly use `Math.fround` everywhere (again, especially on V8). This is probably because the engines optimize direct calls of the form `Math.fround(x)` better than `$fround(x)` where `$fround` happens to be `Math.fround`. Intuition would go in the other way, because we would think the engine could see that `$fround` is *never* going to change, and therefore optimize accordingly. Whereas *both* `Math` *and* `Math.fround` could be changed at run-time. But the engines must be doing some alternative strategy, probably based on the global *assumption* that `Math.fround` will always be what it's supposed to be, and globally invalidate that everywhere if and when it does change.

I guess the same applies to `Math.imul` and `Math.clz32`, which we should also inline when target ES2015.
