### ISSUE TITLE
Null-or-Undefined property not produced on Scala 3

### ISSUE THREAD

**Issue by exoego** [scala-js/scala-js#4615]
* Scala.js 1.8.0

```scala
val obj = new js.Object {
  var foo = js.undefined
  var bar = null
}
println(js.Object.hasProperty(obj, "foo"))
println(js.Object.hasProperty(obj, "bar"))
```

On Scala 2.13.7 and 2.12.15,
```
true
true
```

However on Scala 3.1.0,
```
false
false
```

I expect properties (`foo` and `bar` in the above example) should be produced even if its value is `null` or `undefined`.

**Comment by sjrd** [comment]
If it is a problem with Scala 3 only, please report at https://github.com/lampepfl/dotty/issues instead.

**Comment by exoego** [comment]
Reported https://github.com/lampepfl/dotty/issues/14168
Closing
