### ISSUE TITLE
Better dead code elimination (including possibly removing .toString from case classes)

### ISSUE THREAD

**Issue by strelec** [scala-js/scala-js#4626]
Let's start with a simple example:

We have a case class, that is never put in a `Map` as key, or any other operation that requires the computation of the `hashCode`.
So, technically, even though `hashCode` is technically defined on `Any`, it can be eliminated for this case class.

We are also assuming that `hashCode` is never called on `Any`, as that would make this optimization much more complex, as we would need to do flow/escape analysis to make sure the case class never reaches that point in code. I am merely suggesting the most basic version.

I think this optimization could potentially be used to remove `toString` definitions for better obfuscation, however this is trickier, as it is very easy to introduce usages on `Any` (or unbound type) by doing string concatenation (for example in exception messages).

How hard is it to make such optimization work, and why is Closure compiler not doing it already?

**Comment by sjrd** [comment]
This is not possible. Due to the erased nature of the Scala type system, the `Map` is always a `Map[Any, Any]`. So it does call `hashCode()` on `Any`, and that makes it reachable for all classes. The same applies to `toString()`.
