### ISSUE TITLE
.mjs file extension for ESModule output

### ISSUE THREAD

**Issue by shishkin** [scala-js/scala-js#4631]
When running with ESModule setting, scalajs linker outputs files with `.js` extension. In absence of a `package.json` file, Node runs `.js` modules in CommonJS mode and thus fails to run Scala.js ESM output by default.

If linker would name output files with `.mjs` file extension instead, [Node would run them](https://nodejs.org/api/esm.html#enabling) without issues.

**Comment by sjrd** [comment]
You can already do this with the following sbt setting:
```scala
scalaJSLinkerConfig ~= { _.withOutputPatterns(org.scalajs.linker.interface.OutputPatterns.fromJSFile("%s.mjs")) }
```
It won't be the default since the `.mjs` extension is non-standard and Node.js-specific.

**Comment by gzm0** [comment]
Also see the section "ES modules and Node.js" at https://www.scala-js.org/doc/project/module.html
