### ISSUE TITLE
Improved Basic Tutorial Requested

### ISSUE THREAD

**Issue by kolotyluk** [scala-js/scala-js#4664]
On https://www.scala-js.org/doc/tutorial/basic/ after

> First create a new folder where your sbt project will go.

It would be more helpful if there were an example of what sbt command to run. For example, I tried

    sbt new

which started with

> eric.kolotyluk@Y2RCV7009N makemake % sbt new
> copying runtime jar...
> [info] [launcher] getting org.scala-sbt sbt 1.6.2  (this may take some time)...
> [info] [launcher] getting Scala 2.12.15 (for sbt)...
> [info] welcome to sbt 1.6.2 (Oracle Corporation Java 17.0.1)

However, this does not do anything, the project directory is empty. From https://docs.scala-lang.org/getting-started/sbt-track/getting-started-with-scala-and-sbt-on-the-command-line.html the example is

    sbt new scala/hello-world.g8

So, my expectation is that for Scala.js the example should be something like

    sbt new scalajs/basic-tutorial.g8

as in https://www.scala-sbt.org/1.x/docs/sbt-new-and-Templates.html or https://github.com/vmunier/play-scalajs.g8

Instead, the tutorial just dives into more advanced sbt topics... 🙄

**Comment by sjrd** [comment]
> First create a new folder where your sbt project will go.

Oh, that is supposed to mean creating a an empty folder, without sbt:

    $ mkdir hello-world

Arguably, we could add that command to the tutorial. But that should be an issue (or a PR) to https://github.com/scala-js/scala-js-website instead of this repo.

About the g8 template, there is already an open issue at #4390.
