### ISSUE TITLE
ES2021 not supported in fullLinkJS

### ISSUE THREAD

**Issue by Lasering** [scala-js/scala-js#4675]
When running `fullLinkJS` with the following option set in sbt:
```
scalaJSLinkerConfig ~= { _.withESFeatures(_.withESVersion(ESVersion.ES2021)) }
```
I get the error `Unknown ES version ECMAScript 2021 (edition 12)`.

Probably when [this code](https://github.com/scala-js/scala-js/blob/main/linker/jvm/src/main/scala/org/scalajs/linker/backend/closure/ClosureLinkerBackend.scala#L71) was written the Google Closure Compiler didn't support ES2021 but now it seems [it does](https://github.com/google/closure-compiler/wiki/Releases#august-8-2021-v20210808).

**Comment by sjrd** [comment]
Thanks for the report. Looks like a bug, indeed.
