### ISSUE TITLE
Improve `js.Promise` facade

### ISSUE THREAD

**Issue by fdietze** [scala-js/scala-js#4678]
Currently, the facade for `js.Promise` is implemented as a class:

https://github.com/scala-js/scala-js/blob/main/library/src/main/scala/scala/scalajs/js/Promise.scala#L45

But in Typescript, it's modeled as an interface, separately from the constructors:

https://github.com/microsoft/TypeScript/blob/main/lib/lib.es5.d.ts#L1446

This results in transpilation problems in ScalablyTyped, where a typescript facade wants to implement the `Promise` **interface** but instead tries to inherit from a **class** requiring a constructor:

https://github.com/ScalablyTyped/Converter/issues/404#issuecomment-1023659519

The relevant parts of generated code look like this:

```typescript
// generated valid typescript code
export type PrismaPromise<A> = Promise<A> & {[prisma]: true}
export class Prisma__WorkspaceClient<T> implements PrismaPromise<T> {
    [prisma]: true;
...
```

```scala
// transpiled to Scala
@js.native
trait PrismaPromise[A] extends js.Promise[A]

@JSImport("generated-prisma-client", "Prisma.Prisma__WorkspaceClient")
@js.native
class PrismaWorkspaceClient[T] protected () extends PrismaPromise[T] {
...
```

compile error:
```
[error]      not enough arguments for constructor Promise: (executor: scala.scalajs.js.Function2[scala.scalajs.js.Function1[T | scala.scalajs.js.Thenable[T], _], scala.scalajs.js.Function1[Any, _], _]): scala.scalajs.js.Promise[T].
[error]      Unspecified value parameter executor.
[error]      L16: class PrismaWorkspaceClient[T] protected () extends PrismaPromise[T] {
[error]                                                            ^
```

I'm wondering if we could improve the Promise facade to be more similar to the typescript facade, which is probably also closer to the specs.

For reference, the `Promise` specification:
https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-properties-of-the-promise-prototype-object

**Comment by oyvindberg** [comment]
Thanks for filing this. I started towards a PR for this, but ran out of steam before i got to the motivation part. What you wrote pretty much covers it.

Here is my WIP https://github.com/oyvindberg/scala-js/commit/adee19f9e06f9236e71684a96b0a4752e6e2d1fe

I'm mostly curious if this approach is backwards compatible.

**Comment by sjrd** [comment]
The specification you linked clearly establishes that `js.Promise` is a class. Anything that wants to pretend it's not a class is at odds with the specification.

The corresponding interface is `js.Thenable`.

**Comment by fdietze** [comment]
> The specification you linked clearly establishes that `js.Promise` is a class.

How do you draw this conclusion? Do you mean the first sentence?

> A Promise is an object that ...

Object to me sounds more like an object instance or a prototype from prototype inheritance. But I'm not sure if I interpret it correctly.

If it is definitely a class, then you would say that the Typescript facades are wrong?

Classes and Promises were introduced in ES2015/ES6 (https://en.wikipedia.org/wiki/ECMAScript#ES2015), so after ES5. But the ES5 types contain the interface definitions, the ES2015 types are using: https://github.com/microsoft/TypeScript/blob/main/lib/lib.es2015.promise.d.ts#L21

Was that just a practical consideration from their side, that is compatible with ES6 classes?

**Comment by sjrd** [comment]
> > The specification you linked clearly establishes that `js.Promise` is a class.
> 
> How do you draw this conclusion? Do you mean the first sentence?

From the existence of [The Promise Constructor](https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-promise-constructor). If something has a constructor, it's a class (these two ideas are one and the same thing in ES).

> If it is definitely a class, then you would say that the Typescript facades are wrong?

It depends on your (and their) definition of correct or wrong. What I can tell you is that making it a trait in Scala.js would be wrong for the definition of Scala.js.

**Comment by sjrd** [comment]
The changes in that commit seem to all be

* either redundant, as there is already a constructor where all params have default values,
* or incorrect wrt. the spec, because the spec requires a non-`undefined` parameter to be passed.

If we extend those classes with non-native JS classes, it is important that the type system prevents us from doing the wrong thing.

If we extend them from native JS classes, recall that you can always fill in the super constructor args with `js.native`, if you don't want to provide something else.

**Comment by oyvindberg** [comment]
Ok, thanks. A scala implementation of Promise was absolutely not something I considered, but it's a fair point. With that constraint I suggest we close this issue.

I suppose I can make this work on my side by analyzing the inheritance hierarchy for every class and infer an `extends js.Promise(js.native, js.native) with <original inheritance>`. I'll likely skip that work and just use `js.Thenable` instead.
