### ISSUE TITLE
Unit JS default param makes compiler crash with "Found a dangling UndefinedParam"

### ISSUE THREAD

**Issue by armanbilge** [scala-js/scala-js#4684]
```scala
//> using scala "2.13.8"
//> using platform "js"

package foo

import scala.scalajs.js

@js.native
trait Bar extends js.Object {
  protected[foo] def baz(
    dummy: Unit = js.native,
  ): Unit = js.native
}

object App {

  def bar: Bar = ???

  def main = bar.baz()

}
```

```
[error] ./bug.scala:15:1: Found a dangling UndefinedParam at Position(file:/workspace/sandbox/bug.scala,18,17). This is likely due to a bad interaction between a macro or a compiler plugin and the Scala.js compiler plugin. If you hit this, please let us know.
```

Scala 3 sibling issue:
- https://github.com/lampepfl/dotty/issues/15419

**Comment by gzm0** [comment]
I can reproduce this on all major Scala versions. Thank you for the report.

**Comment by gzm0** [comment]
Note: Package private is not required. Plain old public method also causes the issue.

**Comment by armanbilge** [comment]
Interesting, it may have been needed for my Scala 3 reproduction since that's where I started from.

**Comment by gzm0** [comment]
I think the issue is the `Unit` value: The generated IR that crashes is:

```
def main;V() {
  val qual$1: any = this.bar;Lhelloworld.Bar();
  val x$1: java.lang.Void = {
    <undefined-param>;
    (void 0)
  };
  qual$1["baz"](x$1)
}
```

**Comment by gzm0** [comment]
FWIW: Indeed changing the argument type to `Int` makes the issue vanish.

**Comment by sjrd** [comment]
Ouch. I guess the scalac (and dotc) tree that comes right before that is
```scala
val x$1: BoxedUnit$ = {
  qual$1.baz$default$1();
  BoxedUnit$.UNIT
}
```
We could recognize that shape and collapse it to a single `<undefined-param>`, but we might be too broad and get false positives with that. Then again, if we don't catch that shape and it's present, it is going to crash anyway instead, so perhaps that's fine.
