### ISSUE TITLE
Add support for Test / envVars

### ISSUE THREAD

**Issue by alexandru** [scala-js/scala-js#4686]
This may be out of scope for an issue, as there may be a workaround that I'm not aware of.

I want to set environment variables in tests:

```scala
Test / envVars := Map(
  "MY_TEST" -> "true",
)
```

Which are then accessible via:

```scala
global.process.env.selectDynamic("MY_TEST").asInstanceOf[js.UndefOr[String]]
```

For the JVM this works in tandem with `Test / fork := true`, however it seems that this is an option that is banned on top of Scala.js:

```
[error] `test / test` tasks in a Scala.js project require `test / fork := false`.
```

I'm guessing this happens because Scala.js has to fork a process anyway, but it appears that the forking ignores the `envVars` setting. Would be great if it didn't.

**Comment by sjrd** [comment]
I'm afraid that's not supported. Not all `JSEnv`s support custom environment variables. For those that do, you can directly configure the `jsEnv` instead. For example:
```scala
import org.scalajs.jsenv.nodejs.NodeJSEnv

jsEnv := new NodeJSEnv(NodeJSEnv.Config().withEnv(Map(
  "MY_TEST" -> "true",
)))
```

**Comment by sjrd** [comment]
Perhaps we could support it, if we added an `env: Map[String, String]` in [`jsenv.RunConfig`](https://github.com/scala-js/scala-js-js-envs/blob/9d46d49310619de3d722b5d3867fa7599b1a5831/js-envs/src/main/scala/org/scalajs/jsenv/RunConfig.scala#L46). But I'm not sure it's worth it.

@gzm0 WDYT?

**Comment by gzm0** [comment]
I would advise against that. The `RunConfig` needs to be handled by all `JSEnv`s. But for many `JSEnv`s environment variables are not meaningful.

What we could do, is configure the default `jsEnv` automatically with `envVars`.

**Comment by sjrd** [comment]
> What we could do, is configure the default `jsEnv` automatically with `envVars`.

Unfortunately, we cannot do that either without some breakage. `jsEnv` is defined in `Global` by sbt-scalajs. So people can set `Global / jsEnv := ...` or `ThisBuild / jsEnv := ...` to specify for their entire build. But `envVars` would be set by project, if not by configuration. We would have to define `jsEnv` by configuration to take `envVars` into account, but that would then break any build that relies on overriding `jsEnv` at the global, this-build or project level.

**Comment by sjrd** [comment]
> I would advise against that. The `RunConfig` needs to be handled by all `JSEnv`s. But for many `JSEnv`s environment variables are not meaningful.

That's not entirely accurate. We do have infrastructure (the `Validator`) for JSEnvs to report that they do not support such or such option in `RunConfig`. It is possible for JS envs that wouldn't support environment variables to report an error with that mechanism.

**Comment by gzm0** [comment]
Hmm... That is not wrong. However, it feels to me that this is not what the validator in `RunConfig` was intended for. I cannot however, pinpoint exactly what that means :-/

My best attempt at this is something like: `RunConfig` is the common interface to all `JSEnv`s and the validator is merely a compatibility mechanism so that we can add requirements at a later point in time. Two things stick out for me here:

- `onOutputStream`, `inheritError`, `inheritOut` are grossly misnamed: They should be talking about `console`, not output streams.
- The only reasonable use-case for a compatibility mechanism like we have it would precisely be an optional additional feature. If it is not an optional feature, we'd break compatibility.

There is one remaining distinction for the compatibility mechanism though:
- Things that can (or even must, by newer ES standards) be provided by JSEnvs and just haven't yet.
- Things that will likely never be supported by some JSEnvs

IMHO env variables clearly falls into the second category. 

Now that being said, maybe this distinction is too theoretical and it just boils down to: Do we think this is a common / important / general enough feature to build support for it into core...

**Comment by sjrd** [comment]
I've been trying to come up with an opinion here, but I'm not sure I am any closer to getting one that when I started. Some specific comments:

>     * `onOutputStream`, `inheritError`, `inheritOut` are grossly misnamed: They should be talking about `console`, not output streams.

That doesn't seem right to me. If one writes data to Node.js' `process.stdout`, they will be captured by `onOutputStream`. If the VM itself crashes or reports VM-wide warnings to stderr, that will also be captured. We're really talking about the std streams. `console` is only one way to write to them.

> My best attempt at this is something like: `RunConfig` is the common interface to all `JSEnv`s and the validator is merely a compatibility mechanism so that we can add requirements at a later point in time. Two things stick out for me here:
> 
> * The only reasonable use-case for a compatibility mechanism like we have it would precisely be an optional additional feature. If it is not an optional feature, we'd break compatibility.

I have a hard time reconciling those two statements. Either it's for optional features, or it's for mandatory features from the future.

Also, if it truly were only about future requirements, why would we have built `supportsInheritIO()` and `supportsOnOutputStream()` in `Validator`? These two features were there in the very first version of the JS envs.

No, IMO `RunConfig` was always meant to support fully *optional* features. And hence it doesn't seem unreasonable to me to add a config option that not all JS envs would be able to support.

> Now that being said, maybe this distinction is too theoretical and it just boils down to: Do we think this is a common / important / general enough feature to build support for it into core...

Now that of course is a different question. Evidently, sbt thought it was common enough to expose it as a task key themselves. But maybe it's more relevant to the JVM than to JS?

I looked at the full list of sbt's keys, and IMO there is only one other key that we do not support, and for which it could make sense to support it: `outputStrategy`. That one specifies where to send the stdout/stderr of the running process. The default is to stdout/stderr--or, as we figured, to `System.out` and `System.err`--but they can also be sent to a `logger`'s `info`/`error` methods, for example. See https://github.com/sbt/sbt/blob/1f29c9053cdc52128fa45cfe0b22e9a4d085cc1b/run/src/main/scala/sbt/OutputStrategy.scala . Interestingly enough, we already have exactly the support in `JSEnv` that we need to implement that one.

**Comment by gzm0** [comment]
I guess this is fair. So maybe we should just build support then?

**Comment by sjrd** [comment]
Yes, I think it would make sense.

**Comment by gzm0** [comment]
I can take a stab at this.

**Comment by sjrd** [comment]
@gzm0 Do you still want to do the sbt plugin side of this feature, now that the JSEnv side is done? Or would you prefer that I do it?

I still have a PR to actually (finally) separate the javalib in its own jar in progress, but otherwise I think we'll be done for 1.11.0.

**Comment by gzm0** [comment]
I have started on this, but likely will not have time any time soon. So feel free to take it over.
