### ISSUE TITLE
How to liberate the javalib from the dependency on js.JavaScriptException?

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#4688]
In the context of #4677, we need to "liberate" the javalib from its dependency on `js.JavaScriptException`. The problem comes from the semantics of a Scala-level `try..catch` and `throw`:

## Reminder: language-level semantics

In the following Scala.js code:
```scala
try {
  body()
} catch {
  case t: Throwable => handle(t)
}
```
the `try..catch` is specified to catch *any* value thrown during `body()`. Because JavaScript is what it is, that can truly be *any* value, including primitives, any JS object, and even any Scala object that's not a `Throwable` (which in that case behaves as a JS object).

When catching something that *is* a `Throwable`, `t` is assigned to that thing. When catching some other value `e`, it is wrapped in a `scala.scalajs.js.JavaScriptException(e)`.

Conversely, in the following code:
```scala
throw t
```
the semantics are specified as: if `t` is a `js.JavaScriptException(e)`, actually throw `e`; otherwise throw `t`.

`js.JavaScriptException` is defined in
https://github.com/scala-js/scala-js/blob/v1.10.0/library/src/main/scala/scala/scalajs/js/JavaScriptException.scala

## Consequence for library-level semantics

To be consistent, library methods that are specified as throwing a given value, or catching anything in a certain code (such as in a function value argument), must follow the same wrapping and unwrapping behavior.

This can be seen explicitly, for example, in the `js.Promise` <-> `Future` adapter:
https://github.com/scala-js/scala-js/blob/6619c4b84c25ab36efdc038be67dddbc56581101/library/src/main/scala/scala/scalajs/js/Thenable.scala#L54-L69

It is also present *implicitly* (through the use of the `throw` keyword) in `java.util.Optional` at
https://github.com/scala-js/scala-js/blob/bbf031451b99380b878af0d729ce12a38d984b3a/javalib/src/main/scala/java/util/Optional.scala#L71-L73

## Problem

The problem with that is that the javalib has an implicit dependency on `js.JavaScriptException`. One that is almost *specced*: if `java.util.Optional.orElseThrow` receives a `js.JavaScriptException` from its `exceptionSupplier`, it *must* throw the wrapped value instead.

Currently, this involves an instance test against `js.JavaScriptException` followed by accessing its underlying `exception` field. So there is a dependency in the IR code.

Conversely, if the JDK added a method such as
```scala
def catchAll(runnable: Runnable): Optional[Throwable]`
```
who was supposed to call `runnable.run()` but catch and return any exception thrown, it would have to *wrap* non-`Throwable`s into a `js.JavaScriptException`.

These dependencies put the independent javalib "project" in jeopardy. By definition, any dependency from the javalib on Scala-defined stuff is forbidden, and `js.JavaScriptException` is not exempted. We *could* have exempted it (with caveats) if `JavaScriptException` were a bare Java-like class. Unfortunately, it is a `case class`, and that means it depends on `scala.Product` and other Scala types. So exempting it is a total no-go for this project.

## What to do about it?

I propose we discuss what we can do about it in this issue. There are two situations we can examine:

* How we could redesign in the best possible way for Scala.js 2.x, free of backward compatibility constraints?
* How we can mitigate the issues in Scala.js 1.x, given the compatibility constraints?

Although there are no plans for anything like a Scala.js 2.x in the foreseeable future, it is still probably good to think about what the ideal design would be, to guide what kind of mitigation would be acceptable.

**Comment by sjrd** [comment]
The least bad solution I have so far, and which I implemented in #4677, solves the *unwrapping* problem for Scala.js 1.x, but not the *wrapping* problem (and it cannot be generalized as is for the wrapping problem).

The idea is to add an internal, protected method to `Throwable`, as follows:
```scala
class Throwable {
  ...

  /* Not part of the JDK API, overridden internally in js.JavaScriptException
   * and used by the javalib IR cleaner to replace calls to
   * `scala.scalajs.runtime.unwrapJavaScriptException()`.
   */
  protected def unwrapJavaScriptExceptionInternal(): Any =
    this
}
```
and to override it in `js.JavaScriptException` as follows:
```scala
final case class JavaScriptException(exception: Any) {
  ...

  /* Hack: override Throwable.unwrapJavaScriptExceptionInternal, which is a
   * "public" method but not part of the JDK API. This is used by the javalib
   * IR clear to replace calls to
   * `scala.scalajs.runtime.unwrapJavaScriptException()`.
   */
  /* override */ protected def unwrapJavaScriptExceptionInternal(): scala.Any =
    exception
}
```
This way, the `throw t` instruction doesn't have to do a type-test on `js.JavaScriptException`. It can directly call `t.unwrapJavaScriptExceptionInternal()` in a Scala-agnostic way to receive the value that must actually be thrown.

This solution is enough for *today*'s javalib. Indeed, there is only a single place (namely `Optional.orElseThrow`) that must perform a wrap or unwrap operation by spec, and it is only an unwrapping. Other occurrences of wrap/unwrap in the javalib can be internally eliminated, without altering the spec from the outside.

But I have no solution for the wrapping problem. If the JDK adds one day a method that must wrap by spec, I have no solution on how to implement it without depending on `js.JavaScriptException` so far.

**Comment by gzm0** [comment]
Just writing down thoughts I had about this:

- IMHO it is clear that machinery to deal with the differences of JS / JVM throwing semantics should be provided by the IR.
- Could we make `js.JavaScriptException` something like a hijacked class?

**Comment by sjrd** [comment]
Making `js.JavaScriptException` a hijacked class is not really solving anything, at least not in 1.x. Because it still needs to retain its class/interface hierarchy, and that depends on Scala classes such as `Product`.

Nevertheless, if `JavaScriptException` becomes a hijacked class, the question is: what is its representation?

There's an argument to be made that it should be the thrown value itself. That means that *any* value `x` that is not a `Throwable` would *be* a `JavaScriptException`. And then that means they would actually answer `true` to `x.isInstanceOf[Throwable]` (like any value answers true to `.isInstanceOf[java.lang.Object]`). The difficulty is then that it must include any Scala class. So `x: List` would have to be a `JavaScriptException`, and hence a `Throwable` as well. That probably opens up all kinds of cans of worms, and I'm not even considering the superclasses of `JavaScriptException` like `Product`, so the difficulty would stay in a hypothetical 2.x.

So if it's not the value itself, it must be an instance of a small wrapper class defined by the core JS lib (like `$Char` for boxed `Char` instances). We could then have Scala-agnostic IR instructions to wrap/unwrap any value in that container. Something like:
```js
class $WrapperThrowable {
  constructor(e) {
    this.e = e;
  }
}
// Any => Throwable
function $wrapAsThrowable(e) {
  return e instanceof $WrapperThrowable ? e : new $WrapperThrowable(e);
}
// Throwable => Any
function $unwrapFromThrowable(th) {
  return th instanceof $WrapperThrowable ? th.e : th;
};
```
There would be two IR nodes for this wrap/unwrap function pair. The compiler would use them to compile a Scala `try..catch`. We could expose them as primitive methods in `js.special` (and perhaps even a JS-level `try..catch` primitive that catches an `Any` instead of a `Throwable`).

This would allow the javalib to directly use those IR nodes to wrap/unwrap when necessary.

Now it would still be awkward to (re-)define `JavaScriptException` as a hijacked class for this wrapper:

* First, it does live in the `scala` namespace, so now the *very definition of the IR* would depend on the `scala` package, which is not the case currently.
* It will cause all of `Product`, `Equals`, `RuntimeException`, `Exception` and `Throwable` to become ancestors of a hijacked class, which complicates their method dispatch and instance test. (There's also `Serializable` but that one is already a hijacked class ancestor).
* Since `Throwable` has *fields*, we now have a case of a hijacked class with a field, which will complicate the hijacking mechanism.

A mitigating factor the second bullet is that we have good infrastructure for method dispatch of hijacked classes now. It used to be the case that we needed manual configuration of each method, but now it's pretty automated. We also already have a precedent for a *class* that is an ancestor, with `java.lang.Number`, so that shouldn't be such an issue.

So that is what we would have to do for Scala.js 1.x. Not pretty, but *doable*.

In a hypothetical 2.x, we could get rid of all this complexity by redefining `JavaScriptException` as a mere constructor/extractor:
```scala
object JavaScriptException {
  def apply(e: Any): Throwable =
    js.special.wrapAsThrowable(e)

  def unapply(th: Throwable): Any = {
    val e = js.special.unwrapFromThrowable(th)
    if (e eq th) None else Some(e)
  }
}
```

**Comment by sjrd** [comment]
Rereading myself: assuming the above is the model we want for 2.x, there's actually a simpler filler solution for 1.x. It would be to use `js.JavaScriptException` as the class manipulated by the wrap/unwrap IR nodes, instead of `$WrapperThrowable`.

Pro: no need to patch `JavaScriptException` as a hijacked class.

Con : it makes it impossible to design the linker in a way that does not require `JavaScriptException` to be on the classpath. That's not good for the minilib, and it's not good for other languages that could like to target the IR without depending on the scalalib.

**Comment by sjrd** [comment]
We could combine the advantages of both approaches with two different strategies in the emitter:

* If `scala.scalajs.js.JavaScriptException` is on the classpath, then wrap/unwrap to and from that class.
* Otherwise, use `$WrapperThrowable`.

It may be ugly, but I suspect it will be less ugly than making `JavaScriptException` a hijacked class.

**Comment by sjrd** [comment]
Other possibility for 1.x, similar to the above but with less hackery in the emitter: the emitter could inject an IR file with a bare-bone `scala.scalajs.js.JavaScriptException` that does not depend on the scalalib, defined in the linkerPrivateLib:
```scala
class JavaScriptException(val exception: Any) extends RuntimeException {
  override def getMessage(): String = exception.toString()

  override def fillInStackTrace(): Throwable = {
    type JSExceptionEx = JavaScriptException {
      def setStackTraceStateInternal(e: scala.Any): Unit
    }
    this.asInstanceOf[JSExceptionEx].setStackTraceStateInternal(exception)
    this
  }
}
```
(the only real difference with the real one is that it's not a `case` class.)

If there's `JavaScriptException` on the classpath, it will take priority. Otherwise, the minimal one above will be used.

**Comment by gzm0** [comment]
I think that is actually quite a decent solution. In a hypothetical 2.0, we could then just change the package of this class.

I wonder if we can avoid the reflective call though :-/

**Comment by sjrd** [comment]
> I wonder if we can avoid the reflective call though :-/

The reflective call is already present in today's `js.JavaScriptException`. It's probably not possible to get rid of it, other than by writing the IR of this method by hand. This class is compiled separately form the javalanglib, so the compiler doesn't know that `setStackTraceStateInternal` exists.
