### ISSUE TITLE
Elide statements that simply reference js.Object field values

### ISSUE THREAD

**Issue by japgolly** [scala-js/scala-js#4692]
I've captured some Scala.js output and was surprised to see the following:

https://github.com/japgolly/scalajs-react/blob/a8693f45d2216857200578cfe2094da7bf1161e9/library/testEmissions/jvm/src/test/resources/rr-sjr/HooksPrimative-out3.js#L79-L82

`props` is an instance of `Box[A]`, where `Box` is defined as:

```scala
@js.native
trait Box[+A] extends js.Object {
  @JSName("a") val unbox: A = js.native
}
```

`props.a;` on it's own as a statement doesn't do anything because `.a` is `val` and can't side-effect. It would be nice to elide those statements.

**Comment by japgolly** [comment]
Also for the record, the SJS settings used were:

```scala
      Compile / scalaJSLinkerConfig ~= { _
        .withModuleKind(ModuleKind.ESModule)
        .withModuleSplitStyle(ModuleSplitStyle.SmallestModules)
        .withSourceMap(false)
        .withSemantics(_
          .withArrayIndexOutOfBounds(CheckedBehavior.Unchecked)
          .withAsInstanceOfs(CheckedBehavior.Unchecked)
          .withProductionMode(true)
        )
      },
```

**Comment by sjrd** [comment]
As far as Scala.js knows, `props.a` could be a computed property with a side-effecting getter. So no, it can't elide it without changing semantics, in the general case.

**Comment by japgolly** [comment]
Would it be worth making a distinction for Scala-js defined js-objects? We know that they would follow Scala's semantics.

**Comment by sjrd** [comment]
That's not how Scala.js semantics work. Scala.js-defined JS objects maybe defined with a syntax that's the same as a Scala class, but their *semantics* are those of a JavaScript class. It wouldn't prevent some code from overwriting the field with a side-effecting getter, for example.

For the IR, there's even no difference between a native JS value and a non-native one. They're all JS values with JS semantics.

**Comment by japgolly** [comment]
> It wouldn't prevent some code from overwriting the field with a side-effecting getter, for example.

Maybe I'm misunderstanding you but that wouldn't compile, right? You mean something like this?

```scala
trait Foo extends js.Object {
  val unbox: Int = js.native
}

trait Bar extends Foo {
  override val unbox: Int = { println(); 1 }
}

def andThenGivenAnInstance(b: Bar) = {
  b.unbox // this can't contain side-effects, no?
}
```

**Comment by sjrd** [comment]
I said over*writing*, not just your regular overriding. So with a run-time call to `js.Object.defineProperty`.

**Comment by japgolly** [comment]
Oh wow. Good catch. I guess there's no option but to close this then. Thanks for the discussion
