### ISSUE TITLE
Specify the additional binary API of our javalib wrt. the JDK

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#4710]
From the discussion at https://github.com/scala-js/scala-js/pull/4677#discussion_r914132518

As we want to actually separate the `javalib` in its own artifact, the additional API it provides to `scalajs-library` becomes public information. Therefore, we need to actually specify it in some way or another.

Among that API, there are two methods that are effectively already publicly guaranteed to exist: `StackTraceElement.{get,set}ColumnNumber`, defined at
https://github.com/scala-js/scala-js/blob/112def5cb59b942d8b2c4c5791b17ea0c7c4a7dc/javalib/src/main/scala/java/lang/StackTraceElement.scala#L29-L38
and tested at
https://github.com/scala-js/scala-js/blob/112def5cb59b942d8b2c4c5791b17ea0c7c4a7dc/test-suite/js/src/test/scala/org/scalajs/testsuite/javalib/lang/StackTraceElementJSTest.scala#L24-L40

Other than that, there are:
* `Throwable.setStackTraceInternal` (used in `js.JavaScriptException` -- both the one in scalajs-library and the one in the linker-private-library)
  * There's a `getStackTraceInternal` but it's only used by `j.l.StackTrace`, so that one can be made `private[lang]`.
* All the methods in `TypedArrayBufferBridge`

So how do we specify that API?

**Comment by sjrd** [comment]
In the linked discussion, @gzm0 suggests to use an actual compile-time interface, in the form of `.class` file, shipped with the `javalib` artifact.

While that is appealing, I see two issues with that.

First, it cannot specify the additional methods on existing classes, such as `StackTraceElement.getColumnNumber`.

Second, in `TypedArrayBufferBridge`, there are values typed as `Object` although they represent specific JS types. We cannot use the specific JS types because they would be references to scalajs-library. But any given language may not want to *expose* those weakly-typed methods; they would instead want to provide language-specific APIs with more precise types instead (which we do in `TypedArrayBufferOps`). If we ship a `.class` files with these methods in the `javalib` artifact, they become public for all users, not just for language implementers.

**Comment by gzm0** [comment]
> First, it cannot specify the additional methods on existing classes, such as StackTraceElement.getColumnNumber.

IMHO this is not that big of a deal. In fact, I think we should very strongly consider offering this API as static methods only anyways.

> Second, in TypedArrayBufferBridge, there are values typed as Object although they represent specific JS types. 

That on the other hand is indeed a very serious issue, since this would leak to all users. To me, this makes it clear that we should definitely not ship `.class` files in the main `javalib` artifact. Whether it is worth it (or total overkill) to do this in another auxiliary artifact, IDK.

Just to make it explicit: Main advantages of the `.class` file approach:

- Definitions are checked for correctness (by scalac)
- Definitions are checked for backwards compatibility (by mima)

**Comment by sjrd** [comment]
> > First, it cannot specify the additional methods on existing classes, such as StackTraceElement.getColumnNumber.
> 
> IMHO this is not that big of a deal. In fact, I think we should very strongly consider offering this API as static methods only anyways.

They would have to be not only static, but also static *in separate classes*. And if we have to put them in `.class` files of our own, we ought to put them in our own non-`java` package in order to play nice with Java's module system.

If we don't declare the API with `.class` files, we can leave them in the corresponding classes. We could standardize on static methods only, though, I agree.

After #4712, the full list would be:

* `java.lang.StackTraceElement`:
  * `createWithColumnNumber(...): StackTraceElement`
  * `getColumnNumber(StackTraceElement): Int`
* `java.nio.Buffer`:
  * `hasArrayBuffer(Buffer): Boolean`
  * `arrayBuffer(Buffer): Object` // a js.typedarray.ArrayBuffer
  * `arrayBufferOffset(Buffer): Int`
  * `dataView(Buffer): Object` // a js.typedarray.DataView
  * `hasTypedArray(Buffer): Boolean`
  * `typedArray(Buffer): Object` // an appropriate TypedArray
* `java.nio.ByteBuffer`:
  * `wrapArrayBuffer(Object): ByteBuffer` // takes an ArrayBuffer
  * `wrapArrayBuffer(Object, Int, Int): ByteBuffer` // takes an ArrayBuffer
  * `wrapInt8Array(Object): ByteBuffer` // takes an Int8Array
* `java.nio.CharBuffer`:
  * `wrapUint16Array(Object): CharBuffer` // takes a Uint16Array
* `java.nio.ShortBuffer`:
  * `wrapInt16Array(Object): ShortBuffer` // takes an Int16Array
* `java.nio.IntBuffer`:
  * `wrapInt32Array(Object): IntBuffer` // takes an Int32Array
* `java.nio.FloatBuffer`:
  * `wrapFloat32Array(Object): FloatBuffer` // takes a Float32Array
* `java.nio.DoubleBuffer`:
  * `wrapFloat64Array(Object): DoubleBuffer` // takes a Float64Array

> Just to make it explicit: Main advantages of the `.class` file approach:
> 
> * Definitions are checked for correctness (by scalac)
> * Definitions are checked for backwards compatibility (by mima)

Yes, I agree.

**Comment by gzm0** [comment]
> They would have to be not only static, but also static in separate classes

Yes. But I'd still argue that this is a good thing:

- It clearly separates Scala.js specific API from JDK API.
- It prevents potential collisions with future JDK additions (arguably unlikely for the Buffer API, less unlikely for the stack trace API).

Maybe a viable approach would be to do just that (static methods in separate classes). This would allows us (at a later point), to ship a `javalib-interface` package if the need arises.

**Comment by sjrd** [comment]
Yes, indeed. I think you convinced me. Shall we put those in a package `org.scalajs.javalibintf`?

**Comment by gzm0** [comment]
Yeah, that sound like a good name.
