### ISSUE TITLE
Better error message for out of bounds string index

### ISSUE THREAD

**Issue by krux02** [scala-js/scala-js#4713]
Currently it says: "NaN is not an instance of java.lang.Integer"

Yes this kind of tackles the "undefiend behavior area" but it is still a bug. This exception is only thrown when the code is not optimized for performance. Optimized builds simply return a `\0` character. I am not arguing for or against the `\0` character, because this falls in this "undefined behavior" and can be reasoned with the performance argument. I am arguing for the debug build that generates a very confusing exception that is both wrong and slow.

```scala
val myString = "abcdef"
println(myString(17))
```

**Comment by sjrd** [comment]
That would be fixed by #4707.
