### ISSUE TITLE
Interop feature for the ** operator of ECMAScript 2016

### ISSUE THREAD

**Issue by sjrd** [scala-js/scala-js#4719]
See #4619. We need some interop feature for the `**` operator introduced in ES 2016.

**Comment by sjrd** [comment]
In addition to the compatibility issues, which can be solved by introducing `@JSOperator`, there is one design choice here. What do we do when emitting ES < 2016? I see 4 possibilities:

1. Emit the `**` operator anyway, potentially breaking if run in an interpreter that doesn't support it.
  This doesn't actually work with the GCC output because it breaks early, so not really an option.
2. Refuse it at link time in the Analyzer -- this is what we do for `new.target`, for example.
3. Replace by `Math.pow` -- that works for `number`s but not for `bigint`s. That could be deemed acceptable given that if we emit for ES < 2016, there "shouldn't be" `bigint`s (which are ES 2020+). But if one feature-tests for `bigint`s being supported at run-time, that is not going to do the right thing.
4. Replace it with a custom `$pow` function that accurately implements the semantics of `**` both for `number`s (with `Math.pow`) and `bigint`s (by repeatedly applying `*`, although that's slow).

If only there was a non-syntax-based way to call the exponentiation operation on `bigint`s, it would be cheap to implement 4. Unfortunately we cannot do anything but the slow repeated `*`. Note that we cannot *polyfill* in the sense of feature-testing to use the native `**` if it's present, because it is syntax, so it would cause an early `SyntaxError`. We have to *always* use our slow implementation instead.

The `new.target` precedent is tempting for its simplicity. Its story was different, though, since there *was* no way to implement it correctly. Moreover, it would be nice to be able to write `linkingInfo.esVersion`-based branches that choose to use `bigint`s and `**` when targeting ES2020+. With 2., that's not possible, because the `**` would survive when the optimizer is disabled, and so the Analyzer has to flag it as an error even if it is dead code after optimizations. A concrete example where that would be useful is in `Float.parseFloatDecimalCorrection`:
https://github.com/scala-js/scala-js/blob/c56b30fcfc3b963cc8cdb346a2033635f1635813/javalib/src/main/scala/java/lang/Float.scala#L232

**Comment by gzm0** [comment]
Have you considered using `eval` to get around the syntax restriction? Basically an option like 4, that implements `$pow` via eval (like #4619). That also removes any concerns about forward compatibility. (What if ** starts supporting more types in the future).

**Comment by sjrd** [comment]
Some environments have a hard stop on `eval` and other similar features. So we cannot rely on that.

**Comment by gzm0** [comment]
Hmm... By hard stop you mean irrecoverable exception on usage or failure to load module on presence (IIUC with strict mode, `eval` is always recognizable statically)?

In general: I'm unsure whether it is a good idea to provide a polyfill in core for something the core doesn't need and where the trade-offs are not super clear cut (in environments where eval works, that might be the better / more performant option).

Thinking about this more, I think it might be valuable to break down what we provide:
1. The ability to use a later ES feature on a lower ES level via polyfill. This is not something we offer to user space code (and never have). We only do this if we need a certain feature in core (e.g. Symbols, Maps, fround).
2. The ability to write library code targeting different ES levels with decision at linking time. We are offering this through `LinkingInfo.esVersion` + inlining in the optimizer. This is a real problem for `**`. However, note that `new.target` suffers from the same limitation.
3. The ability to dynamically detect whether a feature is supported for the purpose of targeting a lower ES level statically (e.g. use BigInt's but don't assume `Object.getOwnPropertyDescriptors` is present). This seems like theoretical problem, form ES2015 to ES2016, `**` is the only thing we use. For ES5.1 this would indeed be an issue (as in: a ES5.1 runtime that supports `**`), but it seems unlikely to be an issue in practice.
4. The ability to dynamically detect whether a feature is supported for the purpose of falling back to a different implementation if it is not. This is not specific to Scala.js for `**` (or `new.target`) but is a problem for any code targeting JS.

On can argue that the combination of 2 + 4 is a problem for this specific case (especially BigInt, is there any downside to use `Math.pow` over `**`?).

Solutions 3+4 above address this by providing 1.

The eval proposal addresses this by baking in a hacky mechanism to solve 4 into core. Arguably a library could do the same.

My "in general" comment above questions backing down on 1 (in general).

Maybe it makes sense to investigate whether we can provide better support for 2? (now that I think about it `globalFallback` for `JSImport` solves a similar issue but for module styles).

**Comment by sjrd** [comment]
> Hmm... By hard stop you mean irrecoverable exception on usage or failure to load module on presence (IIUC with strict mode, `eval` is always recognizable statically)?

I'm not sure what's the worst that can happen. But there is already a pretty bad situation with [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) enabled in a web page. It can be configured to actively *report* any violation of the policy (instead of or in addition to blocking the evaluation), such that even a feature test will report a violation. That's not something we can afford, I think.

**Comment by sjrd** [comment]
In general, I fully agree that proposing polyfills for user-space is not something we do. And we shouldn't set a general precedent for that.

What's unique about `**`, which made me consider it at all is the following:
* We *can* feature-test `bigint`s overall, and they can be used as fast-path to implement some operations (possibly even all of `java.math.BigInteger`) when they are available.
* `**` is the only way to access native exponentiation on `bigint`s, so we'd like to be able to use based on `linkingInfo.esVersion`. And we'd like to do that in libraries (including the javalib).
* But we cannot actually do that because the linking behavior is such that an error must be reported before the optimizer can constant-fold it away.

If any of these were not true, then it would clearly not be worth it. So it's like you said for 2+4.

> Maybe it makes sense to investigate whether we can provide better support for 2? (now that I think about it `globalFallback` for `JSImport` solves a similar issue but for module styles).

Scala Native has something like that, but at a significant cost in complexity for their equivalent of our Analyzer. If it were *only* about `esVersion`, it could remain manageable, but in general we may want other forms of conditions. It's unclear where to draw the boundary if we start in that direction.

**Comment by sjrd** [comment]
Since it's unclear what's best, perhaps we should just go with the conservative option, i.e., disallow `**` when emitting ES < 2016.

**Comment by gzm0** [comment]
Yes, I agree. I don't think there is any doubt about what should happen when ES >= 2016. And by restricting it for ES < 2016, we can improve later without breaking compatiblity.
