### ISSUE TITLE
`j.u.ArrayDeque#pollFirst` is `O(n)`

### ISSUE THREAD

**Issue by armanbilge** [scala-js/scala-js#4734]
Specifically this method:

https://github.com/scala-js/scala-js/blob/639313922b7c203f5ce12fdac414cd1c5b786eb3/javalib/src/main/scala/java/util/ArrayDeque.scala#L84-L91

AFAIK there is no guarantee that `shift` is `O(1)`, apologies If I'm wrong about that.

According to the Javadoc this method (and others) should be amortized `O(1)`.

https://docs.oracle.com/javase/8/docs/api/java/util/ArrayDeque.html

**Comment by sjrd** [comment]
Thanks for the report. Indeed, we should use the underlying array as a circular buffer.
