### ISSUE TITLE
Vector.apply is much slower than Array.apply in browsers

### ISSUE THREAD

**Issue by JD557** [scala-js/scala-js#4752]
I was running a [quick benchmark](https://scastie.scala-lang.org/TVc0BVLyQuKxUHW5aa9Idg) with scala-cli to try to debug some performance issues on Firefox and got some surprising results:

While the performance between `Array.apply` and `Vector.apply` seems quite consistent on JVM and Native, with a slight performance hit on Node, both Chrome and Firefox (especially Firefox) take a huge performance hit.

Not sure if this should be filled on the stdlib, but considering the benchmarks of non-browser targets (especially the differences between Node and Chrome), I wonder if somehow the generated code is not triggering some JIT optimizations.

<details><summary><b>JVM</b> (<code>scala-cli .\bench.sc</code>) </summary>
<pre>
[Vector Sum] Run: 0 | Duration: 7ms | Result: 745038442
[Vector Sum] Run: 1 | Duration: 7ms | Result: 745038442
[Vector Sum] Run: 2 | Duration: 8ms | Result: 745038442
[Vector Sum] Run: 3 | Duration: 8ms | Result: 745038442
[Vector Sum] Run: 4 | Duration: 8ms | Result: 745038442
[Array Sum] Run: 0 | Duration: 5ms | Result: 582852528
[Array Sum] Run: 1 | Duration: 6ms | Result: 582852528
[Array Sum] Run: 2 | Duration: 6ms | Result: 582852528
[Array Sum] Run: 3 | Duration: 6ms | Result: 582852528
[Array Sum] Run: 4 | Duration: 7ms | Result: 582852528
</pre></details>

<details><summary><b>Native</b> (`scala-cli --native --native-mode release .\bench.sc`) </summary>
<pre>
[Vector Sum] Run: 0 | Duration: 3ms | Result: 1059989820
[Vector Sum] Run: 1 | Duration: 2ms | Result: 1059989820
[Vector Sum] Run: 2 | Duration: 3ms | Result: 1059989820
[Vector Sum] Run: 3 | Duration: 3ms | Result: 1059989820
[Vector Sum] Run: 4 | Duration: 3ms | Result: 1059989820
[Array Sum] Run: 0 | Duration: 1ms | Result: 829760435
[Array Sum] Run: 1 | Duration: 1ms | Result: 829760435
[Array Sum] Run: 2 | Duration: 1ms | Result: 829760435
[Array Sum] Run: 3 | Duration: 2ms | Result: 829760435
[Array Sum] Run: 4 | Duration: 1ms | Result: 829760435
</pre></details>

<details><summary><b>Node</b>  (`scala-cli --js --js-mode release --js-version 1.11.0 .\bench.sc`)</summary>

```
[Vector Sum] Run: 0 | Duration: 5ms | Result: -621972994
[Vector Sum] Run: 1 | Duration: 5ms | Result: -621972994
[Vector Sum] Run: 2 | Duration: 5ms | Result: -621972994
[Vector Sum] Run: 3 | Duration: 5ms | Result: -621972994
[Vector Sum] Run: 4 | Duration: 5ms | Result: -621972994
[Array Sum] Run: 0 | Duration: 0ms | Result: -1945024196
[Array Sum] Run: 1 | Duration: 1ms | Result: -1945024196
[Array Sum] Run: 2 | Duration: 0ms | Result: -1945024196
[Array Sum] Run: 3 | Duration: 0ms | Result: -1945024196
[Array Sum] Run: 4 | Duration: 1ms | Result: -1945024196
```
</details>

<details><summary><b>Chrome 107.0.5304.107</b>  (`scala-cli package --js --js-mode release --js-version 1.11.0 -f .\bench.sc`)</summary>

```
[Vector Sum] Run: 0 | Duration: 11ms | Result: -1051291627
[Vector Sum] Run: 1 | Duration: 12ms | Result: -1051291627
[Vector Sum] Run: 2 | Duration: 11ms | Result: -1051291627
[Vector Sum] Run: 3 | Duration: 13ms | Result: -1051291627
[Vector Sum] Run: 4 | Duration: 11ms | Result: -1051291627
[Array Sum] Run: 0 | Duration: 0ms | Result: 495574317
[Array Sum] Run: 1 | Duration: 1ms | Result: 495574317
[Array Sum] Run: 2 | Duration: 0ms | Result: 495574317
[Array Sum] Run: 3 | Duration: 0ms | Result: 495574317
[Array Sum] Run: 4 | Duration: 1ms | Result: 495574317
```
</details>

<details><summary><b>Firefox 106.0.5</b>  (`scala-cli package --js --js-mode release --js-version 1.11.0 -f .\bench.sc`)</summary>

```
[Vector Sum] Run: 0 | Duration: 29ms | Result: 152901963
[Vector Sum] Run: 1 | Duration: 28ms | Result: 152901963
[Vector Sum] Run: 2 | Duration: 31ms | Result: 152901963
[Vector Sum] Run: 3 | Duration: 31ms | Result: 152901963
[Vector Sum] Run: 4 | Duration: 28ms | Result: 152901963
[Array Sum] Run: 0 | Duration: 1ms | Result: -2045275239
[Array Sum] Run: 1 | Duration: 1ms | Result: -2045275239
[Array Sum] Run: 2 | Duration: 0ms | Result: -2045275239
[Array Sum] Run: 3 | Duration: 1ms | Result: -2045275239
[Array Sum] Run: 4 | Duration: 0ms | Result: -2045275239
```
</details>

**Comment by sjrd** [comment]
Same answer as https://github.com/scala-js/scala-js/issues/4699. `Vector` is just not well suited to JS. If someone wants to contribute an efficient and maintainable alternative, we could look at it, but we're not going to work on anything ourselves.
