### ISSUE TITLE
RFC drop Scala 2.11 ?

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#4759]
We are considering dropping support for Scala 2.11 (prompted by #4758).

Please upvote / downvote and comment for any (remaining) 2.11 use cases.

**Comment by WojciechMazur** [comment]
As soon as Scala.js would drop Scala 2.11, Scala Native would do the same. The only reason of keeping it is to allow for smooth cross building projects.

**Comment by sjrd** [comment]
> Is Scala 2.11 not EOL already?

Java 8 is EOL too. That doesn't prevent many libraries to keep supporting it as their canonical target.

**Comment by oyvindberg** [comment]
Absolutely pro dropping it. 

Just wanted to chime in that the relevant data point here is probably ratio of downloads from maven central
