### ISSUE TITLE
Add `j.u.TreeMap`, implement `j.n.Charset.availableCharsets`

### ISSUE THREAD

**Issue by armanbilge** [scala-js/scala-js#4783]
I hate to ask for more Javalib, since the existing coverage in Scala.js is already so good. But just mentioning this minor one.

We rely on `Charset.availableCharsets` in some libraries, which forces us to split to platform-dependent code. I assume the reason it's not implemented is because so far there is currently no implementation of `SortedMap` e.g. `TreeMap`?

https://docs.oracle.com/javase/8/docs/api/java/nio/charset/Charset.html#availableCharsets--

It looks like there is already groundwork in place to implement `TreeMap`.

https://github.com/scala-js/scala-js/blob/0eea7c77e8c66422caacbb07689e761ac736c561/javalib/src/main/scala/java/util/RedBlackTree.scala#L19-L21

**Comment by gzm0** [comment]
Implementation here (no tests yet): https://github.com/gzm0/scala-js/tree/tree-map

**Comment by sjrd** [comment]
`availableCharsets` returns an immutable, case-insensitive map. Because it's case-insensitive, it cannot directly use `TreeMap`. Because it's immutable, we can implement it in a dedicated private class that only supports that use case without depending on an actual tree implementation. That would also much less expensive in terms of code size.

So I think this an entirely different problem than providing `TreeMap`.

**Comment by armanbilge** [comment]
> Because it's case-insensitive, it cannot directly use `TreeMap`

Hum, why not? A `TreeMap` can take a custom comparator; in this case `String.CASE_INSENSITIVE_ORDER`.

- https://docs.oracle.com/javase/8/docs/api/java/util/TreeMap.html#TreeMap-java.util.Comparator-
- https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#CASE_INSENSITIVE_ORDER

---

On the other hand

> Because it's immutable, we can implement it in a dedicated private class that only supports that use case without depending on an actual tree implementation. That would also be much less expensive in terms of code size.

This sounds nice :)

**Comment by gzm0** [comment]
> Because it's case-insensitive, it cannot directly use TreeMap

I thought that as well initially, but the docs of `TreeMap` are fairly clear about this:

>  The behavior of a sorted map is well-defined even if its ordering is inconsistent with equals; it just fails to obey the general contract of the Map interface.

> Because it's immutable, we can implement it in a dedicated private class that only supports that use case without depending on an actual tree implementation. That would also be much less expensive in terms of code size.

I think this would be easier, but is it still if we implement all the projections in NavigableMap / NavigableSet?

**Comment by sjrd** [comment]
`availableCharsets()` returns a `SortedMap`, not a `NavigableMap`. So you don't need all those projections. ;)

**Comment by gzm0** [comment]
Ah, yes. But the basic versions of the projections are in SortedMap:
https://docs.oracle.com/en/java/javase/19/docs/api/java.base/java/util/SortedMap.html#subMap(K,K)

Still, of course, since the map is immutable, we can simply copy for these.

**Comment by sjrd** [comment]
True, even the basic projections are a bit of a pain to implement, especially to faithfully implement the error cases.

Perhaps for the projections we can build a `TreeMap`, wrap it in an `unmodifiableMap`, and then delegate to its projections. That way, as long as we don't use the projections methods, we won't trigger a dependency on `TreeMap`.
