### ISSUE TITLE
SyntaxError on regex with an optional negative lookahead (only on JS) 

### ISSUE THREAD

**Issue by FabioPinheiro** [scala-js/scala-js#4784]
Scala version: 3.2.2-RC2
Scala.js version: 1.12.0
Test on browsers Chrome v108 and Firefox v108

The following scala code give an error only one ScalaJS (running on any JS platform)
`"""tes(?!t)?""".r`

The js code generated looks like:
`new RegExp(jsPattern, (this.ju_regex_Pattern__f_java$util$regex$Pattern$$jsFlags + 
(this.ju_regex_Pattern__f_java$util$regex$Pattern$$sticky ? "gy" : "g")))`

When running will be
 `new RegExp('tes(?!t)?', "usg")`

Got the following error:
```VM3840:1 Uncaught SyntaxError: Invalid regular expression: /tes(?!t)?/: Invalid quantifier
 at new RegExp (<anonymous>)
```

Is this undefined behavior of regex or a bug? (optional negative lookahead )
Why does the error only happen when we have the Unicode flag?
For this code, it shouldn't matter whether I have the flag on or off.

Also reported a bug on Bugzilla to try to some answers to those questions
https://bugzilla.mozilla.org/show_bug.cgi?id=1809716

**Comment by sjrd** [comment]
The [ECMAScript spec for pattern syntax](https://262.ecma-international.org/13.0/#sec-patterns) does seem to say that a quantifier is *not* allowed after an Assertion. Only after an Atom. We already have [code to protect `^`  and `$`](https://github.com/scala-js/scala-js/blob/54f9a69f48ff3083ec2be66409be76eacd3bf1a2/javalib/src/main/scala/java/util/regex/PatternCompiler.scala#L1195-L1201). We need to do the same for other Assertions.

**Comment by FabioPinheiro** [comment]
_The [ECMAScript spec for pattern syntax](https://262.ecma-international.org/13.0/#sec-patterns) does seem to say that a quantifier is not allowed after an Assertion. Only after an Atom._
Yes but since we are using the `~UnicodeMode` this [QuantifiableAssertion](https://tc39.es/ecma262/#prod-annexB-QuantifiableAssertion).

Got that explanation from https://bugzilla.mozilla.org/show_bug.cgi?id=1809716 why it only fails with the unicode flag.

I was going to try to understand the code to see if I could make a PR but seems you are fixing.
Correction. Is already fixed and merged (too fast) XD
