### ISSUE TITLE
`ReferenceError: clearTimeout is not defined` on V8

### ISSUE THREAD

**Issue by armanbilge** [scala-js/scala-js#4789]
### Minimizer

```scala
//> using scala "2.13.10"
//> using jsVersion "1.12.0"
//> using platform "js"

import scala.concurrent.duration._
import scala.scalajs.js

object Main {
  def main(args: Array[String]) = {
    val handle = js.timers.setTimeout(1.second)(())
    js.timers.clearTimeout(handle)
  }
}
```

### Output

```
$ ~/.jsvu/bin/v8
V8 version 11.1.199
d8> ^C
$ ~/.jsvu/bin/v8 Main.js 
Main.js:4417: ReferenceError: clearTimeout is not defined
  clearTimeout(handle)
  ^
ReferenceError: clearTimeout is not defined
    at $c_sjs_js_timers_package$.clearTimeout__sjs_js_timers_SetTimeoutHandle__V (Main.js:4417:3)
    at $c_LMain$.main__AT__V (Main.js:1062:31)
    at $s_LMain__main__AT__V (Main.js:1041:15)
    at Main.js:17181:1
    at Main.js:17182:4
```

### Expectation

I assume that (raw) V8 is a supported runtime? :)

Obviously it can't be helped that `clearTimeout` isn't available. But since this is offered as a higher-level API, I'd expect it to be polyfilled.

**Comment by armanbilge** [comment]
I guess the doc does say non-standard, and that it may be unsupported. This case is weird since `setTimeout` is supported.
https://github.com/scala-js/scala-js/blob/4ed87720ce940ef7029a672d2b7263e4d6d58e4f/library/src/main/scala/scala/scalajs/js/timers/package.scala#L17-L25

**Comment by sjrd** [comment]
Hum, yes, as the doc says, they're non-standard and possibly not supported. Do you think we can make that clearer?

> Obviously it can't be helped that `clearTimeout` isn't available. But since this is offered as a higher-level API, I'd expect it to be polyfilled.

We never polyfill JavaScript functions in the core, except in an invisible way to support other features of core (e.g., we internally polyfill `Math.fround` and `Math.imul` when targeting ES 5.1, and we internally polyfill the `d` flag of regexes when targeting ES < 2020, but in an invisible way so you still can't use them yourselves from user space).

**Comment by armanbilge** [comment]
> but in an invisible way so you still can't use them yourselves from user space)

Fair enough, although I'm not exactly sure what "invisible" means. To be clear I'm not suggesting to polyfill `RawTimers.clearTimeout`, but rather `timers.clearTimeout`. Although it's a thin wrapping layer it is arguably still a "core feature". But I don't feel too strongly about it.

---

> Do you think we can make that clearer?

Perhaps this can be clarified. V8 supports `setTimeout`, but it doesn't mean all the methods work.
```
  *  The methods in this package work in all JavaScript virtual machines 
  *  supporting `setTimeout` and `setInterval`.
```

**Comment by gzm0** [comment]
Ah, yes the documentation is not clear. I guess the assumption was that if `setTimeout` is supported, so is `clearTimeout` :P
