### ISSUE TITLE
Prefer `queueMicrotask` when available?

### ISSUE THREAD

**Issue by armanbilge** [scala-js/scala-js#4795]
Specifically here, instead of the resolved `Promise` trick.

https://github.com/scala-js/scala-js/blob/6ffe54e130cb4e5517df79b3c63a118c4d878697/library/src/main/scala/scala/scalajs/concurrent/QueueExecutionContext.scala#L46-L50

- https://developer.mozilla.org/en-US/docs/Web/API/queueMicrotask
- https://caniuse.com/mdn-api_queuemicrotask

I already made a first attempt in https://github.com/scala-js/scala-js/commit/c91c5fdb9f5e0ae393fcecc3cacff61c4b1df527, but it looks like it will require some rework of the `PromiseMock` facilities. So I wanted to check if there's general support first 😅 thanks!

**Comment by armanbilge** [comment]
Another approach would be to create a `MicrotaskExecutionContext` class, but its semantics are not meaningfully different from `PromisesExecutionContext` (unlike the difference between `PromisesExecutionContext` and `TimeoutsExecutionContext`). But maybe that's okay?

**Comment by sjrd** [comment]
That's a browser-specific API, isn't it? We normally avoid relying on environment-specific APIs, especially when we can achieve the same result using standard ECMAScript.

**Comment by armanbilge** [comment]
https://nodejs.org/api/globals.html#queuemicrotaskcallback

**Comment by sjrd** [comment]
That's still not standard in ECMAScript. Node.js supports more and more browser APIs, but that doesn't make those API standard in ECMAScript itself.

**Comment by armanbilge** [comment]
> but that doesn't make those API standard in ECMAScript itself.

Sure, I get that. My point is that it's not specifically a browser-specific API.

`setTimeout` is also not standard ECMAScript, but there is still `TimeoutsExecutionContext`. And oddly enough, it's the fallback in case `PromisesExecutionContext` is unavailable, even though that's the standard API 🤷 

https://github.com/scala-js/scala-js/blob/6ffe54e130cb4e5517df79b3c63a118c4d878697/library/src/main/scala/scala/scalajs/concurrent/QueueExecutionContext.scala#L27-L29

**Comment by sjrd** [comment]
There are historical accidents that date back to Scala.js < 0.1. We can't get rid of them without breaking very old support. Note that it's as a fallback to `Promise`, which is the standard thing, mostly intended for ES 5. We could argue to use `queueMicrotask` as a fallback for `Promise`, but that would be useless given that the former is less supported than the latter.

**Comment by armanbilge** [comment]
Ok, thanks for explaining :)
