### ISSUE TITLE
Dangling UndefinedParam

### ISSUE THREAD

**Issue by cornim** [scala-js/scala-js#4825]
I've got the following error when building on my AWS Gitlab runner:

Found a dangling UndefinedParam at Position(file:/builds/ProjectForecast/project-forecast/scalajs/src/main/scala/scalajs/MainScalaJS.scala,144,24). This is likely due to a bad interaction between a macro or a compiler plugin and the Scala.js compiler plugin. If you hit this, please let us know.

The same code compiles and runs fine on my local MXLinux.

I don't know what infos you need but if you let me know I'll try and provide them.

**Comment by cornim** [comment]
Given the fact that the exact same source code with the exact same build.sbt works fine locally and doesn't compile on my Gitlab runner, your first point is very hard to do. Especially since trying randomly can take forever with each iteration taking approx 5 minutes (pipeline duration) so unless you can give me some pointers, this is not something that I can reasonably do.

As for you other points:
- scalaVersion := "2.13.8"
- addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.9.0")
- I expected it to compile
- It didn't compile

**Comment by sjrd** [comment]
* Does this still happen with Scala.js 1.13.0? What about Scala 2.13.10?
* Do you have any other compiler plugin enabled? Any macros involved in the mentioned file?
* Does it happen with coverage enabled, perhaps? (that might explain why it's only on the CI, if you don't run coverage locally)
* Any other factor that changes between your local environment and the CI environment (compiler options, etc.)?

**Comment by cornim** [comment]
Thank you for the ideas. I'll try them out and get back to you.

**Comment by cornim** [comment]
Your hint with the coverage was spot on. With that I could narrow the issue down locally and can now provide you with a minimal example which reproduces the error.

build.sbt:
```
scalaVersion := "2.13.10"


//Definitions for the scalajs sub-project
lazy val scalajs = (project in file("scalajs")).settings(
  name := "projectforecast-scalajs",
  libraryDependencies += "org.scala-js" %%% "scalajs-dom" % "2.1.0",
  libraryDependencies += "io.lemonlabs" %%% "scala-uri" % "4.0.0"
).enablePlugins(ScalaJSPlugin)
```

plugins.sbt:
```
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.13.0")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "2.0.7")
```

MainScalaJS.scala:
```
package scalajs

import org.scalajs.dom
import org.scalajs.dom.{Element, HTMLCollection}

import scala.scalajs.js
import scala.scalajs.js.annotation.{JSExportTopLevel, JSGlobal}

object MainScalaJS {
  private def getElementsByClassName(className: String): HTMLCollection[Element] =
    dom.document.getElementsByClassName(className)

  @JSExportTopLevel("dragulaInit")
  def dragulaInit(): Unit = {
    import js.JSConverters.genTravConvertible2JSRichGenTrav
    val containers = getElementsByClassName("dragula-container")
    Dragula.dragula(containers.toJSArray)
  }
}

object Dragula{
  @js.native
  @JSGlobal("dragula")
  def dragula(containers: js.Array[Element], options: Map[String, js.Any] = Map.empty): Unit = js.native
}
```

if i run `sbt clean coverage compile` I get the error.  
if i comment out the line `Dragula.dragula(containers.toJSArray)` the error disappears.

this is on sbt 1.8.2 btw.

If you need more info, let me know.

**Comment by armanbilge** [comment]
This looks like:
- https://github.com/scoverage/scalac-scoverage-plugin/issues/447

Probably this issue can be closed, and one opened there.

**Comment by armanbilge** [comment]
```
options: Map[String, js.Any] = Map.empty): Unit = js.native
```
This looks suspect. `js.native` methods can't have default arguments, that can just be `= js.native`.

**Comment by cornim** [comment]
The ScalaJS documentation says:

> Methods can have parameters with default values, to mark them as optional. However, the actual value is irrelevant and never used. Instead, the parameter is omitted entirely (or set to undefined). The value is only indicative, as implicit documentation.

but i tried your suggestion and just actually passing an empty Map fixes the error.  
In this case the documentation should probably be amended and the error message could most likely be improved. Currently it says:
```
MainScalaJS.scala:9:8: Found a dangling UndefinedParam at Position(file:/home/corni/workspace/projectforecast/scalajs/src/main/scala/scalajs/MainScalaJS.scala,16,12). This is likely due to a bad interaction between a macro or a compiler plugin and the Scala.js compiler plugin. If you hit this, please let us know.
[error] object MainScalaJS {
[error]        ^
[error] one error found
[error] (scalajs / Compile / compileIncremental) Compilation failed
[error] Total time: 1 s, completed Mar 7, 2023, 8:58:17 PM
```

Also there is definitely some strange interaction with scoverage as running without it works just fine. Even with the default parameter in place.

**Comment by sjrd** [comment]
> but i tried your suggestion and just actually passing an empty Map fixes the error.

I would say that it *works around* the error more than it fixes it. ;) There's still a problem within scoverage when relying on the default value of a JS native method, unfortunately. And as @armanbilge identified, it looks very much like (yet another incarnation of) https://github.com/scoverage/scalac-scoverage-plugin/issues/447.

But that means there's nothing we can do in this repo. It needs to be addressed on scoverage's side.

**Comment by cornim** [comment]
> I would say that it works around the error more than it fixes it. ;)

Fair enough.

> But that means there's nothing we can do in this repo. It needs to be addressed on scoverage's side.

Okay. I'll mention the issue in the other ticket and am closing this on. Thanks.
