### ISSUE TITLE
emitter.KnowledgeGuardian incorrectly compares field defs

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#4831]
https://github.com/scala-js/scala-js/blob/54c9aa32a56a049d7bfb91ae935125c6a553ae71/linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/KnowledgeGuardian.scala#L313

As a result, field def askers always get invalidated if the fields do not have reference equality.

Discovered during #4824.

**Comment by gzm0** [comment]
Unassigning from myself for now, I'm not actively working on this.

**Comment by sjrd** [comment]
Do you still think the first commit of #4824 is the way to go? Or should we take a different approach?

**Comment by gzm0** [comment]
I think we need a completely different approach (FWIW: I'm starting to think the whole class version past the optimizer business is harmful: it's not clear at all what is tracked by the version and what isn't).

**Comment by gzm0** [comment]
(For context, I unassigned myself because I'm currently prioritizing #4835)
