### ISSUE TITLE
High memory consumption during linking when using `ModuleSplitStyle.SmallModulesFor(...)`

### ISSUE THREAD

**Issue by rmgk** [scala-js/scala-js#4833]
This is based on a [discord discussion](https://discord.com/channels/632150470000902164/635668814956068864/1084860483305222254).

We have a webapp using  ModuleSplitStyle.SmallModulesFor(...). 
Scala 3.2.2, Scalajs 1.13

`fullLinkJS` (and `fastLinkJS`) produces a 7GB HashMap full of 50 million `linker.frontend.modulesplitter.Tagger$DynamicPaths`.
Which makes the compilation painfully slow.

No issues with the default split style `ModuleSplitStyle.FewesModules`, and also no issue with `ModuleSplitStyle.SmallestModules`

A tree that has the issue (not minimized at all) is available here: 
https://github.com/rmgk/reform-scalajs-linker-memory-issue
`sbt fullLinkJS` is enough to trigger the issue. I tested the split style by changing line 36 `build.sbt`.

@gzm0 tagging you as you requested this issue as a reminder (and I don’t think I can assign people) :-)

**Comment by sjrd** [comment]
Thanks for the report.

I'm not able to checkout that commit from that repo:
```
$ git checkout 7ac6e83a4253d28919938b057883bd8ce39dd630
fatal: reference is not a tree: 7ac6e83a4253d28919938b057883bd8ce39dd630
```
Could you make sure that there is a branch that points to that commit?

**Comment by gzm0** [comment]
FWIW:
- I can reproduce this on the repo locally (but have not even attempted to minimize so far).
- I suspect this line to be the culprit (just a gut feeling):
https://github.com/scala-js/scala-js/blob/44014be9ef5904f3b19052ac5c9861b1020567c4/linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/Tagger.scala#L106-L107

**Comment by gzm0** [comment]
I can confirm locally that the following path fixes the problem (on reform-scalajs-linker-memory-issue):

```diff
modified   linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/Tagger.scala
@@ -90,10 +90,19 @@ private class Tagger(infos: ModuleAnalyzer.DependencyInfo,
       .put(pathRoot, pathSteps)
 
     if (updated) {
+      val excluded = excludedClasses.contains(className)
       val classInfo = infos.classDependencies(className)
-      classInfo
-        .staticDependencies
-        .foreach(staticEdge(_, pathRoot, pathSteps))
+
+
+      if (excluded) {
+        classInfo
+          .staticDependencies
+          .foreach(staticExcludedEdge(_, pathRoot, pathSteps))
+      } else {
+        classInfo
+          .staticDependencies
+          .foreach(staticEdge(_, pathRoot, pathSteps))
+      }
 
       classInfo
         .dynamicDependencies
@@ -109,6 +118,14 @@ private class Tagger(infos: ModuleAnalyzer.DependencyInfo,
       tag(className, pathRoot, pathSteps)
   }
 
+  private def staticExcludedEdge(className: ClassName, pathRoot: ModuleID, pathSteps: List[ClassName]): Unit = {
+    if (excludedClasses.contains(className))
+      tag(className, pathRoot, pathSteps)
+    else
+      // Force a "dynamic edge" from the external module.
+      dynamicEdge(className, pathRoot, pathSteps)
+  }
+
   private def dynamicEdge(className: ClassName, pathRoot: ModuleID, pathSteps: List[ClassName]): Unit =
     tag(className, pathRoot, pathSteps :+ className)
 ```

What it does is preventing forced dynamic edges inside the small split parts of the module.

I suspect this is splitting too much. Naively, we could do fine and coarse grained analysis completely independently, but that can lead to circular module dependencies in the following case (`app` is fine, `lib` is coarse):

```mermaid
graph TD;

subgraph entrypoint
main
end

subgraph coarse
lib.A
lib.C
end

subgraph fine
app.B
end

main --> lib.A --> app.B --> lib.C
```
