### ISSUE TITLE
Duplicate @JSExportTopLevel fails silently

### ISSUE THREAD

**Issue by tballard** [scala-js/scala-js#4836]
I copied and pasted a _**@JSExportTopLevel("Something")**_ line and forgot to rename it to _**"SomethingElse"**_. It punished me by emitting only the generic **_client.fastLinkJS There were linking errors_** which narrows the scope of the error down to, you know, the whole project. I'm confident that can be improved on.

**Comment by gzm0** [comment]
Sorry, I don't know mill at all. But to me, this looks very much like mill simply not displaying the relevant logs.

Have you tried asking on discord?

**Comment by tballard** [comment]
Could be. I'll see what the mill guy thinks. Thanks.

**Comment by tballard** [comment]
For future reference, here's what he thinks:
It seems that there are some problem propagating the logs from the Scala.js toolchain to the Mill client.
As a workaround you can re-run with --no-server and it should show you the full Scala.js linker output

**Comment by sjrd** [comment]
Thanks. In that case it definitely looks like a Mill issue. I'm going to close this ticket, as there's nothing we can do about it here.
