### ISSUE TITLE
Don't emit `unused explicit parameter` warning for facades

### ISSUE THREAD

**Issue by rochala** [scala-js/scala-js#4851]
Scala 3.3.0 is going to ship unused warnings. At the moment it emits them even for manually written facades e.g.

```scala
@JSImport("paper", "Rectangle")
class Rectangle() extends js.Object {
  def this(x1: Double, y1: Double, x2: Double, y2: Double) = this() // unused explicit parameter
}
```

This clutters the reporting, and it should not be emitted in such case, as the arguments are never going to be used.

**Comment by rochala** [comment]
It turned out it is not reporting those warnings on latest compiler.

**Comment by sjrd** [comment]
This was done here: https://github.com/lampepfl/dotty/issues/17240
