### ISSUE TITLE
@JSExportAll should work on enum

### ISSUE THREAD

**Issue by user753** [scala-js/scala-js#4859]
I think It would be great if 
```scala
@JSExportAll
enum FooBar { 
  case Foo(x: Int)
  case Bar(y: Int)
}
```
would work as 
```scala
enum FooBar { 
  @JSExportAll
  case Foo(x: Int)
  @JSExportAll
  case Bar(y: Int)
}
```
Right now I believe `@JSExportAll` on `enum` do nothing.

**Comment by gzm0** [comment]
This is for Scala 3, right? In this case, it needs to go into the dotty repository (https://github.com/lampepfl/dotty).

**Comment by gzm0** [comment]
(sorry I cannot transfer it, I'm not a dotty contributor).

**Comment by user753** [comment]
> This is for Scala 3, right? In this case, it needs to go into the dotty repository (https://github.com/lampepfl/dotty).

Thanks. I did know that. So there are two separate implementations of Scala.js?

**Comment by gzm0** [comment]
>  So there are two separate implementations of Scala.js?

For compilation, yes (the Scala 2 compiler plugin in this repo, the Scala 3 compiler supports Scala.js natively).
For linking, the implementation is in this repo.
