### ISSUE TITLE
UUID comparison doesn't match JVM

### ISSUE THREAD

**Issue by ant8e** [scala-js/scala-js#4882]
The compare implementation on UUID produces incoherent results.

The following test will pass on the JVM but fail on JS

```scala
import munit.FunSuite

import java.util.UUID

class UUIDSuite extends FunSuite {

  test("v0 UUID should be less than v1 UUID") {
    val v0 = UUID.fromString("1ee23e57-7fff-6490-8018-c46dfbd6cdf7")
    val v1 = UUID.fromString("1ee23e57-8001-6ba0-8000-824f2f22b333")

    assertEquals(v0.compareTo(v1), -1)
  }

}

```

Seems that the culprit is the usage of signed integer arithmetic in :  

https://github.com/scala-js/scala-js/blob/0aabf899e71dc4d31b1a7ca7e205ad7f06c5b41b/javalib/src/main/scala/java/util/UUID.scala#L118-L132  

For the example above, i2 is negative for v1. The condition at L122 returns 1. An unsigned comparison should be used instead.

**Comment by ant8e** [comment]
Looks like the JVM does itself not comply with the RFC : https://bugs.openjdk.org/browse/JDK-7025832 (⚠️ this ticket contains copy/pasted openJDK code)

Basically, this is something similar but with signed longs, also broken but in a different way 🤦 

At this point, I'm not sure what would be the correct way forward. Adopting the same behaviour as the JVM ? Becoming  RFC compliant ?

**Comment by sjrd** [comment]
It might be hard to write something bug compatible without looking at the code nor tests of the JDK. 😕

**Comment by gzm0** [comment]
Fair point :-/ We might need to wait until either the JDK doc is updated to specify the behavior according to the bug or the JDK implementation is updated.

**Comment by ant8e** [comment]
I think that the [UUID Javadoc](https://docs.oracle.com/javase/8/docs/api/java/util/UUID.html) gives away enough information to implement a compatible behaviour.
