### ISSUE TITLE
Add `AggregateError`

### ISSUE THREAD

**Issue by armanbilge** [scala-js/scala-js#4888]
Unless there is a reason we can't / shouldn't that I don't realize :) I can open a PR if it's 👍 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError
https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-aggregate-error-objects

**Comment by sjrd** [comment]
It's in the core ES spec, so we should have it, indeed.

I guess it was introduced later than ES 5.1? If yes, we should identify in which version it was added to put the correct ES version badge in the Scaladoc. Example here:
https://github.com/scala-js/scala-js/blob/bc9618cf3c66c09ab3c2d856e35258e6b1aa9bd3/library/src/main/scala/scala/scalajs/js/Promise.scala#L22

**Comment by sjrd** [comment]
Also since it's a new API, it needs a minor version, so the PR should start with a commit like this one:
https://github.com/scala-js/scala-js/commit/2615f3626659eb1526a75f4859da786eab71fdad
to bump the upcoming version number.
