### ISSUE TITLE
NullPointerException not caught by Try under scala.js

### ISSUE THREAD

**Issue by cptwunderlich** [scala-js/scala-js#4914]
I tried updating a dependency of ours and had to also update scala.js from 1.12.0. A test that used to work now fails.

It boils down to `Try(null.toString())` being caught on Scala (jvm) but causing a NullPointerException under scala.js 1.13.2 and 1.14.0.

Here is the PR with the code changes and the error message: https://github.com/cptwunderlich/scala-uri/pull/1

I'll add the error message in-line for convenience:

    [info] - should result in a None *** FAILED ***
    [info]   org.scalajs.linker.runtime.UndefinedBehaviorError: java.lang.NullPointerException
    [info]   at $throwNullPointerException(/home/ben/Projects/scala-uri/js/target/scala-3.3.1/scala-uri-test-fastopt/main.js:70:9)
    [info]   at $n(/home/ben/Projects/scala-uri/js/target/scala-3.3.1/scala-uri-test-fastopt/main.js:74:5)
    [info]   at io.lemonlabs.uri.Uri$.parseTry(/home/ben/Projects/scala-uri/js/target/scala-3.3.1/scala-uri-test-fastopt/main.js:7205:54)
    [info]   at io.lemonlabs.uri.Uri$.parseOption(/home/ben/Projects/scala-uri/js/target/scala-3.3.1/scala-uri-test-fastopt/main.js:7225:18)
    [info]   at io.lemonlabs.uri.ParsingTests.testFun$proxy6$1(/home/ben/Projects/scala-uri/js/target/scala-3.3.1/scala-uri-test-fastopt/main.js:162102:51)
    [info]   at {anonymous}()(/home/ben/Projects/scala-uri/js/target/scala-3.3.1/scala-uri-test-fastopt/main.js:163580:52)
    [info]   at scala.scalajs.runtime.AnonFunction0.apply(/home/ben/Projects/scala-uri/js/target/scala-3.3.1/scala-uri-test-fastopt/main.js:76507:43)
    [info]   at org.scalatest.Transformer.apply(/home/ben/Projects/scala-uri/js/target/scala-3.3.1/scala-uri-test-fastopt/main.js:104706:63)
    [info]   at org.scalatest.Transformer.apply(/home/ben/Projects/scala-uri/js/target/scala-3.3.1/scala-uri-test-fastopt/main.js:104728:15)
    [info]   at org.scalatest.flatspec.AnyFlatSpecLike$$anon$5.apply(/home/ben/Projects/scala-uri/js/target/scala-3.3.1/scala-uri-test-fastopt/main.js:88653:166)
    [info]   ...
    [info]   Cause: java.lang.NullPointerException:
    [info]   at $throwNullPointerException(/home/ben/Projects/scala-uri/js/target/scala-3.3.1/scala-uri-test-fastopt/main.js:70:97)
    [info]   at $n(/home/ben/Projects/scala-uri/js/target/scala-3.3.1/scala-uri-test-fastopt/main.js:74:5)
    [info]   at io.lemonlabs.uri.Uri$.parseTry(/home/ben/Projects/scala-uri/js/target/scala-3.3.1/scala-uri-test-fastopt/main.js:7205:54)
    [info]   at io.lemonlabs.uri.Uri$.parseOption(/home/ben/Projects/scala-uri/js/target/scala-3.3.1/scala-uri-test-fastopt/main.js:7225:18)
    [info]   at io.lemonlabs.uri.ParsingTests.testFun$proxy6$1(/home/ben/Projects/scala-uri/js/target/scala-3.3.1/scala-uri-test-fastopt/main.js:162102:51)
    [info]   at {anonymous}()(/home/ben/Projects/scala-uri/js/target/scala-3.3.1/scala-uri-test-fastopt/main.js:163580:52)
    [info]   at scala.scalajs.runtime.AnonFunction0.apply(/home/ben/Projects/scala-uri/js/target/scala-3.3.1/scala-uri-test-fastopt/main.js:76507:43)
    [info]   at org.scalatest.Transformer.apply(/home/ben/Projects/scala-uri/js/target/scala-3.3.1/scala-uri-test-fastopt/main.js:104706:63)
    [info]   at org.scalatest.Transformer.apply(/home/ben/Projects/scala-uri/js/target/scala-3.3.1/scala-uri-test-fastopt/main.js:104728:15)
    [info]   at org.scalatest.flatspec.AnyFlatSpecLike$$anon$5.apply(/home/ben/Projects/scala-uri/js/target/scala-3.3.1/scala-uri-test-fastopt/main.js:88653:166)
    [info]   ...

**Comment by armanbilge** [comment]
This is expected. This is because `NullPointerException`s are "undefined behavior" on Scala.js so you should not expect them to work behave they do on the JVM.

To learn more about this and why it changed in Scala.js v1.13.0, please read the release notes.
https://www.scala-js.org/news/2023/01/26/announcing-scalajs-1.13.0/#checked-exceptions-for-nullpointerexception
