### ISSUE TITLE
Assertion failed: Trying to move a local VarDef after the super constructor call of a non-native JS class

### ISSUE THREAD

**Issue by OndrejSpanel** [scala-js/scala-js#4929]
When compiling my project using my own facades for magenta.ts and tone.js, I get following Scala.js assertion:

<details><summary>[error]   Trying to move a local VarDef after the super constructor call of a non-native JS class</summary>

<pre>

[error] Error while emitting Main.scala
[error] assertion failed:
[error]   Trying to move a local VarDef after the super constructor call of a non-native JS class at RangePosition(C:\Dev\scalaJsLocalVarDefAssert\src\main\scala\Main.scala, 207, 239, 277)
[error]      while compiling: C:\Dev\scalaJsLocalVarDefAssert\src\main\scala\Main.scala
[error]         during phase: jscode
[error]      library version: version 2.13.12
[error]     compiler version: version 2.13.12
[error]   reconstructed args: -bootclasspath C:\Users\Ondra\AppData\Local\Coursier\Cache\v1\https\repo1.maven.org\maven2\org\scala-lang\scala-library\2.13.12\scala-library-2.13.12.jar -classpath C:\Dev\scalaJsLocalVarDefAssert\target\scala-2.13\classes;C:\Users\Ondra\AppData\Local\Coursier\Cache\v1\https\repo1.maven.org\maven2\org\scala-js\scalajs-library_2.13\1.15.0\scalajs-library_2.13-1.15.0.jar;C:\Users\Ondra\AppData\Local\Coursier\Cache\v1\https\repo1.maven.org\maven2\org\scala-js\scalajs-scalalib_2.13\2.13.12%2B1.15.0\scalajs-scalalib_2.13-2.13.12%2B1.15.0.jar;C:\Users\Ondra\AppData\Local\Coursier\Cache\v1\https\repo1.maven.org\maven2\org\scala-js\scalajs-javalib\1.15.0\scalajs-javalib-1.15.0.jar -Xplugin:C:\Users\Ondra\AppData\Local\Coursier\Cache\v1\https\repo1.maven.org\maven2\org\scala-js\scalajs-compiler_2.13.12\1.15.0\scalajs-compiler_2.13.12-1.15.0.jar
[error]
[error]   last tree to typer: Select(Select(Ident(scala), scalajs), js)
[error]        tree position: line 6 of C:\Dev\scalaJsLocalVarDefAssert\src\main\scala\Main.scala
[error]             tree tpe: scala.scalajs.js.type
[error]               symbol: final package js in package scalajs
[error]    symbol definition: final package js (a ModuleSymbol)
[error]       symbol package: scala.scalajs
[error]        symbol owners: package js
[error]            call site: class Defined in package <empty>
[error]
[error] == Source file context for tree position ==
[error]
[error]      3
[error]      4 @js.native
[error]      5 @JSGlobal("Native")
[error]      6 class Native(output: js.Any = js.native, callbackObject: js.Any = js.native) extends js.Any
[error]      7
[error]      8 class Defined(callbackObject: js.Any) extends Native(callbackObject = callbackObject)
[error]      9
[error] one error found```

</pre>

</details> 

The minimal repro code (using Scala 2.13.18 and Scala.js 1.15.0):

_Note: I get no error when trying this with Scala 3.2.1 and Scala.js 1.15._

```scala
import scala.scalajs.js
import scala.scalajs.js.annotation.JSGlobal

@js.native
@JSGlobal("Native")
class Native(output: js.Any = js.native, callbackObject: js.Any = js.native) extends js.Any

class Defined(callbackObject: js.Any) extends Native(callbackObject = callbackObject)
```

I guess there is probably some error in my code or in the facade, but the assertion is not very helpful.

Online repro: https://scribble.ninja/u/OndrejSpanel/crxnynclgqgzlfdcltblxjpofdqy

**Comment by gzm0** [comment]
I can reproduce this. Thank you for filing this issue.

The issue seems to be that `genPrimaryJSClassCtor` cannot deal with the following tree:

```
List({
  <artifact> val x$1: scala.scalajs.js.Any = callbackObject;
  <artifact> val x$2: scala.scalajs.js.Any = helloworld.this.Native.<init>$default$1();
  Defined.super.<init>(x$2, x$1)
})
```

(it is unwilling to move the defs across the super boundary).

**Comment by gzm0** [comment]
If I disable the assert that moves the VarDefs, it becomes apparent why it is needed (comment mine):

```js
js class helloworld.Defined extends helloworld.Native {
  constructor def constructor(arg: any): any = {
    var callbackObject: any = null;
    val overload: int = {
      callbackObject = arg;
      0
    };
    super((void 0), x$1); // BAD: x$1 is not assigned here!
    val x$1: any = callbackObject;
    /*<skip>*/;
    (void 0)
  }
}
```

**Comment by gzm0** [comment]
I have a WIP fix in https://github.com/gzm0/scala-js/tree/fix-default-js-ctor-params for this. But I feel it needs to be a bit more principled. I'm not sure how much time I'll have to work on this, hence sharing my results so far.

**Comment by sjrd** [comment]
Other data point: whether the parent class is native or not does not matter. It can be a non-native JS class and the same issue appears.
