### ISSUE TITLE
Investigate Fishy Record Names in Optimizer Core

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js#4947]
Follow-up form here:

https://github.com/scala-js/scala-js/blob/244fa5307edd253332b46a97408e198672b387a6/linker/shared/src/main/scala/org/scalajs/linker/frontend/optimizer/OptimizerCore.scala#L1236-L1240

**Comment by gzm0** [comment]
I've been playing around with this and so far, I have not actually managed for the optimizer to produce a Record.

Either, the local def system already resolved everything before even creating a record (this is what happened here: https://github.com/scala-js/scala-js/pull/4946#discussion_r1493338408) or the optimizer cancelled the inlining.

@sjrd how did you determine the piece of code in question is not dead code? I'm starting to suspect that it only triggers for RuntimeLong (where we have more aggressive class inlining policies).

**Comment by sjrd** [comment]
> @sjrd how did you determine the piece of code in question is not dead code? I'm starting to suspect that it only triggers for RuntimeLong (where we have more aggressive class inlining policies).

Replace it by `???` and try `testSuite2_12/Test/fastLinkJS`. It blows up.

In order for a record to be reified, I believe we need at least an if/else where both branches return an instance of the inline class. Or any other merge point. So that's maybe what we need to add to https://github.com/scala-js/scala-js/pull/4946#discussion_r1493338408

**Comment by gzm0** [comment]
I managed to find a problematic program:

```scala
class A {
  private val x: Int = 1
  def foo = x
}

@inline
class B extends A {
  private val x: String = "f"
  def bar = x
}

object HelloWorld {
  @noinline
  def p(x: Any) = println(x)

  @noinline
  def test: Boolean = false

  def main(args: Array[String]): Unit = {
    val b =
      if (test) new B()
      else new B()

    p(b.foo)
    p(b.bar)
  }
}
```

The main method links to:

```js
$c_Lhelloworld_HelloWorld$.prototype.main__AT__V = (function(args) {
  if (this.test__Z()) {
    var b__x = 1;
    var b__x$1 = "f";
  } else {
    var b__x = 1;
    var b__x$1 = "f";
  }
  this.p__O__V(b__x);
  this.p__O__V(b__x); // should be b__x$1
});
```

**Comment by sjrd** [comment]
Nice catch!
