### ISSUE TITLE
Generated modules export unnecessary symbols

### ISSUE THREAD

**Issue by scf37** [scala-js/scala-js#4976]
**Reproduction steps**
1. sbt fastLinkJS

**Expected**
/target/scala-3.4.0/bug1-fastopt/internal-35d0ce2b42710889d7e1a46fac762e09375bf8d5.js contains 6 exports because only 6 exports are actually used by other modules

**Actual**
/target/scala-3.4.0/bug1-fastopt/internal-35d0ce2b42710889d7e1a46fac762e09375bf8d5.js contains 199 exports

**Motivation**
Unused exports add names to global scope hurting optimization by external tools (uglify-js or GCC simple mode)

[bug1.tar.gz](https://github.com/scala-js/scala-js/files/14892697/bug1.tar.gz)

**Comment by gzm0** [comment]
I can see how this might be a problem even with a full blown bundler: The bundler will not make the distinction between internal and public modules, as such, it might leave exports around unnecessarily.

@scf37 could you actually observe unnecessary export statements in bundled output (I'm not sure I'd count Uglfy as a bundler)?

Scala.js does *not* have the goal to generate shipping ready JS code. It is expected that a downstream bundler is run.

More specifically: Scala.js does make no attempt to generate optimal modules. It merely generates modules with sufficiently granular structure so general-purpose JS bundlers can take advantage of it. But it is expected that the module structure is still changed / optimized after Scala.js is run.

**Comment by scf37** [comment]
> could you actually observe unnecessary export statements

Yep. AFAIK GCC simple mode run independently on every file with `--assume_function_wrapper` still produces the best results. Writing simple script to analyze dependencies and comment out unused exports decreases output module size significantly.

No big deal to write such transformer btw but I guess it could be easy fix on your side.

**Comment by gzm0** [comment]
> AFAIK GCC simple mode run independently

Ah, yes. That's expected. I meant if you observe unnecessary exports if you run a bundler that optimizes the whole program / all the modules.

> it could be easy fix on your side.

Not really :-/ Basically, when generating, say a function, in a module, we do not (trivially) have tracking information of whether this function is only used by this module (no export) or also other modules, (must export). Tracking this comes at a cost, especially in an incremental scenario where this information can change non-locally (another module *started* using it, so now it must be exported, even though it didn't change).
