### ISSUE TITLE
Allow variable method name on Selectable.selectDynamic / Selectable.applyDynamic when invoked within macro implementation

### ISSUE THREAD

**Issue by nkgm** [scala-js/scala-js#4996]
I'm working on a mini dsl for inlining operations on literals eg:

```scala
import myInlineOps.*
codeOf {
  inline val ticktock = """
    |tick
    |tock
  """
  inline val clock =
    ticktock.inlined(_.stripMargin.stripTrailing.repeat(3).strip)
}
```
gives:
```scala
{
  inline val ticktock: ("\n        |tick\n        |tock\n      " : String) =
    "\n        |tick\n        |tock\n      "
  inline val clock: ("tick\ntock\ntick\ntock\ntick\ntock" : String) =
    "tick\ntock\ntick\ntock\ntick\ntock"
  ()
}
```

It relies on `applyDynamic` to interpret the `lambda` without the need for quote matchers, ie here's the full user code for the previous example:

```scala
object myInlineOps extends InlineOps {

  extension [V](inline v: V)
    transparent inline def inlined[R](
        inline lambda: InlineValue[V] => InlineValue[R]
    ) = ${ this.inlinedImpl[V, R]('v, 'lambda) }

  extension (v: InlineValue[String])
    def stripMargin = v(_.stripMargin)
    def stripLeading = v(_.stripLeading)
    def stripTrailing = v(_.stripTrailing)
    def strip = v(_.strip)
    def repeat(n: Int) = v(_.repeat(n))
    def size = v(_.size)
}

// on the library side, here's the general shape of `inlineImpl`:
trait InlineOps extends Selectable {
  def inlinedImpl[V: Type, R: Type](
      v: Expr[V],
      lambda: Expr[InlineValue[V] => InlineValue[R]]
  )(using Quotes) = {
    import quotes.reflect.*
    ...
    def invokeDynamic(op: String, args: List[(Class[?], Any)]): Any = {
      this
        .applyDynamic(
          op,
          args.map(_._1)*
        )(args.map(_._2)*)
    }
    ...
    val res: Any = ... (reflection stuff calling invokeDynamic)
    exprFromRes(res).asExprOf[R]
}
```

It works fine on the JVM but fails to compile on SJS.

Any help or workaround would be greatly appreciated!

**Comment by sjrd** [comment]
> It works fine on the JVM but fails to compile on SJS.

Could you elaborate? In what way does it fail, exactly?

**Comment by nkgm** [comment]
```
[error] -- Error: nkgm-predef/shared/src/main/scala-3/nkgm/macros/inlineops/InlineOps.scala:113:10 
[error] 113 |          op,
[error]     |          ^^
[error]     |The method name given to Selectable.selectDynamic or Selectable.applyDynamic must be a literal string. Other uses are not supported in Scala.js.
```
Also tried various workarounds with separate jvm/js sources but no luck.

**Comment by sjrd** [comment]
The error seems legit to me. There is no general-purpose reflection in Scala.js. We have to emit a compile error if you try to use arbitrary names in `applyDynamic`, since that would require general reflection to implement.

**Comment by nkgm** [comment]
I understand, but doesn't the existence of a Quotes implicit provide safety against that? I'm not returning an expression that contains `applyDynamic`, which I would totally get, but merely use it in the macro implementation, which is a compile-time-only operation, so in theory it's not code SJS would ever have to run.

**Comment by sjrd** [comment]
So far, we have no implementation of the compiler that would run on JS, so indeed macro code is never executed on JS. But there is theoretically nothing preventing us from making a version of the compiler that would work on Scala.js. If we allow `applyDynamic` in macro code today, we are shutting ourselves out of ever providing a compiler on JS. I don't think we want that.

**Comment by nkgm** [comment]
100% agreed and that is an amazing prospect btw 💯 

As a workaround with means already available, what if I were to compile a jar with just the offending function and no .sjsir, then add it as a dependency to my SJS project. Would that trick the compiler into moving things along? Or is there something along those lines I could try, that doesn't require me restructuring all my macros?

**Comment by sjrd** [comment]
You can directly use Java reflection APIs in that case. Scala.js will only complain at link-time in that case (and macro code won't be linked, as long as the compiler itself does not *actually* run on JS).

**Comment by nkgm** [comment]
For anyone else interested, this is my working solution:

```scala
lazy val myproj_compiletime = 
  crossProject(JVMPlatform, JSPlatform)
    .in(file("myproj_compiletime"))
    .crossType(CrossType.Pure)
    .jsSettings(
      scalacOptions -= "-scalajs"
    )
```

**Comment by sjrd** [comment]
Er ... don't do that. You're going to break everything down the line.

If you really have to, make it a JVM-only project, and depend on it with `%%` instead of `%%%`.

But don't make a supposedly-Scala.js project (published with a `_sjs1` suffix) that does not actually contain .sjsir. That's twisting the system's arm, and it will get angry at you or at your users.

**Comment by nkgm** [comment]
I'm not super happy about it either, but what if it's part of a multi-module build like so?

```scala
lazy val myproj_compiletime = 
  crossProject(JVMPlatform, JSPlatform)
    .in(file("myproj_compiletime"))
    .crossType(CrossType.Pure)
    .jsSettings(
      scalacOptions -= "-scalajs"
    )

lazy val myproj = 
  crossProject(JVMPlatform, JSPlatform)
    .in(file("myproj"))
    .dependsOn(myproj_compiletime)
```

**Comment by nkgm** [comment]
Found my solution in this [so answer](https://stackoverflow.com/a/47662756) by some clever guy you may have heard of 😄  
```scala
lazy val myproj_compiletime = 
  project
    .in(file("myproj_compiletime"))

lazy val myproj = 
  crossProject(JVMPlatform, JSPlatform)
    .in(file("myproj"))
    .jsConfigure(_.dependsOn(myproj_compiletime))
    .jvmConfigure(_.dependsOn(myproj_compiletime))
```
Thank for helping me flesh this out!
