### ISSUE TITLE
Basic reflection support

### ISSUE THREAD

**Issue by pkolaczk** [scala-js/scala-js#50]
It would be really awesome to have some basic reflection support:
- listing methods / fields
- calling methods / fields
- dynamically creating instances

Even if it worked only for Scala classes, this would be great!
Currently I can call getClass, but it is mostly useless. The same goes about typeTags/classTags introduced in Scala 2.10.

**Comment by andreaTP** [comment]
Cannot figure out why this enhancement was dropped out,
I have a real need for it in the porting of akka to scala.js (mean Props implementation and encapsulation troubles...).
Any chance to have a basic support, at least of instantiating new classes with args from a Class type?

**Comment by sjrd** [comment]
This was dropped because, overall, it would *not* be an enhancement. More features does not always mean better. Reflection impairs things, such as the global optimizations which allows Scala.js to be basically on par with JS.

You can instantiate classes with args from a `Class` value if the class that is referenced has `@JSExport` (or one of its superclasses/traits has `@JSExportDescendantClasses`), like this:
```scala
def instantiate[A](cls: Class[A])(args: Any*): A = {
  val ctor = (js.Dynamic.global /: cls.getName.split("\\.")) {
    (prev, part) => prev.selectDynamic(part)
  }
  js.Dynamic.newInstance(ctor)(args.asInstanceOf[Seq[js.Any]]: _*).asInstanceOf[A]
}
```

**Comment by andreaTP** [comment]
Ok thanks a lot!
Is there any method to inspect also constructors in Dynamic?

**Comment by sjrd** [comment]
No, you cannot inspect anything.

**Comment by sjrd** [comment]
Actually, rather than `js.Dynamic.global`, it would be more correct to use `scala.scalajs.runtime.environmentInfo.exportsNamespace` in the above snippet. Often they coincide, but in theory they could be different.

**Comment by andreaTP** [comment]
So the only chance to have a dynamic builder without knowing parameters is at compile time, maybe a macro can do the job...

p.s. thanks for the precisation

**Comment by gzm0** [comment]
Note that stuff in `scala.scalajs.runtime` is subject to change at any time.
