### ISSUE TITLE
java.lang.Character.codePointAt(java.lang.CharSequence,int)int

### ISSUE THREAD

**Issue by mio-19** [scala-js/scala-js#5010]
I feel like this method could be added to Scala.JS easily.

```
[error] Referring to non-existent method static java.lang.Character.codePointAt(java.lang.CharSequence,int)int

```

Scala.JS version 1.16.0

**Comment by ekrich** [comment]
You may be able to port that one from Scala Native - https://github.com/scala-native/scala-native/blob/main/javalib/src/main/scala/java/lang/Character.scala#L256

**Comment by Nishant9771** [comment]
Overcome from this issues by checking following things :-

1. Ensure that you are using correct Method
2. Check Method name and parameters are correct
3.  And check java library
