### ISSUE TITLE
Implement java.nio.file.Path/Paths so that existing code compiles

### ISSUE THREAD

**Issue by mio-19** [scala-js/scala-js#5011]
I am migrating a project to Scala.JS. I don't expect java.nio.file.Path/Paths to work but I would like to see them compile so that there is less work for migrating

**Comment by gzm0** [comment]
That is against Scala.js policy: if it links, it works.

That being said, it is probably possible to implement parts of the path API while staying in line with the policy. Whether this is a good idea is another question (as in: how useful is the resulting API going to be / how confusing is it going to be)

**Comment by sjrd** [comment]
In any case, this is a huge API. Unless there is some evidence that it *has to* be implemented in core, this would have to be fine outside of core. So I'm going to close this here.

**Comment by gzm0** [comment]
FWIW: IMO the path API itself (the interface) is not very big. And the linker API might benefit from it.

But granted, both of these are marginal arguments.
