### ISSUE TITLE
Linker cannot process code containing non-English identifiers (Windows-only)

### ISSUE THREAD

**Issue by nartamonov** [scala-js/scala-js#5026]
In my project sometimes Russian names are used for class and object identifiers. For example:

```scala
package company.root_module.domain

object НазваниеКлассаНаРусскомЯзыке

object Main {
  def main(args: Array[String]): Unit = {
    println(НазваниеКлассаНаРусскомЯзыке)
  }
}
```
Unfortunately, this code is not processed by the ScalaJS linker if the linker is configured to generate ES modules, breaking them down into small modules within the application package to work effectively with bundlers like Parcel:

```scala
// Emit modules in the most Parcel-friendly way
scalaJSLinkerConfig ~= {
  _.withModuleKind(ModuleKind.ESModule)
    .withModuleSplitStyle(ModuleSplitStyle.SmallModulesFor(List("company.root_module")))
}
```

## How to reproduce

1. Clone repository `https://github.com/nartamonov/reproduce-scalajs-bug`
2. Run `sbt fastLinkJS`

The following error will appear:

```
C:\Dev\repoduce-js-bug\project_files (master -> origin)
λ sbt fastLinkJS
Picked up JAVA_TOOL_OPTIONS: -Dstdout.encoding=UTF-8 -Dstderr.encoding=UTF-8
Picked up JAVA_TOOL_OPTIONS: -Dstdout.encoding=UTF-8 -Dstderr.encoding=UTF-8
[info] welcome to sbt 1.10.1 (Eclipse Adoptium Java 22.0.1)
[info] loading settings for project project_files-build from plugins.sbt ...
[info] loading project definition from C:\Dev\repoduce-js-bug\project_files\project
[info] loading settings for project project_files from build.sbt ...
[info] set current project to root-module (in build file:/C:/Dev/repoduce-js-bug/project_files/)
[info] compiling 1 Scala source to C:\Dev\repoduce-js-bug\project_files\target\scala-2.13\classes ...
[info] Fast optimizing C:\Dev\repoduce-js-bug\project_files\target\scala-2.13\root-module-fastopt
[error] java.nio.file.FileSystemException: C:\Dev\repoduce-js-bug\project_files\target\scala-2.13\root-module-fastopt\.tmp-company.root_module.domain.-u00041dН-u000430а-u000437з-u000432в-u000430а-u00043dн-u000438и-u000435е-u00041aК-u00043bл-u000430а-u000441с-u000441с-u000430а-u00041dН-u000430а-u000420Р-u000443у-u000441с-u000441с-u00043aк-u00043eо-u00043cм-u00042fЯ-u000437з-u00044bы-u00043aк-u000435е$.js3696010906854088543.tmp: Синтаксическая ошибка в имени файла, имени папки или метке тома
[error]         at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
[error]         at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[error]         at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[error]         at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:234)
[error]         at java.base/java.nio.file.Files.newByteChannel(Files.java:379)
[error]         at java.base/java.nio.file.Files.createFile(Files.java:657)
[error]         at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:136)
[error]         at java.base/java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:159)
[error]         at java.base/java.nio.file.Files.createTempFile(Files.java:878)
[error]         at org.scalajs.linker.PathOutputDirectory$Impl.$anonfun$writeAtomic$2(PathOutputDirectory.scala:86)
[error]         at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$1$$anon$2.block(ExecutionContextImpl.scala:75)
[error]         at java.base/java.util.concurrent.ForkJoinPool.compensatedBlock(ForkJoinPool.java:3977)
[error]         at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3959)
[error]         at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$1.blockOn(ExecutionContextImpl.scala:87)
[error]         at scala.concurrent.package$.blocking(package.scala:146)
[error]         at org.scalajs.linker.PathOutputDirectory$Impl.$anonfun$writeAtomic$1(PathOutputDirectory.scala:85)
[error]         at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error]         at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error]         at scala.util.Success.map(Try.scala:213)
[error]         at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error]         at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:42)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:74)
[error]         at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1726)
[error]         at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1717)
[error]         at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(ForkJoinTask.java:1641)
[error]         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
[error]         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
[error]         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
[error]         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
[error]         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
[error] (Compile / fastLinkJS) java.nio.file.FileSystemException: C:\Dev\repoduce-js-bug\project_files\target\scala-2.13\root-module-fastopt\.tmp-company.root_module.domain.-u00041dН-u000430а-u000437з-u000432в-u000430а-u00043dн-u000438и-u000435е-u00041aК-u00043bл-u000430а-u000441с-u000441с-u000430а-u00041dН-u000430а-u000420Р-u000443у-u000441с-u000441с-u00043aк-u00043eо-u00043cм-u00042fЯ-u000437з-u00044bы-u00043aк-u000435е$.js3696010906854088543.tmp: Синтаксическая ошибка в имени файла, имени папки или метке тома
[error] Total time: 3 s, completed 30 авг. 2024 г., 17:29:42
```

The error text is in Russian, as the operating system locale is Russian. Translated as "Syntax error in file name, folder name or volume label".

## Analysis

Presumably, the error occurs due to the way of encoding Unicode identifiers in a language other than English:

```
.tmp-company.root_module.domain.-u00041dН-u000430а-u000437з-u000432в-u000430а-u00043dн-u000438и-u000435е-u00041aК-u00043bл-u000430а-u000441с-u000441с-u000430а-u00041dН-u000430а-u000420Р-u000443у-u000441с-u000441с-u00043aк-u00043eо-u00043cм-u00042fЯ-u000437з-u00044bы-u00043aк-u000435е$.js3696010906854088543.tmp
```

As a result, the file length is 312 characters. I use Windows 10, and it was configured to supports long file paths. However, although the path itself has no length limit, the restriction still has a path component, [usually it cannot exceed 255 characters](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation):

> The Windows API has many functions that also have Unicode versions to permit an extended-length path for a maximum total path length of 32,767 characters. This type of path is composed of components separated by backslashes, each up to the value returned in the lpMaximumComponentLength parameter of the [GetVolumeInformation](https://learn.microsoft.com/en-us/windows/win32/api/FileAPI/nf-fileapi-getvolumeinformationa) function (this value is commonly 255 characters).

There is no way around this limitation, as far as I know. It would be nice to find a way to encode the identifiers in a more economical way.

**Comment by sjrd** [comment]
Thanks for the report and the analysis.

So, if I understand correctly, this is not so much about non-ASCII characters (different from non-English, btw), but rather about very long names produced for modules?

If yes, then we could switch to a scheme with a hash for module names that would be too long. We do that for modules that contain several classes anyway, IIRC.

**Comment by gzm0** [comment]
I was right to be suspicious: Case folding cannot be implemented with case mapping for stability reasons.

Unicode Standard 15.1.0, section 5.18, case mappings, subsection caseless mapping (excerpt):

> R5 From each class, one representative element (a single lowercase letter where possible) is chosen to be the common form.

> For rule R5, it is preferable to choose a single lowercase letter for the common form, but
this is not possible in all instances. For case folding of Cherokee letters, for example, a single uppercase letter must be chosen instead, because the uppercase letters for Cherokee
were encoded in an earlier version of the Unicode Standard, and the lowercase letters were
encoded in a later version. This choice is required to keep case folding stable across Unicode versions.

**Comment by sjrd** [comment]
Is that really an issue for our use case? I guess it could mean in theory that using a different JVM to build a project would result in differently-cased output file names? Is that the only issue?

**Comment by gzm0** [comment]
> Is that the only issue?

No, I don't think so. Notably, case folding is locale independent (modulo Turkish), case mapping isn't.

**Comment by sjrd** [comment]
Even for Turkish (and Lithuanian and Azeri), I believe the `x->toUpper->toLower` is locale-independent. (although neither is independent when *alone*)

**Comment by gzm0** [comment]
Ah, potentially. But I don't think Unicode gives us that guarantee. So we'd rely on how things are right now.

But maybe that's acceptable, especially if we write a test that validates this assumption.

Then again, using toUpper, toLower to chose the representative element would go directly against the standard. IIRC, the standard mentions Cherokee where the representative element is upper case for backwards compatibility reasons.

TBH, between validating all these assumptions and including CaseFolding.txt as a data file to the linker, I'd prefer the latter :-/

**Comment by sjrd** [comment]
Overall I'm not sure this would even since the issue we have here. We could always find a class name that is full of uppercase Cyrillic letters. Those would not case-fold to themselves, and so we'd be back with a super long name.

Although I guess embedding the full case folding database would allow us to assign a "folding index" to every code point. If there are 3 code points that fold to the same one, they would receive indices 0, 1 and 2. Then we can prefix by `-1` instead of `-u` followed by 6 more hex digits.

**Comment by nartamonov** [comment]
> So, if I understand correctly, this is not so much about non-ASCII characters (different from non-English, btw), but rather about very long names produced for modules?

Yes, it's about very long filenames produced by linker. If we reduce the name of the class in my original example, it will be processed without problems:

```scala
package company.root_module.domain

object НазваниеКлассаНа // was previously НазваниеКлассаНаРусскомЯзыке

object Main {
  def main(args: Array[String]): Unit = {
    println(НазваниеКлассаНа)
  }
}
```

**Comment by gzm0** [comment]
> Overall I'm not sure this would even solve the issue we have here. We could always find a class name that is full of uppercase Cyrillic letters. Those would not case-fold to themselves, and so we'd be back with a super long name.

Ah, yes. Absolutely. We'd need the fallback to hash the names either way.

But if we want to provide something a bit better human consumable, then we could do what I'm proposing as an in-between.

> Although I guess embedding the full case folding database would allow us to assign a "folding index" to every code point. If there are 3 code points that fold to the same one, they would receive indices 0, 1 and 2. Then we can prefix by -1 instead of -u followed by 6 more hex digits.

This might be nice, since the names will be much closer to what they were originally.
