### ISSUE TITLE
Wasm backend fails when no modules are defined

### ISSUE THREAD

**Issue by tanishiking** [scala-js/scala-js#5048]
Was: **Improve error message for Wasm backend when no modules are defined**

The current error message in `WebAssemblyLinkerBackend` is not clear for users not very familiar with Scala.js when no modules are defined. It says: `"The WebAssembly backend does not support multiple modules. Found: "`.

https://github.com/scala-js/scala-js/blob/7c95972e30c9897440e4404515d05bf663639daa/linker/shared/src/main/scala/org/scalajs/linker/backend/WebAssemblyLinkerBackend.scala#L69-L72

This message can be confusing and doesn't provide actionable steps to resolve the issue. We may want to update the error message to clearly state the problem and provide guidance on how to fix it: such as

```
The WebAssembly backend requires exactly one module, but no modules were found. You can do either:
1. Set 'scalaJSUseMainModuleInitializer := true', or
2. Annotate exported functions with @JSExportTopLevel"
```

**What JS backend says?**

JS backend says nothing on `fastLinkJS` when no module is found. Instead it prompts users to set `jsEnvInput` manually when no `main` module is found.
Should we keep silence when no modules are found in Wasm backend? I don't think so: when no modules are exported, there's nothing we can do with the Wasm module.

**Comment by sjrd** [comment]
We should indeed do as the JS backend says. If there is no module in the `ModuleSet`, we should emit no file at all (even deleting files that may be present from a previous run), and return an empty `Report`.

There are legitimate cases for calling `fastLinkJS` on projects that have no module initializer nor top-level export. Typically this happens with internal libraries, which have no entry point. If users rely on an aggregate `fastLinkJS` command across all their projects, that will include the libraries.

**Comment by tanishiking** [comment]
Makes sense :+1: Updated the PR not to emit files and delete previous artifacts when no modules are defined
