### ISSUE TITLE
Support java.util.SequencedCollection added in Java 21

### ISSUE THREAD

**Issue by ekrich** [scala-js/scala-js#5069]
See https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/SequencedCollection.html

**Background**
When testing https://github.com/ekrich/sconfig with Java 21 and Scala 3.3.4, it seems the the above class is needed at least for the code in this project.

I was unable to create a reproducer. I was unable to see the problem with Scala 2.12 or 2.13. See the following issue: https://github.com/ekrich/sconfig/issues/398. The issue seems to be the code related to `java.util.ArrayList` which implements `java.util.List` which extends `java.util.SequencedCollection` on Java.

**Comment by sjrd** [comment]
Also: `SequencedMap` and `SequencedSet`.

See [JEP 431](https://openjdk.org/jeps/431) for a comprehensive list of the new interfaces and their retrofitting in the collection hierarchy.

**Comment by sjrd** [comment]
Closing as completed by #5075. Although that PR does not provide any of the *methods* of the new traits, it should be enough to avoid the linking issues mentioned in the issue description.

If the methods are desirable, feel free to open a separate issue.

**Comment by sjrd** [comment]
FTR, my WiP for the methods is available here:
https://github.com/scala-js/scala-js/compare/main...sjrd:scala-js:ju-sequencedcollection

**Comment by ekrich** [comment]
Confirmed that Scala.js 1.18.1 fixes my issue.
