### ISSUE TITLE
`Array.ofDim[Unit](0)` throws `IllegalArgumentException`

### ISSUE THREAD

**Issue by armanbilge** [scala-js/scala-js#5084]
On the JVM it returns an array of `scala.runtime.BoxedUnit`.

**Comment by armanbilge** [comment]
Aha, this is by-design as part of the semantics.

**Comment by sjrd** [comment]
Hum, I'm not so sure. If it's well-defined on the JVM, I believe it should do the same as `new Array[Unit]`, shouldn't it?

**Comment by armanbilge** [comment]
This was Scala 3.

**Comment by sjrd** [comment]
Would you mind opening another issue in the Scala 3 repo?

**Comment by armanbilge** [comment]
- https://github.com/scala/scala3/issues/22226
