### ISSUE TITLE
Custom fingerprint for test framework

### ISSUE THREAD

**Issue by EECOLOR** [scala-js/scala-js#677]
I want to create a test framework that can be run using the Scala.js test infrastructure. In order to not have to depend on the Scala.js library in my test framework (only in the runner) I need to modify the fingerprint.

The fingerprint is hardcoded in [`TestFramework`](https://github.com/scala-js/scala-js/blob/master/sbt-plugin/src/main/scala/scala/scalajs/sbtplugin/testing/TestFramework.scala). It would be nice if we could change the default `scala.scalajs.test.Test` using an sbt setting which should be specified in [`ScalaJSPlugin`](https://github.com/scala-js/scala-js/blob/master/sbt-plugin/src/main/scala/scala/scalajs/sbtplugin/ScalaJSPlugin.scala)

**Comment by gzm0** [comment]
This can all be done now (see #1073).
