### ISSUE TITLE
Including Closure Compiler ready JS source files

### ISSUE THREAD

**Issue by smeagol74** [scala-js/scala-js#761]
If we already compiling scala code to Closure Compiler Advanced ready js files. Why not to allow to include to scalajs project Closure Compiler Advanced ready js files like Closure Library made in JavaScript.

I think this can be done something like this (for example for Google Closure Library):

1. We put Closure Library js source files to the `src/main/javascript` folder. This folder should be included into Closure Compiler include paths, so it's libs could be compiled to resulting javascript.
2. Make some marker trait like this that will be used to mark Closure Compiler ready js libs with sources in `src/main/javascript` folder:
  ```scala
  package scala.scalajs.js
  trait GoogScope extends Object
  ```
3. Prepare wrapper traits that will be used in scala-js code like we have currently for "binary" jQuery lib but with sources like this:
  ```scala
  package goog.text
  
  import scala.scalajs.js.GoogScope

  trait LoremIpsum extends GoogScope {
    def generateParagraph(opt_startWithLorem: Boolean = false): String
    def generateSentence(opt_startWithLorem: Boolean = false): String
  }
  ```
4. Then in code we using that goog.text.LoremIpsum like we can use jQuery for now.
  ```scala
  package com.example

  import goog.text.LoremIpsum

  @JSExport
  object ScalaJSExample {
    @JSExport
    def main() {
      val $playground = $("#playground")
      val li = new LoremIpsum()
      $playground.append(li.generateParagraph(true))
    }
  }
  ```
5. When scalajs compiles the js sources and see import of GoogScope ancestor it should add it's full packaged name to this file with `goog.require('goog.text.LoremIpsum');` so Closure compiler compiled it into the resulting JS file.

I think this feature should be rather easy to implement and it will be very cool, cause it will allow to use Closure Library and also make some new source level reusable JavaScript libs.

I just do not know yet if it will be possible to package such source js libs containing scalajs wrappers and js files in to jars to reuse.

**Comment by coreyauger** [comment]
Hi guys.  I am also running into this issue and had a few questions for the group.  
* A great feature of scalaJS is having a shared `Model` between the client and the server.  If you were to start to remove some of the scala collections from your client code... What is the best way to continue to use the Model in server side code with scala collections?

* The application consists of a framework that allows for `apps` to extend things in iframes.  Is there a way to load one file with common elements/language features for all these apps... and then just load language features above and beyond as extra. 

Our opt file is 2Meg ... 500Kb gz ... so really looking to try and get this down.

Thanks :)

**Comment by sjrd** [comment]
First bullet: use a platform-specific `type` alias. On the JVM, it uses some Scala collection. On JS, it uses something lightweight like `js.Array`.

Second bullet: no, there isn't. See #1787 for background.
