### ISSUE TITLE
build.sbt for tutorial project fails to parse when project is added as sub-project

### ISSUE THREAD

**Issue by johanatan** [scala-js/scala-js#862]
The build of course does work from within the sub-project directory but not from the outer (root) directory. The following is the actual error:

```
$ sbt compile 
[info] Loading project definition from /[redacted]/build.sbt:1: error: not found: value scalaJSSettings
scalaJSSettings
^
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q
```

**Comment by milahu** [comment]
> error: not found: value scalaJSSettings

had the same error when bumping versions .. 
replaced `scalaJSSettings` with `ScalaJSPlugin.projectSettings` as said [here](https://github.com/scala-js/scala-js/issues/1450#issuecomment-69716740)
