### ISSUE TITLE
fastOptJS: chunked output possible?

### ISSUE THREAD

**Issue by jokade** [scala-js/scala-js#947]
Some WebKit based browsers seem to have a problem with large JS files (for instance, JavaFX WebView seems to ignore (?) lines beyond ~44.000 and/or  > ~2MB). Hence it would be useful if fastOptJS could generate chunked output.

**Comment by siriux** [comment]
I've created a similar issue for fullOptJS https://github.com/scala-js/scala-js/issues/1475 Maybe people interested in this issue is also interested on fully optimized chunked output.
