### ISSUE TITLE
ScalaTest/Specs compatibility

### ISSUE THREAD

**Issue by lihaoyi** [scala-js/scala-js#96]
It's trivial to take a pure-Scala project and publish it as a ScalaJS project if it doesnt use any JVM specific things. What's not so trivial is checking that your ScalaJS project actually continues to work when compiled to javascript! For [scalatags](https://github.com/lihaoyi/scalatags), this basically involved copying and pasting the body of the unit tests into a separate project, `optimizeJS`ing, and opening up my `index.html` in chrome to verify manually that it continues to do the right thing.

It would be great if there ScalaJS had support for running ScalaTest/Specs tests in node/rhino. Even if the fancy reflective features don't work, supporting basic things like "do stuff, assert results" should be achievable as long as these libraries don't do any fancy reflective stuff internally (I'm not sure). 

Ideally I'd be able to take my existing test suite and easily run it under ScalaJS to verify that the semantics didn't change in the translation, and that all the properties that hold in the JVM version continue to hold in the ScalaJS version.

**Comment by dbYoung** [comment]
uTest Good, and Try [This](https://github.com/greencatsoft/greenlight) could help you test both, scala and scalajs.

This Framework covers both side. Scala and Scala.js.
